### ISSUE TITLE
FEAT: Including the vulnerability database in the Docker image

### ISSUE THREAD

**Issue by pascalandy** [aquasecurity/trivy#100]
Because at the moment, it takes forever to download these on my local machine.

![Screen Shot 2019-07-25 at 12 16 16 PM](https://user-images.githubusercontent.com/6694151/61890795-44ae0380-aed6-11e9-8645-ad4201fa54d9.jpg)

By having the vulnerability database pre-cached in the Docker image that would make the Docker flow very quick.

**Comment by pascalandy** [comment]
I can see the vuln. DB and other artifacts are taking about 2.3G at this. I feel it would be faster if they are in the docker image itself.

**Comment by knqyf263** [comment]
Now, we provide pre-built DB on [trivy-db](https://github.com/aquasecurity/trivy-db/releases). And, the size of DB is small enough to download it. So, I think we don't have to include DB in the Docker image. If you have other ideas, let me know, please

**Comment by pascalandy** [comment]
Do I understand that the db is now around 9MB to download? If it's the case, it makes perfect sense :)
