### ISSUE TITLE
Fanal caches accumulate endlessly

### ISSUE THREAD

**Issue by v1r7u** [aquasecurity/trivy#101]
We embedded trivy to several our CI pipelines. Each time we build a new version of our product image, we run a security scan against it. 99% of the time, scanned image has a new unique tag:
![image](https://user-images.githubusercontent.com/1583399/61936200-80a3a000-af8c-11e9-9243-8fc94400ffdf.png)

Just after a few weeks of usage, our build agents accumulated 10-20 Gb of cached images.

We're going to run a daily clean-up job to just purge content of `fanal` folder. Is it the only one option? Maybe you can suggest a better way to not blow-up our build-agents disks?

And thank you for your work ;)

**Comment by knqyf263** [comment]
This was fixed by https://github.com/aquasecurity/trivy/pull/398

**Comment by stefannica** [comment]
@knqyf263 Could you please give more details about how #398 helps control the cache size ? The PR doesn't give any information about that. Many thanks in advance !

**Comment by knqyf263** [comment]
@stefannica It doesn't control the cache size, but we migrated the cache to JSON-based. It means cache size is not an issue in most cases, as the cache per image is very small. It could be a problem if you scan millions of images. Are you facing any issues?

**Comment by stefannica** [comment]
@knqyf263 Thanks ! Not facing any issues, my question was purely theoretical.

**Comment by knqyf263** [comment]
You're welcome. If you face an issue regarding cache size, please feel free to raise an issue.
