### ISSUE TITLE
docs | Incorrect ENV variable name mentioned in docs for registry type GCR

### ISSUE THREAD

**Issue by TauseefMalik** [aquasecurity/trivy#1019]
## Description
In Trivy docs, the env var mentioned to be set for scanning image in private Google cloud registry is: 
GOOGLE_APPLICATION_CREDENTIALS
But instead it should be:
DOCKER_CREDENTIAL_GCR_STORE

## What did you expect to happen?
Trivy should take credential store path set in ENV variable GOOGLE_APPLICATION_CREDENTIALS

## What happened instead?
Setting GOOGLE_APPLICATION_CREDENTIALS does not work and Trivy looks into other credentials sources like gcloud store instead if available.

Fix:
Update documentation with correct ENV variable to be set.

**Comment by TauseefMalik** [comment]
@knqyf263 Teppei can you please confirm the fix then I will go ahead and update the docs

**Comment by knqyf263** [comment]
I don't get your point. `GOOGLE_APPLICATION_CREDENTIALS` and `DOCKER_CREDENTIAL_GCR_STORE` look different.

>Setting GOOGLE_APPLICATION_CREDENTIALS does not work and Trivy looks into other credentials sources like gcloud store instead if available.

Could you elaborate on it? What are other credentials?
