### ISSUE TITLE
Add application dependency scanning for Java

### ISSUE THREAD

**Issue by moshloop** [aquasecurity/trivy#103]
Via a pom.xml or build.gradle

**Comment by knqyf263** [comment]
Currently, It's difficult. See https://github.com/knqyf263/trivy/issues/69.

If there is a vulnerability database of Java, I can implement this feature.

**Comment by moshloop** [comment]
Have a look at https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/java/org/owasp/dependencycheck/analyzer/JarAnalyzer.java  that and the associated Dependency code will create CPE's that can be used to check NVD.

**Comment by knqyf263** [comment]
@moshloop Thanks. I know DependencyCheck. The method of DependencyCheck is heuristic. In other words, it makes false positives. I hope that Trivy has no or very few false positives except for bugs. If more algorithmic way is found, I will implement it.

**Comment by moshloop** [comment]
I think a heuristic check is better than no check at all. Asking end-users to use `.trivyignore` to ignore false positives is a good middle ground.

I am assuming from the AGPL license, there is a plan to commercialize this at some point, The vast majority of paying customers (Enterprises) will have Java workloads

**Comment by knqyf263** [comment]
I'm afraid that users will not see results if there are many false positives. I know this heuristic check detects many false positives. So, users will get tired to ignore those vulnerabilities. But, it may be a good middle ground to prepare the option. By default, the scanning of Java is disabled.

**Comment by knqyf263** [comment]
This is closed until we find a good way.
