### ISSUE TITLE
Does TRIVY Support OpenEuler OS?

### ISSUE THREAD

**Issue by Artiver** [aquasecurity/trivy#1031]
As the title says, does TRIVY support openEuler?
link: https://openeuler.org/zh/

**Comment by knqyf263** [comment]
Trivy currently doesn't support openEuler. If someone wants to support it, you have to add a script fetching security advisories of openEuler in vuln-list-update.
https://github.com/aquasecurity/vuln-list-update

Those advisories need to be committed to vuln-list.
https://github.com/aquasecurity/vuln-list

Please feel free to ask any questions!

**Comment by Artiver** [comment]
Thank you for your answer. Trivy is a new tool for me. I want to customize it for scanning specific OS images. Do you have a detailed operation procedure? Thank you. @knqyf263
