### ISSUE TITLE
Better detection of Python and Node packages

### ISSUE THREAD

**Issue by mpoindexter** [aquasecurity/trivy#1039]
It seems like for NPM and Python packages, Trivy takes the approach of looking for lockfiles (package-lock.json, Poetry lock files, etc) vs actual packages installed on the system. This means that if a Python or Node package is installed via other means, or the lockfile is not copied into the image the package will not be detected. I think a better approach is to look for installed packages in the image whether they are referenced in a lockfile or not.

For npm/Node this would involve looking at package.json for each package in a node_modules directory tree to build an inventory of installed packages.

For Python, this would involve looking at `PKG-INFO`/`.dist-info/METADATA` created by egg and wheel packages (related: https://github.com/aquasecurity/trivy/issues/716)

I've implemented these changes in a local fork, and they improve the rate of false negatives significantly for images we build in my company where we use NPM and Python heavily. We have other dependency scanners implemented currently and the detection reports in Trivy were poor for these ecosystems compared to the incumbents.

One obstacle is that once I implemented these changes, libraries installed via OS packages (i.e. Python or Node packages installed via APT/RPM) were detected twice. To combat this, I implemented a deduplication step where if the package file is part of an OS package, the detected library will be suppressed. This is important because sometimes distros backport security fixes and do not change the version number, so the OS package version should take precedence for vulnerability identification.

I have changes to the following projects that implement the changes described above: trivy, fanal, go-dep-parser and go-rpmdb. I'm raising this issue to discuss whether the maintainers think that this change in how packages are detected makes sense. If so, happy to open PRs against all of the projects above with my changes.

**Comment by Gerry9000** [comment]
@mpoindexter It looks like this issue has overlap: https://github.com/aquasecurity/trivy/issues/492
