### ISSUE TITLE
Timeout when downloading large layers

### ISSUE THREAD

**Issue by Phaeilo** [aquasecurity/trivy#104]
**Description**

I want to use trivy to analyze some images that I keep on AWS ECR. This works fine for small images. However, with larger containers, trivy seems to experience a timeout condition if a layer download takes longer than 60 seconds. This results in a very nondescript error message that doesn't point the user to the actual root cause.

**What did you expect to happen?**

Trivy should download the image and perform analysis on it.

**What happened instead?**

After 60 seconds, trivy exits with a very generic error message.

**Output of run with `-debug`:**

(ECR URL masked)
```
% time trivy -d --clear-cache 111111111111.dkr.ecr.xyz.amazonaws.com/foo-bar:latest
2019-07-30T11:14:40.497+0200	DEBUG	cache dir:  /home/philip/.cache/trivy
2019-07-30T11:14:40.497+0200	INFO	Removing image caches...
2019-07-30T11:14:40.504+0200	DEBUG	db path: /home/philip/.cache/trivy/db/trivy.db
2019-07-30T11:14:40.508+0200	INFO	Updating vulnerability database...
2019-07-30T11:14:40.508+0200	DEBUG	git pull
2019-07-30T11:14:41.133+0200	DEBUG	total updated files: 1
2019-07-30T11:14:41.160+0200	DEBUG	Vulnerability type:  [os library]
2019-07-30T11:15:41.161+0200	FATAL	error in image scan:
    github.com/knqyf263/trivy/pkg.Run
        /home/philip/go/src/github.com/knqyf263/trivy/pkg/run.go:166
  - failed to analyze image:
    github.com/knqyf263/trivy/pkg/scanner.ScanImage
        /home/philip/go/src/github.com/knqyf263/trivy/pkg/scanner/scan.go:34
  - failed to extract files:
    github.com/knqyf263/fanal/analyzer.Analyze
        /home/philip/go/pkg/mod/github.com/knqyf263/fanal@v0.0.0-20190706175150-0e953d070757/analyzer/analyzer.go:127
  - Could not extract the archive
    github.com/knqyf263/fanal/extractor.init.ializers
    	/home/philip/go/pkg/mod/github.com/knqyf263/fanal@v0.0.0-20190706175150-0e953d070757/extractor/extractor.go:12
    runtime.main
    	/usr/lib/go/src/runtime/proc.go:188
    runtime.goexit
    	/usr/lib/go/src/runtime/asm_amd64.s:1337
trivy -d --clear-cache   7,72s user 2,40s system 16% cpu 1:00,68 total
```

**Output of `trivy -v`:**

```
trivy version dev
```

It's actually v0.1.4 which I built from source.

**Additional details (base image name, container registry info...):**

There seems to be a default timeout of 60 seconds for HTTP operations. After this timeout is reached, the layer download is stopped. This in turn causes the TAR reader to experience an early EOF, which results in the stacktrace shown above.

While debugging the code, I noticed the environment variable `TRIVY_TIMEOUT_SEC` which can be used to modify this timeout. By setting it to `600s` I was able to successfully fetch the image from ECR and perform analysis.

It is weird that a timeout condition would happen while the client is actively receiving data from the server.

**Comment by joberget** [comment]
I am experiencing this issue as well with timeouts after 60 seconds.

**Comment by knqyf263** [comment]
You can specify `--timeout` option with Triv v0.1.7.
