### ISSUE TITLE
From where does trivy fetch CVE info?

### ISSUE THREAD

**Issue by srtimsina** [aquasecurity/trivy#105]
From where does trivy fetch the vulnerability CVE records. Does it fetch from a single source or multiple sources?

**Comment by FernandoMiguel** [comment]
Multiple

**Comment by srtimsina** [comment]
Hi @FernandoMiguel , Thank you.  Can we know the sources?

**Comment by FernandoMiguel** [comment]
@srtimsina I'm currently mobile, so no.
But try it for yourself

**Comment by srtimsina** [comment]
@FernandoMiguel we didn't find the source mentioned anywhere. That's why I am asking.

**Comment by masahiro331** [comment]
@srtimsina 
OS Packages cves source are here https://github.com/knqyf263/vuln-list-update 
Application Packages cves source are here   https://github.com/knqyf263/trivy/tree/master/pkg/scanner/library
※ libraly/{application}/advisory.go -> dbURL

**Comment by srtimsina** [comment]
@masahiro331 , thank you so much. :)

**Comment by masahiro331** [comment]
👍
