### ISSUE TITLE
Trivy integration with OPA

### ISSUE THREAD

**Issue by SamarSidharth** [aquasecurity/trivy#1061]
I want to know if there is a way to integrate Trivy with OPA in an environment that has no internet access and uses local repositories for hosting images.

Thanks

**Comment by knqyf263** [comment]
You can filter vulnerabilities by OPA even under an air-gapped environment.
https://aquasecurity.github.io/trivy/v0.18.3/examples/filter/#by-open-policy-agent

**Comment by SamarSidharth** [comment]
@knqyf263 thanks for your reply.
I followed the document and was able to get the trivy server running.
Question:
Does trivy client certificate option ?
