### ISSUE TITLE
Having issue while scanning host images from Trivy container

### ISSUE THREAD

**Issue by SamarSidharth** [aquasecurity/trivy#1063]
## Description

I am trying to scan host image using trivy from a container. Following the steps mentioned in the document  for running as docker image https://aquasecurity.github.io/trivy/v0.18.3/installation/

## What did you expect to happen?
Trivy should return the scan results for images present on the host.

## What happened instead?
I get below errors
        * unable to inspect the image (index.docker.io/external/nginx:1.19): Error: No such image: index.docker.io/external/nginx:1.19
        * unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
        * Get "https://index.docker.io/v2/": dial tcp 34.202.206.152:443: connect: no route to host

## Output of run with `-debug`:

```
2021-06-11T17:26:02.455Z        DEBUG   Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2021-06-11T17:26:02.456Z        DEBUG   cache dir:  /root/.cache/trivy
2021-06-11T17:26:02.457Z        DEBUG   DB Schema: 1, Type: 1, UpdatedAt: 2021-06-11 12:04:10.570517612 +0000 UTC, NextUpdate: 2021-06-11 18:04:10.570517312 +0000 UTC, DownloadedAt: 2021-06-11 12:48:54.228898004 +0000 UTC
2021-06-11T17:26:02.457Z        DEBUG   Vulnerability type:  [os library]
2021-06-11T17:26:02.527Z        FATAL   scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:67
  - unable to initialize a scanner:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:157
  - unable to initialize a docker scanner:
    github.com/aquasecurity/trivy/pkg/commands/artifact.dockerScanner
        /home/runner/work/trivy/trivy/pkg/commands/artifact/image.go:29
  - 3 errors occurred:
        * unable to inspect the image (index.docker.io/external/nginx:1.19): Error: No such image: index.docker.io/external/nginx:1.19
        * unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
        * Get "https://index.docker.io/v2/": dial tcp 34.202.206.152:443: connect: no route to host
```

## Output of `trivy -v`:

```
Version: 0.18.3
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2021-06-11 12:04:10.570517612 +0000 UTC
  NextUpdate: 2021-06-11 18:04:10.570517312 +0000 UTC
  DownloadedAt: 2021-06-11 12:48:54.228898004 +0000 UTC

```

## Additional details (base image name, container registry info...):
I am trying to run trivy in a secured environment with no internet access and images are hosted on a local registry.

**Comment by knqyf263** [comment]
Did you mount docker socket?
https://aquasecurity.github.io/trivy/v0.18.3/installation/#docker-hub

**Comment by SamarSidharth** [comment]
@knqyf263 thanks for you reply.
Yes the docker socket was mounted. The problem was resolved by giving root privilege to the trivy container. I got this solution from an old issue.

**Comment by knqyf263** [comment]
Nice. I'll close this issue.
