### ISSUE TITLE
Add OS info to the new JSON schema

### ISSUE THREAD

**Issue by mozillazg** [aquasecurity/trivy#1066]
Add new `OS` field to the new JSON schema to include detected os info from image, like this:

```js
  "OS": {
    "Name": "alpine",
    "Version": "3.7",
    "NoLongerSupported": true
  }
```

before:

```js
{
  "SchemaVersion": 2,
  "TrivyVersion": "0.18",
  "ArtifactID": "sha256:5c534be56eca62e756ef2ef51523feda0f19cd7c15bb0c015e3d6e3ae090bf6e",
  "RepoTags": [
    "alpine:3.7"
  ],
  // ...
}
```

after:

```js
{
  "SchemaVersion": 2,
  "TrivyVersion": "0.18",
  "ArtifactID": "sha256:5c534be56eca62e756ef2ef51523feda0f19cd7c15bb0c015e3d6e3ae090bf6e",
  "RepoTags": [
    "alpine:3.7"
  ],
  "OS": {                        // new field
    "Name": "alpine",
    "Version": "3.7",
    "NoLongerSupported": true
  },
  // ...
}
```

In some cases, we want to get os info of the image when there are CVEs and use it to decide how to fix found CVEs.
At current, we have to parse the value of `Target` field (to get os name and version) and stdout/stderr of trivy command (to get `no longer supported` info)

**Comment by knqyf263** [comment]
Agree. But why is it an array?

**Comment by mozillazg** [comment]
@knqyf263 Because the value of `RepoTags` is an array, I don't why but just follow it. 

BTW, I prefer to use Object instead of Array as type of `RepoTags` / `RepoDigests` and the new `OS` fields.

**Comment by knqyf263** [comment]
I see. Multiple tags can be assigned to a single image such as `alpine:latest` and `alpine:3.14`.

```
$ docker pull alpine:latest
$ docker pull alpine:3.14
$ docker inspect alpine:latest | jq '.[0].RepoTags'
[
  "alpine:3.14",
  "alpine:latest"
]
```

`RepoDigests` is the same

```
$ docker pull alpine:latest
$ docker pull amd64/alpine:latest
$ docker inspect alpine:latest | jq '.[0].RepoDigests'
[
  "amd64/alpine@sha256:1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d",
  "alpine@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0"
]
```

They are all the same images. We can hold only one OS info.

**Comment by mozillazg** [comment]
👌
