### ISSUE TITLE
trivy image failed to download vulnerability TLS handshake timeout

### ISSUE THREAD

**Issue by Liarick** [aquasecurity/trivy#1089]
## Description

Hello,

I m trying to use trivy to scan images on our Centos 7 servers. This servers are behind a corporate proxy on a private network.
I ve tried both ways :
- by using trivy docker image
- by installing trivy

In both case, when I run the trivy command I found that error :
```
2021-06-25T16:41:33.910+0200    INFO    Need to update DB
2021-06-25T16:41:33.911+0200    INFO    Downloading DB...
2021-06-25T16:41:43.916+0200    FATAL   DB error: failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: Get "https://api.github.com/repos/aquasecurity/trivy-db/releases": proxyconnect tcp: net/http: TLS handshake timeout
```

## What did you expect to happen?
No fatal error and a scanning report

## What happened instead?
A FATAL error
```
DB error: failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: Get "https://api.github.com/repos/aquasecurity/trivy-db/releases": proxyconnect tcp: net/http: TLS handshake timeout
```

## Output of run with `-debug`:

```
# trivy --debug image --download-db-only
2021-06-25T17:12:36.186+0200    DEBUG   Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2021-06-25T17:12:36.186+0200    DEBUG   cache dir:  /root/.cache/trivy
2021-06-25T17:12:36.186+0200    INFO    Using your github token
2021-06-25T17:12:36.186+0200    DEBUG   There is no valid metadata file: unable to decode metadata: EOF
2021-06-25T17:12:36.186+0200    INFO    Need to update DB
2021-06-25T17:12:36.186+0200    INFO    Downloading DB...
2021-06-25T17:12:46.193+0200    FATAL   DB error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:60
  - failed to download vulnerability DB:
    github.com/aquasecurity/trivy/pkg/commands/operation.DownloadDB
        /home/runner/work/trivy/trivy/pkg/commands/operation/operation.go:91
  - failed to download vulnerability DB:
    github.com/aquasecurity/trivy/pkg/db.Client.Download
        /home/runner/work/trivy/trivy/pkg/db/db.go:169
  - failed to list releases:
    github.com/aquasecurity/trivy/pkg/github.Client.DownloadDB
        /home/runner/work/trivy/trivy/pkg/github/github.go:89
  - Get "https://api.github.com/repos/aquasecurity/trivy-db/releases": proxyconnect tcp: net/http: TLS handshake timeout
```

## Output of `trivy -v`:

```
# trivy -v
Version: 0.18.3
```

## Additional details (base image name, container registry info...):
- I can access with curl to this url : https://api.github.com/repos/aquasecurity/trivy-db/releases
- I set proxy (http & https) as env variables
- I try to use without github token & with github token (it doesn't change anything)

Let me know for additional informations that I could have forgot.

thanks a lot for your help

**Comment by knqyf263** [comment]
What is your proxy setting? Please make sure your proxy works with `go get` as below.

```
$ http_proxy=http://[your-proxy-server]:[your-proxy-port] go get code.google.com/p/go.crypto/bcrypt

```

**Comment by Liarick** [comment]
Hello,

Thanks for your quick answer. My proxy is working because all other tools that I have installed are working fine with this proxy. I can't make the test with go, because I do not have go installed on my servers.
As an example, when I set my proxy, this command :
```
# curl -H "Authorization: token ploup" https://api.github.com/repos/aquasecurity/trivy-db/releases
```
it returns :
```
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```
(because the token is a fake one, but I have an answer from Github server)

When I unset my proxy settings (with the same command), it returns :
```
curl: (35) Encountered end of file
```
it's a typical return for bad proxy settings.

Let me know for any other informations
