### ISSUE TITLE
Option to download/update database without scan

### ISSUE THREAD

**Issue by miguelbernadi** [aquasecurity/trivy#109]
The initial download of the vulnerability databases takes a long time. In our CI systems, we use ephemereal runners for the tasks, so on the first build of every worker we need to fetch the entire database before being able to do the scan.

I'd like the option of retrieving the database as a stand-alone operation so I can do it in the worker provision step of my CI system, and then the builds would simply update at the time of running, maybe even filtered to only the systems relevant for them.

Would this be acceptable? If it is, I could try to send a PR implementing it after some guidance.

**Comment by dmpe** [comment]
Especially with corporate environment s and proxies this would be very welcome indeed @miguelbernadi

**Comment by knqyf263** [comment]
@miguelbernadi Thank you for the suggestion! I will accept that feature. Welcome PR!

**Comment by miguelbernadi** [comment]
As obvious, I didn't get time to focus on this yet. I'm aiming to get something ready during Hacktoberfest, as I''l get time to devote to PRs and such.

**Comment by miguelbernadi** [comment]
Can you comment on the DB changes for next version (as you mentioned when merging the PR) and how those will affect this feature @knqyf263 ? Just looking to help out and ensure this feature keeps working or improves for the future :)

**Comment by knqyf263** [comment]
This option will be left, but the download of DB will be faster enough with the next version. You may not need `--download-db-only` option.
https://github.com/aquasecurity/trivy/issues/251
