### ISSUE TITLE
Any plans to have this run natively on Windows?

### ISSUE THREAD

**Issue by ericpromislow** [aquasecurity/trivy#1103]
Despite #211 I was able to install this in an Ubuntu/WSL partition and run it there. But would be good to run it from Windows directly.

**Comment by ericpromislow** [comment]
Yeah, just close it. It's fine running this in wsl, gives us more control on its environment.

**Comment by mpgioia** [comment]
@ericpromislow Can you DM me with some help in running this in WSL\Ubuntu please ? I need to do this.

**Comment by itrice** [comment]
> Yeah, just close it. It's fine running this in wsl, gives us more control on its environment.

Hi, dose this can san the image on Windows container?
