### ISSUE TITLE
Failed to download Vulnerability DB: DB File not found

### ISSUE THREAD

**Issue by onlyonepercent** [aquasecurity/trivy#1108]
Im getting "Fatal" error while downloading the Vulnerability DB. This is same when scanning the image too.

It was working till yesterday, but not working since this morning.

I tried to run curl to see the connectivity to github repos for trivy-db , which is working and can see the list of releases.

![trivy_error](https://user-images.githubusercontent.com/77245934/125246029-f0d29a00-e2f9-11eb-9980-f2b13dc57e6c.jpg)

**Comment by knqyf263** [comment]
Hmm. It works in my environment. Does it always fail in your env?

```
$ trivy image --download-db-only                                                                                                  [~/src/github.com/aquasecurity/trivy]
2021-07-12T10:24:53.240+0300    INFO    Need to update DB
2021-07-12T10:24:53.240+0300    INFO    Downloading DB...
22.34 MiB / 22.34 MiB [-------------------------------------------------------------------------------------------------------------------------------------] 100.00% 13.00 MiB p/s 2s
```

**Comment by onlyonepercent** [comment]
@knqyf263 till yesterday it worked fine, today i'm getting the error 

$ trivy image --download-db-only                                          
2021-07-12T07:57:43.038Z        INFO    Need to update DB
2021-07-12T07:57:43.038Z        INFO    Downloading DB...
2021-07-12T07:57:43.232Z        FATAL   DB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found

**Comment by onlyonepercent** [comment]
It seems this is the issue because of our build machines, some security/network restrictions. Our network team is working on it to resolve. Closing the issue. Thanks.
