### ISSUE TITLE
trivy scan fails for terraform code build after image aquasec/trivy:0.18.3

### ISSUE THREAD

**Issue by PrakashFromBunnings** [aquasecurity/trivy#1120]
trivy scan fails for terraform code build after image aquasec/trivy:0.18.3

Trivy scan to work as it was happening and output vulnerability information

Last successful run was with aquasec/trivy:0.18.3, we wanted to see same with latest trivy images,

```
    github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:69
  - image scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:185
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:98
  - analyze error:
    github.com/aquasecurity/fanal/artifact/image.Artifact.Inspect
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/artifact/image/image.go:95
  - failed to analyze layer: sha256:22a285a07059e9e0a2eb147c4207363644c2f68b645b5f095fc30bec3fb532c7 :
    github.com/aquasecurity/fanal/artifact/image.Artifact.inspect.func1
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/artifact/image/image.go:139
  - config scan error:
    github.com/aquasecurity/fanal/artifact/image.Artifact.inspectLayer
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/artifact/image/image.go:207
  - scan terraform error:
    github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/config/scanner/scanner.go:70
  - terraform scan error:
    github.com/aquasecurity/fanal/config/scanner.Scanner.scanTerraformByTFSec
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/config/scanner/scanner.go:117
  - stat /app/modules/Internal.PagerdutyEscalationPolicy/inputs.tf: no such file or directory
2021-07-13T09:26:27.954Z        DEBUG   Analysis error: unable to parse usr/bin/comm: failed to parse usr/bin/comm: EOF
2021-07-13T09:26:27.957Z        DEBUG   Analysis error: unable to parse usr/bin/cpio: failed to parse usr/bin/cpio: EOF
2021-07-13T09:26:27.957Z        DEBUG   Analysis error: unable to parse usr/bin/crontab: failed to parse usr/bin/crontab: EOF
2021-07-13T09:26:27.957Z        DEBUG   Analysis error: unable to parse usr/local/bin/wsdump.py: failed to parse usr/local/bin/wsdump.py: unrecognized executable format
2021-07-13T09:26:27.957Z        DEBUG   Analysis error: unable to parse usr/bin/cmp: failed to parse usr/bin/cmp: EOF
2021-07-13T09:26:27.955Z        DEBUG   Analysis error: unable to parse usr/bin/bzip2: failed to parse usr/bin/bzip2: EOF

```

We are running below command, which uses latest trivy image.
```
 docker run   --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 1 --debug --severity CRITICAL XXXXXXXXXXXXXXXXX.azurecr.io/pagerduty.api.infra:13797

```

https://hub.docker.com/r/aquasec/trivy/tags?page=1&ordering=last_updated

We can see latest trivy images were added in last 1 week.

**Comment by knqyf263** [comment]
Could you confirm that the version you are using is really v0.18.3? Looks like v0.19.1.

**Comment by dietervds** [comment]
Hey 👋  Just confirming that this is an issue on v0.19.1, running in to the same kind of problem:

![Screenshot 2021-07-19 at 12 03 49](https://user-images.githubusercontent.com/1225429/126143429-4ab96c81-08d4-4e6c-8ab2-b7240cb52fea.png)

**Comment by PrakashFromBunnings** [comment]
till v0.18.3  no issues , after this version (aything above this ) has issue.

**Comment by dietervds** [comment]
If it helps: Trivy is trying to stat `/service/service/terraform`, when the actual path is `/service/terraform`. It might simply be a little path parsing problem.

**Comment by dietervds** [comment]
I'm not actually sure my problem is the same as @PrakashFromBunnings :D Apologies for the confusion. Shall I create another issue thread?

**Comment by PrakashFromBunnings** [comment]
@dietervds  True :) , But can you give test with older trivy like 0.18.3 , that might help to confirm if your issue is same as mine or not. if you dont want , that is also fine :)

**Comment by dietervds** [comment]
👍  Trying that right now, but running in to some issues. We install Trivy through the apt repo but that only seems to get me the latest version. Trying installs through wget. Will fiddle with it and let you know what I find.

**Comment by dietervds** [comment]
@PrakashFromBunnings Sorry m8, tried installing `0.18.3` through `wget`, which works fine for `0.19.1` but it gives me a segmentation fault on `0.18.3`. I won't pursue further probably, as I'm really only concerned with the latest version :/ 

![Screenshot 2021-07-19 at 12 43 18](https://user-images.githubusercontent.com/1225429/126148263-177f5652-5422-4053-9822-1f1fd60f0ba8.png)

**Comment by dietervds** [comment]
I was able to run my scan on `0.18.3` and did not encounter my "terraform stat" issue. It seems the two were unrelated, apologies. I'll create a separate thread. 

For anyone coming across the same segfault issue I had when trying to run `0.18.3`: it has something to do with me running that in Docker on my M1 machine. When I ran it on my older Mac the scan with `0.18.3` worked fine. It's probably just a concern on my end, but you never know that you have the same issue if you're reading this.

**Comment by PrakashFromBunnings** [comment]
@dietervds  If your scan is working on 0.18.3 and not working on any latest after that version and see same error as mine. 
I think we are seeing the same issue, unless I didnt understand what you are doing .

**Comment by dietervds** [comment]
@PrakashFromBunnings Sorry, I thought your scan -wasn't- working on `0.18.3`, but when re-reading it all, yep you're right. I'm all over the place today it seems. 

So yes: both our cases started at `0.19.1` and have something to do with terraform :-) 

@knqyf263 Sorry for the confusing thread. Happy to try out stuff locally if I can help in any way. I'll try and get a proper `--debug` run of Trivy with the same issue today. 

P.S.: The segfault issue I got above seems to be intermittent, I'm not sure if it has anything to do with Trivy, or my M1, or Docker, so I'm just removing any mention of it to not confuse things further. `0.18.3` runs fine locally now.

**Comment by dietervds** [comment]
Yep, definitely the same issue :-) Screenshot of a `--debug` run with `0.19.1`:

![Screenshot 2021-07-19 at 15 22 38](https://user-images.githubusercontent.com/1225429/126166495-e3890b39-1ea0-4fa2-bfbd-e99ef74a0315.png)

**Comment by knqyf263** [comment]
v0.19.2 should address this issue. Thanks for your patience.

**Comment by dietervds** [comment]
Tried it just now and works like a charm again. Thanks @knqyf263! 

![Screenshot 2021-07-20 at 13 13 31](https://user-images.githubusercontent.com/1225429/126314768-21ae0cd8-639a-4dc8-8b94-8c6be2e90091.png)
