### ISSUE TITLE
No output when using trivy Conf

### ISSUE THREAD

**Issue by craig-fidus** [aquasecurity/trivy#1122]
I am running the follwoing command: 
`trivy -f json -o /location/output.json config /location/configs/`

But I do not get an output, is this common?

Thanks in advance

**Comment by AndreyLevchenko** [comment]
Hi @craig-fidus 
Could you modify your command a bit:
```trivy config -f json -o /location/output.json /location/configs/```
and check again

Thanks

**Comment by craig-fidus** [comment]
Hi @AndreyLevchenko 

Yup this worked, this is probably the one variation of the command I mustn't have tried.

Thank you!
