### ISSUE TITLE
Debian scan always return empty result, even there have vulns

### ISSUE THREAD

**Issue by SunOfDawn** [aquasecurity/trivy#1125]
## Description
Debian scan always return empty result, even there have vulns
Other effected os：
alpine
amazon

## What did you expect to happen?
Show vulns and fixversion

## What happened instead?
empty result

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
(paste your output here)
```

## bug detail:
example:
pkg/detector/ospkg/debian/debian.go line.83
```go
                   for _, adv := range advisories {
			var fixedVersion version.Version
			fixedVersion, err = version.NewVersion(adv.FixedVersion)

                        // if db has no fixversion, will parse failed and ignored
			if err != nil {
				log.Logger.Debugf("failed to parse Debian package version: %w", err)
				continue
			}
```

**Comment by SunOfDawn** [comment]
Hi @AndreyLevchenko
You can tested trivy with any basic debian images. I think it will show me some known vulns if not install any security update, but i just see no vulns, and some debug log with `failed to parse Debian package version: `. And then i find a point in `pkg/detector/ospkg/debian/debian.go`. If `version.NewVersion` return an err, this advisoriy will be ignored, It wrong, you should check if  `fixVersion` exists.

**Comment by AndreyLevchenko** [comment]
Hi @SunOfDawn 
Sorry for delay and thank you for provided details.  While I understand that some incorrectly formed version could be cause of error I still need to find some real example. Could you point to particular CVE that you think is missed from trivy output.
Also please let us know which version of trivy you are using

Thanks
