### ISSUE TITLE
False positive with qemu-ipxe, qemu-sgabios, qemu-vgabios,qemu-seabios (SLES)

### ISSUE THREAD

**Issue by Samikhed** [aquasecurity/trivy#1140]
Trivy report issue on the sub-component (e.g.  qemu-ipxe  1.0.0+-11.19.2  and suggest fix on the main component of qemu e.g. 4.2.1-11.4.4).  

![qemu_components](https://user-images.githubusercontent.com/87763550/126496078-6bcb69d9-18e3-43c8-a720-109d0efd0d9e.png)

 
If we check the advisory, the corrected versions-release are as follows:
https://lists.suse.com/pipermail/sle-security-updates/2021-June/008949.html

   - SUSE Linux Enterprise Module for Server Applications 15-SP2 (noarch):

      qemu-ipxe-1.0.0+-11.19.2
      qemu-microvm-4.2.1-11.19.2
      qemu-seabios-1.12.1+-11.19.2
      qemu-sgabios-8-11.19.2
      ### qemu-vgabios-1.12.1+-11.19.2

And we have the same installed already:

$ rpm -qi qemu-vgabios-1.12.1+-11.19.2.noarch
Name        : qemu-vgabios
Version     : 1.12.1+
Release     : 11.19.2
Vendor      : SUSE LLC https://www.suse.com/

$ rpm -qi qemu-seabios-1.12.1+-11.19.2.noarch
Name        : qemu-seabios
Version     : 1.12.1+
Release     : 11.19.2
Vendor      : SUSE LLC https://www.suse.com/

$ rpm -qi qemu-sgabios-8-11.19.2.noarch
Name        : qemu-sgabios
Version     : 8
Release     : 11.19.2
Architecture: noarch
Vendor      : SUSE LLC https://www.suse.com/

$ rpm -qi qemu-ipxe-1.0.0+-11.19.2
Name        : qemu-ipxe
Version     : 1.0.0+
Release     : 11.19.2
Vendor      : SUSE LLC https://www.suse.com/

If we look at the Release line  (11.19.2) of above sub-component of qemu,  it is higher than proposed fixed release( 11.4.4)
However,  the Version are different and this may triggered the report.  But it is a false positive as fixed is already there.
 
qemu   **4.2.1**-11.19.2 
qemu-ipxe **1.0.0+**-11.19.2
qemu-seabios-**1.12.1+**-11.19.2
qemu-sgabios-**8**-11.19.2

**Comment by AndreyLevchenko** [comment]
Hi @Samikhed 
Sorry for the delayed response.
Could you help me reproduce it: which tag exactly you are scanning?
