### ISSUE TITLE
Download the latest trivy version

### ISSUE THREAD

**Issue by ayush42** [aquasecurity/trivy#1144]
Hello, 
I have an Ubuntu system in my CI/CD pipeline on which I am trying to install Trivy using the series of following commands. 

`

sudo apt-get install wget apt-transport-https gnupg lsb-release
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
sudo apt-get update
sudo apt-get install trivy
`

When I run the command '**trivy -v**' it shows me '**Version: 0.16.0**'. How can i always download the latest version of Trivy without knowing the exact version number ?

ref : https://aquasecurity.github.io/trivy/v0.19.2/getting-started/installation

**Comment by AndreyLevchenko** [comment]
Hi @ayush42 
The steps you specified above should install the latest version.

**Comment by ayush42** [comment]
@AndreyLevchenko 

I tried both the commands. ("trivy -v" and "which trivy"). The output was as follows :

Version: 0.16.0
/usr/local/bin/trivy

**Comment by ayush42** [comment]
Attaching the installation logs for your reference :


##[section]Starting: Download and install Trivy
------------------------------------------------------------------------------------------------------------------------
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
------------------------------------------------------------------------------------------------------------------------
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /vsts/agent/_work/_temp/<script.sh>
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (1.2.29).
gnupg is already the newest version (1.4.20-1ubuntu3.3).
lsb-release is already the newest version (9.20160110ubuntu0.2).
lsb-release set to manually installed.
wget is already the newest version (1.17.1-1ubuntu1.5).
The following package was automatically installed and is no longer required:
  shtool
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
OK
deb https://aquasecurity.github.io/trivy-repo/deb xenial main
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:6 https://dl.hhvm.com/ubuntu xenial InRelease [3,106 B]
https://aquasecurity.github.io/trivy-repo/deb xenial InRelease [2,337 B]
http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,558 kB]
http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9,827 kB]
http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [2,559 kB]
http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [16.4 kB]
http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [1,544 kB]
https://dl.hhvm.com/ubuntu xenial/main amd64 Packages [2,201 B]
http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [26.2 kB]
http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [10.9 kB]
http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [12.7 kB]
https://apt.llvm.org/xenial llvm-toolchain-xenial-6.0 InRelease [4,236 B]
https://aquasecurity.github.io/trivy-repo/deb xenial/main amd64 Packages [367 B]
http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [2,051 kB]
Get:21 https://apt.llvm.org/xenial llvm-toolchain-xenial-6.0/main amd64 Packages [6,577 B]
Get:22 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [15.9 kB]
Get:23 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [984 kB]
Get:24 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [8,820 B]
Fetched 19.4 MB in 2s (9,558 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  shtool
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  trivy
0 upgraded, 1 newly installed, 0 to remove and 237 not upgraded.
Need to get 9,589 kB of archives.
After this operation, 28.3 MB of additional disk space will be used.
Get:1 https://aquasecurity.github.io/trivy-repo/deb xenial/main amd64 trivy amd64 0.16.0 [9,589 kB]
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 9,589 kB in 0s (11.3 MB/s)
Selecting previously unselected package trivy.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 125153 files and directories currently installed.)
Preparing to unpack .../trivy_0.16.0_amd64.deb ...
Unpacking trivy (0.16.0) ...
Setting up trivy (0.16.0) ...
Version: 0.16.0
/usr/local/bin/trivy
##[section]Finishing: Download and install Trivy

**Comment by ayush42** [comment]
@AndreyLevchenko 

The behavior is still the same. 
It is downloading 0.16.0 version.

`

sudo apt-get install wget apt-transport-https gnupg lsb-release
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
sudo apt-get update
sudo apt-get install trivy
trivy -v
which trivy
`
