### ISSUE TITLE
Jar file also scanned along with Docker image scan

### ISSUE THREAD

**Issue by ayush42** [aquasecurity/trivy#1146]
I have a Docker container which runs a java jar command on bootstrap. 
The jar file is copied inside the docker while building the docker image. 

When I run the foolowing command : 
**trivy image --exit-code 0 --ignore-unfixed --severity MEDIUM <DOCKER_IMAGE_TAG>**

I get the following output : 

[trivy_logs.txt](https://github.com/aquasecurity/trivy/files/6862588/trivy_logs.txt)

I am unable to understand why the jar file is scanned in the image scan process. 

Kindly help.
Thanks & Regards

**Comment by AndreyLevchenko** [comment]
@ayush42 
It's expected behavior since 0.17.0
https://github.com/aquasecurity/trivy/discussions/966

**Comment by ayush42** [comment]
@AndreyLevchenko 
Could you please elaborate on the need for this ? 
What other things are automatically scanned while doing a Trivy image scan ?

**Comment by AndreyLevchenko** [comment]
Basically all data sources specified here 
https://aquasecurity.github.io/trivy/v0.19.2/vulnerability/detection/data-source/
are applied to image to ensure container running with it is secure.
