### ISSUE TITLE
Trivy Config: Scan all levels but only fail if critical is found

### ISSUE THREAD

**Issue by austin-engle** [aquasecurity/trivy#1156]
I wanted to run this for an automation but thought it could be more useful if we were able to see the outputs of all levels but only fail if a particular level showed up. 

Example: I want to see Low and Above but only stop the code if a Critical is found. 

I am using this in a GitHub action using the trivy-action repo and they said it would need to be implemented here first before we could implement it over there.

**Comment by knqyf263** [comment]
We recommend running Trivy twice.
https://aquasecurity.github.io/trivy/v0.19.2/advanced/integrations/travis-ci/

**Comment by austin-engle** [comment]
Closing for semi resolution

**Comment by wiktor-k** [comment]
The link 404s but in case anyone gets here from a search engine (like I did) the solution is to use a custom `trivy.yaml` (via `trivy --config ...`) looking like this:

```yaml
severity:
  - CRITICAL
exit-code: 1
```

For failures but a different file when just a report is necessary.

Hope this helps someone 👋
