### ISSUE TITLE
Trivy image scan timeout

### ISSUE THREAD

**Issue by Partunaks** [aquasecurity/trivy#1157]
## What did you expect to happen?
Properly scan of image

## What happened instead?
Scan error

## Output of run with `-debug`:

Analysis error: unable to parse usr/share/file/magic: failed to parse usr/share/file/magic: EOF Analysis error: unable to parse usr/lib64/.libcrypto.so.1.1.hmac: failed to parse usr/lib64/.libcrypto.30.1.1.hmac: EOF
Analysis error: unable to parse usr/lib64/libelf.so.1: failed to parse usr/lib64/libelf.so.1: EOF
Analysis error: unable to parse usr/lib64/libnssckb1.80: failed to parse usr/lib64/libnssckbi.so: EOF
Analysis error: unable to parse usr/bin/build-classpath: failed to parse usr/bin/build-classpath: unrecognized executable format
Analysis error: unable to parse usr/bin/build-classpath-directory: failed to parse usr/bin/build-classpath-directory: unrecognized executable
Analysis error: unable to parse usr/bin/build-jar-repository: failed to parse usr/bin/build-jar-repository: unrecognized executable formati

Analysis error: unable to parse usr/bin/check-binary-files: failed to parse usr/bin/check-binary-files: unrecognized executable format

Analysis error: unable to parse usr/bin/clean-binary-files: failed to parse usr/bin/clean-binary-files: unrecognized executable format
Analysis error: unable to parse usr/bin/create-jar-links: failed to parse usr/bin/create-jar-links: unrecognized executable format
Analysis error: unable to parse usr/bin/diff-jara: failed to parse usr/bin/diff-jars: unrecognized executable format
 Analysis error: unable to parse usr/bin/find-jar: failed to parse usr/bin/find-par: unrecognized executable format BUG Analysis error: unable to parse usr/bin/rebuild-jar-repository: failed to parse usr/bin/rebuild-jar-repository: unrecognized executable format

 Analysis error: unable to parse usr/bin/shade-jar: failed to parse usr/bin/shade-jar: unrecognized executable format

Analysis error: unable to parse usr/bin/update-gtk-immodules: failed to parse usr/bin/update-gtk-inmodules: unrecognized executable format BUG Parsing Java artifacts... ("file": "usr/lib/java/hawtjni/hawtjni-runtime.jar"))

 Analysis error: unable to parse usr/lib64/libseccomp.so.2: failed to parse usr/lib64/11bseccomp.so.2: EOF

11:30:15 2021-07-28T11:30:07.367+0300 FATAL scan erROR: 11:30:15

github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:69

image scan failed:

github.com/aquasecurity/trivy/pkg/commands/artifact.acan

/home/runner/work/trivy/crivy/pkg/commands/artifact/run.go:185

11:30:15 failed analysis:

github.com/aquasecurity/trivy/pkg/scanner. Scanner. ScanArtifact

/home/runner/work/trivy/trivy/pkg/scanner/scan.go:98

analyze error:

github.com/aquasecurity/fanal/artifact/image.Artifact. Inspect

/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210719144537-c73cie9f21bf/artifact/image/image.go:95

timeout:

github.com/aquasecurity/fanal/artifact/image.Artifact.inspect

/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210719144537-c73cle9f21bf/artifact/image/image.go:159

context deadline exceeded

## Output of `trivy -v`:
Version: 0.19.2

**Comment by knqyf263** [comment]
Try --timeout option
