### ISSUE TITLE
Support Software Bill of Materials (SBOM) scanning

### ISSUE THREAD

**Issue by mrueg** [aquasecurity/trivy#1164]
It would be nice if trivy would support scanning Software Bill of Materials (SBOM) for vulnerabilities, similar to https://github.com/anchore/grype

This would potentially allow faster scanning as one does not need to fetch the whole container image but only the generated SBOM (which can be stored via e.g. https://github.com/sigstore/cosign on the same container registry).

SBOMs can be generated e.g. via https://github.com/spdx/spdx-sbom-generator

**Comment by knqyf263** [comment]
Agree. We want to support it in the near future.

**Comment by cdupuis** [comment]
Another +1 here. This would be super useful.

**Comment by krol3** [comment]
@knqyf263 trivy support SBOM currently, doesn't it? does it generate using image, fs, and rootfs? Could you guide me with this feature? I could improve the documentation about this.

**Comment by knqyf263** [comment]
@krol3 I missed your question. Trivy supports CycloneDX output, but it doesn't support CycloneDX input.

**Comment by Dentrax** [comment]
Hey @knqyf263, can you please tell us what to do to add SBOM scanning feature (like Grype did[^1] in package matcher), so we (@developer-guy) want to work on this.

[^1]: https://github.com/anchore/grype/blob/c9f27163896663bd0139a09db05abd0e9b30e51f/grype/matcher/rpmdb/matcher.go#L27

**Comment by masahiro331** [comment]
https://github.com/aquasecurity/fanal/pull/536
in progress now.

**Comment by knqyf263** [comment]
@Dentrax Thanks for offering! @masahiro331 is working on that now. Please let us ask you if we need your help.
