### ISSUE TITLE
when i use docker run trivy:tag to scan image, how should i get json report?

### ISSUE THREAD

**Issue by logerror** [aquasecurity/trivy#1165]
when i use docker run trivy:tag to scan image, how should i get json report?

**Comment by AndreyLevchenko** [comment]
You will need to configure additional docker volume like:
```docker run --rm -v /var/run/docker.sock:/var/run/docker.sock  -v ~:/root/output   -v /tmp/Caches:/root/.cache/ aquasec/trivy --format json  -o /root/output/python3.4.json  python:3.4-alpine```
to store output file in your home

**Comment by logerror** [comment]
okay, thanks
