### ISSUE TITLE
How can I scan a image without Socket - Directly from Registry

### ISSUE THREAD

**Issue by sscholl** [aquasecurity/trivy#1184]
Hello,

can I run trivy image scan without any docker/podman socket but only a image on a registry (needs authentification)?

```
11:55:52  + trivy --cache-dir ./trivy --skip-update --format template --template @/contrib/junit.tpl --output junit-trivy-report-low.xml --severity UNKNOWN,LOW,MEDIUM myregistry.com/something/imagename:1.0.0
11:55:52  2021-08-17T09:55:52.580Z	[31mFATAL[0m	scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
11:55:52  	* unable to inspect the image (myregistry.com/something/imagename:1.0.0): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
11:55:52  	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
11:55:52  	* GET https://myregistry.com/v2/something/imagename/1.0.0: UNAUTHORIZED: The client does not have permission for manifest; map[manifest:something/imagename/1.0.0/manifest.json]
```

Thanks
Simon

**Comment by knqyf263** [comment]
Yes, you need authentication. `docker login`, or whatever you want.

**Comment by sscholl** [comment]
Hi @knqyf263 I have feeling that you did not understand the problem: If I **dont** have a docker socket. Even tho I did docker login in get the same error message as discribed above...

**Comment by Miladbr** [comment]
@sscholl You should set as environment variables.
```
export TRIVY_USERNAME=username
export TRIVY_PASSWORD=passwd
```

**Comment by sscholl** [comment]
@Miladbr nono, I can not use trivy with podman socket still.

What helped was:

(1) On environment where podman build was executed
`podman save IMAGE -o image.tar"`
(2) transfer image to trivy container
(3) `trivy .....  --input image.tar`
