### ISSUE TITLE
Out of memory error for Trivy in /var/log/messages

### ISSUE THREAD

**Issue by amey-datametica** [aquasecurity/trivy#1190]
Hello Team,

I was able to scan 1 of my workspace in Jenkins using non dockerized Trivy in Cent OS 7.9
I installed trivy using yum install command.
But today when I am trying to execute the same cmdline, I am getting Killed message after few minutes.

1) The command = 
root@prod-jenkins# cd /tmp
root@prod-jenkins# trivy fs --security-checks vuln --output result.json /var/lib/jenkins/workspace/product1_Dev/product1_release_owasp/

Output after 2 minutes = Killed

2) If I tail /var/log/messages = 
Aug 20 15:00:18 prod-jenkins kernel: Out of memory: Killed process 4154115 (trivy) total-vm:9467352kB, anon-rss:8291056kB, file-rss:0kB, shmem-rss:0kB, UID:0
Aug 20 15:00:18 prod-jenkins kernel: oom_reaper: reaped process 4154115 (trivy), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

3) The vm config = 16gb ram/ 4 vCPU's 

4) Trivy version 
[root@prod-jenkins log]# trivy --version
Version: 0.19.2
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2021-08-20 06:04:47.096104462 +0000 UTC
  NextUpdate: 2021-08-20 12:04:47.096104262 +0000 UTC
  DownloadedAt: 2021-08-20 06:52:12.057326871 +0000 UTC

How can I remediate this issue?
After the manual test, I want to add the trivy cmdline in a shell script in my Jenkins job.

Thanks & Regards,
Amey.

**Comment by masahiro331** [comment]
I guess that there is a huge file.
Can I get disk usage for target. 
Please run `du -h $PATH` .

If there is confidential information, please mask it or just give us the total size.

**Comment by amey-datametica** [comment]
Hello @masahiro331 = 
[root@prod-jenkins ~]# du -h $PATH
du: cannot access '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/share/maven/bin:/root/bin': No such file or directory
[root@prod-jenkins ~]# pwd
/root

**Comment by masahiro331** [comment]
@amey-datametica 
Would you like to run this command `du -h /var/lib/jenkins/workspace/product1_Dev/product1_release_owasp/` ?

**Comment by kilin-s** [comment]
Hi. 
I have the same problem with trivy in docker.
vm: 8gb ram, 2 cpu
image 'aquasec/trivy:0.19.2'

`# trivy -d --cache-dir /cache/ fs -f template -t "@/contrib/html.tpl" -o reports/ALL.html --list-all-pkgs ./`

trivy use all memory, cpu and died with error

fatal error: runtime: out of memory

dir size is 6.6 G
