### ISSUE TITLE
where cache remote image?

### ISSUE THREAD

**Issue by JianfuYang** [aquasecurity/trivy#1195]
hello, I use trivy as a scanner for harbor, I find that trivy pull image from reposity once. However,I can not find where the image saved, I only find the message in the fanal.db. More ,the trivy host does not install docker engine.
(1) Does trivy pull image from remote and Save it locally? where ?
(2) how trivy get image layerInfo? it may need a local image? or it just communcate with remote?

**Comment by afdesk** [comment]
Hi @JianfuYang !
Thanks for your interest to `trivy`!

1. Yes, `trivy` pulls a new image but it does cleanup after scanning. 
We don't store image entirely, but we keep OS and package information in cache.

2. If the image name is in Docker Engine, `trivy` inspects the pulled image via Docker API.
If it doesn't exist in local, `trivy` tries to pull the image from the registry.

**Comment by JianfuYang** [comment]
that's ok
