### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/trivy#1200]
Currently trivy can find package-lock.json and process it, looking for vulnerabilities. It would be nice if it could process `pnpm-lock.yaml` files too

**Comment by vafanassieff** [comment]
Agree it would be cool !

**Comment by WorldVirus** [comment]
Hi ! 
I am new in open source. But can I take this issue ?

**Comment by knqyf263** [comment]
Sure. We have to develop a parser for pnpm at first. You can refer to other parsers. Please feel free to ask any questions.
https://github.com/aquasecurity/go-dep-parser/issues/65

**Comment by IkeLutra** [comment]
@WorldVirus How did get on with this? I would be happy to help as well

**Comment by WorldVirus** [comment]
I thought, that somebody already took the issue

**Comment by 06kellyjac** [comment]
cc: @eranshapira
