### ISSUE TITLE
Sort hml report output by Severity

### ISSUE THREAD

**Issue by kb7791** [aquasecurity/trivy#1212]
Is there an option that can be added to html template output to generate sorted by severity (CRITICAL -> LOW) versus Package?

**Comment by AndreyLevchenko** [comment]
Hi @kb7791 
Thank you for the question. Just to clarify: You need something like on picture below? 
![sort-by-severity](https://user-images.githubusercontent.com/353652/132208137-dc97d5cd-14d8-48d1-bafb-c2d0a9f3ca59.png)

**Comment by kb7791** [comment]
Hi @AndreyLevchenko 
Right So I have a report that uses the html.tpl file. But ut seems to be ordered alphabetically by "Package". I was hoping to sort by severity. So all the crtitical, high, etc..... are grouped together first. So having the severity descending from Critical to Low.  Instead of look like the following image where Low and Highs are intertwined because everything seem to be sorted by Package name.

![Screenshot from 2021-09-07 06-41-53](https://user-images.githubusercontent.com/11503681/132355107-f29b2bf1-d41a-491f-97f6-e351acaeda77.png)
