### ISSUE TITLE
Any option available to not to scan local image 

### ISSUE THREAD

**Issue by Tej-Singh-Rana** [aquasecurity/trivy#1216]
Any option available which can ignore during the scan to local image and scan new images. Example -
#### This image is already available in the locally
 trivy image nginx:alpine

As I said earlier, this image is already available locally but I don't want to __Trivy__ to scan this local image and try for a new same image. I would like to try without deleting this local image. 

Thanks,

**Comment by afdesk** [comment]
Hi @Tej-Singh-Rana
we are glad that you're using `trivy`!

you can set an incorrect value (not empty) for `DOCKER_HOST` environment variable and `trivy` will skip accessing to your local Docker Daemon.

Example: 
```sh
DOCKER_HOST=nil trivy image alpine:latest
```

**Comment by Tej-Singh-Rana** [comment]
Thank you!! @afdesk
