### ISSUE TITLE
Is Redis for acceleration or as the backend hosting the vulnerability database

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#1217]
### Discussed in https://github.com/aquasecurity/trivy/discussions/1214

<div type='discussions-op-text'>

<sup>Originally posted by **Vad1mo** September  4, 2021</sup>
This is not clear to me from the documentation. I want to run Trivy in server mode with a read only filesystem. 

There is the option to [use REDIS](https://aquasecurity.github.io/trivy/v0.18.3/examples/cache/) for caching. 

It's not clear to me whether REDIS is there only for caching and the db is still on FS or if Redis can hold the complete vulnerability database so we can run fully stateless in a read-only container.</div>

**Comment by afdesk** [comment]
Hi @Vad1mo !
Thanks for your interest to `trivy`!

Now `trivy` supports REDIS only for caching and the db still stores locally (on FS).
