### ISSUE TITLE
Image scan command out of memory killed 

### ISSUE THREAD

**Issue by dani8art** [aquasecurity/trivy#1242]
## Description

The process running a `trivy image` command is being OOMKilled when the target image has a large size. In our case it is happening with `docker.io/bitnami/pytorch:1.9.0-debian-10-r73`. The real size of the image is 5.7 GB (using `dive`), even though DockerHub reports that the compressed image size is 2.2 Gb.

We were able to reproduce locally by using docker desktop and a limited resources 2CPU, 6Gb RAM.

```
$ docker run -ti --entrypoint /bin/sh  aquasec/trivy
/ # trivy --timeout 300s --format json --output /tmp/puzzle-trivy-5736823038963200902.json docker.io/bitnami/pytorch:1.9.0-debian-10-r73
2021-09-17T09:17:16.970Z	INFO	Need to update DB
2021-09-17T09:17:16.970Z	INFO	Downloading DB...
23.95 MiB / 23.95 MiB [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 5.04 MiB p/s 5s
Killed
/ # echo $?
137
```

If we inspect the resources consumption, we can see how the process gets all the available memory and at the end it is killed

```
$ docker top 5ce52f7ff3db -aux
USER                PID                 %CPU                %MEM                VSZ                 RSS                 TTY                 STAT                START               TIME                COMMAND
root                42562               0.0                 0.0                 1668                712                 ?                   Ss                  09:17               0:00                /bin/sh
root                42762               158                 85.4                7028804             5198928             ?                   Sl+                 09:25               3:47                trivy --timeout 300s --format json --output /tmp/puzzle-trivy-5736823038963200902.json docker.io/bitnami/pytorch:1.9.0-debian-10-r73
```

## What did you expect to happen?

Trivy image scan to run successfully

## What happened instead?

Trivy image scan was killed

## Output of run with `-debug`:

N/A

## Output of `trivy -v`:

```
/ # trivy --version
Version: 0.19.2
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2021-09-17 06:05:20.365155598 +0000 UTC
  NextUpdate: 2021-09-17 12:05:20.365155198 +0000 UTC
  DownloadedAt: 2021-09-17 09:25:17.532882 +0000 UTC
```

**Comment by dani8art** [comment]
I've rerun this on a machine with higher specs and used `/usr/bin/time -v` to get some figures of actual usage. This time the process finished in around 10 minutes, with a peak memory usage of almost 11GB:

```
Maximum resident set size (kbytes): 11238356
```

Also, I've tried different ways of executing it (always previously resetting the cache `trivy image --reset`), and I got some interesting results from executing it without the `--format` and `--output` flags: the execution time got down to 3 minutes only, and peak memory usage was 7GB, which is still high but sensibly lower than the other case.
I hope that helps!

**Comment by afdesk** [comment]
@dani8art thanks for your feedback!
I'm trying to resolve this issue.

**Comment by afdesk** [comment]
the first test (scan a local image) is OK
```
docker pull bitnami/pytorch:1.9.0-debian-10-r73
trivy -d i bitnami/pytorch:1.9.0-debian-10-r73

bitnami/pytorch:1.9.0-debian-10-r73 (debian 10.10)
==================================================
Total: 155 (UNKNOWN: 4, LOW: 22, MEDIUM: 71, HIGH: 50, CRITICAL: 8)
```
The second test (scan a remote image) is broken by fatal error.
```
DOCKER_HOST=nil trivy -d i bitnami/pytorch:1.9.0-debian-10-r73
```

**Comment by dani8art** [comment]
Hi @afdesk, just out of curiosity, why did we fix the issue skipping the scan for large files? could it be skipping important security info? why is the selected size 200MB? 

Thanks in advance!

**Comment by knqyf263** [comment]
From our research, most Go binaries are under 200MB, so it is enough to parse files under 200MB. We may be going to make it possible to specify the size by the user.

**Comment by knqyf263** [comment]
In your case, there are large *.so files in container images. We can skip them and it will not affect the scan result.

**Comment by adapasuresh** [comment]
> From our research, most Go binaries are under 200MB, so it is enough to parse files under 200MB. We may be going to make it possible to specify the size by the user.

Waiting for "Specify the size by the user" which version of trivy

**Comment by knqyf263** [comment]
There is no limitation now. Trivy scans all Go binaries.

**Comment by adapasuresh** [comment]
I am trying to scan my application base images and application custom images, which are above 200MB. Trivy is not able scan the images. I have tried with --timeout 10m and --timeout 15m still its failing.
Example UseCase:
0. Trivy DB - X items - date 30 June, 05:00 pm
1. Scan Base Image like openjdk-11 - OK - date 30 June, 05:00 pm
2. Scan Application fs - OK - date 30 June, 05:10 pm
3. Scan Application Image <MerchantOps-Java-1.0> -OK - date 30 June, 05:15 pm
4. Deployed into production - OK - date 30 June, 05:20 pm

After 12 hours, 
date 01 July 05:01 AM, Trivy DB is updated - OK
5. Now, Assuming I have X+1 items, I want to repeat 1.,2.,3. before going for 4. new production deployment. 
It is an continuous process.....

**Comment by afdesk** [comment]
@adapasuresh maybe is there another issue for your use case?
could you try to skip secret scanning?

```sh
2022-07-01T11:06:18.098+0600	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-01T11:06:18.098+0600	INFO	Please see also https://aquasecurity.github.io/trivy/v0.29.2/docs/secret/scanning/#recommendation for faster secret detection

```
