### ISSUE TITLE
 Trivy's vulnerability db updation frequency

### ISSUE THREAD

**Issue by omkarparkhe** [aquasecurity/trivy#1255]
How often is the Trivy's vulnerability db updated to include the new or latest vulnerabilities and update the changes made to the existing vulnerabilities in the db?

**Comment by knqyf263** [comment]
Every 6 hours for now.
https://github.com/aquasecurity/trivy-db#update-interval

**Comment by omkarparkhe** [comment]
Ok, so does this mean a user's Trivy DB is updated every 6 hours or the vulnerabilities in the db are updated every 6 hours?

**Comment by knqyf263** [comment]
both

**Comment by omkarparkhe** [comment]
ok, thanks 
that's helpful
so another related question - aqua security has a paid-for or enterprise container security scanning solution and an open source (i.e. Trivy). So what are the major differences among the two?

**Comment by krol3** [comment]
Hi @omkarparkhe! This content will help you with the major differences: https://blog.aquasec.com/aqua-vulnerability-scanner-tools

**Comment by omkarparkhe** [comment]
Thanks @krol3

**Comment by michaelact** [comment]
> Every 6 hours for now. https://github.com/aquasecurity/trivy-db#update-interval

Does this mean the database will be updated at 00:00, 06:00, 12:00, 18:00 in a day?

**Comment by knqyf263** [comment]
No, but you can keep watching this workflow.
https://github.com/aquasecurity/trivy-db/actions/workflows/cron.yml
