### ISSUE TITLE
Move build into the container build process

### ISSUE THREAD

**Issue by asohh** [aquasecurity/trivy#1256]
Hey,

I think it would be usefull to change the Dockerfile, that it would build trivy in a container. This would be usefull to simplify building the trivy container in a CI. 

I prepared a Dockerfile that would build trivy in a two step build. First build the trivy binary and then copy it over to the alpine container, that can be used to run trivy. I tested the build using Buildah and scanned some containers to verify that it's working.

Here is a link to my Dockerfile: https://github.com/asohh/trivy/blob/main/Dockerfile

**Comment by knqyf263** [comment]
Trivy uses GoReleaser. No need to compile the Trivy binary in Dockerfile.
https://goreleaser.com/customization/docker/
