### ISSUE TITLE
Issue detecting config files

### ISSUE THREAD

**Issue by craig-fidus** [aquasecurity/trivy#1257]
I am running the command in the example provided:
trivy conf ./configs

I have made the deployment.yaml file and put it in the folder with a dockerfile but it only seems to detect the dockerfile and not the YAML file (shown in image)

I am using Trivy 0.19.2, could you advise?

![TrivyIssue](https://user-images.githubusercontent.com/83061778/135249528-28bd8865-66cc-45b3-9a1e-419020d37908.PNG)

**Comment by 91jme** [comment]
I'm having the same issue. My directory contains a dozen manifests (no Dockerfile) and Trivy doesn't detect any of them.

I'm running the Trivy container (latest) in my case and mounting the directory containing the manifests but see the same issue:

```docker run -it -v C:\my\local\dir\with\manifests\:/var/configs aquasec/trivy config /var/configs```

```2021-09-29T10:39:36.196Z        INFO    Need to update the built-in policies
2021-09-29T10:39:36.196Z        INFO    Downloading the built-in policies...
2021-09-29T10:39:37.214Z        INFO    Detected config files: 0
```

Using busybox I can see the volume mount is valid and contains the manifests

**Comment by czunker** [comment]
Hi @craig-fidus ,

I could reproduce your issue.

I have three files in a directory:
```
ls configs 
deployment-rules.yaml  deployment.yaml  Dockerfile
```

Calling trivy, it only recognizes two of them:
```
trivy conf -s HIGH ./configs 
2021-09-30T14:39:42.476+0200	INFO	Detected config files: 2

Dockerfile (dockerfile)
=======================
Tests: 11 (SUCCESSES: 10, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (HIGH: 1)

....

deployment.yaml (kubernetes)
============================
Tests: 7 (SUCCESSES: 6, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (HIGH: 1)

...
```

The only difference between the two deployment*.yaml files, it the `rules` section you also have in your file:
```
diff configs/deployment* 
30,36d29
< rules:
< - apiGroups:
<         - '*'
<         resources:
<         - '*'
<         verbs:
<         - '*'
```

The `rules` part, makes the yaml file an invalid Kubernetes object, which you can verify with, e.g, kube-linter. Therefore it is ignored by trivy.

**Comment by czunker** [comment]
I used these two files for the test:
https://github.com/aquasecurity/trivy/blob/main/examples/misconf/rule-exception/configs/deployment-deny.yaml
https://github.com/aquasecurity/trivy/blob/main/Dockerfile

For the 3rd file, I added the rules shown in your screenshot to the `deployment.yaml`.

**Comment by dAnjou** [comment]
We have a very similar if not the same issue with version **0.29.2**.
```
% trivy -d config -f json terraform
2022-07-11T18:03:50.178+0200	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-07-11T18:03:50.217+0200	DEBUG	cache dir:  /Users/tw/Library/Caches/trivy
2022-07-11T18:03:50.218+0200	INFO	Misconfiguration scanning is enabled
2022-07-11T18:03:50.340+0200	DEBUG	OS is not detected.
2022-07-11T18:03:50.340+0200	INFO	Detected config files: 0
{
  "SchemaVersion": 2,
  "ArtifactName": "terraform",
  "ArtifactType": "filesystem",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  }
}
```
But there are clearly terraform files in that directory:
```
% tree -P "*.tf" --prune terraform
terraform
├── grafana-dashboards.tf
├── main.tf
├── module
│   ├── deployment.tf
│   ├── prometheus.tf
│   ├── providers.tf
│   ├── secrets.tf
│   ├── service.tf
│   └── variables.tf
└── variables.tf

1 directory, 9 files
```

**Comment by afdesk** [comment]
Hi @dAnjou thanks for the report!

I took a look at your issue.
at first, there were created correct terraform files with your struct (tree), got the same empty result.

then, I replaced `main.tf` with my badly file: https://github.com/afdesk/demo/blob/master/main.tf
`Trivy` caught misconfiguration.
```sh
...
main.tf (terraform)

Tests: 12 (SUCCESSES: 3, FAILURES: 9, EXCEPTIONS: 0)
Failures: 9 (UNKNOWN: 0, LOW: 3, MEDIUM: 0, HIGH: 3, CRITICAL: 3)
``` 

so `Trivy` works correctly here.
but if you want more logs and details, you can create another issue for it.

have a good day!

**Comment by afdesk** [comment]
@dAnjou yes, i agree this message is a bit confusing, 
but this fix may require changes in another package, so I asked to create a new issue.

i can create an issue myself, ok?
