### ISSUE TITLE
no recommendations after scanning 

### ISSUE THREAD

**Issue by SergTik** [aquasecurity/trivy#1263]
As a result of scanning, the lack of a corrected version in the report was repeatedly noticed, but the databases already have a corrected version:

![image](https://user-images.githubusercontent.com/51058936/135627338-ab1a6cae-7e6e-4103-9b01-7f34187ae882.png)
![image](https://user-images.githubusercontent.com/51058936/135628028-77275512-eda7-47ee-9b99-a56d4238892c.png)

Why does it work this way?

**Comment by knqyf263** [comment]
The vendor hasn't provided the patch yet.
