### ISSUE TITLE
Support Additional Report Formats (JUnit, SARIF) with `Trivy config`

### ISSUE THREAD

**Issue by AErmie** [aquasecurity/trivy#1267]
According to the ["misconfiguration" report formats](https://aquasecurity.github.io/trivy/v0.19.2/misconfiguration/options/report/) (aka `trivy config`)...
> Misconfiguration scanning doesn't support default templates such as XML and SARIF for now.

... whereas the `trivy image` scan supports the following [report formats](https://aquasecurity.github.io/trivy/v0.19.2/vulnerability/examples/report/): JUnit XML, HTML, SARIF

It would be appreciated if there was consistency across the different options for using Trivy, and be able to obtain the same report format outputs.

**Comment by krol3** [comment]
Related to using trivy in gh-action. https://github.com/aquasecurity/trivy-action/issues/65

**Comment by knqyf263** [comment]
Thanks. We're working on it here.
https://github.com/aquasecurity/trivy/pull/1437

**Comment by FelipeEmerim** [comment]
I see the PR is specific to Sarif templates. Will Junit also be supported?

**Comment by knqyf263** [comment]
Trivy now supports JUnit and SARIF for misconfiguration.
