### ISSUE TITLE
How to save scan report for scanning images?

### ISSUE THREAD

**Issue by amey-datametica** [aquasecurity/trivy#1278]
Hello Team,

/usr/local/bin/trivy --output result.json image my_image:5005/image-byol:1.0.4.1_4 command shows the scan result on the screen but I am unable to find the result.json file on my server.

How to save the scan report for scanning docker images? Thanks.

**Comment by knqyf263** [comment]
As @bryankmorrow said, you need to specify the format. And they should be passed after `trivy image`.
