### ISSUE TITLE
Support for trivy image scans for other Container Runtime Engines

### ISSUE THREAD

**Issue by vrushalisonwani** [aquasecurity/trivy#1282]
Please provide an option in trivy to add further CRI's.

**Comment by vrushalisonwani** [comment]
[root@node1 vrushali]# trivy image test/duLL1:v1
2021-10-07T02:46:45.061-0400    FATAL   scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
        * unable to inspect the image (test/duLL1:v1): Error: No such image: test/duLL1:v1
        * unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
        * Get "https://test/duLL1/v2": dial tcp: lookup test on A:B:C:D: no such host

Current support is only for docker images.

**Comment by sdlarsen** [comment]
Any chance of getting this re-opened? I'd love to se cri-o support, even help out if someone could point me in the right direction...

**Comment by knqyf263** [comment]
We're [working on containerd](https://github.com/aquasecurity/trivy/issues/851) now. I think we should have a dedicated issue for CRI-O. Could you open a new issue?
