### ISSUE TITLE
Trivy brew install fails on M1 mac

### ISSUE THREAD

**Issue by bermannoah** [aquasecurity/trivy#1296]
## Description
Running `brew install aquasecurity/trivy/trivy` on an M1 mac results in an error.

## What did you expect to happen?
Normal brew install.

## What happened instead?
```
$ brew install aquasecurity/trivy/trivy

==> Tapping aquasecurity/trivy
Cloning into '/opt/homebrew/Library/Taps/aquasecurity/homebrew-trivy'...
remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 213 (delta 33), reused 0 (delta 0), pack-reused 111
Receiving objects: 100% (213/213), 28.56 KiB | 2.60 MiB/s, done.
Resolving deltas: 100% (68/68), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/aquasecurity/homebrew-trivy/trivy.rb
formulae require at least a URL
Error: Cannot tap aquasecurity/trivy: invalid syntax in tap!
```

## Additional details (base image name, container registry info...):

It looks like Stripe ran into the [same thing](https://github.com/stripe/homebrew-stripe-cli/issues/1) and fixed it this way: https://github.com/stripe/stripe-cli/pull/608

**Comment by bermannoah** [comment]
This will also work and is much nicer than my workaround 😄 , I guess I got stuck in "how to do this with brew" mode. (The dockerized version will work as well as the other alternate installs, I just meant if someone really wanted to do this install via brew that would be a way to do it before this gets fixed.)

**Comment by knqyf263** [comment]
Thanks for filing the issue! It is weird as our goreleaser configuration used to support M1 mac as well. Let me take a look.

**Comment by knqyf263** [comment]
v0.20.1 is out! We confirmed `brew install` works on M1 mac.
https://github.com/aquasecurity/homebrew-trivy/blob/ef953a6ec4373e895ed5ec28b2bbb1233a3f0892/trivy.rb#L12-L15
