### ISSUE TITLE
No way to scan single file or single directory?

### ISSUE THREAD

**Issue by jaklan** [aquasecurity/trivy#1302]
Hi all, I wanted to run `trivy` for a simple case - to just scan single Dockerfile. Unfortunately, that doesn't work, because `trivy config` (and `trivy fs` as well) expects dir name, not single files. I tried then to scan the root project directory, but it turned out `trivy` automatically traverse all the sub-directories (in which there were placed other Dockerfiles, which weren't interesting for me in that moment - so the output was really messy). 

Is that mean there's no simple way to just use `trivy` for a) single files b) directories, but not recursively?

**Comment by afdesk** [comment]
Hi @jaklan! thanks for your interest in `trivy`. 
for scanning a single directory i can suggest next way:
```sh
$ trivy fs /path/to/dir/
$ trivy conf /path/to/dir/
```

**Comment by jaklan** [comment]
@afdesk that's not the answer for my question... I pointed directly - `a) single files b) directories, but not recursively`.

**Comment by afdesk** [comment]
@jaklan sorry, but now `trivy` supports only such option.
but we welcome the contribution )

**Comment by knqyf263** [comment]
We are trying to support a single file scanning.
https://github.com/aquasecurity/fanal/pull/356

**Comment by zachary-lavigueure-mark43** [comment]
Hi, can I run and report Trivy issues, against only the Terraform module I modify? Opposed to the entire file/directory?

**Comment by nikpivkin** [comment]
Hi @zachary-lavigueure-mark43 !

There is no such feature at this time. If you use GitHub and upload [SARIF](https://trivy.dev/latest/docs/configuration/reporting/#sarif), GitHub uses fingerprinting to deduplicate results across runs. https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#providing-data-to-track-code-scanning-alerts-across-runs
