### ISSUE TITLE
It would be great to get the output of IAC files in SARIF or add this to the documentation if not suuported

### ISSUE THREAD

**Issue by myvali95** [aquasecurity/trivy#1303]

**Comment by knqyf263** [comment]
We're working on it now.
https://github.com/aquasecurity/trivy/pull/1437

**Comment by abhinavkhanna-sf** [comment]
@knqyf263 When are you planning to release sarif related changes #1437  ?

**Comment by knqyf263** [comment]
We planned to release it at the end of this month, but there may be some delay.

**Comment by knqyf263** [comment]
Forgot to close
