### ISSUE TITLE
trivy scanner on Bitbucket CI/CD pipeline pipes

### ISSUE THREAD

**Issue by kotireddyaluri** [aquasecurity/trivy#1307]
Hi Team,

I came across bitbucket pipes - https://support.atlassian.com/bitbucket-cloud/docs/write-a-pipe-for-bitbucket-pipelines/
I see trivy can be integrated in bitbucket pipelines very well. I have also tried with the sample code, please have a look

cicd pipe plug-in for trivy - https://bitbucket.org/kotireddyaluri/aquasec-trivy-scanner/src/master/

sample test project to run the pipe - https://bitbucket.org/kotireddyaluri/dirsearch_worker/src/main/

bitbucket-pipelines.yaml for sample project - https://bitbucket.org/kotireddyaluri/dirsearch_worker/src/main/bitbucket-pipelines.yml

output for the pipe - 
https://bitbucket.org/kotireddyaluri/dirsearch_worker/addon/pipelines/home#!/results/8

<img width="1788" alt="trivy-bitbucket-pipe" src="https://user-images.githubusercontent.com/4362114/137846002-88b1ecf3-786c-4459-b298-1fa8a45795da.png">

CICD pipe integration is possible even without creating pipe separately, directly we can do like below

on the bitbucket-pipelines.yml

```
- step:
        name: Run Trivy
        image: aquasec/trivy:0.20.1
        script:
          -  trivy image python:3.4-alpine
          -  trivy fs --security-checks vuln,config .
```

**Comment by knqyf263** [comment]
Thanks for sharing! We've added a link to our repository for Bitbucket Pipelines in our doc.
