### ISSUE TITLE
Is CircleCI working correctly now?

### ISSUE THREAD

**Issue by inductor** [aquasecurity/trivy#133]
**Description**

I do not see any status message by CI on your GitHub repository.

**What did you expect to happen?**

CircleCI works on every PR and merge.

**What happened instead?**

CI is not working(?)

**Output of run with `-debug`:**

```
(paste your output here)
```

**Output of `trivy -v`:**

```
(paste your output here)
```

**Additional details (base image name, container registry info...):**

**Comment by knqyf263** [comment]
It seems to work. Where are you talking about?
https://circleci.com/gh/aquasecurity/trivy/228

**Comment by inductor** [comment]
This is how it is now
<img width="769" alt="スクリーンショット 2019-08-25 22 14 00" src="https://user-images.githubusercontent.com/20236173/63650424-b8695780-c785-11e9-9c0a-1dd075fa7c59.png">

This is what I'm expecting
<img width="695" alt="スクリーンショット 2019-08-25 22 14 08" src="https://user-images.githubusercontent.com/20236173/63650425-b99a8480-c785-11e9-8781-c92efe6ca803.png">

**Comment by inductor** [comment]
My point is that CircleCI result should be the part of merge triggers

**Comment by knqyf263** [comment]
I got it.

![image](https://user-images.githubusercontent.com/2253692/63650569-d7b4b480-c786-11e9-804f-9b8a1647d1f1.png)

Currently, it runs builds for pull requests from forks, maybe. Thanks!!!
