### ISSUE TITLE
Built-in SARIF template version

### ISSUE THREAD

**Issue by daiyinong** [aquasecurity/trivy#1337]
https://github.com/aquasecurity/trivy/blob/5dc8cfe55d808c39ae0d785710a7107d6e6de06b/contrib/sarif.tpl#L11

Hello,

Hope things are well - would like to check whether the version referred to in the above line should correspond to the Trivy version (i.e. output of `trivy --version`) or is actually something else. Is it possible to use a templated variable that refers to the Trivy version in this template?
Thanks!

**Comment by knqyf263** [comment]
Looks like it's not correct. It should be fixed in https://github.com/aquasecurity/trivy/pull/1437
