### ISSUE TITLE
integrate with snyk Vulnerability DB (for golang and Java)

### ISSUE THREAD

**Issue by tomoyamachi** [aquasecurity/trivy#134]
Snyk Vulnerability DB has vuln data of go(dep, go.mod) and Java(Maven).

> if you want to consume the DB feed just send a note to contact@snyk.io or through the form on https://snyk.io/partners 
https://github.com/snyk/vulnerabilitydb

**Comment by tomoyamachi** [comment]
https://github.com/aquasecurity/trivy/issues/103
https://github.com/aquasecurity/trivy/issues/69

**Comment by tisc0** [comment]
Hello @knqyf263,
+1 on that request !

**Comment by erzz** [comment]
+1 Here too. Given #103 was closed on "waiting until a good way" doesn't this solve the problem?

**Comment by stayfrostnl** [comment]
+1

**Comment by bitsofinfo** [comment]
+1

**Comment by felix19350** [comment]
+1

**Comment by kennr** [comment]
+1
We'd love a Java vuln feed!

**Comment by knqyf263** [comment]
We are about to support Java. Please look forward to it.
https://github.com/aquasecurity/trivy/pull/837

**Comment by malanvaneck** [comment]
Hi there @knqyf263,
Is this still in the pipeline?

**Comment by knqyf263** [comment]
We're integrating GitLab Advisory Database.
https://gitlab.com/gitlab-org/advisories-community

Let me close this issue.

**Comment by knqyf263** [comment]
v0.17.0 is out.
https://github.com/aquasecurity/trivy/discussions/966
