### ISSUE TITLE
is it possible to scan an image for specific binaries?

### ISSUE THREAD

**Issue by geasus** [aquasecurity/trivy#1341]
We would like to scan an image and see if that image has for example nano, vi, vim or netcat installed, is it possible to scan a image and let it return if any of those binaries has been installed inside the image?

Thank you

**Comment by geasus** [comment]
does anyone have any idea if this would be possible?

**Comment by knqyf263** [comment]
We're sorry to miss it. `trivy image --list-all-pkgs -f json YOUR_IMAGE` will include all the installed packages and you can check it with the result JSON yourself.
