### ISSUE TITLE
`RancherDesktop` support

### ISSUE THREAD

**Issue by sureshg** [aquasecurity/trivy#1342]
[RancherDesktop](https://rancherdesktop.io/) is used by many folks as a replacement for the docker desktop on Mac due to licensing changes. So it would be great to support that also.
```
2021-10-28T16:31:12.592-0700	FATAL	scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
	* unable to inspect the image (gcr.io/distroless/java:base): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: 
```

**Comment by knqyf263** [comment]
Thanks for the request! It makes sense. We may need help.

**Comment by mcdowellstl** [comment]
Any updates on this?

**Comment by knqyf263** [comment]
Rancher Desktop integrates Trivy. You can try that on UI.
https://docs.rancherdesktop.io/getting-started/features/#scanning-images

If you want to scan images from CLI, we still need help.

**Comment by itaysk** [comment]
closing as this has been implemented by Rancher
