### ISSUE TITLE
[helm] Externalize env vars and load them dynamically as per kubernetes standards

### ISSUE THREAD

**Issue by abdennour** [aquasecurity/trivy#1343]
This is about storing environment variables into the right k8s resources : ConfigMap & Secret if it's sensitive data.
Once environment variables are stored in these resources, the pod definition can load these env vars with `spec.containers.envFrom` instead of putting directly the env vars with `spec.containers.env`.

This design has many benefits:

1. Meet k8s standards
2. distributed configuration
3. keeping pod template definition more stable as maintenance of env vars are shifted to configmap or/and secret template definition
4. Help to secure reading env vars with k8s RBAC ( .i.e restrict access to Secret resources, and pod exec verb )

**Comment by krol3** [comment]
PR merged
