### ISSUE TITLE
Possibility to use trivy in server-client mode.

### ISSUE THREAD

**Issue by marcinbojko** [aquasecurity/trivy#135]
I love how trivy integrates with all CI tools, I am using it with gtlab and dind. But, having only small changes in images (like adding app) makes whole scanning process quite long - not to mention about downloading whole db all over again.
Is it possible to use trivy in server-client mode in few scenarios:
- passing image name and highest/lowest level of acceptable threats gets an answer like: true/false
- passing image name getting json/jaml of vulnerabilities found?
- white/blacklist of allowed IP (option)
- basic authorization (option)

**Comment by knqyf263** [comment]
@marcinbojko Thank you for submitting the issue. It's nice idea. I am just considering whether I should implement server-client mode.

BTW, what does the following mean? Using cache, it fetches the difference of DB.
>having only small changes in images (like adding app) makes whole scanning process quite long

**Comment by marcinbojko** [comment]
Thanks.
When using dind - every run is done on new (cleared) state. So there are no lasting layers as your dind get whole image anew.
In images when only last, smallest (app) portion changes it forces dind/trivy to download whole image again + db.

**Comment by michielvermeir** [comment]
Additionally, and I don't know if this fits the original question, having an API that can be invoked instead of shelling out to a process would be real nice. I know there's already the possibility to  It would spur the development of language specific SDKs for Trivy.

**Comment by christian-weiss** [comment]
relates to: https://github.com/aquasecurity/trivy/issues/168

**Comment by knqyf263** [comment]
I forgot to share with you. I've published v0.3.0. You can use client/server mode now!
https://github.com/aquasecurity/trivy/releases/tag/v0.3.0

**Comment by knqyf263** [comment]
Also, you can generate a client by [Twirp](https://github.com/twitchtv/twirp) if you need.
https://github.com/aquasecurity/trivy/tree/master/rpc/detector
