### ISSUE TITLE
error retrieving template from path: open contrib/junit.tpl: no such file or directory

### ISSUE THREAD

**Issue by saivenkateshedem** [aquasecurity/trivy#1353]
## Description

Iam trying to use the xml template for generating output.Getting file not found error.Below is the command

trivy image --format template --template "@contrib/junit.tpl" -o report.xml <image-name>

## Instead it is throwing error
unable to write results: failed to initialize template writer: error retrieving template from path: open contrib/junit.tpl: no such file or directory

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
Version: 0.20.2
Vulnerability DB:
  Type: Full
  Version: 1
  UpdatedAt: 2021-11-02 06:05:35.284812963 +0000 UTC
  NextUpdate: 2021-11-02 12:05:35.284812663 +0000 UTC
  DownloadedAt: 2021-11-02 11:24:02.159383772 +0000 UTC
```

**Comment by afdesk** [comment]
@saivenkateshedem thanks for your interest in `trivy`.

for using templates you need to download this folder: [contrib](https://github.com/aquasecurity/trivy/tree/main/contrib).

it works for me:
```sh
$ ls
contrib 

$ trivy -d image --format template --template "@contrib/junit.tpl" -o report.xml alpine:latest
```

let me know if i can help you.

**Comment by saivenkateshedem** [comment]
Thanks for the solution.It helped

**Comment by geowalrus4gh** [comment]
Could you please document this?

**Comment by davinkevin** [comment]
The `contrib` templates were embedded in the binary, which was really simple to use. This (major) change should be documented 👍 if not fixed I think

**Comment by akzov** [comment]
@davinkevin that appears to be incorrect https://github.com/aquasecurity/trivy/blob/6e7f62d2debbb4acbeb7ad58ecd8ac7379f19e40/docs/docs/configuration/reporting.md?plain=1#L343

**Comment by LanceSandino** [comment]
I'm still running into this bug, do we need to include it in the repo we are scanning?
