### ISSUE TITLE
trivy integration with Aqua SaaS or Aqua Enterprise?

### ISSUE THREAD

**Issue by sawp-d** [aquasecurity/trivy#1354]
Trivy is awesome! Is there any out-of-box/native integration with Aqua SaaS or Enterprise or are they intended to be separate/non-integrated tools? Aqua Enterprise shows a CI/CD Scans panel but I don't see any flags/switches for trivy to push to it. (I do see that there is some integration from Azure DevOps to Aqua, but the source code is private).

**Comment by knqyf263** [comment]
We're working on it hardly. Please look forward to it.
