### ISSUE TITLE
Error: runtime error: invalid memory address or nil pointer dereference on running trivy conf

### ISSUE THREAD

**Issue by pritamstyz4ever** [aquasecurity/trivy#1357]
## Description
Running command `trivy conf --severity HIGH,CRITICAL .` causes nil pointer exception. I am running it against my [repository:](https://github.com/screwdriver-cd/aws-producer-scripts/tree/feat/sd-2560)

## What did you expect to happen?
Should not fail with exception and give the scanning results.

## What happened instead?
Received Error:
`WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: skipped general-secrets-sensitive-in-attribute due to error(s): value is null
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x19f142a]

goroutine 1 [running]:
github.com/aquasecurity/tfsec/internal/app/tfsec/scanner.(*Scanner).scanModule(0xc004db0230, {0x2852b90, 0xc007aeb0c0}, {0xc0007a0000, 0xff, 0xc003351d00})
        /home/runner/go/pkg/mod/github.com/aquasecurity/tfsec@v0.58.11/internal/app/tfsec/scanner/scanner.go:77 +0x36a
github.com/aquasecurity/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan(0xc00a4e9e30, {0xc00adb3c00, 0xe, 0xc00f86e000})
        /home/runner/go/pkg/mod/github.com/aquasecurity/tfsec@v0.58.11/internal/app/tfsec/scanner/scanner.go:55 +0x2b9
github.com/aquasecurity/tfsec/pkg/externalscan.(*ExternalScanner).Scan(0xc00075c5a0)
        /home/runner/go/pkg/mod/github.com/aquasecurity/tfsec@v0.58.11/pkg/externalscan/external_scan.go:60 +0x2c5
github.com/aquasecurity/fanal/config/scanner.Scanner.scanTerraformByTFSec({{0x7ffeefbff964, 0x1}, {0xc0007548e0, 0x2, 0x2}, 0xc000a61a00, 0xc00075c5a0}, {0xc0012ac000, 0x188, 0x200})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211014152324-29fbacfbfca4/config/scanner/scanner.go:113 +0x136
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs({{0x7ffeefbff964, 0x1}, {0xc0007548e0, 0x2, 0x2}, 0xc000a61a00, 0xc00075c5a0}, {0x28478d8, 0xc00004f620}, {0xc0010f8000, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211014152324-29fbacfbfca4/config/scanner/scanner.go:66 +0x26e
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect({{0x7ffeefbff964, 0x1}, {0x3f9d178, 0xc000119050}, {{{0x0, 0x0, 0x0}, {0xc000a61ac0, 0x3, 0x4}}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211014152324-29fbacfbfca4/artifact/local/fs.go:94 +0x330
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0x0, 0x0, 0x0}, {0xc000118f90, ...}, ...})
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:96 +0xce
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{0xc000756040, 0xc00030c5a8, {0x27f0090, 0x6}, 0x0, 0x0, {0xc0003171d0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:214 +0x87e
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout({_, _}, {{0xc000756040, 0xc00030c5a8, {0x27f0090, 0x6}, 0x0, 0x0, {0xc0003171d0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:69 +0x425
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{0xc000756040, 0xc00030c5a8, {0x27f0090, 0x6}, 0x0, 0x0, {0xc0003171d0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:41 +0xc8
github.com/aquasecurity/trivy/pkg/commands/artifact.ConfigRun(0xc000756040)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/config.go:29 +0x266
github.com/urfave/cli/v2.(*Command).Run(0xc0004b7d40, 0xc000661900)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc000103d40, {0x28478a0, 0xc0000400b0}, {0xc00003a0a0, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x4f`

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
Version: 0.20.2
Vulnerability DB:
  Type: Full
  Version: 1
  UpdatedAt: 2021-11-03 18:07:05.68475629 +0000 UTC
  NextUpdate: 2021-11-04 00:07:05.68475599 +0000 UTC
  DownloadedAt: 2021-11-03 18:43:02.128159 +0000 UTC
```

## Additional details (base image name, container registry info...):
Mac OS BigSur

**Comment by knqyf263** [comment]
@afdesk please have a look at this issue.

**Comment by afdesk** [comment]
Hi @pritamstyz4ever! thanks for your report!

i'm trying to reproduce your problem, and can't yet.
I did clone the repository and tried to run trivy with your args - no errors.

maybe there is a problem with your `.terraform` folder...

**Comment by afdesk** [comment]
Hi @pritamstyz4ever, could you show the logs in trivy debug mode:
```sh
trivy -d conf --severity HIGH,CRITICAL .
```

when I scan branch `feat/sd-2560` the result is next:
```sh
$ trivy conf --severity HIGH,CRITICAL .
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/security-group/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
2021-11-14T22:12:47.872+0600	INFO	Detected config files: 4

msk.tf (terraform)
==================
Tests: 15 (SUCCESSES: 15, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (HIGH: 0, CRITICAL: 0)


providers.tf (terraform)
========================
Tests: 3 (SUCCESSES: 3, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (HIGH: 0, CRITICAL: 0)


variables.tf (terraform)
========================
Tests: 28 (SUCCESSES: 28, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (HIGH: 0, CRITICAL: 0)


vpc.tf (terraform)
==================
Tests: 4 (SUCCESSES: 4, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (HIGH: 0, CRITICAL: 0)

```

**Comment by afdesk** [comment]
@pritamstyz4ever also I see that `runtime error` is occuring inside `tfsec/scanner`.

Could you scan your terraform templates with [tfsec](github.com/aquasecurity/tfsec/)?

**Comment by pritamstyz4ever** [comment]
Hi @afdesk, thank you for the response. 
Here's the debug output:

`$ trivy conf --severity HIGH,CRITICAL .
^^/D/s/aws-consumer-scripts >>> trivy -d conf --severity HIGH,CRITICAL .                                                                   (*feat/sd-2558+11) 21:37:14 
2021-11-14T21:37:15.713-0500    DEBUG   Severities: HIGH,CRITICAL
2021-11-14T21:37:15.762-0500    DEBUG   cache dir:  /Users/ppaul/Library/Caches/trivy
2021-11-14T21:37:15.762-0500    DEBUG   Vulnerability type:  []
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: skipped general-secrets-sensitive-in-attribute due to error(s): value is null
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x19f142a]

goroutine 1 [running]:
github.com/aquasecurity/tfsec/internal/app/tfsec/scanner.(*Scanner).scanModule(0xc00d4d04b0, {0x2852b90, 0xc0059a43c0}, {0xc000a14000, 0xff, 0x102f72c})
        /home/runner/go/pkg/mod/github.com/aquasecurity/tfsec@v0.58.11/internal/app/tfsec/scanner/scanner.go:77 +0x36a
github.com/aquasecurity/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan(0xc00aa23e30, {0xc008b16600, 0xe, 0xc00df22000})
        /home/runner/go/pkg/mod/github.com/aquasecurity/tfsec@v0.58.11/internal/app/tfsec/scanner/scanner.go:55 +0x2b9
github.com/aquasecurity/tfsec/pkg/externalscan.(*ExternalScanner).Scan(0xc000916b10)
        /home/runner/go/pkg/mod/github.com/aquasecurity/tfsec@v0.58.11/pkg/externalscan/external_scan.go:60 +0x2c5
github.com/aquasecurity/fanal/config/scanner.Scanner.scanTerraformByTFSec({{0x7ffeefbff967, 0x1}, {0xc00094e020, 0x2, 0x2}, 0xc000ce3200, 0xc000916b10}, {0xc000ac8000, 0x188, 0x200})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211014152324-29fbacfbfca4/config/scanner/scanner.go:113 +0x136
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs({{0x7ffeefbff967, 0x1}, {0xc00094e020, 0x2, 0x2}, 0xc000ce3200, 0xc000916b10}, {0x28478d8, 0xc0006793e0}, {0xc000d04000, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211014152324-29fbacfbfca4/config/scanner/scanner.go:66 +0x26e
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect({{0x7ffeefbff967, 0x1}, {0x8db12b0, 0xc0009039b0}, {{{0x0, 0x0, 0x0}, {0xc000ce3240, 0x3, 0x4}}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211014152324-29fbacfbfca4/artifact/local/fs.go:94 +0x330
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0x0, 0x0, 0x0}, {0xc0009038e0, ...}, ...})
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:96 +0xce
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{0xc0008d8040, 0xc0008125c8, {0x27f0090, 0x6}, 0x0, 0x1, {0xc0001229f0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:214 +0x87e
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout({_, _}, {{0xc0008d8040, 0xc0008125c8, {0x27f0090, 0x6}, 0x0, 0x1, {0xc0001229f0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:69 +0x425
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{0xc0008d8040, 0xc0008125c8, {0x27f0090, 0x6}, 0x0, 0x1, {0xc0001229f0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:41 +0xc8
github.com/aquasecurity/trivy/pkg/commands/artifact.ConfigRun(0xc0008d8040)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/config.go:29 +0x266
github.com/urfave/cli/v2.(*Command).Run(0xc0008857a0, 0xc000883900)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc000549ba0, {0x28478a0, 0xc00019c008}, {0xc000196120, 0x6, 0x6})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x4f`

**Comment by pritamstyz4ever** [comment]
Here's the output of `tfsec .`

`tfsec .                                                                                                    (*feat/sd-2558+11) 21:51:35 
Warning: A tfvars file was found but not automatically used. Did you mean to specify the --tfvars-file flag?

  Result 1

  [aws-lambda-enable-tracing][LOW] Resource 'module.lambda_function:aws_lambda_function.this[0]' uses default value for tracing_config.mode
  /Users/ppaul/Documents/screwdriver-cd/aws-consumer-scripts/.terraform/modules/lambda_function/main.tf:19-97


      16 | 
      17 | }
      18 | 
      19 | resource "aws_lambda_function" "this" {
      20 |   count = var.create && var.create_function && !var.create_layer ? 1 : 0
      21 | 
      22 |   function_name                  = var.function_name
      23 |   description                    = var.description
      24 |   role                           = var.create_role ? aws_iam_role.lambda[0].arn : var.lambda_role
      25 |   handler                        = var.package_type != "Zip" ? null : var.handler
      26 |   memory_size                    = var.memory_size
      27 |   reserved_concurrent_executions = var.reserved_concurrent_executions
      28 |   runtime                        = var.package_type != "Zip" ? null : var.runtime
      29 |   layers                         = var.layers
      30 |   timeout                        = var.lambda_at_edge ? min(var.timeout, 5) : var.timeout
      31 |   publish                        = var.lambda_at_edge ? true : var.publish
      32 |   kms_key_arn                    = var.kms_key_arn
      33 |   image_uri                      = var.image_uri
      34 |   package_type                   = var.package_type
      35 |   architectures                  = var.architectures
      36 | 
      37 |   filename         = local.filename
      38 |   source_code_hash = var.ignore_source_code_hash ? null : (local.filename == null ? false : fileexists(local.filename)) && !local.was_missing ? filebase64sha256(local.filename) : null
      39 | 
      40 |   s3_bucket         = local.s3_bucket
      41 |   s3_key            = local.s3_key
      42 |   s3_object_version = local.s3_object_version
      43 | 
      44 |   dynamic "image_config" {
      45 |     for_each = length(var.image_config_entry_point) > 0 || length(var.image_config_command) > 0 || var.image_config_working_directory != null ? [true] : []
      46 |     content {
      47 |       entry_point       = var.image_config_entry_point
      48 |       command           = var.image_config_command
      49 |       working_directory = var.image_config_working_directory
      50 |     }
      51 |   }
      52 | 
      53 |   dynamic "environment" {
      54 |     for_each = length(keys(var.environment_variables)) == 0 ? [] : [true]
      55 |     content {
      56 |       variables = var.environment_variables
      57 |     }
      58 |   }
      59 | 
      60 |   dynamic "dead_letter_config" {
      61 |     for_each = var.dead_letter_target_arn == null ? [] : [true]
      62 |     content {
      63 |       target_arn = var.dead_letter_target_arn
      64 |     }
      65 |   }
      66 | 
      67 |   dynamic "tracing_config" {
      68 |     for_each = var.tracing_mode == null ? [] : [true]
      69 |     content {
      70 |       mode = var.tracing_mode
      71 |     }
      72 |   }
      73 | 
      74 |   dynamic "vpc_config" {
      75 |     for_each = var.vpc_subnet_ids != null && var.vpc_security_group_ids != null ? [true] : []
      76 |     content {
      77 |       security_group_ids = var.vpc_security_group_ids
      78 |       subnet_ids         = var.vpc_subnet_ids
      79 |     }
      80 |   }
      81 | 
      82 |   dynamic "file_system_config" {
      83 |     for_each = var.file_system_arn != null && var.file_system_local_mount_path != null ? [true] : []
      84 |     content {
      85 |       local_mount_path = var.file_system_local_mount_path
      86 |       arn              = var.file_system_arn
      87 |     }
      88 |   }
      89 | 
      90 |   tags = var.tags
      91 | 
      92 |   # Depending on the log group is necessary to allow Terraform to create the log group before AWS can.
      93 |   # When a lambda function is invoked, AWS creates the log group automatically if it doesn't exist yet.
      94 |   # Without the dependency, this can result in a race condition if the lambda function is invoked before
      95 |   # Terraform can create the log group.
      96 |   depends_on = [null_resource.archive, aws_s3_bucket_object.lambda_package, aws_cloudwatch_log_group.lambda]
      97 | }
      98 | 
      99 | resource "aws_lambda_layer_version" "this" {
     100 |   count = var.create && var.create_layer ? 1 : 0

  Impact:     Without full tracing enabled, it is difficult to trace the flow of logs
  Resolution: Enable tracing

  More Info:
  - https://tfsec.dev/docs/aws/lambda/enable-tracing#aws/lambda 
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#mode 

  times
  ------------------------------------------
  disk i/o             58.450223ms
  parsing HCL          165.703µs
  evaluating values    89.151184ms
  running checks       15.390157ms

  counts
  ------------------------------------------
  files loaded         21
  blocks               39
  modules              3

  results
  ------------------------------------------
  critical             0
  high                 0
  medium               0
  low                  1
  ignored              0

  1 potential problems detected.`

**Comment by afdesk** [comment]
Hi @pritamstyz4ever!
I can't reproduce this issue. is it still actual?

also, I can't fetch a branch now:
```sh
fatal: couldn't find remote ref feat/sd-2558+11 
```

**Comment by pritamstyz4ever** [comment]
Yes, it's still an issue for me. Please use branch `main`. 
Also, the command [tfsec](https://github.com/aquasecurity/trivy/issues/1357#issuecomment-968476680) seems ok.
But the `trivy` command is what fails

**Comment by afdesk** [comment]
@pritamstyz4ever thanks!
will investigate more

**Comment by afdesk** [comment]
Hi @pritamstyz4ever! I can't reproduce this issue?
Could you help?

my steps:
1. `git clone https://github.com/screwdriver-cd/aws-producer-scripts`
2. scan a raw repository `$ trivy conf --severity HIGH,CRITICAL .`
Results:
```sh
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/security-group/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
2021-11-26T17:26:18.100+0600	INFO	Detected config files: 4

aws-producer-scripts/msk.tf (terraform)
=======================================
Tests: 15 (SUCCESSES: 15, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (HIGH: 0, CRITICAL: 0)

aws-producer-scripts/providers.tf (terraform)
=============================================
Tests: 3 (SUCCESSES: 3, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (HIGH: 0, CRITICAL: 0)

aws-producer-scripts/variables.tf (terraform)
=============================================
Tests: 28 (SUCCESSES: 28, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (HIGH: 0, CRITICAL: 0)

aws-producer-scripts/vpc.tf (terraform)
=======================================
Tests: 4 (SUCCESSES: 4, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (HIGH: 0, CRITICAL: 0)
```
3. Initializing modules: `terraform init`
Result: 
```...
Terraform has been successfully initialized!
```
4. Run `trivy` again: `trivy conf --severity HIGH,CRITICAL .`
5. the results are [here](https://gist.github.com/afdesk/ac29ffea6029c55f10cf06b7ba6289c3)

**Comment by afdesk** [comment]
Hi @pritamstyz4ever! 
Could you try to run `trivy` version 0.21.1?
thanks!

**Comment by pritamstyz4ever** [comment]
Thank you @afdesk . The scan succeeded after I updated `trivy` version to  `v0.21.1`. I am closing the issue.

**Comment by thangamani-arun** [comment]
@afdesk we are using trivy `v0.20.1`, while scanning `liferay/portal:7.3.7-ga8` always failing, but this time it fails with same error as stated in this issue.

We kept trivy timeout as 1hr,

```
{"exit_code":1,"image_ref":"harbor-core:80/gitlab-test/liferay/portal@sha256:2916d43ae0c9460f710cf184bb6ff696fa40a88986e69e8505b4bdd78f6a7f49","level":"error","msg":"Running trivy failed","std_out":"2022-01-24T08:11:31.205Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","time":"2022-01-24T08:11:31Z"}
{"error":"running trivy wrapper: running trivy: exit status 1: 2022-01-24T08:11:31.205Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","level":"error","msg":"Scan failed","time":"2022-01-24T08:11:31Z"}
ERROR: runJob.panic - runtime error: invalid memory address or nil pointer dereference
{"level":"error","msg":"Cannot find scan job","scan_job_id":"8bdfd4707a1d4b5347797b7c","time":"2022-01-24T08:11:32Z"}
```

What is the reason for this failure? do we need to tweak parameter?
If not, is it a bug in `v0.20.1`?

**Comment by afdesk** [comment]
@thangamani-arun thanks for your report!
could you try the latest version of `trivy` at first?

and please, let me know if the problem persists. thanks

**Comment by thangamani-arun** [comment]
With latest image, it got fixed. Thanks @afdesk for the pointers.
