### ISSUE TITLE
Trivy fs stopped recognizing golang binary file.

### ISSUE THREAD

**Issue by rohitagg2020** [aquasecurity/trivy#1359]
Hi,

We were running trivy on our go binary file with versions prior to 1.20. It used to scan the binary file. But from 1.20 onwards, it stopped recognising the binary file. Also I see that from trivy fs command, `input` field is removed. What is the alternative to that ?

## Prior to version 1.20:
Input:
trivy fs <BINARY_FILE_LOCATION>
Output:

INFO Number of language-specific files: 1
INFO Detecting gobinary vulnerabilities...

. (gobinary)
Total: 0 (HIGH: 0)

## Version 1.20 onwards:
Input:
trivy fs <BINARY_FILE_LOCATION>
Output:

INFO Number of language-specific files: 0

Please help me if I am missing something.

**Comment by knqyf263** [comment]
Yes, it is intended. Please see the document.
https://aquasecurity.github.io/trivy/v0.20.2/vulnerability/detection/language/

**Comment by rohitagg2020** [comment]
@knqyf263 Thanks for the prompt response. I see that, we can scan the golang binaries using trivy `rootfs` now. 

Also there is an option to run trivy on the `repo` directly.

I am seeing two different behavior. When I run trivy `rootfs` on the binary, I dont see any vulnerabilities. But when I run it on the `repo`, I see 6(including 5 `HIGH`) vulnerabilities. I am unable to understand this difference. 

I expected running in either of the mode(`rootfs` or `repo`) to report same no. of vulnerabilities. Can you please share what is happening here.

**Comment by knqyf263** [comment]
It might be due to dev dependencies. `go.sum` includes dev dependencies and go binaries don't.
https://aquasecurity.github.io/trivy/v0.20.2/vulnerability/detection/language/

**Comment by knqyf263** [comment]
We don't have the plan for now.
