### ISSUE TITLE
access https://aquasecurity.github.io/trivy-repo/rpm/releases/2.2/x86_64/repodata/repomd.xml returns 404

### ISSUE THREAD

**Issue by tuhaolam** [aquasecurity/trivy#136]
```
curl -I "https://aquasecurity.github.io/trivy-repo/rpm/releases/2.2/x86_64/repodata/repomd.xml"

HTTP/1.1 404 Not Found
Server: GitHub.com
Content-Type: text/html; charset=utf-8

```

**Comment by knqyf263** [comment]
@tuhaolam What OS version are you using? For example, if you use CentOS6, you have to specify `releases/6` instead of `releases/2.2`.

```
curl -I "https://aquasecurity.github.io/trivy-repo/rpm/releases/6/x86_64/repodata/repomd.xml"
HTTP/2 200
```

**Comment by krol3** [comment]
@tuhaolam What OS version are you using?

**Comment by tuhaolam** [comment]
> @tuhaolam What OS version are you using? For example, if you use CentOS6, you have to specify `releases/6` instead of `releases/2.2`.
> 
> ```
> curl -I "https://aquasecurity.github.io/trivy-repo/rpm/releases/6/x86_64/repodata/repomd.xml"
> HTTP/2 200
> ```

I use a OS developed on CentOS7, and its release version number is 2.2, maybe this is the reason.
