### ISSUE TITLE
New Trivy mode: Image Diff

### ISSUE THREAD

**Issue by distortedsignal** [aquasecurity/trivy#1365]
**As A** software developer, focused on security, building container images
**I want** a mode of trivy that will help me detect changes between two different images
**So that** I can show customers why a newer image of a container is better than an old image of a container

Currently, I can closely approximate this functionality by doing something like this in zsh:

```sh
OLD_IMG="img:1" ; \
NEW_IMG="img:2" ; \
OLD_OUT=$(trivy -q i -f json $OLD_IMG | jq '.Results[]? | .Vulnerabilities[]? | .VulnerabilityID' | sort | uniq) ; \
NEW_OUT=$(trivy -q i -f json $NEW_IMG | jq '.Results[]? | .Vulnerabilities[]? | .VulnerabilityID' | sort | uniq) ; \
OLD_OUT=("${(@f)OLD_OUT}") ; \
NEW_OUT=("${(@f)NEW_OUT}") ; \
for new_cve_item in $NEW_OUT ; \
do OLD_OUT=(${OLD_OUT#$new_cve_item}) ; \
done ; \
echo "Diff:" ; \
echo "$OLD_OUT"
```

but I feel like this could be cleaner if it was built directly into trivy. If this was built directly into trivy, it would be far simpler to...

* ... have `-s` filtering.
* ... output the diffs as a table.
* ... consume image paths instead of looking at the docker image store.
* ... have better ignore-unfixed semantics.

And so on.

EDIT: I feel like having that entire zsh program on one line was... moderately sociopathic... so let's _not_ do that.

**Comment by knqyf263** [comment]
Hi @distortedsignal, thanks for the suggestion. We want to keep Trivy as small as possible. You can write a plugin in any language you want.
https://aquasecurity.github.io/trivy/v0.20.2/advanced/plugins/
