### ISSUE TITLE
Add minimum Go version supported

### ISSUE THREAD

**Issue by egberts** [aquasecurity/trivy#1370]
I installed Trivy on Debian 11 (bullseye) but it failed with embed module not found installed under /usr.  

Needs Go v1.16.0 or later.  

Debian has Go v1.15.9

Didn’t see that minimum Go version somewhere in the README.

**Comment by knqyf263** [comment]
Could you elaborate on it? What did you scan? How did you install Trivy?

>it failed with embed module not found installed under /usr.
