### ISSUE TITLE
error retrieving template from path: open /contrib/sarif.tpl: no such file or directory

### ISSUE THREAD

**Issue by rohitagg2020** [aquasecurity/trivy#1373]
## Description

I am trying to use the sarif template for generating output. Getting `file not found` error. Below is the command

trivy rootfs --format template --template "@/contrib/sarif.tpl" -o report.sarif

## What did you expect to happen?

I have downloaded the binary file(version: 0.20.2) and started using it.
I expected it to generate the sarif file containing results of `trivy rootfs`.

## What happened instead?
It throws an error.

## Output of `trivy command`:

```
	FATAL	unable to write results: failed to initialize template writer: error retrieving template from path: open /contrib/sarif.tpl: no such file or directory
```

**Comment by AndreyLevchenko** [comment]
Hi @rohitagg2020 
Path to the template shouldn't start with `/` if you are referring folder in current directory

**Comment by rohitagg2020** [comment]
Also we need to have this template in our machine before refering it. So we have to download it from trivy github. For more info, see this issue: 
https://github.com/aquasecurity/trivy/issues/1353
