### ISSUE TITLE
FileWalk() and FilterTargets() in utils package are not referenced by any files in this repository except utils_test.go

### ISSUE THREAD

**Issue by naoyukis** [aquasecurity/trivy#1375]
`FileWalk()` and `FilterTargets()` in `utils` package are not referenced by any files in this repository except `utils_test.go`.
Are you leaving these functions out of concern that they are referenced in external packages?

I think it would be good to remove them to avoid maintenance of unused code.
(It's only a small improvement...)

**Comment by knqyf263** [comment]
Thanks for raising an issue. I guess it is probably what we forgot to remove. We can remove it.

**Comment by naoyukis** [comment]
@knqyf263 
OK. I'll make a PR.
