### ISSUE TITLE
Sign RPM packages

### ISSUE THREAD

**Issue by crivetimihai** [aquasecurity/trivy#1384]
## Description

https://aquasecurity.github.io/trivy-repo/ describes setting up RHEL/CentOS repos with `gpgcheck=0`. For security reasons this is not a good practice. The repo cannot be browsed as it's hosted on github pages.

Can you please provide a URL to the GPG key?

Thanks!

**Comment by knqyf263** [comment]
Yes, we're working on it, but it may need some more time.
https://github.com/aquasecurity/trivy/pull/1093

**Comment by darkhonor** [comment]
Has any progress been made?  It has been over a year since the last update.  Is there something that would help implement?  The referenced PR was closed for inactivity

**Comment by afdesk** [comment]
@darkhonor sorry for waiting
I'm working on it this week

**Comment by john-0248** [comment]
Would like to implement trivy in a RedHat context but lack of GPG-key and a signed install-RPM makes it a non-starter unfortunately. Any progress? Estimated date when this could be available? Regardless, TIA! :-)

**Comment by knqyf263** [comment]
Reopened as we reverted #3612.
