### ISSUE TITLE
Trivy as kubernetes pod

### ISSUE THREAD

**Issue by saivenkateshedem** [aquasecurity/trivy#1394]
Can we deploy trivy as kubernetes pod and route traffic to this kubernetes service from jenkins to scan and generate report?Basically to isolate trivy from jenkins due to traffic

**Comment by knqyf263** [comment]
You can use our helm chart.
https://github.com/aquasecurity/trivy/tree/main/helm/trivy

**Comment by saivenkateshedem** [comment]
Thanks..it worked
