### ISSUE TITLE
"--ignore-unfixed" doesn't work with "image" as expected

### ISSUE THREAD

**Issue by szpak** [aquasecurity/trivy#1402]
## Description

A scan with "--ignore-unfixed" for images behaves differently if "image" keyword was used in a call or not.

## What did you expect to happen?

I should be able to call `trivy --ignore-unfixed some-image` and `trivy --ignore-unfixed image some-image` to get the same results.

## What happened instead?

Using `image` seems to cause `--ignore-unfixed` to be ignored:

```
$ trivy --ignore-unfixed eclipse-temurin:17.0.1_12-jdk | grep "Total" -B2
eclipse-temurin:17.0.1_12-jdk (ubuntu 20.04)
============================================
Total: 12 (UNKNOWN: 0, LOW: 12, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

```
$ trivy --ignore-unfixed image eclipse-temurin:17.0.1_12-jdk | grep "Total" -B2
eclipse-temurin:17.0.1_12-jdk (ubuntu 20.04)
============================================
Total: 89 (UNKNOWN: 0, LOW: 77, MEDIUM: 12, HIGH: 0, CRITICAL: 0)
```

Original call without `--ignore-unfixed`:

```
$ trivy image eclipse-temurin:17.0.1_12-jdk | grep "Total" -B2
eclipse-temurin:17.0.1_12-jdk (ubuntu 20.04)
============================================
Total: 89 (UNKNOWN: 0, LOW: 77, MEDIUM: 12, HIGH: 0, CRITICAL: 0)
```

## Output of run with `-debug`:

```
I will provide if needed
```

## Output of `trivy -v`:

```
Version: 0.20.0
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2021-11-19 ...
  NextUpdate: 2021-11-19 ...
  DownloadedAt: 2021-11-19 ...
```

**Update**. The same is with 0.21.0.

**Comment by knqyf263** [comment]
Try `trivy image --ignore-unfixed`. Feel free to reopen the issue if it doesn't address your issue.
