### ISSUE TITLE
Sarif results version in 0.21.1

### ISSUE THREAD

**Issue by krol3** [aquasecurity/trivy#1419]
## Description

Using the latest sarif template of trivy 0.21.1. I see some differences between the older version.
It's missing some fields in the new version of sarif

### Older sarif template

![Screen Shot 2021-11-26 at 17 13 25](https://user-images.githubusercontent.com/8355621/143626373-0fcbd055-084f-492e-97ff-323fe1cc83b9.png)

### New sarif template

![Screen Shot 2021-11-26 at 17 15 40](https://user-images.githubusercontent.com/8355621/143626516-ff207c6b-8e1a-498e-b15a-ff67189509ec.png)

**Comment by afdesk** [comment]
@krol3 Thanks for this report!
I'm investigating it now
