### ISSUE TITLE
Pod Security Policy is being depreciated

### ISSUE THREAD

**Issue by saivenkateshedem** [aquasecurity/trivy#1434]
Hi,
As pod security policy is being depreciated, do we have a plan to change the kubernetes yaml specifications.Below is the blog for the proof.

https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

**Comment by knqyf263** [comment]
Are you talking about our Helm chart?
https://github.com/aquasecurity/trivy/blob/main/helm/trivy/templates/podsecuritypolicy.yaml

**Comment by saivenkateshedem** [comment]
@knqyf263 yes

**Comment by knqyf263** [comment]
@krol3 Could take a look?

**Comment by krol3** [comment]
@saivenkateshedem  we have an issue already created for this: https://github.com/aquasecurity/trivy/issues/1305
Please take a look, and also any advice to replace it, it's welcome.

Here the PR https://github.com/aquasecurity/trivy/pull/1315

**Comment by knqyf263** [comment]
As @krol3 shared, we will discuss it in #1305.
