### ISSUE TITLE
Add an option to scan a running host (no docker context)

### ISSUE THREAD

**Issue by ChristianWeissCG** [aquasecurity/trivy#144]
I know trivy is for docker containers, but it would be very cool expend its use to running systems (VMs, physical systems, workstations, notebooks and so on; everything that is not jet in a docker container; everything that is maybe provisioned with ansible, puppet, cfengine, etc. or even setup manually). 

This would make the job of a security engineer more easyer as he could use a single tool for all purposes, and get consistent results. This would extend the adoption of using such a vulnerability scanner to an extended audience => more feedback, faster feedback.

It should be "easy" to implement that option as in both cases (docker & non-docker context) the base data for the scanner is the OS packaging system.

Hope to see some thumbs-up on this ticket to get this feature...

**Comment by ChristianWeissCG** [comment]
As the Vulnerabilit DB of trivy is better (at least for alpine), it would be cool if both project (this one & vuls) would join a partnership on "vulnerabilty db" (and DB updater).

Maybe to abstract the db/db-updater in a third project could avoid some long-term maintenance costs.

https://hub.docker.com/r/vuls/vuls/

**Comment by knqyf263** [comment]
The time has come to work on this issue. You can track it on this issue.
https://github.com/aquasecurity/trivy/issues/466

Let me close this issue.
