### ISSUE TITLE
What Image does Trivy scan on Docker tag collisions?

### ISSUE THREAD

**Issue by mkemmerz** [aquasecurity/trivy#1440]
Hello, quick question only.

Let's say I want to scan an Image that is available locally on my machine with a specific Docker tag but the same tag also exists remotely on a Docker Hub (or any other Container Registry). What image would Trivy scan if those are 2 different images (different hashes) but share the same Docker Tag?

Would Trivy scan the local or the remote image?

**Comment by DmitriyLewen** [comment]
Hello, @mkemmerz 
Trivy will scan the local image.

**Comment by afdesk** [comment]
@mkemmerz thanks for your interest in `trivy`!
can we help you with something else?

**Comment by mkemmerz** [comment]
Thanks for the help! This was my only question so I will close this issue.
