### ISSUE TITLE
Identical runs of standard table output and HTML template output generate different vulnerability outcomes

### ISSUE THREAD

**Issue by richardj-bsquare** [aquasecurity/trivy#1442]
## Description

With the following Dockerfile (to simulate a vulnerability):
``` Dockerfile
FROM node:14-alpine
```

Run...
``` bash
trivy config . 
```

and then
``` bash
trivy config --format=template --template='@contrib/html.tpl' . 
```

## What did you expect to happen?

To get the following vulnerability in the table output *and* the HTML output.

``` text
+---------------------------+------------+-----------+----------+------------------------------------------+
|           TYPE            | MISCONF ID |   CHECK   | SEVERITY |                 MESSAGE                  |
+---------------------------+------------+-----------+----------+------------------------------------------+
| Dockerfile Security Check |   DS002    | root user |   HIGH   | Specify at least 1 USER                  |
|                           |            |           |          | command in Dockerfile with               |
|                           |            |           |          | non-root user as argument                |
|                           |            |           |          | -->avd.aquasec.com/appshield/ds002       |
+---------------------------+------------+-----------+----------+------------------------------------------+
```

## What happened instead?

The contrib/html.tpl (https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl) generates valid HTML but no vulnerabilities are listed.

Removed non-body for brevity.
``` HTML
<body>
    <h1>Dockerfile - Trivy Report - 2021-12-07T12:12:31.35474Z</h1>
    <table>
      <tr class="group-header"><th colspan="6">dockerfile</th></tr>
      <tr><th colspan="6">No Vulnerabilities found</th></tr>
    </table>
  </body>
```

## Output of run with `-debug`:

```
Note: the output between the non-HTML and HTML is identical...
```
trivy --debug config --format=template --template='@html.tpl' --output 'test.html' . 
2021-12-07T12:16:11.753Z	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2021-12-07T12:16:11.793Z	DEBUG	cache dir:  *****
2021-12-07T12:16:11.793Z	DEBUG	Vulnerability type:  []
2021-12-07T12:16:12.337Z	DEBUG	OS is not detected and vulnerabilities in OS packages are not detected.
2021-12-07T12:16:12.337Z	INFO	Detected config files: 1
2021-12-07T12:16:12.337Z	DEBUG	Scanned config file: Dockerfile
```
```

## Output of `trivy -v`:

```
Version: 0.21.1
Vulnerability DB:
  Type: Full
  Version: 1
  UpdatedAt: 2021-12-07 06:40:43.429721191 +0000 UTC
  NextUpdate: 2021-12-07 12:40:43.429720491 +0000 UTC
  DownloadedAt: 2021-12-07 08:10:19.65267 +0000 UTC
```

**Comment by afdesk** [comment]
Hi @richardj-bsquare! thanks for your report!
I could reproduce this issue and will try to resolve it.

**Comment by Amaelh** [comment]
Thanks, same here ! I get "No vulnerabilities found" with most templates : gitlab, gitlab-codequality, sarif, html while getting actual vulnerabilities in table and json format outputs.

**Comment by afdesk** [comment]
@Amaelh thanks for report too!
we'll investigate it.

**Comment by afdesk** [comment]
@richardj-bsquare, @Amaelh we don't have a html template for the scan results of config files yet.

**Comment by Amaelh** [comment]
Neither gitlab or sarif templates ? I ran my test with following command :

```
docker run --pull always --rm \
			-v $(PROJECT_DIR):/project/:rw \
			aquasec/trivy:latest \
			-debug \
			fs --security-checks vuln,config \
			--format template --template "@contrib/gitlab.tpl" --no-progress \
			-o /project/output/gl-trivy-filesystem.json \
			/project/
```

**Comment by afdesk** [comment]
@Amaelh I took a look at `gitlab` template. yes, it contains only `vulnerabilities` results, without misconfiguration problems.

**Comment by afdesk** [comment]
@richardj-bsquare @Amaelh we're are working on html template right now

**Comment by richardj-bsquare** [comment]
Ah, that's a little bit of a misunderstanding / documentation thing then; assumed underlying JSON would be the same for all vulnerability types... Happy that you are working on it though !

**Comment by jpinkham** [comment]
This seems related to #1317.  With Trivy v0.22.0, I'm seeing configuration/IaC findings in the HTML report

**Comment by afdesk** [comment]
`trivy` has the HTML template for misconfigurations now. I think we can close this issue.
If I'm wrong, please feel free to reopen it. thanks
