### ISSUE TITLE
Add arm64 packages to apt repository

### ISSUE THREAD

**Issue by ginkel** [aquasecurity/trivy#1455]
Hi there,

I'd like to use trivy on arm64 Ubuntu 20.04 (running on a Raspberry Pi). Would it be possible to publish arm64 .deb packages in the trivy apt repository?

Thanks,
Thilo

**Comment by sjansen1** [comment]
+ for that request. I just tried to install trivy on arm64 systems (Oracle Cloud arm64 Ampere Altera Systems) to look for the new log4j zeroday.

**Comment by knqyf263** [comment]
I think we can. We use GoReleaser to build Linux packages.
https://goreleaser.com/customization/nfpm/?h=nfpm

You can build packages in local as below.

```
$ goreleaser release --skip-publish --skip-validate 
```

If I understand correctly, the arm64 packages are already generated and we simply ignore them here.
https://github.com/aquasecurity/trivy/blob/c275a841fd0ef0429684185a76bc85a5e72fa843/ci/deploy-deb.sh#L16-L17

The name is replaced here.
https://github.com/aquasecurity/trivy/blob/c275a841fd0ef0429684185a76bc85a5e72fa843/goreleaser.yml#L46-L57

Once we add `reprepro` lines for arm64, it will be published. Note that you can test it in your forked repository.

**Comment by mowangdk** [comment]
@knqyf263 I'd like to try 

/assign

**Comment by knqyf263** [comment]
Thanks! I've assigned it to you.

**Comment by knqyf263** [comment]
@mowangdk Please deploy the deb files (and rpm files if possible) to your forked repository (like mowangdk/trivy-repo) from `mowangdk/trivy` and make sure that you can install the arm64 packages on Linux. 

```
$ sudo apt-get install apt-transport-https
$ wget -qO - https://mowangdk.github.io/trivy-repo/deb/public.key | sudo apt-key add -
$ echo deb https://mowangdk.github.io/trivy-repo/deb [CODE_NAME] main | sudo tee -a /etc/apt/sources.list
$ sudo apt-get update
$ sudo apt-get install trivy
```

@ginkel and @sjansen1 might help you for testing.

**Comment by mowangdk** [comment]
> @mowangdk Please deploy the deb files (and rpm files if possible) to your forked repository (like mowangdk/trivy-repo) from `mowangdk/trivy` and make sure that you can install the arm64 packages on Linux.
> 
> ```
> $ sudo apt-get install apt-transport-https
> $ wget -qO - https://mowangdk.github.io/trivy-repo/deb/public.key | sudo apt-key add -
> $ echo deb https://mowangdk.github.io/trivy-repo/deb [CODE_NAME] main | sudo tee -a /etc/apt/sources.list
> $ sudo apt-get update
> $ sudo apt-get install trivy
> ```
> 
> @ginkel and @sjansen1 might help you for testing.

gotcha

**Comment by mowangdk** [comment]
@ginkel @sjansen1  I have a question about how to set GPG_KEY secrets in forked repo, and what is this used for? 
![image](https://user-images.githubusercontent.com/9926112/145771635-82b18ce1-d1d1-4c44-9fea-a1d1baa78aef.png)
cc @knqyf263

**Comment by mowangdk** [comment]
@ginkel @sjansen1 @knqyf263  I have successfully generated the deb package, but it still fails when I update the source on ubuntu. What should I check for this situation?

![image](https://user-images.githubusercontent.com/9926112/146196466-ddefca08-3568-4175-9fd4-8ad27e0a5b40.png)
![image](https://user-images.githubusercontent.com/9926112/146197195-090baa32-8dd8-4494-a4ce-7ba144df4c2b.png)

**Comment by mowangdk** [comment]
> @mowangdk Thanks. You need to deploy those files in GitHub Releases. ![image](https://user-images.githubusercontent.com/2253692/146210290-a9213bf9-636f-438b-afcb-9281ea7f8188.png)

ok， Thanks~
