### ISSUE TITLE
Unable to generate Trivy SARIF report: error retrieving template from path: open contrib/sarif.tpl: no such file or directory

### ISSUE THREAD

**Issue by nvuillam** [aquasecurity/trivy#1457]
## Description

In the context of the [integration of trivy within MegaLinter](https://megalinter.github.io/v6-alpha/descriptors/repository_trivy/), I need SARIF output, but when I try it it generates the following error

`trivy fs --security-checks vuln,config --exit-code 1 --format template --template @contrib/sarif.tpl -o /tmp/sarif/REPOSITORY_TRIVY.sarif .`

result: `unable to write results: failed to initialize template writer: error retrieving template from path: open contrib/sarif.tpl: no such file or directory`

## What did you expect to happen?

A SARIF output file :)

## What happened instead?

A crash

## Output of run with `-debug`:

```shell
[trivy] command: ['trivy', 'fs', '--security-checks', 'vuln,config', '--exit-code', '1', '--format', 'template', '--template', '@contrib/sarif.tpl', '-o', '/tmp/sarif/REPOSITORY_TRIVY.sarif', '.']
[trivy] CWD: /tmp/lint/.automation/test/trivy/bad
[trivy] result: 1 2021-12-11T20:11:58.563Z	INFO	Number of language-specific files: 1
2021-12-11T20:11:58.563Z	INFO	Detecting npm vulnerabilities...
2021-12-11T20:11:58.563Z	INFO	Detected config files: 0
2021-12-11T20:11:58.564Z	FATAL	unable to write results: failed to initialize template writer: error retrieving template from path: open contrib/sarif.tpl: no such file or directory
 ```

## Output of `trivy -v`:

```
Version: 0.21.2
```

## Additional details (base image name, container registry info...):

Trivy installed on alpine-linux with: `RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.21.2`

**Comment by afdesk** [comment]
Hi @nvuillam! thanks for your interest in `trivy`!
It seems that `trivy` can't find a sarif template here: `contrib/sarif.tpl`.
you need to set up a path to a sarif template.
also you can copy from here: [https://github.com/aquasecurity/trivy/blob/main/contrib/sarif.tpl](https://github.com/aquasecurity/trivy/blob/main/contrib/sarif.tpl)

**Comment by nvuillam** [comment]
@afdesk i'm sorry, i'm still striggling and I feel I tried everything, but sarif output file remains empty...

I install trivy like that in dockerfile
```dockerfile
RUN wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.22.0 && \
    wget --tries=5 -q -O /usr/local/bin/sarif.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/sarif.tpl && \
    chmod 644 /usr/local/bin/sarif.tpl
```

Then I call it this way

```shell
trivy fs --security-checks vuln,config --exit-code 1 --format template --template /usr/local/bin/sarif.tpl -o /tmp/sarif/REPOSITORY_TRIVY.sarif .
```

Do you see something else I could try ?

**Comment by afdesk** [comment]
@nvuillam is `REPOSITORY_TRIVY.sarif` empty? does it contain `/usr/local/bin/sarif.tpl`?
if there is a path in the output file, i'd add **@** to `template` option:
```sh
trivy fs --security-checks vuln,config --exit-code 1 --format template --template @/usr/local/bin/sarif.tpl -o /tmp/sarif/REPOSITORY_TRIVY.sarif .
```
it worked for me

**Comment by nvuillam** [comment]
@afdesk it works, many thanks for saving me from madness ;)

I close the issue :)
