### ISSUE TITLE
feat : Other outputs 

### ISSUE THREAD

**Issue by Davidffry** [aquasecurity/trivy#1461]
Hello,

I would like to know if it enables to have other output type like *JSON* *YAML* *plain text* and so on...

**Comment by afdesk** [comment]
Hi @Davidffry! thanks for your interest in `trivy`.
Now `trivy` supports `--format` option.
you can take a look it here: [https://aquasecurity.github.io/trivy/v0.21.2/vulnerability/examples/report/](https://aquasecurity.github.io/trivy/v0.21.2/vulnerability/examples/report/)

**Comment by afdesk** [comment]
also you can write your custom template ;)

**Comment by Davidffry** [comment]
Great 👍 thanks, I close the issue.
