### ISSUE TITLE
Display links column in the trivy table format output

### ISSUE THREAD

**Issue by saivenkateshedem** [aquasecurity/trivy#1464]
## Description

Trivy table output format not displaying **LINKS** column
      

## What did you expect to happen?
It should display LINKS column as it comes in the html report

## What happened instead?
Currently it displays the below  columns in the table format output 
   LIBRARY  
 VULNERABILITY ID 
SEVERITY 
 INSTALLED VERSION 
 FIXED VERSION     
       TITLE        

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
(paste your output here)
```

**Comment by afdesk** [comment]
@saivenkateshedem thanks for your interest in `trivy`!
in the table format `title` fields contain links to the descriptions.

**Comment by saivenkateshedem** [comment]
@afdesk Thanks for the reply
Below are the screenshots of both table and html
Table
-------
<img width="820" alt="Screenshot 2021-12-13 at 4 10 19 PM" src="https://user-images.githubusercontent.com/87964472/145798046-657deec0-489b-49a6-bfb7-f91110c58e3b.png">

HTML
-------
<img width="1403" alt="Screenshot 2021-12-13 at 4 10 50 PM" src="https://user-images.githubusercontent.com/87964472/145798090-319fceb7-dbf3-4c54-9e38-98323ffdb9d5.png">

Links which has been provided in html report are not present in table format

**Comment by richbecks** [comment]
I agree, would allow clickable links in terminal output on CI/CD systems, and terminals that support it.

**Comment by afdesk** [comment]
@saivenkateshedem oh, I understood it.
@richbecks thanks for your feedback too!

it seems It's not a bug, right?
we need to discuss this changes with @knqyf263

**Comment by afdesk** [comment]
I thought there were enough links to [aqua vulnerability db](https://avd.aquasec.com/)

**Comment by saivenkateshedem** [comment]
@afdesk thought like this is an issue because links are showing in html format not in tablular format...now i understood that tabular format doesnt show that..Yes this doesnt like a bug...We can mark it as a feature

**Comment by richbecks** [comment]
@afdesk - Why has github actions closed this... It doesn't appear to have been resolved in any way?

**Comment by richbecks** [comment]
Just confirmed that 0.24.2 (latest version at time of writing) doesn't have HTTP links in text table output, so can't see a valid reason for closing this.

**Comment by afdesk** [comment]
@richbecks ok, it seems that you're right. because there is no decision about this feature.

**Comment by afdesk** [comment]
is this issue still relevant?

**Comment by richbecks** [comment]
:-(
