### ISSUE TITLE
Docker images is not pull during scan

### ISSUE THREAD

**Issue by jainpratik163** [aquasecurity/trivy#1468]
## Description
we are trying to run docker image scan for CVE and it fails if docker image is not present , ideally it should pull automatically if image is not present

## What did you expect to happen?
if the docker image is not present it should pull automatically 

## What happened instead?
unable to inspect the image getting this image is image is not present.

## Output of `trivy -v`:
Version: 0.20.1
Vulnerability DB:
  Type: Full
  Version: 1
  UpdatedAt: 2021-12-13 06:42:10.877923081 +0000 UTC
  NextUpdate: 2021-12-13 12:42:10.877922781 +0000 UTC
  DownloadedAt: 2021-12-13 12:45:05.573408916 +0000 UTC

**Comment by afdesk** [comment]
Hi @jainpratik163! thanks for your report!
it's a strange behavior, `trivy` should pull the missing image. but `trivy` doesn't save it after scanning.

maybe is there a problem with repository? do you use [Docker Hub](https://hub.docker.com/)?

**Comment by jainpratik163** [comment]
when i am trying to run command getting the below error

2021-12-14T06:06:26.377+0200    INFO    Need to update DB
2021-12-14T06:06:26.377+0200    INFO    Downloading DB...
25.18 MiB / 25.18 MiB [----------------------------------------------------------------------------------------] 100.00% 10.69 MiB p/s 3s
2021-12-14T06:06:30.415+0200    FATAL   scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
        * unable to inspect the image (<image>): Error: No such image: <docker reg>/<dockern image>:0.42.37
        * unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
        * Get "https://<docker reg>/v2/": http: server gave HTTP response to HTTPS client

**Comment by afdesk** [comment]
@jainpratik163 it seems that `trivy` can't get `ServerURL` for your registry...

**Comment by jainpratik163** [comment]
this is error
2021-12-17T06:41:50.513+0200    FATAL   scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
        * unable to inspect the image (dockerreg/apigw-app:2.3.2): Error: No such image: dockerreg:5001/apigw-app:2.3.2
        * unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
        * Get "https://dockerreg:5001/v2/": http: server gave HTTP response to HTTPS client

**Comment by afdesk** [comment]
> Get "https://dockerreg:5001/v2/": http: server gave HTTP response to HTTPS client

It seems that is a reason, why `trivy` can't pull images, right?

**Comment by afdesk** [comment]
or I missed something

**Comment by jainpratik163** [comment]
my docker registry is on HTTP and trivy doesn't support the HTTP registry?

**Comment by knqyf263** [comment]
Looks like the same issue as https://github.com/aquasecurity/trivy/issues/1489. Could you try `TRIVY_NON_SSL=true`?
https://aquasecurity.github.io/trivy/v0.21.2/advanced/private-registries/self/

**Comment by jainpratik163** [comment]
Thanks with this export TRIVY_NON_SSL=true it works.
