### ISSUE TITLE
Support "executable" spring-boot jars for scanning

### ISSUE THREAD

**Issue by zeldigas** [aquasecurity/trivy#1470]
SpringBoot has a feature to build "*nix executable" jar files that essentially consists of a shell script and real jar file appended below - https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-executable.
Right now trivy does not support such files - it does not fail scan, but such a file is simply skipped. Would be great to support this so that even if such specific packaging is selected, it will be possible to perform scan.

Example of how this file looks like:
```
cat -v app.jar  | head -n 400
#!/bin/bash
#
#    .   ____          _            __ _ _
#   /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
#  ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
#   \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
#    '  |____| .__|_| |_|_| |_\__, | / / / /
#   =========|_|==============|___/=/_/_/_/
#   :: Spring Boot Startup Script ::
#

### BEGIN INIT INFO
# Provides:          api
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: api
# Description:       Parent pom providing dependency and plugin management for applications built with Maven
# chkconfig:         2345 99 01
### END INIT INFO
.... around 300 lines of bash....
exit 0
PK^C^D^T^@^H^H^H^@.....contents of jar file.....
````

**Comment by pryorda** [comment]
with the recent log4j vuln, this would be amazing!
