### ISSUE TITLE
Make filesystem scan for java jar actually work?

### ISSUE THREAD

**Issue by AkselAllas** [aquasecurity/trivy#1477]
For a bigger java application I (most-likely?) get rate-limited by maven.

After some time, from that server I can curl `search.maven.org` again, while after scan I can't. 

```
Analysis error: jar/war/ear parse error: failed to search by SHA1: status 403 Forbidden from https://search.maven.org/solrsearch/select?q=1%3A%2244ee8147a8a7246533db16f584d960832663bd1e%22&rows=1&wt=json
```

Literally doesn't provide any value with jar scans not working :(

**Comment by AkselAllas** [comment]
Maybe it's because I'm trying to parallalize these requests, but they are coming from the same NAT gateway.

**Comment by afdesk** [comment]
Hi @AkselAllas thanks for your report and sorry for waiting! 
In `tvivy` v0.22.0 was added a new option `--offline-scan` for scanning without API requests.
**Note**: there was disabled JAR detection in fs/repo scanning. now you should scan jar-files with `rootfs` option.

I think that it should work for you:
```sh
trivy -d rootfs --offline-scan .
```

**Comment by AkselAllas** [comment]
@afdesk 
`--offline-scan` in `v0.22.0` helps! Now my scan finishes finally! Thanks!

Still ideally we could host a local maven mirror / Nexus repository and pass the url as argument for the API requests.
Because currently ~15 to 20% of debug output is:

```
Unable to identify POM in offline mode  {"file": "spring-orm-3.2.0.jar"}
```

Also for running this in production environments, we need a way to throttle the scan since it hogs all the CPU/IO it can.
e.g. in a 2 CPU VM
![image](https://user-images.githubusercontent.com/26136082/147810132-c6b0c88f-0810-4c88-a7bd-5fc79b65f71d.png)


I can make separate issues for these if you wish. I may also be able to allocate some time for a PR myself aswell.

**Comment by afdesk** [comment]
@AkselAllas thanks a lot for your time and reports!
we welcome the contribution! I think it will be very nice if you can create a PR and separate issues!
