### ISSUE TITLE
UI to list all trivy projects

### ISSUE THREAD

**Issue by saivenkateshedem** [aquasecurity/trivy#1487]
Is there a interface/UI  for trivy where we can see all list of projects and its vulnerabilities in a single place?.

We have integrated trivy in the jenkins pipeline...we want to know whether we can view all project results in a single place

**Comment by knqyf263** [comment]
I'm sorry, but we don't have it at the moment. If someone develops it, our doc can refer to that. Thanks.
https://aquasecurity.github.io/trivy/v0.21.2/advanced/community/tools/
