### ISSUE TITLE
trivy repo scan for git refs

### ISSUE THREAD

**Issue by danielhelfand** [aquasecurity/trivy#1508]
I would like to use `trivy` to scan remote GitHub repositories, but I want to specifically scan specific tags of repositories. At the moment, I do not see any flag with `trivy repo` to make it simple to specify a tag to scan like the following example:

```
trivy repo https://github.com/helm/helm --tag v3.7.2
```

Alternatively, I would like some documentation somewhere (maybe [here](https://aquasecurity.github.io/trivy/v0.21.3/vulnerability/scanning/git-repository/)?) or an example with `trivy repo -h` that shows the proper format for specifying a git tag in the remote url.

**Comment by rsareth** [comment]
Allowing to scan a tag should also interpreted as Allowing to scan a reference in a git repository. We might need to scan a branch for example.

**Comment by danielhelfand** [comment]
@rsareth Yes, makes total sense to me. I titled the issue with ref to capture that, but realize I only called out tag in the issue.

I do hope this could be a more general solution as you mention though. Including things like commit sha might be another interesting case.

**Comment by ShubhamPalriwala** [comment]
Hey, so just to get the issue right,
Right now we only scan the default branch and what we are looking here is to 
- pass an argument for the branch name &
- pass an argument for a commit hash to scan for the these specific instances.


Am I correct here?

**Comment by ShubhamPalriwala** [comment]
@danielhelfand @rsareth @knqyf263 I would like to work on this once you can confirm the problem as I detailed above

**Comment by rsareth** [comment]
Hi @ShubhamPalriwala ,

It is okay for me. But, be careful during your test that we can use the ssh protocol too.

**Comment by ShubhamPalriwala** [comment]
@rsareth Opened a PR for the same a couple of days ago :)))

**Comment by kiefshemul-tomtom** [comment]
Is there any way to pass a git ref instead of specifying tag | branch | commit ?

**Comment by ShubhamPalriwala** [comment]
Can you try passing the ref with the commit flag and see if it works?
