### ISSUE TITLE
support for oracle, amazon and suse linux images

### ISSUE THREAD

**Issue by dhavalp2010** [aquasecurity/trivy#151]
When trivy will provide support for oracle, amazon and suse linux images?

**Comment by knqyf263** [comment]
v0.1.7 has released. Amazon Linux is supported now!

**Comment by knqyf263** [comment]
Now, Trivy supports Oracle Linux 🎉  Thanks to @masahiro331 .
https://github.com/aquasecurity/trivy/pull/286

**Comment by knqyf263** [comment]
Also, we supported SUSE.
