### ISSUE TITLE
Improve reporting to avoid ambiguity when no failures are reported in the JUnitReport

### ISSUE THREAD

**Issue by HugoVeillette** [aquasecurity/trivy#1510]
Hi, this is a feature request to improve upon the default JUnit template output. 
https://github.com/aquasecurity/trivy/blob/main/contrib/junit.tpl

The current behavior returns that 0 test were performed when no issues are found.  See below.

```
trivy --severity HIGH,CRITICAL --ignore-unfixed --format template --template "@contrib/junit.tpl" -o /reports/junit-report.xml golang
cat /reports/junit-report.xml
<testsuites>
    <testsuite tests="0" failures="0" name="golang (debian 11.2)" errors="0" skipped="0" time="">
        <properties>
            <property name="type" value="debian"></property>
        </properties>
    </testsuite>
</testsuites>
```

This behavior causes issue when interpreting the report; unless there are issues we cannot assert that the scan actually happened.

To avoid running into this scenario, would it be possible to add a test case in each test suite, asserting that no vulnerabilities were reported by severity?

For instance, using custom template derived from the default we can correct the behavior. 
```
<?xml version="1.0" ?>
<testsuites>
{{- range . -}}
{{- $failures := len .Vulnerabilities }}
    <testsuite tests="{{ add $failures 1 }}" failures="{{ add $failures (min $failures 1) }}" name="{{  .Target }}" errors="0" skipped="0" time="">
    {{- if not (eq .Type "") }}
        <properties>
            <property name="type" value="{{ .Type }}"></property>
        </properties>
        {{- end -}}
        {{ range .Vulnerabilities }}
        <testcase classname="{{ .PkgName }}-{{ .InstalledVersion }}" name="[{{ .Vulnerability.Severity }}] {{ .VulnerabilityID }}" time="">
            <failure message="{{ escapeXML .Title }}" type="description">{{ escapeXML .Description }}</failure>
        </testcase>
	{{- end}}
        <testcase name="No CVE found" classname="Scan.{{ .Type }}" time="" >
          {{- if not (eq $failures 0) }}
                <failure message="Found vulnerabilities in {{ escapeXML .Target }}" type="description">Expecting 0 CVE but found {{ $failures }}.</failure>
          {{- end}}
        </testcase>
    </testsuite>
{{- end }}
</testsuites>                
```

**Comment by gzmarstone** [comment]
I like this idea, it would be nice to see how many packages were found and how many have vulnerabilities...

**Comment by HugoVeillette** [comment]
@gzmarstone  indeed; 
Afaik, this information is not available in the object passed to the golang template, nor is the DB version used for the scan.
The severities and filters are not available globally, we can aggregate (as shown in doc/samples), but only among failures.

If we could improve the current implementation to pass not only the failures, but the context and the success (where package are found), that would be a tremendous improvement. 

The example I provided is the best we can do with the lack of information, i.e. not ideal resolution.
