### ISSUE TITLE
image scan fails with error: "semaphore acquire: context deadline exceeded"

### ISSUE THREAD

**Issue by uwedisch** [aquasecurity/trivy#1519]
## Description
I'm executing "trivy rootfs --security-checks vuln,config /" on Kali Linux (rolling).
Downloaded Trivy with "curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.22.0"

I'm getting error messages like this (every scan on another location, but error message keeps the same):

2021-12-25T23:11:01.818-0300	FATAL	scan error: image scan failed: failed analysis: walk dir: walk error: unknown error with //var/lib: unknown error with //var/lib/dpkg: unknown error with //var/lib/dpkg/info: failed to analyze file: analyze file (var/lib/dpkg/info/libxml2-utils.list): semaphore acquire: context deadline exceeded

## What did you expect to happen?
That the scan finishes succesful.

## What happened instead?
The scan interrupts with error.

## Output of run with `-debug`:

```
2021-12-25T23:43:46.300-0300	FATAL	scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:71
  - image scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:217
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:98
  - walk dir:
    github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211224205755-c94f68b6d71a/artifact/local/fs.go:98
  - walk error:
    github.com/aquasecurity/fanal/walker.Dir.Walk
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211224205755-c94f68b6d71a/walker/fs.go:60
  - unknown error with //opt/rapid7/nexpose/plugins/java/1/WindowsDefenderScanner:
    github.com/aquasecurity/fanal/walker.Dir.Walk.func2
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211224205755-c94f68b6d71a/walker/fs.go:54
  - unknown error with //opt/rapid7/nexpose/plugins/java/1/WindowsDefenderScanner/1:
    github.com/aquasecurity/fanal/walker.Dir.Walk.func2
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211224205755-c94f68b6d71a/walker/fs.go:54
  - failed to analyze file:
    github.com/aquasecurity/fanal/walker.Dir.Walk.func1
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211224205755-c94f68b6d71a/walker/fs.go:42
  - analyze file (opt/rapid7/nexpose/plugins/java/1/WindowsDefenderScanner/1/vulns.jar):
    github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect.func1
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211224205755-c94f68b6d71a/artifact/local/fs.go:93
  - semaphore acquire:
    github.com/aquasecurity/fanal/analyzer.Analyzer.AnalyzeFile
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211224205755-c94f68b6d71a/analyzer/analyzer.go:210
  - context deadline exceeded

```

## Output of `trivy -v`:

```
Version: 0.22.0
Vulnerability DB:
  Type: Full
  Version: 1
  UpdatedAt: 2021-12-26 00:50:11.241144861 +0000 UTC
  NextUpdate: 2021-12-26 06:50:11.241144561 +0000 UTC
  DownloadedAt: 2021-12-26 01:33:59.625181896 +0000 UTC

```

**Comment by knqyf263** [comment]
Looks like a timeout. Please try `--timeout 30m`. Also, `rootfs` tries to traverse all the directories. If you want to skip some of them, you can use `--skip-dirs` to finish scanning quicly.

**Comment by uwedisch** [comment]
No, that's not the problem. I tried with timeout parameter. The error occurs after about 2 or 3 minutes.
I also tried to skip dirs, but it's feeling like that, that you will end up in excluding nearly the whole disk. I tried to work with excluding and posted this issue after the 5th exclude ...
What is the default timeout of rootfs scanning?

**Comment by uwedisch** [comment]
Yes, strong positional parameters. timeout parameter must not go before rootfs parameter. If it is placed after then scanning works.

In the future it might be useful to display a usable error message that mentions the expired timeout.

**Comment by knqyf263** [comment]
Thanks for the feedback. It used to show an error message regarding the timeout option. It might be removed due to regression. We'll consider adding it again. At least, it is mentioned in our doc.
https://aquasecurity.github.io/trivy/v0.22.0/getting-started/troubleshooting/#timeout

Please feel free to reopen the issue if you have some other issues.
