### ISSUE TITLE
For alpine how you are fetching vuln infor from https://bugs.alpinelinux.org/projects/alpine/issues?

### ISSUE THREAD

**Issue by dhavalp2010** [aquasecurity/trivy#152]
For alpine how you are fetching vuln info from https://bugs.alpinelinux.org/projects/alpine/issues?

I am not able to find any CSV/JSON/Rest Api for clearly checking the vuln  info, are you searching from the issues text?

Just wanted to check how it is fetching more vulnerabilities than other open source tools.

**Comment by knqyf263** [comment]
Recently we migrated to [secdb](https://secdb.alpinelinux.org/).
