### ISSUE TITLE
Feature: Allow specifying a single package manager file to scan

### ISSUE THREAD

**Issue by abierbaum** [aquasecurity/trivy#1533]
Trivy looks like a great tool and is working very well on my containers.  The next step is that I would like to use it to scan specific yarn.lock and requirements.txt files for some of our dependencies.  But I don't want to scan the entire repository or directory tree, what I would like to do is to scan a specific file with a single run.

So something like:

```
trivy filesystem main_module/yarn.lock
trivy filesystem another_module/requirements.txt
```

Then for each of these runs it would give me any vulnerabilities found for only those specific package files.

Is this somehow possible without having to put a step in the middle of creating a temporary directory, copying the file into it, and then scaning the temp directory?

**Comment by rsareth** [comment]
I'm facing a similar issue. I have several text files to declare my python libraries:
- requirements.txt
- requirements-devel.txt

So I'm using another tools to read all my requirements-devel.txt files.

**Comment by jerbob92** [comment]
@rsareth I have created a PR for that: https://github.com/aquasecurity/fanal/pull/355

**Comment by jerbob92** [comment]
@abierbaum I have created a PR for that too: https://github.com/aquasecurity/fanal/pull/356
However, I don't really think they will merge it, since everything is still named `dir` or `directory` internally, even though you would give it a filepath, which may cause issues downstream (for example in this trivy cli tool).

But, we will see :)

**Comment by abierbaum** [comment]
@jerbob92 Thank you for putting together a PR for this.  I think it would be a great feature but I see what you mean that they may want it in a different way.
