### ISSUE TITLE
Reenable support for scanning jar files on fs

### ISSUE THREAD

**Issue by DaspawnW** [aquasecurity/trivy#1543]
Dear trivy team,

with release 0.22.0 you have dropped the support for jar scanning if trivy fs is used.
This now enables the direct usage of pom.xml, but as there are more then one build tool (gradle, ant) it would be great if this could be reverted.

With this you would be still able to scan build jar files without the problem how to convert gradle to maven pom.xml.

Thank you in advance,
Best regards,
 Björn

**Comment by knqyf263** [comment]
Hi, you can use the `rootfs` subcommand for the purpose.
https://aquasecurity.github.io/trivy/v0.22.0/vulnerability/scanning/rootfs/

We know it is a bit confusing and want to improve, but you can see which analyzers are enabled here.
https://aquasecurity.github.io/trivy/v0.22.0/vulnerability/detection/language/

**Comment by MartinEmrich** [comment]
@knqyf263 I was just about to open the same issue... TBH, "rootfs" suggests scanning actually the root filesystem, were it not for your comment, I would not have thought of that option. (Yep, this is more of an UX issue)

What's the difference between "fs" and "rootfs" apart from not scanning JAR files anymore? Does on "miss out" on anything from "fs" when switching to "rootfs"?
