### ISSUE TITLE
Support for newer distro releases - Ubuntu 20.04, CentOS 8, CentOS Stream, etc

### ISSUE THREAD

**Issue by scottcunningham** [aquasecurity/trivy#1550]
Hello!

I've been looking at the "Supported OS" documentation here:
https://aquasecurity.github.io/trivy/v0.17.0/vuln-detection/os/

The latest supported versions of some OSes are quite old:

- Ubuntu -- the latest supported version per the docs is 19.10, but the 20.04 LTS is almost 2 years old
- CentOS -- no support for CentOS 8 or CentOS Stream mentioned

Are there plans to support newer versions of these distros?

Another question -- for OS versions not explicitly mentioned, should detection still work (albeit without release-specific erratas and backports)?

Thank you.

**Comment by Driste** [comment]
That's v0.17.0

Try the latest documentation for Ubuntu:
https://aquasecurity.github.io/trivy/v0.22.0/vulnerability/detection/os/

It still doesn't mention CentOS 8, but RHEL 8 is listed.

**Comment by scottcunningham** [comment]
Good catch, thanks!

Looks like Ubuntu is covered, but I'd like to know about any plans for CentOS 8 and CentOS Stream.

**Comment by knqyf263** [comment]
@DmitriyLewen Would you update the documentation regarding supported OS? Please check which versions are supported in Ubuntu. We support CentOS 8, not CentOS Stream.

**Comment by DmitriyLewen** [comment]
Okey, i will do it

**Comment by scottcunningham** [comment]
@knqyf263 @DmitriyLewen Do you have any plans for supporting CentOS stream in the future?

**Comment by knqyf263** [comment]
As far as I know, CentOS stream doesn't have security advisories. We cannot support it in a canonical manner.

**Comment by knqyf263** [comment]
If you want Trivy to support CentOS Stream, could you open a dedicated issue and close this one?

**Comment by scottcunningham** [comment]
will do!

**Comment by scottcunningham** [comment]
Filed https://github.com/aquasecurity/trivy/issues/1622 to track this.

**Comment by knqyf263** [comment]
Thanks
