### ISSUE TITLE
HTML template missing target names for go, npm, python/pip, java pom.xml, config files

### ISSUE THREAD

**Issue by jpinkham** [aquasecurity/trivy#1556]
For many different types of files being scanned, the target names are not being reported in the HTML template, only the type of file.  This makes it impossible to know which file contains the vulnerabilities and/or misconfigurations that were found.

- The HTML title of the file is only for the first item scanned, all other items only list their type. It would be great if the title was set to directory, repo, or image that was scanned (.ArtifactName, .ArtifactType)
- Now that config entries are included with the vulnerabilities (which is awesome btw, thanks!), it's slightly confusing to see entries with "No vulnerabilities found" that are followed immediately by what looks like a vulnerability (but is actually a misconfiguration)
<img width="1337" alt="Trivy_HTML_report_confusing_mixed_findings" src="https://user-images.githubusercontent.com/2560080/148665692-a0868e73-8c64-4d62-b0c5-989d7cd687c4.png">

I happened to have a local clone of https://github.com/docker/awesome-compose  available, which is good for scanning because it contains files of multiple types (except golang).  I've attached the json output of the scan and the HTML output for comparison (for some reason GH doesn't support HTML or JSON file attachments....so I gzip'd them).  I attached trivy results of Trivy as well, since it contains golang examples plus lots of config files.

And here's some screenshots of the lack of Target name:
<img width="1337" alt="Trivy_HTML_report_AwesomeCompose" src="https://user-images.githubusercontent.com/2560080/148665475-dca6f10e-3037-4686-8d93-ace7a9f2b2d2.png">
<img width="1161" alt="Trivy_HTML_report_trivy_itself" src="https://user-images.githubusercontent.com/2560080/148665476-138b5a07-5419-450c-be6d-01c868a91285.png">

[awesome-compose.html.gz](https://github.com/aquasecurity/trivy/files/7834291/awesome-compose.html.gz)
[awesome-compose.json.gz](https://github.com/aquasecurity/trivy/files/7834292/awesome-compose.json.gz)
[trivy_results_of_trivy_itself.json.gz](https://github.com/aquasecurity/trivy/files/7834293/trivy_results_of_trivy_itself.json.gz)
[trivy_results_of_trivy_itself.html.gz](https://github.com/aquasecurity/trivy/files/7834294/trivy_results_of_trivy_itself.html.gz)

NOTE: These reports were generated with Trivy v0.22.0

**Comment by jpinkham** [comment]
I've taken a [first pass at tweaking the template](https://github.com/aquasecurity/trivy/compare/main...jpinkham:jp/HTML-template-changes) to increase readability.  This round was more about determining what data I can add to the page, vs fussing too much with styling. Feedback is welcome
<img width="1180" alt="Trivy_HTML_report_trivy_itself__first_pass_html_reportchanges" src="https://user-images.githubusercontent.com/2560080/148667678-9b266914-6c67-42f1-aeaf-2840e3018c61.png">
<img width="1180" alt="Trivy_HTML_report_trivy_itself__first_pass_html_reportchanges-2" src="https://user-images.githubusercontent.com/2560080/148667802-f973f818-b8b4-4210-85fc-04cc6e5954c3.png">

**Comment by frjonsen** [comment]
Was also facing this issue, where we scan a large number of .NET projects at the same time, and each project would only get the header "nuget". Would be great to see the modifications by @jpinkham implemented.

**Comment by afdesk** [comment]
@frjonsen you can use any custom templates for `trivy` results:
```sh
$ trivy image --format template --template @path/to/custom/html.tpl --output result.html alpine:latest
```
it seems that @jpinkham's changes are here: https://github.com/aquasecurity/trivy/commit/7b4fb9daadffa758337a9042ff37b057b602a772

**Comment by jpvg10** [comment]
I think this shouldn't be closed, I'd like to see this fixed at some point... And the PR hasn't been merged yet

**Comment by huornlmj** [comment]
Same issue here - please merge the PR

**Comment by huornlmj** [comment]
This also applies when using Trivy's misconfiguration scanning AND filesystem scanning features.

**Comment by huornlmj** [comment]
Ping to keep this active.  This is the official bundled HTML template and it's never worked properly.  I think this should be fixed.

**Comment by itaysk** [comment]
Hi @huornlmj, we have a plan to extract the non-essential output options out of trivy so that the community can develop it, therefore we are reluctant to invest in these areas right now.
related:  https://github.com/aquasecurity/trivy/discussions/4451

**Comment by huornlmj** [comment]
Still an issue

**Comment by huornlmj** [comment]
Still an issue - quietly longing for this fix as I believe it would be one of those "missing puzzle piece" feature fixes.!

**Comment by itaysk** [comment]
@huornlmj I'm sorry but we have no intention to maintain the HTML template in-tree, most like we will remove it. I would advise people interested in an HTML output to either copy the html from Trivy and tweak it, or make the request with one of the existing plugins such as https://github.com/fatihtokus/scan2html
