### ISSUE TITLE
Image scan not detecting vulnerabilities 

### ISSUE THREAD

**Issue by nathalieflower** [aquasecurity/trivy#1557]
## Description

When scanning a custom image with the latest version of Trivy (22.0)  I am only getting the vulnerabilities in my base image and not any of my added packages. I.e I have a custom base java image to which I am adding Grafana  - I get all the vulnerabilities in the base java image but no node.js vulnerabilities from Grafana - If I run against Trivy 18.3 I am getting all vulnerabilities, including the node.js ones.    

When scanning a custom image with the latest version of Trivy I am only getting the vulnerabilities in my base image and not any of my added packages. I.e I have a custom base java image to which I am adding Logstash  - I get all the vulnerabilities in the base java image but no ruby vulnerabilities from Logstash - If I run against Trivy 18.3 I am getting all vulnerabilities, including the ruby ones.    

## What did you expect to happen?
A report showing the vulnerabilities in the whole of my image

## What happened instead?
I only get the vulnerabilities in my base image

**Comment by afdesk** [comment]
@nathalieflower thanks for your report!
I'll try to clarify this issue.

**Comment by afdesk** [comment]
@nathalieflower could you show your Dockerfile where you add Grafana to an image? thanks a lot!

**Comment by afdesk** [comment]
just I run `trivy -d i grafana/grafana:8.2.1` for `trivy` v0.22.0 and v0.18.3, and see the same result...

**Comment by nathalieflower** [comment]
The Grafana image is bad example because we are doing some custom things there that we need to review.

However if you run it against logstash the latest version `trivy image logstash:7.16.2` you get different results between 0.19 and 0.20 upwards - its like its not picking up the gem file `usr/share/logstash/Gemfile.lock (bundler)`.

**Comment by afdesk** [comment]
@nathalieflower yes, you're right!
> Trivy migrated to *.gemspec scanning. Gemfile.lock in container images will be no longer detected

look at [BREAKING CHANGES v0.20.0](https://github.com/aquasecurity/trivy/discussions/1279)

**Comment by afdesk** [comment]
@nathalieflower for example, you can try a way [Unpacked Filesystem](https://aquasecurity.github.io/trivy/v0.22.0/advanced/container/unpacked-filesystem/) for scanning `Gemfile.lock`: 
```sh
$ docker export $(docker create alpine:3.10.2) | tar -C /tmp/rootfs -xvf -
$ trivy fs /tmp/rootfs
```
it should work: [Language-specific Packages](https://aquasecurity.github.io/trivy/v0.22.0/vulnerability/detection/language/)
