### ISSUE TITLE
full report is not displayed if we want to exit with different code on high or critical vulnerability 

### ISSUE THREAD

**Issue by sourabhgupta385** [aquasecurity/trivy#1563]
I want to fail pipeline if only HIGH or critical vulnerabilities are found in scan. I tried with below command but it partially solves my problem as when I see the report, it lists only HIGH and CRITICAL vulnerabilities and MEDIUM and LOW vulnerabilities are omitted in report. 
`trivy  image --exit-code 1 --severity HIGH,CRITICAL --format template --template "@/usr/local/share/trivy/templates/html.tpl" -o scan-report.html <image>`

I want that report should display all the vulnerabilities. Is there any way to do it?

I know I can scan image twice where in one generate full report and fail in another based on criterion. But that is not feasible. Can it be done with single scan?

**Comment by dotmitsu** [comment]
I have the same problem. I need exit 1 if severity is CRITICAL, but write full log

**Comment by knqyf263** [comment]
You can generate a JSON report with full results and exit on critical vulnerabilities with `convert`.
https://aquasecurity.github.io/trivy/v0.48/docs/configuration/reporting/#converting
