### ISSUE TITLE
Mirror implement

### ISSUE THREAD

**Issue by kraken0909** [aquasecurity/trivy#1564]
Hi! Do you have any plans to implement mirror (For example: Nexus repository) for Maven, npm, .net nuget, pip?

**Comment by kraken0909** [comment]
Hi there! The issue is still relevant today.

**Comment by dvdgsng** [comment]
Still relevant, trivy scans are currently failing because **search.maven.org** is broken.

![image](https://user-images.githubusercontent.com/4592717/213022248-556cf44e-4fbf-42b0-9cb7-549d23ca63fb.png)

**Comment by jprelph** [comment]
We have also been hit by this problem over the past few weeks - being able to add mirrors for JAR scans would mitigate this kind of problem massively.

**Comment by paddy235** [comment]
strongly support
