### ISSUE TITLE
Allow `color.NoColor = false` to set via cli

### ISSUE THREAD

**Issue by amandel** [aquasecurity/trivy#1566]
Reading https://github.com/fatih/color#github-actions it is possible to get colorful output also in ci environments by setting `color.NoColor = false` it would be nice if this can be set or forced via trivy cli option (like `--no-colour=false`) for the table output.

**Comment by stefanlasiewski** [comment]
Also see this related issue (Autoclosed):

https://github.com/aquasecurity/trivy/issues/1091

**Comment by amandel** [comment]
Bringing #1566 and this one together as feature request:

The used color package does a good job in auto detecting whether the output supports ANSI coloring or not. Unfortunately for some use cases (mostly CI or other automation) this fails and needs manual override. Fortunately the color package already has this needed functionality as described in the color readme section for github-actions

For the table format of trivy, it would be nice to have a trivy cli option --color with possible values true, false, and default auto. The default is current behavior, true or false set color.NoColor to the respective value.

**Comment by stefanlasiewski** [comment]
This would be very useful for simple use cases like a simple shell script that calls `trivy image ubuntu:20.04 | grep CVE`. 

`--format json` is more complicated then what many folks need, and `--format template` even more so.
