### ISSUE TITLE
How to query scan result in server mode?

### ISSUE THREAD

**Issue by NitroCao** [aquasecurity/trivy#1576]
We want to query and analyze scanning results. Is there any way to query scanning results of images when trivy runs in server mode?

**Comment by knqyf263** [comment]
You can see here.
https://aquasecurity.github.io/trivy/v0.22.0/advanced/modes/client-server/

**Comment by NitroCao** [comment]
> You can see here. https://aquasecurity.github.io/trivy/v0.22.0/advanced/modes/client-server/

Thanks for your reply. Normally the `trivy client` command returns the scanning results. I mean how to get results on the server side. It seems that results are cached in redis, so can I get them directly from redis?

**Comment by knqyf263** [comment]
The server doesn't store the scan result. It has only layer information in the cache.
