### ISSUE TITLE
Output JSON schema

### ISSUE THREAD

**Issue by javierfreire** [aquasecurity/trivy#1581]
I'm trying to parse the Trivy output. Is there any JSON schema? Is it right that some entities have camel case and other snake_case?

Thank you

**Comment by afdesk** [comment]
@javierfreire thanks for your interest in `trivy`!
If Go struct is Ok for you, You can take a loot at Report struct here: https://github.com/aquasecurity/trivy/blob/22054626f3c95ed219e4af206fced1ad6ac878f7/pkg/report/writer.go#L26-L75

**Comment by javierfreire** [comment]
Thank you
