### ISSUE TITLE
Provide pre-populated vulnerability DB

### ISSUE THREAD

**Issue by Silvanoc** [aquasecurity/trivy#159]
The [Trivy docker image](https://hub.docker.com/r/aquasec/trivy) doesn't provide a pre-populated vulnerabilities DB.

As a consequence the first run has to download >300MB (shallow commit) and wait >2min on my connection.
And a volume is needed if caching the DB is desired between runs (what can be an issue on CI).

The usage of shallow git clones doesn't make the update easy using only git means, but there might be other means... The diff between 2019-09-19 and 2019-09-20 is only 4M big, what about publishing daily git patches on the [vuln-list](https://github.com/aquasecurity/vuln-list) repo and applying them with Trivy?

I think it would be helpful to provide at least one of the following:
- A Docker image with DBs pre-propulated on image build (image to be downloaded becomes much bigger).
- A new image tag "...-db" built based on the default image, but adding a layer with the DBs pre-population. Something like `RUN trivy --refresh` would do it, right?
- A Dockerfile to help users build the image themselves. Almost a two-liner `FROM trivy \n RUN trivy --refresh`, right?

**Comment by knqyf263** [comment]
@Silvanoc I'm sorry for the late reply. I'm working on it.

**Comment by knqyf263** [comment]
Now, we're providing pre-build DB on [trivy-db](https://github.com/aquasecurity/trivy-db/releases). But you don't have to care about it since trivy automatically fetches it.
