### ISSUE TITLE
List front end packages when building on nginx image

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#1607]
Hi

 I am building an angular app, and copying the files on top of an nginx image, something like this https://www.indellient.com/blog/how-to-dockerize-an-angular-application-with-nginx/

I am using trivy with the  --list-all-pkgs, and it is not listing packages in my front end application. It makes sense, as i dont have a package.json file in the final container.

However, i think those dependencies can be retrieved from the final nginx image.I think it would be a good addition to add a new feature to retrieve those dependencies when it is built on top of a nginx image

Thanks

**Comment by krol3** [comment]
@javixeneize the current support language is here https://aquasecurity.github.io/trivy/v0.22.0/vulnerability/detection/language/

Could give more details about the top layer of your app? What files contains?

**Comment by javixeneize** [comment]
Hi

it contains just the dist folder, it is, the static files built with npm. It doesn’t contain any package.lock or similar

thanks

**Comment by ertl** [comment]
I have the same problem. Dependencies of Angular app are missing in the SBOM. The created Angular app has no node_modules folder and no package-lock.json. However, there is a 3rdpartylicenses.txt that contains all dependencies and licences. Is there a way to instruct trivy to include these dependencies in the SBOM generation?

**Comment by knqyf263** [comment]
@ertl Interesting. Could you open a discussion about 3rdpartylicenses.txt support?
https://github.com/aquasecurity/trivy/discussions/categories/ideas

**Comment by ertl** [comment]
Discussion startet: https://github.com/aquasecurity/trivy/discussions/5563
