### ISSUE TITLE
Azure devops integration error with aqua trivy image scanner.

### ISSUE THREAD

**Issue by divi7777777** [aquasecurity/trivy#1609]
Description
we have put aqua login task before scan task and also provided token also but ("docker: Error response from daemon: Head ***/v2/scanner-cli/manifests/6.5": no basic auth credentials.") this error is coming .I have attached the screenshots below of the error and the value which we provided for scan

What did you expect to happen?

we expect to scan the image and give the result.

![Screenshot (115)](https://user-images.githubusercontent.com/96525577/150309453-b4304305-6e1b-4a9a-afec-dd39adbd3ead.png)
![Screenshot (116)](https://user-images.githubusercontent.com/96525577/150309463-02e6cf2c-db63-4ff3-b455-c98836a00d09.png)
![Screenshot (117)](https://user-images.githubusercontent.com/96525577/150309464-dfd211cd-7ea2-4629-9563-1c1d26f28eea.png)
![Screenshot (118)](https://user-images.githubusercontent.com/96525577/150309469-827eaeff-da06-40b1-af05-a318e1b13714.png)

**Comment by knqyf263** [comment]
It is not Trivy, but Aqua. Please ask the Aqua product team.
