### ISSUE TITLE
Java (jars) not being scanned for images

### ISSUE THREAD

**Issue by jdesouza** [aquasecurity/trivy#1613]
trivy 0.21.3 has an output for Java jar vulnerabilities.

For example: trivy image docker.io/library/elasticsearch:5.6.13 (on 0.21.3) brings a table with jar libs with log4j vulnerabilities

With trivy 0.22.0 the Java (jar) table has gone
When I type: trivy image docker.io/library/elasticsearch:5.6.13  (on 0.22.) no log4j vulnerability is displayed.

**Comment by afdesk** [comment]
@jdesouza thanks for your report! I could reproduce it, will investigate more!

**Comment by jdesouza** [comment]
Hey, how are you? Any update on this one?

**Comment by afdesk** [comment]
@jdesouza sorry for waiting. we're working on it right now.

**Comment by jdesouza** [comment]
Thanks @afdesk

**Comment by jdesouza** [comment]
trivy i  docker.io/library/elasticsearch:5.6.13 <---- this does not work

trivy i  docker.io/library/elasticsearch:8.0.1  <--- this works

**Comment by tipruzs** [comment]
I'm able to reproduce this even with own images (created with buildah)

`trivy image` is parsing the jar files (--debug) but does not provide any finding in the report.

Extracting the image and retry with `trivy rootfs` brings findings in the report, as soon as the path is not the relative "/" of the image. E.g. the jars are located somewhere under /opt/some/path inside the image and the image gets extracted to /tmp/extracted-image, the `trivy rootfs` command provides findings as soon as the given path points to /tmp/extracted-image/opt. If the provided path points to /tmp/extracted-image, findings are empty again

To exclude build issues i did a retest with grype (against the image) and dependency-check (against the extracted image) and both tools provide the expected findings.
