### ISSUE TITLE
What is the usage of --security-checks?

### ISSUE THREAD

**Issue by tatulea** [aquasecurity/trivy#1619]
I have seen that for the `image` module there is an option called `--security-checks` which can have the values `vuln,config`. What does the `config` value does? I was expecting it to be the same as `trivy config`, but actually it does not return any config file.

In what conditions should I use `--security-checks=config`?

**Comment by knqyf263** [comment]
Please see the documentation.
https://aquasecurity.github.io/trivy/v0.22.0/misconfiguration/filesystem/

**Comment by tatulea** [comment]
That is the difference between `fs` and `rootfs`? Currently I am working on an unpacket container

**Comment by knqyf263** [comment]
No, this option is for specifying vulnerabilities or misconfigurations and can be used with `fs` and `rootfs`. If you want to detect IaC (Infrastructure as Code) misconfigurations as well as vulnerabilities, you have to specify `--security-checks vuln,config`.

**Comment by tatulea** [comment]
What is the difference between `fs` and `rootfs`? What can one detect and the other cannot?

**Comment by knqyf263** [comment]
https://aquasecurity.github.io/trivy/v0.22.0/vulnerability/detection/language/
