### ISSUE TITLE
Use "jq" instead of "grep" in CI examples

### ISSUE THREAD

**Issue by bogdanbarna** [aquasecurity/trivy#162]
I keep having trouble when running the cURL for fetching the latest version of trivy to download inside TravisCI.
I suggest using something like [jq](https://stedolan.github.io/jq/manual/) instead, since that GitHub URL return a JSON anyway.

**Comment by jbergstroem** [comment]
The benefit of using grep here is that it is installed and supported on pretty much every unix-based operating system, where `jq` is an optional add-on.
