### ISSUE TITLE
Support for CentOS Stream

### ISSUE THREAD

**Issue by scottcunningham** [aquasecurity/trivy#1622]
This issue is to track what would be required to support CentOS stream.

Follow-up from https://github.com/aquasecurity/trivy/issues/1550

## The problem

As I understand it, the issue is that Trivy can't apply the RHEL security advisories to CentOS Stream as CentOS Stream now tracks ahead of RHEL in the release cycle.

## Alternatives to RHEL security advisories

One potential solution could be to use NVD feeds instead of the RHEL feeds.

My team has developed some OSS tooling for this in the past: see [rpm2cpe](https://github.com/facebookincubator/nvdtools#rpm2cpe) and [cpe2cve](https://github.com/facebookincubator/nvdtools#cpe2cve).

This would lack some of the nuance in the RHEL feeds -- eg. the NVD feeds don't know about any patches that CentOS have applied to RPMs, however I don't think there's any dataset we can use for that information with the current state of CentOS Stream.

**Comment by mohag** [comment]
It seems like vulnerabilities are showed as "fix available" on CentOS Stream, even after the latest package updates have been installed (i.e. the fix might only be available in RHEL or the version of the fix might be different on CentOS stream.
