### ISSUE TITLE
provide vulnerability attestation based on cosign vuln spec

### ISSUE THREAD

**Issue by developer-guy** [aquasecurity/trivy#1646]
In cosign, we (w/@dentrax @dlorenc) worked on generating a spec for vulnerabilities[^1] and ended up having something like the following 👇
https://github.com/sigstore/cosign/blob/main/specs/COSIGN_VULN_ATTESTATION_SPEC.md

So, I thought it'd be nice to adapt it to Trivy, and maybe we can enable this support with a flag `--attestation <PATH>.` 

[^1]: https://github.com/sigstore/cosign/issues/442

**Comment by knqyf263** [comment]
Thanks. Sounds interesting.

**Comment by developer-guy** [comment]
I can work on this, feel free to assign it to me 🙋🏻‍♂️

**Comment by knqyf263** [comment]
Great to hear that! Could you share how it works before you start working on it?

**Comment by knqyf263** [comment]
@otms61 Could you work on it?

**Comment by otms61** [comment]
@knqyf263  Alright. I will try.
