### ISSUE TITLE
Broken args with v0.23.0, ignore-unfixed / exit-code / no-progress

### ISSUE THREAD

**Issue by vbonini** [aquasecurity/trivy#1657]
## Description
After updating to the new v0.23.0 release, several of the args that we rely on (within gitlab CI) are not found. 

```
trivy --ignore-unfixed --exit-code 1 --cache-dir .trivycache/ --no-progress --severity CRITICAL $REPO
```
```
2022-01-31T09:49:28.569-0700    FATAL   flag provided but not defined: -ignore-unfixed
...
2022-01-31T09:49:40.898-0700    FATAL   flag provided but not defined: -exit-code
...
2022-01-31T09:50:01.488-0700    FATAL   flag provided but not defined: -no-progress
```

## What did you expect to happen?

Command to complete successfully.
- Trivy to not print/output unfixed vulnerabilities.
- Trivy to fail w/exit code 1 on detecting a fixed CRITICAL vulnerability. 
- Trivy to limit output while scanning (no-progress).

## What happened instead?

Trivy fails to run, does not recognize the args that used to work.

## Output of run with `-debug`:

[does not run]

## Output of `trivy -v`:

[does not run]

## Additional details (base image name, container registry info...):

Only occurs with  v0.23.0 release. Rolling back to  v0.22.0 release works fine.

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/issues/1656
