### ISSUE TITLE
flag provided but not defined: -download-db-only

### ISSUE THREAD

**Issue by caiohasouza** [aquasecurity/trivy#1658]
## Description

Hi, 

On 0.23.0 release the param "download-db-only" stopped to working.

## What did you expect to happen?
The param "download-db-only" still continue working.

## What happened instead?
We receive this error:

```
FATAL	flag provided but not defined: -download-db-only
```

## Output of run with `-debug`:

```
docker run -it --rm aquasec/trivy:0.23.0 download-db-only --debug
FATAL	flag provided but not defined: -download-db-only
```

## Output of `trivy -v`:

```
docker run -it --rm aquasec/trivy:0.23.0 -v
Version: 0.23.0
```

## Additional details (base image name, container registry info...):
Docker image aquasec/trivy:0.23.0

**Comment by snowbldr** [comment]
Seems intentional, https://github.com/aquasecurity/trivy/discussions/1515

It seems we will need to change our calls to `trivy image --download-db-only`

**Comment by knqyf263** [comment]
@snowbldr Thanks for answering. Yes, you're right.

**Comment by knqyf263** [comment]
Duplicated
- https://github.com/aquasecurity/trivy/issues/1657
- https://github.com/aquasecurity/trivy/issues/1656
