### ISSUE TITLE
sign and verify trivy binaries/container images with cosign

### ISSUE THREAD

**Issue by developer-guy** [aquasecurity/trivy#1660]
[cosign](https://github.com/sigstore/cosign) is a tool for signing blobs, container images, etc. The real power of cosign comes from storing signatures, attestation, etc in the Rekor Transparency log feature without requiring public/private key pairs. So, we can use cosign to sign and verify Trivy container images, binaries, etc.

> Feel free to assign it to me, I'm willing to work on this.

**Comment by knqyf263** [comment]
We are actually planning to sign our images with cosign, but it would be great if you do that.
