### ISSUE TITLE
Trivy 0.23.0 Incorrect Usage. flag provided but not defined: -f

### ISSUE THREAD

**Issue by s3nl** [aquasecurity/trivy#1661]
Hi

In Trivy 0.23.0, the error message "Incorrect Usage. flag provided but not defined: -f occurs."

I have added "image" to the trivy command like this:
trivy image -f json -o "$OS_VULN_REPORT" --cache-dir "/name off dir" --vuln-type os "path to image"

But then the message "Incorrect Usage. flag provided but not defined: -cache-dir occurs". 

placing the "image" command after: --cache-dir "/var/tmp/name" also does not work.

Thank you in advance for your help!

**Comment by afdesk** [comment]
@s3nl thanks for your interest in `trivy`!
It seems that there is a problem with args.

**note**: `--cache-dir` is a global arg, so you must construct the command as `trivy --cache-dir $CACHE_DIR image ...`

my example works correctly:
```sh
trivy --cache-dir ~/.cache/trivy/ image -f json -o result.json --vuln-type os alpine:latest
```

**Comment by s3nl** [comment]
This works! Thank you for your quick response.
