### ISSUE TITLE
Flag provided but not defined

### ISSUE THREAD

**Issue by ElGusanito** [aquasecurity/trivy#1662]
trivy --skip-dirs /etc --skip-dirs /usr/local/lib/node_modules has been working all along until latest update (0.23.0)

Now I get the following error:  Incorrect Usage. flag provided but not defined: -skip-dirs

**Comment by afdesk** [comment]
@ElGusanito  Did it help you?

**Comment by ElGusanito** [comment]
> 

Yes, that seems to have fixed the issue.  Thanks for your input.

**Comment by afdesk** [comment]
I'm glad to help you.
can we close this issue?
