### ISSUE TITLE
Update overview section in Dockerhub to reflect "trivy image" command change

### ISSUE THREAD

**Issue by nilushancosta** [aquasecurity/trivy#1664]
The overview section in https://hub.docker.com/r/aquasec/trivy still shows `trivy [YOUR_IMAGE_NAME]` as the command to be used to scan a Docker image. 
This should be changed to `trivy image [YOUR_IMAGE_NAME]` as per https://github.com/aquasecurity/trivy/discussions/1515

**Comment by knqyf263** [comment]
Thanks. We will update it shortly.

**Comment by knqyf263** [comment]
Fixed
