### ISSUE TITLE
Trivy on Air-Gapped Environment does not work as expected on the Version 0.23.0

### ISSUE THREAD

**Issue by aasyria** [aquasecurity/trivy#1667]
## Description
Trivy on Air-Gapped Environment does not work as expected on the Version 0.23.0

## What did you expect to happen?
When I copy the files "metadata.json" and "trivy.db" into the cache folder and passing the "--skip-update --offline-scan" it should scan normally without any update

## What happened instead?
It is tiling me that the schema is old 

## Output of run with `-debug`:

```
2022-02-02T09:54:24.190Z	ERROR	The local DB has an old schema version which is not supported by the current version of Trivy CLI. It needs to be updated.
2022-02-02T09:54:24.190Z	FATAL	DB error:
```

## Output of `trivy -v`:

```
Version: 0.23.0
Vulnerability DB:
  Type: Full
  Version: 1
  UpdatedAt: 2022-02-02 06:40:18.277492605 +0000 UTC
  NextUpdate: 2022-02-02 12:40:18.277491505 +0000 UTC
  DownloadedAt: 0001-01-01 00:00:00 +0000 UTC
```

## Additional details (base image name, container registry info...):

It worked when I'm running with older Trivy version.

## Important to know :
when the tool pulling the database, the database version is 2, and it is running without any Errors.
When I change the database Version manually, the tool does not return any Errors, but there is no scanning happened

**Comment by knqyf263** [comment]
@DmitriyLewen Could you look into it? Looks like the database copy just failed according to the output of `trivy -v`.

**Comment by DmitriyLewen** [comment]
Hello @aasyria 
Thanks for your issue!
I will take a look your problem and contact you later.

Regards, Dmitriy.

**Comment by DmitriyLewen** [comment]
Hello @aasyria 
Since v23.0 trivy [uses DB v2](https://github.com/aquasecurity/trivy/discussions/1652).
Please download the new version as indicated [here](https://github.com/aquasecurity/trivy/blob/main/docs/advanced/air-gap.md).

Regards, Dmitriy

**Comment by aasyria** [comment]
> Hello @aasyria Since v23.0 trivy [uses DB v2](https://github.com/aquasecurity/trivy/discussions/1652). Can you explain how you get trivy DB?
> 
> Also, please, download the new version as specified [here](https://github.com/aquasecurity/trivy/blob/main/docs/advanced/air-gap.md) and try scanning.
> 
> Regards, Dmitriy

Thank you for the quick response 
I am downloading the database from the Releases on the Repository 
and then I moved the file into our internally system and extracted as in the Documentation described in the cache folder and tried to start the scan as I described above.

**Comment by aasyria** [comment]
> Hello @aasyria Since v23.0 trivy [uses DB v2](https://github.com/aquasecurity/trivy/discussions/1652). Can you explain how you get trivy DB?
> 
> Also, please, download the new version as specified [here](https://github.com/aquasecurity/trivy/blob/main/docs/advanced/air-gap.md) and try scanning.
> 
> Regards, Dmitriy

I did that and the Version 0.23.0 still does not read the Database Schema correctly. 
please try to debug it in not internet environment.

**Comment by aasyria** [comment]
after reading the new 

> Hello @aasyria Since v23.0 trivy [uses DB v2](https://github.com/aquasecurity/trivy/discussions/1652). Can you explain how you get trivy DB?
> 
> Also, please, download the new version as specified [here](https://github.com/aquasecurity/trivy/blob/main/docs/advanced/air-gap.md) and try scanning.
> 
> Regards, Dmitriy

after reading [uses DB v2](https://github.com/aquasecurity/trivy/discussions/1652) and  [Documentation](https://github.com/aquasecurity/trivy/blob/main/docs/advanced/air-gap.md) i think i can not download the  Database from the Releases

**Comment by 06kellyjac** [comment]
That's correct. Currently you have to pull it from OCI. The guide Dmitriy posted uses `oras`

or you can use this function to use `crane` (from go-containerregistry)

```
getDB() {
	OLDDIR="$PWD"
	TMPDIR="$(mktemp -d)"
	cd "$TMPDIR" || exit 1
	crane pull "$1" file.tar.gz
	FILENAME="$(crane manifest "$1" | jq -r .layers[0].digest | cut -d':' -f2).tar.gz"
	tar xf file.tar.gz "$FILENAME"
	cd "$OLDDIR" || exit 1
	mv "$TMPDIR/$FILENAME" "db.tar.gz"
}

# then run:

getDB ghcr.io/aquasecurity/trivy-db:2
```

**Comment by flavienbwk** [comment]
Is there any way to download this file without a 3rd party tool ?

**Comment by afdesk** [comment]
> Is there any way to download this file without a 3rd party tool ?

@flavienbwk  you can use Trivy )
```sh
$ trivy image --download-db-only
```

**Comment by afdesk** [comment]
i meant that there is a workaround:
```sh
$ trivy --cache-dir ~/my/dir image --download-db-only
```
and then `~/my/dir/db` will contain `metadata.json` and `trivy.db`, you can copy these files.

**Comment by flavienbwk** [comment]
Thanks @afdesk, another native way without even installing the trivy client might be :

```bash
docker run --rm -v ./trivy-data:/root/.cache aquasec/trivy:0.29.2 image --download-db-only
```
