### ISSUE TITLE
Sample ASFF template doesn't include wrapping structure

### ISSUE THREAD

**Issue by Amndeep7** [aquasecurity/trivy#1684]
## Description

Currently the asff template just provides an array of all the findings; however, the format specifies that it should be an object with an attribute called "Findings" that consists of that array of all the findings.

You can see this specification on the ["ASFF Syntax"](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format-syntax.html) and ["BatchImportFindings"](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchImportFindings.html) pages.

## What did you expect to happen?

I expected the templated file to be an object consisting of an attribute called "Findings" pointing at the array of findings.

## What happened instead?

The templated file consisted of an array of findings.

## Output of `trivy -v`:

```
Version: 0.23.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-02-08 00:09:40.961465287 +0000 UTC
  NextUpdate: 2022-02-08 06:09:40.961464687 +0000 UTC
  DownloadedAt: 2022-02-08 04:33:24.241013 +0000 UTC
```

## Additional details (base image name, container registry info...):

Calling command:

```
AWS_REGION=us-east-1 AWS_ACCOUNT_ID=123456789012 trivy image --no-progress --format template --template "@/absolute_path_to/git_clone_of/trivy/contrib/asff.tpl" -o trivy_asff.json golang:1.12-alpine
```

**Comment by afdesk** [comment]
@Amndeep7 thanks for your report!
I'll try to clarify this issue.

**Comment by Amndeep7** [comment]
@afdesk I have a PR attached that'll ideally provide this fix for you.  Just need permission before I sign off on the CLA.

**Comment by oliviergaumond** [comment]
I also commented in the PR. After further investigation, the API does require the wrapping Findings object, but the CLI expects directly the array.

Therefore the sample provided here: https://aquasecurity.github.io/trivy/v0.17.0/integrations/aws-security-hub/ no longer works with the new template. At a minimum the documentation should be updated.
