### ISSUE TITLE
download-db-only and cache-dir option can not be used together

### ISSUE THREAD

**Issue by DanielMcKracken** [aquasecurity/trivy#1686]
I want to download the database into a specific folder, but the command "trivy image --download-db-only --no-progress --cache-dir .cachedir/" shows error message:

"Incorrect Usage: flag provided but not defined: -cache-dir"

Seems like the download-db-only and cache-dir option can not be used together, as the cache-dir is a global option now.

trivy version is 0.23.0

**Comment by knqyf263** [comment]
Try
trivy --cache-dir .cachedir/ image --download-db-only --no-progress

**Comment by DanielMcKracken** [comment]
Thank you very much for the quick response - it works now! Sorry for the buzz :)
