### ISSUE TITLE
--list-all-pkgs flag doesnt exist in version 0.23

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#1689]
Hi

I have moved from version 0.21 to 0.23, and this flag is no longer there. Has the name changed? 

Thanks

**Comment by knqyf263** [comment]
I guess you just missed `image` subcommand.

```
$ trivy image -h | grep list-all-pkgs
   --list-all-pkgs                  enabling the option will output all packages regardless of vulnerability (default: false) [$TRIVY_LIST_ALL_PKGS]
```

**Comment by javixeneize** [comment]
This was the next question, how could i see available flags as the help only display some. Yeah, looks like the syntax format has changed between both versions and now i have to run trivy image --list-all-pkgs $IMAGE. In 0.21 i could run trivy --list-all-pkgs image  $IMAGE

Thanks!

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/issues/1662
