### ISSUE TITLE
--skip-update is not preventing DB update.

### ISSUE THREAD

**Issue by yuriShafet** [aquasecurity/trivy#1690]
## Description
```
ubuntu@$ trivy image --skip-update alpine:3.12
2022-02-08T15:52:22.502Z	ERROR	The first run cannot skip downloading DB
2022-02-08T15:52:22.502Z	FATAL	DB error: database error: --skip-update cannot be specified on the first run
```
## What did you expect to happen?

Trivy should not start DB update procedure.

## What happened instead?

Trivy  started DB update procedure.

## Output of run with `-debug`:

```
ubuntu@$ trivy image --skip-update alpine:3.12
2022-02-08T15:52:22.502Z	ERROR	The first run cannot skip downloading DB
2022-02-08T15:52:22.502Z	FATAL	DB error: database error: --skip-update cannot be specified on the first run
```

## Output of `trivy -v`:

```
Version: v0.23.0
Vulnerability DB:
  Version: 2

```

**Comment by yuriShafet** [comment]
If this issue is confirmed, I could make a PR that resolves it.

**Comment by yuriShafet** [comment]
It seems that Trivy requires for metadata.json existence. After the file is present, update is not required.

**Comment by RoyeeW** [comment]
> It seems that Trivy requires for metadata.json existence. After the file is present, update is not required.

/root/.cache/trivy/db
-rwx------. 1 root root       149 Mar 11 08:50 metadata.json
-rwx------. 1 root root 227598336 Mar 11 08:50 trivy.db

 trivy image **--skip-update** alpine:3.12
 ERROR   The local DB has an old schema version which is not supported by the current version of Trivy CLI. It needs to be updated
FATAL   DB error: database error: validate error: --skip-update cannot be specified with the old DB schema

or
 trivy image **--skip-db-update** alpine:3.12
 ERROR   The local DB has an old schema version which is not supported by the current version of Trivy CLI. It needs to be updated
FATAL   DB error: database error: validate error: --skip-update cannot be specified with the old DB schema

**Comment by swage6** [comment]
+1+1  The same thing happened to me

**Comment by afdesk** [comment]
@RoyeeW @swage6 it seems that you try to use old db with new `trivy`.
the trivy DB schema was updated a few month ago.

please, update your database.

the same issue: https://github.com/aquasecurity/trivy-db/issues/186
