### ISSUE TITLE
Installation on Ubuntu 21.10 Impish not working

### ISSUE THREAD

**Issue by madianas21** [aquasecurity/trivy#1692]
## Description

Installing Trivy according to [official instruction here](https://aquasecurity.github.io/trivy/v0.21.2/getting-started/installation/#debianubuntu)

Installation via `apt` on the latest version of Ubuntu is not supported.

## What did you expect to happen?
Successfull installation

## What happened instead?
```
$ sudo apt-get update
Err:12 https://aquasecurity.github.io/trivy-repo/deb impish Release
  404  Not Found [IP: 185.199.110.153 443]
```

**Comment by YuviGold** [comment]
According to https://aquasecurity.github.io/trivy-repo/, it's not supported
At least we can make the [trivy docs](https://github.com/aquasecurity/trivy/blob/9e08bd44fb3c50360d4b992a4d843824c8272c95/docs/getting-started/installation.md#debianubuntu) to mention it

**Comment by RobMaskell** [comment]
code is using `UBUNTU_RELEASES=$(sort -u <(ubuntu-distro-info --supported-esm) <(ubuntu-distro-info --supported))` and `ubuntu-distro-info --supported-esm` gives
```
trusty
xenial
bionic
focal
jammy
```
on my impish system even though `ubuntu-distro-info --supported` and `ubuntu-distro-info --stable` both include `impish`
In the end I edited `/etc/apt/sources.list.d/trivy.list` and replaced `impish` with `focal` installed trivy and it seems to work

**Comment by knqyf263** [comment]
We use Ubuntu 18.04 for releasing our deb packages on GitHub Actions. I'm wondering if it returns `impish` or not.

**Comment by madianas21** [comment]
> According to https://aquasecurity.github.io/trivy-repo/, it's not supported At least we can make the [trivy docs](https://github.com/aquasecurity/trivy/blob/9e08bd44fb3c50360d4b992a4d843824c8272c95/docs/getting-started/installation.md#debianubuntu) to mention it

`https://aquasecurity.github.io/trivy-repo/` must be outdated too, since changing `impish` to `focal` installs and works fine for me.

**Comment by YuviGold** [comment]
> We use Ubuntu 18.04 for releasing our deb packages on GitHub Actions. I'm wondering if it returns `impish` or not.

I added this PR to have a GHA that tests different distributions' installations. 
https://github.com/aquasecurity/trivy-repo/pull/9
I removed `impish` from there since it wasn't supported, but it can be added after the release will be fixed.

**Comment by afdesk** [comment]
I run Ubuntu 18.04 on DigitalOcean droplet:
```sh
root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

root@ubuntu:~# sort -u <(ubuntu-distro-info --supported-esm) <(ubuntu-distro-info --supported)
bionic
focal
impish
jammy
trusty
xenial
```
it's really strange, because `deb repo` doesn't contain `impish`: https://github.com/aquasecurity/trivy-repo/tree/8acff2496b2a45e967a5c65b1573a69c232ccfe4/deb/dists

but I found errors in logs for `create deb repository` action:
```sh
Adding deb package to impish
Cannot find definition of distribution 'impish'!
There have been errors!
Cannot find definition of distribution 'impish'!
There have been errors!
Cannot find definition of distribution 'impish'!
There have been errors!
Adding deb package to jammy
Cannot find definition of distribution 'jammy'!
There have been errors!
Cannot find definition of distribution 'jammy'!
There have been errors!
Cannot find definition of distribution 'jammy'!
```

**Comment by MatthewEppelsheimer** [comment]
This seems related:

With Ubuntu 21.10 when I `sudo apt-get update` I get:
```
E: The repository 'https://aquasecurity.github.io/trivy-repo/deb impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

After taking @RobMaskell's suggestion to edit `/etc/apt/sources.list.d/trivy.list`, replacing `impish` with `focal`, it runs without error.

**Comment by RobMaskell** [comment]
I unpicked my earlier change, and working now for impish, thanks
