### ISSUE TITLE
--no-progress flag is broken

### ISSUE THREAD

**Issue by ejoubaud** [aquasecurity/trivy#1693]
## Description

Passing the `--no-progress` flag now causes trivy to error out. Looking at ef8a1afcdb4c081c9b75cad7ad7136961778ef27, that doesn't seem intentional.

## What did you expect to happen?

```
#!/bin/bash -eo pipefail
GITHUB_TOKEN=$TRIVY_GITHUB_TOKEN trivy \
  --no-progress \
  -f json \
  -o /tmp/trivy.json \
  myrepo/myimage:git-$CIRCLE_SHA1
```

should work

## What happened instead?

It gives me a `Incorrect Usage. flag provided but not defined: -no-progress` message and error status

**Comment by knqyf263** [comment]
Duplication
- https://github.com/aquasecurity/trivy/issues/1689
- https://github.com/aquasecurity/trivy/issues/1662
- https://github.com/aquasecurity/trivy/issues/1658
- https://github.com/aquasecurity/trivy/issues/1657
- https://github.com/aquasecurity/trivy/issues/1656
- https://github.com/aquasecurity/trivy/issues/1659

**Comment by ejoubaud** [comment]
Right, we hadn't added the `image` command, sorry about the rushed report
