### ISSUE TITLE
Label images based on org.opencontainers.image schema

### ISSUE THREAD

**Issue by msw-kialo** [aquasecurity/trivy#1697]
**Background**: 
The official Trivy images are labeled following [the `org.label-schema` Label Schema](https://label-schema.org). That schema has been deprecated in favor of [the superseeding OCI image spec annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#back-compatibility-with-label-schema).

The first tools rely on the `org.opencontainers.image` and ignore `org.label-schema` labels. For example [RenovateBot](https://docs.renovatebot.com/modules/datasource/#docker-datasource) isn't able to embed a change log upon Trivy image PRs.

**Requirements**:

Add `org.opencontainers.image` image labels instead or in addition to the `org.label-schema` ones. The here used ones are compatible and are only renamed.

I am be open to prepare a PR myself if needed (from my understanding only `goreleaser.yml` needs to be adapted).

**Comment by knqyf263** [comment]
It would be appreciated if you help us.

> from my understanding only goreleaser.yml needs to be adapted

Exactly. We have to fix these templates.

https://github.com/aquasecurity/trivy/blob/3b0b2ed4ce481c7f058d47b0f128c906fb91a958/goreleaser.yml#L110-L119
https://github.com/aquasecurity/trivy/blob/3b0b2ed4ce481c7f058d47b0f128c906fb91a958/goreleaser.yml#L134-L143

**Comment by knqyf263** [comment]
You can decide it 😄
