### ISSUE TITLE
Error in the aquasecurity.github.io documentation

### ISSUE THREAD

**Issue by ilomax** [aquasecurity/trivy#1700]
## Description

The [documentation for the Gitlab CI integration](https://aquasecurity.github.io/trivy/v0.23.0/advanced/integrations/gitlab-ci/) does not correspond to [the example on Github](https://github.com/aquasecurity/trivy/blob/main/docs/advanced/integrations/gitlab-ci.md), when it comes to the Trivy container configuration.

## What did you expect to happen?

Using the example from the doc, I want to generate a vulnerability report from a Gitlab pipeline.

## What happened instead?

The trivy command threw an error : `flag provided but not defined: -download-db-only`, then, after having added the 'image' subcommand : ` flag provided but not defined: -cache-dir`

The command currently is:
`time trivy --download-db-only --no-progress --cache-dir .trivycache/`

But it should be: (working in my case)
`time trivy --cache-dir .trivycache/ image --download-db-only --no-progress`

**Comment by AndreyLevchenko** [comment]
Hi @ilomax 
Thank you for noticing that. We will fix the documentation

Regards
Andrey

**Comment by pimperator** [comment]
Same issue here!

The documentation [here](https://aquasecurity.github.io/trivy/v0.18.3/integrations/gitlab-ci/) with the headline `GitLab CI using Trivy container`
with the following error:
```
$ time trivy --download-db-only --no-progress --cache-dir .trivycache/
Incorrect Usage. flag provided but not defined: -download-db-only
```

**Comment by pimperator** [comment]
ok, my bad. I just saw that I am reading the documentation of an older tag. this is the new one: https://aquasecurity.github.io/trivy/v0.23.0/advanced/integrations/gitlab-ci/

**Comment by knqyf263** [comment]
Looks like you found out the cause. Please let me close this issue, but feel free to reopen it if you have any other issues.
