### ISSUE TITLE
Questions about cache and Update DB with custom cache path

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#1703]
Hi

I have a couple of questions about how to use cache. If i set my own path for my cache, when i run the scan with the --cache-dir flag, will the database in that path be updated? I dont know if this feature only works with the default cache path

Also, related to cache. If i have some cache, and a new vulnerability is affecting one of my images, when it is re-scanned with trivy with the new DB that contains that vulnerability identifier, will it be rescanned and detect that vulnerability, or will it just use what was cached from the previous scan?

Thanks

**Comment by knqyf263** [comment]
@DmitriyLewen Can you help @javixeneize?

**Comment by DmitriyLewen** [comment]
Hello @javixeneize 
Thanks for your interest in trivy!

1. The database is stored in the cache directory. If you use `--cache-dir your/cache/dir` flag, database will be downloaded in `your/cache/dir`. 
2. Trivy does not store vulnerability information, only image information. If you rescan your image with a new DB (with a new vulnerabilities), trivy will detect new vulnerabilities.

Regards, Dmitriy
