### ISSUE TITLE
packages not listed

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#1714]
Hi

Sometimes when scanning an image, using the list all packages flag, it returns no java packages. After cleaning the cache and rescanning again, it works fine, but i am loosing the cache for all the other images i had scanned

Is this a known issue? Is there any way to clean the cache only for a given image?

Thanks

**Comment by afdesk** [comment]
@javixeneize thanks for your interest in `trivy`!
could you show your `trivy` options? 
I'd like to reproduce an issue.
thanks a lot.

**Comment by javixeneize** [comment]
Hi
It is quite weird, it happens randomly, i have not seen any pattern that helps me to identify what might be the problem. As explained, adter cleaning the cache, if i rescan the image again it works

Options are pretty straightforward. trivy -d image $IMAGE

**Comment by afdesk** [comment]
we saw such problems for scanning jar apps. 
it was due to a lot of API requests.
so `trivy` has `--offline-scan` option now.

Could you check this option?
```sh
trivy -d image --offline-scan $IMAGE
```

**Comment by javixeneize** [comment]
Thanks for the answer. Ok, i will try that. 

Will the DB be updated with this command, or do i need to do an update-only before running it?

Thanks

**Comment by afdesk** [comment]
the DB will be updated.

**Comment by afdesk** [comment]
@javixeneize it's really strange behavior, but i couldn't reproduce it.
can you try to scan next image (I use it for tests):
```sh
$ trivy -d image -f json -o report.json --list-all-pkgs elasticsearch:7.14.2
```

**Comment by javixeneize** [comment]
Yeah its strange. I scanned that image and it works fine. It is a random behaviour i think when i scan a lot of images in a row

Using debug doesnt add much value, is there anything else i can do to provide more level of detail?

Thanks

**Comment by afdesk** [comment]
Hi @javixeneize!
could you try to reproduce your issue with the latest version `v0.26.0`?
thanks!

**Comment by knqyf263** [comment]
I believe it is no longer a problem after migrating to trivy-java-db.
