### ISSUE TITLE
Scanning libraries in private repository (codeartifact)

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#1727]
Hi

I am trying to scan a pom.xml i have with trivy filesystem. 
In the pom.xml i have some dependencies that i have built and are in codeartifact, those are not in the public maven repository. I am having an error saying those dependencies cant be resolved 

Is there any way to force trivy to use a custom settings.xml to point to a specific repository to resolve my dependencies?

My understanding is that trivy will build the tree, and if i have a library in a custom repository, if it can resolve it, it will resolve and scan the dependencies i have in my library, right?

Thanks

**Comment by AndreyLevchenko** [comment]
Hi @javixeneize 
Thank you for feedback
Unfortunatelly trivy doesn't support access to repositories configured in `settings.xml` at the moment
