### ISSUE TITLE
Error in image scan: failed to scan image: failed to analyze OS: Unknown OS

### ISSUE THREAD

**Issue by cchung100m** [aquasecurity/trivy#173]
**Description**

Hi trivy team,
I encounter the error **failed to scan image: failed to analyze OS: Unknown OS** when using trivy to scan my image which OS is debian 9. I would appreciate if you can add support of debian 9.

many thanks,

**What did you expect to happen?**
trivy should support debian 9

**What happened instead?**
trivy throw an unknown OS error message 

**Output of run with `-debug`:**

```
root@localhost:~# trivy  localhost:5000/myImage:latest --clear-cache --debug
2019-10-01T09:11:35.563Z	INFO	Updating vulnerability database...
2019-10-01T09:11:36.990Z	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2019-10-01T09:11:37.162Z	FATAL	error in image scan: failed to scan image: failed to analyze OS: Unknown OS
```

**Output of `trivy -v`:**

```
root@localhost:~# trivy -v
trivy version 0.1.6
```

**myImage OS version:**
```
/bin # cat /proc/version
Linux version 4.9.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.144-3 (2019-02-02)
```

**Comment by knqyf263** [comment]
@cchung100m Thank you for taking a time to file an issue. What is your base image? I know it is Debian 9, but I need to know the image name. In other words, `FROM` line.

**Comment by cchung100m** [comment]
Hi @knqyf263 

Sorry for the late reply.

I download the image from private registry so that I don't have its dockerfile.

I also tried to leverage third-party tool `chenzj/dfimage` to lookup its `FROM` line,
however the  `FROM` line of output shows `registry:5000/myImage:latest` which doesn't help.

I would appreciate if you can guide me how to provide more useful information for this issue.

many thanks,

**Comment by knqyf263** [comment]
@cchung100m Would you show me the result with `--debug` option?

Then, let me know the result by the following commands.
```
$ docker run [YOUR_IMAGE] cat /etc/lsb-release
$ docker run [YOUR_IMAGE] cat /etc/debian_version
```

**Comment by cchung100m** [comment]
Hi @knqyf263 

Thanks for prompt reply.

I run the commands and get results above:

```
/ # cat /etc/lsb-release
cat: can't open '/etc/lsb-release': No such file or directory
/ # cat /etc/debian_version
cat: can't open '/etc/debian_version': No such file or directory
/ # cat /proc/version
Linux version 4.9.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.144-3 (2019-02-02)
```
```
root@localhost:~# trivy registry:5000/myImage:latest --debug
2019-10-21T01:12:52.320Z	INFO	Updating vulnerability database...
2019-10-21T01:13:27.083Z	INFO	Updating nvd data...
 439 / 439 [====================================================================================================================================================================================] 100.00% 2s
2019-10-21T01:13:29.932Z	INFO	Updating alpine data...
 18 / 18 [======================================================================================================================================================================================] 100.00% 0s
2019-10-21T01:13:30.882Z	INFO	Updating redhat data...
 3789 / 3789 [===============================================================================================================================================================================] 100.00% 1m33s
2019-10-21T01:15:04.433Z	INFO	Updating debian data...
 2049 / 2056 [==================================================================================================================================================================================]  99.66% 5s
2019-10-21T01:15:10.099Z	INFO	Updating debian-oval data...
 21184 / 21184 [=============================================================================================================================================================================] 100.00% 1m15s
2019-10-21T01:16:25.380Z	INFO	Updating ubuntu data...
 6050 / 6050 [=================================================================================================================================================================================] 100.00% 39s
2019-10-21T01:17:04.965Z	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2019-10-21T01:17:05.170Z	FATAL	error in image scan: failed to scan image: failed to analyze OS: Unknown OS
```

**Comment by vjtm** [comment]
Hi there,

I've seen the same message error when using ```FROM scratch``` images (ie, using Go static binaries)

**Comment by cchung100m** [comment]
Hi @knqyf263 

I found trivy cannot scan [busybox](https://hub.docker.com/_/busybox) image as well.

```
[root@ ~]# docker pull busybox:latest
Trying to pull repository docker.io/library/busybox ... 
latest: Pulling from docker.io/library/busybox
7c9d20b9b6cd: Pull complete 
Digest: sha256:fe301db49df08c384001ed752dff6d52b4305a73a7f608f21528048e8a08b51e
Status: Downloaded newer image for docker.io/busybox:latest

[root@ ~]# trivy docker.io/busybox:latest --debug
2019-10-25T06:14:37.107Z	INFO	Updating vulnerability database...
2019-10-25T06:14:38.707Z	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2019-10-25T06:14:38.733Z	FATAL	error in image scan: failed to scan image: failed to analyze OS: Unknown OS
```

**Comment by knqyf263** [comment]
@cchung100m Is your image based on `scratch` like @vjtm ? `scratch` has no package manager. Trivy doesn't support it.

**Comment by cchung100m** [comment]
@knqyf263 

I am afraid so, please feel free to close this PR if `Trivy` doesn't support `scratch` currently.

**Comment by knqyf263** [comment]
Yes, Trivy doesn't support `scratch`. `scratch` doesn't have a package manager, so I think it is less effective to scan vulnerabilities.

**Comment by tisc0** [comment]
> Yes, Trivy doesn't support `scratch`. `scratch` doesn't have a package manager, so I think it is less effective to scan vulnerabilities.

I'm surprised to read that : one of the specificities (and perks) of a distroless, is  the absence of packager manager. 
As far as I know, Clair is not capable of scanning distroless, like google distroless ; Trivy can, checking dependencies relying on .lock files (hope seeing Go support soon ;]).
What did I miss ?

**Comment by knqyf263** [comment]
`scratch` doesn't have any operating system. But Google Distroless is based on Debian. In short, `distroless` contains some dpkg packages. They are different in this respect.
https://github.com/GoogleContainerTools/distroless#base-operating-system

If you want to scan lock files on scratch, please specify `--vuln-type library`.

**Comment by tisc0** [comment]
@knqyf263 Thanks Fukuda sempai ! 

Would it be interesting then to have this option as a fall-back, rather than having to create a condtional call of the program in our wrap script, depending of the image we want to analyse (which could quickly be annoyingly hard, if not impossible) and put the right switches.

I'm actually using this : 

```
(...)

# function to check the need to update DBs before starting looping in images
_check_if_updatedb_is_needed(){
        if [[ ! $(find $CACHE_DIR -type f -iname 'trivy.db' -mmin -240 | grep '.') ]] \
        || [[ ! -d ${CACHE_DIR} ]]
        then
                /usr/local/bin/trivy --no-progress --refresh
        else
                echo 'No need to update Trivy DB'
        fi
}

(...)

# Variables
TRIVY='/usr/local/bin/trivy'
CACHE_DIR='.cache'
SEVERITY='--severity MEDIUM,HIGH,CRITICAL'
TRIVY_OPTIONS="
--skip-update 
--debug 
--cache-dir $CACHE_DIR 
--exit-code 1 
--no-progress 
${SEVERITY}
"
(...)

# Somewhere in the loop, program call
${TRIVY} ${TRIVY_OPTIONS} "${image}"
(...)
```

By not specifying the --vuln-type (os or library), I'm expecting trivy to understand the appropriate behavior depending of what it's finding while opening the image.

Integrated as a job/stage in a Gitlab CI, I'm analyzing images in production in multiple Kubernetes clusters/node pools. I don't have the control of what's being pushed in production, so I wanna be able to analyse images, whatever their format.

Makes sens to me than the default "--vuln-type os,library" would be able to try 'library' analysis if 'os' analysis is not possible.

Thanks for your feedback
