### ISSUE TITLE
Restructuring Docs under the Diataxis framework

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/trivy#1736]
The [diataxis framework](https://diataxis.fr/) structures documentation under four major categories:
* Tutorials
* How to guides
* Explanation
* References
![image](https://user-images.githubusercontent.com/33576047/154695447-59db19de-5726-415f-8d28-42b0eea40d17.png)

**Goals**
1. Using a framework to ensure the documentation can be updated in a coherent manner by different people over time
2. Establishing consistency across our documentation for different projects
3. Allow different users to find the documentation that best suits their needs and capabilities  

**Implementing the framework**
Rather than rewriting the entire documentation the idea is to introduce incremental changes over time that follow the framework.

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/pull/1887
