### ISSUE TITLE
Trivy TF sec ingress false positives (upgrade tfsec)

### ISSUE THREAD

**Issue by natefear** [aquasecurity/trivy#1737]
## Description

False positives on ingress resources when using Trivvy's integrated TF sec v0.63.1 vs standalone TF sec v1.4.1
  
## What did you expect to happen?

Shouldn't see "AVD-K8S-0001: Public egress should not be allowed via network policies" on polices with no egress.
As I do not get these false positives when running TF sec v1.4.1 looks like Trivvy needs to update to tfsec latest.

Looks like Trivy gets tfsec from the fanal pkg, so this may  be solved when https://github.com/aquasecurity/fanal/pull/406 is merged and https://github.com/aquasecurity/trivy/blob/477dc7d5f9628e714f390d7c984afd6da4df6ce5/go.mod#L11 is updated in trivy?

**Comment by owenrumney** [comment]
Hey @natefear - Trivy has got behind on tfsec but as you say, that fanal merge should solve this issue. 

#1747 updates to the latest fanal so it will be in the next release

**Comment by natefear** [comment]
Thanks for the quick action Owen :)
