### ISSUE TITLE
🐛 False-Positive Against Multi-Line Dockerfile Commands

### ISSUE THREAD

**Issue by AErmie** [aquasecurity/trivy#1740]
## Description

When using Trivy to scan a Dockerfile, it reports that DS015 (ie. 'yum clean all' missing) as a Dockerfile Security Check failure. If you include the `yum clean all` command on a new line, the vulnerability is still detected. However, if you include the `yum clean all` command on the **same** line, Trivy will successfully see it as present and the vulnerability will no longer be reported.

**Multi-Line**
```YAML
RUN yum install awscli -y
RUN yum update -y && \
    yum clean all
```

**Single-Line**
```YAML
RUN yum install dotnet-sdk-5.0 -y && yum clean all
```

## What did you expect to happen?

I expect Trivy to be able to accept multi-lines as a valid implementation.

## What happened instead?

I consider this a "false-positive" since a multi-line implementation will still achieve the same desired results.

## Output of run with `-debug`:

```CMD
2022-02-18T12:28:05.739Z	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-02-18T12:28:05.744Z	DEBUG	cache dir:  /root/.cache/trivy
2022-02-18T12:28:05.744Z	DEBUG	Vulnerability type:  []
2022-02-18T12:28:05.744Z	DEBUG	Failed to open the policy metadata: open /root/.cache/trivy/policy/metadata.json: no such file or directory
2022-02-18T12:28:05.744Z	INFO	Need to update the built-in policies
2022-02-18T12:28:05.744Z	INFO	Downloading the built-in policies...
15.56 KiB / 15.56 KiB [-----------------------------------------------------------] 100.00% ? p/s 0s2022-02-18T12:28:06.180Z	DEBUG	Digest of the built-in policies: sha256:e4f955fb769f1c45b271088199c1f234e070f59af245c48de970576db6017391
2022-02-18T12:28:06.296Z	DEBUG	OS is not detected and vulnerabilities in OS packages are not detected.
2022-02-18T12:28:06.296Z	INFO	Detected config files: 1
2022-02-18T12:28:06.296Z	DEBUG	Scanned config file: Dockerfile
2022-02-18T12:28:06.296Z	DEBUG	Found an ignore file .trivyignore
2022-02-18T12:28:06.296Z	DEBUG	These IDs will be ignored: []
```

## Output of `trivy -v`:

```
Digest: sha256:499e0c9cfb49874998323289bd0062774c758252229bf612f05668fec2b0471d
Status: Downloaded newer image for aquasec/trivy:latest
docker.io/aquasec/trivy:latest
Version: 0.23.0
```

## Additional details (base image name, container registry info...):

- Base image: amazonlinux:2

I am executing Trivy via the Docker method (ie. not installed locally).

**Comment by knqyf263** [comment]
@owenrumney @liamg Could you take a look?

**Comment by liamg** [comment]
Hi @AErmie, Trivy is actually finding the issue on the first command in your example. It has picked up that you have a `yum install ...` command without a `yum clean` as part of the same `RUN`. The multiline step is not the issue here.

It is generally considered best practice to combine your package manager commands together to reduce layers, i.e.:

```
RUN yum install awscli -y && \
   yum update -y && \
   yum clean all
```

If you combine all actions into one `RUN` as above, Trivy will show no issues.

Hope that helps!

**Comment by AErmie** [comment]
Thanks @liamg. I'm curious though, since the `yum install` command is chained with a `yum clean` command at the end, why is it still flagged as an issue?
