### ISSUE TITLE
Error while scanning with normal local user

### ISSUE THREAD

**Issue by gopurx** [aquasecurity/trivy#176]
trivy is installed in centos docker image using `rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.1.6/trivy_0.1.6_Linux-64bit.rpm`

when running trivy scanner with default user which is root works fine, but throws an error with a locally created user while trivy scanner. Below is the command used to invoke scanning, works file while running as root. Any suggestions on how to circumvent this error?
```
trivy --auto-refresh --format json -o scan.json --cache-dir /mntshare/trivy myreg.reg.com/centos7.6.1810
```

Error:

```
2019/10/02 17:41:33 failed to mkdir all: mkdir /.cache: permission denied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x605f3a]

goroutine 40 [running]:
bufio.(*Reader).Read(0xc000262420, 0xc000412b80, 0xa, 0x200, 0xc0003eb980, 0x4097d5, 0xd92ac0)
	/usr/local/go/src/bufio/bufio.go:223 +0x21a
io.ReadAtLeast(0x104e220, 0xc000262420, 0xc000412b80, 0xa, 0x200, 0xa, 0x35, 0xc0003ba200, 0xc000056700)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
compress/gzip.(*Reader).readHeader(0xc000412b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/compress/gzip/gunzip.go:175 +0xd7
compress/gzip.(*Reader).Reset(0xc000412b00, 0x0, 0x0, 0x35, 0x0)
	/usr/local/go/src/compress/gzip/gunzip.go:113 +0x124
compress/gzip.NewReader(0x0, 0x0, 0x1, 0xc00000db80, 0x0)
	/usr/local/go/src/compress/gzip/gunzip.go:94 +0x58
github.com/aquasecurity/fanal/extractor/docker.DockerExtractor.Extract.func1(0xc000390680, 0xc00003f0f0, 0xc00003bbf0, 0x1b, 0xc00003bc0c, 0x6, 0xc00003bc13, 0x6, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20190819081512-f04452b627c6/extractor/docker/docker.go:209 +0x79
created by github.com/aquasecurity/fanal/extractor/docker.DockerExtractor.Extract
	/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20190819081512-f04452b627c6/extractor/docker/docker.go:194 +0x5bf
```

**What did you expect to happen?**

**Output of `trivy -v`:**
```
trivy version 0.1.6
```

**Additional details (base image name, container registry info...):**

**Comment by gopurx** [comment]
latest observation:
based on error `failed to mkdir all: mkdir /.cache: permission denied`, created directory /.cache with 777 permission using root user. Now running trivy scanner using local user did worked without any error.

As per original command `trivy --auto-refresh --format json -o scan.json --cache-dir /mntshare/trivy myreg.reg.com/centos7.6.1810`, trivy supposed to be using `/mntshare/trivy` as cache directory but some how still referring to default path for --cache-dir option (default: "/.cache/trivy").

Any suggestions? Am i supposed to use this work around or any better approach to handle this situation.

**Comment by gopurx** [comment]
Can anybody review this and update, thank you

**Comment by gopurx** [comment]
Do we have list of privileges or roles a user should possess while running trivy scanner?

**Comment by krol3** [comment]
Hi! @gopurx, Do you still have this problem?

**Comment by paulliss** [comment]
Hey!
@krol3 
I've solved this by cheking UID & GUI of a user in the container.
  So I my case it has 10000:10000  id's.  When I set permissions for a cache folder
  chown 10000:10000 /mntshare/trivy
  chmod 754 /mntshare/trivy
  
It's working like a charm ))
