### ISSUE TITLE
Error `mkdir /.cache: permission denied` when using Trivy Docker container

### ISSUE THREAD

**Issue by AErmie** [aquasecurity/trivy#1772]
## Description

While running Trivy via the Docker container method, I encounter an error when Trivy tries to create the cache directory. 

```YAML
mkdir TrivyTemp
mkdir TrivyIACReport

docker run --rm \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume $(System.DefaultWorkingDirectory)/TrivyTemp:/tmp/.cache/ \
  --user $(id -u) \
  --group-add $(id -g) \
  --name Trivy aquasec/trivy:latest --debug image \
  --ignore-unfixed --exit-code 0 \
  $(runtimeDockerImageName):$(buildVersion)
```

## What did you expect to happen?
I expect to be able to mount a pre-created directory for use as the temp directory, since (because of setting the container to run as the agent user and not root), it should have the same permissions to the pre-created directory.

## What happened instead?

The following error is thrown:

```CMD
2022-02-25T20:24:40.624Z	FATAL	cache error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:53
  - unable to initialize the cache:
    github.com/aquasecurity/trivy/pkg/commands/artifact.initFSCache
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:99
  - unable to initialize fs cache:
    github.com/aquasecurity/trivy/pkg/commands/operation.NewCache
        /home/runner/work/trivy/trivy/pkg/commands/operation/operation.go:61
  - failed to create cache dir:
    github.com/aquasecurity/fanal/cache.NewFSCache
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220221141823-58a5d668e45f/cache/fs.go:23
  - mkdir /.cache: permission denied
```

## Output of `trivy -v`:

```
Digest: sha256:ab0f7b8f3846ee71564fa355243f2b4c8b8e5ac98abd35e1085aff340de3a0b8
Status: Downloaded newer image for aquasec/trivy:latest
docker.io/aquasec/trivy:latest
Version: 0.24.0
```

## Additional details (base image name, container registry info...):

The Trivy docker container is being run on a self-hosted build server in Azure DevOps

**Comment by afdesk** [comment]
@AErmie thanks for your report!
I've set `--cache-dir` option and it works for me:
```sh
...
  --name Trivy aquasec/trivy:latest --debug --cache-dir /tmp/.cache image \
...
```

**Comment by AErmie** [comment]
Hey @afdesk, I got this to work, but I had to set the `--cache-dir` to a different path, namely `/.cache` instead of `/tmp/.cache`.

The challenge is, the documentation is inconsistent. 

For example, on the GitHub repo, there is no reference or example about the cache directory. 

On the AquaSecurity Trivy documentation [(specifically the Docker installation section)](https://aquasecurity.github.io/trivy/v0.24.1/getting-started/installation/#docker), it shows `/root/.cache/`.

On the [CLI `image`](https://aquasecurity.github.io/trivy/v0.24.1/getting-started/cli/image/) documentation it doesn't list `--cache-dir` as a command (where it were I original became confused, thinking that the command no longer exists).

On this [GitLab page](https://git.shivering-isles.com/github-mirror/aquasecurity/trivy/-/tree/v0.10.0#error-fatalunable-to-initialize-the-cache-failed-to-create-cache-dir-mkdir-rootcache-permission-denied) it shows `/tmp/.cache/`.

And when you run Trivy, the actual debug error output shows that it's trying to use `/.cache` instead of `/tmp/.cache`.

```CMD
2022-02-24T16:17:47.059Z	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-02-24T16:17:47.059Z	FATAL	cache error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:53
  - unable to initialize the cache:
    github.com/aquasecurity/trivy/pkg/commands/artifact.initFSCache
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:99
  - unable to initialize fs cache:
    github.com/aquasecurity/trivy/pkg/commands/operation.NewCache
        /home/runner/work/trivy/trivy/pkg/commands/operation/operation.go:61
  - failed to create cache dir:
    github.com/aquasecurity/fanal/cache.NewFSCache
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220221141823-58a5d668e45f/cache/fs.go:23
  - mkdir /.cache: permission denied
 ```

It would be appreciated to have some unification of documentation and details about all the command-line options when running Trivy.

**Comment by mirekphd** [comment]
It's due to the root requirement when creating the temporary cache folder. 

My solution may help if you run the scanner with a predictable UID. I had to create the `.cache` folder on the host (as root) and then (also as root) changed the ownership of the host `.cache` folder to grant it to the user with which the container was to be run.

**Comment by josehenrique-dev** [comment]
I've set `--cache-dir /tmp/.cache` option and it works for me too, but that's a palliative job, i think use a redis is better than simply use a root user in a container.
