### ISSUE TITLE
Add "ignore until date" feature to .trivyignore

### ISSUE THREAD

**Issue by stealthrabbi** [aquasecurity/trivy#1779]
It would be nice if there was a way to optionally specify the length of time to ignore a finding by trivy in trivyignore. e.g. there may be a vulnerability I want to ignore now, but want to revisit it in 3 months. 

For example, in the gradle plugin for DependencyCheck, an `until=date` attribute can be added to the suppressions file per suppression.
https://jeremylong.github.io/DependencyCheck/index.html

**Comment by knqyf263** [comment]
I think you can leverage Rego.
https://aquasecurity.github.io/trivy/v0.24.2/vulnerability/examples/filter/

The policy will be something like this:
https://play.openpolicyagent.org/p/nGmZEQrB2t

**Comment by knqyf263** [comment]
I realized this issue is duplicate of https://github.com/aquasecurity/trivy/issues/1779.
