### ISSUE TITLE
Configurable database repository (`dbRepository`)

### ISSUE THREAD

**Issue by tenstad** [aquasecurity/trivy#1783]
Add ability to configure repository where trivy database is pulled.

[`dbRepository`](https://github.com/aquasecurity/trivy/blob/2f2d8222e468688bd024322e3d675dd18c2f3398/pkg/db/db.go#L19) is currently `"ghcr.io/aquasecurity/trivy-db"`.  
I would like it to be configurable, so that the trivy db may be updated in an air-gapped envionment where a local container registry is used.

**Comment by knqyf263** [comment]
Thanks for your suggestion. You probably already know, but Trivy can work even in an air-gapped environment.
https://aquasecurity.github.io/trivy/v0.24.2/advanced/air-gap/

Please let me see how many users are using a local OCI registry in an air-gapped environment.

To the community: Please add a comment or upvote if you need this feature.

**Comment by tenstad** [comment]
Thank you for the response! oras is a bit more work, compared to a configurable `dbRepository`, but not that bad.

```Dockerfile
FROM <registry>/oras-project/oras:v0.12.0 as db
RUN oras pull <registry>/aquasecurity/trivy-db:2 -a \
    && mkdir -p /.cache/trivy/db \
    && tar -xzf db.tar.gz -C /.cache/trivy/db

FROM <img>

COPY --from=db /.cache/trivy /root/.cache/trivy
```
```Dockerfile
FROM <img>

RUN trivy image --download-db-only --db-repository <registry>/aquasecurity/trivy-db
```

**Comment by evandeaubl** [comment]
I'm running the client/server configuration in an air-gapped Kubernetes cluster, so this would be really useful. Right now it requires extra infrastructure and hand jamming to get the database into the image and keep it up to date, when with a configurable dbRepository, trivy could do the update the exact same way it does in the non-air-gapped config.

**Comment by knqyf263** [comment]
Closed by https://github.com/aquasecurity/trivy/pull/1873
