### ISSUE TITLE
invalid composer.lock format: invalid character ',' looking for beginning of object key string

### ISSUE THREAD

**Issue by acarsercan** [aquasecurity/trivy#179]
Hi,

I'm running trivy like so
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock     -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy lss:latest`

```
+ trivy --exit-code 1 --severity HIGH,CRITICAL --quiet --input docker/image

2019-10-04T09:24:19.801Z	INFO	Updating vulnerability database...

2019-10-04T09:25:33.288Z	INFO	Updating nvd data...

2019-10-04T09:26:18.586Z	INFO	Updating alpine data...

2019-10-04T09:26:23.762Z	INFO	Updating redhat data...

2019-10-04T09:26:27.712Z	INFO	Updating debian data...

2019-10-04T09:26:39.378Z	INFO	Updating debian-oval data...

2019-10-04T09:26:46.362Z	INFO	Updating ubuntu data...

2019-10-04T09:26:55.645Z	INFO	Detecting Alpine vulnerabilities...

2019-10-04T09:26:55.649Z	FATAL	error in image scan: failed to scan libraries: failed to analyze libraries: failed to analyze libraries: invalid composer.lock format: invalid character ',' looking for beginning of object key string

```
Anyone else come across this?

Regards

**Comment by acarsercan** [comment]
debug

`2019-10-17T07:15:25.082Z	FATAL	error in image scan:
    github.com/aquasecurity/trivy/pkg.Run
        /app/pkg/run.go:169
  - failed to scan libraries:
    github.com/aquasecurity/trivy/pkg/scanner.ScanImage
        /app/pkg/scanner/scan.go:67
  - failed to analyze libraries:
    github.com/aquasecurity/trivy/pkg/scanner/library.Scan
        /app/pkg/scanner/library/scan.go:63
  - failed to analyze libraries:
    github.com/aquasecurity/fanal/analyzer.GetLibraries
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20190930214148-1d3b788f4003/analyzer/analyzer.go:195
  - invalid composer.lock format:
    github.com/aquasecurity/fanal/analyzer/library/composer.composerLibraryAnalyzer.Analyze
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20190930214148-1d3b788f4003/analyzer/library/composer/composer.go:40
  - invalid character ',' looking for beginning of object key string
`

**Comment by imnotjames** [comment]
Do you have the composer lock file in question?

**Comment by acarsercan** [comment]
Thanks for the reply. Any way to get trivy to spit this out? I have a lot of composer.lock files under 

```node_modules/@snyk/composer-lockfile-parser/test/fixtures/vulnerable_project/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/missing_compose_json/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/proj_with_aliases_external_github/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/proj_with_aliases/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/circular_deps_php_project/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/lockfile-invalid-json/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/many_deps_php_project/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/circular_deps_special_test/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/composer-invalid-json/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/no_project_name/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/missing_package_prop/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/proj_with_no_deps/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/interdependent_modules/composer.lock
node_modules/@snyk/composer-lockfile-parser/test/fixtures/no_branch_alias/composer.lock
```

I will state the obvious, something to do with synk

**Comment by imnotjames** [comment]
Looks like snyk has unit tests and intentionally broken composer lock files.

One way to handle this is to ignore invalid composer lock files that can't be parsed as they're invalid and not technically composer lock files.  I can handle this as a PR.

Alternatively, we could add them to some sort of "ignore" file?  The `.trivyignore` only seems to handle vulnerabilities to ignore.  Perhaps that feature could be updated to handle files as well?

**Comment by knqyf263** [comment]
@imnotjames Thank you. I think we should ignore lock files under `node_modules` and `vendor` directory. So, I fixed the behavior. Give me a time to think of your PR.
