### ISSUE TITLE
Wrong version of transitive dependency picked by trivy in maven applications

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#1790]
Hi

I briefly explained this on #1728, but i will open a new ticket to avoid mixing both issues

Trivy is not resolving transitive libraries in the same way as maven does. In my example, the maven tree contains org.springframework:spring-core:jar:5.2.15.RELEASE, while trivy reports i am using  org.springframework:spring-core:jar:4.1.4.RELEASE

To replicate it, use the following dependencies in a pom.xml

`<dependencies>

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <version>2.3.12.RELEASE</version>
        <scope>test</scope>
    </dependency> 
    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <version>3.2.1</version>
    </dependency>

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
        <version>1.2.1.RELEASE</version>
    </dependency>

    
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-security</artifactId>
        <version>1.2.1.RELEASE</version>
    </dependency>

    
    <dependency>
        <groupId>org.springframework.security.kerberos</groupId>
        <artifactId>spring-security-kerberos-core</artifactId>
        <version>1.0.1.RELEASE</version>
    </dependency>

    <dependency>
        <groupId>org.springframework.security.kerberos</groupId>
        <artifactId>spring-security-kerberos-client</artifactId>
        <version>1.0.1.RELEASE</version>
    </dependency>

    <dependency>
        <groupId>org.springframework.security.kerberos</groupId>
        <artifactId>spring-security-kerberos-web</artifactId>
        <version>1.0.1.RELEASE</version>
    </dependency>

    <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-ldap</artifactId>
        <version>5.6.2</version>
    </dependency>

    
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>2.4.4</version>
    </dependency>

    
    <dependency>
        <groupId>javax.validation</groupId>
        <artifactId>validation-api</artifactId>
        <version>1.1.0.Final</version>
    </dependency>

</dependencies>`

Since spring-boot-starter-test:2.3.12 is the first dependency, maven builds the tree with those transitive dependencies (spring-core 5.2.15). If you move that dependency to the end of the dependencies list, then, the tree is built with spring-core 4.1.4, which is the version trivy is resolving

Thanks

**Comment by javixeneize** [comment]
@knqyf263 this is the ticket for what we briefly discussed in #1728

**Comment by knqyf263** [comment]
@javixeneize Thanks for the detail.
@DmitriyLewen Can you look into it?

**Comment by DmitriyLewen** [comment]
Hello @javixeneize 

Thank you for your report!
Checked your pom file.
*org.springframework.boot:spring-boot-starter-test* is ignored because it has the `test` scope tag . Trivy skip this tag.
[org.springframework.boot:spring-boot-starter-web](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web/1.2.1.RELEASE) has org.springframework:spring-core:jar:**4.1.4.RELEASE** library. Trivy takes this version.

Regards, Dmitriy

**Comment by javixeneize** [comment]
right, it makes sense, it confused me that the library was in the tree with a different version

[INFO] |  +- org.springframework:spring-core:jar:5.2.15.RELEASE:compile

Thanks
