### ISSUE TITLE
Trivy 0.23.0 - No space left issue with trivy image  scan

### ISSUE THREAD

**Issue by murugananthsubramani** [aquasecurity/trivy#1796]
Hi Team, 

I'm facing the below issue when i initiate a new image scan in trivy. 

trivy --cache-dir /data/disk1/ --debug image --severity HIGH,CRITICAL  --timeout 15m <<image_name>>

Please help me on this.

logs:     
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:70
  - image scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:219
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:96
  - analyze error:
    github.com/aquasecurity/fanal/artifact/image.Artifact.Inspect
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220129174924-b9e05fcccc57/artifact/image/image.go:105
  - failed to analyze layer: sha256:1414cd8be9363ee31513d9f810a52399205fa281d2b3b059d21c287f08e292c3 :
    github.com/aquasecurity/fanal/artifact/image.Artifact.inspect.func1
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220129174924-b9e05fcccc57/artifact/image/image.go:154
  - unable to get uncompressed layer sha256:1414cd8be9363ee31513d9f810a52399205fa281d2b3b059d21c287f08e292c3:
    github.com/aquasecurity/fanal/artifact/image.Artifact.inspectLayer
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220129174924-b9e05fcccc57/artifact/image/image.go:194
  - failed to get the layer (sha256:1414cd8be9363ee31513d9f810a52399205fa281d2b3b059d21c287f08e292c3):
    github.com/aquasecurity/fanal/artifact/image.Artifact.uncompressedLayer
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220129174924-b9e05fcccc57/artifact/image/image.go:250
  - unable to populate:
    github.com/aquasecurity/fanal/image/daemon.(*image).LayerByDiffID
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220129174924-b9e05fcccc57/image/daemon/image.go:125
  - unable to open:
    github.com/aquasecurity/fanal/image/daemon.(*image).populateImage
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220129174924-b9e05fcccc57/image/daemon/image.go:78
  - failed to copy the image:
    github.com/aquasecurity/fanal/image/daemon.imageOpener.func1
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220129174924-b9e05fcccc57/image/daemon/image.go:40
  - write /tmp/fanal-3323732142: no space left on device

**Comment by knqyf263** [comment]
Looks like your storage just doesn't have space left.
