### ISSUE TITLE
Consider different storage options

### ISSUE THREAD

**Issue by jbergstroem** [aquasecurity/trivy#18]
From bolt docs:
> Please note that Bolt obtains a file lock on the data file so multiple processes cannot open the same database at the same time. 

Lets say you have a CI which would do something like `docker run -v /tmp/cache:.cache/trivy mydockerimage trivy ..`. This would imply that two scans would try to access the same cachefile and likely bail. 

For this reason, exploring other storage options that would allow concurrent access could make sense. Perhaps another pattern would be copying the cache for each run and separate updates to the cache?

**Comment by knqyf263** [comment]
@jbergstroem Thank you for the feedback. I'm considering about using Redis. How do you think?

**Comment by jbergstroem** [comment]
> @jbergstroem Thank you for the feedback. I'm considering about using Redis. How do you think?

Had a think about it. I like the idea of a pluggable storage mechanism since storage at this point is a bit of a "flavor of the month" question. I would personally prefer something that speaks sql – but redis sounds perfectly fine as well – hence the pluggable idea.

**Comment by christian-weiss** [comment]
As long as you have no other backends. 
What about having one docker container being executed every hour to update a docker volume.
And then mount/bind that docker volume to all other docker trivy containers as read-only and with `--skip-update` - that way you do not have concurrent writes and fastest possible trivy scan results.

This works well, if all docker containers are executed on the same host.On a small farm it is maybe an option to have the "update container" to be executed / sticky on each "worker node". On a large farm this is maybe not an option.

**Comment by jbergstroem** [comment]
> As long as you have no other backends.
What about having one docker container being executed every hour to update a docker volume.
And then mount/bind that docker volume to all other docker trivy containers as read-only and with --skip-update - that way you do not have concurrent writes and fastest possible trivy scan results.

> This works well, if all docker containers are executed on the same host.On a small farm it is maybe an option to have the "update container" to be executed / sticky on each "worker node". On a large farm this is maybe not an option.

I'm doing something like this at the moment; daily databases and mounting them to the cache dir. The size of these dailies are pretty significant though. I feel a bit bad for potentially pushing them to docker hub but can do if there's an interest..

**Comment by knqyf263** [comment]
We have the Redis option now.
https://aquasecurity.github.io/trivy/v0.38/docs/vulnerability/examples/cache/#cache-backend
