### ISSUE TITLE
Trivy Misconfiguration - Custom policies support for Terraform

### ISSUE THREAD

**Issue by geowalrus4gh** [aquasecurity/trivy#1802]
Trivy misconfiguration document says as follows,

"Custom policies do not support Terraform at the moment"

Any plan to bring support for custom policies for terraform as well?

**Comment by owenrumney** [comment]
@geowalrus4gh  - we're addding support for custom rego policies to the Terraform scanning engine.

If you need a solution in the short term, Trivy supports tfsec custom check files https://aquasecurity.github.io/tfsec/v1.8.0/getting-started/configuration/custom-checks/

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/pull/2084 added this support. Please try v0.28.0 that will be released soon.

**Comment by geowalrus4gh** [comment]
> #2084 added this support. Please try v0.28.0 that will be released soon.

v0.28.0 document still stays "Custom policies do not support Terraform at the moment"

**Comment by knqyf263** [comment]
@liamg We support it, right? Can you update the doc here?
https://aquasecurity.github.io/trivy/v0.28.1/docs/misconfiguration/custom/

**Comment by liamg** [comment]
I already did it here :+1:  https://github.com/aquasecurity/trivy/pull/2267/files#diff-991154341385c5e7079c545f76e467b6739b278893a58d981b48b14082e47a26L34-L36

**Comment by knqyf263** [comment]
Nice!

@geowalrus4gh It is available from v0.28.0, but we forgot to update the doc. The doc will be also updated in v0.29.0.
