### ISSUE TITLE
Update to latest sprig version

### ISSUE THREAD

**Issue by kochn** [aquasecurity/trivy#1809]
Currently trivy seems to use an very old sprig version, so that many function like: Regex, mustToJson etc. are not supported. Would it be possible to update the version, so that it is possible to use the newest sprig fuction documented in: http://masterminds.github.io/sprig/

In the report documentation is a reference to sprig an many commands are currently not compatible with the latest trivy version: https://aquasecurity.github.io/trivy/v0.24.2/vulnerability/examples/report/

**Comment by knqyf263** [comment]
@DmitriyLewen Can you take it? We have to make sure our templates work with the latest sprig.

**Comment by DmitriyLewen** [comment]
Hello @kochn @knqyf263 
Okay! I will check and write late.
