### ISSUE TITLE
FATAL	error in image scan: failed to scan image: failed to analyze OS packages: exec: "rpm": executable file not found in $PATH

### ISSUE THREAD

**Issue by ANastasiosDF** [aquasecurity/trivy#181]
For every docker image, I am trying to run I receive 
2019-10-07T16:01:33.150+0100	FATAL	error in image scan: failed to scan image: failed to analyze OS packages: exec: "rpm": executable file not found in $PATH

**Output of run with `-debug`:**

```
	FATAL	error in image scan:
    github.com/aquasecurity/trivy/pkg.Run
        /root/project/pkg/run.go:164
  - failed to scan image:
    github.com/aquasecurity/trivy/pkg/scanner.ScanImage
        /root/project/pkg/scanner/scan.go:54
  - failed to analyze OS packages:
    github.com/aquasecurity/trivy/pkg/scanner/ospkg.Scan
        /root/project/pkg/scanner/ospkg/scan.go:52
  - exec: "rpm": executable file not found in $PATH
```

**Output of `trivy -v`:**

```
trivy version 0.1.6
```

**Comment by knqyf263** [comment]
@ANastasiosDF If you are using Debian/Ubuntu and scanning RHEL/CentOS, you have to install `rpm`.
https://github.com/aquasecurity/trivy#debianubuntu

**Comment by ANastasiosDF** [comment]
I am using a MAC

**Comment by knqyf263** [comment]
macOS needs rpm as well

**Comment by knqyf263** [comment]
If this problem occurs even after you install rpm on macOS, please reopen this PR.
