### ISSUE TITLE
Support SPDX in addition to CycloneDX

### ISSUE THREAD

**Issue by stevehipwell** [aquasecurity/trivy#1819]
I'd like to see Trivy support SPDX; both as a release artefact and as an output of the scan. As Trivy is built with GoReleaser the SPDX SBOM can be generated at build time ([docs](https://goreleaser.com/customization/sbom/)).

It would also be great if SPDX was included in the spec for #1164 as a lot of OSS projects already output SPDX SBOMs.

[SPDX](https://spdx.dev/) is the Linux Foundation OpenSSF SBOM solution and an ISO standard.

**Comment by knqyf263** [comment]
Sounds nice.

**Comment by stevehipwell** [comment]
It looks like this has been delivered in v0.28.0.
