### ISSUE TITLE
What makes detection “more accurate” from one distro to another?

### ISSUE THREAD

**Issue by JaneJeon** [aquasecurity/trivy#1821]
I’ve always been curious about this statement on the overview page:

> High Accuracy: Especially Alpine Linux and RHEL/CentOS

What does this mean? Why? What makes it more “accurate” than debian/other distros?

Sorry if this is a dumb question

**Comment by knqyf263** [comment]
As for Alpine, you can see this discussion. We correctly handle version comparison, rejected vulnerabilities, etc.
https://twitter.com/ariadneconill/status/1503505721157206017

Also, Trivy is certified by Red Hat.
https://www.redhat.com/ja/blog/introducing-red-hat-vulnerability-scanner-certification

**Comment by JaneJeon** [comment]
Ah, makes sense. Would be good if you documented it but if not, at least there’s this issue others can look up. Thanks!
