### ISSUE TITLE
Choice possibility directory for image download

### ISSUE THREAD

**Issue by JSGUYOT** [aquasecurity/trivy#1834]
Hello, 

Trivy use /tmp for download image before scan it.
But my /tmp is in small size, and i dont want increase /tmp (production server)

TRIVY_CACHE_DIR not seems work for that ...,, is just for DB data

Is it possible to add parameter for change image download directory and let user choice ?

Regards,

**Comment by knqyf263** [comment]
`--cache-dir` should work. @DmitriyLewen Could you help with it?

**Comment by DmitriyLewen** [comment]
Hello  @JSGUYOT 
Thanks for your interest in trivy!
Hello @knqyf263 
@JSGUYOT is right. Trivy only [uses temp dir](https://github.com/aquasecurity/fanal/blob/5862b1978a8cc0c3064489850826f32ca004712c/image/daemon/docker.go#L38-L41) to [copy image](https://github.com/aquasecurity/fanal/blob/5862b1978a8cc0c3064489850826f32ca004712c/image/daemon/image.go#L39-L41). 
@knqyf263  do you want to move the image upload directory to the caching directory?

**Comment by knqyf263** [comment]
The temp dir is removed after execution. @JSGUYOT Cannot you accept even one shot?

**Comment by JSGUYOT** [comment]
Hello, 

@knqyf263 
No, I can't ...
I use trivy for a big images (~ 3 / 4 Go) ==> I Know is too big, but are not my images :)
My /tmp FS is at 1Go, I can't increase /tmp FS because is production server define with special template 

Regards,

**Comment by knqyf263** [comment]
@JSGUYOT We're sorry for no updates. I think you can override the temp directory via `TMPDIR`.
