### ISSUE TITLE
Add OS dependencies license scans

### ISSUE THREAD

**Issue by VaismanLior** [aquasecurity/trivy#1835]
I would like to use trivy for getting the licenses of a project's dependencies.
This option will help the developer to avoid legal license problems in the development process.

The command can look something like`trivy fs --licenses /path/to/repo` or `trivy licenses /path/to/repo`.
 
It will be helpful to add this feature for Go libraries first and extend it to other programming languages later.

**Comment by knqyf263** [comment]
I thought we might want to enable it by default, but if we call GitHub API a lot to get licenses, it will slow down scanning and reach GitHub API rate limiting (we faced this issue many times). --licnese may be good as a first step.

**Comment by VaismanLior** [comment]
You are right, I thought about checking other options, like [go-licenses](https://github.com/google/go-licenses).
I am not sure how they do it yet

**Comment by VaismanLior** [comment]
After a bit of research, every solution available right now for license information requires the actual libraries and scans their LICENSE file to get this information.
A solution that will work without the actual libraries will require some kind of cache DB to prevent reaching the GitHub rate limit. Something similar to Aqua's vulnerability database(with an update algorithm etc.).
What do you think? @knqyf263

**Comment by knqyf263** [comment]
If I understand correctly, go modules will be stored in local cache like `$GOPATH/pkg/mod/github.com/stretchr/testify@v1.7.0/LICENSE `. In CI/CD, it is common that users run `go build` or `go test`, so we may be able to assume that go modules in local. But it may not exist if the scanning is dependent from other tests. In case we don't find `$GOPATH/pkg`, we can show a warning like `you must run `go mod download` before license scanning`.

**Comment by itaysk** [comment]
closing in favor of #2303
