### ISSUE TITLE
[Infra]: carve out better contributing guidelines

### ISSUE THREAD

**Issue by jamesgeorge007** [aquasecurity/trivy#184]
As of now, the `Readme` is messed up with plethora of information. Also, the repository lacks a `contributing.md` file which is something vital to have as per the [GitHub repo guidelines](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors#adding-a-contributing-file).

- [x] Isolate the `contributing` section into a dedicated `contributing.md` file.
- [x] Carve out a better strategy that would make it beginner-friendly rather than dumping all information in one place (`Readme`).

**Comment by jamesgeorge007** [comment]
I would be happy to submit a PR for this :+1:

**Comment by knqyf263** [comment]
@jamesgeorge007 Thank you for filing an issue. We are also working on CONTRIBUTING.md. You can check the above box.
https://github.com/aquasecurity/trivy/pull/185

**Comment by itaysk** [comment]
Thank you @jamesgeorge007 for taking the time to make this suggestion. Please review the newly added `contributing.md` and feel free to suggest any improvements
