### ISSUE TITLE
Trivy v0.24.3 (possibly previous as well) contains moderate vulnerability

### ISSUE THREAD

**Issue by isuftin** [aquasecurity/trivy#1843]
## Description

Trivy uses the Go containerd lib github.com/containerd/containerd @ version 1.5.9

This library contains a moderate vulnerablity: GHSA-crp2-qrr5-8pq7

https://github.com/containerd/containerd/security/advisories/GHSA-crp2-qrr5-8pq7

This is fixed in v1.5.10

This was found using Grype on a built Docker image

## What did you expect to happen?

No vulnerabilities to be found in offering

## What happened instead?

Vulnerability is found

**Comment by knqyf263** [comment]
It's related to CRI implementation. Trivy doesn't use that feature.
