### ISSUE TITLE
Consistency with integer vs. floating point numbers in numerical fields in output JSON

### ISSUE THREAD

**Issue by jasonumiker-plerion** [aquasecurity/trivy#1845]
I am trying to import Trivy results JSON into Elastic/OpenSearch and get errors like `mapper [Results.Vulnerabilities.CVSS.nvd.V2Score] cannot be changed from type [long] to [float]"` because that V2Score sometimes has a decimal in it and sometimes it doesn't.

I am looking at needing a pipeline to go through and find all the integers/longs and add the .0 to turn them into floats to resolve this - but it would be much easier if for each value in your JSON schema you were consistent on your treatment of these numbers.

**Comment by szisiu** [comment]
I am experiencing the same problem. Any plans on improving it in Trivy reports?
