### ISSUE TITLE
Pre-commit hook

### ISSUE THREAD

**Issue by tspearconquest** [aquasecurity/trivy#1858]
Hi, I want to contribute a pre-commit hook to run Trivy while doing git commit with pre-commit installed.

This issue is to track the effort in case anyone would like to collaborate.

I plan to start this hopefully within a couple of weeks. I'm currently pressed for some time to work on it, but I wanted to get the issue open in case anyone would like to discuss anything about it. :)

**Comment by tspearconquest** [comment]
Please remove stale label

**Comment by createchange** [comment]
Presently exploring creating a pre-commit toolchain for our developers. This would certainly be a welcome addition.

**Comment by mxab** [comment]
Hi,
I toyed arround with pre-commit a little bit. It has native support for creating hooks writen in go. It only requires the pre-commit-hook config in the repo.
Check the PR for more details

**Comment by aacecandev** [comment]
Is any work in progress on this issue?

**Comment by tspearconquest** [comment]
Yes. See https://github.com/aquasecurity/trivy/pull/2490. It's been submitted but not yet approved, as the Aqua Security team was busy during Kubecon.

**Comment by tspearconquest** [comment]
Trivy team has decided not to accept the PR and instead recommended for the author of the hook to host it in his own repo and they are listing it on the [ecosystem page](https://aquasecurity.github.io/trivy/latest/ecosystem/ide/) -- however it will not be visible until the next release of Trivy.

Because of the team not accepting the PR, I am closing out this issue.
