### ISSUE TITLE
trivy client --clear-cache not working

### ISSUE THREAD

**Issue by rohan-kumar-nutanix** [aquasecurity/trivy#1860]
## What did you expect to happen?
Remove artifact cache

## What happened instead?
Issued a warning and did not remove artifact cache

## Output of run with `-debug`:

```
2022-03-21T17:44:15.312+0530	DEBUG	cache dir:  /Users/abc/Library/Caches/trivy
2022-03-21T17:44:15.312+0530	WARN	A client doesn't have image cache
```

## Output of `trivy -v`:

```
Version: 0.24.4
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-03-21 06:06:31.075366441 +0000 UTC
  NextUpdate: 2022-03-21 12:06:31.075366041 +0000 UTC
  DownloadedAt: 2022-03-21 10:56:53.295914 +0000 UTC
```

## Additional details (base image name, container registry info...):
Trivy server works fine

**Comment by knqyf263** [comment]
As the log message says, a client doesn't have any cache.

**Comment by rohan-kumar-nutanix** [comment]
trivy client --help shows an option to clear cache by using the flag --clear-cache. If this does not work, how am I supposed to clear the server cache in a client-server configuration.

Thanks

**Comment by knqyf263** [comment]
>trivy client --help shows an option to clear cache by using the flag --clear-cache.
Oh, you're right. We should remove it.

>If this does not work, how am I supposed to clear the server cache in a client-server configuration.
A client cannot trigger the cache clear as of today. You need to stop a server and clear the cache. If you use Redis as the cache backend, you can log in to the Redis server and remove it.
https://aquasecurity.github.io/trivy/v0.24.4/vulnerability/examples/cache/#cache-backend
