### ISSUE TITLE
Trivy scan vulnerabilities in the application dependencies

### ISSUE THREAD

**Issue by neongreenplants** [aquasecurity/trivy#1867]
Hi, Is it possible to use `Trivy fs`  with custom rego policy (for example I want to find specific packages by name) for scans vulnerabilities in application dependencies?

**Comment by AndreyLevchenko** [comment]
Hi Sergey
you can use `--list-all-package` and `--format json` and then process output with `opa` tool

Regards 
Andrey

**Comment by neongreenplants** [comment]
Hi Andrey,
Thanks for response. Yeap `--list-all-pkgs` gives me info about dependencies, this is a half of task). Can you please give advanced information about  _process output with `opa` tool_ . Does it mean i need 2 use open policy agent on k8s cluster?

**Comment by AndreyLevchenko** [comment]
Hi Sergey
I meant small CLI tool 
https://www.openpolicyagent.org/docs/latest/cli/#opa-eval
