### ISSUE TITLE
Error while scanning an image

### ISSUE THREAD

**Issue by gopurx** [aquasecurity/trivy#187]
trivy scanning results in an error while scanning a specific image. This is happening only with this specific image "centos_shoppingcart:latest".

**What did you expect to happen?**
Expected to scan the image and produce vulnerabilities report

**What happened instead?**
Instead process fails abruptly

**Output of run with `-debug`:**

```
trivy --auto-refresh --debug --format json -o scan.json  --cache-dir /mntshare/trivy myregistry.azurecr.io/centos_shoppingcart:latest
2019-10-11T10:50:19.176-0500	DEBUG	cache dir:  /mntshare/trivy
2019-10-11T10:50:19.176-0500	DEBUG	db path: /mntshare/trivy/db/trivy.db
2019-10-11T10:50:19.180-0500	INFO	Updating vulnerability database...
2019-10-11T10:50:19.180-0500	DEBUG	git pull
2019-10-11T10:50:20.049-0500	DEBUG	total updated files: 1
2019-10-11T10:50:20.051-0500	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2019-10-11T10:50:20.051-0500	DEBUG	Vulnerability type:  [os library]
2019-10-11T10:50:25.632-0500	FATAL	error in image scan:
    github.com/aquasecurity/trivy/pkg.Run
        /root/project/pkg/run.go:164
  - failed to analyze image:
    github.com/aquasecurity/trivy/pkg/scanner.ScanImage
        /root/project/pkg/scanner/scan.go:34
  - failed to extract files:
    github.com/aquasecurity/fanal/analyzer.Analyze
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20190819081512-f04452b627c6/analyzer/analyzer.go:127
  - Could not extract the archive
    github.com/aquasecurity/fanal/extractor.init.ializers
    	/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20190819081512-f04452b627c6/extractor/extractor.go:12
    runtime.main
    	/usr/local/go/src/runtime/proc.go:188
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1337
```

**Output of `trivy -v`:**

```
trivy version 0.1.6
```

**Additional details (base image name, container registry info...):**
base image: centos:centos7.6.1810

**Comment by knqyf263** [comment]
@gopurx Would you try --clear-cache option?

**Comment by knqyf263** [comment]
@gopurx  How large is your image?

**Comment by gopurx** [comment]
@knqyf263 - it is 1.37G

**Comment by knqyf263** [comment]
@gopurx Hmm.. the image size may cause. Would you pull the image before scanning? Then, try scanning with --clear-cache option. Or, you may have to specify `TRIVY_TIMEOUT_SEC` like this.

```
export TRIVY_TIMEOUT_SEC=600s
```

**Comment by gopurx** [comment]
@knqyf263, this worked. As you suspected looks like size of image and number of vulnerabilities with in the image is causing the timeout. What is the default timeout if it is not defined?

**Comment by knqyf263** [comment]
@gopurx 60s. In the next version, you can specify a timeout via the CLI option.
https://github.com/aquasecurity/trivy/pull/143

**Comment by knqyf263** [comment]
v0.1.7 has released. You can specify `--timeout` option.
