### ISSUE TITLE
Trivy returns invalid JSON

### ISSUE THREAD

**Issue by AXDOOMER** [aquasecurity/trivy#1874]
When running Trivy on some projects, the description may contain special characters such as `\n` and `\"`. This prevents parsing the result with Javascript as the JSON.parse() function will complain about a bad control character. To be valid JSON, `\n`should be correctly escaped as `\\n` and `\"` as `\\"`. 

This Javascript function behaves correctly as there shouldn't be such control sequences in JSON strings according to the specification. 
Related: https://stackoverflow.com/questions/42068/how-do-i-handle-newlines-in-json#comment23184783_42073

These problematic characters are found in the "Description" field. Some examples of invalid JSON outputs given by Trivy:

For `golang.org/x/text`, version `0.3.3`, issue due to `\n`:

```
"Description": "Due to improper index calculation, an incorrectly formatted language tag can cause Parse\nto panic via an out of bounds read. If Parse is used to process untrusted user inputs,\nthis may be used as a vector for a denial of service attack.\n",
```
In my opinion, newlines should never be present as it is the responsibility of the parsing application to handle how the string will be presented to the user. 

For `github.com/dgrijalva/jwt-go`, version `3.2.0+incompatible`, issue due to `\"`:

```
"Description": "jwt-go before 4.0.0-preview1 allows attackers to bypass intended access restrictions in situations with []string{} for m[\"aud\"] (which is allowed by the specification). Because the type assertion fails, \"\" is the value of aud. This is a security problem if the JWT token is presented to a service that lacks its own audience check.",
```

How Trivy was run: `../../trivy/trivy fs -f json -o results.json  .`

**Comment by knqyf263** [comment]
@afdesk Could you look into it? We use a standard JSON library provided by Go.

**Comment by afdesk** [comment]
@AXDOOMER thanks for your report!

@knqyf263 I'll try to investigate it.

**Comment by afdesk** [comment]
@AXDOOMER thanks! it seems i understood this problem. will fix

**Comment by afdesk** [comment]
@AXDOOMER 
this issue comes from the data source about vulnerability:
https://storage.googleapis.com/go-vulndb/golang.org/x/text.json
https://storage.googleapis.com/go-vulndb/github.com/dgrijalva/jwt-go.json

now we don't know a good way how to fix it.

as workaround, you can use `sed` for it. something like it:
```sh
sed -E 's/"/\\&/4g; s/\\"(,)?$/"\1/' result.json
```
i hope it will help you.
