### ISSUE TITLE
Rego policy 

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#1876]
Hi

I have a question regarding the rego policy. I would like to suppress a vulnerability in a given package using the CVE identifier. I have not been able to find out what is the name of the field that contains the CVE. 

Is there any document where the fields in the policy is described? I have seen for example input.Severity, input.PkgName etc... but cant find the name for the cve identifier

Also, the link in https://aquasecurity.github.io/trivy/v0.24.4/vulnerability/examples/filter is broken

Thanks

**Comment by DmitriyLewen** [comment]
Hello @javixeneize 
Thank you for your interest to Trivy!

The structure of each vulnerability input is the same as for the Trivy JSON output. To ignore packages by CVE ID use: `input.VulnerabilityID`.

Also you can use [.trivyignore](https://aquasecurity.github.io/trivy/v0.24.4/vulnerability/examples/filter#by-vulnerability-ids) file to skip packages by CVE. 

Thanks for information about broken link in the docs. We will fix it soon.
[This is link from the docs](https://github.com/aquasecurity/trivy/blob/main/pkg/result/module.go), if you still need it.

Regards, Dmitriy

**Comment by javixeneize** [comment]
Thanks! So, the name of the fields match with the ones in the json output, correct? This applies to other fields like lobrary version for example

**Comment by DmitriyLewen** [comment]
Yes! You are right. You can filter by library version by using `input.InstalledVersion`.
