### ISSUE TITLE
Issues with importing the ASFF generated by `asff.tpl`

### ISSUE THREAD

**Issue by ben-harvey** [aquasecurity/trivy#1896]
I'm using `asff.tpl` and running into some issues with importing the resulting ASFF that have led me to use a modified version the template.  However, it would be great to use the provided template directly, since updates to Trivy can introduce changes that break older versions of the template.  
1. The `description` is escaped after truncating.  Since escaping adds characters, this can lead to a description longer than the allowed maximum of [1024 characters](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-required-attributes.html#:~:text=Maximum%20length%3A%201%2C024)
https://github.com/aquasecurity/trivy/blob/36e24b185831a26ec87ec11ea33f5c1c221ff788/contrib/asff.tpl#L33
I see that this has already been noted [here](https://github.com/aquasecurity/trivy/issues/815#issuecomment-1076340113) but wanted to flesh it out.
2. I have run into cases where the `Details.Container.ImageName` is longer than the allowed [128 characters](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-resourcedetails-container.html#:~:text=Type%3A%20String-,Maximum%20length%3A%20128,-LaunchedAt)
3.  Not an import issue, but some security format conversion tools (e.g. [SAF](https://saf-cli.mitre.org/)) group Trivy findings incorrectly because they all share the same static `GeneratorId` field.
https://github.com/aquasecurity/trivy/blob/36e24b185831a26ec87ec11ea33f5c1c221ff788/contrib/asff.tpl#L24
Most other security scan tools, including [kube-bench](https://github.com/aquasecurity/kube-bench/blob/be157a8a5ad9f931a107ab39db2ab30b7f4cbd00/check/controls.go#L251), append a control/vulnerability ID to the `GeneratorId` field so that like findings can be grouped together. (FWIW, AWS specs are a bit unclear about this field, calling it "[a rule, a check, a detector, a plugin, and so on](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-required-attributes.html#:~:text=contain%20a%20vulnerability.%22-,GeneratorId,-Required)")

**Comment by afdesk** [comment]
@ben-harvey thanks for your suggestions.

at first glance it looks really reasonable.

Is it possible to create a PR with your a modified version the template?

**Comment by ben-harvey** [comment]
Sure, @afdesk, I created https://github.com/aquasecurity/trivy/pull/1914

**Comment by afdesk** [comment]
it seems the issue was fixed, isn't it?
@ben-harvey please, feel free to reopen the ticket if you still have this problem. thanks
