### ISSUE TITLE
ASFF Template need a different format depending on the context

### ISSUE THREAD

**Issue by oliviergaumond** [aquasecurity/trivy#1898]
## Description
A recent PR (#1685) modified the format of `contrib/asff.tpl` to include a wrapping structure. As reported in issue #1684 

However, depending on how the report is sent to Security Hub it may or may not need the wrapping structure.
- If using the AWS API or an SDK, the wrapping structure is needed
- If using the AWS CLI the wrapping structure should not be used

## What happened?
With the latest change to the template the sample here no longer works: https://github.com/aquasecurity/trivy/blob/main/docs/advanced/integrations/aws-security-hub.md

## What did you expect to happen?
The documentation probably needs to be updated to reflect the different usage. Maybe we need two versions of the template?

**Comment by oliviergaumond** [comment]
@afdesk I can submit a PR for this if you want. Just want some guidance on how to address.

What I think:
- Create two versions of the template: asff-api.tpl ans asff-cli.tpl
- Update the documentation to provide usage using the CLI and the API with the respective template

Any other suggestions?

**Comment by afdesk** [comment]
@oliviergaumond thanks for your interest!
if you can create a PR, it'll be really useful. 
we welcome contributors!

I'm wondering about 2 templates, is it really need?

in any case, It would be cool to use something like nested templates. but I have no idea right now...

**Comment by afdesk** [comment]
@oliviergaumond could you explain me a moment about AWS CLI?
can we use next command?
```sh
$ aws securityhub batch-import-findings --cli-input-json file://report.asff
```
instead of 
```sh
$ aws securityhub batch-import-findings --findings file://report.asff
```
or i miss something...

thanks

**Comment by oliviergaumond** [comment]
No, the --cli-input-json is to provide the parameters for the actual command in json instead of directly on the command line.

In the end I am thinking maybe we should revert the asff.tpl to the version which doesn't generate the wrapping Findings object. Thus the already documented exemple to upload with the CLI will work.

Then we can add documentation that if someone want's to upload the findings through the API or an SDK they should add the wrapping object with jq or other means.
```
cat report.asff | jq '{"Findings": .}'
```

**Comment by afdesk** [comment]
@oliviergaumond oh sure, you're right. my mistake.

**Comment by afdesk** [comment]
@oliviergaumond  saw your issue on AWS CLI: https://github.com/aws/aws-cli/issues/6804
it's a bit unusual situation, but you're right!

I'd prefer to use the current template with `jq`:
```sh
$ cat a.asff | jq '.Findings'
```

what do you think about this way? thanks for your help and sorry for waiting!

**Comment by afdesk** [comment]
I think so because the documentation about [ASFF syntax](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format-syntax.html) contains only one format with `Findings`.

**Comment by AndrewCharlesHay** [comment]
@afdesk I am getting an ```Job's log exceeded limit of 4194304 bytes.``` error. How do I suppress the output so it doesn't print to the console?

**Comment by afdesk** [comment]
@AndrewCharlesHay you're using GitLab, right?
I'd try to increase `output_limit`: [read more](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section)
