### ISSUE TITLE
Make built-in policies downloadable only

### ISSUE THREAD

**Issue by tiboun** [aquasecurity/trivy#1900]
It would be great to have another option such as --download-db-only for built-in policies. For instance, having a --download-policies-only.

This would make https://github.com/sighupio/trivy-offline/blob/master/Dockerfile covering more offline scan.
What do you think about providing an offline version of your image as well, then it will allow to have an official one ?

Best regards

**Comment by knqyf263** [comment]
We embed built-in policies into Trivy binary. Downloading policies is no longer needed.
