### ISSUE TITLE
Docs - Multi-stage build snippet fails DS018

### ISSUE THREAD

**Issue by baldwicc** [aquasecurity/trivy#1902]
The following snippet in the docs triggers [DS018](https://avd.aquasec.com/misconfig/dockerfile/ds018/):

https://github.com/aquasecurity/trivy/blob/4470a181e2daf993d2e0402d8f29f6c0a6c5c2e9/docs/advanced/container/embed-in-dockerfile.md?plain=1#L20-L25

Would this do the trick instead?

````
# Run vulnerability scan on build image
FROM aquasec/trivy:latest AS trivy
FROM build AS vulnscan
COPY --from=trivy /usr/local/bin/trivy /usr/local/bin/trivy
RUN trivy filesystem --exit-code 1 --no-progress /
````

#### Related
- https://github.com/aquasecurity/trivy/issues/1621
- https://github.com/aquasecurity/appshield/issues/146

**Comment by trevor-vaughan** [comment]
I'm seeing this as well with all multi-stage builds such as:

```dockerfile
FROM foo:1.2.3 as Base
<do stuff>
FROM Base as User
COPY --from=Base /home /home
```
