### ISSUE TITLE
Update Trivy Helm version

### ISSUE THREAD

**Issue by dirsigler** [aquasecurity/trivy#1928]
Trivy was now released with version [0.25.0](https://github.com/aquasecurity/trivy/releases/tag/v0.25.0) but the Helm Chart does still install version [0.24.0](https://github.com/aquasecurity/trivy/blob/main/helm/trivy/Chart.yaml#L4).

Are there any objections to bump the version there, too ?

**Comment by knqyf263** [comment]
Yes, we should update it as well. We just need contribution 😄
