### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by PenelopeFudd** [aquasecurity/trivy#1930]
## Description

`/usr/local/bin/trivy rootfs  /` -- command dies with SIGSEGV.

## What did you expect to happen?
It should "just work".

## What happened instead?
It "just bombed", after 3.5 minutes.

## Output of run with `-debug`:

```
...
2022-04-03T18:01:19.863-0700	DEBUG	No such POM in the central repositories	{"file": "url-test.jar"}
2022-04-03T18:01:19.892-0700	DEBUG	Parsing Java artifacts...	{"file": "home/user/gradle/wrapper/gradle-wrapper.jar"}
2022-04-03T18:01:19.928-0700	DEBUG	No such POM in the central repositories	{"file": "lf.jar"}
2022-04-03T18:01:20.404-0700	DEBUG	No such POM in the central repositories	{"file": "gradle-wrapper.jar"}
2022-04-03T18:01:20.936-0700	DEBUG	Analysis error: unable to decode JSON (home/user/catapult/telemetry/telemetry/internal/backends/chrome/chromeos_login_ext/manifest.json): invalid character '/' looking for beginning of object key string
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15cba0a]

goroutine 60930 [running]:
github.com/aquasecurity/fanal/analyzer/language/python/packaging.packagingAnalyzer.Analyze({}, {0x1c8be20?, 0x7020636f44534a00?}, {{0x7ffcad3c34f5, 0x1}, {0xc015b53d41, 0x83}, {0x2192590, 0xc015b51930}, {0x218c580, ...}, ...})
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/analyzer/language/python/packaging/packaging.go:53 +0x18a
github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile.func1({0x218dad0, 0x3102790}, {0x218f2e0?, 0xc000b7d4b8})
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/analyzer/analyzer.go:253 +0x253
created by github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/analyzer/analyzer.go:248 +0x3d8

```

## Output of `trivy -v`:

```
Version: 0.25.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-04-04 00:09:56.817083217 +0000 UTC
  NextUpdate: 2022-04-04 06:09:56.817082817 +0000 UTC
  DownloadedAt: 2022-04-04 00:56:46.423024596 +0000 UTC

```

## Additional details (base image name, container registry info...):
Ubuntu 18.04.6 LTS

**Comment by DmitriyLewen** [comment]
Hello @PenelopeFudd 
Thanks for your report!

I checked `home/user/catapult/telemetry/telemetry/internal/backends/chrome/chromeos_login_ext/manifest.json` file. If I understand correctly this is `Google Chrome Extensions` manifest.
[I found](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json), that this file may contain comments:
> It is a [JSON](https://developer.mozilla.org/en-US/docs/Glossary/JSON)-formatted file, with one exception: it is allowed to contain "//"-style comments.

Trivy only parses [JSON](https://www.json.org/json-en.html) format.

Could you check this file, please.

Regards, Dmitriy

**Comment by knqyf263** [comment]
@DmitriyLewen Can we skip invalid JSON? The panic is problematic.

**Comment by DmitriyLewen** [comment]
I have mistake.
Invalid JSON does not call a panic.
There was a problem parsing the `*.egg` file.
I will check it more further and write result.

**Comment by PenelopeFudd** [comment]
The file that triggers the problem may not show up in the debug output.
I reported a previous bug where that was the case; strace was necessary to figure it out.
