### ISSUE TITLE
Manage credentials for multiple registries

### ISSUE THREAD

**Issue by tisc0** [aquasecurity/trivy#194]
Hi guyz, and thanks for your neat project !

Everything is in the topic : is it possible for trivy to source some [json] file which would provide multiple credentials for multiple registries ?
$GOOGLE_APPLICATION_CREDENTIALS is the idea but is dedicated to one gcr registry.

Thanks to tell me if it exists already, or if this issue should be re-routed in featureRequest

**Comment by knqyf263** [comment]
@tisc0 Not yet. Would you re-label feature-request?

**Comment by tisc0** [comment]
@knqyf263 Couldn't re-label, just re-posted instead : #200
