### ISSUE TITLE
Rule DS017 has a false positive

### ISSUE THREAD

**Issue by trevor-vaughan** [aquasecurity/trivy#1946]
## Description

DS017 - `'RUN <package-manager> update' instruction alone` does not account for the following:

```dockerfile
RUN apt-get update && apt upgrade --yes
```

## What did you expect to happen?

There should be no finding

## What happened instead?

There was a finding

## Output of `trivy -v`:

```
Version: 0.21.2
Vulnerability DB:
  Type: Full
  Version: 1
  UpdatedAt: 2022-04-05 12:47:55.24793021 +0000 UTC
  NextUpdate: 2022-04-05 18:47:55.24792981 +0000 UTC
  DownloadedAt: 2022-04-05 13:52:56.280274691 +0000 UTC
```

**Comment by knqyf263** [comment]
Thanks for the report, but please raise an issue in [DefSec](https://github.com/aquasecurity/defsec).
