### ISSUE TITLE
Add Go license detection

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#1949]
## Description
Detect licenses of go modules.

1. Assume `go mod download`
2. Looks for license files in $GOPATH/pkg/mod
    - e.g. $GOPATH/pkg/mod/github.com/stretchr/testify@v1.7.0/LICENSE 
3. Classify the license type

## Related
https://github.com/aquasecurity/trivy/issues/1835

**Comment by anthonytwh** [comment]
Is there a target version when GO license detection will be supported?

**Comment by knqyf263** [comment]
>Is there a target version when GO license detection will be supported?

We don't have ETA at the moment
