### ISSUE TITLE
Support CycloneDX as input

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#1952]
## Description
Trivy can generate CycloneDX output, but it can't take CycloneDX as input. It would be great if Trivy supports CycloneDX as input and scans dependencies.

## Related issues
- https://github.com/aquasecurity/trivy/issues/1164

## Example

```
$ trivy sbom --type cyclonedx /path/to/report.cdx
```

## Implementation (Draft)
1. Define sbom.Artifact
    - https://github.com/aquasecurity/fanal/tree/b7afb9b29421d18bb508a50c335a2727c799a1e4/artifact
    - The implementation would be similar to fs.Artifact.
2. Parse SBOM inside `Inspect()`
    - https://github.com/aquasecurity/fanal/blob/b7afb9b29421d18bb508a50c335a2727c799a1e4/artifact/local/fs.go#L78
3. Create `BlobInfo`
    - https://github.com/aquasecurity/fanal/blob/b7afb9b29421d18bb508a50c335a2727c799a1e4/artifact/local/fs.go#L120-L127
4. Put the blob with a pseudo cache key in cache
    - Same as fs.Artifact
    - https://github.com/aquasecurity/fanal/blob/b7afb9b29421d18bb508a50c335a2727c799a1e4/artifact/local/fs.go#L148
6. Return ArtifactReference
    - https://github.com/aquasecurity/fanal/blob/b7afb9b29421d18bb508a50c335a2727c799a1e4/artifact/local/fs.go#L161-L167

**Comment by stevehipwell** [comment]
Should this be more generic for SBOMs as Trivy now supports SPDX?

**Comment by knqyf263** [comment]
Yes, but we will start with CycloneDX. I want to see if people need SPDX input.

**Comment by stevehipwell** [comment]
I need SPDX input, it is the OSSF SBOM format.

**Comment by knqyf263** [comment]
Thanks for letting us know. Could you open an issue? We'll add it to our backlog.

**Comment by knqyf263** [comment]
Closed by https://github.com/aquasecurity/trivy/pull/2203
