### ISSUE TITLE
rate limit when downloading database?

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#1979]
Hi

Does the database update consume any github rate limit? I was under the impression that it was, but i have ran a curl (curl -I https://api.github.com/users/octocat) to check my rate limit, then, i ran the trivy db update, and again, the same curl, and the rate limit was not decreased.

Can you confirm if updating trivy database uses your github rate limit?

Thanks

**Comment by knqyf263** [comment]
Trivy DB is now hosted on [GHCR](https://github.com/aquasecurity/trivy-db/pkgs/container/trivy-db), so it should not consume the rate limit.

**Comment by javixeneize** [comment]
love it! thanks
