### ISSUE TITLE
Support 'Containerfile' as config filename

### ISSUE THREAD

**Issue by gdemoya** [aquasecurity/trivy#1980]
## Description

Podman uses Dockerfile as well as Containerfile as filenames for the container build ([ref](https://docs.podman.io/en/latest/markdown/podman-build.1.html)), but at the moment, trivy does not detect `Containerfile` as a valid config file to be analyzed.

Since the same syntax is used for the image building, it would be interesting to add `Containerfile` as a "synonym" of `Dockerfile`.

## What did you expect to happen?

Detect `Containerfile` as a configuration file.

## What happened instead?

`Containerfile` is not detected.

## Output of run with `-debug`:

```
user:/app/build# ls
Containerfile  bin
user::/app/build# trivy -debug config .
2022-04-12T11:14:40.995Z	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-04-12T11:14:40.996Z	DEBUG	cache dir:  /root/.cache/trivy
2022-04-12T11:14:40.996Z	DEBUG	Vulnerability type:  []
2022-04-12T11:14:41.093Z	DEBUG	OS is not detected and vulnerabilities in OS packages are not detected.
2022-04-12T11:14:41.093Z	INFO	Detected config files: 0
```

## Output of `trivy -v`:

```
user:/app/build# trivy -v
Version: 0.25.4
```

## Additional details (base image name, container registry info...):

N/A

**Comment by knqyf263** [comment]
Thanks for filing an issue. It is interesting. Trivy doesn't support Containerfile for now, so it is the intended behavior. It is kind of like a feature request. I guess it is easy to support Containerfile if it is the same syntax as Dockerfile.

Trivy looks for `Dockerfile` here.
https://github.com/aquasecurity/fanal/blob/e51d560d5bad1aa2d079fa7181b3e1abdb7cab3a/analyzer/config/docker/docker.go#L19
https://github.com/aquasecurity/fanal/blob/e51d560d5bad1aa2d079fa7181b3e1abdb7cab3a/analyzer/config/docker/docker.go#L50-L67

I want to leave the task for someone who is interested in contributing.

**Comment by nishipy** [comment]
Hi, can I work on this issue? Thanks.
