### ISSUE TITLE
`asff.tpl`: empty `.PrimaryURL` breaks import to Security Hub

### ISSUE THREAD

**Issue by ben-harvey** [aquasecurity/trivy#1999]
The ASFF spec states that the `Remediation` field [is optional](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-top-level-attributes.html#:~:text=AcmeNerfHerder%2D111111111111%2Dx189dx7824%22%20%7D%0A%5D-,Remediation,-Optional).  However if the field is included, even though `Remediation.Recommendation`, `Remediation.Recommendation.Text`, and `Remediation.Recommendation.Url` are [all optional](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-remediation.html#asff-remediation-recommendation), the API will fail to validate a case where `Remediation.Recommendation.Url` is included, but empty, as in: 
```json
    "Remediation": {
      "Recommendation": {
        "Text": "More information on this vulnerability is provided in the hyperlink",
        "Url": ""
      }
    },
```
with the error
```
{
    "Id": "{id}",
    "ErrorCode": "InvalidInput",
    "ErrorMessage": "Finding does not adhere to Amazon Finding Format. data.Remediation.Recommendation.Url should NOT be shorter than 1 characters, data.Remediation.Recommendation.Url should match format \"uri\"."
},
```
This invalid ASFF will be generated by `asff.tpl` when the `.PrimaryURL` is empty. 
https://github.com/aquasecurity/trivy/blob/d786655a18a591bd254c2d11d10ec692943c6a78/contrib/asff.tpl#L38-L43
It makes sense to me to omit the entire `Remediation` field (since it's optional) if there's an empty `.PrimaryURL`, as in:
```tpl
        {{ if not (empty .PrimaryURL) -}}
            "Remediation": {
                "Recommendation": {
                    "Text": "More information on this vulnerability is provided in the hyperlink",
                    "Url": "{{ .PrimaryURL }}"
                }
            },
        {{ end -}}
```
If you agree, I'd be happy to open a PR for the change.

**Comment by afdesk** [comment]
@ben-harvey sure, we agree.  we welcome contributors.

**Comment by afdesk** [comment]
@ben-harvey Could you confirm that this issue is fixed via your PR?
thanks a lot!

**Comment by ben-harvey** [comment]
> fix: Omit Remediation if PrimaryURL is empty #2006

@afdesk Yes, I can confirm that we haven't seen this issue in production since the PR was merged.

**Comment by afdesk** [comment]
@ben-harvey thanks! then I closed it
