### ISSUE TITLE
Manage credentials for multiple registries

### ISSUE THREAD

**Issue by tisc0** [aquasecurity/trivy#200]
Hi guyz, and thanks for your neat project !

Everything is in the topic : is it possible for trivy to source some [json] file which would provide multiple credentials for multiple registries ?
$GOOGLE_APPLICATION_CREDENTIALS is the idea but is dedicated to one gcr registry.

Thanks !

**Comment by knqyf263** [comment]
Added in https://github.com/aquasecurity/trivy/pull/3631
