### ISSUE TITLE
No output when using --template "@contrib/html.tpl" with docker image

### ISSUE THREAD

**Issue by arix-dev** [aquasecurity/trivy#2011]
Hi I'm using the following command but I'm not getting output
docker run --rm aquasec/trivy:latest i --format template --template "@contrib/html.tpl" --output trivy_high.html openjdk:8-jdk-alpine

**Comment by DmitriyLewen** [comment]
Hello @arix-dev 
Thanks for your interest to Trivy!

`trivy_high.html` created incide docker container.

You need to get result file to your local machine.

You can create directory and use it as docker volume.
For example:
```
docker run -it -v /your/local/path/result:/result --rm  aquasec/trivy:latest i --format template --template "@contrib/html.tpl" --output /result/trivy_high.html openjdk:8-jdk-alpine
```

Best Regards, Dmitriy

**Comment by arix-dev** [comment]
Thanks @DmitriyLewen, I'll give it a try but it makes sense. Just hope Azure Devops pipeline co-operates now.
