### ISSUE TITLE
SPDX SBOM generation

### ISSUE THREAD

**Issue by ThiefaineM** [aquasecurity/trivy#2015]
Hello,
Since Trivy can generate SBOM, it could be nice to be able to generate it in SPDX format.
It "recently" got the ISO seal, so it might be interesting.

**Comment by thepwagner** [comment]
Duplicate of https://github.com/aquasecurity/trivy/issues/1819 ?

**Comment by ThiefaineM** [comment]
Definitely, sorry for that
