### ISSUE TITLE
Mariner 2.0 OVAL file renamed

### ISSUE THREAD

**Issue by eric-desrochers** [aquasecurity/trivy#2016]
Mariner recently renamed its OVAL file from 'cbl-mariner-2.0-preview-oval.xml' to 'cbl-mariner-2.0-oval.xml'
I wanted to bring this up quickly to prevent any potential disruption in Trivy on Mariner 2.0

**Comment by DmitriyLewen** [comment]
Hello @eric-desrochers 
Thanks a lot for your help.

We [remove](https://github.com/aquasecurity/vuln-list-update/blob/bc6508033e204b7e5da58313f924ebab8dfcd51b/mariner/mariner.go#L107) `preview` substring when working with `cbl-mariner*.xml` file.
Trivy will work as before. 

Best Regards, Dmitriy

**Comment by knqyf263** [comment]
Hi @eric-desrochers, thanks for letting us know! Our script is working even after renaming. Please let me close as we don't need any updates.
https://github.com/aquasecurity/vuln-list/tree/main/mariner/2.0
