### ISSUE TITLE
Ubuntu 22.04 LTS support

### ISSUE THREAD

**Issue by gnadaban** [aquasecurity/trivy#2043]
Hi, when will Ubuntu 22.04 be supported for APT?

Attempting to install on Jammy using APT shows an error:

```
E: The repository 'https://aquasecurity.github.io/trivy-repo/deb jammy Release' does not have a Release file.
```

**Comment by jeffalder** [comment]
https://github.com/aquasecurity/trivy/pull/2044

I'm a new contributor and added the EOL support here. Lemme look at the repo and see if I can figure it out.

**Comment by knqyf263** [comment]
There are two types of "Ubuntu 22.04 support".

1. Install Trivy on Ubuntu 22.04
2. Scan Ubuntu 22.04 images

I think @gnadaban is talking about #1, while @jeffalder is referring to #2.

#1 is done. https://github.com/aquasecurity/trivy-repo/pull/10
#2 requires contribution.
https://github.com/aquasecurity/trivy-db/blob/df65ebde46f4ab443fb6f4702b05b8fe6332c356/pkg/vulnsrc/ubuntu/ubuntu.go#L27-L48
