### ISSUE TITLE
Installation issue with deb package Ubuntu 20.04

### ISSUE THREAD

**Issue by PatrykKlimowicz** [aquasecurity/trivy#2047]
## Description

Installation with .deb package is broken

## What did you expect to happen?

trivy will be installed in correct version

## What happened instead?

trivy is installed in older version

## Steps to reproduce

```
wget https://github.com/aquasecurity/trivy/releases/download/v0.27.0/trivy_0.27.0_Linux-64bit.deb
sudo apt install ./trivy_0.27.0_Linux-64bit.deb
```

results:
```
trivy -v  
Version: 0.22.0
Vulnerability DB:
  Type: 
  Version: 2
  UpdatedAt: 2022-04-26 06:06:39.247959855 +0000 UTC
  NextUpdate: 2022-04-26 12:06:39.247959555 +0000 UTC
  DownloadedAt: 2022-04-26 07:39:57.8571255 +0000 UTC
```

**Comment by knqyf263** [comment]
We need the error message, but did you try removing the existing package like `apt remove --purge trivy`?

**Comment by PatrykKlimowicz** [comment]
> We need the error message, but did you try removing the existing package like `apt remove --purge trivy`?

During the installation there is no error message. Yes, I tried `apt remove --purge trivy`, also the installation with `dpkg` command gives the same result in version mismatch. 

```
# installed version 0.27 from deb package
➜  trivy -v
Version: 0.22.0
Vulnerability DB:
  Type: 
  Version: 2
  UpdatedAt: 2022-04-26 06:06:39.247959855 +0000 UTC
  NextUpdate: 2022-04-26 12:06:39.247959555 +0000 UTC
  DownloadedAt: 2022-04-26 07:39:57.8571255 +0000 UTC
➜  trivy image <my_image>
2022-04-26T10:23:18.841+0200    ERROR   Trivy version (0.22.0) is old. Update to the latest version.
2022-04-26T10:23:18.841+0200    FATAL   DB error: database error: the version of DB schema doesn't match. Local DB: 2, Expected: 1
```

**Comment by knqyf263** [comment]
It is weird. What if you remove the old binary manually?

**Comment by PatrykKlimowicz** [comment]
I managed to resolve. Sorry for inconvenience. The issue was in WSL2 config - for some reason binary file was mounted to windows path which force the version...? I'm confused, but after removing that link the version updated itself to 0.27 automatically. Thx for such quick response! Love the project!

**Comment by knqyf263** [comment]
Thanks for confirming!
