### ISSUE TITLE
Trivy image scans inside docker hangs

### ISSUE THREAD

**Issue by liad5h** [aquasecurity/trivy#2048]
## Description

Hey,

In my jenkins pipeline I run trivy image scans before publishing the images.
Trivy is running as a container:
```
docker.image('aquasec/trivy:latest').inside("""-v /var/run/docker.sock:/var/run/docker.sock -u 0 --entrypoint=''""") {
    trivyScanResult = sh(script: "/usr/local/bin/trivy image ...", returnStdout: true)
}
```

In the last couple of days my jobs are failing when they reach the scan due to one of the following:
- trivy consuming 100% CPU
- trivy reaching timeout of 5 or 10 minutes

This happens with small (30 MB) and large (> 1GB) images.
All images are stored locally on the machine during the scan.

When I login to the machines and start the container manually, I observe the same issue.
If I download trivy to the machines and run it outside of docker, everything works fine.

One of the machines I am using was running trivy, with the same code,  without any issues for a few months.

## What did you expect to happen?
trivy scans usually finish in a matter of seconds to a minute.

## What happened instead?
trivy hangs / timesout.

## Output of run with `-debug`:
```
/usr/local/bin/trivy --debug image --severity HIGH,CRITICAL <image>
2022-04-26T07:41:56.279Z	DEBUG	Severities: HIGH,CRITICAL
```

## Output of `trivy -v`:

```
Version: 0.27.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-04-26 06:06:39.247959855 +0000 UTC
  NextUpdate: 2022-04-26 12:06:39.247959555 +0000 UTC
  DownloadedAt: 2022-04-26 07:05:35.00901385 +0000 UTC
```

## Additional details (base image name, container registry info...):

This does not seems to happen in version 0.25.3.
with version 0.25.3 the scan process takes 10-20 seconds.

**Comment by knqyf263** [comment]
Could you try `/usr/local/bin/trivy image --security-checks vuln`? We want to check if secret scanning causes it or not.

**Comment by liad5h** [comment]
@knqyf263 with this flag trivy completed in 10 seconds again, is this a new feature?

**Comment by knqyf263** [comment]
We enabled secret scanning by default. If you pass `--skip-dirs` or `--skip-files` to skip your large directories/files, the scanning would be faster.

**Comment by knqyf263** [comment]
@liad5h Does your image contain large files like minified javascript file? We'd like to know why it got slow.

**Comment by StijnNoot** [comment]
So I was experiencing the same issue when running trivy on a docker image. We basically ran the following commands in our `bamboo-build.sh`:
`scan --exit-code 0 --format template --template "@contrib/html.tpl" -o /reports/report.html`
`scan --exit-code 1 --ignore-unfixed --severity CRITICAL --offline-scan`

The first of these seemed to be doing fine, and exiting the scan as expected. The second one however would get stuck without letting know why or on which files.
after checking the files it was accessing in a different window on the same image with the `lsof` command we would see that it would not access anything after the following
`25  	/usr/local/bin/trivy   	9     	/cache/db/trivy.db`

After this we went through each individual part of the commands we were executing, which eventually led us to the following solution turning the second command into the following:
`scan --exit-code 1 --format template --template "@contrib/html.tpl" -o /reports/report-CRITICAL.html --ignore-unfixed --severity CRITICAL --offline-scan`
and letting our builds succeed.

I hope this might help some of you or maybe the developers in solving this issue of the trivy scans getting stuck in docker.

**Comment by liad5h** [comment]
> @liad5h Does your image contain large files like minified javascript file? We'd like to know why it got slow.

@knqyf263 this happened both with rather small (30MB) and large (>1GB images).
Let me know if I misunderstood your question.

**Comment by mkruliv** [comment]
Same situation for me too. Revert back to trivy 0.26.0 helped

**Comment by knqyf263** [comment]
@StijnNoot Looks like your case is different. You just ran two processes and got stuck. Trivy uses BoltDB that obtains a file lock on the data file so multiple processes cannot open the same database at the same time.

**Comment by knqyf263** [comment]
>@knqyf263 this happened both with rather small (30MB) and large (>1GB images).

I was asking if your container image contains a large file. Trivy uses regexp for secret detection and it takes some time when an image contains a lot of files or large files.

Could you give me an example image or Dockerfile building your image? You can remove lines that you don't want to share. We want to reproduce it in our environment.

**Comment by schewara** [comment]
We ran into the same one yesterday.

In our case we have one fat jar File in the container and a downgrade to 0.26 fixed it for us as well.

**Comment by liad5h** [comment]
@knqyf263 the 30MB image does not contain large files.

here is a dockerfile example where this issue happened.
```
FROM nginx:1.19-alpine

LABEL version=<version>

WORKDIR <workdir>

RUN apk update && apk add bash
RUN rm -f /etc/nginx/conf.d/default.conf

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/startup.sh ./startup.sh
COPY build/ .

ENTRYPOINT ["/bin/bash", "./startup.sh"]
```

The `docker.image` call in jenkins mounts the current workspace to the container, in this case - trivy.
maybe this is related?

**Comment by dinapappor** [comment]
For information this also happens when you for instance use `docker:dind` (docker in docker) in gitlab pipelines with both `0.27.0` and `0.27.1` (These does however workout side of a docker in docker environment). `0.26.0` is unaffected.

**Comment by dinapappor** [comment]
This still seems to happen with `0.28.0`
