### ISSUE TITLE
Re-add Windows binary to releases.

### ISSUE THREAD

**Issue by Johannestegner** [aquasecurity/trivy#2058]
Hi!

There are a few of us developers who uses windows (it's true!), and having trivy binary directly on windows is quite nice, especially after the new jetbrains plugin have been created!
I understand that it was removed earlier due to some stuff not working as expected (image scanning for example), but by building it locally

_(in `wsl` ubuntu)_
```
GOARCH=amd64 GOOS=windows go build -o trivy.exe cmd/trivy/main.go
```
I could produce a binary which works fine (even the image scanning tool).

Is there any currently known issue which hinders a windows binary to be added to the release scripts or should I create a PR to re-add it to them?
If there is no wish to have windows binaries at all, I'm totally fine with that as well, building it from source is not a huge deal either way! :)

**Comment by itaysk** [comment]
related PR #1469

**Comment by olljanat** [comment]
FYI. I replaced #1469 with #2592 and included test binary to there. It would be nice if others can also test and report results to that PR as it looks to be that Trivy maintainers are Linux only users and are not able to test.

**Comment by DmitriyLewen** [comment]
Hello @olljanat , @owenrumney 

User found problem with table report in Windows(#3039).
Can you include fix for it in PR?

Regards, Dmitriy

**Comment by tomkerkhove** [comment]
+1 on brining this back

**Comment by itaysk** [comment]
we're looking into this in https://github.com/aquasecurity/trivy/pull/3037. not sure it will be merged for this month's release though.
