### ISSUE TITLE
operation.NewCache() print the redis user and password to log

### ISSUE THREAD

**Issue by afghanistanyn** [aquasecurity/trivy#2081]
## Description
`
func NewCache(c option.CacheOption) (Cache, error) {
	if strings.HasPrefix(c.CacheBackend, "redis://") {
		log.Logger.Infof("Redis cache: %s", c.CacheBackend)
`
will print redis user and password to log  if cacheBackend like  "user:pass@localhost:6379/0"

## What did you expect to happen?
remov it or change log to  debug level

**Comment by Kanika637** [comment]
I would like to work on this, could you please guide me toward this @knqyf263

**Comment by knqyf263** [comment]
@Kanika637 Thanks. The code is here. If `@` is found, we should mask characters between `//` and `@` by `****`.
https://github.com/aquasecurity/trivy/blob/b7ec64257279b5f9c47ac02063e12c5305f5af8a/pkg/commands/operation/operation.go#L36
