### ISSUE TITLE
Harbor trivy misconfiguration scan

### ISSUE THREAD

**Issue by ivnilv** [aquasecurity/trivy#2088]
Is there a way to make harbor installed trivy to scan for misconfigurations?

Currently, the scanner is connected to harbor and images are scanned but only for vulnerabilities. 

I need a way to detect misconfigurations as well.

**Comment by knqyf263** [comment]
Unfortunately, I don't think it is available now. cc: @danielpacak

**Comment by knqyf263** [comment]
I think it should be discussed in the Harbor repository.

**Comment by Kilz78** [comment]
@knqyf263 Hi, any link to one issue on the harbor project related this request ? 

I have the same needs, so I'm not sure to understand well, trivy can scan for misconfiguration but why it's not possible to do this type of scan directly with harbor ?
