### ISSUE TITLE
Installation >  RHEL/CentOS documentation error: incorrect baseurl in yum trivy.repo

### ISSUE THREAD

**Issue by fdavis99** [aquasecurity/trivy#2099]
## Description
Created trivy.repo per instructions in https://aquasecurity.github.io/trivy/v0.27.1/getting-started/installation/#rhelcentos

Problem 1: the '$' in the instructions must be quoted with backslash (see https://stackoverflow.com/a/44494477/1701482)

Problem 2: After correcting the file, yum fails on Red Hat Enterprise Linux Server release 7.7 (Maipo), using the baseurl in the trivy.repo file:
```
[trivy]
name=Trivy repository
baseurl=https://aquasecurity.github.io/trivy-repo/rpm/releases/$releasever/$basearch/
gpgcheck=0
enabled=1
```

## What did you expect to happen?
sudo yum makecache fast (and other yum commands) should work for the trivy repo without error.

## What happened instead?
Based on the above trivy.repo file, yum generates a URL that doesn't exist on the trivy github server:
https://aquasecurity.github.io/trivy-repo/rpm/releases/7Server/x86_64/repodata/repomd.xml

## Output of run with `-debug`:
```
$ sudo yum makecache fast
[...]
https://aquasecurity.github.io/trivy-repo/rpm/releases/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
 One of the configured repositories failed (Trivy repository),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=trivy ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable trivy
        or
            subscription-manager repos --disable=trivy

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=trivy.skip_if_unavailable=true

failure: repodata/repomd.xml from trivy: [Errno 256] No more mirrors to try.
https://aquasecurity.github.io/trivy-repo/rpm/releases/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

## Output of `trivy -v`:

N/A, since this error is the installation information on the web page https://aquasecurity.github.io/trivy/v0.27.1/getting-started/installation/#rhelcentos.

## Additional details (base image name, container registry info...):
In /etc/yum.repos.d/trivy.repo, tried setting baseurl to the resolved URL https://github.com/aquasecurity/trivy-repo/tree/main/rpm/releases/7/x86_64/ (which does contain repodata/repomd.xml) but got this error:
```
failure: repodata/repomd.xml from trivy: [Errno 256] No more mirrors to try.
https://github.com/aquasecurity/trivy-repo/blob/main/rpm/releases/7/x86_64/repodata/repomd.xml: [Errno 14] curl#63 - "Callback aborted"
```
According to https://bgstack15.wordpress.com/2019/05/01/yum-curl-error-63-callback-aborted/ 
When yum fails to download a file due to “curl error #63: Callback aborted,” that means that reposync downloaded the rpm file incorrectly. It doesn’t match the expected checksum in the metadata file.

**Comment by DmitriyLewen** [comment]
Hello @fdavis99 
Thanks for your report!

We will add backslash to instruction.
We will also try to solve problem for RHEL without `distroverpkg` field in `/etc/yum.conf` file.

Currently, you can add backslash to `$basearch`, change `$releasever` to `7` and download Trivy:
```
cat << EOF | sudo tee -a /etc/yum.repos.d/trivy.repo
[trivy]
name=Trivy repository
baseurl=https://aquasecurity.github.io/trivy-repo/rpm/releases/7/\$basearch/
gpgcheck=0
enabled=1
EOF
sudo yum -y update
sudo yum -y install trivy
```

Regards, Dmitriy

**Comment by fdavis99** [comment]
Unfortunately Googling trivy install shows links to
https://aquasecurity.github.io/trivy/v0.18.3/installation/ and
https://aquasecurity.github.io/trivy/v0.15.0/installation/. I guess it will
take time for this fix to propagate to the latest page
https://aquasecurity.github.io/trivy/v0.28.0/getting-started/installation/

Since it's doc and not code, it would be better to patch older versions. I
know that's prob too much work, but it has been quite challenging to find
out how to successfully install Trivy. A lot of people are probably lost.

Just adding information, feel free to ignore if not worth the time. You
folks are great -- thanks for the quick response.

--Franklin
