### ISSUE TITLE
Trivy releases: v0.26.0->v0.27.0->v0.27.1->v0.27.0->v0.27.1 ???

### ISSUE THREAD

**Issue by PenelopeFudd** [aquasecurity/trivy#2103]
## Description

I'm monitoring the [Trivy release page](https://github.com/aquasecurity/trivy/releases) so I know when to get the latest and greatest version, and in the past two days something weird happened: the release version went backwards!

![image](https://user-images.githubusercontent.com/1606480/167956577-eca371ea-a24f-43ea-8cad-2114a6704713.png)

## What did you expect to happen?
Expected the version to be monotonically increasing (e.g. v0.28.0 today), especially since the v0.28.0 release notes came out yesterday: https://github.com/aquasecurity/trivy/issues/2097

## What happened instead?
It went from v0.27.1 back to v0.27.0 on May 9th, and then to v0.27.1 on May 10th

## Output of run with `-debug`:

n/a

## Output of `trivy -v`:

n/a

## Additional details (base image name, container registry info...):

The handy-dandy Firefox addon "Distill Web Monitor" (by Distill), is the tool that alerted me to the changes.  I recommend it.

**Comment by PenelopeFudd** [comment]
Good news, the release page finally shows v0.28.0.
I'm leaving this ticket open so that you get a chance to see it, as it may be concerning even if it has corrected itself.

**Comment by knqyf263** [comment]
Actually, we have no idea why it disappeared. We released it again.
https://github.com/aquasecurity/trivy/discussions/2095#discussioncomment-2722172
