### ISSUE TITLE
Can we scan all images present in registry at once with trivy 

### ISSUE THREAD

**Issue by samkhamk** [aquasecurity/trivy#2105]
Hello Team,

My question is way too basic but I am new to trivy and doing some research how we can scan all images present in registry at once with trivy , 
do I need to use for loop or we can pass any option while scanning the image.

Please guide,

Thanks! 
SAM

**Comment by knqyf263** [comment]
Trivy doesn't support scanning all images in registry.

>do I need to use for loop or we can pass any option while scanning the image.

Yes, you have to do that.
