### ISSUE TITLE
Integrating trivy with GCR ( google container registry) in Gitlab CI

### ISSUE THREAD

**Issue by cyrine-souid** [aquasecurity/trivy#2125]
I'm trying to integrate trivy with GCR in my pipeline to scan images , tried the official documentation code : 

  ```
 must set TRIVY_USERNAME empty char
  export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credential.json

```
It didn't work , and I'm struggling to authenticate to GCR with trivy, did anyone solve a similar issue ? 
( I'm avoiding using docker, docker dind... and did the build with kaniko )

**Comment by Shivam-nagar23** [comment]
Facing the same Issue @cyrine-souid . Did you find anything on this. Will be of great help.
