### ISSUE TITLE
SPDX Report is missing Relationship field

### ISSUE THREAD

**Issue by Pivotal-Jeff-Jun** [aquasecurity/trivy#2139]
## Description

I have ran `trivy image --format spdx-json --output result.spdx ubuntu:latest` and I was expecting `relationship` field to be available. However, it did not have any relationship information available.

## What did you expect to happen?

Expected relationship information between image and the packages, as well as relationship between packages (parent vs subpackage)

## What happened instead?

Got SBOM in SPDX 2.2 format without relationships information.

## Output of `trivy -v`:

```
Version: dev
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-05-16 18:11:12.155276451 +0000 UTC
  NextUpdate: 2022-05-17 00:11:12.155275851 +0000 UTC
  DownloadedAt: 2022-05-16 19:02:36.827604 +0000 UTC
```

## Additional details (base image name, container registry info...):
* [Link to SPDX doc on relationships](https://spdx.github.io/spdx-spec/relationships-between-SPDX-elements/)

**Comment by knqyf263** [comment]
@ShiraCohen33 Could you take a look?
