### ISSUE TITLE
trivy config just got slower

### ISSUE THREAD

**Issue by ahysing** [aquasecurity/trivy#2162]
In my company we use `trivy config` to scan for security issues in kubernetes configuration **before** applying them to the cluster. Up until now we have had great success by running trivy version v0.25.3 on all our configuration. We scan a folder with all the expanded YAML files for kubernetes. the exact command is.
`trivy config  --format sarif -o report.sarif .`

After upgrading to release v0.28.0 this just got slower. I am doing this job inside azure devops. the machine is throttled by the cloud provider, but with version v0.25.3 we were able to do this job within 3 minutes.
After upgrading the same process takes 1 hour before it times out!!!
the same issue is present on the developer PC. on my 6 core mac I am able to run `trivy config  --format sarif -o report.sarif .`. It runs for 3 to 4 minutes before it finishes.

Are there any quick tricks to make `trivy config` faster?

**Comment by ahysing** [comment]
Testing further I found that there is a significant increase of scan times (`sarif config`) between version 0.27.1 and 0.28.0

**Comment by ahysing** [comment]
this is me testing sarif scan on the relevant files on my local machine. from 0.27.1 to 0.28.0 sarif scan times went from 7 seconds to 3 minutes:

```
andreasdreyerhysingvippsnos-MacBook-Pro:~ andreas.dreyer.hysing$ time /Users/andreas.dreyer.hysing/Downloads/trivy_0.27.1_macOS-64bit/trivy config --format sarif -o report.sarif /Users/andreas.dreyer.hysing/code/Cloud-Platform/vce-infra/resources/
2022-05-20T12:33:53.972+0200	INFO	Detected config files: 121

real	0m7.798s
user	0m12.284s
sys	0m0.589s
andreasdreyerhysingvippsnos-MacBook-Pro:~ andreas.dreyer.hysing$ time /Users/andreas.dreyer.hysing/Downloads/trivy_0.28.0_macOS-64bit/trivy config --format sarif -o report.sarif /Users/andreas.dreyer.hysing/code/Cloud-Platform/vce-infra/resources/
2022-05-20T12:37:54.204+0200	INFO	Detected config files: 121

real	3m56.822s
user	4m27.690s
sys	0m3.025s
```
this test was performed on a Mac with these specs
<img width="590" alt="image" src="https://user-images.githubusercontent.com/1487947/169512248-6d6ad48b-9022-423b-8a39-f38a150c2b9c.png">

**Comment by knqyf263** [comment]
I think it is the same issue as https://github.com/aquasecurity/trivy/issues/2141.

**Comment by knqyf263** [comment]
Could you try [v0.28.1](https://github.com/aquasecurity/trivy/releases/tag/v0.28.1)? If you still see the issue, please feel free to reopen it.
