### ISSUE TITLE
Trivy service access

### ISSUE THREAD

**Issue by ajinkya1986** [aquasecurity/trivy#2164]
How can we access the trivy service externally if we are using a trivy docker image or installing it locally? I want to pass the image info and arguments to the trivy service externally and get the output so that we can use the output for backend consumption?

**Comment by afdesk** [comment]
@ajinkya1986 `Trivy` has `client/server` mode now, you can read here: https://aquasecurity.github.io/trivy/v0.28.0/docs/references/modes/client-server/
