### ISSUE TITLE
Trivy k8s scanning fails with context deadline exceeded error

### ISSUE THREAD

**Issue by gowthamshankar99** [aquasecurity/trivy#2169]
## Description

Trivy Kubernetes Scanning fails with the following error when scanning the entire cluster 

Note - the scan works ok when a specific namespace is scanned but fails when entire cluster is scanned with ```context deadline exceeded``` error

```
➜  trivy k8s --report summary
2022-05-22T17:54:57.663-0400	INFO	Need to update DB
2022-05-22T17:54:57.663-0400	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2022-05-22T17:54:57.663-0400	INFO	Downloading DB...
31.94 MiB / 31.94 MiB [---------------------------------------------------------------------------------------------------------------] 100.00% 21.15 MiB p/s 
78 / 5373 [-->_______________________________________________________________________________________________________________________________________] 1.45% 0 p/s
2022-05-22T17:59:57.599-0400	FATAL	k8s scan error: scanning misconfigurations error: scan error: image scan failed: failed analysis: failed to call hooks: post handler error: scan config error: context deadline exceeded
```

**Comment by josedonizetti** [comment]
@gowthamshankar99 Thank you for reporting. This error is happening because your cluster is big, `5373` resources. The default timeout currently is `300s`, would you mind trying to run the scan with a bigger timeout? 

```
$ trivy k8s --report summary --timeout 900s
```

That is a great insight though, I will improve the error message to be more clear about the timeout, and also there some PRs coming to improve performance.

**Comment by gowthamshankar99** [comment]
@josedonizetti  - this helps thanks ! I will give that a try

**Comment by knqyf263** [comment]
Please feel free to reopen the issue if you still have the same issue. Thanks.

**Comment by nrjsingh167** [comment]
trivy k8s --security-checks=config --report=summary cluster --timeout 1800s
1352 / 6705 [----------------------------------->___________________________________________________________________________________________________________________________________________] 20.16% 5 p/s
2022-06-17T09:49:13.774+0530	FATAL	k8s scan error: scanning misconfigurations error: scan error: image scan failed: failed analysis: failed to call hooks: post handler error: scan config error: eval_cancel_error: caller cancelled query execution

**Comment by josedonizetti** [comment]
@nrjsingh167 Thanks for reporting. Would you mind trying `trivy k8s --security-checks=config --report=summary --timeout=1800s cluster`. Flags after the target `cluster` are ignored.

**Comment by nrjsingh167** [comment]
Can you help me for cluster scanning command with timeout
`trivy k8s --report summary --timeout 3600 cluster`
Its not  working

**Comment by josedonizetti** [comment]
@nrjsingh167 do you get the same error when scanning a single namespace? ‘trivy k8s —report=summary all’

**Comment by nrjsingh167** [comment]
trivy k8s -n kube-system --report=summary all --timeout 1800
7 / 46 [--------------------------->________________________________________________________________________________________________________________________________________________________] 15.22% 0 p/s
2022-06-20T09:54:20.687+0530	WARN	Increase --timeout value
2022-06-20T09:54:20.687+0530	FATAL	k8s scan error: scanning misconfigurations error: scan error: image scan failed: failed analysis: failed to call hooks: post handler error: scan config error: context deadline exceeded

**Comment by josedonizetti** [comment]
@nrjsingh167 To be sure, because the command you posted here wouldn't use the timeout, can you try:

```
trivy k8s -n kube-system --report=summary --timeout 1800s all 
```

The `--timeout` flag must come before the target `all` or `cluster`

**Comment by DrissiReda** [comment]
> Can you help me for cluster scanning command with timeout `trivy k8s --report summary --timeout 3600 cluster` Its not working

Make sure to add the unit `s` to your seconds, so the command should be:

```
trivy k8s --report summary --timeout 3600s cluster
```
