### ISSUE TITLE
ppc64le is no longer available after relase 0.23. 

### ISSUE THREAD

**Issue by rpsene** [aquasecurity/trivy#2177]
Power is no longer available as part of the releases. Was it removed or is this a CICD issue?

**Comment by afdesk** [comment]
@rpsene thanks for your report. let me take a look at the reason.

**Comment by afdesk** [comment]
The reason is here #1694:

> modernc.org/sqlite (technically modernc.org/libc) doesn't support the following pairs and we need to drop those supports for now.
> ...
>  */ppc64le

**Comment by rpsene** [comment]
@afdesk thanks for replying. I do believe the libc issue was recently fixed. We will check.

**Comment by DanielCasali** [comment]
@afdesk Power is supported now on the latest libc v1.16.7 and ssqlite v1.17.3 fixed this and I just tested the build after altering go.mod for this versions and running
`go get github.com/knqyf263/go-rpmdb/pkg/sqlite3@v0.0.0-20220209103220-0f7a6d951a6d`
trivy seems to run fine after compiled:
`[root@power-compare-eu-de-2-bastion-0 trivy]# ./trivy image docker.io/library/golang:alpine
2022-05-25T11:42:48.865Z	INFO	Need to update DB
2022-05-25T11:42:48.865Z	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2022-05-25T11:42:48.865Z	INFO	Downloading DB...
32.03 MiB / 32.03 MiB [---------------------------------------------------------------------------------------------------------------------] 100.00% 21.34 MiB p/s 1.7s
2022-05-25T11:43:11.853Z	INFO	Detected OS: alpine
2022-05-25T11:43:11.853Z	INFO	This OS version is not on the EOL list: alpine 3.16
2022-05-25T11:43:11.853Z	INFO	Detecting Alpine vulnerabilities...
2022-05-25T11:43:11.854Z	INFO	Number of language-specific files: 0

docker.io/library/golang:alpine (alpine 3.16.0)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

[root@power-compare-eu-de-2-bastion-0 trivy]#`

**Comment by knqyf263** [comment]
Great! Could you open a PR updating those dependencies?
https://github.com/knqyf263/go-rpmdb

**Comment by rpsene** [comment]
@knqyf263 https://github.com/knqyf263/go-rpmdb/pull/23

**Comment by rpsene** [comment]
@knqyf263 the PR with the updates for the go-rpmdb was merged. We can now continue the work on this issue.

**Comment by knqyf263** [comment]
Thanks. We need to update go-rpmdb in fanal first.

**Comment by rpsene** [comment]
@knqyf263 https://github.com/aquasecurity/fanal/pull/553

**Comment by knqyf263** [comment]
Thanks, but it is failing.

**Comment by rpsene** [comment]
@knqyf263 Fanal is updated https://github.com/aquasecurity/fanal/pull/553#issuecomment-1150776807, can we proceed now?

**Comment by rpsene** [comment]
https://github.com/aquasecurity/trivy/pull/2281/files

**Comment by knqyf263** [comment]
Thanks, but it is failing.

**Comment by knqyf263** [comment]
I think you need to bump fanal.
