### ISSUE TITLE
docs: Installation on Debian/Ubuntu: follow Debian's "instructions to connect to a third-party repository"

### ISSUE THREAD

**Issue by elchenberg** [aquasecurity/trivy#2180]
According to the Debain wiki keys “MUST NOT be placed in /etc/apt/trusted.gpg.d or loaded by apt-key add.”: <https://wiki.debian.org/DebianRepository/UseThirdParty>

So instead of this:

```bash
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
```

the [Debian/Ubuntu installation instructions](https://github.com/aquasecurity/trivy/blob/v0.28.0/docs/getting-started/installation.md#debianubuntu) could look like this:

```bash
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
```

**Comment by knqyf263** [comment]
Sounds reasonable! Could you open a PR?

**Comment by elchenberg** [comment]
Sure, can do. Unless someone else is faster. :slightly_smiling_face:

**Comment by knqyf263** [comment]
would be helpful
