### ISSUE TITLE
Kube-bench checks with Trivy

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#2198]
Epic to track work on adding kube-bench support 

- [x] https://github.com/aquasecurity/trivy/issues/2199
- [x] https://github.com/aquasecurity/trivy/issues/2200
- [x] https://github.com/aquasecurity/trivy/issues/2766
- [x] https://github.com/aquasecurity/trivy/issues/2919
- [x] https://github.com/aquasecurity/trivy/issues/3276
- [x] https://github.com/aquasecurity/trivy/issues/2201

**Comment by knqyf263** [comment]
All of the tasks are closed.
