### ISSUE TITLE
Detect secrets in container environment variables

### ISSUE THREAD

**Issue by rcarpio-hbo** [aquasecurity/trivy#2204]
Scan container images for secrets present in the container environment variables.

Example Dockerfile with AWS secret:
```
FROM node:12.22.12-slim
 
ENV AWS_SECRET_ACCESS_KEY erHSKM98c+afa418tkewJRjsdaJMxuiSgOExample
```

**Comment by itaysk** [comment]
I think we can expand the scope of this issue to "detect secrets in misconfiguration scanning"?

**Comment by knqyf263** [comment]
Yes, that is what I said. It is scanning config of images.

**Comment by gliwka** [comment]
The secret is also part of the image history, not just the configuration.

**Comment by rcarpio-hbo** [comment]
@knqyf263 are you planning to implement this feature in the near future?

**Comment by knqyf263** [comment]
No, but we welcome any contribution.

**Comment by itaysk** [comment]
related to issue: https://github.com/aquasecurity/trivy/issues/2676
If we would infer the dockerfile of an image, we could scan it for exposed secrets as well

**Comment by knqyf263** [comment]
>The secret is also part of the image history, not just the configuration.

FYI: The image configuration includes history as well.
