### ISSUE TITLE
Vulnerability scanning for Dockerfile

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/trivy#2225]
Today Trivy can identify configuration issues in Dockerfile (e.g. "USER" statement is not specified).

It would be super nice if Trivy could also scan the base image that the Dockerfile is referring to ("FROM" statement) and show the amount of vulnerabilities it has.

This way, when scanning Dockerfile we will get both the misconfigurations and the vulnerabilities that are related to the image that will be created by this Dockerfile.

**Comment by knqyf263** [comment]
In favor of https://github.com/aquasecurity/trivy/issues/1984
