### ISSUE TITLE
Replace Kube-bench NSA checks with rego policies

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#2254]
## Description
it is required to replace the kube-bench NSA checks with rego policies

**Comment by chen-keinan** [comment]
depend on #2198

**Comment by itaysk** [comment]
@chen-keinan @josedonizetti  is this the issue for the "infra checks"? If so, (I don't think it's very clear from the description) is it making this release or next?

**Comment by josedonizetti** [comment]
@itaysk Don't think NSA is for infra-checks. Though I didn't release we are about to release, I have just synced with Teppei to post it to tmr, so I can close it today. I really want it to make the release.

**Comment by chen-keinan** [comment]
@itaysk Its not nsa , its basically replacing kube-bench checks ,its exactly what @josedonizetti is doing , can be closed as duplucate to task Jose is working on

**Comment by itaysk** [comment]
so can we rename/rewrite this issue to something more meaningful?

**Comment by josedonizetti** [comment]
This is a duplication of https://github.com/aquasecurity/trivy/issues/2766. Closing!
