### ISSUE TITLE
Allow multiple --template params

### ISSUE THREAD

**Issue by redsigma** [aquasecurity/trivy#2259]
It would be nice for trivy to accept multiple params or an actual folder. The syntax would be
```
trivy image --format template   --template  "@./boilerplate_setup.tpl" --template "@./report-format.tpl"  
```

The `boilerplate_setup.tpl` will contain defines such as
```
{{- define "include_css_data" -}}
{{- printf "<styles> ... </styles>"  -}}
{{- end }}
```

The `report-format.tpl` will only contain the valuable data
```
{{ template "include_css_data" $ }}

// valuable data goes here

```

Seems that this was also discussed here https://github.com/aquasecurity/trivy/pull/835

**Comment by preetamap** [comment]
Indeed a good feature to have, avoids multiple scans..
Alternatively feature to convert json to html or csv would also help..

**Comment by knqyf263** [comment]
In favor of https://github.com/aquasecurity/trivy/issues/3243
