### ISSUE TITLE
Authentication issues with Gitlab - repository scan error: scan error: unable to initialize a scanner: unable to initialize a filesystem scanner: git error: authorization failed

### ISSUE THREAD

**Issue by miglen** [aquasecurity/trivy#2260]
## Description
Hello, I was trying to use the latest ability to scan remote gitlab images in a private group. I had created a token, tested, and verified that it works with python-gitlab (same libaryr you use in trivy) but I keep getting authentication issues. I had exported the `GITLAB_TOKEN`, verified and even unset the `GITHUB_TOKEN`

## What did you expect to happen?
To be able to scan the remote private GitLab repository.

## What happened instead?
I had received a scan error - authorization failed.

## Output of run with `-debug`:

```
➜  ~ trivy -d repo gitlab.com/private/package
2022-06-03T14:39:42.168+0300	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-06-03T14:39:42.172+0300	DEBUG	cache dir:  /home/miglen/.cache/trivy
2022-06-03T14:39:42.172+0300	DEBUG	DB update was skipped because the local DB is the latest
2022-06-03T14:39:42.174+0300	DEBUG	DB Schema: 2, UpdatedAt: 2022-06-03 06:06:41.981063556 +0000 UTC, NextUpdate: 2022-06-03 12:06:41.981062956 +0000 UTC, DownloadedAt: 2022-06-03 07:55:36.810620987 +0000 UTC
2022-06-03T14:39:42.174+0300	DEBUG	Vulnerability type:  [library]
2022-06-03T14:39:42.948+0300	FATAL	repository scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:334
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*Runner).Scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:182
  - unable to initialize a scanner:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:458
  - unable to initialize a filesystem scanner:
    github.com/aquasecurity/trivy/pkg/commands/artifact.repositoryStandaloneScanner
        /home/runner/work/trivy/trivy/pkg/commands/artifact/repository.go:16
  - git error:
    github.com/aquasecurity/fanal/artifact/remote.NewArtifact
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220519114754-f9a9d959763a/artifact/remote/git.go:53
  - authorization failed

```

## Output of `trivy -v`:

```
Version: 0.28.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-06-03 06:06:41.981063556 +0000 UTC
  NextUpdate: 2022-06-03 12:06:41.981062956 +0000 UTC
  DownloadedAt: 2022-06-03 07:55:36.810620987 +0000 UTC

```

## Additional details (base image name, container registry info...):
Private, sorry.

**Comment by afdesk** [comment]
@miglen thanks for your report.
I can reproduce this issue. will investigate more.

**Comment by afdesk** [comment]
oh, it seems this is an authentication problem. 
you need to use [a personal access token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) for private repositories and set up an environment variable `GITLAB_TOKEN` for `Trivy` (https://aquasecurity.github.io/trivy/v0.28.1/docs/vulnerability/scanning/git-repository/):
```
$ GITLAB_TOKEN=glxxx-pRrivateToken trivy -d repo gitlab.com/private/package
```

**Comment by afdesk** [comment]
@miglen could you check the permissions for your gitlab token?

**Comment by afdesk** [comment]
I've set up only one permission for my gitlab token - `read_repository`, and it works for me...

**Comment by miglen** [comment]
I had re-issued the same token with the same permissions (read_api, read_repository, read_registry) and it worked.
