### ISSUE TITLE
Problem while trying to run trivy from docker container (with offline DB)

### ISSUE THREAD

**Issue by crytech7** [aquasecurity/trivy#2283]
Hi, could you please advice me  how to fix this error (maybe I specified the cache dir in incorrect way?):

![image](https://user-images.githubusercontent.com/75042095/172457735-f1e366c0-e330-49c2-af4e-420875c968cb.png)

I was trying to run a container with Trivy build from Dockerfile:

    FROM ubuntu:18.04

    RUN apt-get update \
     && apt-get install -y wget

    RUN wget https://github.com/aquasecurity/trivy/releases/download/v0.28.1/trivy_0.28.1_Linux-64bit.deb
    RUN dpkg -i trivy_0.28.1_Linux-64bit.deb

    RUN rm trivy_0.28.1_Linux-64bit.deb

    RUN mkdir -p /root/.cache/trivy/db
    RUN cd /root/.cache/trivy/db
    RUN wget https://github.com/aquasecurity/trivy-db/releases/latest/download/trivy-offline.db.tgz
    RUN tar xf trivy-offline.db.tgz

    RUN rm trivy-offline.db.tgz

    RUN trivy --cache-dir /root/.cache/trivy/db

    ENTRYPOINT ["trivy"]

**Comment by afdesk** [comment]
Hi @crytech7 try to use `/root/.cache/trivy/` without `db`.

**Comment by afdesk** [comment]
also you need to use `oras` for downloading. read more here: [Air-Gapped Environment](https://aquasecurity.github.io/trivy/v0.28.1/docs/advanced/air-gap/)

**Comment by crytech7** [comment]
Hi, @afdesk thanks to your reply! 

1. I have added some fixes to Dockerfile following the instructions, but it did not helped.
2. I tried to reproduce same commands on my host OS - everything works. 
4. then I tried  to mount /root/.cache/ dir from host OS to the container /root/.cache/  dir:
![image](https://user-images.githubusercontent.com/75042095/172784366-0b9ad0a4-056c-4475-97b5-c0daf31a7fa7.png)

..and it successfully scans offline (first scan with my custom container image, second with official trivy container image)

5. So the problem is how to put Trivy offline DB inside the container?

**Comment by crytech7** [comment]
Dockerfile now:

     FROM ubuntu:18.04

    RUN apt-get update \
     && apt-get install -y wget \
     && apt-get install -y python3\
     && apt-get install -y curl


    RUN curl -LO https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_linux_amd64.tar.gz
    RUN mkdir -p oras-install/
    RUN tar -zxf oras_0.12.0_*.tar.gz -C oras-install/
    RUN mv oras-install/oras /usr/local/bin/
    RUN rm -rf oras_0.12.0_*.tar.gz oras-install/
   
    RUN wget https://github.com/aquasecurity/trivy/releases/download/v0.28.1/trivy_0.28.1_Linux-64bit.deb
    RUN dpkg -i trivy_0.28.1_Linux-64bit.deb

    RUN rm trivy_0.28.1_Linux-64bit.deb


    RUN mkdir -p /root/.cache/trivy/db/
    RUN cd /root/.cache/trivy/db/
    RUN oras pull ghcr.io/aquasecurity/trivy-db:2 -a
    RUN tar xvf db.tar.gz

    RUN trivy --cache-dir /root/.cache/trivy/
    RUN rm db.tar.gz

    ENTRYPOINT ["trivy"]

**Comment by afdesk** [comment]
@crytech7 there is a problem inside your Dockerfile with layers, so `Trivy` can't find the db. 

my missy sample works correctly: 
```Dockerfile

RUN mkdir -p /root/.cache/trivy/db/ \
    && oras pull ghcr.io/aquasecurity/trivy-db:2 -a && tar xvf db.tar.gz -C /root/.cache/trivy/db/ \
    && rm db.tar.gz

```
