### ISSUE TITLE
docs site version selector should omit patch version

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/trivy#2288]
currently we have a version selector for every git tag, which is unnecessary overhead on the user. It is not needed from documentation perspective as there aren't (shouldn't be) any docs change in patch versions, only for new/changed features. 

before:
v0.27.0, v0.27.1, v0.27.2, v0.28.0
after 
v0.27, v0.28

**Comment by itaysk** [comment]
I think we would need to
1. stop generating docs on patch versions
2. remove existing patch versions manually
I'll create a PR for 1

**Comment by knqyf263** [comment]
>remove existing patch versions manually

Do you think we can hide the existing versions in the version selector? It shows only minor versions like v0.30 and v0.31, but v0.30.0 is still valid though it is hidden. There are doc URLs in many places. I don't to make them 404.

e.g.
- v0.30
- v0.30.0 (hidden)
- v0.30.1 (hidden)
- v0.31
- v0.31.0 (hidden)
- v0.31.1 (hidden)
- v0.31.2 (hidden)
- v0.32
- v0.32.0 (will not be created anymore)

**Comment by itaysk** [comment]
After playing around with mkdocs and mike, it seems that 'mike alias' achieves this

**Comment by knqyf263** [comment]
Nice👍

**Comment by itaysk** [comment]
closed by #2900
