### ISSUE TITLE
From where the trivy retrieves vulnerability information?

### ISSUE THREAD

**Issue by jananathbanuka** [aquasecurity/trivy#2291]
I need to know 

1. From where `trivy` pulls its database?
2. How trivy's database keeps up to date? Where it pulls the CVE information?

**Comment by DmitriyLewen** [comment]
Hello @jananathbanuka 
Thanks for your interest to Trivy!

Trivy pulls database from [Trivy-db](https://github.com/aquasecurity/trivy-db). 
Trivy-db is updated every 6 hours.
Information about data sources that are included in Trivy-db is [here](https://aquasecurity.github.io/trivy/v0.28.1/docs/vulnerability/detection/data-source/).

Regards, Dmitriy

**Comment by jananathbanuka** [comment]
Thanks for this, It was very helpful
