### ISSUE TITLE
SIGSEGV when trying to scan Kubernetes on a M1 Macbook (arm64)

### ISSUE THREAD

**Issue by nycnewman** [aquasecurity/trivy#2309]
## Description

Attempting to scan a local (K-in-D) cluster results in a SIGSEGV error when printing the Misconfiguration results. The image vulnerabilities are displayed and then the following:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105ae6a04]

goroutine 1 [running]:
sync.(*Once).Do(...)
	sync/once.go:57
github.com/aquasecurity/trivy/pkg/report.TableWriter.setVulnerabilityRows({{0x14000746bc0, 0x5, 0x8}, {0x107b130b8, 0x14000010018}, 0x0, 0x0, 0x0}, 0x14002cc9390, {0x14001eb3600?, ...})
	github.com/aquasecurity/trivy/pkg/report/table.go:161 +0x134
github.com/aquasecurity/trivy/pkg/report.TableWriter.writeVulnerabilities({{0x14000746bc0, 0x5, 0x8}, {0x107b130b8, 0x14000010018}, 0x0, 0x0, 0x0}, 0x14002cc9390, {0x14001eb3600, ...})
	github.com/aquasecurity/trivy/pkg/report/table.go:152 +0x170
github.com/aquasecurity/trivy/pkg/report.TableWriter.write({{0x14000746bc0, 0x5, 0x8}, {0x107b130b8, 0x14000010018}, 0x0, 0x0, 0x0}, {{0x106c7d953, 0x6}, ...})
	github.com/aquasecurity/trivy/pkg/report/table.go:79 +0x28c
github.com/aquasecurity/trivy/pkg/report.TableWriter.Write(...)
	github.com/aquasecurity/trivy/pkg/report/table.go:48
github.com/aquasecurity/trivy/pkg/k8s.TableWriter.Write({{0x16b36b143, 0x3}, {0x107b130b8, 0x14000010018}, {0x14000746bc0, 0x5, 0x8}}, {0x0, {0x140014e51a0, 0x9}, ...})
	github.com/aquasecurity/trivy/pkg/k8s/table.go:25 +0x608
github.com/aquasecurity/trivy/pkg/k8s.write({0x0, {0x140014e51a0, 0x9}, {0x14001c22300, 0x1, 0x1}, {0x1400045ac00, 0x1, 0x1}}, {{0x106c7b00b, ...}, ...})
	github.com/aquasecurity/trivy/pkg/k8s/report.go:139 +0x1b4
github.com/aquasecurity/trivy/pkg/k8s.run({_, _}, _, {{0x1400148f500, 0x14000b1b870, {0x107405794, 0x6}, 0x0, 0x0, {0x14000648360, ...}}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/k8s/run.go:98 +0x16c
github.com/aquasecurity/trivy/pkg/k8s.Run(0x1400148f500)
	github.com/aquasecurity/trivy/pkg/k8s/run.go:89 +0x548
github.com/urfave/cli/v2.(*Command).Run(0x140010966c0, 0x1400148ea80)
	github.com/urfave/cli/v2@v2.5.1/command.go:163 +0x50c
github.com/urfave/cli/v2.(*App).RunContext(0x14000603860, {0x107b30030?, 0x140000580d8}, {0x1400004e180, 0x6, 0x6})
	github.com/urfave/cli/v2@v2.5.1/app.go:313 +0x888
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.5.1/app.go:224
main.main()
	github.com/aquasecurity/trivy/cmd/trivy/main.go:16 +0x5c

## What did you expect to happen?

Print out of full report

## What happened instead?

Seg Fault error

## Output of run with `-debug`:

```
2022-06-12T17:33:20.424-0400	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-06-12T17:33:20.478-0400	DEBUG	cache dir:  /Users/edwardnewman/Library/Caches/trivy
2022-06-12T17:33:20.478-0400	DEBUG	DB update was skipped because the local DB is the latest
2022-06-12T17:33:20.478-0400	DEBUG	DB Schema: 2, UpdatedAt: 2022-06-12 18:07:10.17903656 +0000 UTC, NextUpdate: 2022-06-13 00:07:10.17903636 +0000 UTC, DownloadedAt: 2022-06-12 21:32:58.393664 +0000 UTC
1 / 1 [----------------------------------------------------------------------------------------------------------------------] 100.00% 2 p/s

<Full table of vulnerabilities>

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101a02a04]

goroutine 1 [running]:
sync.(*Once).Do(...)
	sync/once.go:57
github.com/aquasecurity/trivy/pkg/report.TableWriter.setVulnerabilityRows({{0x140011727c0, 0x5, 0x8}, {0x103a2f0b8, 0x14000010018}, 0x0, 0x0, 0x0}, 0x140030d3390, {0x140023df760?, ...})
	github.com/aquasecurity/trivy/pkg/report/table.go:161 +0x134
github.com/aquasecurity/trivy/pkg/report.TableWriter.writeVulnerabilities({{0x140011727c0, 0x5, 0x8}, {0x103a2f0b8, 0x14000010018}, 0x0, 0x0, 0x0}, 0x140030d3390, {0x140023df760, ...})
	github.com/aquasecurity/trivy/pkg/report/table.go:152 +0x170
github.com/aquasecurity/trivy/pkg/report.TableWriter.write({{0x140011727c0, 0x5, 0x8}, {0x103a2f0b8, 0x14000010018}, 0x0, 0x0, 0x0}, {{0x102b99953, 0x6}, ...})
	github.com/aquasecurity/trivy/pkg/report/table.go:79 +0x28c
github.com/aquasecurity/trivy/pkg/report.TableWriter.Write(...)
	github.com/aquasecurity/trivy/pkg/report/table.go:48
github.com/aquasecurity/trivy/pkg/k8s.TableWriter.Write({{0x16f44f142, 0x3}, {0x103a2f0b8, 0x14000010018}, {0x140011727c0, 0x5, 0x8}}, {0x0, {0x140015556a0, 0x9}, ...})
	github.com/aquasecurity/trivy/pkg/k8s/table.go:25 +0x608
github.com/aquasecurity/trivy/pkg/k8s.write({0x0, {0x140015556a0, 0x9}, {0x1400226ac00, 0x1, 0x1}, {0x1400226af00, 0x1, 0x1}}, {{0x102b9700b, ...}, ...})
	github.com/aquasecurity/trivy/pkg/k8s/report.go:139 +0x1b4
github.com/aquasecurity/trivy/pkg/k8s.run({_, _}, _, {{0x14001a3ea80, 0x1400058f7a0, {0x103321794, 0x6}, 0x0, 0x1, {0x140007a73b0, ...}}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/k8s/run.go:98 +0x16c
github.com/aquasecurity/trivy/pkg/k8s.Run(0x14001a3ea80)
	github.com/aquasecurity/trivy/pkg/k8s/run.go:89 +0x548
github.com/urfave/cli/v2.(*Command).Run(0x14000f8f8c0, 0x14001a3e000)
	github.com/urfave/cli/v2@v2.5.1/command.go:163 +0x50c
github.com/urfave/cli/v2.(*App).RunContext(0x140014a11e0, {0x103a4c030?, 0x140000580d8}, {0x1400004e070, 0x7, 0x7})
	github.com/urfave/cli/v2@v2.5.1/app.go:313 +0x888
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.5.1/app.go:224
main.main()

```

## Output of `trivy -v`:

```
trivy -v
Version: 0.28.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-06-12 18:07:10.17903656 +0000 UTC
  NextUpdate: 2022-06-13 00:07:10.17903636 +0000 UTC
  DownloadedAt: 2022-06-12 21:32:58.393664 +0000 UTC
```

## Additional details (base image name, container registry info...):

K-in-D on Podman with Kubernetes 1.24
docker.io
nycnewman/web-frontend:0.5

**Comment by josedonizetti** [comment]
@nycnewman thank you for reporting, this was fixed at https://github.com/aquasecurity/trivy/pull/2175, and will be available at the next release. Feel free to reopen it, if still see  the problem on the next release.
