### ISSUE TITLE
How to Enable the File paths for vulnerabilities found in the docker image scan

### ISSUE THREAD

**Issue by nareshk355** [aquasecurity/trivy#2325]
Hi Team,

Could you please help by providing flags to enable filepaths for vulnerabilities found in docker images scanning.

we are using the below command for the scanning.

trivy image imagename

Thanks,
Naresh

**Comment by DmitriyLewen** [comment]
Hello @nareshk355 
Thanks for your interest to Trivy!

You can use `-format json` and `--list-all-pkgs` flags.
Result will include list of found packages with `FilePath` fields.
Example:

```json
"Target": "Java",
      "Class": "lang-pkgs",
      "Type": "jar",
      "Packages": [
        {
          "Name": "log4j:log4j",
          "Version": "1.2.17",
          "Layer": {
            "DiffID": "sha256:07f9f583b5a2cd6a8d6d03fc6055a4faf5b92996d2a8927ad89db60b2340cf30"
          },
          "FilePath": "usr/local/tmp/log4j-1.2.17.jar"
        }
```

Regards, Dmitriy
