### ISSUE TITLE
Trivy finds vulns for the packages not installed in the image

### ISSUE THREAD

**Issue by onrylmz** [aquasecurity/trivy#235]
Image Name: **adoptopenjdk/openjdk12**
Image Version: **x86_64-alpine-jdk-12.0.1_12-slim**

Eventhough the _curl_ and _nghttp2_ packages have not installed in the image, trivy still finds some vulnerabilities related to those packages.

As a workaround I tried to remove these packages via the command

`apk del curl nghttp2`

This removal does not affect the result and trivy still finds the same vulnerabilities.

**Comment by tisc0** [comment]
@onrylmz hi!
Could you post the command line you used & output ? Are you sure it's not the library scan that got some dependencies CVEs ?
Just my 2 cents

**Comment by onrylmz** [comment]
This is my command

`docker run --rm -v [MY_CACHE_DIR]:/root/.cache/  aquasec/trivy adoptopenjdk/openjdk12:x86_64-alpine-jdk-12.0.1_12-slim`

This is the output

<img width="800" alt="Screen Shot 2019-10-29 at 11 46 22" src="https://user-images.githubusercontent.com/6976362/67760515-c2d3f600-fa41-11e9-8784-ec9c50b059f3.png">

**Comment by imnotjames** [comment]
Could be that it was installed in a different layer and then removed?

In that case, trying to remove it again would still have it be caught.

**Comment by onrylmz** [comment]
> Could be that it was installed in a different layer and then removed?
> 
> In that case, trying to remove it again would still have it be caught.

I tried to remove these packages but trivy still finds the same vulns.

**Comment by imnotjames** [comment]
Right - but if they're in a previous layer, you cannot remove them via a later layer.  Looking at the source, I only see curl explicitly being added but it's possible nghttp2 is a transitive dependency. 

Both are added and removed in the source layer.

Not much that can be done about that, trying to remove them in a layer that depends on the source image, they're still possibly in the original.

There's a feature request elsewhere to denote those kinds of cases.

**Comment by knqyf263** [comment]
@imnotjames Thank you for the explanation! It's very very grateful!

@onrylmz Yes, @imlonghao  is right. This package is from the previous layer. I know it is not easy to understand. I will improve it.
