### ISSUE TITLE
Trivy sbom for python doesn't work for fs due to ignore requirements.txt file

### ISSUE THREAD

**Issue by csharpknife2002** [aquasecurity/trivy#2365]
## Description

I try to use trivy sbom command to scan and generate sbom information for my app in local.
I used the trivy 18.1 and 19.1 against a local node and python application  via this command
trivy sbom --artifact-type fs --output sbom-code-result.json  . 

## What did you expect to happen?
I am expection it works both for my node and python apps.
In my node app, I use express (in package.json), in my python app, i use flask( in requirements.txt)

According to https://aquasecurity.github.io/trivy/v0.29.1/docs/vulnerability/detection/language/
both node (package.json, package.json.lock) and python (requirements.txt) are supported.

## What happened instead?
It works with node app, but not the python app. The python requirements.txt is ignored, so there is no components are found.

{"bomFormat":"CycloneDX","specVersion":"1.4","serialNumber":"urn:uuid:1783d1cb-5b41-44d7-aa88-e907e8a86e2c","version":1,"metadata":{"timestamp":"2022-06-20T23:03:42+00:00","tools":[{"vendor":"aquasecurity","name":"trivy","version":"0.29.1"}],"component":{"bom-ref":"cccc26bd-3352-457e-8236-7abc568857a4","type":"application","name":".","properties":[{"name":"aquasecurity:trivy:SchemaVersion","value":"2"}]}},"components":null,"dependencies":[{"ref":"cccc26bd-3352-457e-8236-7abc568857a4"}],"vulnerabilities":[]}

## Output of run with `-debug`:
N/A
trivy sbom doesn't accpect -d

## Output of `trivy -v`:

N/A
trivy sbom doesn't accpect -v

**Comment by DmitriyLewen** [comment]
Hello @csharpknife2002 
Thanks for your report!

can you send your `requirements.txt` file or result of `trivy -d fs path/to/requirements.txt` command?
I need this to investigate your problem.

Regards, Dmitriy

**Comment by csharpknife2002** [comment]
Hello @DmitriyLewen,
Thanks for your suggestion. I did another look and then I realize in my requirements.txt I only had a 'flask" which is a Python built in library, after I add other dependency it works as expected. Sorry for this noise. I will close this issue.
