### ISSUE TITLE
After npm aduit fix, trivy still have the same vulnerabilities in html report

### ISSUE THREAD

**Issue by kamil1027** [aquasecurity/trivy#2367]
![image1](https://user-images.githubusercontent.com/77478122/174728141-dc6257c6-0803-4147-ad2a-d2a3413e8a26.png)
Using minimist 1.2.5

After npm aduit fix
![image2](https://user-images.githubusercontent.com/77478122/174728294-cbe48780-a5cf-4fc3-8e68-950ee6edae14.png)
Using minimist 1.2.6

![image3](https://user-images.githubusercontent.com/77478122/174728506-59aa318e-a368-4596-ac3f-6677f623a718.png)

In the report, it displays the 1.2.5 version of minimist.
In my opinion, if i use npm aduit fix, there should not display the minimist because it had already fixed by npm aduit fix

**Comment by DmitriyLewen** [comment]
Hello @kamil1027 
Thank for your report!

If i understand correctly `nmp audit fix` doesn't fix dependencies in `yarn.lock` files(https://stackoverflow.com/questions/51732435/is-there-a-yarn-alternative-for-npm-audit).

Your report contains vulnerabilities from `yarn.lock` file. Path to file you be found using `-format json` flag(`Target` field).
For example: 
```
➜  test trivy fs -f json . 
2022-06-27T12:23:00.547+0600	INFO	Vulnerability scanning is enabled
2022-06-27T12:23:00.547+0600	INFO	Secret scanning is enabled
2022-06-27T12:23:00.547+0600	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-06-27T12:23:00.547+0600	INFO	Please see also https://aquasecurity.github.io/trivy/v0.29.1/docs/secret/scanning/#recommendation for faster secret detection
2022-06-27T12:23:00.548+0600	INFO	Number of language-specific files: 1
2022-06-27T12:23:00.548+0600	INFO	Detecting yarn vulnerabilities...
{
  ...

  "Results": [
    {
      "Target": "test/yarn.lock",
      "Class": "lang-pkgs",
      "Type": "yarn",

  ...
```

Can you check your `yarn.lock` file?

Regards, Dmitriy

**Comment by kamil1027** [comment]
In yarn.lock file, some of dependencies have been upgraded to the safe version.
Dependency example: minimist

![image](https://user-images.githubusercontent.com/77478122/177080154-a70a3d9a-4441-42e2-905f-d9bdcfdb0b7c.png)

However, some dependencies have not upgrade. Jusk like
![image](https://user-images.githubusercontent.com/77478122/177080218-0bd426f0-9c23-472c-92ef-0d48a2a64d57.png)
![image](https://user-images.githubusercontent.com/77478122/177080265-513b1028-bf71-4340-a115-2ca52afb8754.png)

I think that this question should be caused by the dependency version. If i need to use the package with a outdate  and risk version, there is no any actions that i can do. The only action should be waiting for the package owner updating the package dependencies to a safe version.

That is my consideration about the question.
Sorry for late.

**Comment by DmitriyLewen** [comment]
I think you can try to convert `package-lock.json` file into `yarn.lock`: https://stackoverflow.com/a/60878037.
This may solve your problem.
