### ISSUE TITLE
Support authentication for --db-repository OCI registry

### ISSUE THREAD

**Issue by blacksails** [aquasecurity/trivy#2373]
We have a mirror of ghcr.io/aquasecurity/trivy-db our mirror requires authentication, but there doesnt seem to be any way to do authentication for the repository containing trivy-db.

```
➜ trivy image \
  --db-repository ourmirror.com/aquasecurity/trivy-db \
  someimage:latest
2022-06-21T15:52:16.580+0200    INFO    Need to update DB
2022-06-21T15:52:16.580+0200    INFO    DB Repository: ourmirror.com/aquasecurity/trivy-db
2022-06-21T15:52:16.580+0200    INFO    Downloading DB...
2022-06-21T15:52:16.743+0200    FATAL   init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: GET https://ourmirror.com/v2/token?scope=repository%3Aaquasecurity%2Ftrivy-db%3Apull&service=ourmirror.com: : Authentication is required
```

The above has been adapted replacing our actual mirror with ourmirror.com. It would be nice if we could provide OCI authentication details.

**Comment by knqyf263** [comment]
Please try `docker login`.

**Comment by blacksails** [comment]
> Please try `docker login`.

I am authenticated with docker

**Comment by knqyf263** [comment]
But it works in another place as I mentioned above. Could you write a small snippet to replicate it? If it works, it may be a Trivy issue.

**Comment by blacksails** [comment]
How does `TRIVY_USERNAME` and `TRIVY_PASSWORD` tie into this?

Do you only use the above authentication method for the database? 
eg. can I pull the database without the mirror and then scan an image on an authenticated registry without setting the `TRIVY_USERNAME` and `TRIVY_PASSWORD` variables?

**Comment by knqyf263** [comment]
`TRIVY_USERNAME` and `TRIVY_PASSWORD` are for pulling an image now, not the database.

**Comment by blacksails** [comment]
Is there any reason why it's not the same approach with regards to authentication?

**Comment by ThomasBertiere** [comment]
Hi, 

I face the same problem as @blacksails :

```
trivy image --db-repository  myrepo.com/aquasecurity/trivy-db --offline-scan myimage:tag

2022-06-22T13:22:29.641+0200	INFO	Need to update DB
2022-06-22T13:22:29.641+0200	INFO	DB Repository: myrepo.com/aquasecurity/trivy-db
2022-06-22T13:22:29.641+0200	INFO	Downloading DB...
2022-06-22T13:22:29.683+0200	FATAL	init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: GET https://myrepo.com/v2/token?scope=repository%3Arepository%2Faquasecurity%2Ftrivy-db%3Apull&service=myrepo.com: : Authentication is required
```

I'm well authenticated against `myrepo.com` as I can pull docker images from it. Moreover, I can pull the trivy-db via `oras` without any problem : 

```
oras pull myrepo.com/aquasecurity/trivy-db:2 -a

Downloaded 5affceed0f4b db.tar.gz
Pulled myrepo.com/aquasecurity/trivy-db:2
Digest: sha256:a41...
```

I'm running trivy v0.28.1 and docker 20.10.9 but in rootless mode. May the problem comes from the rootless mode ?

**Comment by sys-ops** [comment]
Hi Y'All,
Unfortunately, I started facing the same issue today. Yesterday everything was fine. I use private docker registry but the default 
OCI repository to retrieve trivy-db from "ghcr.io/aquasecurity/trivy-db".
```
2022-06-22T14:26:33.920+0200    INFO    Need to update DB
2022-06-22T14:26:33.920+0200    INFO    DB Repository: ghcr.io/aquasecurity/trivy-db
2022-06-22T14:26:33.920+0200    INFO    Downloading DB...
2022-06-22T14:26:35.099+0200    FATAL   DB error: failed to download vulnerability DB: database download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:650e60eb07987f7716e708acd0a6ec305018e134175bf09e6d9162e75cb9dc91: UNAUTHORIZED: unauthenticated: User cannot be authenticated with the token provided.
```
I did not upgrade trivy. I use version 0.25.4.
Why should I use TRIVY_USERNAME and TRIVY_PASSWORD?

**Comment by knqyf263** [comment]
@sys-ops Your issue is due to GitHub being down. Please refer https://github.com/aquasecurity/trivy/issues/2385.

**Comment by knqyf263** [comment]
@ThomasBertiere Thanks for updating. We don't use Docker Engine, but a credential. Rootless should not matter.

@afdesk Could you replicate it? Upload trivy-db to your private repository in GHCR, set up a credential and try `--db-repository`.

**Comment by afdesk** [comment]
yes... it works:
```
$ oras push ghcr.io/<MY GITHUB ACC>/trivy-db-private:2 db.tar.gz:application/vnd.aquasec.trivy.db.layer.v1.tar+gzip
```

**Comment by afdesk** [comment]
```sh
$ trivy i --db-repository ghcr.io/<MY GITHUB ACC>/trivy-db-private alpine:latest
2022-06-22T22:12:22.348+0600	INFO	Need to update DB
2022-06-22T22:12:22.348+0600	INFO	DB Repository: ghcr.io/<MY GITHUB ACC>/trivy-db-private
2022-06-22T22:12:22.348+0600	INFO	Downloading DB...
32.65 MiB / 32.65 MiB [-----------------------------------------------------------------------------------------------------] 100.00% 3.45 MiB p/s 9.7s
2022-06-22T22:12:33.743+0600	INFO	Vulnerability scanning is enabled

```

**Comment by afdesk** [comment]
I've removed my access token from GHCR and could get a similar error:
```sh
$ trivy i --db-repository ghcr.io/<MY GITHUB ACC>/trivy-db-private alpine:latest
2022-06-22T22:25:02.556+0600	INFO	Need to update DB
2022-06-22T22:25:02.556+0600	INFO	DB Repository: ghcr.io/<MY GITHUB ACC>/trivy-db-private
2022-06-22T22:25:02.557+0600	INFO	Downloading DB...
2022-06-22T22:25:03.180+0600	FATAL	init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: GET https://ghcr.io/token?scope=repository%3A<MY GITHUB ACC>%2Ftrivy-db-private%3Apull&service=ghcr.io: DENIED: denied

```

**Comment by afdesk** [comment]
I created a new token and login via docker. it also works for me:
```sh
$ export CR_PAT=ghp_NEW_TOKEN
$ echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
WARNING! Your password will be stored unencrypted in ________
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

$ trivy i --db-repository ghcr.io/<MY GITHUB ACC>/trivy-db-private alpine:latest
2022-06-22T22:34:56.905+0600	INFO	Need to update DB
2022-06-22T22:34:56.905+0600	INFO	DB Repository: ghcr.io/<MY GITHUB ACC>/trivy-db-private
2022-06-22T22:34:56.905+0600	INFO	Downloading DB...
32.65 MiB / 32.65 MiB [------------------------------------------------------------------------------------------------------] 100.00% 2.59 MiB p/s 13s
2022-06-22T22:35:11.370+0600	INFO	Vulnerability scanning is enabled

```

**Comment by afdesk** [comment]
I have no idea what else to try

**Comment by afdesk** [comment]
tested. it works correctly on macOS Monterey 12.1

**Comment by knqyf263** [comment]
@ThomasBertiere Thanks for confirming. I don't have an environment to test with JFrog Artifactory, but does `oras` work for example? It should work if JFrog Artifactory is a OCI registry.

**Comment by afdesk** [comment]
@ThomasBertiere is there anything strang in the JFrog logs?

**Comment by ThomasBertiere** [comment]
Ok I made a mistake... 😩 

My second repository (Harbor) was `Public` so no need of authentication. I change it to `Private` and trivy does not work. The error message is slightly different :

```
$ trivy image --db-repository mySecondRepo.com/aquasecurity/trivy-db --offline-scan myimage:tag
 
2022-06-23T14:28:04.908+0200	INFO	Need to update DB
2022-06-23T14:28:04.908+0200	INFO	DB Repository: mySecondRepo.com/aquasecurity/trivy
2022-06-23T14:28:04.908+0200	INFO	Downloading DB...
2022-06-23T14:28:05.001+0200	FATAL	init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: GET https://mySecondRepo.com/v2/aquasecurity/trivy/manifests/2: UNAUTHORIZED: unauthorized to access repository: aquasecurity/trivy, action: pull: unauthorized to access repository: aquasecurity/trivy, action: pull
```
But I can pull it via `oras` :
```
oras pull mySecondRepo.com/aquasecurity/trivy:2 -a

Downloaded fe21c8f4550b db.tar.gz
Pulled mySecondRepo.com/aquasecurity/trivy:2
Digest: sha256:bcd0f...
```

And I can pull docker images from mySecondRepo.com.

@afdesk unfortunately I do not have access to JFrog logs...

**Comment by afdesk** [comment]
@ThomasBertiere oh, thanks. will try again.

**Comment by afdesk** [comment]
@ThomasBertiere i got your issue.
I've downloaded `Trivy` 0.28.1 and it seems this version doesn't work correctly.

Could you test the latest Trivy? thanks!

**Comment by afdesk** [comment]
```sh
$ trivy-28-1 -v
Version: 0.28.1
$ trivy-28-1 i --db-repository ghcr.io/<MYACC>/trivy-db-private alpine:latest 
2022-06-23T18:59:57.250+0600	INFO	Need to update DB
2022-06-23T18:59:57.250+0600	INFO	DB Repository: ghcr.io/<MYACC>/trivy-db-private
2022-06-23T18:59:57.250+0600	INFO	Downloading DB...
2022-06-23T18:59:57.839+0600	FATAL	init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: GET https://ghcr.io/token?scope=repository%3A<MYACC>%2Ftrivy-db-private%3Apull&service=ghcr.io: UNAUTHORIZED: authentication required
```

**Comment by knqyf263** [comment]
@afdesk Oh, nice catch. I forgot to check the installed versions. It should be v0.29.0 or greater.

**Comment by afdesk** [comment]
@blacksails could you confirm too that this issue was fixed? thanks

**Comment by blacksails** [comment]
It works with v0.29.2 <3

**Comment by afdesk** [comment]
> It works with v0.29.2 <3

so can we close this issue?

**Comment by blacksails** [comment]
One thing which is a bit related to this is how to approach --db-repository authentication when using the docker image for running trivy. AFAIK it doesn't have docker or oras CLI's to provide the login functionality.

**Comment by afdesk** [comment]
> One thing which is a bit related to this is how to approach --db-repository authentication when using the docker image for running trivy. AFAIK it doesn't have docker or oras CLI's to provide the login functionality.
> 
> I guess one could construct the docker config.json manually without using docker login.

hm, it works for me:
```sh
$ docker run -it --rm --entrypoint /bin/sh -v /home/user/.docker/config.json:/root/.docker/config.json aquasec/trivy:0.29.2

/ # trivy -d i --db-repository ghcr.io/<MY ACC>/trivy-db-private alpine:latest
```

**Comment by afdesk** [comment]
it works too:
```sh
$ docker run -it --rm -v /home/user/.docker/config.json:/root/.docker/config.json aquasec/trivy:0.29.2 i --db-repository ghcr.io/<MY ACC>/trivy-db-private alpine:latest
```

**Comment by blacksails** [comment]
I guess this is resolved then 👍 Thanks for the help 🙏

**Comment by flngen** [comment]
this still doesn't work for a private registry that requires authentication, even with the latest version of trivy

**Comment by danf425** [comment]
@fingen That's exactly the behavior I'm seeing. 
I need to pull the trivy-db image from a private/on-prem artifactory repo but there's no way to authenticate for --db-repository. 

What's unfortunate is "trivy-db" and the image I intend to scan both exist in the same artifactory repo but TRIVY_USERNAME and TRIVY_PASSWORD can't be utilized for DB auth.

**Comment by afdesk** [comment]
@flngen @danf425 thanks for your reports!
could you give us more information about your cases?

**Comment by flngen** [comment]
@afdesk - I’m running trivy in an air-gapped environment. I’m building the OCI artifacts for trivy-db and pushing them with Oras to a private registry that requires authentication. Oras login and pull works fine, as others in similar situations have reported. I use trivy —db-repository my.private.reg/trivy-db option. If I turn the authentication off, the db is downloaded as expected, otherwise does not work. Docker login is not a factor at all here. If it were, then TRIVY_USERNAME and TRIVY_PASSWORD would work for pulling the oci artifacts. As others have pointed out, I have the trivy-db:2 in the same registry as some target container images. Trivy scans them fine, as it’s able to login to the registry with proper credentials. The problem is that the code for downloading trivy-db from a private registry assumes the registry does not require authentication and/or does not reuse creds used for image scanning.

**Comment by afdesk** [comment]
> @afdesk - I’m running trivy in an air-gapped environment. I’m building the OCI artifacts for trivy-db and pushing them with Oras to a private registry that requires authentication. Oras login and pull works fine, as others in similar situations have reported. I use trivy —db-repository my.private.reg/trivy-db option. If I turn the authentication off, the db is downloaded as expected, otherwise does not work. Docker login is not a factor at all here. If it were, then TRIVY_USERNAME and TRIVY_PASSWORD would work for pulling the oci artifacts. As others have pointed out, I have the trivy-db:2 in the same registry as some target container images. Trivy scans them fine, as it’s able to login to the registry with proper credentials. The problem is that the code for downloading trivy-db from a private registry assumes the registry does not require authentication and/or does not reuse creds used for image scanning.

thanks!

could you show logs?

also another question, do you pass a media type for pushing the OCI artifacts?
https://github.com/aquasecurity/trivy/issues/2373#issuecomment-1163321298

**Comment by knqyf263** [comment]
It is supported now

**Comment by admincasper** [comment]
@knqyf263 I try to run same test as mention in https://aquasecurity.github.io/trivy/v0.24.4/advanced/private-registries/acr/ for our private Azure Container Registry. 

I run the following commands: 
`oras pull ghcr.io/aquasecurity/trivy-db:2`

`oras push <myrepo>.azurecr.io/aquasec/trivy-db:2 db.tar.gz:application/vnd.aquasec.trivy.db.layer.v1.tar+gzip`

```
docker run --rm --name trivy-test -it \
-v /tmp:/tmp -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} \
-e AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} \
-e AZURE_TENANT_ID=${AZURE_TENANT_ID} \
aquasec/trivy:0.41.0 \
--username $AZURE_CLIENT_ID \
--password $AZURE_CLIENT_SECRET \
--download-db-only --db-repository <myrepo>.azurecr.io/aquasec/trivy-db
```

I've tried not using --username and --password also. 
I always get the following error: 
```
2023-05-30T11:40:17.447Z        INFO    Downloading DB...
2023-05-30T11:40:19.705Z        FATAL   init error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 3 errors occurred:
        * GET https://<myrepo>.azurecr.io/v2/aquasec/trivy-db/manifests/2: MANIFEST_UNKNOWN: OCI artifact found, but accept header does not support OCI artifacts
        * GET https://<myrepo>.azurecr.io/v2/aquasec/trivy-db/manifests/2: MANIFEST_UNKNOWN: OCI artifact found, but accept header does not support OCI artifacts
        * GET https://<myrepo>.azurecr.io/oauth2/token?scope=repository%3Aaquasec%2Ftrivy-db%3Apull&service=<myrepo>.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.
```
I've also tried pushing it to acr as explained here: 
https://github.com/aquasecurity/trivy/discussions/3497

Any help would be greatly appreciated!

**Comment by admincasper** [comment]
> @knqyf263 I can't get this to work for our private ACR repository.
> 
> I try to run same test as mention in https://aquasecurity.github.io/trivy/v0.24.4/advanced/private-registries/acr/ for our private Azure Container Registry. The credentials are of a Service Principal that has `Contributor` on the ACR. Which 

> Any help would be greatly appreciated!

There is definitely something wrong with how oras pulls or pushes the image to ACR!

I got it to work by running `oras cp` (preview) like this:
`oras cp ghcr.io/aquasecurity/trivy-db:2 <myrepo>.azurecr.io/aquasec/trivy-db:2`

After running the same command for testing: 
```
docker run --rm --name trivy-test -it \
-v /tmp:/tmp -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} \
-e AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} \
-e AZURE_TENANT_ID=${AZURE_TENANT_ID} \
aquasec/trivy:0.41.0 \
--username $AZURE_CLIENT_ID \
--password $AZURE_CLIENT_SECRET \
--download-db-only --db-repository <myrepo>.azurecr.io/aquasec/trivy-db
```
it worked!
```
2023-05-30T12:01:53.218Z        INFO    Downloading DB...
2023-05-30T12:01:53.219Z        DEBUG   no metadata file
37.38 MiB / 37.38 MiB [------------------------------------------------------------------------------------------] 100.00% 3.68 MiB p/s 10s
2023-05-30T12:02:05.609Z        DEBUG   Updating database metadata...
2023-05-30T12:02:05.611Z        DEBUG   DB Schema: 2, UpdatedAt: 2023-05-30 06:09:36.570726802 +0000 UTC, NextUpdate: 2023-05-30 12:09:36.570726402 +0000 UTC, DownloadedAt: 2023-05-30 12:02:05.610190551 +0000 UTC
```

**Comment by knqyf263** [comment]
FYI: https://github.com/aquasecurity/trivy-db/pull/305
