### ISSUE TITLE
The Aqua website certificate is expired

### ISSUE THREAD

**Issue by tspearconquest** [aquasecurity/trivy#2386]
Hello,

I'm writing to let you know that the TLS certificate for https://aquasec.com/ expired on June 20 and web browsers are showing an invalid certificate warning to all users who visit your website.

Please address this as soon as possible

Thank you.

**Comment by tspearconquest** [comment]
![image](https://user-images.githubusercontent.com/81998567/175046121-8f8dcd51-ce68-4f9e-9535-5d99608726ae.png)
![image](https://user-images.githubusercontent.com/81998567/175046152-f65c1839-e080-42fc-b851-b401dc16cc8f.png)

**Comment by knqyf263** [comment]
Thanks. I saw the same issue, but after I reloaded the page, the certificate seems to be valid. Cache issue maybe?
![image](https://user-images.githubusercontent.com/2253692/175056522-bf939ba6-4d1e-469e-b98c-ef1135e561c6.png)

**Comment by tspearconquest** [comment]
Looks that way, thanks for confirming!
