### ISSUE TITLE
avd links running trivy config are not valid (404)

### ISSUE THREAD

**Issue by webmutation** [aquasecurity/trivy#2387]
## Description

The avs links displayed inline are not pointing to valid URL returns 404

## What did you expect to happen?
links should send to correct page

examples: 
See https://avd.aquasec.com/misconfig/ds002 
See https://avd.aquasec.com/misconfig/ksv003

## What happened instead?
returns 404

should redirect to new URL or be fixed in output of the CLI
https://avd.aquasec.com/misconfig/dockerfile/general/avd-ds-0002/

## Output of `trivy -v`:

```
Tests: 22 (SUCCESSES: 21, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

HIGH: Specify at least 1 USER command in Dockerfile with non-root user as argument
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Running containers with 'root' user can lead to a container escape situation. It is a best practice to run containers as non-root users, which can be done by adding a 'USER' statement to the Dockerfile.

See https://avd.aquasec.com/misconfig/ds002
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

## Additional details (base image name, container registry info...):
v 0.29.2

**Comment by knqyf263** [comment]
Fixed it
