### ISSUE TITLE
Lightweight DB

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#241]
We're working on lightweight DB without vulnerability description, reference, etc. This DB contains only CVE-ID and severity. It's only 2MB. This DB is built periodically on CI.

Trivy downloads this DB on the first run and just use it. This improves the scan speed on the first run.

Before: ~10min
After: ~5sec

**Comment by hazcod** [comment]
@knqyf263 would this alleviate the 1.7GB database download needed when running?
Asking for https://github.com/aquasecurity/trivy/issues/233

**Comment by knqyf263** [comment]
@hazcod Yes, Trivy downloads only 2MB when running.
