### ISSUE TITLE
Add support for .Net core .deps.json files

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#2421]
## Description
.Net core generates a [appname].deps.json alongside the executable which contains the dependencies of that executable. Parsing it would provide information on dependencies for deployed .Net core executables. Support for parsing .deps.json was already added to go-dep-parser in https://github.com/aquasecurity/go-dep-parser/pull/103. Also, there is a WIP PR https://github.com/aquasecurity/fanal/pull/550. @astevenson-microsoft doesn't seem to be available now. If someone wants to take it over, it would be great.

- As we archived fanal, we need the similar PR in Trivy instead.
- Other implementations like https://github.com/aquasecurity/trivy/pull/2414 will be helpful.

## Issues
- https://github.com/aquasecurity/fanal/issues/549
- https://github.com/aquasecurity/go-dep-parser/issues/102

**Comment by usjpaq** [comment]
Is there a config option to turn this feature off?

**Comment by knqyf263** [comment]
`--vuln-type os` scans only OS packages.
