### ISSUE TITLE
Error: FATAL	unable to initialize a image struct:

### ISSUE THREAD

**Issue by sjgupta19** [aquasecurity/trivy#2432]
Hi, 
I am using trivy scanner via azure/container-scan github action and running into the following error(screenshot attached). It was running file till yesterday. Below are the configs that I am using - 
<img width="274" alt="image" src="https://user-images.githubusercontent.com/105396748/176753221-7599a45c-e033-4dd7-a02f-2fa6c3632f67.png">

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/105396748/176752897-badc6fc5-8eb4-42cf-88ec-2ed93db8b08e.png">

**Comment by sjgupta19** [comment]
thanks that worked. it was working yesterday, why this broke all of a sudden? dont see any changes pushed to dockle repo.

**Comment by arman1371** [comment]
Maybe change in GitHub runners (update)

**Comment by knqyf263** [comment]
Thanks for your help, @arman1371!
