### ISSUE TITLE
Dependency graph in CycloneDX and GitHub Dependency Graph

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#2451]
## Description
After https://github.com/aquasecurity/trivy/pull/1970, Trivy currently has a dependency graph for Node.js. It should be reflected to CycloneDX and GitHub Dependency Graph as well.

## References
- https://cyclonedx.org/use-cases/#dependency-graph
- https://docs.github.com/en/rest/dependency-graph/dependency-submission

**Comment by knqyf263** [comment]
Now, we also have dependency graphs for Rust, apt, deb and apk.
https://github.com/aquasecurity/trivy/pull/3093
https://github.com/aquasecurity/trivy/pull/3094

**Comment by afdesk** [comment]
ok, i'll take a look at this task

**Comment by knqyf263** [comment]
Added in https://github.com/aquasecurity/trivy/pull/3177
