### ISSUE TITLE
Client/Server setup, mainly done for multiple images scan at a time. Is not working when I have many server nodes.

### ISSUE THREAD

**Issue by AJJJAIAH** [aquasecurity/trivy#2471]
## Description
I have 2 CIs(Jenkins & Bamboo), currently my setup is on Trivy version v0.28.1.
Installation is done via Curl script both on client & server.

The client installed on NFS share and Trivy server on local FS (so that cache is specific to node).
I have set up an HTTPd load balancer at Trivy server, currently, it is 3 nodes (Trivy servers).

Now, when I call the image scan from my client to server as below.
/trivy_clien/trivy -d image --server http://trivyserver.dev.xxx.com artifactory.dev.xxxx.com/docker/myImage:21.2

## What did you expect to happen?
My HTTPd load balancer has to assign the traffic to one of my Trivy server node for the scan run and retrieve & cache all the missing layers and generate the report in the table format.

## What happened instead?

I get this error.
---------------------------
2022-07-06T12:16:13.087Z        FATAL   image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:322
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*Runner).Scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:182
  - image scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:464
  - scan failed:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:122
  - failed to detect vulnerabilities via RPC:
    github.com/aquasecurity/trivy/pkg/rpc/client.Scanner.Scan
        /home/runner/work/trivy/trivy/pkg/rpc/client/client.go:83
  - twirp error internal: failed scan, artifactory.dev.xxxx.com/docker/myImage:21.2: failed to apply layers: layer cache missing: sha256:7b8acb0282288c03de468c0c3e349b0899633f7a18f
--------------------------

## Output of run with `-debug`:

```
2022-07-06T12:16:13.087Z        FATAL   image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:322
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*Runner).Scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:182
  - image scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:464
  - scan failed:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:122
  - failed to detect vulnerabilities via RPC:
    github.com/aquasecurity/trivy/pkg/rpc/client.Scanner.Scan
        /home/runner/work/trivy/trivy/pkg/rpc/client/client.go:83
  - twirp error internal: failed scan, artifactory.dev.xxxx.com/docker/myImage:21.2: failed to apply layers: layer cache missing: sha256:7b8acb0282288c03de468c0c3e349b0899633f7a18f
```

## Output of `trivy -v`:

```
Version: 0.28.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-06-29 12:08:01.631805324 +0000 UTC
  NextUpdate: 2022-06-29 18:08:01.631805023 +0000 UTC
  DownloadedAt: 2022-06-29 13:41:42.781647535 +0000 UTC
```

## Additional details (base image name, container registry info...):

My observations:

When the scan happens, it tries to hit the Trivy server, with my load balancer, it assigns most of the time different nodes for each missing layer.
This is one of the image scan logs captured in the load balancer.

First layer cache request has gone to -->  Trivy server node1
Next Layer gone to --> Trivy server node2
Next one -> Trivy server node3
Now the Scan runs on --> Trivy server node1 ( This would be missing the second & third layer)
======================
10.XXX.XXX.XXX - - [24/Jun/2022:11:32:49 +0000] "POST /twirp/trivy.cache.v1.Cache/MissingBlobs HTTP/1.1" 200 146 "-" "Go-http-client/1.1" "1" http://trivyservernode1.dev.xxx.com:4954/
10.XXX.XXX.XXX- - [24/Jun/2022:11:32:49 +0000] "POST /twirp/trivy.cache.v1.Cache/PutBlob HTTP/1.1" 200 - "-" "Go-http-client/1.1" "2" http://trivyservernode2.dev.xxx.com:4954/
10.XXX.XXX.XXX- - [24/Jun/2022:11:32:49 +0000] "POST /twirp/trivy.cache.v1.Cache/PutBlob HTTP/1.1" 200 - "-" "Go-http-client/1.1" "3" http://trivyservernode3.dev.xxx.com:4954/
10.XXX.XXX.XXX - - [24/Jun/2022:11:32:49 +0000] "POST /twirp/trivy.scanner.v1.Scanner/Scan HTTP/1.1" 500 255 "-" "Go-http-client/1.1" "1" http://trivyservernode1.dev.xxx.com:4954/
======================

**Comment by AJJJAIAH** [comment]
This setup works if I have only one Trivy Server node behind my HTTPd load balancer, it won't work if I add more Trivy servers.

**Comment by AJJJAIAH** [comment]
I am suspecting some Sticky session issue here, would be great if anyone points me to those details and how to make it work.

**Comment by knqyf263** [comment]
@AJJJAIAH If you want to run multiple Trivy servers, you need to use Redis as the cache backend so that those servers can share the cache.
https://aquasecurity.github.io/trivy/v0.29.2/docs/vulnerability/examples/cache/#cache-backend

@DmitriyLewen Can we add it to troubleshooting?
https://aquasecurity.github.io/trivy/v0.29.2/docs/references/troubleshooting/

**Comment by AJJJAIAH** [comment]
@knqyf263 
Do you mean to say, having one Redis instance or cache for all my Trivy server nodes?

example: Trivy server node 1, Trivy server node 2, Trivy server node 3, etc till Nth Trivy server will have only one Redis cache server? is that what you mean?

As I have both Jenkins & Bamboo CIs I expect at least 25-30 multiple-image scans to take place at the same time because I will have a minimum of 450+ jobs running during release, the possibility of those running at the same time is quite possible & I have no hardware restriction to increase my Trivy server nodes to 30-40 in soon. Maybe I will go for the k8s cluster for server setup.

I would need a way or the setup that can make scalling options or multiple scan at a time easy and depedable.

Don't we have a Sticky session or Loadbalance setup guide for Trivy yet? if yes, please share that info, which will help us a lot at the moment.

thanks.

**Comment by AJJJAIAH** [comment]
Any updates? I brought up one Redis in one of the Trivy Server nodes (out of 3) and used the same Redis in all nodes. My Trivy servers are behind the load balancer. I am getting 502 & connection errors.

**Comment by AJJJAIAH** [comment]
Thanks, I got it to work. The missing piece was, that I have to use the local cache for the servers along with Redis.
