### ISSUE TITLE
Error in the format of sbom(purl) when I scan the golang image

### ISSUE THREAD

**Issue by tonyupup** [aquasecurity/trivy#2474]
## Description
Error in the format of SBOM when I scan the golang image。

## What did you expect to happen?
like standard purl format. ex: "purl": "pkg:golang/go.opencensus.io/go.opencensus.io@v0.23.0"
## What happened instead?
SBOM purl format not have namespace or name 

"purl": "pkg:golang/go.opencensus.io@v0.23.0",

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
Version: c537c91
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-07-07 00:11:57.851494902 +0000 UTC
  NextUpdate: 2022-07-07 06:11:57.851494602 +0000 UTC
  DownloadedAt: 2022-07-07 05:32:16.086895 +0000 UTC
```

**Comment by masahiro331** [comment]
@tonyupup 
https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#golang

From the examples in the purl-types specification, it appears that libraries such as `github.com/masahiro331/somemodule` have a namespace.

The output of cyclonedx-gomod, which is officially distributed by cyclonedx, also seems to output `pkg:golang/go.opencensus.io@v0.23.0`. 

go.mod
```
module github.com/masahiro331/go-playground

go 1.18

require github.com/package-url/packageurl-go v0.1.0

require go.opencensus.io v0.23.0 // indirect
```

cyclonedx-gomod 
```
$ mkdir project  && cd project
$ vim go.mod 
$ go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest
$ cyclonedx-gomod | grep opencensus
    <component bom-ref="pkg:golang/go.opencensus.io@v0.23.0" type="library">
```

**Comment by knqyf263** [comment]
Please feel free to reopen it if you have any other questions.
