### ISSUE TITLE
AWS scanning

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/trivy#2476]
Add a new target to trivy that scans an AWS account. By connecting to the AWS API, discovering relevant resources, and scanning them with current scanners. For starts we will scan for misconfigurations only.
the UX flow should be similar to Kubernetes scanning: start by a broad scan, and show summary only. then user can drill into resources to detailed findings.

Things to consider:
- how to consistently specify an AWS resource (id/name/arn)
- local caching of resources. to allow a responsive experience while "navigating" within an account

**Comment by owenrumney** [comment]
https://github.com/aquasecurity/defsec/issues/763
