### ISSUE TITLE
trivy fs --security-checks secret can't find the hardcoded bearer token in the code.

### ISSUE THREAD

**Issue by clin4** [aquasecurity/trivy#2501]
I have a piece of typescript code, which contains a bearer token. I am hoping I can use the trivy fs --security-check secret options to find this kind of issue from the code base, but it doesn't.  Is this the expected behavior or I used the wrong options?

I am using trivy 0.29.1

The scan result
=================
trivy fs --security-checks secret  -f json .
2022-07-12T21:38:42.049Z        INFO    Secret scanning is enabled

2022-07-12T21:38:42.049Z        INFO    If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-12T21:38:42.049Z        INFO    Please see also https://aquasecurity.github.io/trivy/v0.29.1/docs/secret/scanning/#recommendation for faster secret detection
{
  "SchemaVersion": 2,
  "ArtifactName": ".",
  "ArtifactType": "filesystem",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  }
}

The file content
================== 
`
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  use: {
    baseURL: 'https://xxx.com',
    extraHTTPHeaders: {
      'Authorization': `Bearer eyxxx`,
    }
  },
  timeout: 180 * 1000,
  reporter: [['list'], ['junit', { outputFile: 'results/xml/junitresults.xml' }]],
};
`

**Comment by DmitriyLewen** [comment]
Hello @clin4 
Thanks for your interest to Trivy!

We don't  currently have pattern for correctly defining Bearer tokens. 
If you know a way to detect Bearer, please let us know and we will add it!

About your case:
I think, you can use [custom rule](https://aquasecurity.github.io/trivy/v0.29.2/docs/secret/configuration/).
I created small example for your file:
``` yaml
rules:
  - id: rule1
    category: general
    title: Generic Rule
    severity: HIGH
    path: .*
    keywords:
      - Bearer
    regex: 'Bearer (?P<secret>[0-9a-zA-Z\-_=]*)'
    secret-group-name: secret
```
Trivy result:
```
  "Results": [
    {
      "Target": "file.json",
      "Class": "secret",
      "Secrets": [
        {
          "RuleID": "rule1",
          "Category": "general",
          "Severity": "HIGH",
          "Title": "Generic Rule",
          "StartLine": 8,
          "EndLine": 8,
          "Match": "'Authorization': Bearer *****,"
        }
      ]

```

Best Regards, Dmitriy

**Comment by clin4** [comment]
Hi Dmitriy,
Thank you for the quick and valuable response. It really helps.
