### ISSUE TITLE
SBOM attestation

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#2506]
Our documentation should describe how to sign and attach our SBOM.

According to [the cosign doc](https://github.com/sigstore/cosign/blob/6eeb3cf5864edf34d87084c3f942d4a9a36a54ce/doc/cosign_attest.md), it would be like below.

```
$ trivy image --format cyclonedx -o cyclonedx.json IMAGE
$ cosign attest --key cosign.key --type cyclonedx --predicate cyclonedx.json IMAGE
```

**Comment by knqyf263** [comment]
@otms61 Could you work on it?

**Comment by otms61** [comment]
@knqyf263 Alright. I will try.
