### ISSUE TITLE
Improve the scan speed on a first run

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#251]
Currently, Trivy uses [vuln-list](https://github.com/aquasecurity/vuln-list] as a vulnerability source. After pulling it, the vulnerability database is built on the local machine. It takes a while on a first run. On a second run, it will be faster since Trivy fetches only differences through git.

Trivy will fetch the pre-built database file from GitHub and just use it with the next version. The database file is built in advance on a server (maybe GitHub Actions cron). It dramatically improves the scan speed on a first run.

Here is a prototype:
  Current version: ~10m
  Next version: ~5s

![light-db](https://user-images.githubusercontent.com/2253692/67982475-6d5b3d00-fc2b-11e9-954d-b8604ad24f2f.gif)

`--only-update`, `--refresh` and `--auto-refresh` will be deprecated.

**Comment by FernandoMiguel** [comment]
It's probably a good idea to check with github if they are OK with pushing out gigabytes of blobs.
They could suspend your account

**Comment by knqyf263** [comment]
@FernandoMiguel I thought the same thing. I've been trying to reduce the DB size. Now, in my branch, the DB size is ~7MB. I think it is fine.

**Comment by FernandoMiguel** [comment]
That should be fine.
Most repo clone or checkouts are bigger than that 
I can easily checkout over a gigabyte
