### ISSUE TITLE
Whether the Apk Analyzer needs to manually close the file after reading it

### ISSUE THREAD

**Issue by ghost** [aquasecurity/trivy#2514]
https://github.com/aquasecurity/trivy/blob/931afd7f26f941b34990b02f22ec15c2188590fa/pkg/fanal/analyzer/command/apk/apk.go#L89

whether need to close file handles manually?

**Comment by knqyf263** [comment]
Looks like yes

**Comment by za** [comment]
Hi @knqyf263 any hint how to close this issue? Thanks.

**Comment by thebigbone** [comment]
> Hi @knqyf263 any hint how to close this issue? Thanks.

 This should work: `defer reader.(*os.File).Close()`

**Comment by knqyf263** [comment]
Already fixed
https://github.com/aquasecurity/trivy/blob/eca51500c3534d9ca5bb14f60dc15c7908254487/pkg/fanal/analyzer/imgconf/apk/apk.go#L106
