### ISSUE TITLE
Specify kubeconfig file path for "trivy k8s" command

### ISSUE THREAD

**Issue by pcgeek86** [aquasecurity/trivy#2522]
### Description

When you run the `trivy k8s` command, there is no option to specify an alternative `kubeconfig` file path. 
By default, the kubeconfig file resides in `$HOME/.kube/config`. 
However, users of Kubernetes often need to specify a different path, using a parameter like `--kubeconfig` on the `kubectl` command.

If you don't have the kubeconfig in the default filesystem path, then the error below is received.

```
root@trivy:~# trivy k8s --report summary cluster
2022-07-15T08:25:43.301Z        FATAL   get k8s artifacts error: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```

### Solution

Please add `--kubeconfig` as an argument / parameter for the `trivy k8s` command.

**Comment by mgsh** [comment]
i would like help if work hasn't been started on this issue yet. can i take a shot at it?

**Comment by josedonizetti** [comment]
@mgsh Sorry for the delay, was out. Would love to review a PR for it! Still interested in taking it?

**Comment by mgsh** [comment]
Yes @josedonizetti, I'm still interested. I can share a PR by later today. Thanks!

**Comment by mgsh** [comment]
Hi @josedonizetti , I've created PRs on trivy-kubernetes and trivy repos.

I wasn't sure how dependency version gets updated in go.mod in the trivy repo (for now I've just added a TODO in go.mod for the version to be updated once trivy-kubernetes PR gets merged).

Given the change is minor, I'm also not sure about if testing needs to be added. I've done local tests, but it's presently not automated.
