### ISSUE TITLE
Trivy HTML Report Jenkins pipeline

### ISSUE THREAD

**Issue by ngk512** [aquasecurity/trivy#2545]
Hi,

Integrated trivy with jenkins pipeline. while running pipeline getting below error 

unable to write results:
    github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:88
  failed to initialize template writer:
    github.com/aquasecurity/trivy/pkg/report.Write
        /home/runner/work/trivy/trivy/pkg/report/writer.go:120
  error retrieving template from path:
    github.com/aquasecurity/trivy/pkg/report.NewTemplateWriter
        /home/runner/work/trivy/trivy/pkg/report/template.go:35
  open contrib/html.tpl: no such file or directory
   

Please help.

## What did you expect to happen?

Trivy vulnerabilities to generate report in html format.

**Comment by afdesk** [comment]
it seems `trivy` can't find a html template.
is there `contrib/html.tpl` file?
https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl

**Comment by ngk512** [comment]
Yes, its there.

![image](https://user-images.githubusercontent.com/47627540/179798108-e5668e13-a067-48fb-bf80-ccd4c905efd7.png)

Now i'm able to run and its generating report.html file but when i opened it shows as below and not getting any output.

![image](https://user-images.githubusercontent.com/47627540/179798510-8ef6f87d-1db1-4bc4-942a-4e0066f27d28.png)

Please help.

**Comment by afdesk** [comment]
> Yes, its there.
> 
> ![image](https://user-images.githubusercontent.com/47627540/179798108-e5668e13-a067-48fb-bf80-ccd4c905efd7.png)
> 
> Now i'm able to run and its generating report.html file but when i opened it shows as below and not getting any output.
> 
> ![image](https://user-images.githubusercontent.com/47627540/179798510-8ef6f87d-1db1-4bc4-942a-4e0066f27d28.png)
> 
> Please help.

could you set up a path to `html.tpl`:
```sh
$ trivy image --format template --template "@/usr/local/bin/trivy-main/contrib/html.tpl" -o report.html alpine:latest
```

**Comment by ngk512** [comment]
Now i'm getting the below error:

Vulnerability scanning is enabled
2022-07-20T12:17:07.384+0530	[34mINFO[0m	Secret scanning is enabled
2022-07-20T12:17:07.384+0530	[34mINFO[0m	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-20T12:17:07.384+0530	[34mINFO[0m	Please see also https://aquasecurity.github.io/trivy/0.30.0/docs/secret/scanning/#recommendation for faster secret detection
2022-07-20T12:22:07.364+0530	[33mWARN[0m	Increase --timeout value
2022-07-20T12:22:07.364+0530	[31mFATAL[0m	image scan error: scan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded

**Comment by afdesk** [comment]
oh, it looks like you use Windows, right?

**Comment by ngk512** [comment]
No, i installed trivy in centos 7 i.e., where we installed Jenkins also in same server. We added the stage in Jenkins pipeline and While running the Jenkins build i'm getting error.

**Comment by ngk512** [comment]
No, i installed trivy in centos 7 i.e., where we installed Jenkins also in same server. We added the stage in Jenkins pipeline and While running the Jenkins build i'm getting error.

**Comment by afdesk** [comment]
@ngk512 please, check the path to `html.tpl` in `trivy` command

**Comment by ngk512** [comment]
It was issue with the image. Now its working fine.

Thanks for help!

**Comment by ngk512** [comment]
How to run trivy scan for local images in windows?

**Comment by ngk512** [comment]
How to run trivy scan for local images in windows?

**Comment by afdesk** [comment]
@ngk512 you can try to run `trivy` image for it.
```sh
docker run --rm aquasec/trivy:0.30.2 image alpine:latest
```

**Comment by ngk512** [comment]
Thank You and it worked!

**Comment by ngk512** [comment]
Can we use trivy to scan the installed application as a service instead of images?

for example: I installed application openfire in centos server and i want to scan using the trivy.

**Comment by ngk512** [comment]
@afdesk I have installed some applications like MySQL, MongoDB Compass, Python etc. I want to scan these applications using trivy. How can i do that?

**Comment by afdesk** [comment]
Trivy scans [Container Images](https://aquasecurity.github.io/trivy/v0.30.2/docs/vulnerability/scanning/image/), [Rootfs](https://aquasecurity.github.io/trivy/v0.30.2/docs/vulnerability/scanning/rootfs/), [Filesystem](https://aquasecurity.github.io/trivy/v0.30.2/docs/vulnerability/scanning/filesystem/), and [Git Repositories](https://aquasecurity.github.io/trivy/v0.30.2/docs/vulnerability/scanning/git-repository/)

**Comment by ngk512** [comment]
Thanks for Help!
