### ISSUE TITLE
Skip vuln scan mode for SBOM generation

### ISSUE THREAD

**Issue by robertlagrant** [aquasecurity/trivy#2557]
It would be great to have a mode for Trivy where it can simply generate an SBOM and quit, without having to download a database or do its own analysis.

My use case is running in CI to generate an SBOM (where I'd like the scan to be as fast as possible, so no vuln database download time and no time processing) and then push it to OWASP Dependency Track, which will do the vuln and licence assessments.

**Comment by knqyf263** [comment]
We already made the change in https://github.com/aquasecurity/trivy/pull/2541. It will be released in v0.31.0.

**Comment by lsauer** [comment]
Great. I was about to request the same. Same scenario. That would be really useful for many corporate CI flows

**Comment by knqyf263** [comment]
There is the `--offline-scan` flag.
https://aquasecurity.github.io/trivy/v0.30.4/docs/references/troubleshooting/#maven-rate-limiting-inconsistent-jar-vulnerability-reporting

**Comment by knqyf263** [comment]
Merged #2541. It will be included in v0.31.0.

**Comment by robertlagrant** [comment]
Hmm - I'm not sure if this is exactly what this issue was describing. It looks as though trivy, even with `--skip-update` still wants to download the vulnerability database on first run:
```bash
% trivy fs --skip-update --format cyclonedx --output result.json .
2022-08-01T10:10:48.665+0100	ERROR	The first run cannot skip downloading DB
2022-08-01T10:10:48.665+0100	FATAL	init error: DB error: database error: --skip-update cannot 
be specified on the first run
```

And the new option doesn't disable the database download either - from the linked page:
```
The first is to enable offline scanning using the --offline-scan option to stop Trivy from making API 
requests. This option affects only vulnerability scanning. The vulnerability database and builtin policies 
are downloaded as usual.
```

So it looks from all that that it's not going to be possible to use Trivy as an SBOM scanner directly in a CI runner, as it will want to download the vulnerability DB before it runs. Is it possible to keep this issue open on that basis?

**Comment by knqyf263** [comment]
Did you try the main branch?

**Comment by lsauer** [comment]
I  ended up tranferring the cache with the directory from an online environment to the air-gapped environment and mounting The Cache as described in the examples.
It wasn't that straightforward with due to relative paths and permissions as trivy is run from within a container.

**Comment by robertlagrant** [comment]
@knqyf263 I didn't, but I have now, I think! I cloned the repo and ran `make build`. Result:

```bash
% make build
go build -ldflags "-s -w -X=main.version=v0.30.4-13-g55825d76" ./cmd/trivy
go: downloading github.com/aquasecurity/go-dep-parser v0.0.0-20220626060741-179d0b167e5f
go: downloading go.uber.org/zap v1.21.0
<!snip!>
go: downloading modernc.org/mathutil v1.4.1
go: downloading modernc.org/memory v1.1.1
go: downloading github.com/remyoudompheng/bigfft v0.0.0-20200410134404-eec4a21b6bb0
% ./trivy --version
Version: v0.30.4-13-g55825d76
% ./trivy fs --skip-update ../electron_test
2022-08-01T14:54:56.513+0100	ERROR	The first run cannot skip downloading DB
2022-08-01T14:54:56.513+0100	FATAL	init error: DB error: database error: --skip-update 
                                        cannot be specified on the first run
```

Here's why I think it's still running: https://github.com/aquasecurity/trivy/blob/main/pkg/db/db.go#L91-L96

**Comment by knqyf263** [comment]
You're missing `--format cyclonedx`.

**Comment by robertlagrant** [comment]
Erm, _yes!_ That works perfectly! Thanks.
