### ISSUE TITLE
ENV vars broken

### ISSUE THREAD

**Issue by tipruzs** [aquasecurity/trivy#2559]
## Description

Env vars are no longer working as expected.

## What did you expect to happen?

Setting cache-dir using env var TRIVY_CACHE_DIR

## What happened instead?

Setting cache-dir using env var TRIVY_CACHE_DIR has no effect

## Output of run with `-debug`:

```
docker run -it --rm -e TRIVY_CACHE_DIR="/.trivycache" ghcr.io/aquasecurity/trivy:0.30.0 --debug image alpine:3.16
2022-07-21T08:31:35.917Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-07-21T08:31:35.923Z	DEBUG	cache dir:  /.trivycache
```
```
docker run -it --rm -e TRIVY_CACHE_DIR="/.trivycache" ghcr.io/aquasecurity/trivy:0.30.1 --debug image alpine:3.16
2022-07-21T08:31:57.259Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-07-21T08:31:57.274Z	DEBUG	cache dir:  /root/.cache/trivy
```

**Comment by mikaello** [comment]
I see the same (I duplicated your issue https://github.com/aquasecurity/trivy/issues/2560). The removal of env auto bind in https://github.com/aquasecurity/trivy/pull/2526 seems to me as a possible source for this regression.

**Comment by jeffqumata** [comment]
Yep, seeing the same with the `TRIVY_IGNORE_UNFIXED` env var being ignored, breaking a bunch of builds. Rolling back to 0.30.0 works as expected

**Comment by DmitriyLewen** [comment]
Hello @tipruzs , @mikaello , @jeffqumata 
Thanks a lot for your reports!

We are working on a fix for this bug.

Regards, Dmitriy

**Comment by jeffqumata** [comment]
thanks @DmitriyLewen, is this planned for release today?

**Comment by mikaello** [comment]
> thanks @DmitriyLewen, is this planned for release today?

It was released a minute after your comment : https://github.com/aquasecurity/trivy/releases/tag/v0.30.2
