### ISSUE TITLE
FATAL   unable to write results: failed to initialize template writer: error parsing template: template: output template:61: function "sourceID" not defined

### ISSUE THREAD

**Issue by tanmoyrsc** [aquasecurity/trivy#2568]
## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
(paste your output here)
```

**Comment by tanmoyrsc** [comment]
I am running "**trivy image --format template --template "@contrib/asff.tpl" -o report.asff auth:latest**" command and getting the error " unable to write results: failed to initialize template writer: error parsing template: template: output template:61: function "sourceID" not defined"

**Comment by DmitriyLewen** [comment]
Hello @tanmoyrsc 
Thanks for your report!

It looks like you are using old Trivy with a new template.
We [added](https://github.com/aquasecurity/trivy/pull/1644) `sourseID` function in Trivy v0.23.0.

Can you tell me what version of Trivy are you using?

Regards, Dmitriy

**Comment by tanmoyrsc** [comment]
Hi Dimitriy,

now after using 0.23 the error has gone but facing below error when uploading result.asff to aws security hub. can you please help on that. I have also attached report.asff herewith.

_$ aws securityhub batch-import-findings --findings file://report.asff

Error parsing parameter '--findings': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
JSON received: {_

Regards,
Tanmoy
[report.zip](https://github.com/aquasecurity/trivy/files/9169500/report.zip)

**Comment by DmitriyLewen** [comment]
Hello @tanmoyrsc 

I checked your report. Trivy correctly created this file([BatchImportFindings format](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchImportFindings.html#API_BatchImportFindings_RequestSyntax)).

If i understand correctly - for `securityhub batch-import-findings` command you need to use only elements of `Findings` array.
Read more about the format of this command [here](https://docs.aws.amazon.com/securityhub/latest/userguide/finding-update-batchimportfindings.html#batchimportfindings-command-line).

**Comment by afdesk** [comment]
it looks like a known problem with ASFF: #1898 
@tanmoyrsc you can use next workaround:
```sh
$ cat report.asff | jq '.Findings'
```

**Comment by tanmoyrsc** [comment]
@DmitriyLewen , @afdesk ,

Thanks for your help now I can successfully able to push the report to securityhub. but facing this new issue, "**FATAL   flag provided but not defined: -no-progress**" the -no-progress option is not working with 0.23.0 version. could you please let me know the new option to failed the build if vulnerability is HIGH or CRITICAL ?

Thanks & Regards,
Tanmoy

**Comment by tanmoyrsc** [comment]
Sorry I got the reason for error, I missed the **image** argument after the **trivy** command.

**Comment by afdesk** [comment]
@tanmoyrsc can we close this issue?

**Comment by tanmoyrsc** [comment]
> @tanmoyrsc can we close this issue?

yes please, thanks a lot for your help on time.

**Comment by DmitriyLewen** [comment]
Hello @SanthoshAspire 

> I have set 777 permission for the contrib folder 

What about permissions for `html.tpl` file?
Does it also have 777 resolution?

**Comment by SanthoshAspire** [comment]
@DmitriyLewen , ya i have set the  same permission for the html.tpl file also.

![image](https://user-images.githubusercontent.com/80687968/234531720-15b25782-a8d8-400d-b561-26b6db704375.png)

**Comment by DmitriyLewen** [comment]
hm... it is weird...
Maybe problem is in user and group for `ec2-user` folder.

Your `ec2-user` folder doesn't have `read` permission for group and other users.(`drwx------`).

Can you try to use `ec2-user`?
