### ISSUE TITLE
Is there any plan to release Trivy's plugin for Jenkins?

### ISSUE THREAD

**Issue by kiewza** [aquasecurity/trivy#257]
It would be nice if we can see the scan report there in the build result other than the terminal

**Comment by raghureddycloud** [comment]
It would be great to see Trivy's plugin for Jenkins.

**Comment by mammademachine** [comment]
@kiewza I hope this answer your question
https://github.com/jenkinsci/aqua-security-scanner-plugin/blob/master/version.md

**Comment by kiewza** [comment]
@m

> @kiewza I hope this answer your question
> https://github.com/jenkinsci/aqua-security-scanner-plugin/blob/master/version.md

**Comment by kiewza** [comment]
> @kiewza I hope this answer your question
> https://github.com/jenkinsci/aqua-security-scanner-plugin/blob/master/version.md

Thanks for your answer but this can work well with Trivy, right?

**Comment by Alexc0007** [comment]
i also support adding a trivy plugin to jenkins...
the post above about aqua security scanner doesnt talk about trivy...

many pipelines run on Jenkins and uses an alpine image(because of its size), and its impossible to install trivy on alpine...
so a jenkins plugin will be awesome!

**Comment by almahaja** [comment]
Hello,
Just wondering if there's any latest update on this?

Thanks

**Comment by Asgoret** [comment]
Any information?

**Comment by knqyf263** [comment]
We don't have a plan to release a Jenkins plugin for Trivy. But it sounds like a nice idea. We really welcome your contribution. You can publish a new plugin following the official guides.
https://www.jenkins.io/doc/developer/publishing/#how-to-guides

**Comment by Hokwang** [comment]
@knqyf263 I read the article about retiring microscanner and trivy will have microscanner's experience. when is the target date?
and now microscanner has jenkins plugin, how about update it for trivy? I think you already have a plan like this.

**Comment by wwuck** [comment]
https://github.com/jenkinsci/warnings-ng-plugin/blob/master/SUPPORTED-FORMATS.md

`warnings-ng` plugin now supports trivy.  Run trivy with json output format to capture from warnings-ng.

**Comment by krol3** [comment]
@wwuck  we have a PR to add a sample using warnings-ng. https://github.com/aquasecurity/trivy/pull/1266

**Comment by AutomatonRob** [comment]
> the post above about aqua security scanner doesnt talk about trivy...

Personally I try to avoid Jenkins plugins wherever I can (as our Jenkins is cluttered already and maintenance is really annoying). I don't know if this would make your life easier but I use an alpine image as base and copy trivy over. A little bit of maintenance to update it every once in a while but works like a charm. :) 
The Dockerfile looks something like this:
```
FROM trivy:0.24.4 as trivy
FROM alpine:3.15

COPY --from=trivy /usr/local/bin/trivy /usr/local/bin/trivy

RUN ...
```
