### ISSUE TITLE
Allow users to restrict the number of times `trivy` attempts to connect to Maven on JAR scans

### ISSUE THREAD

**Issue by trevor-vaughan** [aquasecurity/trivy#2571]
When using a local Maven mirror, generally the system is either available or it's not.

Presently, for each JAR found, `trivy` attempts a large number of retries.

Users should be able to set something like `MAVEN_CENTRAL_TRIES` to limit the number of retries to a sensible number (like 2) to allow pipelines to move ahead more quickly.

**Comment by knqyf263** [comment]
Trivy uses trivy-java-db now.
https://github.com/aquasecurity/trivy-java-db
