### ISSUE TITLE
can't update the trivy database in ClientServer mode

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/trivy#2579]
from @erikgb 

## Description
I am trying to use trivy in ClientServer mode to support scanning of images built in GitLab pipelines AND to offload the actual scan jobs for trivy-operator. While this works well for some time after startup of the trivy server, it seems to crash when trying to hot-update the vuln DB:

## What happened instead?
```sh
2022-07-18T00:15:19.588Z	[34mINFO[0m	Updating DB...
2022-07-18T00:15:19.608Z	[31mERROR[0m	failed DB hot update:
    github.com/aquasecurity/trivy/pkg/rpc/server.dbWorker.update
        /home/runner/work/trivy/trivy/pkg/rpc/server/listen.go:135
  - failed to download vulnerability DB:
    github.com/aquasecurity/trivy/pkg/rpc/server.dbWorker.hotUpdate
        /home/runner/work/trivy/trivy/pkg/rpc/server/listen.go:148
  - database download error:
    github.com/aquasecurity/trivy/pkg/db.(*Client).Download
        /home/runner/work/trivy/trivy/pkg/db/db.go:157
  - failed to fetch the layer:
    github.com/aquasecurity/trivy/pkg/oci.Artifact.Download
        /home/runner/work/trivy/trivy/pkg/oci/artifact.go:120
  - GET https://artifactory/.<company-domain>/v2/ghcr-docker-remote/aquasecurity/trivy-db/blobs/sha256:69a281fd44de250530862f193d73a259641f700646b1ad6b04a268308c08a20c: unexpected status code 404 Not Found: {"errors":[{"code":"BLOB_UNKNOWN","message":"blob unknown to registry","detail":{"blobSum":"sha256:69a281fd44de250530862f193d73a259641f700646b1ad6b04a268308c
```

## Additional details (base image name, container registry info...):
Note: We run in a semi air-gapped environment, and have to go through Artifactory for pulling all images. Which in this case means that I have configured trivy to use our mirror-proxy for downloading the DB. Using Helm to deploy trivy server, I have set value trivy.dbRepository=artifactory.<company-domain>/ghcr-docker-remote/aquasecurity/trivy-db . Any clues?

**Comment by venkiain** [comment]
**image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer** (sha256:d8fd14fb96bef9c021c968f7dbccc668827baa7f9c3f4753205d4db8c94f5d18): unable to get uncompressed layer sha256:d8fd14fb96bef9c021c968f7dbccc668827baa7f9c3f4753205d4db8c94f5d18: failed to get the layer content (sha256:d8fd14fb96bef9c021c968f7dbccc668827baa7f9c3f4753205d4db8c94f5d18): GET https://myprivate/v2/myimage/blobs/sha256:dce1bb70b937c091f7e1c0027e922bea7b980c620a86cea36c0d70d4ec856e30: unexpected status code 404 Not Found: {"errors":[{"code":"BLOB_UNKNOWN","message":"blob unknown to registry","detail":{"blobSum":"sha256:dce1bb70b937c091f7e1c0027e922bea7b980c620a86cea36c0d70d4ec
