### ISSUE TITLE
Offline use documentation includes obsolete flag to oras

### ISSUE THREAD

**Issue by hlein** [aquasecurity/trivy#2580]
## Description

The documentation for air-gapped/offline use (https://aquasecurity.github.io/trivy/v0.30.2/docs/advanced/air-gap/) says to use `oras` to fetch like so:

```
$ oras pull ghcr.io/aquasecurity/trivy-db:2 -a
```

However, current `oras` throws a usage message:

```
$ oras pull ghcr.io/aquasecurity/trivy-db:2 -a                                                                    
Error: unknown shorthand flag: 'a' in -a
$ oras version
Version:        0.13.0+unreleased
Go version:     go1.18.4
Git tree state: clean

```

Per https://github.com/oras-project/oras/issues/130 and https://github.com/oras-project/oras/pull/387, `-a`/`--allow-all` behavior is now the default, and those arguments have been removed, apparently with no deprecated-warning grace period.

**Comment by DmitriyLewen** [comment]
Hello @hlein 
Thanks a lot for your report!

We will update information about this in the docs.

Best Regards, Dmitriy

**Comment by hlein** [comment]
> We will update information about this in the docs.

Sweet, thanks for the quick fix @DmitriyLewen !
