### ISSUE TITLE
Incorrect CPE generated for Debian package

### ISSUE THREAD

**Issue by 37b** [aquasecurity/trivy#2597]
## Description

The CPE for a Debian package **should be** `cpe:2.3:a:debian:dpkg:1.20.9:*:*:*:*:*:*:*` but Trivy reports it as `cpe:2.3:a:dpkg:dpkg:1.20.9:*:*:*:*:*:*:*`

## What did you expect to happen?

The correct CPE `cpe:2.3:a:debian:dpkg:1.20.9:*:*:*:*:*:*:*`

## What happened instead?

The incorrect CPE was generated `cpe:2.3:a:dpkg:dpkg:1.20.9:*:*:*:*:*:*:*`

**Comment by afdesk** [comment]
@37b thanks for your report. I'll try to clarify this issue

**Comment by afdesk** [comment]
@37b could you tell me there are any images for tests?

**Comment by 37b** [comment]
@afdesk There's no pre-built image for the project, but the code is here https://github.com/DefectDojo/django-DefectDojo

**Comment by afdesk** [comment]
@37b thanks! i can see that this project uses `python:3.8.13-slim`. it depends on `debian 11.4`, right?

which format is sensitive for you?
i mean where do you see incorrect outpur: `cpe:2.3:a:dpkg:dpkg:1.20.9:*:*:*:*:*:*:*`?

thanks a lot!

**Comment by 37b** [comment]
@afdesk According to the spec (from Wikipedia, I am not an expert)

`cpe:<cpe_version>:<part>:<vendor>:<product>:<version>:<update>:<edition>:<language>:<sw_edition>:<target_sw>:<target_hw>:<other>`

the first `dpkg` entry should be the vendor, in this case `debian`

**Comment by afdesk** [comment]
@37b sorry, I meant where do you see this CPE string?
how can i reproduce it?
thanks

**Comment by afdesk** [comment]
@37b sorry, i missed your issue. It seems I asked a weird question.

Trivy depends on several data sources, and it doesn't generate CPE strings. 
I'd like to figure out where it came from.

so could you confirm that this issue is still appears and where/when Trivy shows the incorrect CPE string? 

thanks a lot

**Comment by knqyf263** [comment]
Trivy doesn't generate CPE.
