### ISSUE TITLE
Reduce a cache size

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#260]
Currently, trivy stores the entire layer as a cache. This makes the size of cache increase. 
https://github.com/aquasecurity/fanal/blob/c1c079886da609315fbffaeec5ca95ef5ac451f6/extractor/docker/docker.go#L206

But the necessary files are not so much. We should store only necessary files.
`filenames` are file names to be extracted from tar layers.
https://github.com/aquasecurity/fanal/blob/c1c079886da609315fbffaeec5ca95ef5ac451f6/extractor/docker/docker.go#L262

**Comment by simar7** [comment]
Could you comment on what are these "necessary files" that need to be stored?

**Comment by knqyf263** [comment]
Each analyzer has `RequiredFiles()`. 
e.g.
https://github.com/aquasecurity/fanal/blob/e80236018d261719c3caaac25b9eed8a662716c0/analyzer/os/alpine/alpine.go#L36-L38

Then, `analyzer.RequiredFilenames()` calls all `RequiredFiles()`
https://github.com/aquasecurity/fanal/blob/e80236018d261719c3caaac25b9eed8a662716c0/analyzer/analyzer.go#L101-L114

They are passed to `Extract` as `filenames`.
https://github.com/aquasecurity/fanal/blob/e80236018d261719c3caaac25b9eed8a662716c0/analyzer/analyzer.go#L129

Before storing an entire layer to the cache, we can filter the layer by `filenames`.
https://github.com/aquasecurity/fanal/blob/c1c079886da609315fbffaeec5ca95ef5ac451f6/extractor/docker/docker.go#L206

But, we have to care that the layer is a tar format. We may need to decompress the tar file. Or, we can use BoltDB to store the cache.

Besides, we have many options.

- Layer ID or Image ID?
  - Layer ID: Many layers are duplicate, but we need to apply layers again.
  - Image ID: If the same image is passed again, trivy can return the result fastly. But if the images are a little different, trivy needs to fetch all layers again.
- Local file system or BoltDB?
- Raw content or JSON?
  - Raw content: actual file content
  - JSON: a result after analyzing an image

Example
- Use a layer id on a local file system (dir)
  - sha256:[LAYER_ID] (dir)
    - /var/lib/dpkg/status (file)
    - /etc/os-release (file)
- Use a layer id on a local file system (tar)
  - sha256:[LAYER_ID] (tar file)
    - /var/lib/dpkg/status (file)
    - /etc/os-release (file)
- Use a image digest on a local file system (dir)
  - sha256:[IMAGE_ID] (dir)
    - /var/lib/dpkg/status (file)
    - /etc/os-release (file)
- Use a image digest on a local file system (tar)
  - sha256:[IMAGE_ID] (tar)
    - /var/lib/dpkg/status (file)
    - /etc/os-release (file)
- Use a layer id on a local file system (dir)
  - sha256:[LAYER_ID] (dir)
    - /var/lib/dpkg/status (file)
    - /etc/os-release (file)
- Use a layer id on BoltDB
  - sha256:[LAYER_ID] (bucket)
    - "/var/lib/dpkg/status": []byte
    - "/etc/os-release": []byte
- Use a image digest on BoltDB
  - sha256:[IMAGE_ID] (bucket)
    - "/var/lib/dpkg/status": []byte
    - "/etc/os-release": []byte
- Use a image digest and store JSON on a local file system
  - sha256:[IMAGE_ID] (filename)
    - {"InstalledPackages": [{"bash": "1.2.3"}, {"openssl": "1.1.1"}]...}
- Use a image digest and store JSON on BoltDB
  - "sha256:[IMAGE_ID]": {"InstalledPackages": [{"bash": "1.2.3"}, {"openssl": "1.1.1"}]...}

@simar7 what do you think?

**Comment by knqyf263** [comment]
Closed by https://github.com/aquasecurity/trivy/pull/398
