### ISSUE TITLE
  Report problems that cannot be displayed normally, 

### ISSUE THREAD

**Issue by jiangsi520** [aquasecurity/trivy#2600]
I tried to export the report template and found that only html.tpl can display the interface normally, while others such as asff.tpl and gitlab.tpl cannot be opened normally. When I open it with a browser, the source code is displayed.
![image](https://user-images.githubusercontent.com/30169495/181205862-653b7c8d-dad1-4d91-a43f-8c45af92defa.png)

![image](https://user-images.githubusercontent.com/30169495/181201842-a2cd9778-a641-4304-b78d-5ae8b546222e.png)

**Comment by knqyf263** [comment]
Other templates don't export HTML.
