### ISSUE TITLE
Is there any API for Trivy scanner?

### ISSUE THREAD

**Issue by srtimsina** [aquasecurity/trivy#261]
Because we want to host Trivy and Jenkins build server on different hosts, we are looking for the Trivy API so that we can scan the Docker images after each build. We want to scan the docker image from Jenkins using the Trivy's API, i.e Jenkins should access the locally hosted Trivy server and scan the newly created image.

**Comment by knqyf263** [comment]
I'm sorry, but Trivy doesn't have API for now. But we may support it in the future.

**Comment by srtimsina** [comment]
Thank you @knqyf263, for the information.
