### ISSUE TITLE
Scan SBOM attestation

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#2614]
Trivy generates SBOM and [cosign](https://github.com/sigstore/cosign) uploads it in an in-toto attestation format to OCI registry. 
https://aquasecurity.github.io/trivy/dev/docs/attestation/sbom/

Also, Trivy can scan SBOM (currently CycloneDX only) for vulnerabilities.
https://aquasecurity.github.io/trivy/dev/docs/sbom/cyclonedx/

The next step is consuming the SBOM attestation and scanning it for vulnerabilities. There are some use cases as far as I know.

1. Fetch attestation of a container image from OCI registry, extract SBOM and scan it for vulnerabilities
2. [cosign verify-attestation](https://github.com/sigstore/cosign/blob/main/doc/cosign_verify-attestation.md) returns verified attestation, so Trivy takes it as input and scans it for vulnerabilities
3. Take a local file including attestation and scan it

We may want to add a new subcommand for attestation like `trivy attestation` that takes attestation as input. Then, the commands for each above could be as below.

1. `$ trivy image --attest knqyf263/myapp:latest`
2. `$ cosign verify-attestation --key cosign.pub knqyf263/myapp:latest | trivy attestation -`
3. `$ trivy attestation ./vuln.json`

Feedback is welcome.

**Comment by knqyf263** [comment]
@otms61 Could you take it?

**Comment by otms61** [comment]
Alright. I will try.
