### ISSUE TITLE
Can trivy resolve python dependencies?

### ISSUE THREAD

**Issue by eslamkarim** [aquasecurity/trivy#2620]
Hey all I wanted to use trivy in a python environment but i couldn't find a way to not only scan the requirements file but also whatever dependencies these packages will probably have as my solution will require failing a build if a dependency is vulnerable.
Is this something we can do already with trivy? or is it something to think about?
Thank you!

**Comment by knqyf263** [comment]
Please refer to this page.
https://aquasecurity.github.io/trivy/v0.30.4/docs/vulnerability/detection/language/

**Comment by eslamkarim** [comment]
@knqyf263 this page says that dev dependencies are included but i don't see that
using other solutions i do find some vulnerable dependencies while in argo it doesn't really care it just flags a package vulnerable if this package itself have vulnerabilities.
did i understand the table wrong? does dev dependencies mean something else than what i expected?
