### ISSUE TITLE
Transient issue when scanning containers with zfs storage - "error creating zfs mount"

### ISSUE THREAD

**Issue by 4oo4** [aquasecurity/trivy#2624]
## Description
I use zfs for my storage backend for docker, and I noticed that sometimes when I scan it terminates early because it's unable to find something in the zfs graph directory. If I try to rescan it right after that (just a few seconds later) it works.

## What did you expect to happen?
Trivy has some way of dealing with this, perhaps a timer and retry? Is trivy zfs-aware when it scans docker images? I'm wondering if the layer it was referencing might have been a r/w clone that trivy tried to scan by mistake. I might be wrong but I was thinking that docker does things a bit differently when zfs is used for storage.

https://docs.docker.com/storage/storagedriver/zfs-driver/

## What happened instead?
The scan aborted.

## Output of run with `-debug`:
Because it happens randomly, I haven't captured debug output yet, but I'm not sure how I can figure out what type of layer that is (zfs snapshot, clone, r/w clone) based on just the path it's giving.

```
2022-07-28T23:10:37.050-0500	INFO	Vulnerability scanning is enabled
2022-07-28T23:10:37.063-0500	INFO	Detected OS: ubuntu
2022-07-28T23:10:37.063-0500	INFO	Detecting Ubuntu vulnerabilities...
2022-07-28T23:10:37.069-0500	INFO	Number of language-specific files: 0
2022-07-28T23:10:37.432-0500	INFO	Vulnerability scanning is enabled
2022-07-28T23:11:31.930-0500	FATAL	image scan error: scan error: image scan failed: failed analysis: analyze error: failed to analyze layer: sha256:015cd120071b14a5c117e774493178dd1b034e0a0d17bcf1a6c730dd1f902bec : unable to get uncompressed layer sha256:015cd120071b14a5c117e774493178dd1b034e0a0d17bcf1a6c730dd1f902bec: failed to get the layer (sha256:015cd120071b14a5c117e774493178dd1b034e0a0d17bcf1a6c730dd1f902bec): unable to populate: unable to open: unable to export the image: Error response from daemon: error creating zfs mount: mount zstorage/zfs/730a65b41e038487a2ea3b11494b4d8ded01fda84af2570aa5c367894d23b3d4://mnt/zfs/.docker/docker/zfs/graph/730a65b41e038487a2ea3b11494b4d8ded01fda84af2570aa5c367894d23b3d4: no such file or directory
```

## Output of `trivy -v`:

```
Version: 0.30.4
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-07-29 00:11:12.52345116 +0000 UTC
  NextUpdate: 2022-07-29 06:11:12.52345066 +0000 UTC
  DownloadedAt: 2022-07-29 03:06:56.685095577 +0000 UTC

```

## Additional details (base image name, container registry info...):
I think the container that caused the issue was this one: https://hub.docker.com/r/linuxserver/unifi-controller

Cheers

**Comment by DmitriyLewen** [comment]
Hello @4oo4 
Thanks for your report!

Trivy uses [github.com/docker/docker](https://github.com/moby/moby) repository to save image and read layers.
`docker/docker` supports `zfs`. `error creating zfs mount` error was received from this repository.

I tried reproduce your error, but Trivy works correctly.

Can you tell me any steps to reproduce error?

Best Regards, Dmitriy

**Comment by 4oo4** [comment]
OK cool. When this happened I'd be scanning a docker image with a command like this:
`trivy image --security-checks vuln --timeout 15m --format template --template "@/usr/local/share/trivy/templates/html.tpl" -o myimage.html myimage`

When I got the error I was running trivy was in a bash script and scanning about 7 containers sequentially, and I had to do this multiple times in a row to get my script working. It tended to happen on the first container it tried to scan. I wasn't doing any other docker operations (restarting containers, building images, etc.) at the time I was doing the scan.

If I'm understanding correctly, trivy might have just gotten a strange response from the docker daemon, versus something with trivy itself? If that's the case, then I can close the issue, and look more closely at the docker side.

Thanks

**Comment by DmitriyLewen** [comment]
Hello @4oo4 
> trivy might have just gotten a strange response from the docker daemon, versus something with trivy itself?

You are right. Trivy gets error when docker daemon tries to save image.(Trivy saves working image to temp dir and works with this copy).

You said you used script. Do you have error when running Trivy without bash script?  It's very weird, but there might be a problem with this.

**Comment by 4oo4** [comment]
No, I haven't encountered it there. My script isn't doing anything fancy, just finding docker images from running containers then passing it to a trivy command to get a couple different report formats:

```bash
images=($(docker ps | awk '{print $2}' | tail -n +2))

short_template='{{- $critical := 0 }}{{- $high := 0 }}{{- range . }}{{- range .Vulnerabilities }}{{- if  eq .Severity "CRITICAL" }}{{- $critical = add $critical 1 }}{{- end }}{{- if  eq .Severity "HIGH" }}{{- $high = add $high 1 }}{{- end }}{{- end }}{{- end }}Critical: {{ $critical }}, High: {{ $high }}'

    for image in ${images[@]}; do
        
        report_filename=$(echo "${image}"| sed 's|/|-|g; s|:|-|g;');
        report_path="${trivy_report_dir}/${report_filename}_${date_string}.html"
        
        trivy_summary=$(trivy image \
            --security-checks vuln \
            --ignore-unfixed \
            --timeout 15m  \
            --format template \
            --template "${short_template}" "${image}")

        trivy image \
            --security-checks vuln \
            --ignore-unfixed \
            --timeout 15m \
            --format template \
            --template "@/usr/local/share/trivy/templates/html.tpl" \
            -o "${report_path}" "${image}";
    done
```
So I think it may just have been something weird with the way I was testing this and perhaps causing something weird to happen with my docker daemon. I haven't experienced it for a while, so I'm not going to worry about it.

Thanks!
