### ISSUE TITLE
Trivy for k3s

### ISSUE THREAD

**Issue by muddassir-r** [aquasecurity/trivy#2627]
Can I run trivy on k3s setup?

**Comment by knqyf263** [comment]
There are two options:
- Helm chart
  - https://github.com/aquasecurity/trivy/tree/main/helm/trivy
- Operator
  - https://aquasecurity.github.io/trivy-operator/v0.1.5/

**Comment by muddassir-r** [comment]
Can we use Trivy to scan k3s cluster?

**Comment by knqyf263** [comment]
It should work.
