### ISSUE TITLE
scanning images from artifactroy

### ISSUE THREAD

**Issue by mammademachine** [aquasecurity/trivy#264]
Hello everyone,

sorry if asking dull question but, I am trying to scan images from company artifactory and constantly hitting the wall.

`sudo trivy -d artifactory.company.com:5001/someimage:tag`

I get

`2019-11-14T12:04:57.891Z        DEBUG   cache dir:  /home/user/.cache/trivy
2019-11-14T12:04:57.893Z        DEBUG   db path: /home/user/.cache/trivy/db/trivy.db
2019-11-14T12:04:57.918Z        INFO    Updating vulnerability database...
2019-11-14T12:04:57.920Z        DEBUG   git pull
2019-11-14T12:04:58.900Z        DEBUG   total updated files: 1
2019-11-14T12:04:58.906Z        DEBUG   Vulnerability type:  [os library]
2019-11-14T12:05:00.431Z        FATAL   error in image scan:
    github.com/aquasecurity/trivy/pkg.Run
        /home/circleci/project/pkg/run.go:168
  - failed to analyze image:
    github.com/aquasecurity/trivy/pkg/scanner.ScanImage
        /home/circleci/project/pkg/scanner/scan.go:38
  - failed to extract files:
    github.com/aquasecurity/fanal/analyzer.Analyze
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20191015084852-e80236018d26/analyzer/analyzer.go:131
  - failed to get the v2 manifest:
    github.com/aquasecurity/fanal/extractor/docker.DockerExtractor.Extract
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20191015084852-e80236018d26/extractor/docker/docker.go:181
  - Get https://artifactory.company.com:5001/v2/someimage/manifests/tag: http: non-successful response (status=401 body="{\n  \"errors\" : [ {\n    \"status\" : 401,\n    \"message\" : \"Authentication is required\"\n  } ]\n}")`

I tried to add 

export TRIVY_AUTH_URL=https://artifactory.company.com # with and without ports 80 443 5001 # and with both http and https
export TRIVY_USERNAME={ARTIFACTORY_USERNAME}
export TRIVY_PASSWORD={ARTIFACTORY_PASSWORD}

result is always the same.

Does Trivy support Artifactory and if it does what am I missing in my steps or doing wrong for that matter.

Thank you in advance.

**Comment by webmutation** [comment]
What version of trivy are you using?

In your pipeline are you able to pull the docker image, using docker pull command ?

**Comment by mammademachine** [comment]
version: 0.1.7
@webmutation yes I did managed to pull image and to enable trivy to scan it once I do docker login with artifactory credentials as a workaround.

anyhow it would be nice if trivy could work with artifactory directly but this will do as well.

Tnx again.

Question closed.
