### ISSUE TITLE
Difference between cluster and all in scan command

### ISSUE THREAD

**Issue by muddassir-r** [aquasecurity/trivy#2655]
Whats the diffecrence between the below two commands. When to use **all** and when to use **cluster**

$ trivy k8s -n kube-system --report=summary **all**
$ trivy k8s --report=summary **cluster**

**Comment by knqyf263** [comment]
`cluster` includes cluster-level resources such as ClusterRole

**Comment by muddassir-r** [comment]
@knqyf263 So can I add both `cluster `and `all `in single command. or which one to use for maximum coverage?

**Comment by knqyf263** [comment]
`cluster` covers more than `all`. Please refer to the doc.
https://aquasecurity.github.io/trivy/v0.30.4/docs/kubernetes/cli/scanning/

**Comment by muddassir-r** [comment]
@knqyf263 Thank you for your response. 
Actually `https://aquasecurity.github.io/trivy/v0.30.4/docs/kubernetes/cli/scanning/` doesn't explains the difference.

**Comment by knqyf263** [comment]
OK, we'll update the doc. Thanks.
