### ISSUE TITLE
```trivy image``` support auth parameterization when use self hosted repo

### ISSUE THREAD

**Issue by afghanistanyn** [aquasecurity/trivy#2659]
1. Using env  ```TRIVY_USERNAME,TRIVY_PASSWORD``` is too difficult when i hava to scan a lot of image from diffrent repo. 
2.  i integrate trivy to my app , to set diffrent auth info, i have to  rewrite runner.ScanImage()

i hope ```DockerConfig``` or ```DockerOption``` add to ```flag.Options```

**Comment by knqyf263** [comment]
I've started working on that.
