### ISSUE TITLE
Enable ARM testing on Github actions

### ISSUE THREAD

**Issue by odidev** [aquasecurity/trivy#2660]
Hi Team, 

Currently, there are only AMD64 test jobs available in GitHub actions. We can add arm64 test jobs as well in the CI to this repository. I have successfully tested all features and ran unit and Module Integration tests of trivy on the ARM64 platform. It will be useful if we add test jobs for ARM64 as well in GitHub actions. 

We can do ARM64 testing in GitHub actions using self-hosted arm64 runners. 

If interested, we can get access to ARM H/W through [WorksOnArm](https://github.com/WorksOnArm).

**Comment by aktech** [comment]
Hey @odidev Sorry for jumping on this. "ARM testing" got my attention. 

You can achieve this easily with https://cirun.io It creates on demand runners for GitHub Actions on your cloud and manages the complete lifecycle. You simply connect your cloud provider and define what runners you need in a simple `yaml` file and that's it.

See https://docs.cirun.io/reference/examples.html#aws for example. Let me know if you have any questions. I am the creator of Cirun.
