### ISSUE TITLE
Json report to HTML report

### ISSUE THREAD

**Issue by muddassir-r** [aquasecurity/trivy#2661]
How to convert Json scan report to HTML format.

I tried @contrib/html.tpl but it was showing some error.

**Comment by afdesk** [comment]
@muddassir-r 

```sh
$ trivy image -f template --template @contrib/html.tpl alpine:latest
```

**Comment by muddassir-r** [comment]
I am using the following 
sudo trivy kubernetes -n namespace deployment appname --timeout 3000s --format template --template "@contrib/html.tpl" -o report.html

Do we need to mention -o filename.html?

**Comment by afdesk** [comment]
@muddassir-r could you check a path to the html template?
i mean that subfolder `contrib` should contain `html.tpl`.

**Comment by afdesk** [comment]
@muddassir-r also `json` format works correctly, right?

**Comment by muddassir-r** [comment]
@afdesk 
yes json works correctly, I installed trivy using the debian package. Is there something I need to do differently.

**Comment by afdesk** [comment]
you can download `html.tpl` here https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl
and use a path to this file

**Comment by afdesk** [comment]
> @afdesk I git cloned the repo and html.tpl is present inside contrib

does it work?

**Comment by muddassir-r** [comment]
@afdesk i am getting the below error.
FATAL   unable to write results: unknown format "template". Use "json" or "table"

**Comment by afdesk** [comment]
@muddassir-r oh, it maybe another issue

**Comment by muddassir-r** [comment]
@afdesk please let me know is you need more info to debug. I would be happy to share.

**Comment by muddassir-r** [comment]
@afdesk do I need to provide the path in double quotes ""?

**Comment by afdesk** [comment]
@muddassir-r i'm so sorry, i missed this issue and your last comments.
subcommand `kubernetes` in `Trivy` doesn't support `template` flag yet

**Comment by muddassir-r** [comment]
@afdesk Thank you for the response. 
Hope we can take this as a feature for enhancement.
