### ISSUE TITLE
Add Severity to .trivyignore

### ISSUE THREAD

**Issue by dkahn22** [aquasecurity/trivy#2670]
Would it be possible to add the capability to add a Severity field to the .trivyignore.  This feature would cover the case where a finding ID can change severity, such as from High to Critical, or Unknown to High, and allow for the finding to not get erroneously ignored.

**Comment by knqyf263** [comment]
Sorry for the late reply. It could be interesting. Here is where we filter out results.
https://github.com/aquasecurity/trivy/blob/1064636b3d4fe750c78f02754ab61814eddc1bb8/pkg/result/filter.go#L31-L54

**Comment by knqyf263** [comment]
I think we can merge this task into https://github.com/aquasecurity/trivy/issues/4022
