### ISSUE TITLE
can vulns in table be sorted by severity, so that "CRITICAL" display first etc?

### ISSUE THREAD

**Issue by jamesfmaccoll** [aquasecurity/trivy#2671]
As title, I'd like to be able to sort table vulns by severity. This is so that when developers are checking, they'll see the worst vulns first, which I believe will encourage action, rather than possibly being buried further down "randomly".

**Comment by DmitriyLewen** [comment]
Hello @jamesfmaccoll 

Trivy is currently unable to sort the results.

We are always glad to new members. contributions.
You can create changes and create PR.
More information about contribution [here](https://aquasecurity.github.io/trivy/v0.30.4/community/contribute/pr/).

Best Regards, Dmitriy

**Comment by cfculhane** [comment]
Hi, a workaround that I used was to define a template where it defined a list and then iterated over that, e.g. from my modified html template:

```
{{- range $severity_level := list "CRITICAL" "HIGH" "MEDIUM" "LOW" "UNKNOWN"}}
    {{- range $vuln := $result.Vulnerabilities }}
        {{ if (eq (escapeXML $vuln.Vulnerability.Severity) $severity_level) }}
            <tr class="severity-{{ escapeXML $vuln.Vulnerability.Severity }}">
                <td class="pkg-name">{{ escapeXML $vuln.PkgName }}</td>
                <td>{{ escapeXML $vuln.VulnerabilityID }}</td>
                <td class="severity">{{ escapeXML $vuln.Vulnerability.Severity }}</td>
                <td class="pkg-version">{{ escapeXML $vuln.InstalledVersion }}</td>
                <td>{{ escapeXML $vuln.FixedVersion }}</td>
                <td>{{ escapeXML $vuln.Description }}</td>
                <td class="links" data-more-links="off">
                    {{- range $vuln.Vulnerability.References }}
                        <a href={{ escapeXML . | printf "%q" }}>{{ escapeXML . }}</a>
                    {{- end }}
                </td>
            </tr>
        {{- end }}
    {{- end}}
{{- end }}
```

**Comment by itaysk** [comment]
Sorting/prioritization is currently out of scope for Trivy. We recommend taking the results to another tool for further processing.
