### ISSUE TITLE
Output both the table and json to be saved

### ISSUE THREAD

**Issue by webmutation** [aquasecurity/trivy#268]
Trivy 0.2.0 is really fast, already replaced clair with this version.
However there is one feature that i am missing, that that is the ability to have the table output that is great for logs, but also have the json output to be saved and uploaded to a repository. 

Would it be possible to enable this feature, save as json and output as table. looking at the -f option it seems to take only one parameter.

**Comment by knqyf263** [comment]
How about running Trivy twice?

```
$ trivy alpine:3.10
$ trivy -f json -o result.json alpine:3.10
```

If you run twice, it takes only a few seconds.

**Comment by webmutation** [comment]
Ill do that then! Thanks for the tip

**Comment by knqyf263** [comment]
I'm sorry for the inconvenience. If you still think trivy should have the feature, don't hesitate to reopen this PR.

**Comment by ganeshkumar5699** [comment]
It would be great to have this feature, to avoid re-running twice and doubling the execution time, especially when there are many components that need to be scanned.

**Comment by knqyf263** [comment]
Please track the issue
https://github.com/aquasecurity/trivy/issues/3243
