### ISSUE TITLE
json result with trivy image

### ISSUE THREAD

**Issue by krol3** [aquasecurity/trivy#2681]
Hi! 

I'm genereting a json output ` trivy image --format json --output alpine.json alpine:3.10.9`

In the json generated, I can't the  "total" structure, that I found in the --format table

````
alpine:3.10.9 (alpine 3.10.9)
=============================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 1)

`````
I expected to have in the json similar to this sample in json, this structure will help us to generate template to Postee. @simar7 

````

  "vulnerability_summary": {
    "total": 1,
    "critical": 1,
    "high": 0,
    "medium": 0
  },
````

**Comment by simar7** [comment]
I'd +1 this, it'd be useful to have a summary of vulnerabilities in the JSON output. Postee can then use such JSON results with a very simple rego rule like: `input.report.summary.criticalCount > 0` to trigger actions.

FWIW, Trivy operator does something similar today to summarize and include as part of the `vulnerabilityreports`.

**Comment by knqyf263** [comment]
Does it mean summary per OS packages and lang-specific packages? Or do you want the total summary?
Let's say OS packages have 5 critical and `package-lock.json` has 3 medium. Do you want to see the summary as follows?

```
"vulnerability_summary": {
    "total": 8,
    "critical": 5,
    "high": 0,
    "medium": 3
  },
```

**Comment by simar7** [comment]
> Does it mean summary per OS packages and lang-specific packages? Or do you want the total summary? Let's say OS packages have 5 critical and `package-lock.json` has 3 medium. Do you want to see the summary as follows?
> 
> ```
> "vulnerability_summary": {
>     "total": 8,
>     "critical": 5,
>     "high": 0,
>     "medium": 3
>   },
> ```

I see - good question, I would be fine with just a summary.
