### ISSUE TITLE
Is Vulnerability database needed to create SBOMs?

### ISSUE THREAD

**Issue by niklaskeerl** [aquasecurity/trivy#2687]
First of all, thank you for maintaining such an important product for security.
I use trivy to create SBOMs for all kinds of artifacts from different programming languages since trivy supports very many of them.
Here also comes my question.

Since I only want to create SBOMs and do not want vulnerability detection, I want to ask if downloading the vulnerability database is necessary?
If it is not needed, then forcing to download the vulnerability database could save energy and internet traffic and would improve the overall carbon footprint of the program.

I tried the following:
```
trivy fs --offline-scan --security-checks vuln --output bom.json --format cyclonedx --skip-db-update .
```

This returns the following:
```
FATAL	init error: DB error: database error: --skip-update cannot be specified on the first run
```

Thank you in advance for answering my question and taking your time :)

**Comment by knqyf263** [comment]
Duplicated. Coming in v0.31.0.
https://github.com/aquasecurity/trivy/issues/2557
