### ISSUE TITLE
Scan Multiple Images

### ISSUE THREAD

**Issue by sohnaeo** [aquasecurity/trivy#2696]
Hi,

I am trying to work out how can I run trivy against multiple docker images. As per the command, 

`--input value, -i value          input file path instead of image name [$TRIVY_INPUT]`

I am not sure how the file look like. Could someone help to provide me the file format how it should look like? Documentation doesnt provide any more information about this. I tried putting the image names in /tmp/images and it throws an error

```
/app10/trivy  --cache-dir=/app/.cache/trivy/ image --skip-update --vuln-type os --severity CRITICAL -i /tmp/images
2022-08-11T17:03:25.674+1000	FATAL	scan error: unable to initialize a scanner: unable to initialize the archive scanner: 2 errors occurred:
	* unable to open /tmp/images as a Docker image: unexpected EOF
	* unable to open /tmp/images as an OCI Image: stat /tmp/images/index.json: not a directory
```
I provided the image names in json format in file but it didnt work as well. 

I just realised it is for OCI directory. Is there way to scan multiple images in one go?

Thank you.

**Comment by DmitriyLewen** [comment]
Hello @sohnaeo 
Thanks for your interest to Trivy!

Trivy doesn't currently support scanning multiple images.

`--image` flag used to scan local [tar](https://docs.docker.com/engine/reference/commandline/save/#examples) image. 

Regards, Dmitriy

**Comment by tuananh** [comment]
I would love to have this feature implemented as well. maybe support piping from other tools to trivy too.

**Comment by ganeshkumar5699** [comment]
Interested in this feature too

**Comment by sbp-bvanb** [comment]
Could this be reopened?

**Comment by knqyf263** [comment]
We don't have plans to add support for that upstream. You can write a plugin.
https://aquasecurity.github.io/trivy/v0.46/docs/advanced/plugins/
