### ISSUE TITLE
composer.lock files in vendor folder are scanned

### ISSUE THREAD

**Issue by mihob** [aquasecurity/trivy#2705]
## Description

I scanned an image with a php application and trivy scanned the composer.lock files in the vendor folder. But these do not reflect what is really installed, trivy should only scan the composer.lock of the application. 

This was also the case in the older versions.

## What did you expect to happen?

composer.lock files in the vendor folder should be ignored.

## What happened instead?

composer.lock Dateien im vendor Ordner werdne nicht ignoriert.

## Output of `trivy -v`:

```
Version: 0.30.4
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-08-15 06:07:55.064552776 +0000 UTC
  NextUpdate: 2022-08-15 12:07:55.064552376 +0000 UTC
  DownloadedAt: 2022-08-15 08:48:03.542538 +0000 UTC
```

**Comment by knqyf263** [comment]
Thanks for the report. It is a regression. We will fix it soon.
