### ISSUE TITLE
Does not do scan when using --clear-cache/TRIVY_CLEAR_CACHE

### ISSUE THREAD

**Issue by mpicard** [aquasecurity/trivy#273]
It appears as thought the --clear-cache/TRIVY_CLEAR_CACHE flag is preventing the scan from running. Prior to v0.2.0, when the --clear-cache flag was added it would still preform the scan but now if I add the flag I only get the follow output:

```
2019-11-15T10:10:24.643Z	INFO	Removing image caches...
```

When I remove the flag the scan performs as normally. Is this intentional or a regression?

**What did you expect to happen?**

I expect the scan to run and output the findings when including the --clear-cache flag

**What happened instead?**

The cache was cleared but the scan was not performed and the exit code was 0

**Output of run with `-debug`:**

```
2019-11-15T10:20:56.348Z	DEBUG	cache dir:  /root/.cache/trivy
2019-11-15T10:20:56.356Z	DEBUG	DB update was skipped because DB is the latest
2019-11-15T10:20:56.356Z	INFO	Removing image caches...
```

**Output of `trivy -v`:**

```
trivy version 0.2.0
```

Image does not matter but I used `python:3.4-alpine` since there are some open CVEs in there.

**Comment by knqyf263** [comment]
@mpicard Thank you for reporting the issue. I changed a behavior, so this is intentional. I will add an explanation to the CLI help.
