### ISSUE TITLE
add support for --profile flag w.r.t to saml2aws

### ISSUE THREAD

**Issue by swapHR** [aquasecurity/trivy#2732]
While running trivy locally we encounter `FATAL	unknown flag: --profile` when the environment is configured with [saml2aws](https://github.com/Versent/saml2aws) which has multiple aws profiles

**Comment by liamg** [comment]
We can add this argument, in the meantime could you try using `export AWS_PROFILE=whatever` to set your profile name and then running trivy?

**Comment by swapHR** [comment]
Thanks, this was helpful!
