### ISSUE TITLE
Scanning of Helm chart with dependencies does not work

### ISSUE THREAD

**Issue by romanwoessner** [aquasecurity/trivy#2735]
## Scanning of Helm chart with dependencies does not work

Misconfiguration scanning of simple Helm charts without dependencies works as expected. As soon as you are trying to scan a chart with dependencies, the scan does not work.

Steps to reproduce:
1. Create a new helm chart with `helm create chart-with-dependencies`
2. Add a dependency in the newly created `Chart.yaml`:
```yaml
dependencies:
  - name: kube-prometheus-stack
    version: "39.8.0"
    repository: https://prometheus-community.github.io/helm-charts
```
3. Run `helm dependency update`

## What did you expect to happen?

Running `trivy config ./chart-with-dependencies` should detect a Helm chart, its templates and should output the scan result.

## What happened instead?

```
❯ trivy config ./chart-with-dependencies
2022-08-17T13:57:09.039+0200    INFO    Misconfiguration scanning is enabled
2022-08-17T13:57:09.091+0200    INFO    Detected config files: 0
```

## Output of run with `-debug`:

```
❯ trivy config ./chart-with-dependencies --debug
2022-08-17T13:55:15.587+0200    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-08-17T13:55:15.625+0200    DEBUG   cache dir:  /Users/woessner/Library/Caches/trivy
2022-08-17T13:55:15.626+0200    INFO    Misconfiguration scanning is enabled
2022-08-17T13:55:15.676+0200    DEBUG   OS is not detected.
2022-08-17T13:55:15.676+0200    INFO    Detected config files: 0
```

## Output of `trivy -v`:

```
Version: 0.31.2
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-08-11 06:08:51.78901066 +0000 UTC
  NextUpdate: 2022-08-11 12:08:51.78901036 +0000 UTC
  DownloadedAt: 2022-08-11 11:09:46.239071 +0000 UTC
```

**Comment by romanwoessner** [comment]
It seems to be fixed in 0.34.0 🥳

**Comment by romanwoessner** [comment]
Unfortunately I do not have any information about how this has been fixed.
I just played around a bit and found that the scan with dependencies only works for unpacked charts. Scanning charts as a zipped tarball does not work for either 0.38 or 0.34.0.

**Comment by andrewwarz** [comment]
I think I figured out what I need to do. When I run the job I need to do a before_script to install helm -- then run "helm dependency build" before performing my trivy scan. just incase anyone stumbles upon this
