### ISSUE TITLE
Any way to ignore secrets scanning in intermediate layers?

### ISSUE THREAD

**Issue by isuftin** [aquasecurity/trivy#2744]
Currently, we build a Docker image to be used internally using https://hub.docker.com/r/jenkins/ssh-agent as the base

We came up on this issue: https://github.com/jenkinsci/docker-ssh-agent/issues/116

In previous versions of Trivy we were fine because we do remove the secrets in the derivative image. However, with the new version of Trivy, the image does get flagged because it does check intermediate layers for the secrets. I understand the point of that feature but we would like to ignore the intermediate layers for secrets while still scanning for secrets in our final image instead of having to add a `--skip-dirs` command since we do also want to include all dirs in that secret scanning.

I don't see anything documented for this. Is this something that exists in Trivy or can be added?

**Comment by DmitriyLewen** [comment]
Hello @isuftin 
Thanks for your interest to Trivy!

Can you explain the reason why you want to disable secrets scanning in intermediate layers?
After removing secrets they still exists in your image.

Best Regards, Dmitriy

**Comment by exiett** [comment]
Just want to add on this issue as it may seem related, I'm not interested in scanning images at all when using `trivy image` in a pipeline flow. Is there an easy way to ignore all secret scanning as I'm only interested in lang packages/vulns and OS-based vulns? 

c/c @DmitriyLewen 

Thank you in advance. :)

**Comment by DmitriyLewen** [comment]
Hello @exiett 
You can use `--security-checks vuln`.
More information about image flags [here](https://aquasecurity.github.io/trivy/v0.32/docs/references/cli/image/)

Regards, Dmitriy
