### ISSUE TITLE
Optionally include Copyrights/Notices in scan results

### ISSUE THREAD

**Issue by omkarparkhe** [aquasecurity/trivy#2756]
Opening a new issue as the older one was closed. 
https://github.com/aquasecurity/trivy/issues/1639

**Comment by knqyf263** [comment]
@omkarparkhe We're sorry to be late. Could you elaborate on that?

**Comment by PeterBurner** [comment]
@knqyf263 could you please re-open this ticket? I think this is still relevant and would be a valuable feature.

Regarding the feature:
Many licenses contain a copyright notice. It usually consists of a copyright holder and a year or version number. Most of these licenses (like MIT, Apache, GPL, LGPL, MPL, etc.) do require you to reproduce the copyright notice(s) of the original authors and any subsequent contributors when you distribute the software. This is usually a core condition of the license.
Popular SBOM formats even specify a dedicated field for the copyright notice (CycloneDX --> `Copyright`, SPDX --> `copyrightText`, ...).
Unfortunately Trivy currently does not exposed this information in any way.

For completenes sake:
The original ticket was converted into a [discussion](https://github.com/aquasecurity/trivy/discussions/4374).
