### ISSUE TITLE
sign vulnerability attestation before saving it to the disk

### ISSUE THREAD

**Issue by developer-guy** [aquasecurity/trivy#2758]
We (w/@dentrax) thought there was a slight time window that the attacker could gain access to the system and changes the content of the vulnerability attestation before you sign and upload it to the registry. A similar problem has been addressed in the Syft project for SBOM attestations[^1]. So, we should sign the vulnerability attestation before saving it to the disk. 

If you like the idea, we are willing to do that, and please share your thoughts, thanks.
cc: @knqyf263 @itaysk 

[^1]: https://anchore.com/sbom/creating-sbom-attestations-using-syft-and-sigstore/

**Comment by knqyf263** [comment]
What if we pass attestations via pipe?

```
$ trivy image -f cosin-vuln <IMAGE> | COSIGN_EXPERIMENTAL=1 cosign attest --type vuln --predicate - <IMAGE>
```

Then, all security scanners don't have to re-implement cosign functionalities.

**Comment by developer-guy** [comment]
Quoted from @znewman01:

> FWIW you can do this today in bash or zsh (though not sh) with process substitution:
```shell
COSIGN_EXPERIMENTAL=1 cosign attest \
    --type vuln \
    --predicate <(trivy image -f cosin-vuln <IMAGE>) \
    <IMAGE>
```

**Comment by znewman01** [comment]
But also note @developer-guy's PR to accept `-` to read from STDIN: https://github.com/sigstore/cosign/issues/2215

That's a better long-term solution 😄

**Comment by knqyf263** [comment]
Looks like @developer-guy'S PR got merged. Thanks for your help.

**Comment by itaysk** [comment]
We should probably update the docs still
