### ISSUE TITLE
Support for HTML report format when using `trivy k8s`

### ISSUE THREAD

**Issue by mohan-13** [aquasecurity/trivy#2778]
When trivy cli is used to scan a kubernetes cluster, only table and json report formats are available. It would be nice to have `html` report format as well becuase it makes it hard to visualise results from json/table when the cluster has more number of services.

**Comment by fatihtokus** [comment]
Hi @mohan-13 ,

I have a trivy plugin(https://github.com/fatihtokus/scan2html) that creates a well-formated filterable/sortable html report for any scan result of trivy.  The usage is very simple, please have a look: 

Install the plugin: $ trivy plugin install github.com/fatihtokus/scan2html
$ trivy scan2html k8s --report=all cluster result.html

Regards!

**Comment by itaysk** [comment]
@mohan-13 we are trying to limit the variety of outputs supported by trivy and to encourage the community to create output plugins. you can use the scan2 html plugin suggested here. 
in the future we will add support for extensible outputs as plugins. this is tracked in https://github.com/aquasecurity/trivy/issues/4860
