### ISSUE TITLE
Provide signatures for binaries in releases

### ISSUE THREAD

**Issue by JAORMX** [aquasecurity/trivy#2788]
We'd like to start verifying signatures coming from Trivy releases, but currently are unable to do so given that binaries not being signed.

There is already signatures in place for container manifests, so we could leverage cosign as well for this.

**Comment by itaysk** [comment]
@JAORMX If I may ask, I'm interested in why checksums did not suffice for this use case (not that it'll affect this welcome addition, just for my education)

**Comment by JAORMX** [comment]
> @JAORMX If I may ask, I'm interested in why checksums did not suffice for this use case (not that it'll affect this welcome addition, just for my education)

Sure! The main thing is being able to verify this from the immutable transparency log. Checksums ate great for verifying integrity, but having a public and trusted record that I can use to do verification helps me sleep at night.
