### ISSUE TITLE
Add option to authenticate against github in order to prevent ratelimiting

### ISSUE THREAD

**Issue by wargamez** [aquasecurity/trivy#280]
https://developer.github.com/v3/#rate-limiting

We are currently hit by this problem, when the trivy is trying to check for  new version of the database, it would be nice if you implemented the possibility to set auth keys as described in the doc above

**Comment by knqyf263** [comment]
@wargamez Thank you for telling me. This is a critical problem. I'm going to fix it as soon as possible.
