### ISSUE TITLE
Deploy trivy for concurrent scanning in k8s

### ISSUE THREAD

**Issue by MprBol** [aquasecurity/trivy#2802]
Hi,

I would like to deploy Trivy in an efficient way in a k8s cluster, enabling concurrent scanning. We have 2000+ docker images and gitlab repositories to scan, and simply starting a trivy instance for each image/repository is not my preferred solution.

How can i most efficiently do this?

I tried the following:

* Start multiple instances of trivy in standalone mode. This does not work, as Trivy can only run one scan at a time. Eventually, a Trivy standalone instance will fail with "context deadline exceeded"
* Run trivy in server mode with Redis as backend cache. Just like trivy in standalone, it seems Trivy still fails with "context deadline exceeded". Additionally, there doesnt seem to be any rate limiting configured in Trivy server mode. So i worry it might just crash when dealing with many trivy clients. 

An alternative option would be to make use of a [PubSub](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern). Publish "work" and create a  newTrivy standalone docker container per task in the PubSub - while limiting the amount of tasks that can execute concurrently. This will likely result in Trivy having to download the vulndb multiple times, and overhead in having to start+teardown a docker container for each and every task.

Is there a better approach? How did other people did this ?

**Comment by josedonizetti** [comment]
@MprBol have you considered using trivy-operator? https://github.com/aquasecurity/trivy-operator 
It does run concurrent scans, but also within a limit to not overwhelm your cluster. It will created a job per resource deployed, scan  vulnerabilities, secrets, and misconfigurations, but this can configured.

**Comment by MprBol** [comment]
hi @josedonizetti , it looks very interesting. I had not seen trivy operator before.

In this case the use case is to automatically scan all of our gitlab repositories for secrets. Using Gitlab API, I request all repositories which were recently updated, scan them via Trivy, collect the results, and post them in our central vulnerabilities database for further processing.  Additionally, our k8s cluster has some security constraints. Im not entirely sure if we can run trivy-operator as is. 

A colleague of mine is looking into scanning k8s workloads automatically, i forwarded trivy-operator to him!

**Comment by MprBol** [comment]
( in the end we've created a trivy container spawning solution ourselves )
