### ISSUE TITLE
Detecting vulnerabilities for pip-installed packages?

### ISSUE THREAD

**Issue by michel-thebeau-WR** [aquasecurity/trivy#283]
Hi,
This is a question

I was trying to determine if Trivy is reporting vulnerabilities in packages installed with 'pip install'.  The README is referring to python safety-db but the context of that is "application dependencies".  Something installed by pip is probably classified under "OS Packages".

Thanks for your answers.

---

I think my answer is 'no', unless there's something about those lock files for application dependencies which I have misunderstood.  I'm looking at scanning container images which I have not myself created.  I added the lock files from trivy-ci-test into a container image and ran trivy ; I think all that I did was get trivy to report on the list of packages/versions in those lock files.

Michel

**Comment by knqyf263** [comment]
Trivy doesn't detect vulnerabilities of pip-installed packages since Trivy just checks a lockfile for now. In the case of python, you need to use Pipenv or Poetry.

**Comment by michel-thebeau-WR** [comment]
@knqyf263 Thank you

**Comment by suhalvemu** [comment]
Is this issue still open?  I am facing an issue where python requests package as vulnerability which X-Ray was able to identified but trivy doesn't. Is there anything I am missing to understand?

**Comment by michel-thebeau-WR** [comment]
The issue is in closed state.  The response at that time was that trivy does not report bugs in packages installed by pip.  If the python package is installed by another package manager that trivy supports then it is reasonable to expect that trivy may correctly report a defect for that package type.

M

________________________________

**Comment by knqyf263** [comment]
This issue was opened almost four years ago, and Trivy now supports pip packages.
https://aquasecurity.github.io/trivy/v0.43/docs/scanner/vulnerability/language/python/

@suhalvemu If you're facing an issue, please open a discussion.
