### ISSUE TITLE
Support yarn "resolutions"/ npm "overrides" in package.json

### ISSUE THREAD

**Issue by mastacheata** [aquasecurity/trivy#2831]
It would be great if trivy could honor the resolutions/overrides keys for yarn/npm selective dependency resolution.
These are used to override nested dependencies when you can't/don't want to update the top-level package respsonsible for requiring it.
As of right now, trivy only checks the dependencies key in package.json, but ignores any overrides/resolutions specified to replace subdependencies.

References:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json/#overrides  
https://github.com/npm/rfcs/blob/main/accepted/0036-overrides.md  
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by laymain** [comment]
could this issue be re-opened?

**Comment by mastacheata** [comment]
I don't think there's any chance of success with reopening. 
It seems like the company (Aqua Security) isn't using the GitHub issues for tracking feature requests, but rather only respond to bugs/errors found by users in the open source repo and ignoring feature requests here.

That's well within their rights, but it could be better documented to align expectations.
