### ISSUE TITLE
trivy config scanning does not detect tar'ed dependency Helm charts

### ISSUE THREAD

**Issue by JAORMX** [aquasecurity/trivy#2850]
## Description

When using `trivy config .` or `trivy fs --security-checks config .` to scan a directory with helm charts, trivy ignores the directory and is not able to scan.

## What did you expect to happen?

Trivy to return configuration issues in helm charts with tar'ed dependencies.

## What happened instead?

Trivy doesn't detect any configuration files.

## Output of run with `-debug`:

```bash
$ trivy fs --security-checks config -d .
2022-09-08T19:59:28.534+0300	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-09-08T19:59:28.577+0300	DEBUG	cache dir:  <redacted>
2022-09-08T19:59:28.577+0300	INFO	Misconfiguration scanning is enabled
2022-09-08T19:59:28.652+0300	DEBUG	OS is not detected.
2022-09-08T19:59:28.652+0300	INFO	Detected config files: 0
```

## Output of `trivy -v`:

```
Version: 0.31.3
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-08-31 12:08:27.060697172 +0000 UTC
  NextUpdate: 2022-08-31 18:08:27.060696772 +0000 UTC
  DownloadedAt: 2022-08-31 15:14:00.670222 +0000 UTC
```

**Comment by owenrumney** [comment]
To add some additional context - this is sub charts in the `charts` dir that aren't being indentified when the check for dependencies is performed. 

In this example, the chart refers to `common` but the file in `charts` is tarred as `common-1.6.tar.gz`

I think we're going to need to explode all tars that are found in the dir hierarchy, I don't think it's going to be too challenging to resolve

**Comment by WatcherWhale** [comment]
Is it correct that trivy now scans double once in the tar with the dependency values and then with the parent chart values?
