### ISSUE TITLE
How Trivy DB update works ?

### ISSUE THREAD

**Issue by daliaezt** [aquasecurity/trivy#2870]
Hi team !

we are running Trivy scanner behind a proxy, we need to know which Websites are being searched by Trivy to get CVE information ? In order to whitelist these specific sites in our proxy config. 
Also, we need more info about how Trivy stores CVE data ?

Thanks.

**Comment by knqyf263** [comment]
You can refer to [this page](https://aquasecurity.github.io/trivy/v0.31.3/docs/advanced/air-gap/). It also mentions allowlist.

**Comment by daliaezt** [comment]
@knqyf263 sorry i cannot find allowlist in the attached page . Can you provide me direct link to it ?
