### ISSUE TITLE
Bulk search for Rekor entries

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#2892]
Currently, the `--sbom-sources` flag tries to fetch Rekor log entries one by one, but it could be slow when there are a lot of entries. Seems like several entries can be obtained at once.
https://github.com/sigstore/rekor/blob/689924f1035cd10b1db62e1828806f37469a559d/openapi.yaml#L213-L235

**Comment by knqyf263** [comment]
@otms61

**Comment by otms61** [comment]
Alright, I'll try
