### ISSUE TITLE
Add shell completion

### ISSUE THREAD

**Issue by LucasVanHaaren** [aquasecurity/trivy#2896]
Hello everybody,

I was searching through docs if there is any way to get shell completion (in my case bash shell) for the trivy cli.
I think this feature does not exists for now.

I know trivy is mainly used in CI-CD automated pipelines but because some commands have a lot of options, I think it will be a great feature while using manually ! :smiley:

**Comment by knqyf263** [comment]
We use cobra, so I suppose we could easily achieve that.
https://github.com/spf13/cobra/blob/main/shell_completions.md

**Comment by didiermichel** [comment]
Hello,
I would like to work on this subject if available.

**Comment by ShubhamPalriwala** [comment]
Hey @didiermichel, I'm interested to work on this, let me know if you need any kind of help or want me to take this up! Would be happy to help in any way possible.

**Comment by ShubhamPalriwala** [comment]
@didiermichel since you have already started researching, please go ahead! Let me know if I can help in anyway possible :))
All the best

**Comment by titanventura** [comment]
Hey @didiermichel. Are you still working on this issue. If not , i would like to take this up !
