### ISSUE TITLE
trivy image --security-checks config IMAGE_NAME

### ISSUE THREAD

**Issue by Kilz78** [aquasecurity/trivy#2907]
Hi, 

I'm studying how to scan for misconfiguration for some docker images.

I can see in the documentation of trivy that we are able to scan for config on docker images like that : 
`$ trivy image --security-checks config IMAGE_NAME` (https://aquasecurity.github.io/trivy/v0.32/docs/misconfiguration/scanning/)

built-in policies are stored here : https://github.com/aquasecurity/defsec/tree/master/internal/rules/docker/policies

But when I'm trying to execute this command : 
`trivy image <IMAGE_NAME> --security-checks config --config-policy <PATH_TO_CONFIG_FILES>`

I got : 
`2022-09-19T14:08:19.209Z        INFO    Misconfiguration scanning is enabled
2022-09-19T14:08:19.702Z        INFO    Detected config files: 0`

But this image run without any USER instead of ROOT, with ADD commands insted of COPY etc... If I run the same test on the Dockerfile I have what I need to see : 

`HIGH: Specify at least 1 USER command in Dockerfile with non-root user as argument` etc...

**CONTEXT :** 
I would like to scan this image for security compliance before to upload it to my private repository. I have a lot of clients, so I can't ask them to give me all Dockerfile etc.. The goal is to automate this operation during the CVE scan.

Any help please ?

**Comment by itaysk** [comment]
This command will scan the files within the container image for misconfigurations. For example, if the image contains a Kubernetes definition file, this file will be scanned for Kuberentes misconfigurations. The `--config-policy` flag is used to specify custom policies that you want to check, I'm not sure you needed it.
Anyway, this command does not scan the dockerfile that was used to generate the image, if that is what you expected. This feature may come in the future and is tracked here https://github.com/aquasecurity/trivy/issues/2676

**Comment by Kilz78** [comment]
@itaysk thanks you very much for those information ! I’m looking to found something similar of my need since few days/months.

I’m working for one financial company that really needs this feature. If I can, I can also give some helps to develop/test this.
