### ISSUE TITLE
Broken Link in ReadMe.md

### ISSUE THREAD

**Issue by techmaharaj** [aquasecurity/trivy#2913]
The integrations link in the [readme.md](https://github.com/aquasecurity/trivy/blob/main/README.md) is broken, leads to HTTP 404 instead of the integrations page. Below is the line where the broken link is.

- See [integrations](https://aquasecurity.github.io/trivy/latest/docs/integrations/) section in the documentation. [Broken Link]

I suppose it should redirect to https://github.com/aquasecurity/trivy/tree/main/docs/tutorials/integrations

**Comment by DmitriyLewen** [comment]
Hello @techmaharaj 
Thanks a lot for your report!

[PR](https://github.com/aquasecurity/trivy/pull/2931) to fix this has been created.

Regards, Dmitriy
