### ISSUE TITLE
Git clone failure for repository scan

### ISSUE THREAD

**Issue by awakenine** [aquasecurity/trivy#2921]
## Description
I got the following error trying to scan remote repo
`2022-09-20T13:51:54.034Z	FATAL	repository scan error: scan error: unable to initialize a scanner: unable to initialize a filesystem scanner: git clone error: write /tmp/fanal-remote183400706/libs/tsconfig.lib.json: no space left on device`

Tmp dir cannot be changed in running options, because it is hardcoded.
[	tmpDir, err := ioutil.TempDir("", "fanal-remote")](https://github.com/aquasecurity/trivy/blob/e393ce1477901ea566b43ccd2d29a239c1a4c7e8/pkg/fanal/artifact/remote/git.go#L34)

It happens because I'm using tmpfs on my server and repository size is huge, so I would like to change this tmp path.

## What did you expect to happen?

Possibility to provide tmp dir as a run argument instead

**Comment by knqyf263** [comment]
You can overwrite the cache dir via `TMPDIR`.
https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/os/file_unix.go;drc=86ca550f407827f620e6c8314ec503fdb48dd898;l=338

**Comment by knqyf263** [comment]
@afdesk Would you add this note to our troubleshooting?
https://aquasecurity.github.io/trivy/v0.32/docs/references/troubleshooting/
