### ISSUE TITLE
More flexible source of software packages

### ISSUE THREAD

**Issue by netrounds-fredrik** [aquasecurity/trivy#293]
I'm looking into using trivy to scan dependency files (yarn.lock, requirements.txt, etc.) as well as software installed in VM images. It seems like trivy would be able to do both of these, but it currently requires me to convert the VM image and add my dependency files to a dummy docker image.

Would it be possible to make trivy more flexible in what it's scanning. In it's simplest form, I like to be able to pass trivy a list of software packages and their versions. Next level would be to pass a filesystem and let trivy detect the installed software. And the final level would be to pass trivy a docker image, like today.

Is there some technical reason this would not be possible?

**Comment by chezou** [comment]
Supporting requirements.txt and constraints.txt would be a great option. 

pip can manage installed packages using `constraints.txt` like:

```
(venv)$ pip freeze -l
numpy==1.13.1
pandas==0.20.3
pkginfo==1.4.1
pytest==3.2.0
python-dateutil==2.6.1
pytz==2017.2
(venv)$ pip freeze -l > constraints.txt
(venv)$ cat requirements.txt
pandas
numpy
(venv)$ pip install -r requirements.txt -c constraints.txt
```

See also: https://chezo.uno/blog/2017-08-30_python-basics-package-management-462918458f96/#managing-package-version

**Comment by netrounds-fredrik** [comment]
It seems like steps has been taken in this direction with the new server/client mode introduced in https://github.com/aquasecurity/trivy/pull/295 where the server has a GRPC interface where you can, from a list of packages, get a list of vulnerabilities (see https://github.com/aquasecurity/trivy/blob/master/rpc/detector/service.proto).

So I could now write my own GRPC client and use the server mode, but I still think that it would make sense to expose this functionality in the trivy CLI as well.

**Comment by ArjonBu** [comment]
@netrounds-fredrik  how did you accomplish that?

**Comment by netrounds-fredrik** [comment]
@ArjonBu, I have not done this in practice, and it seems like the gRPC API has become more complicated to use now compared to what it was initially (https://github.com/aquasecurity/trivy/blob/74717b888e2af41d8cf71b85e787966e487ebe6b/rpc/detector/service.proto).

Without digging too much into how the current gRPC API works, it seems like you first have to call `PutArtifact`, which I think would normally correspond to a container image, and `PutBlob` which I think would normally correspond to a image layer and there you can specify the list of distro packages (`PackageInfo`) and Python/JS/etc. libraries (`Application`). The `Scan` rpc then takes the stored artifact and blob ID as argument.

As I initially wrote in this issue, I think that it would be good to have and API and CLI that is more flexible and not only focused on working with containers.

**Comment by fredde-fisk** [comment]
This has been fixed in https://github.com/aquasecurity/trivy/pull/2203 (https://github.com/aquasecurity/trivy/issues/1164). Please close.

**Comment by knqyf263** [comment]
Thanks for the heads-up.
