### ISSUE TITLE
Can the code be included in another project?

### ISSUE THREAD

**Issue by 030** [aquasecurity/trivy#2938]
I would like to scan a library by Trivy when my code downloads an artifact. Is this possible? If true, what code should be called?

**Comment by knqyf263** [comment]
You can use exported functions in Trivy, but it is not designed to be used as a library. It may break compatibility.

**Comment by 030** [comment]
Use case:

- In the code, a JAR file is downloaded
- Once downloaded this file has to be sent to Trivy
- If a vulnerability is detected, the app will stop and the user has to inspect the file

What call is required to make this work? Could you provide a code snippet?
