### ISSUE TITLE
Fetch db as a container from registry

### ISSUE THREAD

**Issue by mrueg** [aquasecurity/trivy#294]
In an airgapped environment, the container registry is a nice artifact storage that offers a strict control on what enters it and what not. While I'm aware that this is scriptable, it would be useful if trivy had an option built-in to fetch their db as a container image. (building and pushing would be optional, but i think other tools could provide that).

**Comment by knqyf263** [comment]
Thank you for opening the issue. Let me know a use case for this feature because trivy already fetches a database file automatically.

**Comment by mrueg** [comment]
Trivy should have an option to fetch a database from different sources (e.g. local file system or in this case a registry, similar to https://hub.docker.com/r/arminc/clair-db).

This allows to run trivy inside an airgapped environment that only can access a container image registry.

**Comment by lyuboraykov** [comment]
+1
I'm an engineer in Mirantis and we have this use case.
We want to provide our customers image security scanning but many of them have airgapped environments (lacking internet connection).
It would be great if there is a mechanism to provide the update repository on the file system or something similar.

**Comment by knqyf263** [comment]
@mrueg I see. Thank you for explaining it. We're reviewing https://github.com/aquasecurity/trivy-db/pull/22. Just a moment, please.

@lyuboraykov Thank you for the comment. In your case, can your customers download an image from a container registry?

**Comment by lyuboraykov** [comment]
@knqyf263 yes, that would work for us.

**Comment by knqyf263** [comment]
We merged https://github.com/aquasecurity/trivy-db/pull/22. Thanks a lot, @mrueg. Next, we have to build this DB in Docker Registry such as DockerHub.
