### ISSUE TITLE
support exporting HTML or PDF reports?

### ISSUE THREAD

**Issue by Changego** [aquasecurity/trivy#2944]
Hello, excuse me.

Can I support exporting HTML or PDF reports?

**Comment by DmitriyLewen** [comment]
Hello @Changego 
Thanks for your interest to Trivy!

Trivy currently only supports exporting reports to html format.
More information about html format [here](https://aquasecurity.github.io/trivy/v0.32/docs/vulnerability/examples/report/#html).
P.S. Don't forget to download [html template](https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl).

Regards, Dmitriy

**Comment by Changego** [comment]
Thank you very much. It's done
