### ISSUE TITLE
feat(helm): configure service port independent of container port

### ISSUE THREAD

**Issue by elchenberg** [aquasecurity/trivy#2957]
I would like to use port 80 as the service port but keep the default container port (or use any other unprivileged port as container port) because I am not very good at remembering (seemingly) random port numbers. It is much easier to remember the address of the Trivy server as http://trivy.trivy.svc than remembering http://trivy.trivy.svc:4954. I do not want to use the privileged port 80 as container port though (and even if I wanted, the container would fail to start with the following error: `FATAL   listen tcp 0.0.0.0:80: bind: permission denied`).

With the current Helm chart I can only configure the `.service.port` value and this will be used for service's port, the service's targetPort and for the container's port:

- https://github.com/aquasecurity/trivy/blob/v0.32.1/helm/trivy/templates/service.yaml#L15-L16
- https://github.com/aquasecurity/trivy/blob/v0.32.1/helm/trivy/templates/statefulset.yaml#L100

**Comment by dbirks** [comment]
Yeah I agree, being able to set port 80 for the service is quite nice to have. I can't remember what each app's port is otherwise. Just submitted a PR to fix :wrench:

**Comment by sparkacus** [comment]
This is quite an important request.

Although I haven't created helm charts myself, it seems a bit odd for the port defined specifically for a service to be forcefully reused as the port the container binds to. If I define the 'service' port I expect that to be the service only, at least that's my opinion.

There are often various reasons why the ports need to be different. Routes to a kubernetes service can be from many directions e.g. internally, externally etc. I'm now hitting the same issue in that all our CI builds point to the local kube service DNS and we don't define a port as we're happy to use port 80. I have no problem with the container binding to a high value port, but I need the service to route on port 80.
