### ISSUE TITLE
credentials file for several private registries

### ISSUE THREAD

**Issue by SBatais** [aquasecurity/trivy#2958]
I would like to know if trivy can handle a credentials file that contains the credentials of several private docker registries (like docker used .docker/config.json). 
I know that trivy can access to a private registry by using env variables, but it's limited to one private registries
Thanks in advance.

**Comment by SBatais** [comment]
Hello
Can I have an update for this issue ?
Thanks in advance

**Comment by knqyf263** [comment]
Trivy reads `.docker/config.json`. You can configure credentials via `docker login`.

**Comment by knqyf263** [comment]
Also, we added support for multiple credential pairs in v0.39.0.
https://aquasecurity.github.io/trivy/v0.39/docs/advanced/private-registries/
