### ISSUE TITLE
Does Trivy have an exit code?

### ISSUE THREAD

**Issue by huornlmj** [aquasecurity/trivy#2959]
When I run Trivy and get a clean scan, I get an error code of 0.  If I scan and I get errors I also get a 0.  Is there actually an error code feature?

**Comment by DmitriyLewen** [comment]
Hello @huornlmj 
Thanks for your interest to Trivy!

If you need exit-code you can use `--exit-code` flag.
More information about supported flags [here](https://aquasecurity.github.io/trivy/v0.32/docs/references/cli/image/).

Regards, Dmitriy

**Comment by huornlmj** [comment]
Thanks @DmitriyLewen .  That answers my question.  I had originally ran
```console
$ trivy --help | grep -i exit
```
Expecting to see a tool-wide exit code mention in the help and didn't find one, hence the question.  But I now see each scan type has it's own exit-code option:

```console
$ trivy image --help | grep -i exit
    --exit-code int          specify exit code when any security issues are found.
```
