### ISSUE TITLE
Please provide instructions on how to verify the binary file downloads

### ISSUE THREAD

**Issue by nicolaevladescu** [aquasecurity/trivy#2963]
I cannot seem to be able to verify a deb using it's .sig and .pem files, I tried with openssl and gpg.

Can you give more details please?

Thank you.

**Comment by nicolaevladescu** [comment]
I figured it out by browsing the source code.

1. Install [cosign](https://docs.sigstore.dev/cosign/installation)
2. Download an artifact and it's `.sig` and `.pem` files.
3. Run `COSIGN_EXPERIMENTAL=1 cosign verify-blob artifact --signature artifact.sig --certificate artifact.pem`

Thanks.

**Comment by tschroeder13** [comment]
Hey, unfortunately this is no longer working:

```
.\cosign-windows-amd64.exe verify-blob .\trivy_0.52.0_Linux-64bit.tar.gz --signature .\trivy_0.52.0_Linux-64bit.tar.gz.sig --
certificate .\trivy_0.52.0_Linux-64bit.tar.gz.pem
Error: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
main.go:74: error during command execution: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode

```

**Comment by nikpivkin** [comment]
Hi @tschroeder13 !

Did you follow the instructions in the documentation?
https://aquasecurity.github.io/trivy/v0.52/getting-started/signature-verification/

**Comment by tschroeder13** [comment]
Argh, ... too obvious, sorry.

Thank you for the hint!
