### ISSUE TITLE
Pull Trivy database not over GitHub Api to avoid rate limits

### ISSUE THREAD

**Issue by JulianSchmidgall** [aquasecurity/trivy#299]
Our scan is currently failing, because it is running into a rate limit of the GitHub Api while updating the database. For us it is difficult to add a GitHub-Token. Therefore it would be helpful to have the Trivy database somewhere else hosted, where no rate limit exists.

**Comment by knqyf263** [comment]
@JulianSchmidgall Thank you for reporting an issue. If you know a good free service for hosting files, let me know, please. For now, you can download DB from GitHub daily and sync it to AWS S3 or something like it. When using Trivy on CI, you download DB from S3 and copy it under the cache directory.

**Comment by knqyf263** [comment]
If someone has any ideas, please reopen this issue.

**Comment by dmpe** [comment]
Facing the very same issue. 
Now have to wait for 10 minutes...

**Comment by hemikak** [comment]
@knqyf263, Where is this cache directory ?

I am facing this issue. More like a blocker to me. I am running on travis.

**Comment by knqyf263** [comment]
First of all, if you can set `GITHUB_TOKEN`, you should do it. 

The cache dir depends on the environment. You can check it with `--cache-dir` option.

```
$ trivy -h | grep cache-dir
  --cache-dir value           cache directory (default: "/Users/teppei/Library/Caches/trivy")[$TRIVY_CACHE_DIR]
```

**Comment by hemikak** [comment]
I moved running my security scans from travis to github actions because jobs in github actions are already equipped with a github token. Refer https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

Example:
```bash
GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./trivy --exit-code 1 --severity HIGH --no-progress <docker_image_name>
```

**Comment by tianon** [comment]
I haven't looked into the code that does this updating, but my understanding is that it's downloading files from releases on https://github.com/aquasecurity/trivy-db/releases?  Couldn't something like `git ls-remote --tags https://github.com/aquasecurity/trivy-db.git`, sorted numerically, then tried in order until there's a successful download work?  That should bypass the GitHub API limits. (Perhaps even only as a fallback after hitting the API limits?)

**Comment by jgimenez** [comment]
Maybe @cloudflare could be interested in hosting this? Just a suggestion.
