### ISSUE TITLE
how to get details from "trivy aws" scan

### ISSUE THREAD

**Issue by ozbillwang** [aquasecurity/trivy#2995]
follow up this document to get the aws scan summary from command `trivy aws --region <region_name>`

https://aquasecurity.github.io/trivy/v0.31.3/docs/cloud/aws/scanning/

But if I want to know what are misconfigurationed? how to check?

![image](https://user-images.githubusercontent.com/8954908/194055585-11f3bcbe-3478-42df-994f-43884826d60e.png)

from above sample, there are 737 miconfigurations in ec2, but no detail about them

by the way, if possible, could trivy also provide with remediation as well.

**Comment by dbirks** [comment]
Sharing a workaround I've been using in the meantime... you can change the output format to sarif, and use another cli tool like sarif-fmt (docs [here](https://docs.rs/crate/sarif-fmt/latest)) to view it in a nicer format:

```
trivy aws --service cloudfront --format sarif | sarif-fmt
```

![image](https://user-images.githubusercontent.com/7545665/195423103-f42c7607-aba3-4033-a991-ac074440467a.png)

**Comment by ozbillwang** [comment]
thanks, @dbirks 

I am not good at Rust. But I did it with container way.

```
$ cat Dockerfile

FROM rust:alpine

RUN apk add --update --no-cache build-base

RUN cargo install sarif-fmt

ENTRYPOINT sarif-fmt

$ docker build -t sarif-fmt .

$ alias sarif-fmt="docker run -i --rm sarif-fmt"

$ trivy aws --service ec2 --format sarif |sarif-fmt
```

**Comment by ozbillwang** [comment]
So the way with Sarif-fmt is nice output for human readible, otherwise, with `--format json` I can see all details already. 

```
  -f, --format string          format (table, json, sarif, template, cyclonedx, spdx, spdx-json, github, cosign-vuln) (default "table")
```
If we can add a new format to export as HTML file, that would be better.

**Comment by knqyf263** [comment]
You need to specify ARN to display the details.
https://aquasecurity.github.io/trivy/v0.32/docs/cloud/aws/scanning/

**Comment by ozbillwang** [comment]
@kenXengineering 

Thanks for the document, but the way is not convenient.

Anyway I got what I need. 

thanks.
