### ISSUE TITLE
alert if a base OS is EOL and ignore option for Pipeline usage

### ISSUE THREAD

**Issue by mcasviper** [aquasecurity/trivy#2996]
I scanned a Container Image based on php:7.0 which is definitely very old. I scanned with --ignore-unfixed and got no warnings. I think this is because the underlaying OS is EOL and there are no new packages for it.
My idea /  feature request would be a hint for this situation like "0 WARN 0 HIGH 0 CRIT - Your base OS is EOL. There might be open issues which are not correctly detected" with an option to make EOL images fail in CI Pipelines or better it fails by default and --ignore-eol makes it go through it.

**Comment by cupello** [comment]
Hello!

I think it would be easier if we had something like: ignore unfixed if it is NOT X days old. What do you think?

**Comment by mcasviper** [comment]
Hi @cupello 
thanks for your response. I understand that this would be easier but how reliable would it be? What would "not x days old" mean? Will it be x days since last update for this OS?

**Comment by knqyf263** [comment]
We can add `--fail-on-eol` or something like that.
