### ISSUE TITLE
Unable to build trivy from source

### ISSUE THREAD

**Issue by vanshaj** [aquasecurity/trivy#3005]
Unable to build trivy from main branch source code.

I took the latest code from the trivy repository and tried to build the trivy using 
`go build ./cmd/trivy/`

But after downloading some dependencies, it hangs and doesnot generates a binary. I am using below versions
golang - 1.19
OS - Ubuntu 20.04

## What did you expect to happen?
Trivy should build and generate a proper binary

## What happened instead?
It gets hanged after downloading some dependencies at 
`github.com/matttproud/golang_prootobuf_extensions v1.0.2-0.20181231171920-c182affec369`

![image](https://user-images.githubusercontent.com/7772741/194852527-43ec316c-bfb7-465d-ba43-3739520a60ea.png)

**Comment by dbirks** [comment]
Hm I'm having trouble duplicating this on my end. 

golang: 1.19.2
OS: NixOS

Can you run `go mod tidy` successfully? I'm not sure what the error is trying to download that dependency.

**Comment by vanshaj** [comment]
Hello @dbirks,

Yes I am able to execute `go mod tidy` successfully but after that when i execute `go build`, it hangs. 

Using 
golang: 1.19.2
OS : Ubuntu 20.04

Can you provide some help?

Thanks
