### ISSUE TITLE
Missing Legend in Readme for Comparison with other scanners

### ISSUE THREAD

**Issue by ggeldenhuis** [aquasecurity/trivy#301]
The Comparison with other scanners section does not appear to contain a legend that explains what the various symbols mean. Would be handy to know, how to interpret the various symbols in the comparison table.

**Comment by gknepper** [comment]
According to google the symbols stands for:

| Symbol  |  Meaning  | Assumed Value  | 
|---|---|---|
| ◎ | Bullseye  | Best  | 
| △ | Cool  |  Good | 
| ◯  | OK   |  OK | 
| ×  | None/Null | Not present  |  

| Scanner        | OS<br>Packages | Application<br>Dependencies | Easy to use | Accuracy | Suitable<br>for CI |
| -------------- | :------------: | :-------------------------: | :---------: | :------: | :-------------------: |
| Trivy          |       OK           |              OK                |      OK         |    Best       |           OK              |
| Clair          |       OK           |        Not present        |      Good       |    OK        |           Good            |
| Anchore Engine |       OK          |              Good           |      Good       |    OK        |           Good            |
| Quay           |       OK           |       Not present          |      OK         |    OK        |    Not present         |
| MicroScanner   |       OK           |      Not present         |      OK         |    OK        |           OK              |
| Docker Hub     |       OK           |       Not present       |      OK         |    Not present    |      Not present        |
| GCR            |       OK           |        Not present         |      OK         |    OK        |       Not present        |

**Comment by knqyf263** [comment]
Thanks. I'll update it.
