### ISSUE TITLE
CycloneDX output does not fill type value string

### ISSUE THREAD

**Issue by security101** [aquasecurity/trivy#3023]
## Description

When using the cyclonedx output does not always provide a valid value for the component item type, which isn't compliant with the cyclonedx spec. (see https://cyclonedx.org/docs/1.4/json/#components_items_type) . Importing the sbom file to Dependency Track v4.6.0 to analyze the resulting output throws an exception regarding the type field is empty means "".

trivy added components identified in the /etc/ssl directory (secrets) to the cyclonedx output but does not provide a valide type. It leave it empty.

## What did you expect to happen?

    {
      "type": "**file**",
      "name": "/etc/ssl/private.key",
      "properties": [
        {
          "name": "aquasecurity:trivy:Type",
          "value": ""
        },
        {
          "name": "aquasecurity:trivy:Class",
          "value": "secret"
        }
      ]
    }

## What happened instead?

    {
      "type": "",
      "name": "/etc/ssl/private.key",
      "properties": [
        {
          "name": "aquasecurity:trivy:Type",
          "value": ""
        },
        {
          "name": "aquasecurity:trivy:Class",
          "value": "secret"
        }
      ]
    }

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
(paste your output here)
```

## Additional details (base image name, container registry info...):

envoyproxy/envoy-alpine:v1.20-latest

**Comment by msymons** [comment]
@masahiro331, when the import problem into Dependency-Track was being discussed (a discussion that led to this issue being logged) it was mentioned that the trivy version was:  **v0.30.3**

@security101, is that still valid?

**Comment by msymons** [comment]
Here we go...  discussion URL:

**Comment by nscuro** [comment]
> Trivy does not output secret scan results to the SBOM.

Looks like the code has changed since v0.30.3. In v0.30.3, I think the `secret` result ended up being processed by `resultToCdxComponent`, which had a non-exhaustive `switch` on `r.Class`:

https://github.com/aquasecurity/trivy/blob/fa8a8ba7dc819c502b77f272ff0c239dcff7d9f3/pkg/sbom/cyclonedx/marshal.go#L372-L391

This doesn't appear to be the case anymore in the latest Trivy version. So I guess the fix here is to upgrade Trivy @security101.

**Comment by masahiro331** [comment]
Thank you @nscuro !!!!!

**Comment by security101** [comment]
Thank you all for analyzing the issue. I ask my colleagues to upgrade trivy from v0.30.3 and check again. An update will be provided as soon as I have the results on our side. Have a nice day!

**Comment by masahiro331** [comment]
@security101 

Have a nice day!

**Comment by knqyf263** [comment]
Please feel free to reopen this issue if you're still facing the same problem.
