### ISSUE TITLE
Upgrading golang.org/x/text causes github.com/sigstore/rekor to be downgraded

### ISSUE THREAD

**Issue by tspearconquest** [aquasecurity/trivy#3045]
## Description

I was trying to patch golang/x/text in Trivy today due to a new CVE before submitting a pull request and ran into an issue where rekor is being downgraded.

as per Owen from [slack](https://aquasecurity.slack.com/archives/C02KVB6AED9/p1666196227737919):
> defsec uses 0.3.8 of golang/x/text and something else in trivy is bringing in transitively v0.3.8-0.20211004125949-5bd84dd9b33b - 

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
(paste your output here)
```

**Comment by knqyf263** [comment]
I believe it is not our bug. We're not sure why, but `go get` downgrades rekor...

**Comment by tspearconquest** [comment]
Thanks. I will share my workaround here for documentation purposes:

To get around this, run `go get -u <packages> <rekor package>` by replacing `<packages>` with the packages you want to upgrade and replacing `<rekor package>` with the rekor package @version that is currently listed in `go.mod`. For example with Trivy v0.32.1:

`go get -u golang.org/x/text@v0.3.8 github.com/sigstore/rekor@v0.12.0`

**Comment by tspearconquest** [comment]
I'm okay with closing this out as "not planned/won't fix" if you are okay with it also @knqyf263. Thanks for the update.
