### ISSUE TITLE
Select scan socket (containerd, podman, docker)

### ISSUE THREAD

**Issue by pmengelbert** [aquasecurity/trivy#3049]
Currently, in `pkg/fanal/image/image.go`, the provided container image will be resolved by first the docker daemon, then podman, then containerd, then remote. It would be helpful if there were some way to configure, from the CLI or a config file, which socket(s) to attempt. The current logic is preferential and somewhat confusing.

If there is a place that this can be configured already, it would be helpful to know where -- I didn't find it documented anywhere.

**Comment by knqyf263** [comment]
We don't have an option for that. What if adding `--container-engine`?

**Comment by pmengelbert** [comment]
@knqyf263 That sounds like a good solution to me

**Comment by knqyf263** [comment]
OK. I'll leave it for contributors for the time being.

**Comment by blueskyson** [comment]
I'm interested in this issue but I haven't used any image clients other than Docker before...

**Comment by itaysk** [comment]
from @knqyf263 in https://github.com/aquasecurity/trivy/issues/4044#issuecomment-1505710476:

I have an idea about the selection of image sources. We are supposed to implement it in v0.41.0.
https://github.com/aquasecurity/trivy/issues/3929

I suggest allowing users to specify the priority of runtimes.

# Force remote scanning
$ trivy image --image-from remote XXX

# Force containerd scanning
$ trivy image --image-from conatinerd XXX

# Prefer remote images and disable podman
$ trivy image --image-from remote,docker,containerd XXX
