### ISSUE TITLE
Integrate trivy into Go Projects

### ISSUE THREAD

**Issue by himywei** [aquasecurity/trivy#3078]
Hi, when i integrate trivy into my go projects,  the executable file after compilation is too large. Is there any good way to solve this problem? thanks.

**Comment by knqyf263** [comment]
What is the executable file? Do you mean the Trivy binary?

**Comment by himywei** [comment]
yes, due to too many dependencies on trivy, the binary file is too large.

**Comment by knqyf263** [comment]
You can try `upx` to compress the binary. We don't have any other way for now.

**Comment by himywei** [comment]
I ‘ve tried, but the way is not appropriate for me. Thanks a lot !
