### ISSUE TITLE
Provide a clear warning that only Trivy generated SBOMs will return vulnerabilities

### ISSUE THREAD

**Issue by ChaosInTheCRD** [aquasecurity/trivy#3081]
After feeding an SBOM generated by [Anchore/Syft](https://github.com/anchore/syft) into Trivy with `trivy sbom ./sbom.json`, I discovered that I got no vulnerabilities back, when I was expecting multiple.

After reading https://github.com/aquasecurity/trivy/issues/2934, my suspicions were confirmed that custom SBOM properties generated by trivy are the reason why it can find vulnerabilities from its own SBOMs. I think I am right in saying that therefore Trivy can only assess Trivy generated SBOMs?

At this point, it is very misleading that it does not notify the user of this. Especially considering that in the standard SBOM consumption model, it will be more often than not that the SBOM will not have been generated by Trivy.

Could a warning message of some sort be added to make it clear to the user of this when they supply an SBOM? It seems like it would even be pretty easy to set up functionality that states "oh no, this SBOM was not generated by Trivy, fail.". Unless I am missing something and this problem is way less big than it seems.

If this sounds like a good idea, I am happy to try and tackle the PR!

Thanks 😄

**Comment by L1ghtman2k** [comment]
In my case, I got error: `sbom scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: failed to scan application libraries: failed vulnerability detection of libraries: failed to initialize a driver: unsupported type alpine`. Still, I would have for sure appreciated a comment that trivy can only scan trivy generated SBOMs

**Comment by knqyf263** [comment]
>I think I am right in saying that therefore Trivy can only assess Trivy generated SBOMs?

No, it is not correct. SBOM spec doesn't have enough fields for accurate vulnerability scanning, so we rely on custom properties. However, the detection itself is still possible though the accuracy of the result could be worse. We need to evaluate how it will be different.

I agree that we should warn when SBOM is not generated by Trivy. It would be appreciated if you contribute to that.

**Comment by ChaosInTheCRD** [comment]
> >I think I am right in saying that therefore Trivy can only assess Trivy generated SBOMs?
> 
> 
> 
> No, it is not correct. SBOM spec doesn't have enough fields for accurate vulnerability scanning, so we rely on custom properties. However, the detection itself is still possible though the accuracy of the result could be worse. We need to evaluate how it will be different.
> 
> 
> 
> I agree that we should warn when SBOM is not generated by Trivy. It would be appreciated if you contribute to that.

Noted, however aren't the fields used for accurate vulnerability scanning the CPE and PURL? I appreciate that aquasec does not use these (as far as I understand)

Will try and get down to add said warnings ☺️

**Comment by knqyf263** [comment]
We use PURL, but it is also missing some necessary fields. For example, rpm-based scanning definitely requires [modularity](https://dnf.readthedocs.io/en/latest/modularity.html) information, but PURL doesn't define that value.
https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#rpm
