### ISSUE TITLE
[CRITICAL] Output uses 'DESCRIBE' not 'DESCRIBES' which doesn't match SPDX spec

### ISSUE THREAD

**Issue by bardenstein** [aquasecurity/trivy#3100]
## Description

SPDX SBOMs generated by Trivy create files that use a field called "DESCRIBE" to describe the asset, whereas the proper SPDX spec uses the field name "DESCRIBES."

Command used: trivy image --format spdx-json --output result.spdx.json alpine:3.15

## What did you expect to happen?
Field name should be "DESCRIBES"

## What happened instead?
SBOM contained a field 

## Output of run with `-debug`:

--

## Output of `trivy -v`:

Version: 0.34.0

**Comment by DmitriyLewen** [comment]
Hello @bardenstein 
Thanks for your report!

I created #3102 to fix this problem.

Regards, Dmitriy
