### ISSUE TITLE
init error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error:

### ISSUE THREAD

**Issue by azeezullah-abdulrasheed** [aquasecurity/trivy#3127]
Trivy version I'm using it:

19:35:55  + /usr/local/bin/trivy --version
19:35:55  Version: 0.32.1
19:35:55  Vulnerability DB:
19:35:55    Version: 2

Below is the error message while the jenkins jobs failed:

19:35:55  + sudo /usr/local/bin/trivy --debug --insecure image rethinkdb:add-trivy-scan-stage-to-jenkinsfile-6 --exit-code 1
19:35:56  2022-11-03T07:05:55.931-0700	[35mDEBUG[0m	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
19:35:56  2022-11-03T07:05:55.933-0700	[35mDEBUG[0m	cache dir:  /root/.cache/trivy
19:35:56  2022-11-03T07:05:55.933-0700	[35mDEBUG[0m	There is no valid metadata file: unable to open a file: open /root/.cache/trivy/db/metadata.json: no such file or directory
19:35:56  2022-11-03T07:05:55.933-0700	[34mINFO[0m	Need to update DB
19:35:56  2022-11-03T07:05:55.933-0700	[34mINFO[0m	DB Repository: ghcr.io/aquasecurity/trivy-db
19:35:56  2022-11-03T07:05:55.933-0700	[34mINFO[0m	Downloading DB...
19:35:56  2022-11-03T07:05:55.933-0700	[35mDEBUG[0m	no metadata file
19:35:56  2022-11-03T07:05:56.174-0700	[31mFATAL[0m	init error:
19:35:56      github.com/aquasecurity/trivy/pkg/commands/artifact.Run
19:35:56          /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:362
19:35:56    - DB error:
19:35:56      github.com/aquasecurity/trivy/pkg/commands/artifact.NewRunner
19:35:56          /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:121
19:35:56    - failed to download vulnerability DB:
19:35:56      github.com/aquasecurity/trivy/pkg/commands/operation.DownloadDB
19:35:56          /home/runner/work/trivy/trivy/pkg/commands/operation/operation.go:117
19:35:56    - OCI artifact error:
19:35:56      github.com/aquasecurity/trivy/pkg/db.(*Client).Download
19:35:56          /home/runner/work/trivy/trivy/pkg/db/db.go:154
19:35:56    - OCI artifact error:
19:35:56      github.com/aquasecurity/trivy/pkg/db.(*Client).initOCIArtifact
19:35:56          /home/runner/work/trivy/trivy/pkg/db/db.go:194
19:35:56    - OCI repository error:
19:35:56      github.com/aquasecurity/trivy/pkg/oci.NewArtifact
19:35:56          /home/runner/work/trivy/trivy/pkg/oci/artifact.go:69
19:35:56    - Get "https://ghcr.io/v2/": EOF

**Comment by walkerxiong** [comment]
Hi @azeezullah-abdulrasheed ,
The most likely cause of your problem is because the server (https://ghcr.io/v2/) closed the connection.
