### ISSUE TITLE
Segfault after aborting DB download

### ISSUE THREAD

**Issue by mattcollier** [aquasecurity/trivy#315]
**Description**
Just installed trivy  0.2.1 on Debian 10.

ran `trivy` command and immediately saw message about downloading DB and within a second or two I hit ctrl-c to abort.  Subsequently, running the trivy command by itself or with --reset flag produced a segfault.  I was able to correct the problem by removing `~/.cache/trivy`

**What did you expect to happen?**
I would expect a corrupt/incomplete DB download to resume or perhaps provide instruction for using the --reset flag (which of course should work)

**What happened instead?**
matt@september2015:~$ trivy
unexpected fault address 0x7f82fed68008
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f82fed68008 pc=0x526ed7]

goroutine 1 [running]:
runtime.throw(0xdccb18, 0x5)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00025b580 sp=0xc00025b550 pc=0x42e442
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc00025b5b0 sp=0xc00025b580 pc=0x442f1e
github.com/etcd-io/bbolt.(*freelist).read(0xc0003f0780, 0x7f82fed68000)
	/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/freelist.go:265 +0x37 fp=0xc00025b640 sp=0xc00025b5b0 pc=0x526ed7
github.com/etcd-io/bbolt.(*DB).loadFreelist.func1()
	/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:316 +0xcf fp=0xc00025b678 sp=0xc00025b640 pc=0x53115f
sync.(*Once).doSlow(0xc000406368, 0xc00025b728)
	/usr/local/go/src/sync/once.go:66 +0xe3 fp=0xc00025b718 sp=0xc00025b678 pc=0x477b93
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/etcd-io/bbolt.(*DB).loadFreelist(0xc000406200)
	/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:309 +0x6a fp=0xc00025b748 sp=0xc00025b718 pc=0x52219a
github.com/etcd-io/bbolt.Open(0xc00042a120, 0x23, 0xc000000180, 0x14fe4c0, 0x0, 0xc00025b800, 0x409b4b)
	/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:286 +0x35d fp=0xc00025b830 sp=0xc00025b748 pc=0x521c4d
github.com/aquasecurity/trivy-db/pkg/db.Init(0xc0003e8ae0, 0x17, 0xdd233b, 0xe)
	/go/pkg/mod/github.com/aquasecurity/trivy-db@v0.0.0-20191101193735-bb56553762c0/pkg/db/db.go:62 +0x13c fp=0xc00025b898 sp=0xc00025b830 pc=0x7699cc
github.com/aquasecurity/trivy/pkg.Run(0xc000414b00, 0xc000414b00, 0xc00025bb9f)
	/home/circleci/project/pkg/run.go:41 +0x2ef fp=0xc00025bba0 sp=0xc00025b898 pc=0xbb712f
github.com/urfave/cli.HandleAction(0xc693a0, 0xe04ed8, 0xc000414b00, 0xc0003ec6c0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8 fp=0xc00025bbc8 sp=0xc00025bba0 pc=0x7cdab8
github.com/urfave/cli.(*App).Run(0xc0003d8340, 0xc0000301d0, 0x1, 0x1, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x58c fp=0xc00025bf00 sp=0xc00025bbc8 pc=0x7cbcbc
main.main()
	/home/circleci/project/cmd/trivy/main.go:17 +0x6f fp=0xc00025bf60 sp=0xc00025bf00 pc=0xbb87ef
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc00025bfe0 sp=0xc00025bf60 pc=0x42fdde
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00025bfe8 sp=0xc00025bfe0 pc=0x45b351

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

**Output of run with `-debug`:**

```
(paste your output here)
```

**Output of `trivy -v`:**

```
trivy version 0.2.1

```

**Additional details (base image name, container registry info...):**

**Comment by simar7** [comment]
Thanks @mattcollier for reporting this issue. I agree it shouldn't panic out like this but rather gracefully try again. We'll triage this and get back to you with a fix.

Some more insight into it, if you're interested: I had a quick look at what could be the cause of the actual panic and it seems that BoltDB wasn't happy with the state of the db it found. Seems like the freelist it was dealing with went corrupt when you issued a `ctrl+c`.

**Comment by Vreyesm** [comment]
In OS X you should delete `$HOME/Library/Caches/trivy`

**Comment by knqyf263** [comment]
Duplicated https://github.com/aquasecurity/trivy/issues/288
