### ISSUE TITLE
exclude --compliance flag from non supported sub-commands

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#3157]
it is required to exclude `--compliance` report flag from non relevant `sub-commands` : 
- image
- config
- fs
- repository

**Comment by itaysk** [comment]
why do you think those are non-relevant? can you please elaborate?

**Comment by chen-keinan** [comment]
> why do you think those are non-relevant? can you please elaborate?

it might be related in the future but currently its only implemented (flag is addressed) in `trivy k8s`, other sub-command show it in `help` which is misleading as user could think it works when it doesn't
