### ISSUE TITLE
Unable to install trivy on kubernetes cluster(Rancher)

### ISSUE THREAD

**Issue by hamzanasir443** [aquasecurity/trivy#3185]
Dear Seniors

I am trying to install trivy on the Kubernetes cluster by following https://www.vultr.com/docs/how-to-secure-kubernetes-deployments-using-trivy-operator/ now the problem is after being installed successfully. I am unable to find trivy on my cluster and if run the command "kubectl get deployment -n trivy-system" I get the result but the pod is not running. Could you please help me to figure out.
Thanks

**Comment by knqyf263** [comment]
You can ask that in [trivy-operator](https://github.com/aquasecurity/trivy-operator).
