### ISSUE TITLE
Install details don't work on Amazon Linux

### ISSUE THREAD

**Issue by bbodenmiller** [aquasecurity/trivy#3189]
## Description

Following https://aquasecurity.github.io/trivy/v0.34/getting-started/installation/#rhelcentos does not properly install Trivy on Amazon Linux

## What did you expect to happen?

Install Trivy

## What happened instead?

`https://aquasecurity.github.io/trivy-repo/rpm/releases/2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

## Output of run with `-debug`:

n/a

## Output of `trivy -v`:

n/a

## Additional details (base image name, container registry info...):

```
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by afdesk** [comment]
@bbodenmiller thanks for your report!
now, there are releases only for RHEL/CentOS versions 5-9 , Amazon Linux has version 2. it's their specific number, and not EL number. 

As workaround, You can try to set `RELEASE_VERSION` variable 5-9

**Comment by bbodenmiller** [comment]
This workaround should be documented rather than issue closed without any change.

**Comment by afdesk** [comment]
> This workaround should be documented rather than issue closed without any change.

probably, it makes sense

**Comment by afdesk** [comment]
we need to add a repository in trivy-repo for Amazon Linux, as told @knqyf263 

https://github.com/aquasecurity/trivy/issues/3483#issuecomment-1403263911
