### ISSUE TITLE
Trivy github repo scan reports in json format

### ISSUE THREAD

**Issue by mydailypuff** [aquasecurity/trivy#3233]
## Description

Hi,
I am scanning my github go,python,js repos using trivy. I see the report as in the 
screenshots. Could anyone please help me how to extract the attached report in json?
I see that there is a command to extract vulnerabilities of docker images in json format:
` trivy image -f json -o results.json <image>`
 I don't see anything like this for repos/files/folders
 I tried the below command, but it did not work:
` trivy fs --security-checks vuln,secret,config ./ -o json > trivy-report.json`

![image](https://user-images.githubusercontent.com/83843152/204229170-df123a64-7027-446f-97de-f18480531eeb.png)
![image](https://user-images.githubusercontent.com/83843152/204229280-cb8fcdc7-f902-4ed1-a22a-1810a5c99e30.png)

**Comment by DmitriyLewen** [comment]
Hello @mydailypuff 
Thanks for your interest to Trivy!

Trivy has same flags for `image` and `fs`.

You can use `trivy fs -f json -o results.json <path>` command.
