### ISSUE TITLE
Trivy client unable to fetch image layers

### ISSUE THREAD

**Issue by navzen2000** [aquasecurity/trivy#3245]
trivy image --security-checks vuln --server <trivyserver:port> alpine:latest -d
2022-12-01T01:24:12.925-0800    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-12-01T01:24:12.925-0800    INFO    Vulnerability scanning is enabled
2022-12-01T01:24:12.926-0800    DEBUG   Vulnerability type:  [os library]
2022-12-01T01:24:12.929-0800    DEBUG   Image ID: sha256:49176f190c7e9cdb51ac85ab6c6d5e4512352218190cd69b08e6fd803ffbf3da
2022-12-01T01:24:12.929-0800    DEBUG   Diff IDs: [sha256:ded7a220bb058e28ee3254fbba04ca90b679070424424761a53a043b93b612bf]
2022-12-01T01:24:12.929-0800    DEBUG   Base Layers: []
2022-12-01T01:24:43.498-0800    FATAL   image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:370
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:230
  - scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:544
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:127
  - unable to get missing layers:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.Inspect
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:118
  - unable to fetch missing layers:
    github.com/aquasecurity/trivy/pkg/cache.RemoteCache.MissingBlobs
        /home/runner/work/trivy/trivy/pkg/cache/remote.go:61
  - twirp error unavailable: Error from intermediary with HTTP status code 502 "Bad Gateway"

**Comment by afdesk** [comment]
@navzen2000 thanks for your report! 

Could you try to set a protocol (http/https) for `--server` flag?

but if it doesn't resolve the issue, we'll need more details about your environment

**Comment by navzen2000** [comment]
@afdesk 
This was the original command:
trivy image --security-checks vuln --server http://<hostname:port> alpine:latest -d

Let me know the info you are looking for

FYI: docker pull  alpine:latest 
works on same env

**Comment by afdesk** [comment]
@navzen2000 could you show how you run Trivy server?

**Comment by navzen2000** [comment]
@afdesk 
trivy server --listen 0.0.0.0:9000

**Comment by afdesk** [comment]
@navzen2000 hm, it should work correctly. 

it seems that Trivy client doesn't have an access to Trivy server. maybe the port is closed....

**Comment by navzen2000** [comment]
CLosing
