### ISSUE TITLE
Java Package Detection Using Maven Central Repo

### ISSUE THREAD

**Issue by varanasikalyan** [aquasecurity/trivy#3287]
To detect GroupId, ArtifactId, Version of a jar we want to use sha of the jar files (Use case: reduces false positives of jar packages). We already have the data of sha vs GAV mapping from maven central repo. To leverage this data in trivy premium we want to have 
 
1) A variable in package struct (https://github.com/aquasecurity/trivy/blob/3a1f05e331719901999f636cced7492acae14165/pkg/fanal/types/artifact.go#L26) to store the sha value in analyzer.
2) A method above this line https://github.com/aquasecurity/trivy/blob/3a1f05e331719901999f636cced7492acae14165/pkg/detector/library/detect.go#L28 to override the lib.Name, lib.Version based on lib.sha (we will generate lib.sha using point1). Also method should have access to db for fetching sha vs gav mapping.

**Comment by knqyf263** [comment]
> 1. A variable in package struct () to store the sha value in analyzer.

I think you can use CustomResources to store digests.
https://github.com/aquasecurity/trivy/blob/7cc83cc2f68284c57608b97bfc6ed36819c1b8ed/pkg/fanal/analyzer/analyzer.go#L160

> 2. A method above this line

It is better to replace digests with names and versions while applying layers because SBOM will not include those packages if we replace them in vulnerability detection.

I'd suggest defining a custom applier as `Applier` is an interface.
https://github.com/aquasecurity/trivy/blob/9b0e9794cb94a2292c506afbff2bcd8695170558/pkg/scanner/local/scan.go#L52-L54

Also, I think [cacheMergedLayer](https://github.com/aquasecurity/trivy/blob/5745961194c4ea3ab7d1dbbb5a9a79a30db33754/pkg/fanal/applier/applier.go#L19-L21) should be moved to the custom applier.

```
type CustomApplier struct {
	applier applier.Applier
}

func NewCustomApplier(c cache.Cache) CustomApplier {
	return &CustomApplier {
		applier: applier.NewApplier(c),
	}
}

func (a *CustomApplier) ApplyLayers(imageID string, layerKeys []string) (types.ArtifactDetail, error) {
	var mergedKey string

	// Try to restore the merged layer
	var err error
	mergedKey, err = calcMergedKey(layerKeys)
	if err != nil {
		return types.ArtifactDetail{}, xerrors.Errorf("failed to calculate a merged key: %w", err)
	}
	if b, err := a.cache.GetBlob(mergedKey); err == nil {
		return b.ToArtifactDetail(), nil
	}

	mergedLayer, err := a.applier.ApplyLayers(imageID, layerKeys)
	if err != nil {...}

	// Store the merged layer if the feature is enabled
	if a.cacheMergedLayer {
		if err := a.cache.PutBlob(mergedKey, mergedLayer.ToBlobInfo()); err != nil {
			log.Logger.Error("Unable to cache the merged layer: %s", err)
		}
	}

	// Detect groupID, artifactID and version by file digests.
	lookupDigests(&mergedLayer)

	return mergedLayer, nil
}

func calcMergedKey(layerKeys []string) (string, error) {
	h := sha256.New()
	if err := json.NewEncoder(h).Encode(layerKeys); err != nil {
		return "", xerrors.Errorf("json error: %w", err)
	}

	d := digest.NewDigest(digest.SHA256, h)
	return d.String(), nil
}

func lookupDigests(mergedLayer *types.ArtifactDetail) error {
	var javaPkgs []types.Package
	for _, cr := range mergedLayer.CustomResources {
		if cr.Type != "jar-digest" {
			continue
		}
		digest := cr.Data.(string)
		name, version, err := lookupDigest(digest)
		if err != nil {...}

		javaPkgs = append(javaPkgs, types.Package {
			Name: name,
			Version: version,
			FilePath: cr.FilePath,
		})
	}

	mergedLayer.Applications = append(mergedLayer.Applications, types.Application {
		Type: ftypes.Jar // https://github.com/aquasecurity/trivy/blob/68f374ac9a1b7962875afb5f76bf84dacf20a805/pkg/fanal/types/const.go#L24
		Libraries: javaPkgs,
	}
}
```

Then, you can detect vulnerabilities as usual.

**Comment by behara** [comment]
Thanks for the suggestion @knqyf263. On 2nd Point I have trimmed the function custom **ApplyLayers** as below for two reasons

1. a.cache.GetBlob, a.cache.PutBlob are already being called in a.applier.ApplyLayers. So I have removed them
2. When you say a.cache.GetBlob I believe it's a.applier.cache.GetBlob from here https://github.com/aquasecurity/trivy/blob/5745961194c4ea3ab7d1dbbb5a9a79a30db33754/pkg/fanal/applier/applier.go#L17.
But a.applier.**cache** is unexposed so it's not accessible.

```
func (a *CustomApplier) ApplyLayers(imageID string, layerKeys []string) (types.ArtifactDetail, error) {
	mergedLayer, err := a.applier.ApplyLayers(imageID, layerKeys)
	if err != nil {...}

	// Detect groupID, artifactID and version by file digests.
	lookupDigests(&mergedLayer)

	return mergedLayer, nil
}
```
Do you find any issues with this ?

**Comment by knqyf263** [comment]
>When you say a.cache.GetBlob I believe it's a.applier.cache.GetBlob from here

You can quickly fix it.

```
type CustomApplier struct {
	applier applier.Applier
	cache cache.Cache
}

func NewCustomApplier(c cache.Cache) CustomApplier {
	return &CustomApplier {
		applier: applier.NewApplier(c),
		cache: c,
	}
}
```

>a.cache.GetBlob, a.cache.PutBlob are already being called in a.applier.ApplyLayers. So I have removed them

No, those functions are for storing merged layers as I said as below.

>Also, I think [cacheMergedLayer](https://github.com/aquasecurity/trivy/blob/5745961194c4ea3ab7d1dbbb5a9a79a30db33754/pkg/fanal/applier/applier.go#L19-L21) should be moved to the custom applier.

**Comment by tonaim** [comment]
@knqyf263 , instead of duplicating complete apply layers at our side again, can we have something like postApplyLayer hook?

**Comment by knqyf263** [comment]
@tonaim Please take a deeper look at the source code above. The custom applier wraps the OSS applier and calls the original `ApplyLayers`. You don't have to define the same logic in the custom applier.

**Comment by behara** [comment]
> Also, I think [cacheMergedLayer](https://github.com/aquasecurity/trivy/blob/5745961194c4ea3ab7d1dbbb5a9a79a30db33754/pkg/fanal/applier/applier.go#L19-L21) should be moved to the custom applier.

@knqyf263 I have created a pr here https://github.com/aquasecurity/trivy/pull/3332 for removing cacheMergedLayer. Please let me know if this is fine.

**Comment by knqyf263** [comment]
The tests are failing. Can you please fix them first?

**Comment by behara** [comment]
> The tests are failing. Can you please fix them first?

@knqyf263 I have fixed them now. Can you please review now

**Comment by knqyf263** [comment]
Merged.

**Comment by knqyf263** [comment]
@behara Does my suggestion make sense? I will close this issue if it's feasible on your end.

**Comment by behara** [comment]
@knqyf263  thanks for your suggestion. We can close it for now. If anything needed I will reopen it.
