### ISSUE TITLE
Terraform module SSH source support

### ISSUE THREAD

**Issue by guyb1** [aquasecurity/trivy#3301]
## Description

Hi,
Trivy supports scanning of TF modules. On scanning tf module with  "https clone URL" source, trivy clones the source repo and scans it perfectly. However, when "ssh clone URL" source is given, things go wrong on CI (because ssh clone must be done with git account linked).
Example can be found [here](https://github.com/andresguisado/aws-tf-ec2-dns-docker/blob/d5ac83c4313049e9e44871c3926c0aaa5fba5f0a/main.tf#L3). 
Working example can be found [here](https://github.com/andresguisado/aws-tf-ec2-dns-docker/pull/1/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR3).

## What did you expect to happen?
On defsec, when cloning the source we should convert it to https clone URL before cloning and continue so Trivy can support also CI.

## Output:
Adding some logs in defsec outputs the follows:

```
failed to load module 'aws_ec2_docker': failed to download: error downloading 'ssh://git@github.com/andresguisado/aws-tfmodule-ec2-dns-docker.git': /usr/bin/git exited with 128: Cloning into '/tmp/.aqua/cache/3d0a610c49e05ec74a04944803886c1a'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

```

**Comment by itaysk** [comment]
the fact that this CI runner struggles with ssh doesn't mean that Trivy was doing something wrong, so I don't think this is a bug with Trivy.
I could suggest some work-arounds, like:
1. reconfigure the CI runner to support ssh
2. rewrite module links to http like you suggest, but outside trivy, for example using https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf

both can be done with an step to CI
