### ISSUE TITLE
parsePlatform is failing with UNAUTHORIZED error

### ISSUE THREAD

**Issue by varanasikalyan** [aquasecurity/trivy#3304]
parsePlatform is failing with UNAUTHORIZED error particularly for registries which require valid credentials to communicate with. 

**Stacktrace**
https://github.com/aquasecurity/trivy/blob/01c7fb14bc6c09c41497509667d5455bf96b7e68/pkg/fanal/image/remote.go#L70
func parsePlatform(ref name.Reference, p string) (*v1.Platform, error)

Call 1 **go-containerregistry**
func Index(ref name.Reference, options ...Option) (v1.ImageIndex, error)

Call 2
func get(ref name.Reference, acceptable []types.MediaType, options ...Option) (*Descriptor, error)

Call 3
func makeFetcher(ref name.Reference, o *options) (*fetcher, error) 

Call 4
tr, err := transport.NewWithContext(o.context, ref.Context().Registry, o.auth, o.transport, []string{ref.Scope(transport.PullScope)})

This call for transport.NewWithContext for registries which require valid credentials to communicate with is generating 
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}

Observed that o.auth is anonymous while transport.NewWithContext is requested for.

**Note:**

Even with valid Username and Password are being sent for trivy scanner via **type DockerOption struct**

**Comment by varanasikalyan** [comment]
Looks like this behaviour is seen from this commit
https://github.com/aquasecurity/trivy/commit/7594b1f04108bc841e7e793a351c86facb24a14d

**Comment by knqyf263** [comment]
You need to add support for authentication.
Please refer to the implementation.
https://github.com/aquasecurity/trivy/blob/7594b1f04108bc841e7e793a351c86facb24a14d/pkg/fanal/image/remote.go#L41-L48
