### ISSUE TITLE
Include Conda packages in SBOMs

### ISSUE THREAD

**Issue by maitre-matt** [aquasecurity/trivy#3321]
This is a follow up from #1856 to track scanning for Anaconda packages and including them in generates SBOMs separately. Potential next step after that would be to track vulnerabilities in Anaconda packages.

**Comment by knqyf263** [comment]
Thanks. Hopefully, we will include it in [v0.36.0](https://github.com/aquasecurity/trivy/milestone/12).

**Comment by jacogasp** [comment]
Hello, I'm using version 0.38.3 which supports SBOM generation for `envs/*/conda-meta/*.json` but I did not understand how I'm supposed to use this feature.

I would like to generate SBOMs for all or some of my conda environments. I tried the following are empty.

```
trivy fs --format cyclonedx --output result.json -d miniconda3/envs/aligners
```
but the generated SBOMs are empty

```json
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:b7cf7b04-cbe7-423f-ac38-5740b3cd0349",
  "version": 1,
  "metadata": {
    "timestamp": "2023-03-30T10:12:50+00:00",
    "tools": [
      {
        "vendor": "aquasecurity",
        "name": "trivy",
        "version": "0.38.3"
      }
    ],
    "component": {
      "bom-ref": "8c090bce-b3dd-4fa6-9b2d-c1a54ad29ab9",
      "type": "application",
      "name": "miniconda3/envs/aligners",
      "properties": [
        {
          "name": "aquasecurity:trivy:SchemaVersion",
          "value": "2"
        }
      ]
    }
  },
  "components": [],
  "dependencies": [
    {
      "ref": "8c090bce-b3dd-4fa6-9b2d-c1a54ad29ab9",
      "dependsOn": []
    }
  ],
  "vulnerabilities": []
}
```

What I'm getting wrong?

**Comment by maitre-matt** [comment]
Maybe try without `-d miniconda3/envs/aligners`? I am wondering whether the paths are handled relative to that folder in the analyzers, in which case the pattern `.*/envs/.+/conda-meta/.+-.+-.+\.json` would not match any file.

**Comment by jacogasp** [comment]
Thank you @maitre-matt,
you're right, running `trivy fs --format cyclonedx --output ~/result.json miniconda3` it works.
If I change to `miniconda3/envs` or `miniconda3/envs/<some-env>` then it produces an empty boom.

For my specific use case its ok since I have a script that creates one env at the time and then remove it.
