### ISSUE TITLE
Add basic authentication for OCI artifact module

### ISSUE THREAD

**Issue by NitroCao** [aquasecurity/trivy#3354]
Sometimes the images of vulnerability database or modules are in a private registry, so we need add basic authentication to get them. But for now Trivy does not support it. I skimmed the source code, we may need to modify `NewArtifact()` in file `pkg/oci/artifact.go` in order to implement it.
https://github.com/aquasecurity/trivy/blob/4813cf5cfdaf22d3caf8ca2a2cc89448a5ef994f/pkg/oci/artifact.go#L66-L70

**Comment by NitroCao** [comment]
Any suggestion? I'm glad to implement this feature if you guys are busy on other things.

**Comment by knqyf263** [comment]
After I take another look, I found we already support authentication.
https://github.com/aquasecurity/trivy/blob/4813cf5cfdaf22d3caf8ca2a2cc89448a5ef994f/pkg/oci/artifact.go#L59

You can pull modules after `docker login YOUR_REGISTRY`.

**Comment by NitroCao** [comment]
It works well. Thanks for your reply.
