### ISSUE TITLE
Config flag for `confidence level` in the license scanner

### ISSUE THREAD

**Issue by sentenz** [aquasecurity/trivy#3378]
## Description

The [SPDX license list data](https://github.com/spdx/license-list-data/tree/main/text) contains 553 license files, but trivy detects 227 licenses running:

```bash
trivy fs --security-checks license --license-full <path/to/spdx/list/data> -o license.log
```

See output file [license.log](https://github.com/aquasecurity/trivy/files/10345220/license.log).

## What did you expect to happen?

The confidence level in [classifier.go](https://github.com/aquasecurity/trivy/blob/5190f9566b6ad5c0cf914870732891509541369a/pkg/licensing/classifier.go#L57) is set to 0.9. With a configurable confidence level I expect a much better result.

## Output of `trivy -v`:

```
Version: 0.35.0
```

**Comment by aswath-s-tw** [comment]
Would like to take this up !

**Comment by thevibegod** [comment]
Pairing on this with @aswath-s-tw

**Comment by thevibegod** [comment]
Please review #4073. Thanks.
