### ISSUE TITLE
'trivy client --clear-cache' isn't working properly

### ISSUE THREAD

**Issue by PascalLaporte** [aquasecurity/trivy#338]
**Description**

trivy client --help
Show that there is the option --clear-cache available.
But, We are always getting a Fatal error when we are calling it:
`FATAL	error in image scan: image name or image file must be specified`

**What did you expect to happen?**
Cache is clear, without any error

**What happened instead?**
A fatal error.

**Output of run with `-debug`:**

```
trivy client --clear-cache --debug

2019-12-23T19:33:54.855Z	DEBUG	
Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2019-12-23T19:33:54.855Z	DEBUG	cache dir:  /home/jenkins/.cache/trivy
2019-12-23T19:33:54.855Z	DEBUG	Vulnerability type:  [os library]
2019-12-23T19:33:54.855Z	FATAL	error in image scan:
    github.com/aquasecurity/trivy/internal/client.run
        /home/circleci/project/internal/client/run.go:52
  - image name or image file must be specified:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanImage
        /home/circleci/project/pkg/scanner/scan.go:95
```

**Output of `trivy -v`:**

```
trivy version 0.3.1
```

**Additional details (base image name, container registry info...):**
Trivy server is running properly

**Comment by knqyf263** [comment]
I fixed it. Thank you for the issue!
