### ISSUE TITLE
User input path for picking trivy wasm files

### ISSUE THREAD

**Issue by varanasikalyan** [aquasecurity/trivy#3406]
Currently trivy OSS picks .wasm files ".trivy/modules" folder, hardcoded,

1. But this might not work for trivy scanner running in windows environment as ".trivy/modules" is not Windows advisable folder structure. Hence we may need a flexibility to accept custom user input path.
2. In use cases where Trivy needs to be run from server less functions, ".trivy/modules" under user home directory is not feasible.
3. We come across a situation where we many not require all the .wasm files under ".trivy/modules" to be registered by Trivy OSS, hence accept custom .wasm file names/module names only to be registered.

**Comment by knqyf263** [comment]
Seems like several issues are mixed up. What if adding '--module-files' to address the third one?

**Comment by varanasikalyan** [comment]
Yes @knqyf263 this works good. We can send customised path from our use case with --module-files

**Comment by knqyf263** [comment]
OK. I assigned you this issue.

**Comment by varanasikalyan** [comment]
Hi @knqyf263 Planning to add a global flag for this implementation. Please let know if this is okay?
We will need this for all kinds of scans not just of image scan or so.

**Comment by varanasikalyan** [comment]
Hi @knqyf263  please check it this skeleton implementation is okay. If yes... this needs further improvements 
https://github.com/aquasecurity/trivy/compare/main...varanasikalyan:trivy:user-input-module-files

**Comment by knqyf263** [comment]
If you want to disable loading modules from the default dir, --module-dir is better as it is more intuitive. It is not straightforward if we implicitly disable the module dir when passing --module-files.

**Comment by varanasikalyan** [comment]
1. --module-files can give us a flexibility to only load specific files even from a given module directory and not all the files under --module-dir directory.

eg: in Serverless execution context there can be many files (.wasm) placed under execution tmp directory and each request many not need to load / register all the files.

2. --module-dir also makes trivy to look and load .wasm files from only one directory(--module-dir) but --module-files can give flexibility to provide any path

Please check if this okay?

**Comment by varanasikalyan** [comment]
@knqyf263 how about providing option for both --module-dir and --module-files options?

1. --module-dir takes most precedence and skips default dir() if provided
2. --module-files take only specific files as input to be loaded.

The only concern with --module-dir is that Trivy all the files under a given directory not specific set of files only.

**Comment by knqyf263** [comment]
I think `--module-files` should be just additional of `--module-dir`. Modules under `--module-dir` will be loaded regardless of `--module-files`. `--module-files` additionally load modules.

**Comment by varanasikalyan** [comment]
I think there is slight mis-understanding of our request. We agree partially with you suggestion where ‘–modules-files’ is an additional (ie optional) argument. 

Our recommendation is, 

- If --module-dir is not provided then default dir() is considered
- If --modules-dir is provided the all the .WASM files under this directory are loaded.
- If user wants to load only specific modules in --module-dir the --module-files can be used in conjunction with --module-dir (i.e. as specified in steps below.)
• If ‘—modules-files’ argument is not provided, then load all modules in the directory given using ‘—modules-dir’ directory 
• If ‘—modules-files’ argument is provided, then load only the modules (note: this is a relative path we will be expecting) specified in ‘—modules-files’ from the ‘—modules-dir’ directory. 

Note: Since the control of downloading WASM modules to directory is under our control, we will ensure all modules are download in a single directory.

**Comment by knqyf263** [comment]
`--enable-modules` or `--disable-modules` sounds better, then.

**Comment by varanasikalyan** [comment]
Hi @knqyf263 could you please help in elaborating this "--enable-modules or --disable-modules" and how this helps fulfil my points above?

**Comment by knqyf263** [comment]
Let's say there are 3 modules under `module-dir`.
- spring4shell.wasm
- log4shell.wasm
- hello.wasm

If you don't want to enable spring4shell.wasm, you can pass `--disable-modules spring4shell`.

**Comment by varanasikalyan** [comment]
Hi @knqyf263, this makes more sense.
Should we have both? --enable-modules **and** --disable-modules, else **--enable-modules** inclines more towards --module-files that we want.

If we want both --enable-modules **and** --disable-modules, how do want to deal with common modules across --enable-modules **and** --disable-modules?

**Comment by knqyf263** [comment]
Let's start with `--enable-modules`. If nothing is specified, it loads all modules. If `--enable-modules` is specified, we enable those modules only.
