### ISSUE TITLE
How do I customize the database update duration

### ISSUE THREAD

**Issue by carrieyang1212** [aquasecurity/trivy#3408]
How do I customize the database update duration? I expect database updates to be set to biweekly

**Comment by DmitriyLewen** [comment]
Hello @carrieyang1212 
Thanks for your interest to Trivy!

We recommend updating database after every update of Trivy-db(every 6 hours), because you can lose high or critical vulnerabilities.

Trivy doesn't have options to change update duration.
If you still want to change duration - you can use `--download-db-only` and `--skip-db-update` flags.

Regards, Dmitriy.

**Comment by carrieyang1212** [comment]
We would like to be able to concentrate on high or critical vulnerabilities, such as a batch every two weeks.
I have used --skip-db-update, but after a period of time, db will still be forced to update (hotupdate) . Do you have mandatory rules to use --skip-db-update, and will it still be forced to update after a period of time? If so, for exactly how long?

**Comment by carrieyang1212** [comment]
![image](https://user-images.githubusercontent.com/57127288/211761849-fe76f953-e7e2-4155-bc57-7ad22dd6f204.png)

**Comment by DmitriyLewen** [comment]
Trivy has no rules for the `--skip-db-update` flag.

Trivy does not support the `skip-db-update` flag for server mode because we thought people should update the database in server mode.
But we discussed it and will add support for this flag for hot update.

I will make a PR and write to you.

**Comment by carrieyang1212** [comment]
After The Trivy Server runs for a period of time, the service is interrupted due to an OOM error. After the service is restarted, the message "The first run cannot skip download DB" is displayed again. 
![image](https://user-images.githubusercontent.com/57127288/211967443-79ad41ee-9f71-4215-b0bf-d5b4d28b7cd6.png)

![image](https://user-images.githubusercontent.com/57127288/211967415-d452f8ca-420d-4be8-a7f1-f4914956233f.png)

The restart command is as follows：
 nohup trivy server --skip-db-update --listen 0.0.0.0:8080 &

**Comment by DmitriyLewen** [comment]
thanks for information!

I will check this.

**Comment by DmitriyLewen** [comment]
> After the service is restarted, the message "The first run cannot skip download DB" is displayed again.

i checked this moment.
This error may appear if `metadata.json` file is broken. Are you deleting this file after an OOM error?

**Comment by carrieyang1212** [comment]
metadat.json  file is not deleted, the  file update time is 2023-1-10T17:31.
There are two questions:
1. The Trivy Server always has OOM errors.
2. After The OOM error occurs and the service is restarted, Error message "The first run cannot skip download DB" is displayed.

**Comment by DmitriyLewen** [comment]
you're getting an OOM error after running a scan in the client, right?
What version of Trivy are you using?

**Comment by carrieyang1212** [comment]
Yes . 
I have two Trviy，Versions is 0.34.0 and 0.35.0

**Comment by DmitriyLewen** [comment]
can you update Trivy to `v0.36.0` and try to scan again with flag `--security-checks vuln` flag(this flag for client command)

**Comment by DmitriyLewen** [comment]
Hello @carrieyang1212 
We merged changes to use `skip-dp-update` flag for `hot updates`.

We will include this in next release.
Before that you can use canary build(if this is okay for you) - https://github.com/aquasecurity/trivy/actions/runs/3922566589
