### ISSUE TITLE
trivy image hang there without any hint

### ISSUE THREAD

**Issue by cww1769** [aquasecurity/trivy#3457]
when I use trivy image <image> --debug, only one log print as following and then hang there:
2023-01-19T09:08:29.982Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
I noticed only this machine has this issue, other machine I can get the scan report from trivy image.
I deleted ~/.cache/trivy on this machine, and then trivy recovered. 
Can anyone tell me why this issue happened?

**Comment by knqyf263** [comment]
You might run several Trivy processes at the same time. Trivy uses BoltDB, which doesn't allow simultaneous access.

**Comment by cww1769** [comment]
yes, you are right.
