### ISSUE TITLE
Include ignored CVEs in report, explicitly marked as ignored

### ISSUE THREAD

**Issue by victornoel** [aquasecurity/trivy#3464]
Hi,

I was wondering if it would be possible to have an option so that the output of vulnerability scan also include the ignored CVEs marked explicitly as being ignored.

Maybe using something like an option `--include-ignored-in-report` or whatever :)

Ideally, this should be usable for all report format where it's possible to include that information.

Even better would be that we can write a rationale for ignoring a CVE and that rationale is included in the report :)

**Comment by knqyf263** [comment]
We can put it in the JSON report. Do you want to see ignored vulnerabilities in the table output as well?

**Comment by victornoel** [comment]
@knqyf263 yep, it would be a nice option in the table too, it can be useful to get a quick one-look summary of what are the vulnerabilities, which one are ignored, etc :)

**Comment by knqyf263** [comment]
Got it. We can probably add a new field like `Ignored bool` or `Status VulnerabilityStatus` here.
https://github.com/aquasecurity/trivy/blob/cfabdf9138d95f61bb7c40655e9c11acfe00797b/pkg/types/vulnerability.go#L8-L30

The new flag can be added here.
https://github.com/aquasecurity/trivy/blob/e01253d54d657b3fc8ede6a4427e6dfd0919168f/pkg/flag/vulnerability_flags.go

And update the filtering logic.
https://github.com/aquasecurity/trivy/blob/68eda79357d01485f1c72e759d9e20dfd5d4210f/pkg/result/filter.go

**Comment by choffmeister** [comment]
Great idea. One though regarding backwards compatibility though: If we just add a new flag to `DetectedVulnerability`, then existing downstream tooling that parses the JSON would just ignore it and think it is an unignored vulnerability. So from interpretation of the JSON output it would be breaking change.

Maybe a dedicated entry `.Results.IgnoredVulnerabilites` next to the existing `.Results.Vulnerabilities` is a better approach?

**Comment by ShubhamPalriwala** [comment]
Hey, so just to get it right,

Let's say a user sets the following CVEs as ignored:
```
CVE2022-123-123
CVE2022-123-124
```

Now, as of now, the user will not see these in the report generated.

However, if the user passes an `--include-ignored-in-report` option, they should now, in the report, see these CVEs too with the field, "Ignored" as true/false.

Am I getting this correct? Would like to apologise if it got repeatitive for y'all :/

Would like to implement this feature

**Comment by victornoel** [comment]
@ShubhamPalriwala from what everybody is saying, it looks good!

If I understand correctly (hehe, I'm also going the repetitive path :P): the json outputed by trivy will have only the `.Results.Vulnerabilities` but an extra boolean flag for ignored (only if the cli option is on).

Ideally, it would be nice that in the HTML template there be two different sections, one for non-ignored vulnerabilities and one for ignored vulnerabilities (of course that last one wouldn't be visible if the cli option is off).

**Comment by 3XC1T3D** [comment]
That feature would be nice!

The description of the ignore file should alsol be displayed in the html report.

So if you generate the report, it's clear why a cve was ignored.

**Comment by francRang** [comment]
Can someone assign this to me? I'd be interested in working on it.

**Comment by francRang** [comment]
WIP:
https://github.com/aquasecurity/trivy/compare/main...francRang:trivy:main
So far I can output a list of ignored vulns under the report. Need to figure out how to make it so that it only outputs the ignored vulns when the flag is set.

**Comment by francRang** [comment]
Still working on it, everything works, but cannot make the filterByVex option work correctly. Almost there.

**Comment by victornoel** [comment]
Very nice @knqyf263, thanks!
