### ISSUE TITLE
Trivy client should let server download the necessary files

### ISSUE THREAD

**Issue by Vesnica** [aquasecurity/trivy#348]
I'm running a trivy server which can access the internet (by proxy). and I found trivy in client mode will still try to download apk index by himself when scaning some older images, and will fail with a timeout, which unnecessarily prolongs the scan time.

Some log:
```
trivy client --remote http://SERVER_IP:SERVER_PORT some_old_image
2019/12/30 02:17:12 failed to fetch APKINDEX archive: Get https://raw.githubusercontent.com/knqyf263/apkIndex-archive/master/alpine/v3.4/main/x86_64/history.json: dial tcp 151.101.108.133:443: i/o timeout
2019-12-30T02:17:12.677Z        WARN    This OS version is no longer supported by the distribution: alpine 3.4.6
2019-12-30T02:17:12.677Z        WARN    The vulnerability detection may be insufficient because security updates are not provided
```

Maybe the client should let the server download all the necessary files (and better: cache them)?

**Comment by aizural** [comment]
same problem, .,

**Comment by krol3** [comment]
@Vesnica @aizural trivy has the parameter ` --timeout value`. Will this help you with the fail timeout?

**Comment by Vesnica** [comment]
@krol3 Reduce the timeout value may can reduce the overall scanning time, but it won't fix the problem as warning message stats: 
```2019-12-30T02:17:12.677Z        WARN    The vulnerability detection may be insufficient because security updates are not provided```

I think it is a better solution to let the server download the necessary files.
