### ISSUE TITLE
docs: add workaround to install Trivy for Amazon Linux

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/trivy#3483]
it seems, the docs should contain this workaround. right?

              
              now, there are releases only for RHEL/CentOS versions 5-9 , Amazon Linux has version 2. it's their specific number, and not EL number. 
              As workaround, You can try to set `RELEASE_VERSION` variable 5-9

_Originally posted by @afdesk in https://github.com/aquasecurity/trivy/issues/3189#issuecomment-1318305203_

              This workaround should be documented rather than issue closed without any change.

_Originally posted by @bbodenmiller in https://github.com/aquasecurity/trivy/issues/3189#issuecomment-1400090643_

**Comment by knqyf263** [comment]
Can we put a repository in trivy-repo for Amazon Linux?

**Comment by afdesk** [comment]
@knqyf263 it's an interesting idea. need to think it over.
