### ISSUE TITLE
Improve documentation of ignore-policy

### ISSUE THREAD

**Issue by YuriGal** [aquasecurity/trivy#3486]
I am trying to create an exception for AVD-AWS-0088, but can get it in a proper format. Could you please provide an example of ignoring a specific AWS rule? Can it be applied to a specific resource only?

**Comment by itaysk** [comment]
Thanks for the report. I hope the info in [this discussion](https://hachyderm.io/@ygalanter/109760988470193629) helped you. I'll keep this issue open for improving the docs in that area. at the very least clarify what is input

**Comment by YuriGal** [comment]
It's not really ignore policy - if I am not mistaken that applies to vulnerabilities only. I am looking into misconfiguration and exceptions to rules. Basically something like [this](https://github.com/aquasecurity/trivy/blob/f3f302901476663b3edef629f5915236cce98bd4/examples/misconf/rule-exception/policy/ksv006_exception.rego) but for AWS and CloudFormation.

**Comment by itaysk** [comment]
Ignore policy and ignore file works for misconfigurations also, as shown in the other thread

**Comment by itaysk** [comment]
while we're revisiting this doc, we used to refer to this as "exceptions" to be conftest friendly, but we're no longer. The flag is called ignore-policy, so doc needs refresh accordingly

**Comment by itaysk** [comment]
I've started a thread to discuss this doc as part of a bigger picture https://github.com/aquasecurity/trivy/discussions/3620
