### ISSUE TITLE
update latest defsec version with kubelet checks mapping fix

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#3509]
## Description
 Related [Defsec PR ](https://github.com/aquasecurity/defsec/pull/1159)
Related: #2201

**Comment by chen-keinan** [comment]
Not yet , need another pr in trivy with new defsec tag , will do it shortly

**Comment by knqyf263** [comment]
OK. I'll wait for it then.

**Comment by chen-keinan** [comment]
closing issue as trivy is updated with latest defsec `v0.82.9`
