### ISSUE TITLE
download and reuse the search.maven.org DB

### ISSUE THREAD

**Issue by kforner** [aquasecurity/trivy#3511]
In order to solve the issues with search.maven.org slowness/overuse that occurs when jar files are scanned, would it be possible to implement a:
- `download search.maven.org DB`, that would download the subset of search.maven.org that you need to identify the jars
- `with search.maven.org DB`, that would use the supplied pre-downloaded with the above option DB

Then a project like trivy-offline could download it once a day, and that would save millions of requests to search.maven.org and speed up a lot trivy scans.
Does it make sense ? 
Thanks

**Comment by knqyf263** [comment]
We're discussing it here.
https://github.com/aquasecurity/trivy/issues/3427
