### ISSUE TITLE
Unable to open JAR files

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#3514]
## Description
Java scanning may lead to the following error.

```
failed to analyze file: failed to analyze usr/lib/jvm/java-1.8-openjdk/lib/tools.jar: unable to open usr/lib/jvm/java-1.8-openjdk/lib/tools.jar: failed to open: unable to read the file: stream error: stream ID 9; PROTOCOL_ERROR; received from peer
```

Currently, we're investigating this issue. As a temporary mitigation, you may be able to avoid this issue by downloading the Java DB in advance. `--download-java-db-only` is available in v0.37.0+.

```
$ trivy image --download-java-db-only
2023-02-01T16:57:04.322+0900    INFO    Downloading the Java DB...
$ trivy image [YOUR_JAVA_IMAGE]
```

**Comment by StevDa86** [comment]
Full log file: [trivy_debug.log](https://github.com/aquasecurity/trivy/files/10569429/trivy_debug.log)

Here is a debug log from a run which has the same error. Trivy just stops working. 
Its wired cause some times the same image works and a few hours later not.

I also tested it with different images.

`2023-02-02T13:27:35.337Z        DEBUG   Parsing Java artifacts...       {"file": "app/lib/netty-transport-native-kqueue-4.1.79.Final-osx-x86_64.jar"}
2023-02-02T13:27:35.694Z        DEBUG   Parsing Java artifacts...       {"file": "app/lib/netty-transport-native-unix-common-4.1.79.Final.jar"}
2023-02-02T13:27:35.709Z        DEBUG   Parsing Java artifacts...       {"file": "app/lib/nimbus-jose-jwt-9.22.jar"}
2023-02-02T13:27:35.724Z        FATAL   image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:397
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:257
  - scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:588
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:146
  - analyze error:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.Inspect
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:127
  - failed to analyze layer:  :
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspect.func1
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:229
  - walk error:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspectLayer
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:284
  - failed to process the file:
    github.com/aquasecurity/trivy/pkg/fanal/walker.LayerTar.Walk
        /home/runner/work/trivy/trivy/pkg/fanal/walker/tar.go:90
  - failed to analyze file:
    github.com/aquasecurity/trivy/pkg/fanal/walker.LayerTar.processFile
        /home/runner/work/trivy/trivy/pkg/fanal/walker/tar.go:104
  - failed to analyze app/lib/oauth2-oidc-sdk-9.35.jar:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspectLayer.func1
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:279
  - unable to open app/lib/oauth2-oidc-sdk-9.35.jar:
    github.com/aquasecurity/trivy/pkg/fanal/analyzer.AnalyzerGroup.AnalyzeFile
        /home/runner/work/trivy/trivy/pkg/fanal/analyzer/analyzer.go:407
  - failed to open:
    github.com/aquasecurity/trivy/pkg/fanal/walker.(*cachedFile).Open
        /home/runner/work/trivy/trivy/pkg/fanal/walker/cached_file.go:65
  - unable to read the file:
    github.com/aquasecurity/trivy/pkg/fanal/walker.(*cachedFile).Open.func1
        /home/runner/work/trivy/trivy/pkg/fanal/walker/cached_file.go:58
  - unexpected EOF`

**Comment by DmitriyLewen** [comment]
Hello @StevDa86 
Thanks!

We know about this bug and can reproduce "unexpected EOF". 
We are currently working on it.

**Comment by 3XC1T3D** [comment]
> Full log file: [trivy_debug.log](https://github.com/aquasecurity/trivy/files/10569429/trivy_debug.log)
> 
> Trivy version 0.36.1
> 
> Here is a debug log from a run which has the same error. Trivy just stops working. Its wired cause some times the same image works and a few hours later not.
> 
> I also tested it with different images.
> 
> `2023-02-02T13:27:35.337Z DEBUG Parsing Java artifacts... {"file": "app/lib/netty-transport-native-kqueue-4.1.79.Final-osx-x86_64.jar"} 2023-02-02T13:27:35.694Z DEBUG Parsing Java artifacts... {"file": "app/lib/netty-transport-native-unix-common-4.1.79.Final.jar"} 2023-02-02T13:27:35.709Z DEBUG Parsing Java artifacts... {"file": "app/lib/nimbus-jose-jwt-9.22.jar"} 2023-02-02T13:27:35.724Z FATAL image scan error: github.com/aquasecurity/trivy/pkg/commands/artifact.Run /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:397
> 
> * scan error:
>   github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
>   /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:257
> * scan failed:
>   github.com/aquasecurity/trivy/pkg/commands/artifact.scan
>   /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:588
> * failed analysis:
>   github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
>   /home/runner/work/trivy/trivy/pkg/scanner/scan.go:146
> * analyze error:
>   github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.Inspect
>   /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:127
> * failed to analyze layer:  :
>   github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspect.func1
>   /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:229
> * walk error:
>   github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspectLayer
>   /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:284
> * failed to process the file:
>   github.com/aquasecurity/trivy/pkg/fanal/walker.LayerTar.Walk
>   /home/runner/work/trivy/trivy/pkg/fanal/walker/tar.go:90
> * failed to analyze file:
>   github.com/aquasecurity/trivy/pkg/fanal/walker.LayerTar.processFile
>   /home/runner/work/trivy/trivy/pkg/fanal/walker/tar.go:104
> * failed to analyze app/lib/oauth2-oidc-sdk-9.35.jar:
>   github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspectLayer.func1
>   /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:279
> * unable to open app/lib/oauth2-oidc-sdk-9.35.jar:
>   github.com/aquasecurity/trivy/pkg/fanal/analyzer.AnalyzerGroup.AnalyzeFile
>   /home/runner/work/trivy/trivy/pkg/fanal/analyzer/analyzer.go:407
> * failed to open:
>   github.com/aquasecurity/trivy/pkg/fanal/walker.(*cachedFile).Open
>   /home/runner/work/trivy/trivy/pkg/fanal/walker/cached_file.go:65
> * unable to read the file:
>   github.com/aquasecurity/trivy/pkg/fanal/walker.(*cachedFile).Open.func1
>   /home/runner/work/trivy/trivy/pkg/fanal/walker/cached_file.go:58
> * unexpected EOF`

we have the same issue by scanning a Tomcat Image. Did it help to download the Java DB in advance?

**Comment by Momotoculteur** [comment]
Hi guys,

i can reproduce & get the same behaviour

**Comment by namandf** [comment]
Hi,

Still seeing similar issues in latest version of Trivy https://github.com/aquasecurity/trivy/issues/3807
