### ISSUE TITLE
Trivy 0.37 not working due to error message "Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work"

### ISSUE THREAD

**Issue by gumbyDE** [aquasecurity/trivy#3520]
Running Trivy 0.37 on Kali inside a docker container (but also when downloading directly) gives the following error message:

`Unable to initialize the Java DB: Java DB open error: can't open db: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub`

Any ideas how to fix?

**Comment by knqyf263** [comment]
We're on it.

**Comment by nickbroon** [comment]
Duplicate of #3514 ?

**Comment by cpach** [comment]
> Duplicate of #3514 ?

No.

**Comment by knqyf263** [comment]
v0.37.1 is out. We hope it addresses the issue.
https://github.com/aquasecurity/trivy/releases

**Comment by ncouse** [comment]
Just tested container image 0.37.1 and that now works. Thanks.

**Comment by knqyf263** [comment]
Thanks for testing!
