### ISSUE TITLE
Add OCI image annotations to docker hub published aquasec/trivy images

### ISSUE THREAD

**Issue by candrews** [aquasecurity/trivy#3542]
The images published to https://hub.docker.com/r/aquasec/trivy do not have [OCI image annotations](
https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys), such as `org.opencontainers.image.source`

These annotations are useful for people to manual use as well as for use by tools. For example, [Snyk uses them in its UI](https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/) and [Renovate uses them to find release notes](https://github.com/renovatebot/renovate/blob/34.115.1/lib/modules/datasource/docker/readme.md).

I believe at least these labels should be added to the images:
* `org.opencontainers.image.source`
* `org.opencontainers.image.revision`

**Comment by knqyf263** [comment]
Our image has labels.
https://github.com/aquasecurity/trivy/blob/7f8868b7d83fddf251ebe6a4d37f2482ae1e8a8a/goreleaser.yml#L127-L136

```
$ crane config --platform linux/amd64 aquasec/trivy:0.37.1 | jq .config.Labels
{
  "org.opencontainers.image.created": "2023-02-01T15:36:42Z",
  "org.opencontainers.image.description": "A Fast Vulnerability Scanner for Containers",
  "org.opencontainers.image.documentation": "https://aquasecurity.github.io/trivy/v0.37.1/",
  "org.opencontainers.image.revision": "7f8868b7d83fddf251ebe6a4d37f2482ae1e8a8a",
  "org.opencontainers.image.source": "https://github.com/aquasecurity/trivy",
  "org.opencontainers.image.title": "trivy",
  "org.opencontainers.image.url": "https://www.aquasec.com/products/trivy/",
  "org.opencontainers.image.vendor": "Aqua Security",
  "org.opencontainers.image.version": "0.37.1"
}
```

**Comment by knqyf263** [comment]
The canary image is not for production. It doesn't matter actually.

**Comment by candrews** [comment]
Makes sense - thank you!
