### ISSUE TITLE
Any way to have Trivy use local Maven Central mirror?

### ISSUE THREAD

**Issue by isuftin** [aquasecurity/trivy#3548]
Our organization hosts an internal Artifactory server which mirrors Maven Central. With Maven Central having issues for the past few weeks, it would be great if we could point Trivy to Artifactory as a prioritized Maven search target over Maven central, possibly using Maven Central as a fallback.

Looking through the documentation and the help dialog via cli, I don't see anywhere where that can be changed.

Is it currently possible to do?

**Comment by knqyf263** [comment]
We migrated to trivy-java-db. I hope it addresses this issue. Please feel free to reopen that if you mean something else. Thanks.
https://github.com/aquasecurity/trivy-java-db
