### ISSUE TITLE
add little structure for changelog to not miss great things

### ISSUE THREAD

**Issue by hpvd** [aquasecurity/trivy#3554]
Would be great to give the changelog a little structure/sorting e.g. new features, fixes etc.

-> so one doesn't miss great things like this line within 50 other similar lines
`b259b25 feat: Add AWS Cloud scanning 2493`
in
https://github.com/aquasecurity/trivy/releases/tag/v0.31.0
and
-> one could easily look for things one is most interested in e.g. fixes or new features

**Comment by hpvd** [comment]
ah many thanks for pointing to https://github.com/aquasecurity/trivy/discussions/2716
this is what I was looking for :-)
would have never expected it to be located in discussion...

**Comment by itaysk** [comment]
There's a "Join Discussion" button in the release page, but I agree, it is not very inviting.
For next releases, we should put a standout link on top of the release page like here https://github.com/aquasecurity/tracee/releases/tag/v0.10.0

@knqyf263 @giorod3

**Comment by hpvd** [comment]
looks perfect :-)
