### ISSUE TITLE
The result of scanning an image multiple times is not unique

### ISSUE THREAD

**Issue by whhx** [aquasecurity/trivy#3568]
I scan the same image in a period of time, and the results are different.

During the two scans, the vulnerability database was updated, but the jar with the problem remained unchanged. The first scan found the problem. After a period of time, the second scan disappeared

![image](https://user-images.githubusercontent.com/14163617/217176123-463e40f6-6b6f-4558-bc1b-edaacbe183fc.png)
![image](https://user-images.githubusercontent.com/14163617/217176625-51dfcf41-99b0-4df8-ad9e-22c9b316290c.png)

**Comment by whhx** [comment]
两次扫描时间间隔两个小时左右，但是结果不同

**Comment by knqyf263** [comment]
JAR scanning was unstable before introducing java-db. I guess it failed to detect the package for some reason.
