### ISSUE TITLE
Ho do I ignore a specific vulnerability by ID only in a particular file.

### ISSUE THREAD

**Issue by codemedic** [aquasecurity/trivy#3572]
If I have multiple `Dockerfile`s, say one just for build and the other for docker images that are meant for deployment, `trivy` sometimes report issues with the former which I would like to ignore. Since they are build time only, they are safe enough to ignore.

How do I ignore them by ID per file?

**Comment by itaysk** [comment]
Hi, I think the custom ignore policy feature might help you: https://aquasecurity.github.io/trivy/v0.37/docs/misconfiguration/policy/exceptions/

**Comment by itaysk** [comment]
> comment above the offending line in the specific file

sounds like https://github.com/aquasecurity/trivy/issues/2961, please comment there if you have feedback about this feature

> Are there any guides / examples to ignore a specific ID in a specific file?

I think today your best bet would be using [rego exceptions](https://aquasecurity.github.io/trivy/v0.37/docs/misconfiguration/policy/exceptions/) which have some examples [here](https://github.com/aquasecurity/trivy/tree/85d5d61bc7f69e3bc0eec9d52b6aa47f53797cc3/examples/misconf/rule-exception). This feature's documentation [needs improvement](https://github.com/aquasecurity/trivy/issues/3486) 

While we improve the experience around this, you can follow this discussion for some context: https://github.com/aquasecurity/trivy/discussions/3620.
