### ISSUE TITLE
Missing feature for ignoring windows nodes in an AKS cluster containing both windows and Linux pools

### ISSUE THREAD

**Issue by fmad** [aquasecurity/trivy#3593]
## What did you expect to happen?

Be able to ignore windows nodes automatically and/or by passing a flag.

## What happened instead?

Just takes forever (estimated on a sample cluster with 1145 objects - over 24 hours!)

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
Version: 0.37.2
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-02-10 12:07:56.846216503 +0000 UTC
  NextUpdate: 2023-02-10 18:07:56.846216103 +0000 UTC
  DownloadedAt: 2023-02-10 15:42:30.1247773 +0000 UTC
```

**Comment by mineshp100** [comment]
Yes, I agree. This would be helpful for those consumers who have mixed OS kubernetes clusters. +1

**Comment by chen-keinan** [comment]
@fmad @mineshp100 trivy v0.42.0 support exclude node scanning by labels see #4459

**Comment by knqyf263** [comment]
Please reopen this issue if it doesn't meet your requirements.
