### ISSUE TITLE
SPDX2.2: trivy generates SBOM without required PackageDownloadLocation

### ISSUE THREAD

**Issue by surendrapathak** [aquasecurity/trivy#3601]
## Description

While applying [quality checks](https://github.com/interlynk-io/sbomqs) on SBOMs , I found trivy failing to adhere to the strict 2.2 spec for created

```trivy repo --format spdx-json https://github.com/interlynk-io/sbomqs```

results in the attached file with the missing field -

```PackageDownloadLocation:``` 

However, this is a required field for spec 2.2 with `NONE` and `NOASSERTION` as possible fallback values

https://spdx.github.io/spdx-spec/v2.2.2/package-information/#77-package-download-location-field

This causes other tools that rely on strict checks (such as https://github.com/spdx/tools-[python/blob/72780a48d830b29c5d8c85c27e9ddbf39c22b6f6/spdx/utils.py#L37-L39](https://github.com/spdx/tools-python/blob/f934ae27cc76c20f8e701bf2503e3ea521a9bb88/spdx/parsers/jsonyamlxml.py#L1295)) to barf.

## What did you expect to happen?

presence of the following or a legitimate value:
```PackageDownloadLocation: NOASSERTION```  

## What happened instead?

required field is missing

## Output of run with `-debug`:

```
2023-02-12T12:00:43.565-0800	DEBUG	["cyclonedx" "spdx" "spdx-json" "github"] automatically enables '--list-all-pkgs'.
2023-02-12T12:00:43.566-0800	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-02-12T12:00:43.567-0800	INFO	"--format spdx" and "--format spdx-json" disable security checks
2023-02-12T12:00:43.615-0800	DEBUG	cache dir:  /Users/spathak/Library/Caches/trivy
Enumerating objects: 152, done.
Counting objects: 100% (152/152), done.
Compressing objects: 100% (97/97), done.
Total 152 (delta 75), reused 117 (delta 49), pack-reused 0
2023-02-12T12:00:44.243-0800	DEBUG	Walk the file tree rooted at '/var/folders/zx/qlnb6lln5q1_xts5640lvft9zpyfnc/T/fanal-remote1389828702' in parallel
2023-02-12T12:00:44.293-0800	DEBUG	OS is not detected.```

## Output of `trivy -v`:

```
Version: 0.36.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-02-03 18:09:23.361876616 +0000 UTC
  NextUpdate: 2023-02-04 00:09:23.361876316 +0000 UTC
  DownloadedAt: 2023-02-03 19:43:11.792679 +0000 UTC```

## Additional details (base image name, container registry info...):
[sbomqs.spdx.json.txt](https://github.com/aquasecurity/trivy/files/10717233/sbomqs.spdx.json.txt)

**Comment by MarioSMC** [comment]
The issue still exists in the latest release:

Version: 0.38.3
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-03-16 06:06:56.928415362 +0000 UTC
  NextUpdate: 2023-03-16 12:06:56.928414862 +0000 UTC
  DownloadedAt: 2023-03-16 10:27:03.946887416 +0000 UTC
