### ISSUE TITLE
v0.37.2 Introduced Issue in GitLab Pipelines

### ISSUE THREAD

**Issue by matthewriedel-flux** [aquasecurity/trivy#3602]
## Description

We run Trivy using DIND in a GitLab pipeline. Starting in v0.37.2, pipelines started failing with messages indicating that Trivy could not connect to the Docker socket which left it unable to pull images.

## What did you expect to happen?
Trivy would pull images and scan them.

## What happened instead?
Trivy is producing messages like:
```
2023-02-12T20:17:10.408Z	FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
	* unable to inspect the image (123456789012.dkr.ecr.ap-southeast-2.amazonaws.com/engineering/my-image@sha256:<sha256_hash>): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* containerd socket not found: /run/containerd/containerd.sock
	* Get "https://123456789012.dkr.ecr.ap-southeast-2.amazonaws.com/v2/": dial tcp 13.55.237.184:443: connect: connection timed out
```

## Output of run with `-debug`:

```
2023-02-12T22:13:32.214Z	FATAL	image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:424
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:263
  - unable to initialize a scanner:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:649
  - unable to initialize a docker scanner:
    github.com/aquasecurity/trivy/pkg/commands/artifact.imageStandaloneScanner
        /home/runner/work/trivy/trivy/pkg/commands/artifact/scanner.go:22
  - 4 errors occurred:
	* unable to inspect the image (123456789012.dkr.ecr.ap-southeast-2.amazonaws.com/engineering/my-image@sha256:<sha256_hash>): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* containerd socket not found: /run/containerd/containerd.sock
	* Get "https://123456789012.dkr.ecr.ap-southeast-2.amazonaws.com/v2/": dial tcp 13.237.123.211:443: connect: connection timed out 
```

## Output of `trivy -v`:

```
Version: 0.37.2
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-11-14 18:07:12.342610381 +0000 UTC
  NextUpdate: 2022-11-15 00:07:12.342609981 +0000 UTC
  DownloadedAt: 2022-11-14 20:32:54.084738 +0000 UTC
```

## Additional details (base image name, container registry info...):
Using AWS ECR.

A workaround seems to be holding the Trivy version to 0.37.1

**Comment by DmitriyLewen** [comment]
Hello @matthewriedel-flux 
Thanks for your report!

Some question about your problem:
Are you scanning local (I mean: do you pull images before scanning) or remote images?
Are you using any network settings (proxy, etc.)?

Regards, Dmitriy

**Comment by matthewriedel-flux** [comment]
Hi Dmitriy,


> Some question about your problem: Are you scanning local (I mean: do you pull images before scanning) or remote images? 
I am attempting to scan remote (hosted in AWS ECR) images. I do not pull the images before scanning. I've relied on Trivy to do that up until now.

> Are you using any network settings (proxy, etc.)?

Yes, we use a proxy, but no settings related to that have changed. If I switch my image from `0.37.1` to `0.37.2` I start receiving the errors I described. I do not see any proxy-related changes listed in the [0.37.2 Release notes](2022-12-20T09:00:21Z)?

**Comment by DmitriyLewen** [comment]
I asked because we have similar issue with proxy settings(#3592).

I created #3604 to fix this problem.
We will try to merge these changes as soon as possible.

**Comment by matthewriedel-flux** [comment]
Awesome- thanks @DmitriyLewen !

**Comment by DmitriyLewen** [comment]
Hello @matthewriedel-flux !

PR is merged.
We have `canary build` - https://github.com/aquasecurity/trivy/actions/runs/4162685057
You can use this binary(if it is okay for you).

Regards, Dmitriy

**Comment by matthewriedel-flux** [comment]
Great - thanks @DmitriyLewen . I see the binaries, is there a canary Docker image I can pull? We use images in our pipelines, so it's a bit hard to test out binaries there.

**Comment by DmitriyLewen** [comment]
Unfortunately we only have binaries at this time, but we plan to release v0.37.3 in the coming days.

**Comment by knqyf263** [comment]
We have a canary image.
https://hub.docker.com/layers/aquasec/trivy/canary/images/sha256-3d4b40051fec842b4cf195b7606ef855a5db90bf288397c92bcc9700ef95b7dd?context=explore

Also, we cut v0.37.3.

**Comment by matthewriedel-flux** [comment]
v0.37.3 looks good! Thanks very much!
