### ISSUE TITLE
Docs - Misconfig - Dockerfile link

### ISSUE THREAD

**Issue by tellierd** [aquasecurity/trivy#3609]
## Description

The Dockerfile, Containerfile hyperlink on this [documentation page](https://github.com/aquasecurity/trivy/blob/main/docs/docs/misconfiguration/policy/builtin.md) returns a 404.

The source folder has changed and now seems to be here: https://github.com/aquasecurity/defsec/tree/master/internal/rules/policies/docker

**Comment by knqyf263** [comment]
Thanks for catching. I'll leave it for the first-time contributors.

**Comment by nduytg** [comment]
Hi there, I'd like to take up this
