### ISSUE TITLE
Examples and Documentation

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/trivy#3621]
The https://github.com/aquasecurity/trivy/tree/main/examples directory has some useful stuff but no one will find it in the source code. Also unlikely to kept up to date with changes to the relevant features.

I think it needs to be incorporated in the docs somehow, either by moving it to the docs dir, or (probably better) turning it into tutorials and then delete the examples dir.

**Comment by knqyf263** [comment]
Wasm examples are used in integration tests so that the examples can be up-to-date. I've removed misconfiguration examples in https://github.com/aquasecurity/trivy/pull/3977.

**Comment by itaysk** [comment]
this is not a critical issue obviously
In my opinion documentation examples should become tutorials in the docs, and test examples should move to tests directory. If we really need to we can link from docs to a file in tests directory. We could also keep this examples if you think it's useful, but then this issue would become about organizing it properly and connecting it to docs.
