### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by jbauernberger** [aquasecurity/trivy#3645]
Hi,

I might have missed this in the docs but if not is SSO via external IdP's on the roadmap? 

thanks

**Comment by itaysk** [comment]
Hi, can you please elaborate? there's no sign-on to trivy today so not sure where single sign-on is needed

**Comment by jbauernberger** [comment]
sure thing sorry for being unclear. I was looking at a couple of products that could work in an enterprise setting and so I need RBAC and also SSO integration.

I have not installed trivy so had no idea how it worked. thanks for clarification.

**Comment by itaysk** [comment]
you might be referring to the Aqua product (which is built on top of trivy) which already have SSO.
