### ISSUE TITLE
scanner": "trivy", "error": "error in image inspect: analyze error: failed to analyze layer:

### ISSUE THREAD

**Issue by sreekanthaqua** [aquasecurity/trivy#3661]
When customer is using **Trivy Premium Scanner**, an issue is thrown while reading/walking through a file in one of the layers and that is causing the whole scan to fail. Below is the error that customer saw:

`error in image inspect: analyze error: failed to analyze layer: sha256:30cc3f6e822b8588fd417a2f9f35b6829caff907778e700f2c587c201a1bb137 : walk error: failed to process the file: failed to analyze file: failed to analyze usr/lib/jvm/java-1.8.0-openjdk-1.8.0.352.b08-2.el8_7.ppc64le/jre/lib/ext/cldrdata.jar: unable to open usr/lib/jvm/java-1.8.0-openjdk-1.8.0.352.b08-2.el8_7.ppc64le/jre/lib/ext/cldrdata.jar: failed to open: unable to read the file: read tcp 10.88.0.184:33320->172.16.19.205:443: read: connection reset by peer`

Can you please look into this and fix the issue to continue the scan though a file is not readable/unable to open the file. 

SLK-62411 is reported by customer.

**Comment by knqyf263** [comment]
I think it is the same issue we've fixed.
https://github.com/aquasecurity/trivy/issues/3514

Please reopen it if you still see the same issue with the latest version.
