### ISSUE TITLE
OpenSSL Vulnerability - High

### ISSUE THREAD

**Issue by mlinarik** [aquasecurity/trivy#3681]
Latest Version of Trivy as of 2/23/2023,, DIGEST:sha256:fbf4fd64d54f56d9175ae804839becb7cc7bd45c41abc93bc6c295a99dda2630 

Multiple scanners are detecting multiple vulnerabilities in libssl3, libcrypto3 | openssl |  version 3.0.7-r2. Latest version is 3.0.8-r0.

**Comment by knqyf263** [comment]
We're sure it is no longer relevant. Please feel free to reopen it if you are still seeing them.
