### ISSUE TITLE
Using --config-data  with trivy image

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/trivy#3690]
### Discussed in https://github.com/aquasecurity/trivy/discussions/3658

<div type='discussions-op-text'>

<sup>Originally posted by **JC-19891989** February 20, 2023</sup>
Hi, doing some work with Trivy. 

I find --config-data to be a very useful feature when working with Trivy config as I can use it to load in variables to be used in OPA policies. This string does not seem to work in trivy image like it does with trivy config, even though it's in the rego flags part when you run trivy image --help

Is this right/expected or am I doing something wrong?

It seems to not even parse the command, i.e trivy image --config-data ./nofileatall  alpine runs a successful command.

Thanks</div>

**Comment by knqyf263** [comment]
I think we should clarify the use case first. Even the original reporter doesn't remember it.
https://github.com/aquasecurity/trivy/discussions/3658#discussioncomment-6021893

Please let me close this issue and keep discussing it in https://github.com/aquasecurity/trivy/discussions/3658.
