### ISSUE TITLE
Discrepancy in vulnerabilities count between scannercli and scanner daemon

### ISSUE THREAD

**Issue by sreekanthaqua** [aquasecurity/trivy#3697]
Customer is seeing discrepancy in the vulns counts when scanned an image with deployed scanner vs scannercli and using "T**rivy Premium Scanner**" as the scanner in Aqua CSP. 

**Desired Behavior:**
Trivy should be showing the same vulns count when scanned using a deployed scanner and scannercli. There should not be any discrepancy in the vulns count.

**Comment by knqyf263** [comment]
Please raise the issue in Trivy Premium or break down the issue and open it as an OSS issue.

**Comment by sreekanthaqua** [comment]
@knqyf263 Can you please let me where should I raise this for Trivy Premium? I mean the URL for Trivy Premium wher I can go and raise an issue.

**Comment by knqyf263** [comment]
@tonaim Would you let him know?
