### ISSUE TITLE
License Scanner: Unable to initialize the Java DB: Java DB update failed: Java DB client not initialized

### ISSUE THREAD

**Issue by janbman4** [aquasecurity/trivy#3699]
Hello everyone,

applying the license scanner of Trivy v0.37.3 to Java images results in the error stated in the title.

Here are the commands and the logs:

> / # trivy -v
> Version: 0.37.3
> / # trivy image --download-java-db-only --no-progress
> 2023-02-27T16:12:45.976Z        INFO    Downloading the Java DB...
> 2023-02-27T16:13:46.699Z        INFO    The Java DB is cached for 3 days. If you want to update the database more frequently, the '--reset' flag clears the DB cache.
> / # trivy image --exit-code 0 --format json --scanners license --output license-report.json --license-full eclipse-temurin:17-jre
> 2023-02-27T16:15:57.210Z        INFO    Full license scanning is enabled
> 2023-02-27T16:16:17.867Z        INFO    JAR files found
> 2023-02-27T16:16:17.867Z        ERROR   Unable to initialize the Java DB: Java DB update failed: Java DB client not initialized

As one can see, the scanner starts with a fresh database. However, there is something wrong with the so called Java DB client.
How can the client be configured in order to solve the issue?

Thanks in advance!

Jan

**Comment by DmitriyLewen** [comment]
Hello @janbman4 
Thanks for your report and sorry for wait!

We created #3780 to fix this problem.
We will add changes to next release.

Regards, Dmitriy
