### ISSUE TITLE
Trivy Cache: extend Redis TLS support

### ISSUE THREAD

**Issue by ahalay** [aquasecurity/trivy#3706]
Currently, only TLS with private certificates is supported, but there is no way to use TLS in managed solutions (e.g. AWS Elasticache). 

`go-redis` support this but there is no flag for that
https://redis.uptrace.dev/guide/go-redis.html#using-tls

**Comment by knqyf263** [comment]
Does it fallback to plaintext if the TLS connection fails? If yes, we should pass `&tls.Config{}` anyway, no?

**Comment by ahalay** [comment]
> Does it fallback to plaintext if the TLS connection fails? If yes, we should pass `&tls.Config{}` anyway, no?

Seems like that, I got the next error with out any tls.Config:
```bash
ERROR	unable to store layer info in cache:
    github.com/aquasecurity/trivy/pkg/rpc/server.(*CacheServer).PutBlob
        /home/runner/work/trivy/trivy/pkg/rpc/server/server.go:91
  - unable to store blob information in Redis cache (sha256:2848bf6a868981eab38008d320e26070413abea616bf1657b830b33a86951e68):
    github.com/aquasecurity/trivy/pkg/fanal/cache.RedisCache.PutBlob
        /home/runner/work/trivy/trivy/pkg/fanal/cache/redis.go:53
  - i/o timeout
```

With next TLS config everything works as expected:
```go
TLSConfig: &tls.Config{
    MinVersion: tls.VersionTLS12,
},
```

**Comment by ahalay** [comment]
I checked the empty `&tls.Config{}` and it throws the same error. I think it would be great to have some flag like `--cache-tls` which will allow to enabled TLS without private certs and will not affect existing behavior , maybe something like that:

```go
		if !lo.IsEmpty(c.RedisOptions) {
			caCert, cert, err := utils.GetTLSConfig(c.RedisCACert, c.RedisCert, c.RedisKey)
			if err != nil {
				return Cache{}, err
			}

			options.TLSConfig = &tls.Config{
				RootCAs:      caCert,
				Certificates: []tls.Certificate{cert},
				MinVersion:   tls.VersionTLS12,
			}
		} else if c.CacheTLS {
			options.TLSConfig = &tls.Config{
				MinVersion: tls.VersionTLS12,
			}
		}
```

https://github.com/aquasecurity/trivy/blob/793cc43/pkg/commands/operation/operation.go#L45

**Comment by knqyf263** [comment]
It is a Redis-specific option. How about `--redis-tls`?

**Comment by ahalay** [comment]
> It is a Redis-specific option. How about `--redis-tls`?

Yep, make sense

**Comment by SaurabhAhuja1983** [comment]
We are waiting for this feature to release. Please prioritize.
We are trying to use aws elasticache redis cluster to speed up trivy image scan
