### ISSUE TITLE
[SPDX][TV/JSON] SBOM required field 'Creator' is missing/incorrect

### ISSUE THREAD

**Issue by surendrapathak** [aquasecurity/trivy#3707]
## Description

SPDX required field `Creator` missing or incorrect.

## What did you expect to happen?

Per SPDX spec, `Creator` value should be:
`Creator: "Tool: toolidentifier-version"`

## What happened instead?
`Creator: Tool: trivy`
(version is missing)

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
Version: 0.36.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-02-26 18:06:59.661053459 +0000 UTC
  NextUpdate: 2023-02-27 00:06:59.661053059 +0000 UTC
  DownloadedAt: 2023-02-26 19:37:09.016952 +0000 UTC
```

## Additional details (base image name, container registry info...):
Limited to SPDX, CycloneDX includes version.
Finder: [sbomqs](https://github.com/interlynk-io/sbomqs)

**Comment by DmitriyLewen** [comment]
Hello @surendrapathak 
Thanks for your report!

We created #3756 to add version to `Creator.Tool` field.
After merge this PR we will include it to next release.

Regards, Dmitriy
