### ISSUE TITLE
Initial Golang Detection

### ISSUE THREAD

**Issue by mrueg** [aquasecurity/trivy#371]
A lot of tooling in the container ecosystem is written in Golang, unfortunately there's not an easy way to detect vulnerabilities there.

A first integration attempt could utilize functionality like `go version $binary` (in 1.13.x or https://github.com/rsc/goversion for previous versions) to scan all binaries in a container and report back if they were built with a vulnerable golang version.

**Comment by knqyf263** [comment]
@mrueg Thank you for telling me. It sounds nice idea.

**Comment by Alphasite** [comment]
What about if you include the go.mod file in the image? Similar to how pipe file or poetry lock work?

**Comment by mrueg** [comment]
With go modules in place, you probably don't need that. I've built a small tool that extracts used modules from a go binary. https://github.com/mrueg/go-deconstruct

**Comment by knqyf263** [comment]
Do you know a data source to detect vulnerabilities of Go?

**Comment by Alphasite** [comment]
I think there are a couple here: https://github.com/guardrailsio/awesome-golang-security#vulnerabilities-and-security-advisories

**Comment by mrueg** [comment]
The only one I am aware of is https://github.com/aquasecurity/trivy/issues/400

**Comment by knqyf263** [comment]
Does it include vulnerabilities of Go itself? I found the vulnerabilities of some Go packages like etcd and prometheus.

**Comment by mrueg** [comment]
Unfortunately not, I'm sure that go is tracked in other CVE sources so trivy could invent a "virtual" go package that is installed per binary.

**Comment by Alphasite** [comment]
There are a couple here: https://github.com/guardrailsio/awesome-golang-security#vulnerabilities-and-security-advisories

**Comment by knqyf263** [comment]
I'm working Go binary parser.
https://github.com/aquasecurity/go-dep-parser/pull/19

**Comment by knqyf263** [comment]
Please watch https://github.com/aquasecurity/trivy/issues/958
