### ISSUE TITLE
Fails on `upgradable` or `patchable`

### ISSUE THREAD

**Issue by chezou** [aquasecurity/trivy#372]
Since packages managed by OS, e.g., apt, yum, apk, etc, may have unresolved vulnerabilities. It'd be nice if trivy could have `--fails-on` option which detects there are upgradable/patchable packages and return exit code 1 when there are some fixed ones. This makes us get an actionable alert from CI. This idea came from snyk.io, and would love to have same feature for trivy as well.

**Comment by knqyf263** [comment]
@chezou Thank you for filing an issue. Is `--ignore-unfixed` not enough?

```
$ trivy --ignore-unfixed --exit-code 1 ubuntu:18.04
```

I think this option achieves what you want.

**Comment by chezou** [comment]
Thank you for letting me know. That's the one I wanted to know!
