### ISSUE TITLE
discover sbom in OCI registry

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/trivy#3735]
when scanning a container image, trivy should check if there's an associated SBOM in the registry, and if so, use it instead of analyzing the image, similar to how `trivy image --sbom-source rekor` works. This should be possible with the new OCI Reference types specs.
https://github.com/opencontainers/image-spec/pull/934

**Comment by caozhuozi** [comment]
What would happen if multiple SBOM are attached? Which one will be used?

**Comment by caozhuozi** [comment]
Typically, an image's sbom will be expired in terms of vulnerabilities. So there will be situations that we regularly attaches the SBOM for images?

If so, It is more reasonable to use the latest one by default?

**Comment by itaysk** [comment]
thanks for the suggestion. If I recall correctly, we did discuss this already when building the feature and the challange was that there's no native creation date field in the artifact spec, only [an annotation](https://github.com/opencontainers/image-spec/blob/dd7fd714f5406d39db5fd0602a0e6090929dc85e/annotations.md#pre-defined-annotation-keys] that CAN be added by the artifact submitter. Trivy's [referrer plugin](https://github.com/aquasecurity/trivy-plugin-referrer) does populate this annotation, and therefore [supports sorting artifacts by creation date](https://github.com/aquasecurity/trivy-plugin-referrer/blob/383f3f879f103f9f9e587e7dcf475a4f19c4dcf3/get.go#L125). If you have a good suggestion for how to handle this or want to discuss this further, please open a new feature enhancement discussion.

**Comment by caozhuozi** [comment]
@itaysk  Thank you for providing the detailed background to this question! 💗
