### ISSUE TITLE
Scans failed & giving "not a valid zip file" error

### ISSUE THREAD

**Issue by angularprojects4all** [aquasecurity/trivy#3760]
I think we are loosing basic scan feature here, according to 0.38.0 / 0.38.1
facing issue with python (and or java) based dockers.

the issue remained same irrespective of the option --offline-scan (and / or) --scanners vuln

```
2023-03-03T08:44:43.816Z INFO Vulnerability scanning is enabled
2023-03-03T08:44:43.816Z INFO Secret scanning is enabled
2023-03-03T08:44:43.816Z INFO If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-03-03T08:44:43.816Z INFO Please see also https://aquasecurity.github.io/trivy/v0.38/docs/secret/scanning/#recommendation for faster secret detection

2023-03-03T08:44:49.420Z        INFO    JAR files found
2023-03-03T08:44:49.422Z        INFO    Analyzing JAR files takes a while...
2023-03-03T08:44:49.601Z        FATAL   image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:125335cc58b0044b35fab83684d58e6ce76dd9f466af964e859fbe7bad8e5eea): post analysis error: post analysis error: walk dir error: on file: jar/war/ear/par parse error: zip error: zip: not a valid zip file
```
can you help in this?

**Comment by angularprojects4all** [comment]
--debug option resulted below output

licenses/kafka-manager-6.3.785/activemq-broker-5.17.3.jar"}
2023-03-03T09:46:28.339Z        DEBUG   Parsing Java artifacts...       {"file": "apps/licenses/kafka-manager-6.3.785/activemq-camel-5.16.5.jar"}
2023-03-03T09:46:28.342Z        DEBUG   POM was determined in a heuristic way   {"file": "scala-kafka-client_2.12-2.3.1.jar", "artifact": "com.pirum:scala-kafka-client_2.12:2.3.1"}
2023-03-03T09:46:28.450Z        FATAL   image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:427
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:266
  - scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:660
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:146
  - analyze error:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.Inspect
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:139
  - failed to analyze layer (sha256:e7094ea78db515d46b1340130d00c19c182a675aef4a993cf8917f4170e2e2d2):
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspect.func1
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:242
  - post analysis error:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspectLayer
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:320
  - post analysis error:
    github.com/aquasecurity/trivy/pkg/fanal/analyzer.AnalyzerGroup.PostAnalyze
        /home/runner/work/trivy/trivy/pkg/fanal/analyzer/analyzer.go:483
  - walk dir error:
    github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/java/jar.(*javaLibraryAnalyzer).PostAnalyze
        /home/runner/work/trivy/trivy/pkg/fanal/analyzer/language/java/jar/jar.go:91
  - on file:
    github.com/aquasecurity/trivy/pkg/parallel.walk[...]
        /home/runner/work/trivy/trivy/pkg/parallel/walk.go:97
  - jar/war/ear/par parse error:
    github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/java/jar.(*javaLibraryAnalyzer).PostAnalyze.func2
        /home/runner/work/trivy/trivy/pkg/fanal/analyzer/language/java/jar/jar.go:75
  - zip error:
    github.com/aquasecurity/go-dep-parser/pkg/java/jar.(*Parser).parseArtifact
        /home/runner/go/pkg/mod/github.com/aquasecurity/go-dep-parser@v0.0.0-20230228091112-63a15cdc6bc3/pkg/java/jar/parse.go:82
  - zip: not a valid zip file

**Comment by knqyf263** [comment]
@DmitriyLewen Can we prioritize this issue?

**Comment by DmitriyLewen** [comment]
Hello @angularprojects4all , @lucassaldanha 

Thanks a lot @lucassaldanha  for your example!

I invistigated your image and found strange case - image contains dirs with `*.jar` names.
I created #3773 to skip those directories.

@angularprojects4all, @josephkishan  can you check this case on your image?

Regards, Dmitriy!

**Comment by josephkishan** [comment]
Yes @DmitriyLewen, the same happening in our case

**Comment by DmitriyLewen** [comment]
@josephkishan thanks for your answer!

After PR merge, you will be able to use the canary build (image or binary) before a new release.

**Comment by josephkishan** [comment]
Thanks a lot, @DmitriyLewen for your fast response, we will check once PR is merged.

**Comment by josephkishan** [comment]
@knqyf263 @DmitriyLewen can we see this in the next release? If yes can I know how much time it may take for the release

**Comment by DmitriyLewen** [comment]
Hello @josephkishan 

We will include these changes to next release.
Information about release of v0.39.0 [here](https://github.com/aquasecurity/trivy/milestone/15).

These is canary build( [image](https://github.com/aquasecurity/trivy/pkgs/container/trivy/75157964?tag=canary) or [binary](https://github.com/aquasecurity/trivy/actions/runs/4342921755). You can use it until next release.

**Comment by knqyf263** [comment]
We may cut v0.38.2 this week, but can't promise.
