### ISSUE TITLE
Run trivy for k8s cluster without node-collector

### ISSUE THREAD

**Issue by cijujoseph** [aquasecurity/trivy#3769]
I'm looking to use the trivy cli to scan my k8s cluster (EKS) for vulnerabilities. However security policies we have in our cluster is preventing the node-collector from running. How do I get trivy to scan my whole cluster without running the node-collector? The command I am using is,

`trivy k8s cluster --scanners=vuln --report=summary --timeout 20m`

Error

```FATAL	get k8s artifacts error: running node-collector job: warning event received: Error creating: pods "node-collector-5c96f9cfb9-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[6]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[7]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[8]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[9]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [{1 65535}] spec.containers[0].securityContext: Invalid value: []int64{0}: group 0 must be in the ranges: [{1 65535}]] (FailedCreate)```

**Comment by greg-peters** [comment]
```trivy k8s cluster --scanners=vuln --report=summary --timeout 20m``` should not allow a kubernetes job on nodes there a given architecture is not supported... linux/arm... etc... or at least allow configuration of a nodeSelector via the cli
