### ISSUE TITLE
On cluster scan node-collector pods' status OutOfcpu (GKE)

### ISSUE THREAD

**Issue by evr3n** [aquasecurity/trivy#3776]
## Description

I'm trying to scan a GKE cluster with `trivy k8s cluster --compliance=k8s-nsa --report summary --format json --timeout 32000s cluster` that fails with `FATAL get k8s artifacts error: running node-collector job: runner received timeout`. When checking for the node-collector pods with `kubectl get pods -n trivy-temp`I see that the status of all of these pods is OutOfcpu. These commands work on a local kind cluster without problems. 

## What did you expect to happen?
I expected a cluster scan to be performed.

## What happened instead?
The scan fails with a FATAL error.

## Output of run with `-debug`:

```
~ trivy k8s cluster --compliance=k8s-nsa --report summary --timeout 3600s --debug
2023-03-06T15:39:09.659+0100	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-03-06T15:44:18.489+0100	FATAL	get k8s artifacts error:
    github.com/aquasecurity/trivy/pkg/k8s/commands.clusterRun
        github.com/aquasecurity/trivy/pkg/k8s/commands/cluster.go:22
  - running node-collector job: runner received timeout
```

## Output of `trivy -v`:

```
Version: 0.38.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-03-06 06:07:26.478918861 +0000 UTC
  NextUpdate: 2023-03-06 12:07:26.478917961 +0000 UTC
  DownloadedAt: 2023-03-06 11:01:26.423561 +0000 UTC
Policy Bundle:
  Digest: sha256:19a017cdc798631ad42f6f4dce823d77b2989128f0e1a7f9bc83ae3c59024edd
  DownloadedAt: 2023-03-06 11:01:28.978318 +0000 UTC
```

**Comment by chen-keinan** [comment]
Related #3771  #3766
