### ISSUE TITLE
Secrets not detected with trivy image

### ISSUE THREAD

**Issue by jemag** [aquasecurity/trivy#3778]
## Description

Secrets are not being detected from image using `trivy image IMAGE --debug --scanners secret`

For example, given the following Dockerfile:
```Dockerfile
FROM nginx:alpine

COPY test.txt /test.txt

ENV AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKE"
ENV AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"

CMD ["nginx", "-g", "daemon off;"]
```
and the file text.txt:
```
AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKE"
AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"

```

Running `trivy fs ./` will at least detect one of the secret (not quite sure why `AWS_SECRET_ACCESS_KEY` is not detected here as well):
![image](https://user-images.githubusercontent.com/7985687/223233233-065d5732-0f51-4b31-9f5f-c4ada5131b6c.png)

Scanning the image however results in no secret detected:
![image](https://user-images.githubusercontent.com/7985687/223233294-5fd5682f-00d3-4a39-84ba-3168b9e2ea15.png)

Judging by https://github.com/aquasecurity/trivy/issues/2204, I would assume that trivy should be able to detect those secrets both from the file and the `ENV` directives
## What did you expect to happen?
Secrets to be detected

## What happened instead?
Nothing detected

## Output of run with `-debug`:

```
2023-03-06T16:19:35.669-0500    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-03-06T16:19:35.675-0500    DEBUG   cache dir:  /home/jemag/.cache/trivy
2023-03-06T16:19:35.675-0500    INFO    Secret scanning is enabled
2023-03-06T16:19:35.675-0500    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-03-06T16:19:35.675-0500    INFO    Please see also https://aquasecurity.github.io/trivy/v0.38/docs/secret/scanning/#recommendation for faster secr
t detection
2023-03-06T16:19:35.680-0500    DEBUG   No secret config detected: trivy-secret.yaml
2023-03-06T16:19:35.680-0500    DEBUG   Image ID: sha256:38dc5b0df0119047a3dd01f5df78352ed4a7df495fcb9c5b9a6dcb27d55ce17a
2023-03-06T16:19:35.680-0500    DEBUG   Diff IDs: [sha256:7cd52847ad775a5ddc4b58326cf884beee34544296402c6292ed76474c686d39 sha256:d8a5a02a8c2d1e625a89a
956f6773baad42859509fb06b6c2e53b0ee3576dfd sha256:5e59460a18a391d945829d29a9b295b1c2fdeb0d09d1764012736698cacbdcc2 sha256:152a948bab3b2e19f92a88342da9b
271b1e2879272ecdad2200eb59159ea624 sha256:c4d67a5827ca405b493275f4e9df7d5e97f78ecb4bf48d77299e1175cb1dbcc4 sha256:f1bee861c2ba8de7590cbc91799d2bb8a3579
cf1d1519c2445bd2d385338787 sha256:042cd3f87f43b1dea43047cd1d4394440122cb2a14ffed326fad8b34d25660fd sha256:2d3592214552618bb62032797578c5f047e2a82abddd5
3ba3188b2ff342813e]
2023-03-06T16:19:35.680-0500    DEBUG   Base Layers: [sha256:7cd52847ad775a5ddc4b58326cf884beee34544296402c6292ed76474c686d39 sha256:d8a5a02a8c2d1e625a
9a4956f6773baad42859509fb06b6c2e53b0ee3576dfd sha256:5e59460a18a391d945829d29a9b295b1c2fdeb0d09d1764012736698cacbdcc2 sha256:152a948bab3b2e19f92a88342d
9b5271b1e2879272ecdad2200eb59159ea624 sha256:c4d67a5827ca405b493275f4e9df7d5e97f78ecb4bf48d77299e1175cb1dbcc4 sha256:f1bee861c2ba8de7590cbc91799d2bb8a3
79bcf1d1519c2445bd2d385338787]

```

## Output of `trivy -v`:

```
Version: 0.38.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-03-06 18:07:31.47013232 +0000 UTC
  NextUpdate: 2023-03-07 00:07:31.47013172 +0000 UTC
  DownloadedAt: 2023-03-06 20:17:57.816456938 +0000 UTC
Policy Bundle:
  Digest: sha256:19a017cdc798631ad42f6f4dce823d77b2989128f0e1a7f9bc83ae3c59024edd
  DownloadedAt: 2023-03-06 17:18:32.288960253 +0000 UTC

```

## Additional details (base image name, container registry info...):
Running the container, we can clearly see that the file is there:
![image](https://user-images.githubusercontent.com/7985687/223233605-77e27a9f-85eb-424f-bd43-1638b7153356.png)
And the env variables:
![image](https://user-images.githubusercontent.com/7985687/223233723-84a8e2f7-9887-4d6a-ae2f-346d6fdd90c6.png)

**Comment by afdesk** [comment]
@jemag thanks for your report!
I found one problematic place, will fix it

**Comment by afdesk** [comment]
@jemag  there are at least two issues here:
1. your AWS_SECRET_ACCESS_KEY has incorrect length (39 symbols), so Trivy doesn't detect it. I've create a PR to change this behavior.

2. For secret scanning on container image config you need to use `--image-config-scanners secret`:

```sh
$ trivy image issue:3778 --image-config-scanners secret
...
issue:3778 (secrets)

Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 1)

CRITICAL: AWS (aws-access-key-id)
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Access Key ID
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 issue:3778:129
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 127     "NJS_VERSION=0.7.9",
 128     "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKE",
 129 [   "AWS_ACCESS_KEY_ID=********************"
 130     ],
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────



```

**Comment by afdesk** [comment]
@jemag in any case, as a workaround to fix the first issue you can use the custom rule with regex from my PR right now.

**Comment by jemag** [comment]
Thank you for the clarification. I have to say that it is not necessarily the most intuitive experience that:
- `trivy image IMAGE --debug --scanners secret` will detect secrets but not ones from the image configuration
- `trivy fs` will detect secrets including ones in the Dockerfile configuration
- `trivy config` will detect misconfiguration but not secrets in the Dockerfile configuration
- and finally `trivy image --image-config-scanners secret` will be the one detecting secrets in the Dockerfile configuration

It might just be be, but the whole language use around these and the different uses of config, misconfiguration, and image-config-scanner is not the most intuitive.

---
Coming back to the problem, shouldn't the file containing the `AWS_ACCESS_KEY_ID` still be detected by `trivy image IMAGE --debug --scanners secret`? Especially since it is already detected properly by `trivy fs ./`?

**Comment by afdesk** [comment]
@jemag 

`secret` scanner can take a lot of time, so we need a way to disable it.

The `--scanners` flag defines scanners for files in container images. 

`--image-config-scanners` can configure scanners for metadata of container images.

**Comment by afdesk** [comment]
> shouldn't the file `test.txt` containing the `AWS_ACCESS_KEY_ID` still be detected by `trivy image IMAGE --debug --scanners secret`?

yes, sure. you're right. Trivy has to detect secrets inside files, and Trivy does it )
but Trivy skips test data...

if you change a file name (eg. to `tst.txt`), Trivy will catch it:

```Dockerfile
FROM nginx:alpine

COPY test.txt /tst.txt

ENV AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKE"
ENV AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"

CMD ["nginx", "-g", "daemon off;"]
```
and then:
```sh
$ docker build -t issue:3778 .
$ trivy image --scanners secret issue:3778
2023-03-14T18:10:53.722+0600	INFO	Secret scanning is enabled
2023-03-14T18:10:53.722+0600	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-03-14T18:10:53.722+0600	INFO	Please see also https://aquasecurity.github.io/trivy/v0.38/docs/secret/scanning/#recommendation for faster secret detection
2023-03-14T18:10:53.725+0600	INFO	Loading trivy-secret.yaml for secret scanning...

/tst.txt (secrets)

Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 2)

CRITICAL: AWS (aws-access-key-id)
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Access Key ID
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 /tst.txt:2 (added by 'COPY file:ecb0d0b259fbaa26a9bad3142326d2')
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   AWS_SECRET_ACCESS_KEY=****************************************
   2 [ AWS_ACCESS_KEY_ID=********************
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


CRITICAL: AWS (aws-secret-access-key)
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Secret Access Key
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 /tst.txt:1 (added by 'COPY file:ecb0d0b259fbaa26a9bad3142326d2')
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 [ AWS_SECRET_ACCESS_KEY=****************************************
   2   AWS_ACCESS_KEY_ID=********************
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


```

**Comment by afdesk** [comment]
it seems we clarified all your questions, isn't?

**Comment by jemag** [comment]
@afdesk Thank you for the clarification. I guess part of the confusion came from the fact that it was detected with `trivy fs` and not `trivy image`. From this issue https://github.com/aquasecurity/trivy/issues/3801, it seems it was detected with `trivy fs` because it is not in a sub-folder. Any particular reason to only exclude it in sub-folders?

> There are mainly two targets, and you can configure scanners for them respectively.
	    File contents (in container images, filesystem, etc.)
	        --scanners
	    Metadata (of container images)
	        --image-config-scanners

@knqyf263 I might be the only one getting confused by the `config` within `trivy config` and the `config` in `--image-config-scanners`, so feel free to take this with a grain of salt, however perhaps avoiding that word and going with something like `--image-metadata-scanners` could still reflect the intent while avoiding the re-use of the word `config`?

**Comment by knqyf263** [comment]
>however perhaps avoiding that word and going with something like --image-metadata-scanners could still reflect the intent while avoiding the re-use of the word config?

Thanks for your suggestion. The flag name was originally `--image-metadata-scanners`, but what Trivy is scanning is technically image config. Then, we switched to `--image-config-scanners` for better accuracy. But your confusion also makes sense. We may add `--image-metadata-scanners` as an alias.

**Comment by afdesk** [comment]
> From this issue #3801, it seems it was detected with `trivy fs` because it is not in a sub-folder. Any particular reason to only exclude it in sub-folders?

ah, you're right. it seems there is a mistake in regex for test cases.

**Comment by knqyf263** [comment]
We'll keep discussing the naming. Thanks for your feedback.
