### ISSUE TITLE
Trivy errors even on air gapped environment

### ISSUE THREAD

**Issue by admodev** [aquasecurity/trivy#3779]
## Description

Trivy throws an error scanning some packages from a simple war/ear sca even within an air gapped environment, we have cleared and downloaded cache DB, used `--offline-scan` flag and it throws an error while scanning some packages anyways. It is curious that it isn't constant, it may throw an error with package "A" now, run the scan again and it may pass the package "A" scan and throw an error on package "B"...

## What did you expect to happen?

I expect to have a successful scan like we had when we where using versions prior to latest.

## What happened instead?

We have random errors while scanning war's\ear's even in an air gapped environment.

## Output of run with `-debug`:

```
 walk error: failed to process the file: failed to analyze file
```

## Output of `trivy -v`:

```
v0.38.1
```

## Additional details (base image name, container registry info...):

We have a cronjob that automatically pulls and builds the latest version of our base images and tools, and trivy is one of them, so it will always be in it's latest version.

**Comment by knqyf263** [comment]
Need more detailed errors. Or please share JAR to reproduce the issue.

**Comment by admodev** [comment]
More details than i already provided? And i can't share the JAR with you, it is private and belongs to the company where i work...
