### ISSUE TITLE
Does trivy have a license scanner for PHP in composer.json/composer.lock files

### ISSUE THREAD

**Issue by s2504s** [aquasecurity/trivy#3785]
Hi there!
I would like to know does trivy have a license scanner for PHP in composer.json/composer.lock files. I tried to check it but no luck - result of scan is empty (I scanned it in both modes - fs and image) Or should I install the composer dependency first?
Thanks in advance

**Comment by knqyf263** [comment]
License detection is not supported for PHP now.

**Comment by s2504s** [comment]
Could you share with me if you have any plans to implement this feature?
