### ISSUE TITLE
scan golang binaries for dependency vulnerabilities

### ISSUE THREAD

**Issue by dirkmueller** [aquasecurity/trivy#3786]
trivy can identify vulnerable dependencies of golang projects if it finds a go.mod/go.sum file in the container or filesystem. it can however not detect it in compiled golang binaries. however, that information is embedded in the binaries and can be extracted via "go version -m /path/to/binary" (the corresponding scanner is probably available as go module somewhere). 

it would be useful to have alerts based on binaries and their embedded module dependency information.

**Comment by knqyf263** [comment]
It is supported
https://aquasecurity.github.io/trivy/v0.41/docs/scanner/vulnerability/language/golang/
