### ISSUE TITLE
[doc] Document pull behavior + all possible ways to pass credentials

### ISSUE THREAD

**Issue by heidemn** [aquasecurity/trivy#379]
Split from #378 .
The following details seem worth documenting:
* When does Trivy try to pull the image to scan?
   (After testing a bit, I assume that if only pulls the image if not present in local Docker.)
* If Trivy pulls an image, will it 1. be stored in Docker afterwards, or 2. does it only live temporarily inside Trivy? (It seems that 2. is true.)
* Private images/credentials:
  Instead of providing e.g. an AWS API key for ECR, you can run "docker login" yourself.
  Trivy will then use `$HOME/.docker/config.json` to pull the image.
  When running Trivy in Docker, you have to mount `-v $HOME/.docker/config.json:/root/.docker/config.json` to make this work.

**Comment by sanjana1604** [comment]
@heidemn I would like to contribute.

**Comment by krol3** [comment]
@heidemn @sanjana1604  we are using mkdocs now and improve some items. could you review if it's still happening?
