### ISSUE TITLE
Do not silently ignore additional CLI arguments

### ISSUE THREAD

**Issue by heidemn** [aquasecurity/trivy#380]
Split from #378 .
* Current state: `trivy [options] IMAGE1 IMAGE2 ...` scans IMAGE1, and silently ignores all following images.
* Preference mine: Either support multiple images, or abort with an error if more than 1 is supplied.
* Preference @knqyf263: Show a warning that additional images will be ignored.

**Comment by tnir** [comment]
> Preference mine: Either support multiple images, or abort with an error if more than 1 is supplied.

👍

**Comment by knqyf263** [comment]
OK. I implemented to abort Trivy with an error if more than 1 image is specified.

**Comment by tnir** [comment]
Thanks 😄
