### ISSUE TITLE
All info messages should be written to stderr instead of stdout

### ISSUE THREAD

**Issue by heidemn** [aquasecurity/trivy#381]
**Description**

When running Trivy in Docker, it would be convenient to be able to pipe the output from stdout, instead having to use `-o FILENAME`. Then the user doesn't have to fiddle with mounting directories, permissions, etc.

I think it's standard behavior of all Unix-ish tools to write only the "main" output to stdout, and everything else to stderr.

So I would expect that the following commands yield the same result in the file `OUT`:
```
$ trivy -o OUT IMAGE
$ trivy        IMAGE >OUT
```

**What did you expect to happen?**
```
$ trivy --format template --template "MainOutput {{ range . }} {{ .Target }} {{ end }}" \
      golang:1.12-alpine >out.log 2>err.log

-----------------------
$ cat out.log 
MainOutput  golang:1.12-alpine (alpine 3.11.3)

-----------------------
$ cat err.log
2020-01-22T20:07:46.304Z	INFO	Need to update DB
2020-01-22T20:07:46.305Z	INFO	Downloading DB...
...
611.58 KiB / 14.70 MiB [------>_____...___] 4.06% 966.06 KiB p/s ETA 14s
...
2020-01-22T20:08:00.395Z	INFO	Reopening DB...
2020-01-22T20:08:43.963Z	INFO	Detecting Alpine vulnerabilities...
```

**What happened instead?**

```
$ cat out.log 
2020-01-22T20:07:46.304Z	INFO	Need to update DB
2020-01-22T20:07:46.305Z	INFO	Downloading DB...
2020-01-22T20:08:00.395Z	INFO	Reopening DB...
2020-01-22T20:08:43.963Z	INFO	Detecting Alpine vulnerabilities...
MainOutput  golang:1.12-alpine (alpine 3.11.3)

-----------------------
$ cat err.log
...
611.58 KiB / 14.70 MiB [------>_____...___] 4.06% 966.06 KiB p/s ETA 14s
...
```

**Output of run with `-debug`:**
(not relevant)

**Output of `trivy -v`:**

```
trivy version 0.4.2
```

**Additional details (base image name, container registry info...):**
(not relevant)

**Comment by DreadPirateShawn** [comment]
Another use-case -- attempting to send `--format=json` to something like `jq`.

**Current workaround:** Basically `| grep -vE "^2020-12"` -- technically `| grep -vE "^$(date '+%Y-%m')"` -- which is doable but really awkward/messy, and may break if a trivy update happens to add other noise to the stdout.

**Comment by carpioldc** [comment]
Hi! Just for info, I came across this issue on version 0.18.1.
