### ISSUE TITLE
Secret Scan ignoring Python file in "usr/local/lib/pythonx.x" folder

### ISSUE THREAD

**Issue by nikithaguduru** [aquasecurity/trivy#3830]
Scan **ashex/pokemongo-map:latest** from **DockerHub** . Check for below sensitive files . You will not see them as this path is disallowed as per **built-in-allow** rules for secret scan. Is this expected?i f yes, Can you mention the reason for disallowing this path?
![image](https://user-images.githubusercontent.com/12510569/224898141-e3381066-6296-4a90-ac53-2bfd794991bf.png)

**Comment by afdesk** [comment]
@nikithaguduru thanks for the question.
yes, Trivy has several `built-in` rules...

but you can disable them via config file.

I managed to scan secrets inside `ashex/pokemongo-map:latest`
```sh
$ trivy image --scanners secret --secret-config <path to>/trivy-secret.yaml ashex/pokemongo-map:latest
```

You can use `trivy-secret.yaml`:
```yaml
disable-allow-rules:
  - tests
  - usr-dirs
  - locale-dir
  - python
```
Read more [With configuration file](https://aquasecurity.github.io/trivy/v0.27.1/docs/secret/examples/#with-configuration-file)

**Comment by afdesk** [comment]
I close the issue.
please feel free to reopen it if any questions arise
