### ISSUE TITLE
Add base image layer detection to compliance scanning

### ISSUE THREAD

**Issue by Mo0rBy** [aquasecurity/trivy#3834]
I raised issue #3814 due to false positives on docker-cis compliance scanning. The false positives were from a `HEALTHCHECK` layer and a bunch of `ADD` layers in the base image. The `HEALTHCHECK` false positive has been dealt with in said issue, but @knqyf263 has asked that I raise a new feature request to add the`guessBaseLayers` functionality to the docker-cis compliance scanning, to remove all the false positives of `ADD` layers in the base image.
https://github.com/aquasecurity/trivy/blob/3987a679f9520259a1b1474e81704b8aedce2ef7/pkg/fanal/artifact/image/image.go#L496

**Comment by roi-orca** [comment]
I opened a similar issue
https://github.com/aquasecurity/trivy/issues/3792

**Comment by lior-orca** [comment]
Similar issue - https://github.com/aquasecurity/trivy/issues/3792
