### ISSUE TITLE
Exclude yarn scan

### ISSUE THREAD

**Issue by axi92** [aquasecurity/trivy#3838]
Is it possible to exclude yarn.lock files?
I tried it with that `trivy fs --skip-files "*yarn.lock" .` but that did not work.

**Comment by DmitriyLewen** [comment]
Hello @axi92 
Trivy currently doesn't support patterns for `--skip-files/skip-dirs` flags.

To skip found vulns  you can use `--ignore-policy` flag with `rego rules`.
Information about it [here](https://aquasecurity.github.io/trivy/v0.38/docs/vulnerability/examples/filter/#by-open-policy-agent).
Looks like in your case help simple rules. Something like that:
```rego
package trivy

default ignore = false

ignore {
	endswith(input.PkgPath, ".yarn.lock")
}
            
```

**Comment by knqyf263** [comment]
As @DmitriyLewen explained, you need to pass the exact pass to `--skip-files` now.

**Comment by knqyf263** [comment]
Supported in https://github.com/aquasecurity/trivy/pull/3866
