### ISSUE TITLE
Can't scan host images

### ISSUE THREAD

**Issue by aleksandrovpa** [aquasecurity/trivy#384]
**Description**

**What did you expect to happen?**
Output of trivy with vulnerabilities

**What happened instead?**
FATAL	error in image scan: failed to analyze image: failed to extract files: failed to get the v2 manifest: missing signature key

**Output of run with `-debug`:**

```
2020-01-23T13:35:29.813Z	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  2020-01-23T13:35:29.813Z	DEBUG	cache dir:  /root/.cache/trivy
  2020-01-23T13:35:29.813Z	DEBUG	DB update was skipped because DB is the latest
  2020-01-23T13:35:29.813Z	DEBUG	DB Schema: 1, Type: 1, UpdatedAt: 2020-01-23 12:06:34.549901507 +0000 UTC, NextUpdate: 2020-01-24 00:06:34.549901307 +0000 UTC
  2020-01-23T13:35:29.813Z	DEBUG	Vulnerability type:  [os library]
  2020-01-23T13:35:30.631Z	FATAL	error in image scan:
      github.com/aquasecurity/trivy/internal/standalone.run
          /home/circleci/project/internal/standalone/run.go:75
    - failed to analyze image:
      github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanImage
          /home/circleci/project/pkg/scanner/scan.go:82
    - failed to extract files:
      github.com/aquasecurity/fanal/analyzer.Config.Analyze
          /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20200112144021-9a35ce3bd793/analyzer/analyzer.go:126
    - failed to get the v2 manifest:
      github.com/aquasecurity/fanal/extractor/docker.getValidManifest
          /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20200112144021-9a35ce3bd793/extractor/docker/docker.go:285
    - missing signature key
  Process exited with code 1
```

**Output of `trivy -v`:**

```
trivy version 0.4.3
Docker version 18.06.3-ce, build d7080c1
```

**Additional details (base image name, container registry info...):**
We use Azure Container Registry and we wanna scan our images before pushing them to ACR.
I a little bit analyse code and found, that trivy every time trying to login into registry (think it shouldn't be) All ENV provided correctly.
One more point, we build our image within docker container <A>, which running on a host machine \
and then we want to run image with trivy, within container <A>.
So we've tried to do like here `$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \ aquasec/trivy $Image` but trivy going to ACR at first, and return error that couldn't find image in registry. And we should provide credentials for ACR, think shouldn't if we want to use only local images

**Comment by knqyf263** [comment]
Does it happen with the latest version, v0.4.3 as well? And, would you paste a result of `docker version`?

**Comment by aleksandrovpa** [comment]
my mistake, i've updated correct versions of Docker and Trivy at the top.
Docker version 18.06.3-ce, build d7080c1
trivy version 0.4.3

**Comment by aleksandrovpa** [comment]
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by knqyf263** [comment]
Trivy uses Docker client v1.39, which is newer than your version, v1.38. Docker Engine rejects newer version. Could you update the version of Docker Engine to 18.09 or newer?

We may support v1.38 in the future, but we're not sure when we work on it.

**Comment by aleksandrovpa** [comment]
Looks like it helps. will update our agent and came back with results.
Thank you so much!

**Comment by knqyf263** [comment]
Sure thing. We apologize for the inconvenience.
