### ISSUE TITLE
Trivy supports dependency hierarchies in SBOMs

### ISSUE THREAD

**Issue by bardenstein** [aquasecurity/trivy#3860]
When I generate SBOMs from Trivy (in either CycloneDX or SPDX), the resulting SBOM files don't show the dependency hierarchies (i.e. the tree relationships between libraries) that other generators do (like the open-sbom-generator). 

I want/need to be able to see, for a given vulnerable library, how it was introduced into an asset.

Ex:
- Dependency 1 (has a CVE)
- - introduced by dep 2
- - - introduced by dep 3
- - - - introduced by dep 4, which is a top-level library / root node.

**Comment by itaysk** [comment]
Duplicate of #2451
