### ISSUE TITLE
Trivy K8s Compliance Scan Failing Mount

### ISSUE THREAD

**Issue by schuman0** [aquasecurity/trivy#3862]
## Description

When running a K8s compliance scan we run into an error that the BackoffLimitExceeded after some time. This looks to be due to the containers failing to mount kube-root-ca.crt 

## What did you expect to happen?

The scan to succeed

## What happened instead?

the job fails with error: warning event received: Job has reached the specified backoff limit (BackoffLimitExceeded)

## Output of run with `-debug`:

$ trivy k8s cluster -f json -o trivyk8s.json --report=all --timeout 120m --compliance=k8s-cis -d
DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
E0316 17:29:38.732470      29 memcache.go:255] couldn't get resource list for custom.metrics.k8s.io/v1beta1: Got empty response for: custom.metrics.k8s.io/v1beta1
2023-03-16T17:45:08.253Z	FATAL	get k8s artifacts with node info error:
    github.com/aquasecurity/trivy/pkg/k8s/commands.clusterRun
        /home/runner/work/trivy/trivy/pkg/k8s/commands/cluster.go:27
  - running node-collector job: warning event received: Job has reached the specified backoff limit (BackoffLimitExceeded)

## Output of `trivy -v`:

-bash-4.2# ./trivy -v
Version: 0.38.3
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-02-15 12:07:59.958877012 +0000 UTC
  NextUpdate: 2023-02-15 18:07:59.958876612 +0000 UTC
  DownloadedAt: 2023-02-15 14:24:58.6670585 +0000 UTC

## Additional details (base image name, container registry info...):

When looking at the events for the trivy-temp namespace I see this repeating over and over:

2m16s       Normal    SuccessfulCreate   job/node-collector-84b5f6566c         Created pod: node-collector-84b5f6566c-c4b7r
2m8s        Normal    Completed          job/node-collector-84b5f6566c         Job completed
14s         Normal    Pulled             pod/node-collector-859d877857-x4fdr   Container image "ghcr.io/aquasecurity/node-collector:0.0.5" already present on machine
14s         Normal    Created            pod/node-collector-859d877857-x4fdr   Created container node-collector
12s         Normal    Started            pod/node-collector-859d877857-x4fdr   Started container node-collector
8s          Warning   FailedMount        pod/node-collector-859d877857-x4fdr   MountVolume.SetUp failed for volume "kube-api-access-6s6dj" : object "trivy-temp"/"kube-root-ca.crt" not registered
17s         Normal    SuccessfulCreate   job/node-collector-859d877857         Created pod: node-collector-859d877857-x4fdr
8s          Normal    Completed          job/node-collector-859d877857         Job completed

**Comment by schuman0** [comment]
This was resolved for me in the most recent release

**Comment by knqyf263** [comment]
@schuman0 Thanks for confirming!
