### ISSUE TITLE
Skip error files in file walk

### ISSUE THREAD

**Issue by behara** [aquasecurity/trivy#3863]
While doing a file walk with fs scan. I see we stop the scan with err when we couldn't open any file.

## What did you expect to happen?

I expected the scan should continue even when there is an err while opening the file. This can happen since other processes may be using. See the below screen shot

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/16453290/225830716-63a4cc27-3876-4a0c-b76a-5b262f9058f2.png)

## What happened instead?

scan failed with an err stating couldn't open file

## Output of run with `-debug`:

![Screenshot from 2023-03-17 12-11-45](https://user-images.githubusercontent.com/16453290/225831638-c5b315dd-36a3-4d9b-b5e1-a8a551d714f3.png)

## Output of `trivy -v`:

![Screenshot from 2023-03-17 12-13-09](https://user-images.githubusercontent.com/16453290/225831847-623b195f-e798-427b-94f5-885fd909cc51.png)

**Comment by knqyf263** [comment]
I don't think it's a bug. If we skip the file, the scan result differs depending on the file locks. I think the result should be consistent. If some files are unavailable, it makes sense to return an error.

**Comment by knqyf263** [comment]
We may add an option to ignore such errors like https://github.com/aquasecurity/trivy/issues/3869.

**Comment by knqyf263** [comment]
Do you want to ignore any kind of errors or specific errors only?

**Comment by behara** [comment]
@knqyf263 can we have both kinds of customisation implemented ?. We need both for our use case.

**Comment by knqyf263** [comment]
We just check if the specified string is included in errors. Is it enough for you?

**Comment by Juliavol** [comment]
will it be possible to skip specific errors?
for instance a false positive error on a specific file?
