### ISSUE TITLE
Ignore Invalid Zip Files

### ISSUE THREAD

**Issue by baswerc** [aquasecurity/trivy#3869]
Would it be possible to add an option that tells trivy to log and ignore any file that looks like a zip file but is not instead of ending the scan with an error?

**Comment by fawind** [comment]
+1 on this. To add some more context, there are a few situations where this is causing problems for us:

1) **False positives:** There are cases where Trivy assumes files to be an archive that actually aren't, resulting in Trivy erroring-out. A concrete example is that Trivy treats `.par` files as an extractable JAR archive. However within the context of OracleDB, a `.par` file is often present as a regular "parameter file" ([source](https://docs.oracle.com/cd/B10501_01/server.920/a96533/statspac.htm)) and Trivy fails trying to extract it.
2) **Bundled third-party software**: We frequently bundle third party software in our container images and unfortunately its quite common for them to bundle malformed or proprietary files that when Trivy assumes its just a zip it won't be able to read it.

Both cases result in Trivy erroring out and not reporting any CVEs for such images. We can work around this by telling Trivy to skip such files or directories. But when doing scans automatic and at a larger scale, it is hard to keep up and maintain such a list of "known bad files". Having an option to ignore such errors, would allow us to still expose all the other CVEs found in an image without blocking the scan until a human intervenes and fixes the situation.

**Comment by itaysk** [comment]
perhaps with `--skip-files` flag? cc: @simar7

**Comment by gms1** [comment]
alternatively, trivy should check whether a zip header exists and only then assume that it is a zip
currently it assumes that every file with a par extension is also a zip file although this extension may be in use for various other types of files

**Comment by simar7** [comment]
Hi @baswerc we recently released a new feature where it should be possible to specify globs as part of skipping files or directories. 

You could do something like: --skip-files="**/*.zip" to ignore any file with the dot zip extension. 

You can read more on this here: https://aquasecurity.github.io/trivy/v0.40/docs/vulnerability/examples/others/

**Comment by baswerc** [comment]
Hi @simar7 thanks for the tip. I was still hoping trivy would process valid zip file just that it would ignore any files that looked like zip files but weren't, instead of ending the scan error.

**Comment by simar7** [comment]
> I'm hoping the fact that #3863 and #4038 have been closed means this is fixed.  I was planning on trying v0.40.0, but that version only has the --skip-files globbing added and doesn't mention #3863 and #4038 in the change logs of the release page.

That change you mentioned should be in the new release but @knqyf263  can maybe confirm that.
