### ISSUE TITLE
Trivy pom analyzer and maven repo

### ISSUE THREAD

**Issue by bameur** [aquasecurity/trivy#3898]
Hello.

The problem:
In the case of using trivy on a container, the resolution of maven dependencies in the case of a pom type analysis is not effective
Proposal:
Can you add in the documentation the search paths of the local repos for the resolution of the maven.
the [code (go-dep-parser/pkg/java/pom/settings.go)](https://github.com/aquasecurity/go-dep-parser/blob/2172dc21824124196c02ba7696a61d7ccde08809/pkg/java/pom/settings.go#L15) currently used is:

![image](https://user-images.githubusercontent.com/10002139/227477196-46d7613c-9683-4a59-a0fc-f0201a5ec807.png)

and indicated the remote repo used declared in the [parser (go-dep-parser/pkg/java/pom/parse.go)](https://github.com/aquasecurity/go-dep-parser/blob/2172dc21824124196c02ba7696a61d7ccde08809/pkg/java/pom/parse.go#L25) file.

Thank you very much for your work.

**Comment by lsoumille** [comment]
Hello,

This work has helped me when setting up Java project scanning from a trivy container https://aquasecurity.github.io/trivy/v0.38/docs/vulnerability/languages/java/

Thanks,

**Comment by knqyf263** [comment]
Thanks @lsoumille
