### ISSUE TITLE
get k8s artifacts with node info error: invalid character 'f' after top-level value

### ISSUE THREAD

**Issue by haoyu1101** [aquasecurity/trivy#4011]
Hi, 

Seeing this issue when running the trivy Kubernetes cluster check: 
![image](https://user-images.githubusercontent.com/85282645/230780957-bde109f4-675b-4ce9-8921-e126031e95fa.png)

Running the command with --debug: 

 github.com/aquasecurity/trivy/pkg/k8s/commands.clusterRun                                                                                                                                                               /home/runner/work/trivy/trivy/pkg/k8s/commands/cluster.go:27                                                                                                                                                  - invalid character 'f' after top-level value       

Could you share some thoughts on this error? 

thanks!

**Comment by haoyu1101** [comment]
Trivy-v command output: 
![image](https://user-images.githubusercontent.com/85282645/230781207-85a56d53-27ab-47c0-b9d6-045001fc9f04.png)

**Comment by chen-keinan** [comment]
@haoyu1101 thank you for the feedback , could you share more details , such env. cloud provider or hosted k8s version and etc

**Comment by haoyu1101** [comment]
was trying to execute the very first scan command for Kubernetes: trivy k8s --report=summary cluster. The error appears, but it works for the namespace scan command: trivy k8s -n kube-system --report=summary all

**Comment by chen-keinan** [comment]
> 
> kubectl version for both client and server: Major:"1", Minor:"23"

do you have a way to test it on local cluster `kind` or else , wonder if it is env. issue

**Comment by haoyu1101** [comment]
I have executed the namespace scan; it works fine: 
![image](https://user-images.githubusercontent.com/85282645/230870609-994fbcb8-205b-4c5f-944b-e7dbc374bd23.png)

**Comment by chen-keinan** [comment]
> I have executed the namespace scan; it works fine: ![image](https://user-images.githubusercontent.com/85282645/230870609-994fbcb8-205b-4c5f-944b-e7dbc374bd23.png)

yes I know , namespace work differently , it doesn't scan node

**Comment by haoyu1101** [comment]
ahhh, ok. Are there any other configurations we can check to debug the issue?

**Comment by chen-keinan** [comment]
> ahhh, ok. Are there any other configurations we can check to debug the issue?

could run a quick test with `kind cluster` and see if you get error ?

**Comment by haoyu1101** [comment]
hi @chen-keinan, there is no kind installed on the setup, did the installation. The command I run is kind get clusters, and no kind clusters found. is there something missing with the environment?

**Comment by haoyu1101** [comment]
Hi @chen-keinan, sorry for getting back to you late. Based on your suggestion given two days ago, we did some testing and suspected there could be an issue with our setup. Just got a new setup ready and running some tests against it. Will update you again with the result.

**Comment by haoyu1101** [comment]
hi @chen-keinan. I will close this issue as it was an environmental issue of the target. After changing to a new target, it works fine. 
thanks for your help
