### ISSUE TITLE
Handle fatal error from plugin

### ISSUE THREAD

**Issue by davidsalame1** [aquasecurity/trivy#4027]
Today if the plugin kills the process as a normal behavior, this fatal error is displayed:

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/75929252/231067270-e5a8c0bc-421c-425f-981c-e1734f37de70.png">

 We want to tweak this FATAL and Error message, Can we send a different error and dismiss it for this case?

**Comment by knqyf263** [comment]
@davidsalame1 Is it still relevant? We can add it to v0.42.0.
