### ISSUE TITLE
Enable both writing to console and file for results

### ISSUE THREAD

**Issue by nabadger** [aquasecurity/trivy#404]
I don't think this is currently supported...

We run trivy as part of CI, and I would like to have trivy print out results in the current table format, and additionally write json results to file.

This would enable any users monitoring the CI to understand why a particular build failed, and it would also allow results to be collected and centralized so teams can gain further insight.

Any thoughts on this?

I can could work around it by writing results to json, and the using `jq` to pretty-print those results to the console as well.

**Comment by prasenforu** [comment]
If I redirect as follows then exit code not working

```trivy image --exit-code 1 --severity CRITICAL ruby:2.4.0 2>&1 | tee SomeFile.txt```

**Comment by dAnjou** [comment]
I believe #720 is kind of the same issue, no?

**Comment by knqyf263** [comment]
We're discussing that in https://github.com/aquasecurity/trivy/issues/3243
