### ISSUE TITLE
support git, github protocols for yarn.lock files

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#4042]
`yarn.lock` files contain versions for `git` and `github` packages.
e.g.:
```yarn.lock
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"mapbox-gl-feature-drag-and-drop@git+https://github.com/jrd/mapbox-gl-feature-drag-and-drop.git":
  version "1.1.1"
  resolved "git+https://github.com/jrd/mapbox-gl-feature-drag-and-drop.git#538b1126e0d15210e91b4a34ffc223b4fec1ef87"
```

It may be possible to add support for these protocols.

**Comment by gongomgra** [comment]
Hi @DmitriyLewen,

I'm getting a similar error (unknown protocol `https://`) trying to scan [this yarn.lock file from argo-workflows](https://github.com/argoproj/argo-workflows/blob/f2292647c5a6be2f888447a1fef71445cc05b8fd/ui/yarn.lock#L2261), just in case you could also allow the `https` protocol in your changes.

This is the related section in the `yarn.lock` file.

```
# yarn.lock
(...)
"argo-ui@https://github.com/argoproj/argo-ui.git#v2.5.0":
  version "1.0.0"
  resolved "https://github.com/argoproj/argo-ui.git#b7a057c465b2659ae3a0d2f9574caa59f15c2ae6"
  dependencies:
(...)
```

**Comment by DmitriyLewen** [comment]
Hello @gongomgra 
Thanks for information! Required also check this case.

___

> And this is the error message

We merged #4052 for similar case.

**Comment by DmitriyLewen** [comment]
@knqyf263 
We need to investigation nuances to parse these protocols.
Also we need to check which package name we should use (what name does GitLab and GitHub databases use for packages from not official repository).

I didn't have time to check this. I will try to investigate soon.

**Comment by DmitriyLewen** [comment]
i investigated this question:

yarn specifies same name for base repository and another repository with same name(e.g. fork):
```
"debug@https://github.com/DmitriyLewen/debug":
  version "4.3.4"
  resolved "https://github.com/DmitriyLewen/debug#d1616622e4d404863c5a98443f755b4006e971dc"
  dependencies:
    ms "2.1.2"
```
Or there may be incorrect versions  (e.g. if form doesn't have new tags).
In these cases we will incorrectly detect vulnerabilities.

I am not sure about this way, but we can use links as package name (`github.com/DmitriyLewen/debug` for my example) so users can see all packages in `sbom` format.


@knqyf263 whyt?

**Comment by knqyf263** [comment]
We may want to add a new field for sources, then skip dependencies downloaded from somewhere other than the default registry.

**Comment by DmitriyLewen** [comment]
> We may want to add a new field for sources, then skip dependencies downloaded from somewhere other than the default registry.

Good idea. It make sense. But i don't see any activity in this Issue. Perhaps we need to wait to understand that this option is needed for users?

> I didn't see the HTTPS protocol in the document. I'm a bit confused now...

I am not sure, but i think that when you use `https://...` - yarn think it is GitHub protocol:

`yarn add debug@https://github.com/DmitriyLewen/debug`:
```
"debug@https://github.com/DmitriyLewen/debug":
  version: 4.3.4
  resolution: "debug@https://github.com/DmitriyLewen/debug.git#commit=d1616622e4d404863c5a98443f755b4006e971dc"
```
`yarn add debug@DmitriyLewen/debug`:
```
debug@DmitriyLewen/debug:
  version: 4.3.4
  resolution: "debug@https://github.com/DmitriyLewen/debug.git#commit=d1616622e4d404863c5a98443f755b4006e971dc"
```

> I was trying to understand what the value is after @

It is strange case. Because if use `git@github.com:foo/bar.git` -> you will have `github.com:foo/bar` package with `git` name:
`git@https://github.com/DmitriyLewen/debug.git`:
```
"git@https://github.com/DmitriyLewen/debug.git":
  version: 4.3.4
  resolution: "git@https://github.com/DmitriyLewen/debug.git#commit=d1616622e4d404863c5a98443f755b4006e971dc"
```
You need to use `<pkg_name>@git+https://...`
