### ISSUE TITLE
Provide ability to disable specific runtimes for `trivy image`.

### ISSUE THREAD

**Issue by pmengelbert** [aquasecurity/trivy#4044]
Unless there is some way to set this I am unaware of, there is no way to disable docker, podman, containerd, or remote scans. When scanning the local store on a Kubernetes node running containerd, we truly only want to scan the local containerd store. We don't want to allow scanning via remote repository, nor do we want to scan using the local docker or podman store.

There is already a mechanism in code to disable various sockets, but it is not exposed to the end user. See the below:
https://github.com/aquasecurity/trivy/blob/dcefc6bf3c5bbad241d5ef65cf2f26515711a113/pkg/fanal/image/image.go#L23

I propose that a new command-line argument be added under `Scan Flags`, for example
```
Scan Flags
      ...
      --runtimes strings   specify which runtimes to scan (default [docker,containerd,podman,remote])
```

I am happy to contribute this myself, as I'm pretty familiar with this section of the code. I may need some guidance around providing tests and documentation.

**Comment by pmengelbert** [comment]
related https://github.com/aquasecurity/trivy/issues/2540#issuecomment-1284736097

**Comment by itaysk** [comment]
looks like same as https://github.com/aquasecurity/trivy/issues/3049, is there any difference in this issue?

**Comment by knqyf263** [comment]
Looks the same. @pmengelbert Any difference?

I have an idea about the selection of image sources. We are supposed to implement it in v0.41.0.
https://github.com/aquasecurity/trivy/issues/3929

I suggest allowing users to specify the priority of runtimes.

```
# Force remote scanning
$ trivy image --image-from remote XXX

# Force containerd scanning
$ trivy image --image-from conatinerd XXX

# Prefer remote images and disable podman
$ trivy image --image-from remote,docker,containerd XXX
```

**Comment by pmengelbert** [comment]
> looks like same as #3049, is there any difference in this issue?
:sweat: Oops, guess I already opened this once already.

**Comment by pmengelbert** [comment]
> Looks the same. @pmengelbert Any difference?
> 
> I have an idea about the selection of image sources. We are supposed to implement it in v0.41.0. #3929
> 
> I suggest allowing users to specify the priority of runtimes.
> 
> ```
> # Force remote scanning
> $ trivy image --image-from remote XXX
> 
> # Force containerd scanning
> $ trivy image --image-from conatinerd XXX
> 
> # Prefer remote images and disable podman
> $ trivy image --image-from remote,docker,containerd XXX
> ```

I didn't see this until just now. I already sketched out an implementation, so I'll open it up as a draft pr. I've tested manually and it works as expected, but it definitely needs tests. At the very least, I may have saved you some work :)

**Comment by itaysk** [comment]
duplicate of #3049

**Comment by s4zed** [comment]
Based on [#2540](https://github.com/aquasecurity/trivy/issues/2540), it feels like the main idea behind this issue here was to provide an option to modify the default containerd namespace. 
Is there any option to scan images from the "k8s.io" containerd namespace, because setting `--image-src` does not get the job done?

**Comment by pmengelbert** [comment]
@s4zed you can set the `CONTAINERD_NAMESPACE` environment variable. Trivy recognizes it
```bash
export CONTAINERD_NAMESPACE=k8s.io
trivy image --image-src=containerd [...]
```
