### ISSUE TITLE
In client server mode, where do scans actually happen

### ISSUE THREAD

**Issue by the-maldridge** [aquasecurity/trivy#411]
I'm looking at extending some tools that I already have to run trivy on an internal nomad cluster.  As such, I'm trying to minimize the thundering herd effect of scanning every container in the cluster.

I see that there is a client server mode which purports to download and cache some files.  My question is do the scans also happen on the server in this mode?  If the scans happen on the server in this mode I assume then I should not start a large number of simultaneous scans.  If instead the server is used only for hosting the database, then I would assume I could get better throughput by running a bunch of scans in parallel.

Ultimately, I'm wanting to "integrate" trivy into another project I have as an optional source of data beyond "this container is out of date" and this architectural advice will prevent my use case from hammering upstream servers with db downloads.

**Comment by the-maldridge** [comment]
Looking at this, I believe that the scans happen on the server, which is really frustrating to discover as it makes the server completely unusable in the case where multiple repositories are in use.  This makes it necessary to have an individual server for every repository you might want to scan, rather than having a server host all the databases to avoid bumping into the rate limit.

**Comment by simar7** [comment]
Hi @the-maldridge do you still need help with this one or can we close this out? Let us know if you need a hand!

**Comment by the-maldridge** [comment]
I think this can be closed out.  For posterity though, can you confirm that in client/server mode that the server only serves the databases, but the scans are still parallelized across as many clients as connect?  This is what I believe I have observed practically, but I want to be sure my understanding is correct.

**Comment by simar7** [comment]
That's correct. Let us know if there's anything else we can help with! I'll be closing this issue now.
