### ISSUE TITLE
Support Ubuntu 19.10 scanning

### ISSUE THREAD

**Issue by pierrchen** [aquasecurity/trivy#416]
Hi,

First, thanks for the wonderful product to make CVE scanning easy.

What we can expect in terms of supporting Ubuntu 19.10? If there are some docs/examples showing how to add support to new distribution/version, probably the community (including me) can contribute to it as well.

**Comment by knqyf263** [comment]
@pierrchen Would you try scanning Ubuntu 19.10? If it doesn't work, feel free to reopen this issue, please.

**Comment by pierrchen** [comment]
Hi @knqyf263 @masahiro331 

I can confirm the scanning of ubuntu 19.10 works. And so does on 20.04.

Thank you!
