### ISSUE TITLE
feat: Support clearing of policy bundle

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#4165]
Currently the `--clear-cache` only clears the fanal artifacts and not the policy bundles. It should be able to do both in situations like this so the user does not have to manually clear the cache-dir from the filesystem.

Details below of an example: 

             > @zadigus Would you try `trivy config --clear-cache`?

Did not work for me, but removing the cache-dir from filesystem helped

_Originally posted by @muellerst-hg in https://github.com/aquasecurity/trivy/issues/4124#issuecomment-1525314162_

**Comment by knqyf263** [comment]
Actually, I was stupid. `trivy --clear-cache` is supposed to remove image layer cache. `trivy --reset` should handle that.

**Comment by simar7** [comment]
> Actually, I was stupid. `trivy --clear-cache` is supposed to remove image layer cache. `trivy --reset` should handle that as `trivy --clear-cache` doesn't remove the vulnerability database. What do you think?

I see. Based on my understanding I think it'll be best to add a sub flag within the `config` subcommand. I make this claim because of two reasons:

1. Today `--reset` lives under the `image` subcommand. Having it `trivy image --reset` clear policy bundles feels kind of clunky.
2. Some users might actually only want to reset one or the other, and not both. So having them decoupled will let them do that.

Therefore I've updated my associated PR to add a `--reset-policy-bundle` option to the `config` subcommand. 

Thoughts?

**Comment by knqyf263** [comment]
Sounds reasonable
