### ISSUE TITLE
Best way to integrate trivy client as a library in another program

### ISSUE THREAD

**Issue by securityclippy** [aquasecurity/trivy#421]
I'm working on a project to manage automated scanning of images in various registries and would like to kick off a scan on the trivy server via this automation.  In order to to so, I need to send a request to trivy (in server mode) to scan the selected image.  

In reviewing the trivy code, it seems the client related code is all located in the internal directory, making it impossible to include the client directly in any program.  The same goes for App, which wraps client and server.

What is the suggested way to use trivy as a library to initiate a scan on a remote server and return the results.  (Using Golang).

Thanks for any pointers!

**Comment by krol3** [comment]
@securityclippy we added new features in trivy, one of them it's the plugin option. More details here: https://github.com/aquasecurity/trivy/pull/633
