### ISSUE TITLE
Trivy vulnerability database path 

### ISSUE THREAD

**Issue by 2Fey** [aquasecurity/trivy#423]
Hi, in our case we need somethink like 20 images to check by trivy on gitlab ci. We want to check next images without downloading trivy and vulnerability db every stage, but on every new stages it download db. 
So we want use _trivy --download-db-only_ and share vulnerability base beetwen maschines, but we can't find vulnerability base on local machine. Can you write path where trivy download vulnerability database?

**Comment by mozillazg** [comment]
The database is downloaded from [here](https://github.com/aquasecurity/trivy-db/releases).

BTW, how about the [client/server mode](https://github.com/aquasecurity/trivy#client--server) ? Maybe it's what you find for your case.

**Comment by 2Fey** [comment]
Hi, we read about client/server mode, but in this case we need to add new server, in future may be we can do it.
But now, if we download db drom your link we can't share it between servers, because we don't know were db save on server filesystem. So can you write default filepath where db save on server filesystem?

**Comment by mozillazg** [comment]
@2Fey The path is `${TRIVY_CACHE_DIR}/db/trivy.db` and you can get or set the value of `${TRIVY_CACHE_DIR}` via `--cache-dir`:

```
$ ./trivy -h |grep 'TRIVY_CACHE_DIR'
  --cache-dir value           cache directory (default: "/path/to/cache/trivy") [$TRIVY_CACHE_DIR]
```

**Comment by 2Fey** [comment]
Thanks you, this is what we need!
`  before_script:
    - apk add --no-cache curl 
    - export VERSION=$(curl -k -H "$CURL" --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - echo $VERSION
    - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
    - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
  script:
    - ls -la
    - ./trivy --download-db-only --cache-dir .trivycache/
  artifacts:
    paths:
     - trivy
     - .trivycache
    expire_in: 2 hr`
and then in every job we can analyze:
`  script:
    - ./trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@contrib/gitlab.tpl" -o trivyrep/rep.json $IMAGE
    - ./trivy --exit-code 0 --cache-dir .trivycache/ --severity HIGH,CRITICAL --no-progress $IMAGE > trivyrep/ci-all-rep.txt 
    - ./trivy --exit-code 0 --ignore-unfixed --cache-dir .trivycache/ --severity HIGH,CRITICAL --no-progress $IMAGE > trivyrep/ci-fix-rep.txt
    - ./trivy --exit-code 1 --ignore-unfixed --cache-dir .trivycache/ --severity HIGH,CRITICAL --no-progress $IMAGE `

**Comment by devlifealways** [comment]
Exactly what I was looking for, we're trying to download ahead of time the CVE database, and use it as part of CI pipeline behind our company proxy.

**Comment by lovelyplanet2019** [comment]
> Thanks you, this is what we need!
> 
> > before_script:
> > - apk add --no-cache curl
> > - export VERSION=$(curl -k -H "$CURL" --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/._"v([^"]+)"._/\1/')
> > - echo $VERSION
> > - wget [https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz](https://github.com/aquasecurity/trivy/releases/download/v$%7BVERSION%7D/trivy_$%7BVERSION%7D_Linux-64bit.tar.gz)
> > - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
> > script:
> > - ls -la
> > - ./trivy --download-db-only --cache-dir .trivycache/
> > artifacts:
> > paths:
> > - trivy
> > - contrib
> > - .trivycache
> > expire_in: 2 hr
> 
> and then in every job we can analyze:
> 
> > script:
> > - ./trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@contrib/gitlab.tpl" -o trivyrep/rep.json $IMAGE
> > - ./trivy --exit-code 0 --cache-dir .trivycache/ --severity HIGH,CRITICAL --no-progress $IMAGE > trivyrep/ci-all-rep.txt
> > - ./trivy --exit-code 0 --ignore-unfixed --cache-dir .trivycache/ --severity HIGH,CRITICAL --no-progress $IMAGE > trivyrep/ci-fix-rep.txt
> > - ./trivy --exit-code 1 --ignore-unfixed --cache-dir .trivycache/ --severity HIGH,CRITICAL --no-progress $IMAGE

i am trying your solution at my gitlab job running
this process uses alot time "fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz"

any ideal if there is offline DB docker that i can pull directly?
