### ISSUE TITLE
Authentication problem against private registry

### ISSUE THREAD

**Issue by fr33ky** [aquasecurity/trivy#432]
**Description**

We are using a docker registry that requires authentication (artifactory) for some repositories.
Using trivy 0.4.4, this works perfectly, setting environment variables (TRIVY_USERNAME, TRIVY_PASSWORD, TRIVY_AUTH_URL). TRIVY_PASSWORD is set to our personal token.
Since version 0.5.0 up to 0.5.2 this doesn't work anymore, complaining an authentication failure, even though I thought it was related to #427. 

**What did you expect to happen?**
Analyse of an image hosted by a protected registry working as in 0.4.4

**What happened instead?**
No analyse as the image cannot be reached because of an authentication failure.

I'll try to paste some more info as soon as possible (debug output, etc.)

**Comment by knqyf263** [comment]
@fr33ky Thank you for the report! I believed the issue was fixed at v0.5.1. Would you tell me more detail? Do you use Docker Hub?

**Comment by fr33ky** [comment]
Hi there, sorry for the delay.
We are using artifactory (jfrog) as docker registry.
I'll try to reproduce the problem and send you all relevant information.

**Comment by fr33ky** [comment]
Because of the current problem I can't access my artifactory.
I tried to reproduce the problem using harbor demo site, and, unfortunately, it perfectly works as expected.

**Comment by mrueg** [comment]
are you using https for artifactory? does a trustpath to the cert exist?

one thing you could try is upgrading the vendored containers/image to https://github.com/containers/image/releases/tag/v5.2.1

**Comment by fr33ky** [comment]
> are you using https for artifactory? does a trustpath to the cert exist?

We are using HTTPS, true, and a trustpath exists too.

**Comment by knqyf263** [comment]
@fr33ky Are you still under the issue? If so, reopen this issue and share the detail, please.
