### ISSUE TITLE
Request to support defsec policy settings similar to cloudsploit plugin settings

### ISSUE THREAD

**Issue by AkhtarAmir** [aquasecurity/trivy#4358]
### Discussed in https://github.com/aquasecurity/trivy/discussions/4357

<div type='discussions-op-text'>

<sup>Originally posted by **AkhtarAmir** May 14, 2023</sup>
### Description

In cloudsploit, we have an options to give settings for some plugins like desirec encyrption level for SNS or desired instance types for RDS. We want to have something similar to pass on to defsec policies and produce results based on those user given input.

### Target

AWS

### Scanner

Misconfiguration</div>

**Comment by knqyf263** [comment]
We will create an issue after discussing
