### ISSUE TITLE
Vulnerability Count in file storage

### ISSUE THREAD

**Issue by happylie** [aquasecurity/trivy#436]
I have a question.
Can't you save the count of vulnerabilities that are output on the screen when you save the file with the json type?
I also use the related data, but I would like to include the following contents first.

ex)
Total: 26 (UNKNOWN: 0, LOW: 3, MEDIUM: 16, HIGH: 5, CRITICAL: 2)

**Comment by happylie** [comment]
It's not perfect, but it's simple to check through the jq command.
However, while implementing services internally, we will parse Json files to create council data.

If you can do it differently in the jq command, I would appreciate it if you let me know.
I don't handle jq Command well.

ex) Save a.json file 
Total: 26 (UNKNOWN: 0, LOW: 3, MEDIUM: 16, HIGH: 5, CRITICAL: 2)

$ cat a.json | jq '.[0]' | jq '.[]' | jq '.[] | select(.Severity == "LOW") | length' | wc -l
16

**Comment by knqyf263** [comment]
You can use `jq` or any programming languages such as Python.

For example,
```
#!/usr/bin/python
import json
from collections import defaultdict


count = defaultdict(int)
with open("alpine.json") as f:
    result = json.load(f)
    for target in result:
        for vuln in target["Vulnerabilities"]:
            count[vuln["Severity"]] += 1

print(count)
```

I'm not sure we would add the vulnerability count in JSON in the future, but a user can easily count it themself, so I feel it is not necessary for now.

**Comment by happylie** [comment]
Thank you for answering.
I also develop Python and do not have any inconvenience in extracting the count.
However, there are cases where only Total and Severity level counts are needed simply.
I would appreciate it if you consider the function.
