### ISSUE TITLE
Support scanning of files/folders/github repositories

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/trivy#437]
We would like Trivy to support vulnerability scanning for application formats that are not only container images. This includes scanning of standalone files, folders and even a complete github repository.

The idea is that a trivy scan can get any supported format as input parameter, issue a scan on it and show the scan results as it is today.

To support this we should modify the Trivy usage, as currently it only get image as parameter. 

The new usage will look like this:

trivy scan image <image name>
trivy scan file <file or folder name>
trivy scan repo <github repository URL>

**Comment by lizrice** [comment]
A different usage suggestion: 

* `trivy <image name>` - scans image, as today 
* `trivy` - (with no subcommands / parameters) scans local filesystem, like microscanner
* `trivy repo <URL>` - scans git repo from URL. I'm less sure about this one. Open to discussion on whether this should be a subcommand or a flag. TBD how this would work with authentication required to access a private repo.

**Comment by netrounds-fredrik** [comment]
Related issues:
* https://github.com/aquasecurity/trivy/issues/437
* https://github.com/aquasecurity/trivy/issues/293

**Comment by knqyf263** [comment]
Supported at v0.9.0
