### ISSUE TITLE
Amazon Linux support

### ISSUE THREAD

**Issue by abedra** [aquasecurity/trivy#44]
When trying to scan an amazon linux image I got the following
```
FATAL	error in image scan: failed to scan image: failed to analyze OS: Unknown OS
```
Is there a way to force detection to pin against redhat because it's derivative? Any plans to support amazon linux?

**Comment by knqyf263** [comment]
Currently, amazon linux is not supported yet. 
https://github.com/knqyf263/trivy#os-packages

However, I'm developing to support amazon linux now! Please wait a bit 😄

**Comment by abedra** [comment]
Thanks for the update. Glad to see it coming.

**Comment by CaseyLabs** [comment]
Just following up on Amazon Linux support for Trivy, as I've just ran into that limitation:

```WARN    unsupported os : amazon```

Any updates on AL/AL2 support?

**Comment by Alexc0007** [comment]
Hi, did anyone test this?
i just tried to scan amazon linux2 with trivy and it didnt work for me, 
got this message:
WARN	unsupported os : amazon
