### ISSUE TITLE
CycloneDX output can contain duplicate `dependsOn` items, making the BOM invalid

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#4447]
### Discussed in https://github.com/aquasecurity/trivy/discussions/4446

**Comment by DmitriyLewen** [comment]
It is problem with `jar` parser. 
I created #4496

**Comment by DmitriyLewen** [comment]
Fixed in #4515

**Comment by nscuro** [comment]
@DmitriyLewen Thanks for addressing this so quickly!
