### ISSUE TITLE
trivy scanner detect  wrong vulnerable dependencies com.google.guava:guava version11.0.2  in my java app 

### ISSUE THREAD

**Issue by onkarnarkar** [aquasecurity/trivy#4469]
i used trivy scanned to find vulnerable dependency. Trivy shows me vulnerable dependencies for **com.google.guava:guava version11.0.2**  which is not exit in my project and even not downloaded in my local .m2 repository.

**Comment by DmitriyLewen** [comment]
We convert issue from discussion.

We will create issue from #4472 if needed.
