### ISSUE TITLE
Debian:9 Install fails: Unable to locate package trivy

### ISSUE THREAD

**Issue by yed30** [aquasecurity/trivy#447]
**Description**
Hello,
my pipelines failed since yesterday (this was working for months) with the following message:

---> Running in 57651cf46163
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [520 kB]
Get:5 http://deb.debian.org/debian stretch Release [118 kB]
Get:6 http://deb.debian.org/debian stretch Release.gpg [2,410 B]
Get:7 https://aquasecurity.github.io/trivy-repo/deb stretch InRelease [2,320 B]
Get:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages [27.9 kB]
Get:9 http://deb.debian.org/debian stretch/main amd64 Packages [7,083 kB]
Fetched 7,939 kB in 1s (5,444 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Unable to locate package trivy

with the following code:
```
#### Add trivy repo & install trivy
RUN wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key |  apt-key add -
RUN echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main |  tee -a /etc/apt/sources.list.d/trivy.list
RUN apt-get update && apt-get install -y  trivy

```

Commented here too: https://github.com/aquasecurity/trivy-repo/issues/1

**Comment by yed30** [comment]
As a workaround I change the install with:
```
RUN wget https://github.com/aquasecurity/trivy/releases/download/v0.1.6/trivy_0.1.6_Linux-64bit.deb
RUN dpkg -i trivy_0.1.6_Linux-64bit.deb
```

**Comment by yed30** [comment]
As a workaround, I change the install with:
```
RUN wget https://github.com/aquasecurity/trivy/releases/download/v0.5.3/trivy_0.5.3_Linux-64bit.deb
RUN dpkg -i trivy_0.5.3_Linux-64bit.deb
```

**Comment by knqyf263** [comment]
It should work now. Would you try it again?

**Comment by yed30** [comment]
Yes it does work !
Thank you very much for the support and the great work.

**Comment by knqyf263** [comment]
Thank you for the confirmation. I'm sorry for the inconvenience.
