### ISSUE TITLE
show TRIVY_SEVERITY and higher in output

### ISSUE THREAD

**Issue by strowi** [aquasecurity/trivy#449]
Hi,

i'm currently testing trivy in combination with gitlab. But to be fully compatible/able to replace clair (without too much modifications) it should be able to report the specified severity and higher. 

Wondering if there is a use-case where one would want only LOW but not CRITICAL?

E.g.:
- `TRIVY_SEVERITY=HIGH` should display HIGH,CRITICAL
- `TRIVY_SEVERITY=LOW` should display HIGH,MEDIUM,HIGH,CRITICAL
- etc..

regards,
strowi

**Comment by simar7** [comment]
Hi @strowi you could use the `--severity` flag to specify your level. 

`trivy --severity=LOW` to show only `LOW` severity vulnerabilities. 

Alternatively like you mentioned, you could use `TRIVY_SEVERITY` to do the same as an environment variable.

Is there a use case that you have for which the current implementation doesn't suffice?

**Comment by strowi** [comment]
@simar7 thx for checking on this.

We've been using the gitlab/clair template with some modifications just needing: 
```
container_scanning:
  extends: .container_scanning
  variables:
    SEVERITY: High
    SUB_IMAGE_NAME: /php-cli
```

which would map to clair `HIGH,CRITICAL` but with trivy only 'HIGH'. 
With trivy we would need to fix that in every job that switches from clair to trivy (or back).

With my experience in security tools, i am just used to specifying a minimum level that would show all higher risks too.

I was just wondering if there is a use-case for showing only `medium`  and ignoring higher-level risks...

PS: Coming to think about this, we could add another script parsing `SEVERITY` in our template before running trivy..

**Comment by simar7** [comment]
Hi @strowi, I understand now what you're trying to do. I realize you would like to re-use the same template for both Trivy and Clair with the same `SEVERITY` level. But if we change the behaviour of the current `SEVERITY` flag it would be a backwards breaking change.

Another way for us would be to introduce another flag but it would still require you to keep two separate templates for Clair and Trivy. 

For now I'm afraid we don't have a better solution for this.

**Comment by knqyf263** [comment]
Can't you run `sed 's/High/HIGH,CRITICAL/g'`? Is it difficult in your case?

**Comment by strowi** [comment]
@simar7 okay understood. It was just a feature suggestion. I saw the example gitlab-template and thought it would be nice if it were a drop-in replacement. 
Thx for looking into it.
For our use-case in gitlab-ci i can add a sed/other small script into the template like @knqyf263 mentioned:

```bash
#!/bin/bash

shopt -s nocasematch

case "$SEVERITY" in
  "UNKKNOWN")
    export SEVERITY="UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL";;
  "LOW")
    export SEVERITY="LOW,MEDIUM,HIGH,CRITICAL";;
  "MEDIUM")
    export SEVERITY="MEDIUM,HIGH,CRITICAL";;
  "HIGH")
    export SEVERITY="HIGH,CRITICAL";;
  "CRITICAL")
    export SEVERITY="CRITICAL";;
  *)
    echo "Wrong SEVERITY set"
    exit 1
    ;;
esac

echo "SEVERITY: $SEVERITY"

```

this can be closed then.;)

**Comment by knqyf263** [comment]
Thank you for the useful feedback. We may add `HIGH-` or another option like `--severity-min` in the future if many people hope it.
