### ISSUE TITLE
Amazon Linux OS support

### ISSUE THREAD

**Issue by gowthamsundar** [aquasecurity/trivy#450]
Hi,

Recently tried out Trivy on an image from AWS ECR and got the following error? Does Trivy support Amazon Linux os?

> unsupported os : amazon

> Mentioned in Dockerfile from the image hosted in ECR- 
FROM amazonlinux:2017.09

But, while trying to pull the image locally, it is able to provide results. What could be the reason for the error when scanning the image pulled from ECR. Please help.

Thanks

**Comment by knqyf263** [comment]
Which version of trivy do you use? After v0.1.7, Trivy supports Amazon Linux. It might be an authentication problem. Would you make sure you log in ECR?

**Comment by gowthamsundar** [comment]
Yes, installed using rpm with the old version. Thanks for help.
