### ISSUE TITLE
Support docker registry token

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#453]
Pass Docker Registry v2 Bearer token via `TRIVY_REGISTRY_TOKEN`.
https://docs.docker.com/registry/spec/auth/jwt/

**Comment by simar7** [comment]
Should this be closed now since https://github.com/aquasecurity/fanal/pull/102 is merged?

**Comment by knqyf263** [comment]
We need to merge this PR.
https://github.com/aquasecurity/trivy/pull/475​​​​​​​

**Comment by knqyf263** [comment]
We have to merge https://github.com/aquasecurity/trivy/pull/482.
