### ISSUE TITLE
Update / simplify gitlab-ci example

### ISSUE THREAD

**Issue by strowi** [aquasecurity/trivy#454]
Hi,

since trivy doesn't need a docker deamon iteself, the gitlab-ci example can be simplified (and by removing the dind-part) and adjusted more to the default container-scanning template from gitlab.

I can open a MR if desired.

regards,
strowi

**Comment by knqyf263** [comment]
@tnir I'm sorry to bother you, but what do you think about this suggestion?

**Comment by tnir** [comment]
@strowi Sorry for delayed response. Thanks for your suggestion. Your improvement would be very welcome 😄 

@knqyf263 Thanks for mentioning me 🙇

**Comment by strowi** [comment]
@tnir no problem.. just had some free time during lockdown.;) Pls. see the MR. 
The Authentication Issue doesn't really relate to the gitlab-ci template, but we pull in a couple of external images the we would also like to scan.
