### ISSUE TITLE
Can I use Trivy docker image to do CI in Windows?

### ISSUE THREAD

**Issue by daxin09pp** [aquasecurity/trivy#455]
We used docker build image in the Windows environment. Image is based on Linux. We use Gitlab to do CI process. In this case, can I integrate Trivy docker image into our CI process? Can I use Trivy docker image to do CI in Windows?
Thanks!

**Comment by knqyf263** [comment]
You cannot run the trivy binary directly in the Windows environment, but you can run the docker image even in Windows.

**Comment by daxin09pp** [comment]
Yes,I have successfully integrated it into my CI flow
