### ISSUE TITLE
chore: fix a checkboxes (trivy command) in the bugs template

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/trivy#4589]
I also want to notice you that your bug creation checklist has the following step "Run trivy --reset" but when I run that I got the next error: FATAL   unknown flag: --reset .

_Originally posted by @dmytrozelonkin in https://github.com/aquasecurity/trivy/discussions/4580#discussioncomment-6119629_

**Comment by alexandreliberato** [comment]
I can tackle this issue.
