### ISSUE TITLE
fix: address api_server_authorized_ip_ranges false positives

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#4624]
### Discussed in https://github.com/aquasecurity/trivy/discussions/4331

<div type='discussions-op-text'>

<sup>Originally posted by **huornlmj** March 15, 2023</sup>
## Description
Trivy will ignore "authorized_ip_ranges" and will complain if it doesn't find the now deprecated term "api_server_authorized_ip_ranges"

```
CRITICAL: Cluster does not limit API access to specific IP addresses.
```

## What did you expect to happen?
Not get a false positive, and for Trivy to observe the newer construct as a pass

## What happened instead?
A failed scan</div>

**Comment by nikpivkin** [comment]
@simar7 Isn't this problem [solved](https://github.com/aquasecurity/trivy/issues/3850)? However, there is a link to `api_server_authorized_ip_ranges` in several places.

**Comment by simar7** [comment]
> @simar7 Isn't this problem [solved](https://github.com/aquasecurity/trivy/issues/3850)? However, there is a link to `api_server_authorized_ip_ranges` in several places.

Oh you might be right - what do you mean by link in several places?

**Comment by nikpivkin** [comment]
@simar7 [Here](https://github.com/aquasecurity/defsec/blob/3b9a08cd847991b2ca8b8f142ac04607f2310f4a/avd_docs/azure/container/AVD-AZU-0041/Terraform.md?plain=1#L18) and [here](https://github.com/aquasecurity/defsec/blob/3b9a08cd847991b2ca8b8f142ac04607f2310f4a/rules/cloud/policies/azure/container/limit_authorized_ips.tf.go#L26).

**Comment by simar7** [comment]
I see. Should those rules be deprecated as well? (And their documentation removed)

**Comment by nikpivkin** [comment]
@simar7 we just need to fix the links

**Comment by simar7** [comment]
Closed with https://github.com/aquasecurity/defsec/pull/1381
