### ISSUE TITLE
Scan local filesystem

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/trivy#466]
Trivy could scan the packages on the local (host) filesystem. This would enable both host scanning, and microscanner-style scanning from within a Dockerfile as part of the build

**Comment by netrounds-fredrik** [comment]
@knqyf263, glad to see that this is happening. While adding the possibility to scan a filesystem to detect installed software, would you consider to also allow the user to provide the list of software packages to be checked for vulnerabilities as proposed in https://github.com/aquasecurity/trivy/issues/293.
