### ISSUE TITLE
Show the correct URL of the secret scanning

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#4680]
## Description
The wrong link is shown now.
https://github.com/aquasecurity/trivy/blob/dcc73e964a8a19e37fa495f6694be28a06ed3d64/pkg/commands/artifact/run.go#L597

It should be `https://aquasecurity.github.io/trivy/%s/docs/scanner/secret/#recommendation`.

**Comment by tungbq** [comment]
I'd like to work on this issue. Please assign to me if you need help. Thanks!
