### ISSUE TITLE
feat(misconf): Enable `--policy` flag to accept directory and files both

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#4689]
As discussed here  https://github.com/aquasecurity/trivy/discussions/4668#discussioncomment-6240627 - we can add support to the `--policy` flag to accept both directory and files both.

### Current behaviour

```shell
trivy config --policy <path/to/dir>
```

Should pick up all policies under the directory.

### New behaviour

```shell
trivy config --policy <path/to/policy.rego>
```

Should just load the individual policy.

It is important to note both of these behaviour should work with this change. IOW, a user should be able to pass either or as inputs.

**Comment by NikhilSharmaWe** [comment]
Hey Simar,

I would like to work on this.

I see that func [createPolicyFS](https://github.com/aquasecurity/trivy/blob/main/pkg/misconf/scanner.go#L287) is responsible for creating the FileSystem of the policies specified. Is this a relevant function for this issue?

If yes, I am thinking of working with directories the same as before but having all the files under a dir path `./files`.

Please inform me if my understanding is relevant or if you have a better implementation in mind.

Thankyou,
Nikhil Sharma

**Comment by simar7** [comment]
hi @NikhilSharmaWe - you're right as that's the function that handles the code in question.

As for the implementation, that sounds good to me. You could probably use a more descriptive name such as `policyFiles` or the like, for the in memory directory.
