### ISSUE TITLE
Setting up repo for RHEL/CentOS gives 404 error

### ISSUE THREAD

**Issue by sarbajitdutta** [aquasecurity/trivy#471]
**Description**
While setting up repo in CentOS gives 404 error for the baseurl according to the README file.
https://github.com/aquasecurity/trivy#rhelcentos

![image](https://user-images.githubusercontent.com/16959056/79897552-e61ba480-83d7-11ea-9460-213f6d5c9d3d.png)

**What did you expect to happen?**
The url would be accepted.

**What happened instead?**
The baseUrl gives 404 error.

This is required since we want to receive updates from rpm instead of manually updating it in accordance with release cycle of trivy.

**Comment by knqyf263** [comment]
@simar7 Would you do research on this? First of all, you try setting up Trivy in CentOS, following README. If you can reproduce the issue, I'd like you to look into it.

This is a repository keeping rpm packages, so it might be relevant.
https://github.com/aquasecurity/trivy-repo/

**Comment by simar7** [comment]
I just tried to reproduce this locally but wasn't able to. Here's a log of what I did:

```
[vagrant@localhost ~]$ cat /etc/yum.repos.d/trivy.repo
[trivy]
name=Trivy repository
baseurl=https://aquasecurity.github.io/trivy-repo/rpm/releases/$releasever/$basearch/
gpgcheck=0
enabled=1

[vagrant@localhost ~]$ sudo yum -y update
Trivy repository                                                       9.8 kB/s | 3.3 kB     00:00
Dependencies resolved.
Nothing to do.
Complete!
[vagrant@localhost ~]$ sudo yum -y install  trivy
Last metadata expiration check: 0:00:08 ago on Wed 29 Apr 2020 06:00:34 PM UTC.
Dependencies resolved.
=======================================================================================================
 Package                Architecture            Version                   Repository              Size
=======================================================================================================
Installing:
 trivy                  x86_64                  0.6.0-1                   trivy                  6.5 M

Transaction Summary
=======================================================================================================
Install  1 Package

Total download size: 6.5 M
Installed size: 19 M
Downloading Packages:
trivy-0.6.0.el8.x86_64.rpm                                             4.3 MB/s | 6.5 MB     00:01
-------------------------------------------------------------------------------------------------------
Total                                                                  4.3 MB/s | 6.5 MB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                               1/1
  Installing       : trivy-0.6.0-1.x86_64                                                          1/1
warning: user  does not exist - using root
warning: group  does not exist - using root

  Verifying        : trivy-0.6.0-1.x86_64                                                          1/1

Installed:
  trivy-0.6.0-1.x86_64

Complete!
[vagrant@localhost ~]$ trivy --version
Version: 0.6.0
```

Could you add some more detail @sarbajitdutta as to what steps you took?

**Comment by sarbajitdutta** [comment]
> Could you add some more detail @sarbajitdutta as to what steps you took?

We are trying to install trivy in `Red Hat Enterprise Linux Server release 7.8 (Maipo)`.
We have Jenkins installed there and we are trying to setup trivy to appear part of Jenkins shell when creating pipelines. Following the instruction in Readme gives us 404 error on the rpm repo.

**Comment by krol3** [comment]
@sarbajitdutta do you still have this error?
