### ISSUE TITLE
Empty dependency files make Trivy fail

### ISSUE THREAD

**Issue by achton** [aquasecurity/trivy#472]
**Description**

When trivy comes across a application dependency file which is empty, it will fail (in this case `composer.lock`).

**What did you expect to happen?**

For Trivy to ignore the file and maybe issue a warning.

**What happened instead?**

Trivy failed with a FATAL error.

**Output of run with `-debug`:**

```
2020-04-23T12:38:17.726Z	DEBUG	Updating database metadata...
2020-04-23T12:38:17.726Z	DEBUG	DB Schema: 1, Type: 1, UpdatedAt: 2020-04-23 12:07:58.740214484 +0000 UTC, NextUpdate: 2020-04-24 00:07:58.740214184 +0000 UTC
2020-04-23T12:38:17.728Z	DEBUG	Vulnerability type:  [os library]
2020-04-23T12:38:25.885Z	FATAL	error in image scan:
    github.com/aquasecurity/trivy/internal/standalone.run
        /home/circleci/project/internal/standalone/run.go:100
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanImage
        /home/circleci/project/pkg/scanner/scan.go:87
  - analyze error:
    github.com/aquasecurity/fanal/analyzer.Config.Analyze
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20200413182139-9213b79eba1a/analyzer/analyzer.go:115
  - failed to analyze layer: sha256:520175bb38bf7f986e003d17124abbfd5c2e36b3f17dfbc08d4b0be607ab97f6 :
    github.com/aquasecurity/fanal/analyzer.Config.analyze.func1
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20200413182139-9213b79eba1a/analyzer/analyzer.go:134
  - failed to get libraries:
    github.com/aquasecurity/fanal/analyzer.Config.analyzeLayer
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20200413182139-9213b79eba1a/analyzer/analyzer.go:180
  - failed to get libraries:
    github.com/aquasecurity/fanal/analyzer.GetLibraries
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20200413182139-9213b79eba1a/analyzer/analyzer.go:318
  - error with var/www/web/core/modules/system/tests/fixtures/HtaccessTest/composer.lock:
    github.com/aquasecurity/fanal/analyzer/library/composer.composerLibraryAnalyzer.Analyze
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20200413182139-9213b79eba1a/analyzer/library/composer/composer.go:37
  - EOF
```

**Output of `trivy -v`:**

```
Version: 0.6.0
```

**Additional details (base image name, container registry info...):**
- base image was `nginx:1.16.1-alpine` with code pulled in from a private git repo.
- the file in question is from [Drupal 8](https://github.com/drupal/core/tree/8.8.x/modules/system/tests/fixtures/HtaccessTest)
- Trivy is run via a GitHub Action

**Comment by cdchris12** [comment]
We ran into this same issue trying to scan a Drupal site as well. Looks like the issue actually comes from https://github.com/aquasecurity/fanal . We were able to replicate this functionality with versions `v0.6.0`, `v0.7.0`, and `v.0.8.0` testing against an example Drupal site. 

There is also a Drupal issue which has been created to track this incompatibility on Drupal's side of things: https://www.drupal.org/project/drupal/issues/3138691

**Comment by krol3** [comment]
@achton @cdchris12 do you still have issues with this dependency?

**Comment by cdchris12** [comment]
I can confirm that we are no longer experiencing the issue on our platform. :)

**Comment by egertoft** [comment]
The same goes when scanning an image without an OS, like an image built from scratch containing a self-contined Go application. Then you also get a file containing only the word null, that unfortunately often require some special handling when trying to parse the expected JSON.
