### ISSUE TITLE
Get installed packages

### ISSUE THREAD

**Issue by remidinishanth** [aquasecurity/trivy#477]
How does trivy get the list of packages installed in the docker image? Does it run the image and then get them? Or does it cache the base image installed packages and use them?

**Comment by simar7** [comment]
It looks at certain important files that hold such details. For example, in the case of alpine the list of installed packages is available in `lib/apk/db/installed`

Does that answer your question?

**Comment by NISHANTH2066** [comment]
It looks at os package manager files for finding versions, but does it run the conyaiber and get those? Or does it untar the file system and get the file information ?

**Comment by knqyf263** [comment]
The latter. Trivy doesn't run a container.

**Comment by remidinishanth** [comment]
I see. Thank you
