### ISSUE TITLE
fix(test): Test_Run (aws) fluky test

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#4874]
Part of the `Test_Run` tests are falling.
```
--- FAIL: Test_Run (83.11s)
    --- FAIL: Test_Run/fail_without_region (31.95s)
    --- FAIL: Test_Run/fail_without_creds (46.19s)
    --- FAIL: Test_Run/try_to_call_aws_if_cache_is_expired (4.90s)
    --- PASS: Test_Run/succeed_with_cached_infra (0.01s)
    --- PASS: Test_Run/custom_rego_rule_with_passed_results (0.02s)
    --- PASS: Test_Run/compliance_report_summary (0.01s)
    --- PASS: Test_Run/scan_an_unsupported_service (0.00s)
    --- PASS: Test_Run/scan_every_service (0.02s)
    --- PASS: Test_Run/skip_certain_services_and_include_specific_services (0.01s)
    --- PASS: Test_Run/only_skip_certain_services_but_scan_the_rest (0.01s)
    --- PASS: Test_Run/fail_-_service_specified_to_both_include_and_exclude (0.00s)
FAIL
        github.com/aquasecurity/trivy/pkg/cloud/aws/commands    coverage: 85.6% of statements
FAIL    github.com/aquasecurity/trivy/pkg/cloud/aws/commands    84.975s
```

I found that this happened after configuring the default aws profile (`aws configure` command).
```bash
cat ~/.aws/config
[default]
aws_access_key_id=***
aws_secret_access_key=***
region = eu-central-1
```
If the region or account is not passed, then Trivy [loads the default config](https://github.com/aquasecurity/trivy/blob/main/pkg/cloud/aws/commands/run.go#L28C26-L28C26) for aws.

My suggestion: set the `AWS_PROFILE` environment variable in the test or add a new `profile` flag (similar to the [aws cli](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)) to use the passed profile.

**Comment by simar7** [comment]
If these tests are picking up external configuration then they are not unit tests at that point. We need to make sure that they don't do so by either testing against `localstack` or by passing in mocks where needed.
