### ISSUE TITLE
Enhance `trivy repo` for local and remote code repository scanning

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#4888]
See https://github.com/aquasecurity/trivy/issues/4887

**Comment by okainov** [comment]
Please note documentation needs to be updated as well, currently in 0.44.0 I see in CLI help messages:

>
Scanning Commands
  aws         [EXPERIMENTAL] Scan AWS account
  config      Scan config files for misconfigurations
  filesystem  Scan local filesystem
  image       Scan a container image
  kubernetes  [EXPERIMENTAL] Scan kubernetes cluster
  repository  Scan a remote repository


`repository  ` should mention "local filesystem" as well

**Comment by knqyf263** [comment]
Thanks for pointing out. I'll raise an issue.

**Comment by knqyf263** [comment]
Done
https://github.com/aquasecurity/trivy/issues/4985
