### ISSUE TITLE
feat(misconf): Selectively enable misconfiguration scanners

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#4901]
Today we don't have a good way to specify only certain misconfiguration scanners to be run and certain to be disabled. For instance with a file directory input like so:

```shell
$ ls
Dockerfile
chart.yaml
main.tf
```

`trivy config` will scan all of the files. We can limit to an extent by providing file extensions, paths and/or globbing to exclude/include certain types but the approach seems rather convoluted.

Therefore, having a flag to enable selective scanners only (similar to `-vuln-type`) in config scan will help. I propose that we can pick `--config-type` as the flag name and provide values such as: `dockerfile`, `helm`, `terraform`.

The use case will look like the following:
`trivy config --config-type=dockerfile,helm`

Will only scan `dockerfile` and `helm`.

**Comment by mogopz** [comment]
This would be great to have. We're blocked from migrating away from Trivy until this is possible.
