### ISSUE TITLE
Installation not working in ubuntu

### ISSUE THREAD

**Issue by divyam7777** [aquasecurity/trivy#4908]
### Discussed in https://github.com/aquasecurity/trivy/discussions/4906

<div type='discussions-op-text'>

<sup>Originally posted by **divyam7777** August  1, 2023</sup>
### Description

using https://aquasecurity.github.io/trivy/v0.44/getting-started/installation/ site for installing trivy in my pc but getting no package foubd trivy.

### Desired Behavior

installation should happen

### Actual Behavior

W: https://aquasecurity.github.io/trivy-repo/deb/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package trivy
/home/vsts/work/_temp/3d968216-1c54-478a-a9ff-af2480dc5646.sh: line 6: trivy: command not found

### Reproduction Steps

```bash
1.
2.
3.
...
```

### Target

Virtual Machine Image

### Scanner

Vulnerability

### Output Format

Table

### Mode

Standalone

### Debug Output

```bash
installation failed
```

### Operating System

UBUNTU 22

### Version

```bash
0.44
```

### Checklist

- [ ] Run `trivy image --reset`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

**Comment by slideroh** [comment]
The same error:
Get:7 https://aquasecurity.github.io/trivy-repo/deb focal InRelease
Hit:6 https://aquasecurity.github.io/trivy-repo/deb focal InRelease
E: Unable to locate package trivy

**Comment by DmitriyLewen** [comment]
Hello all!
We updated `trivy-repo`.

Can you try installing Trivy again?

**Comment by divyam7777** [comment]
Thanks working fine now

**Comment by DmitriyLewen** [comment]
@divyam7777 I have 1 ask for your:
Create only Discussio next time, please.
Maintainer wil convert it to Issue if necessary.
Thanks in advance, Dmitriy

**Comment by divyam7777** [comment]
@DmitriyLewen sure from next i will create only in discussion,  as it is impacting our production thats why i created issue .

**Comment by knqyf263** [comment]
Duplicate of https://github.com/aquasecurity/trivy-repo/issues/32
