### ISSUE TITLE
More generic support for Python

### ISSUE THREAD

**Issue by itamarst** [aquasecurity/trivy#492]
It seems that `trivy` supports `poetry.lock` and `Pipfile.lock` for Python, but not `requirements.txt`.

`requirements.txt` has dual usage:

1. For some people, it's just high-level dependencies, unpinned to any particular versions.
2. For other, it's equivalent to a lock file, transitively pinned dependencies often with hashes. For example, the `pip-tools` package takes an unpinned `requirements.in` and generates a pinned `requirements.txt`.

More broadly, there's the issue of people who install packages using unpinned mechanisms, e.g. `RUN pip install flask` in their Dockerfile.

I can imagine a number of approaches:

1. Add a parser for `requirements.txt`, and just give up if it's unpinned. This will miss some vulnerabilities.
2. Run `pip list` inside the container to get actually installed packages, and then you don't care _how_ they were installed. The downside is that this is a big difference from your current mode of operation.
3. Do the equivalent of `pip list` just by inspecting the contents of any `site-packages` directories you find in the image. I went and asked a `pip` developer, and turns out all `pip list` does is look for `<package name>-<version>.dist-info` directories and uses that to get package name version. E.g. they look like `paramiko-2.7.1.dist-info` for package `paramiko` with version 2.7.1

The third option seems like the easiest and most useful: it works for _any_ Python environment and installation mechanism (it ought to work for Conda too, which is yet another packaging tool), and it's quite simple, just listing directories and parsing their names.

**Comment by mkjpryor-stfc** [comment]
My team uses requirements.txt as a lock file, so support for that would be much appreciated. 

More generally, I like the idea of just finding any `site-packages` directories and scanning the `dist-info`s. 

An alternative approach could be to locate all `pip` executables and use the output of `pip freeze` to drive the analysis.

**Comment by jithurjacob** [comment]
This would be really helpful as we use conda for ML libs and we are not able to use trivy.

**Comment by knqyf263** [comment]
I've added this task to our backlog.

**Comment by knqyf263** [comment]
As a first step, we'll support `==`.

How it works:

1. Look for all `requirementx.txt`.
2. Parse `requirementx.txt` and extract package names and versions
3. Use them for vulnerability detection

How to implement it:

1. Add a new parser [here](https://github.com/aquasecurity/go-dep-parser/tree/main/pkg)
2. Add a new analyzer for `requirements.txt` [here](https://github.com/aquasecurity/fanal/tree/main/analyzer/library)
3. Update go.mod/go.sum in Trivy

**Comment by PratikDhanave** [comment]
@knqyf263 I am working on it. work in progress

**Comment by Gerry9000** [comment]
Looks like this issue has the same goal for python and node packages, using approach #3 from this issue, and the contributor mentioned they have code they can submit:
https://github.com/aquasecurity/trivy/issues/1039

**Comment by knqyf263** [comment]
We finally merged #1169, so Trivy will support requirements.txt in the next version. Note that it detects only `==` specifier.

**Comment by jerbob92** [comment]
I have tried adding more generic pip-compile support: https://github.com/aquasecurity/fanal/pull/357
Please let me know what you think.
