### ISSUE TITLE
feat: expose "node.collector.imageRef" for trivy k8s scanning

### ISSUE THREAD

**Issue by git-ew** [aquasecurity/trivy#4921]
### Discussed in https://github.com/aquasecurity/trivy/discussions/4898

<div type='discussions-op-text'>

<sup>Originally posted by **git-ew** July 31, 2023</sup>
### Description

I'm using a local artifact repo to locally source images for k8s clusters that cannot reach out to the public Internet.

When performing a trivy k8s scan from cli, the node-collector attempts to pull directly from ghcr.io and will fail deployment.

Can we have node.collector.imageRef exposed for the command line and trivy config yaml (maybe --node-collector-imageref ) similar to what is available in trivy-operator here?

https://github.com/aquasecurity/trivy-operator/pull/941/files

### Target

Kubernetes

### Scanner

None</div>

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/pull/4928

**Comment by git-ew** [comment]
Yeah, misunderstanding on process from my part. Sorry.
