### ISSUE TITLE
feat(misconf): Improve Rego file detection

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#4924]
### Description

On Apple Silicon with newer MacOS versions, Apple keeps around an [AppleDouble](https://en.wikipedia.org/wiki/AppleSingle_and_AppleDouble_formats) file for each file on disk.

Today we don't handle this gracefully leading to errors messages like the following:
```shell
$ trivy config .
<snip>
2023-08-01T23:40:43.172-0600    DEBUG   [defsec] 40:43.172344000 aws-api.scanner.rego             Failed to load module: Users/simar/Library/Caches/trivy/policy/content/policies/kubernetes/policies/rolebinding/._cluster_admin_role_is_only_used_where_required.rego, err: 1 error occurred: Users/simar/Library/Caches/trivy/policy/content/policies/kubernetes/policies/rolebinding/._cluster_admin_role_is_only_used_where_required.rego:1: rego_parse_error: illegal null character
</snip>
``` 

The scan still goes ahead and successfully finishes with all results. The output is just clobbered with the above messages.

### Action item
We need to update the logic for `isRegoFile` here https://github.com/aquasecurity/defsec/blob/master/pkg/rego/load.go#L40 - besides looking at just extension we need to evaluate file prefix as well. 

### Note
AppleDouble Formatted files start with `._` prefix.

**Comment by knqyf263** [comment]
Do you mean our policy bundle contains AppleDouble files? We build it on Linux, I'm curious why it is problematic.
https://github.com/aquasecurity/defsec/blob/0d4c4b51c16d92a01a8a0622432a973a780d1fa1/.github/workflows/release.yaml#L14-L15

**Comment by simar7** [comment]
> Do you mean our policy bundle contains AppleDouble files? We build it on Linux, I'm curious why it is problematic.
> 
> https://github.com/aquasecurity/defsec/blob/0d4c4b51c16d92a01a8a0622432a973a780d1fa1/.github/workflows/release.yaml#L14-L15

I believe once we fetch and untar the policy bundle on disk, these files are generated.

**Comment by itaysk** [comment]
@simar7 the PR seems to fix a different case than the one you describe here. can you elaborate?

**Comment by simar7** [comment]
> @simar7 the PR seems to fix a different case than the one you describe here. can you elaborate?

AppleDouble files are also dotfiles as they are prefixed with `._`. That's the PR is able to fix this issue.

**Comment by itaysk** [comment]
oh right, I missed the doc in the prefix.
