### ISSUE TITLE
Multi-arch docker images.

### ISSUE THREAD

**Issue by Johannestegner** [aquasecurity/trivy#496]
Hi there!

I would like to request multi-arch docker images, seeing the releases page have basically all architectures one could wish for, this should not be a huge issue to implement!

I would think that at the least aarch64 and possibly a couple of the 32b ARM cpu's would be the initial most-required versions if this is to be implemented, and if there is no experience in the field of multi-arch images I'd recommend taking a look at buildx with qemu support.

If you need any type of help with setting something up, let me know and I'll happily help!

---

Until implemented or requested for takedown:

As of now (due to me using both amd64 and arm64 machines in my ci-fleet) I created an image for amd64 and aarch64 cpus which could be found here (for anyone who requires it til it is implemented on the official channel!): https://hub.docker.com/repository/docker/jitesoft/trivy

Image is built from source on native machines and are ofc scanned with Trivy to make sure there are no vulnerabilities! ;)

**Comment by knqyf263** [comment]
I think we can easily do that with GoReleaser. You can see a good example here.
https://github.com/goreleaser/goreleaser/blob/5e23177a4c6837a75f76acce237f2c10f35b9819/.goreleaser.yml#L35-L83

**Comment by ocean** [comment]
@knqyf263 I've taken up your suggestion and got it working great with some extra Goreleaser config and adding Docker Buildx support to the `release` workflow, thanks for the inspiration 😄 

Please see #915  🚀

**Comment by knqyf263** [comment]
See the release note.
https://github.com/aquasecurity/trivy/discussions/966
