### ISSUE TITLE
fix(terraform): do not check the network policy if enable_autopilot is true

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#4961]
Source: https://github.com/aquasecurity/tfsec/issues/2027

If the `enable_autopilot` argument is set to true in the `google_container_cluster` resource, then we should not check `network_policy`, because in autopilot mode, Google [manages](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#what-is-autopilot) the security of the cluster itself. And also the `network_policy` argument [has a conflict](https://github.com/hashicorp/terraform-provider-google/blob/53becdded4b4ee2bab5d4d0f72c415525f287c36/google/services/container/resource_container_cluster.go#L1213C1-L1213C1) with `enable_autopilot`.

**Comment by knqyf263** [comment]
@simar7 When you add an issue to the milestone, would you also set the project to "Trivy Roadmap"? Then, the task will appear here. It is no big deal, but it helps manage tasks.
https://github.com/orgs/aquasecurity/projects/25/views/12

**Comment by simar7** [comment]
Closed via https://github.com/aquasecurity/defsec/pull/1420
