### ISSUE TITLE
Discrepancy between the detected misconfig and the rule on the aqua site

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#4976]
I have the following configuration:
```terraform
resource "aws_s3_bucket" "test" {
  bucket = "my.bucket"
}
```
The Trivy report contains the following misconfiguration:
```bash
MEDIUM: S3 bucket name is not compliant with DNS naming requirements
════════════════════════════════════════════════════════════════════════════════════════════════════════════
Ensures that S3 buckets have DNS complaint bucket names.

See https://avd.aquasec.com/misconfig/n/a
────────────────────────────────────────────────────────────────────────────────────────────────────────────
 main.tf:2
────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   resource "aws_s3_bucket" "test" {
   2 [   bucket = "my.bucket"
   3   }
────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
But on the aqua vulnerability database website, the severity [is listed ](https://avd.aquasec.com/misconfig/aws/s3/s3-dns-compliant-bucket-names/) as unknown. Also the link to the rule is incorrect.

**Comment by simar7** [comment]
> But on the aqua vulnerability database website, the severity [is listed ](https://avd.aquasec.com/misconfig/aws/s3/s3-dns-compliant-bucket-names/)as unknown. Also the link to the rule is incorrect.

What did you expect to see?

**Comment by nikpivkin** [comment]
@simar7 What is the true severity information on the website or in the Trivy report? Also I would like to see the correct link, not `https://avd.aquasec.com/misconfig/n/a`

**Comment by simar7** [comment]
Ah - yeah we haven't updated the generator with the new version of defsec which would include these rules. Here's a PR to tackle this https://github.com/aquasecurity/avd-generator/pull/73

**Comment by simar7** [comment]
Should have the fix in the next release of AVD pages (happens, once a day).
