### ISSUE TITLE
fix(terraform): AWS DynamoDB is encrypted with an AWS key by default

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#5005]
source: https://github.com/aquasecurity/tfsec/issues/1959

If server-side encryption is not enabled for DynamoDB, then the AWS key [is used](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/EncryptionAtRest.html) for encryption.

We need to improve this rule: https://avd.aquasec.com/misconfig/aws/dynamodb/avd-aws-0023/#Terraform

**Comment by simar7** [comment]
Fixed via https://github.com/aquasecurity/trivy-policies/pull/18
