### ISSUE TITLE
kbom component impovements

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#5019]
in components of type application:
    - change `component.name` to official [k8s upstream component](https://github.com/kubernetes/kubernetes/blob/master/staging/README.md)
    - use `component.version` 
    - add actual workload name under `aquasecurity:trivy:workloadName` 
    - deprecate `aquasecurity:trivy:k8s:component:Name`

**Comment by chen-keinan** [comment]
@itaysk maybe we should use `aquasecurity:trivy:resource:name` instead of `aquasecurity:trivy:workload:name` to make it more generic ?

**Comment by itaysk** [comment]
sure that also works
