### ISSUE TITLE
bug(cyclonedx): cyclonedx vulnerability advisory == null

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#5039]
## Description
`Vulnerabilities.Advisories` field of `Cyclonedx` can't be `null` - `Invalid type. Expected: array, given: null`.
See more here - https://github.com/aquasecurity/trivy/issues/4900#issuecomment-1691518333.

**Comment by nscuro** [comment]
I assume this would have to be a bug in cyclonedx-go then, but I wonder how `null` can ever slip through encoding, given the `advisories` field is a slice pointer with `omitempty` tag... https://github.com/CycloneDX/cyclonedx-go/blob/83031d6697bd6d8b20bce2a0326347a0ea7691c7/cyclonedx.go#L607

@DmitriyLewen, were you able to reproduce this given the steps mentioned in #4900? I just tried an the file validates just fine for me.

**Comment by DmitriyLewen** [comment]
Hello @nscuro 

> were you able to reproduce this given the steps mentioned in https://github.com/aquasecurity/trivy/issues/4900?

Yes. I created PR to fix this. I wrote  in PR description, why this happens.
This is nuance of `json`.
But perhaps a check should be added to `cyclonex-go` for this case.
