### ISSUE TITLE
Incorrect command in README

### ISSUE THREAD

**Issue by andrew-lee-metaswitch** [aquasecurity/trivy#504]
**Description**
Running `trivy image python:3.4-alpine` as suggested in the README does not work

```
trivy --version
Version: 0.7.0
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2020-05-26 12:11:12.479923897 +0000 UTC
  NextUpdate: 2020-05-27 00:11:12.479923597 +0000 UTC
trivy image python:3.4-alpine
2020-05-26T17:49:19.415+0100	ERROR	multiple images cannot be specified
2020-05-26T17:49:19.415+0100	FATAL	failed to initialize options: arguments error

```

This `image` subcommand was added yesterday as per https://github.com/aquasecurity/trivy/pull/493

**Comment by andrew-lee-metaswitch** [comment]
It could just be that the README is ahead of the 0.7.0 release (I suspect so).

**Comment by simar7** [comment]
Good catch @andrew-lee-metaswitch we'll cut a new release shortly. cc @knqyf263

**Comment by simar7** [comment]
This should now be fixed with the new release https://github.com/aquasecurity/trivy/releases/tag/v0.8.0 

Let us know if you still need help @andrew-lee-metaswitch

**Comment by andrew-lee-metaswitch** [comment]
Yeah that's fixed! Thanks!
