### ISSUE TITLE
trivy 0.7 not surpport library scan

### ISSUE THREAD

**Issue by mdchao2010** [aquasecurity/trivy#506]
in trivy-db file not find that db:
```
RubySec               = "ruby-advisory-db"
	RustSec               = "rust-advisory-db"
	PhpSecurityAdvisories = "php-security-advisories"
	NodejsSecurityWg      = "nodejs-security-wg"
	PythonSafetyDB        = "python-safety-db"
```

**Comment by knqyf263** [comment]
What does it mean? There are those buckets in trivy-db.
![image](https://user-images.githubusercontent.com/2253692/83349365-14789200-a33d-11ea-8925-f5f08289c4bb.png)

**Comment by mdchao2010** [comment]
> There are those buckets in trivy-db.
I have find that vulnerability files, and add those buckets in trivy-db.

ruby-advisory-db： https://github.com/RustSec/advisory-db.git
php-security-advisories：https://github.com/FriendsOfPHP/security-advisories
nodejs-security-wg：https://github.com/nodejs/security-wg.git
python-safety-db：https://github.com/pyupio/safety-db.git
rust-advisory-db： https://github.com/RustSec/advisory-db.git
