### ISSUE TITLE
Error scan after update to v0.9.0

### ISSUE THREAD

**Issue by dendi** [aquasecurity/trivy#510]
**Description**
Unable to scan (public and private repo) after update to v0.9.0

**What did you expect to happen?**
I have updated trivy to the latest version. When trying to scan image via remote server, an error message appears. 
I have also downgraded the version to 0.7.0, the scanner running fine without issue.

**What happened instead?**
Cannot scan any image in public or private repo.

**Output of run with `-debug`:**
trivy client --remote https://trivy.xxxx.xx:443 --token 'xxxxxxxx' dendipradigta/overseer-bridge-slack:1.0.6 -d
2020-06-03T13:17:23.225+0700	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2020-06-03T13:17:23.225+0700	DEBUG	cache dir:  /Users/dendipradigta/Library/Caches/trivy
2020-06-03T13:17:27.459+0700	DEBUG	Vulnerability type:  [os library]
2020-06-03T13:17:28.497+0700	FATAL	error in image scan:
    github.com/aquasecurity/trivy/internal/client.run
        /home/circleci/project/internal/client/run.go:76
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanImage
        /home/circleci/project/pkg/scanner/scan.go:87
  - unable to get missing layers:
    github.com/aquasecurity/fanal/analyzer.Config.Analyze
        /go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20200413182139-9213b79eba1a/analyzer/analyzer.go:111
  - unable to fetch missing layers:
    github.com/aquasecurity/trivy/pkg/cache.RemoteCache.MissingLayers
        /home/circleci/project/pkg/cache/remote.go:48
  - twirp error bad_route: no handler for path "/twirp/trivy.cache.v1.Cache/MissingLayers"
```
(paste your output here)
```

**Output of `trivy -v`:**
Version: 0.9.0 
```
(paste your output here)
```

**Additional details (base image name, container registry info...):**

**Comment by mozillazg** [comment]
@dendi It's looks like the server (`--remote https://trivy.xxxx.xx:443`) is not use the same version as client. How about upgrade both server and client to 0.9.0 and try again?

**Comment by knqyf263** [comment]
@mozillazg Thank you for the help!

@dendi Yes, would you try upgrading the server to 0.9.0? I'll write the caution in the changelog. Thanks.

**Comment by dendi** [comment]
Thanks all. I have updated both server and client. All running as expected. Will close this thread.

thanks!
