### ISSUE TITLE
README has broken link to "Scanning Coverage" page

### ISSUE THREAD

**Issue by Rob-HCL** [aquasecurity/trivy#5110]
### Discussed in https://github.com/aquasecurity/trivy/discussions/5109

<div type='discussions-op-text'>

<sup>Originally posted by **Rob-HCL** September  1, 2023</sup>
### Description

The link in the top-level README.md to "Scanning Coverage" (target: https://aquasecurity.github.io/trivy/latest/getting-started/coverage/ ) is broken.

It looks like that page no longer exists for 0.45, hence why there's no redirect for the "latest" URI.

### Link

https://github.com/aquasecurity/trivy/blob/main/README.md

### Suggestions

Perhaps the link should be updated to point to https://aquasecurity.github.io/trivy/latest/docs/coverage/ as that works for the latest versions.</div>

**Comment by knqyf263** [comment]
Please read
https://aquasecurity.github.io/trivy/v0.45/community/contribute/discussion/
