### ISSUE TITLE
feat(terraform): support for versioned resources of kubernetes provider

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#5115]
Source https://github.com/aquasecurity/tfsec/issues/1919

> From provider version v2.7.0 onwards Terraform resources and data sources that cover the [standard set of Kubernetes APIs](https://kubernetes.io/docs/reference/kubernetes-api/) will be suffixed with their corresponding Kubernetes API version (e.g v1, v2, v2beta1).  

Ref:
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/versioned-resources
- https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md#270-november-30-2021

**Comment by stevehipwell** [comment]
For clarity about the current behaviour; should Trivy be evaluating Kubernetes Terraform resources such as `kubernetes_pod` for Kubernetes rules?

**Comment by simar7** [comment]
> For clarity about the current behaviour; should Trivy be evaluating Kubernetes Terraform resources such as `kubernetes_pod` for Kubernetes rules?

In Terraform IaC scanning, today it only supports the `kubernetes_network_policy` [resource](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/network_policy). You can see the adapter that adapts the resource [here](https://github.com/nikpivkin/trivy-iac/blob/9622bcaee552ea7666f7fe676ee0ccd04fc789b1/internal/adapters/terraform/kubernetes/adapt.go#L13-L17)
