### ISSUE TITLE
feat(misconf): Add support for wildcard ignores 

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#5120]
As described in the issues below, we can add support for wildcards for workspaces and other resources in general

https://github.com/aquasecurity/tfsec/issues/1937
```
**Is your feature request related to a problem? Please describe. **
I was able to setup ignore rules per workspace, but I should specify full name of workspace I have different workspaces related different apps and environments

Describe the solution you'd like
It would be good to have ability to setup workspace ignore rule with wildcard.
example:
tfsec:ignore:AWS006:exp:2221-01-02 #tfsec:ignore:AWS018:ws:development-*
```

https://github.com/aquasecurity/tfsec/issues/1804
```
Is your feature request related to a problem? Please describe.
I want to add ignore rules depending on the workspace name, For example, if the workspace name contains a test then ignore rules for resources

Describe the solution you'd like
Right now it is possible to ignore the workspace with this
#tfsec:ignore:AWS018:ws:development-test-app-1

Describe alternatives you've considered
I want to be able to ignore the workspace with something like this
#tfsec:ignore:AWS018:ws:*-test-*
```

**Comment by stevehipwell** [comment]
This would be allow us to work around https://github.com/aquasecurity/trivy/issues/4922 where there are a large number of false positives being created.

**Comment by cdenneen** [comment]
Agree with @stevehipwell would like this to work in the `paths` for `.trivyignore.yaml` as well.

**Comment by cdenneen** [comment]
If not wildcard can paths at least accept regex patterns?

**Comment by cdenneen** [comment]
@simar7   Will this work with trivyignore? Can examples of how it would appear using that file? Looks like tests are all inline
