### ISSUE TITLE
Components from Rust binaries use rustbinary instead of cargo in purls

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#5166]
## Description
Replace `rustbinary` with `cargo` in PURL. e.g. `pkg:rustbinary/abomonation@0.7.3` => `pkg:cargo/abomonation@0.7.3`

**Comment by o1oo11oo** [comment]
I haven't tried the same feature for Go binaries, but it looks like it also uses `gobinary` which probably leads to similar issues.

**Comment by knqyf263** [comment]
I don't think Go is the case. We just missed Rust in the switch.
https://github.com/aquasecurity/trivy/blob/7acc5e8312a75f3489483cebb7d59d577210163e/pkg/purl/purl.go#L352-L389
