### ISSUE TITLE
include k8s add-ons  in kbom

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#5175]
it is require to add to include all  k8s add-ons with in kbom
every resource which has label the `k8s-app: <addon-name> in all namespaces.

this change enable trivy to include `Container Network Interface (CNI)` with in kbom
- Flannel
- Calico
- Cilium

**Comment by chen-keinan** [comment]
@knqyf263 I have marked it for milestone v0.45.1 if you think it can't make then move it to v0.46.0

**Comment by knqyf263** [comment]
Is it a bug fix? v0.45.1 is supposed to include bug fixes only.

**Comment by knqyf263** [comment]
@chen-keinan Ping just in case you missed my response.

**Comment by chen-keinan** [comment]
> Is it a bug fix? v0.45.1 is supposed to include bug fixes only.
@knqyf263 
yes, its include a bug fix , and small change to collect resources from all namespaces and not just kube-system

**Comment by knqyf263** [comment]
But this PR is labeled as a feature enhancement. Are you changing it to `fix(k8s):`?
https://github.com/aquasecurity/trivy/pull/5178

**Comment by chen-keinan** [comment]
> But this PR is labeled as a feature enhancement. Are you changing it to `fix(k8s):`? #5178

@knqyf263  done
