### ISSUE TITLE
docs: remove `--scanners none`

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#5182]
## Description
Replace 

```
$ trivy image --scanners none --image-config-scanners secret vuln-image
```

with

```
$ trivy image --image-config-scanners secret vuln-image
```

since `none` is not supported now.

https://aquasecurity.github.io/trivy/v0.45/docs/target/container_image/

**Comment by mehrdadbn9** [comment]
i wanna do that please assign me to that and where can i find document to change
thanks in advance

**Comment by knqyf263** [comment]
Here
https://github.com/aquasecurity/trivy/blob/main/docs/docs/target/container_image.md
