### ISSUE TITLE
Ensure trivy docker image runs as a non root user

### ISSUE THREAD

**Issue by braudel** [aquasecurity/trivy#519]
Attempts to launch trivy using starboard are currently failing in k8s clusters with PSP restricted due to runAsNonRoot.

**Comment by knqyf263** [comment]
@rahul2393 could you work on it?

**Comment by rahul2393** [comment]
Sure, thanks

**Comment by knqyf263** [comment]
Fixed by #570. Thanks, @rahul2393

**Comment by rb1193** [comment]
Hi, this was reverted in [#581](https://github.com/aquasecurity/trivy/pull/581). Is it likely to be something that another attempt could be made at? I did see there were some issues with the ownership of a cache directory.

**Comment by knqyf263** [comment]
It broke scanning in container images on Windows.
https://github.com/aquasecurity/trivy/issues/580
