### ISSUE TITLE
chore: replace brews.tap with brews.repository

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#5219]
Since version 1.19.0 `brews.tap` is [deprecated](https://goreleaser.com/deprecations/#brewstap).

**Comment by nikpivkin** [comment]
@knqyf263 `brews.tap` is deprecated in v1.19.0, Trivy is now using v1.16.2. Is it worth updating goreleaser to the latest v1.20?

**Comment by knqyf263** [comment]
Sounds good

**Comment by nikpivkin** [comment]
@knqyf263 BTW, goreleaser-action v5.0.0 was also [released](https://github.com/goreleaser/goreleaser-action/releases/tag/v5.0.0), which uses node 20. The end date for node16 (which is used in the current version) is September 11 this year.
