### ISSUE TITLE
Support TLS for --server mode

### ISSUE THREAD

**Issue by bitsofinfo** [aquasecurity/trivy#524]
Support TLS for --server mode

I.E. would be great to be able to present TLS in server mode

**Comment by Johannestegner** [comment]
I would recommend using a proxy with TLS support (such as nginx or traefik), at the least until there is an implementation for this in the application itself (if there will be).

**Comment by knqyf263** [comment]
@Johannestegner Thank you for the recommendation!

@bitsofinfo As @Johannestegner said, I also would like to recommend using a proxy like nginx. But if you have any good reason to have TLS support in Trivy, let me know, please.

**Comment by alpesh-valia** [comment]
Hey Amir, 

Could you assign me this issue?
