### ISSUE TITLE
policy support

### ISSUE THREAD

**Issue by DanCech** [aquasecurity/trivy#53]
It would be useful to have a mechanism to specify criteria for what should be considered a successful scan, including the ability to list results that should be ignored whether because there is no fix available or they are false positives.

One potential use-case would be for debian or ubuntu-based images where there are known vunerabilities which are either not going to be fixed or are marked as non-dsa, so we want to acknowledge that those vulnerabilities are expected and should not fail the build, but that any new vulnerabilities should result in a failure until they are either remediated or also added to the exception list.  The `--ignore-unfixed` option provides similar functionality, but is also risky since it won't alert you to any new unfixed vulnerabilities where an explicit exception list would flag them until they can be investigated.

The policy could also specify what level(s) of vulnerabilities should warrant a non-zero exit code, to provide the ability to report on all found vulnerabilities in a single report and with a single run, but only fail the build if high or critical vulnerabilities are found.

**Comment by imnotjames** [comment]
Looks like the `.trivyignore` files allows you to mark specific vulnerabilities as being ignored.

That should solve many of these problems - you could manually add items to it that are firing but are lower than the severity you'd consider a problem.

**Comment by christian-weiss** [comment]
I think `.trivyignor` can cover everything what was asked for. Lets close this ticket now.

**Comment by knqyf263** [comment]
@imlonghao @christian-weiss Thanks. I closed this one.

**Comment by knqyf263** [comment]
OPA was supported at v0.10.0.
https://github.com/aquasecurity/trivy/pull/562
