### ISSUE TITLE
Trivy is not showing docker image digest

### ISSUE THREAD

**Issue by prabha1331** [aquasecurity/trivy#531]
@knqyf263 
**Description**
When we scan a docker image using trivy it is not showing the docker image digest to check whether docker image has been modified or not 

**What did you expect to happen?**
Trivy should show docker image Digest as shown below for every image scan. The below digest is from `docker images --digests` command output.
"Digest":"sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209"

**What happened instead?**
Trivy provides some other digest except docker image digest as shown below
Artifact ID: sha256:1c35c441208254cb7c3844ba95a96485388cef9ccc0646d562c7fc026e04c807
Blob IDs: [sha256:1be74353c3d0fd55fb5638a52953e6f1bc441e5b1710921db9ec2aa202725569]

**Output of run with `-debug`:**

```
2020-06-16T13:30:08.389+0530	DEBUG	Updating database metadata...
2020-06-16T13:30:08.391+0530	DEBUG	DB Schema: 1, Type: 1, UpdatedAt: 2020-06-16 00:18:16.960854785 +0000 UTC
2020-06-16T13:30:08.397+0530	DEBUG	Vulnerability type:  [os library]
2020-06-16T13:30:08.399+0530	DEBUG	Artifact ID: sha256:1c35c441208254cb7c3844ba95a96485388cef9ccc0646d562c7fc026e04c807
2020-06-16T13:30:08.399+0530	DEBUG	Blob IDs: [sha256:1be74353c3d0fd55fb5638a52953e6f1bc441e5b1710921db9ec2aa202725569]
2020-06-16T13:30:08.399+0530	WARN	OS is not detected and vulnerabilities in OS packages are not detected.
```

**Output of `trivy -v`:**

```
Version: 0.9.0
Vulnerability DB:
  Type: Light
  Version: 1
```

**Additional details (base image name, container registry info...):**

**Comment by zidhumenon** [comment]
Hey @knqyf263 any update on this?

**Comment by knqyf263** [comment]
Trivy displays an image id. You can find the difference between an image id and a digest.
https://stackoverflow.com/questions/56364643/whats-the-difference-between-a-docker-images-image-id-and-its-digest

A digest sometimes doesn't exist.
https://stackoverflow.com/questions/39811230/why-doesnt-my-newly-created-docker-have-a-digest

>to check whether docker image has been modified or not

You can use the image id for this purpose. Do you still need a digest?

**Comment by krol3** [comment]
@zidhumenon  the image ID is used as identifier in the docker hub for example this [nginx:1.15](https://hub.docker.com/layers/nginx/library/nginx/1.15/images/sha256-53f3fd8007f76bd23bf663ad5f5009c8941f63828ae458cef584b5f85dc0a7bf?context=explore). in what case do we need digest?

**Comment by zidhumenon** [comment]
@knqyf263 @krol3 Yes I think we still need an image digest to validate whether the image is modified or not! 
For example,
When i run `_**docker images --digests**_` command i can see the below iinformation with sha256: 

``mongo   latest   sha256:d54fb51a493131117a8b85a2d46ed7d64a2cb79607fb3ce350d1722c0cafc812   ef5c2207766e   4 months ago   493MB``

When I run `_**trivy --debug image mongo:latest**_` i am expecting to see the same sha256! but I am not seeing it below


```2021-03-30T13:38:27.972+0530	DEBUG	Artifact ID: sha256:ef5c2207766e4cfa7d009b7372f315fa67a47ea5dd5b71a15b2f829c7f7d024f
2021-03-30T13:38:27.972+0530	DEBUG	Blob IDs: [sha256:b43408d5f11b7b2faf048ae4eb25c296536c571fb2f937b4f1c3883386e93d64 sha256:23135df75b44a66efa9d8dc1a10051768c27bd95388f436eb9553e0eb17211f6 sha256:fe6d8881187d429af3f636c574911690455825998c9f366e985eab646665e711 sha256:df4fd9f71fe8d47eb0d98deaf9ecdf326e624b70a03f42886bd935d30023d5cd sha256:1c0a08cbad59ee82ab99c22b2a1f4ffc5d8211f964e9454c3af4fccd41af7134 sha256:26db7fc12a58fe83033581d37e4b8d4e9623a355674fc37ff9270e403c00a7ec sha256:db0a50043243db19415f2cfc866652b8769954f6d027ef23e4bae9e5d8bec3ab sha256:69d2fbf2b8431c6eb36dd13b39b2d83c444bbdbf43d4d4c6d98af41969722611 sha256:bacd39aef7fba9d4d4fb43546c4aaf9413db025342977c59e9c95c47f8958a42 sha256:34c46f3b55ab435b68535a7622636ca81f7227a83243bf8062a4ea75dab255cc sha256:c7e6746b8f07de041c22e86dd3ee87cee2ec4a74d95bc85262d4c61d286c4c7e sha256:9b4f065b4a28d875e88f7d6fb3612b7b14e04a845537d2ec2d23b2bc6febc97f]```

**Comment by krol3** [comment]
@zidhumenon  for inmutability checking, trivy uses the docker "Id", not the Digest.
![Screen Shot 2021-03-30 at 08 47 35](https://user-images.githubusercontent.com/8355621/112983972-aa837180-9134-11eb-9bd0-1511d8a1973c.png)

**Comment by zidhumenon** [comment]
@krol3 Thanks for the quick response. How trivy is reading the docker ID from image? and could you please explain why trivy uses docker ID over Digest?

**Comment by krol3** [comment]
@zidhumenon,  Teppei  commented about this above. 
```
Trivy displays an image id. You can find the difference between an image id and a digest.
https://stackoverflow.com/questions/56364643/whats-the-difference-between-a-docker-images-image-id-and-its-digest

A digest sometimes doesn't exist.
https://stackoverflow.com/questions/39811230/why-doesnt-my-newly-created-docker-have-a-digest

to check whether docker image has been modified or not

You can use the image id for this purpose. Do you still need a digest?
```

**Comment by joelapatatechaude** [comment]
Wouldn't it make sense for trivy to display the imageID (next to the image_name:tag)?
I see it's available in debug mode, but it feels like it's a key information. Trivy is effectively scanning an image that is uniquely identified by an ID. Name:tag can be changed, overwritten, deleted overtime. Having the image-id available by default help devs auditors that need to reconcile a scan report with an exact image build for example. Particularly relevant for build-scan-push pipelines. docker build output images id used in FROM directive in a dockerfile. docker push display the image-id being pushed. It would make sense to have trivy to display in normal mode the image-id

Thanks to this thread, I see I can use debug mode so I am fine, but I though I would provide this feedback. It's probably an improvement that is easy to add to this great tool.

**Comment by knqyf263** [comment]
Thanks for the feedback. The next version will include Image ID in the JSON result.
