### ISSUE TITLE
Add health check endpoint to trivy server

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#534]
Trivy has client/server mode and the server provides some endpoints. It would be useful if it provides `/healthz` that returns status code 200 and simply "ok" in the case of running Trivy server in k8s cluster. Ideally, we should check the download of the DB, but it is enough to simply return 200 as a first step.

```
$ trivy server
2020-06-23T11:27:59.747+0300    INFO    Listening localhost:4954...
```

```
$ curl http://localhost:4954/healthz
ok
```

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes

**Comment by yashvardhan-kukreja** [comment]
I would like to take up on this issue and start working around it :smile:

**Comment by yashvardhan-kukreja** [comment]
As mentioned, I would just begin by setting up the endpoint `/healthz` to straight away return a 200 response. Then, I can start further augmenting other healthchecks upon that endpoint later.
Sounds fine @knqyf263 ?

**Comment by knqyf263** [comment]
@yashvardhan-kukreja I'm sorry for the late reply. It sounds good!
