### ISSUE TITLE
bug: false positive AVD-DS-0011

### ISSUE THREAD

**Issue by vmarchese** [aquasecurity/trivy#5392]
**Describe the bug**
Scanning an image for Dockerfile misconfiguration with the command

```
trivy image --image-config-scanners config ...
```

with a layered Dockerfile containing a ```COPY``` command that copies a file from a builder layer as in:

```dockerfile
COPY --from=builder somefile /somepath/somefile
```

fails with the message

```
CRITICAL: Slash is expected at the end of COPY command argument '/somepath/somefile'
══════════════════════════════════════════════════════════
When a COPY command has more than two arguments, the last one should end with a slash.

See https://avd.aquasec.com/misconfig/ds
```

It looks like the rego rule  implemented in [copy_with_more_than_two_arguments_not_ending_with_slash.rego](https://github.com/aquasecurity/defsec/blob/v0.93.1/rules/docker/policies/copy_with_more_than_two_arguments_not_ending_with_slash.rego) does not take into account the ```COPY``` command flags 

**To Reproduce**

Write a simple Dockerfile that copies a file from a builder image

**Comment by nikpivkin** [comment]
This is easily reproduced by disabling the [BuildKit](https://docs.docker.com/build/buildkit/):
```bash
DOCKER_BUILDKIT=0 docker build . -t test-img --no-cache

docker history test-img
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
4a7104cf6b42   14 seconds ago   /bin/sh -c #(nop)  USER appuser                 0B
541a645d2e47   14 seconds ago   /bin/sh -c #(nop) COPY file:7e46c04ff62f9f5d…   4B
83f0e82295c3   14 seconds ago   /bin/sh -c #(nop) WORKDIR /app                  0B
```

**Comment by nikpivkin** [comment]
@simar7 This has been fixed in https://github.com/aquasecurity/trivy-policies/pull/56
