### ISSUE TITLE
Add support of .NET `*Packages.props` files.

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#5403]
## Description
Add support of [Directory.Packages.props](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management) files.
Also we can parse `Packages.props`  files. These files were used before `Directory.Packages.props` and use same format - https://github.com/aquasecurity/trivy/discussions/5379#discussioncomment-7316578

**Comment by yuriShafet** [comment]
@DmitriyLewen Should I first create a parser in go-dep-parser repo and then when it is merged add in this repo rest of the implementation?

**Comment by DmitriyLewen** [comment]
> Should I first create a parser in go-dep-parser repo

You are right. 

> then when it is merged add in this repo rest of the implementation?

You don't need to wait for the `go-dep-parser` PR merge. You can create PR for Trivy (add analyzer, docs, tests, etc.) and use `go replace` with commit from your fork.
This will help ensure that your changes works correctly and as expected.

**Comment by yuriShafet** [comment]
@DmitriyLewen 
PR with parser code:
https://github.com/aquasecurity/go-dep-parser/pull/268
