### ISSUE TITLE
bug(cyclonedx): wrong purl for local Go dependencies

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#5449]
### Discussed in https://github.com/aquasecurity/trivy/discussions/5434
We don't create PURL for local Go dependencies, but still create CycloneDX component:
```json
 "bom-ref": "pkg:/",
      "type": "library",
      "name": "./api",
      "purl": "pkg:/",
      "properties": [
...

  "dependencies": [
    {
      "ref": "03a5f5e8-87ca-4f07-9309-c5de465ce1a8",
      "dependsOn": [
        "pkg:/",
...
```

**Comment by knqyf263** [comment]
@DmitriyLewen We should include local dependencies. In case we cannot generate PURL, we should use UUID.

> This relies on a components bom-ref to associate the component to the dependency element in the graph. The only requirement for bom-ref is that it is unique within the BOM. Package URL (PURL) is an ideal choice for bom-ref as it will be both unique and readable. If PURL is not an option or not all components represented in the BOM contain a PURL, then UUID is recommended.

https://cyclonedx.org/use-cases/#dependency-graph

**Comment by MPV** [comment]
After the fix in #5448 I am now instead getting:

`"message": "invalid package url: in manifest \"gobinary\" decoding \"\": scheme is missing",`

**Comment by DmitriyLewen** [comment]
Hello @MPV
Can you give more information about your case, please?

**Comment by MPV** [comment]
> Can you give more information about your case, please?

Yes, see:
- https://github.com/aquasecurity/trivy/discussions/5474

**Comment by DmitriyLewen** [comment]
Hello @MPV 
Looks like this is GitHub bug.

But It is strange. We don't fill purl field for local Go dependencies:
```json
    {
      "name": "./api",
      "SPDXID": "SPDXRef-Package-cab1689fa6aee0c7",
      "versionInfo": "(devel)",
      "supplier": "NOASSERTION",
      "downloadLocation": "NONE",
      "licenseConcluded": "NONE",
      "licenseDeclared": "NONE",
      "copyrightText": "",
      "primaryPackagePurpose": "LIBRARY"
    },
```

GitHub docs say that file must follow SPDX format - https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exporting-a-software-bill-of-materials-for-your-repository
But `externalRefs` (field with purl) is not required field - https://spdx.github.io/spdx-spec/v2.3/package-information/#721-external-reference-field.
