### ISSUE TITLE
Support Sarif output

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/trivy#547]
If we add an option to output Trivy result in Sarif format, they can be uploaded into GItHub's code-scanning results. 

More details [here](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/managing-results-from-code-scanning)

**Comment by knqyf263** [comment]
Hi @rahul2393, could you work on this task? I think it is very similar to what we did for JUnit support, using `template`.

**Comment by rahul2393** [comment]
@knqyf263 ok added

**Comment by knqyf263** [comment]
Thanks! GitHub can only assign an issue to people who have commented on the issue if you're not a member of the organization.

**Comment by rahul2393** [comment]
@lizrice Please check the attached sarif file, I ran to check on image ruby:2.4.0 and exported using the template in PR.

[report.sarif.zip](https://github.com/aquasecurity/trivy/files/4907330/report.sarif.zip)
