### ISSUE TITLE
Adding a timestamp to the vulnerability report

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#5542]
Add `CreatedAt` to the JSON report.

### Discussed in https://github.com/aquasecurity/trivy/discussions/5536

**Comment by u5surf** [comment]
@knqyf263 Can you assign me? I'd like to work on this issue. Probably It may be fixed with `pkg/clock.Now` in `report.Write`.

**Comment by knqyf263** [comment]
Sure, thanks.
