### ISSUE TITLE
Add JUnit tempate (contrib/junit.tpl) to docker image

### ISSUE THREAD

**Issue by mslusarczyk** [aquasecurity/trivy#555]
I see that `contrib/gitlab.tpl` is already included in the docker image: [PR](https://github.com/aquasecurity/trivy/pull/388)
It would be awesome to add `contrib/junit.tpl` for similar reason.

I've created a small PR that does it: https://github.com/aquasecurity/trivy/pull/554

**Comment by knqyf263** [comment]
Thank you for the contribution!
