### ISSUE TITLE
Error retrieving template from path when --format is not template but --template is provided

### ISSUE THREAD

**Issue by mslusarczyk** [aquasecurity/trivy#557]
**Description**
When `--format` is set to `json` and at the same time `--template` is provided trivy fails trying to find the file.

**What did you expect to happen?**
I expect trivy to ingnore `--template` when `--format` is not `template` according to printed warning
`WARN	--template is ignored because --format json is specified. Use --template option with --format template option.`

**What happened instead?**
After report is generated it fails with error:
`FATAL	unable to write results: Error retrieving template from path: open contrib/junit.tpl: no such file or directory`

**Output of run with `-debug`:**

Irrelevant

**Output of `trivy -v`:**

Version: 0.9.1
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2020-06-18 00:18:02.634272316 +0000 UTC
  NextUpdate: 2020-06-18 12:18:02.634272116 +0000 UTC

**Additional details (base image name, container registry info...):**
Irrelevant

I've created a PR with fix: https://github.com/aquasecurity/trivy/pull/556

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/pull/556
