### ISSUE TITLE
Oracle Linux support

### ISSUE THREAD

**Issue by nc-ruth** [aquasecurity/trivy#56]
Hi knqyf263,

Is there any plans to support Oracle Linux? 
Oracle Linux is like Amazon Linux (#44 ) a Redhat derivative.

Currently I get the following issue: FATAL   error in image scan: failed to scan image: unsupported os : oracle

Thank you for this awesome tool 🥇 

Best regards,
Ruba

**Comment by andreineustroev** [comment]
+1

**Comment by knqyf263** [comment]
I'm sorry to be late. Now, Trivy supports Oracle Linux 🎉  Thanks to @masahiro331 .
https://github.com/aquasecurity/trivy/pull/286
