### ISSUE TITLE
chore(misconf): Simplify nomenclature for misconfig checks

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#5609]
Today we have a variety of terms to refer to a `check`, namely: 
1. Policy
2. Check
3. Rule

All refer to the same concept of `checking` for a misconfiguration. We can simplify this and rename everything as a `check`. 

This will require an update to both the docs and the code. This applies to both Go and Rego.

**Comment by itaysk** [comment]
for reference: https://github.com/aquasecurity/trivy/discussions/3620

**Comment by knqyf263** [comment]
Sounds good. For example, will the policy bundle renamed to the check bundle?

**Comment by simar7** [comment]
> Sounds good. For example, will the policy bundle renamed to the check bundle?

Sounds reasonable. After all it is a bundle of checks 😄

**Comment by itaysk** [comment]
policy is overloaded. rule is not very accurate. check sounds ok to me. but i'm ok with any name we choose as long as it's consistent.

**Comment by knqyf263** [comment]
>i'm ok with any name we choose as long as it's consistent.

Same here. We just need consistency.

**Comment by nikpivkin** [comment]
@simar7 The documentation/cli flags still use the term `policy`. Will this be updated?

**Comment by simar7** [comment]
> @simar7 The documentation, cli flags and code still use the term `policy`. Will this be updated?

That's right. Once we have the `trivy-polcies` repo renamed to `trivy-checks`, we can start using it in Trivy and all it's parts (docs, flags, etc.)
