### ISSUE TITLE
--timeout doesn't work

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#568]
It looks like `--timeout` option doesn't work after supporting fs/repo scan.

`context.WithTimeout()` should be called here.
https://github.com/aquasecurity/trivy/blob/020c4a3b140b3ee329eba8926de79e2889ec9312/internal/artifact/run.go#L68
https://github.com/aquasecurity/trivy/blob/020c4a3b140b3ee329eba8926de79e2889ec9312/internal/client/run.go#L48

**Comment by knqyf263** [comment]
@rahul2393 could you help us with this issue?

**Comment by rahul2393** [comment]
Sure
