### ISSUE TITLE
PublishedDate and LastModifiedDate fields required

### ISSUE THREAD

**Issue by juan-chan** [aquasecurity/trivy#573]
The result of trivy does not contains `PublishedDate` and `LastModifiedDate` fields, but I think they are valuable, could you add these fields to the result? Thanks a lot!

**Comment by simar7** [comment]
hi @juan-chan – they will be once this PR is merged https://github.com/aquasecurity/trivy/pull/596

**Comment by juan-chan** [comment]
wow wonderful! thanks again.

![image](https://user-images.githubusercontent.com/49066821/96661786-8484c480-137f-11eb-816f-dd0c3f077825.png)

version: v0.12.0

**Comment by juan-chan** [comment]
ps: I didn't see them on the table format, could I config output fields in default format?

![image](https://user-images.githubusercontent.com/49066821/96661872-b5fd9000-137f-11eb-8854-05d8ecff0140.png)
