### ISSUE TITLE
fix(misconf): extended_auditing_policy remediation not working

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#5739]
The `extended_auditing_policy` block has been removed from the [azurerm_sql_server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server.html) resource, so the use of the `extended_auditing_policy` block should be replaced with [azurerm_mssql_server_extended_auditing_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server_extended_auditing_policy) in the examples.

### Discussed in https://github.com/aquasecurity/trivy/discussions/5738

<div type='discussions-op-text'>

<sup>Originally posted by **wednesday09** December  6, 2023</sup>
### Description

This is the remediation action for enabling audit on Azure SQL Databases and it's not working

LINK: https://avd.aquasec.com/misconfig/azure/database/avd-azu-0027
------------------------------------
I saw these 2 links for your reference:
https://github.com/hashicorp/terraform-provider-azurerm/issues/19376
https://github.com/hashicorp/terraform-provider-azurerm/pull/19390

### Desired Behavior

extended_auditing_policy block should work

### Actual Behavior

I got an error saying: Unexpected block: Blocks of type "extended_auditing_policy" are not expected here

### Reproduction Steps

```bash
resource "azurerm_sql_server" "good_example" {
   name                         = "mssqlserver"
   resource_group_name          = azurerm_resource_group.example.name
   location                     = azurerm_resource_group.example.location
   version                      = "12.0"
   administrator_login          = "mradministrator"
   administrator_login_password = "tfsecRocks"
 
   extended_auditing_policy {
     storage_endpoint                        = azurerm_storage_account.example.primary_blob_endpoint
     storage_account_access_key              = azurerm_storage_account.example.primary_access_key
     storage_account_access_key_is_secondary = true
     retention_in_days                       = 6
   }
 }

This is the sample on your recommended action, but the extended_auditing_policy don't work.
```

### Target

None

### Scanner

None

### Output Format

None

### Mode

None

### Debug Output

```bash
No debug output
```

### Operating System

Windows 10

### Version

```bash
1.5.4
```

### Checklist

- [ ] Run `trivy image --reset`
- [ ] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

**Comment by wednesday09** [comment]
Thanks @nikpivkin, I've been using that example on the link but I'm still having the same issue Unexpected block: Blocks of type "extended_auditing_policy" are not expected here everytime I do code check, and still referring to https://avd.aquasec.com/misconfig/azure/database/avd-azu-0027

I'm using this code for scanning my terraform, do I need to add or delete something on it?

- name: Trivy
  if: ${{ env.step_execution == 'true' }}
  uses: aquasecurity/trivy-action@master
  with:
      scan-type: 'config'
      scan-ref ./azure/
      exit-code: '1'

**Comment by nikpivkin** [comment]
Hi @wednesday09 .

A fix for the examples has not yet been released. You should use the `azurerm_mssql_server_extended_auditing_policy ` resource instead of the `extended_auditing_policy ` block.
