### ISSUE TITLE
What does the Trivy startup string template for Google Registry look like?

### ISSUE THREAD

**Issue by nbublikov** [aquasecurity/trivy#576]
Hello!
You need to run trivy in the form of a docker image to scan our google container registry, to enter there we use the login and password.

How the command to run will look like?

**Comment by knqyf263** [comment]
There are some ways.
For example,

```
$ docker run -v /path/to/credential.json:/tmp/credential.json -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/credential.json image [YOUR_IMAGE]
```

**Comment by nbublikov** [comment]
credential.json - how it's look like for example?)
image [YOUR_IMAGE] - how i should dpecify path to remote Google container registry?) it's not local image
