### ISSUE TITLE
 How can I detect vulnerabilities in a container image using trivy?

### ISSUE THREAD

**Issue by kwonsoonhong** [aquasecurity/trivy#58]

**Comment by kwonsoonhong** [comment]
where can i find a description of the detection process....
Currently, I am not sure how the process finds vulnerabilities in container images.

Thank you

**Comment by hijak** [comment]
it analizes the layers of the docker image against a cve database
`trivy IMAGE/NAME` should be enough

**Comment by knqyf263** [comment]
As @hijak said, the image name should be specified. If you have more questions, please reopen.

**Comment by christian-weiss** [comment]
After some month without response i think it is save to close this ticket.
