### ISSUE TITLE
filesystem scan with remote db

### ISSUE THREAD

**Issue by kostyrev** [aquasecurity/trivy#582]
is not architecturally possible to scan local filesystem and not to download trivy-db by using remote db?
my use case: I'm building packer images and do not want to download db every time in every image.

**Comment by simar7** [comment]
hi @kostyrev – were you looking for something like client/server mode https://github.com/aquasecurity/trivy#client--server but with filesystem scanning?

Would this be your use case:
`$ trivy client <path/to/directory>`

**Comment by kostyrev** [comment]
yep
```
trivy client --remote http://trivy-server.example.org:8080 /
```
but now it fails
```
2020-08-10T12:34:15.987Z	FATAL	failed to initialize options: invalid image: could not parse reference: /
```

**Comment by krol3** [comment]
@kostyrev  are you still with problems?

**Comment by knqyf263** [comment]
Unfortunately, filesystem mode doesn't support client/server at the moment. If other users also want the feature, we will add it to our backlog.

**Comment by knqyf263** [comment]
We will discuss this in https://github.com/aquasecurity/trivy/issues/634.
