### ISSUE TITLE
scan image with `--list-all-pkgs ` flag has missing os installed files with in the report

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#5857]
when running a simple  scan:
 ```sh
trivy image nginx --list-all-pkgs --format json
```
OS packages installed files are detected from each layer and [apply it to map](https://github.com/aquasecurity/trivy/blob/main/pkg/fanal/applier/docker.go#L114)

Each layer has different installed files on packages.
Since the map key is the same `var/lib/dpkg/status/type:ospkg` for os packages then it get overwritten by the different layers

**Comment by knqyf263** [comment]
I'm still debugging this issue, but it looks like the installed files need to be handled similarly to licenses since dpkg has separate files for installed files, unlike apk and rpm.
https://github.com/aquasecurity/trivy/blob/1f0d6290c33c95d5f213cc409a0ff6a53a2c888e/pkg/fanal/applier/docker.go#L187-L206

**Comment by knqyf263** [comment]
I'm sorry I forgot to look into it.
@DmitriyLewen Could you take a look?

**Comment by DmitriyLewen** [comment]
@knqyf263 I have researched this problem and have not found better solution than the one you suggested.
I created #6682 with a fix.

**Comment by knqyf263** [comment]
@DmitriyLewen Do you think we can polish [the existing PR](https://github.com/aquasecurity/trivy/pull/5844) from Chen? Or should we create a new PR?

**Comment by DmitriyLewen** [comment]
Chena and my PR are different.
Chen updated analyzers for  Node package and Python packaging (though I didn’t understand why).
I also used different logic for `applier` (I created common map similar to the one for secrets).
Therefore, it was easier for me to create new PR.
