### ISSUE TITLE
Support AWS Security Finding Format (ASFF)

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#586]
Support ASFF via `--template` like JUnit XML and SARIF.
https://aws.amazon.com/jp/blogs/security/how-to-build-ci-cd-pipeline-container-vulnerability-scanning-trivy-and-aws-security-hub/
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html

**Comment by knqyf263** [comment]
@rahul2393 Let me assign this task to you.

**Comment by rahul2393** [comment]
Thanks

**Comment by knqyf263** [comment]
done
