### ISSUE TITLE
Reusing initial scan results

### ISSUE THREAD

**Issue by sukhinin** [aquasecurity/trivy#589]
Our use case is as follows:
* Containers could run for a long time (months)
* Images could be heavy (gigabytes)
* There are a lot different images (hundreds)

The goal is to detect vulnerabilities that were announced after the image has been built.

Is it possible to save a list of packages found in some image and later check this list against up-to-date vulnerabilities database without pulling and re-scanning the image every time? This way we could run a slow full image scan once at the build time and then schedule fast periodic checks.

**Comment by knqyf263** [comment]
Trivy stores layer id in the cache so that it can skip downloading the layer next time. If your image is not updated often, the second scan should be pretty fast. You can also use the client/server mode for the purpose.
https://github.com/aquasecurity/trivy#client--server

Also, if your images share the base image, trivy can skip downloading the layers of the base image.

**Comment by sukhinin** [comment]
> Trivy stores layer id in the cache so that it can skip downloading the layer next time.

Does Trivy need the layer data to be available locally after the first scan or will it reuse data gathered during the first scan?

> You can also use the client/server mode for the purpose.

Do I get it right that the client scans the image, extracts software metadata, and then queries the server if there are any vulnerabilities? Is it a client or the server who maintains the cache in this case? I've read the docs but wasn't able to find an answer to this question.

**Comment by knqyf263** [comment]
>Does Trivy need the layer data to be available locally after the first scan or will it reuse data gathered during the first scan?

Trivy reuses data gathered during the first scan.

>Do I get it right that the client scans the image, extracts software metadata, and then queries the server if there are any vulnerabilities? Is it a client or the server who maintains the cache in this case?

The client sends software metadata with the layer id to the server and the server stores it in the cache. Next time, the client asks which layer ids are missing in the server cache and fetches missing layers only.

**Comment by sukhinin** [comment]
Thank you, this answers my question.
