### ISSUE TITLE
Scan private git repositories

### ISSUE THREAD

**Issue by viniciusgarcia-hotmart** [aquasecurity/trivy#592]
Hello, I saw that currently private git repositories are not supported, although seems a very easy goal since you guys are using go-git v5, so my question is, is there any security reason to don't do that?

Thanks in advance

**Comment by simar7** [comment]
hi @viniciusgarcia-hotmart to keep things simple we started with only supporting public repos. What's your use case? 

cc @knqyf263

**Comment by viniciusgarcia-hotmart** [comment]
Sure, I understand. I was just wondering why this feature is not present.

**Comment by knqyf263** [comment]
Thank you for understanding. When you need the private repo scanning, feel free to reopen this PR.

**Comment by antoineozenne** [comment]
Please, reopen this. This feature could be very nice to scan our multiple private repos from our multiple teams. It's more easier to maintain a list of private repos to scan than to update each repo's CI to scan local filesystem in each CI pipeline.

**Comment by macedogm** [comment]
Hi @simar7 and @knqyf263 👋🏻 
This features is really handy, specially to automate scans of GitHub and GitLab orgs with tons of private repos.
I'm willing to work on this, as a way of contributing back. If I make a good patch, would you be willing to merge it?
Best regards.

**Comment by knqyf263** [comment]
@macedogm Cool. We always welcome your contribution! You have to update the following lines.
https://github.com/aquasecurity/fanal/blob/03efbabc6a16c06f7dc43d7cbfb789a146f9ba98/artifact/remote/git.go#L39-L43

**Comment by macedogm** [comment]
I've opened PR https://github.com/aquasecurity/fanal/pull/253 with a proposal for this feature.

**Comment by macedogm** [comment]
@knqyf263 Not sure if you were able to review PR https://github.com/aquasecurity/fanal/pull/253. I appreciate if you could let me know if it requires any improvements or looks good.
