### ISSUE TITLE
Reporting kernel CVEs

### ISSUE THREAD

**Issue by andrei-dascalu** [aquasecurity/trivy#609]
Hello,

I have a few n00b-ish questions regarding reporting kernel CVEs:

1. How does trivy identify the kernel? Is it based on the generic version of the base image? Is it based on the host where the scan takes place (since an image actually shares the host's kernel)

2. Is there a way to optionally suppress listing kernel-related issues? I would find it useful since I may not scan an image on the same host where it's going to run. 

3. Generally, does it make sense to report kernel CVEs ?

Thanks

**Comment by simar7** [comment]
> Hello,
> 
> I have a few n00b-ish questions regarding reporting kernel CVEs:
> 
> 1. How does trivy identify the kernel? Is it based on the generic version of the base image? Is it based on the host where the scan takes place (since an image actually shares the host's kernel)
> 2. Is there a way to optionally suppress listing kernel-related issues? I would find it useful since I may not scan an image on the same host where it's going to run.
> 3. Generally, does it make sense to report kernel CVEs ?
> 
> Thanks

hi @andrei-dascalu – trivy scans by image not by kernel. So if you scan a `centos:7` image, all the packages and libraries contained within would be scanned for vulnerabilities.

for the second and third question, do you have an example?

**Comment by dinvlad** [comment]
Could we perhaps add a switch to ignore all kernel CVEs?
