### ISSUE TITLE
feat(misconf): Improve scan results messaging

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#6138]
When reporting misconfiguration scanning results we can be more descriptive about how many "total" files were scanned and how many "misconfigured" files were found.

See context below for details:

Trivy successfully scans the ARM template. I think the message `Detected config files: 0` might be misleading.

@simar7 The issue is that the Azure state for the scan was empty and no checks were applied to it, so Trivy [reported](https://github.com/aquasecurity/trivy/blob/aadbad1d7827cd1af955ce654e943609e05f1745/pkg/scanner/local/scan.go#L224) that 0 configs were detected.

_Originally posted by @nikpivkin in https://github.com/aquasecurity/trivy/discussions/6123#discussioncomment-8466851_

**Comment by nikpivkin** [comment]
@simar7 Should we only change the wording of the `Detected config files: ...` message, or should we add some other messages? Does it make sense for users to report how many files have been checked?

**Comment by simar7** [comment]
@nikpivkin as you brought up [here](https://github.com/aquasecurity/trivy/pull/6307#discussion_r1522605485) this result contains passed items as well. I looked into adding more logic to decouple that but didn't finish the implementation. 

Ideally if we can show the user how many "relevant" files were scanned by the IaC scanner, it would be more relevant. In this case a "relevant" file would be the one that we've processed through the scanner. Currently we don't keep track of this AFAIK.

**Comment by simar7** [comment]
I've created https://github.com/aquasecurity/trivy/pull/7473 as I think it is sufficient to show the count of files scanned and the count of "relevant" config files found that were scanned. Besides this, I'm not sure what much we can do in this case to improve it.

**Comment by nikpivkin** [comment]
@simar7 Is there a need to report how many total files were scanned? We can report the number of files with misconfigurations.

**Comment by simar7** [comment]
I think we're good for now.

**Comment by veryhappythings** [comment]
I think there's a need for this, and maybe I'm missing something available in the tool. I need to provide an auditor with proof that we've run a secret scan (`trivy repo --scanners secret .`), and although it's scanned my entire repo, the output implies that it hasn't:

```
2026-07-14T20:06:10Z	INFO	[secret] Secret scanning is enabled
2026-07-14T20:06:10Z	INFO	[secret] Please see https://trivy.dev/docs/v0.69/guide/scanner/secret#recommendation for faster secret detection
2026-07-14T20:06:12Z	WARN	[pip] Unable to find python `site-packages` directory. License detection is skipped.	err="site-packages directory not found"
2026-07-14T20:06:12Z	INFO	Suppressing dependencies for development and testing. To display them, try the '--include-dev-deps' flag.
2026-07-14T20:06:12Z	INFO	Number of language-specific files	num=3


Report Summary
📣 Notices:

  - Version 0.72.0 of Trivy is now available, current version is 0.69.2

To suppress version checks, run Trivy scans with the --skip-version-check flag

┌───────────────────────────────┬───────┬─────────┐
│            Target             │ Type  │ Secrets │
├───────────────────────────────┼───────┼─────────┤
│ <redacted>                    │ gomod │    -    │
├───────────────────────────────┼───────┼─────────┤
│ <redacted>                    │  uv   │    -    │
├───────────────────────────────┼───────┼─────────┤
│ <redacted>                    │ gomod │    -    │
└───────────────────────────────┴───────┴─────────┘
Legend:
- '-': Not scanned
- '0': Clean (no security findings detected)
```

A readout of "x scanned files, 0 secrets found" would resolve my issue - this looks like it found 3 files and didn't scan them. I've run the scan with debug logging and found that it is indeed scanning my entire repo. Would you consider re-opening this issue for this?

**Comment by Aakarsh133** [comment]
Hey @nikpivkin @simar7 if you are interested in reopening this issue I would be happy to take it up. I believe `-`/`0` only differentiates between not scanned and clean. However it does not exclusively tell whether scan actually ran or not even though it does. I believe we do not need to make any changes in the core changes itself but it is a reporting problem. Also many like @veryhappythings would insist on a auditable format like "N files scanned, 0 secrets found". Looking forward to your suggestions.

**Comment by veryhappythings** [comment]
I've been mucking about a bit and I've got something that gives an output like:

```
Scan Statistics

Files scanned: 10
- Secrets: 10 file(s) scanned, 1 finding(s)
- Licenses: 4 file(s) scanned, 4 finding(s)
```

Which is exactly what would be useful to me.
