### ISSUE TITLE
Introduce golangci-lint

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#616]
https://github.com/golangci/golangci-lint

They have official GitHub Action.
https://github.com/golangci/golangci-lint-action

I think we can disable some of linters such as `errcheck`, `gochecknoglobals` and `gochecknoinits`. At first, we have to run golangci-lint on local machine and figure out how many errors Trivy has and fix them as much as possible.

**Comment by knqyf263** [comment]
@rahul2393 Would you work on it?

**Comment by rahul2393** [comment]
Yeah, thanks for tagging me, Let me check how many errors currently we have
