### ISSUE TITLE
fluky test: aws cloud test

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#6174]
Fluky test: aws cloud test
https://github.com/aquasecurity/trivy/actions/runs/7986747930/job/21807769672?pr=5988

**Comment by simar7** [comment]
GitHub deletes old log output. So just in case if it does, below is the issue.

<img width="1040" alt="image" src="https://github.com/aquasecurity/trivy/assets/1254783/af690bbd-b968-418f-b459-3a046a4a586e">

**Comment by knqyf263** [comment]
AWS is now a plugin. I'd close it.
