### ISSUE TITLE
trivy k8s: `--disable-node-collector` flag

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#6194]
it is require to introduce a new flag `--disable-node-collector`
when the flag is in use trivy will not run `node-collector` job and the scan result will not present misconfiguration finding from inside the Node

- when the flag is not in use the `node-collector` job will not be executed and the scan result will not present misconfiguration finding from inside the Node

- remove old `--components` flag as it cannot operate in conjunction with this flag

**Comment by knqyf263** [comment]
The default is running node-collector. Is it okay for you? @itaysk

**Comment by chen-keinan** [comment]
> The default is running node-collector. Is it okay for you? @itaysk

@knqyf263 yes, node-collector will run by default, see use-cases table here: #5745
