### ISSUE TITLE
use `--vuln-type` flag for `Packages`

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#6269]
## Description
`--vuln-type` flag was added in v0.0.1 even before SBOM. It makes sense to add support for packages.

**Comment by DmitriyLewen** [comment]
:tada: :tada: :tada:  [v0.52.0](https://github.com/aquasecurity/trivy/releases/tag/v0.52.0) already support this (after #6765) :tada: :tada: :tada: :
```bash
➜ trivy -q image aquasec/trivy --vuln-type os,library -f json --list-all-pkgs | grep '"Class":'
      "Class": "os-pkgs",
      "Class": "lang-pkgs",

➜ trivy -q image aquasec/trivy --vuln-type os -f json --list-all-pkgs | grep '"Class":'
      "Class": "os-pkgs",

➜ trivy -q image aquasec/trivy --vuln-type library -f json --list-all-pkgs | grep '"Class":'
      "Class": "lang-pkgs",
```

**Comment by DmitriyLewen** [comment]
since this flag now works for `Packages` - maybe we should change its name to `--pkg-type`.
@knqyf263 wdyt?

**Comment by knqyf263** [comment]
> since this flag now works for `Packages` - maybe we should change its name to `--pkg-type`. @knqyf263 wdyt?

It makes sense.
