### ISSUE TITLE
bug(amazonlinux): Trivy marks `Amazon Linux` version as EOL if `*/system-release` file uses `2023.xxx.xxx` format

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#6294]
## Description
Trivy marks `Amazon Linux` version as EOL if `*/system-release` file uses `2023.xxx.xxx` format
See example in https://github.com/aquasecurity/trivy-db/issues/390

**Comment by Xeroxxx** [comment]
@DmitriyLewen @knqyf263 

Thank you so much for quickly solving this issue! When can we expect the next release of trivy, which will solve the problem with the official trivy Docker images?

**Comment by DmitriyLewen** [comment]
@Xeroxxx  https://github.com/aquasecurity/trivy/milestone/32
