### ISSUE TITLE
webhook support

### ISSUE THREAD

**Issue by cho0o0** [aquasecurity/trivy#632]
Hi, I came across a use case that I needed to send Trivy's scan results to another server. I believe it will be nice to support an  option like `webhook` so that people like me can easily integrate Trivy with webhook endpoints.
I already forked the repository thus I'd like to make a pull request later. It would be more than appreciated to have a review of it.

**Comment by krol3** [comment]
@knqyf263 we could use the [Postee](https://github.com/aquasecurity/postee) plugins integrations to webhoook support. what do you think ?

**Comment by knqyf263** [comment]
Yes, we added the `plugin` architecture https://github.com/aquasecurity/trivy/pull/878. The webhook should be supported by a plugin.

**Comment by knqyf263** [comment]
We have a plugin feature now. Please try it out.
https://aquasecurity.github.io/trivy/v0.18.3/plugins/
