### ISSUE TITLE
Trivy not showing vulnerabilities

### ISSUE THREAD

**Issue by alterEgo123** [aquasecurity/trivy#635]
Hello,
Running trivy  image --output json  nginx:1.16.1 doesn't return the vulnerabilities, only the count of each type.

```
2020-09-11T15:27:47.786Z	INFO	Detecting Debian vulnerabilities...

nginx:1.16.1 (debian 10.3)
==========================
Total: 132 (UNKNOWN: 0, LOW: 93, MEDIUM: 35, HIGH: 4, CRITICAL: 0)
```

How can I return the vulnerabilities?

**Comment by computeralex92** [comment]
The option ```--output``` is not defining the format of the output, but instead the name of file where is output is saved.
If you want to have a JSON output on stdout, the option ```--format``` is working:

```
$ trivy image --format json nginx:1.16.1
2020-09-12T17:56:12.867+0200	INFO	Detecting Debian vulnerabilities...
[
  {
    "Target": "nginx:1.16.1 (debian 10.3)",
    "Type": "debian",
    "Vulnerabilities": [
      {
...
```

See also https://github.com/aquasecurity/trivy#save-the-results-as-json
