### ISSUE TITLE
0.50.0 : big time increase of FS scanning vs 0.49.1

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#6374]
### Discussed in https://github.com/aquasecurity/trivy/discussions/6355

<div type='discussions-op-text'>

<sup>Originally posted by **jlamande** March 20, 2024</sup>
### Question

Scanning in a CI job with exactly the same setup (only changed the trivy version, scanned fs is the same).

With trivy 0.50.0 _(done multiple times with equivalent durations)_

```
time trivy fs --exit-code 0 --scanners vuln --ignore-unfixed "pom.xml"
2024-03-20T05:21:41.521Z	INFO	Vulnerability scanning is enabled
2024-03-20T05:25:47.917Z	INFO	Number of language-specific files: 1
2024-03-20T05:25:47.917Z	INFO	Detecting pom vulnerabilities...
pom.xml (pom)
=============
Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 4, CRITICAL: 0)
real	4m 7.63s
user	0m 12.08s
sys	0m 2.10s
```

With trivy 0.49.1 _(done multiple times with equivalent durations)_

```
time trivy fs --exit-code 0 --scanners vuln --ignore-unfixed "pom.xml"
2024-03-20T07:36:22.530Z	INFO	Vulnerability scanning is enabled
2024-03-20T07:36:30.896Z	INFO	Number of language-specific files: 1
2024-03-20T07:36:30.896Z	INFO	Detecting pom vulnerabilities...
pom.xml (pom)
=============
Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 4, CRITICAL: 0)

real	0m 9.59s
user	0m 6.63s
sys	0m 0.31s
```

Does anyone see the same behavior ?

Is there some new option to enable in 0.50 to avoid this time increase ?

### Target

Filesystem

### Scanner

Vulnerability

### Output Format

None

### Mode

Standalone

### Operating System

Docker

### Version

```bash
Version: 0.50.0
```
</div>

**Comment by decorup** [comment]
I can confirm the issue.

Scan for the same repo. Scan output for 0.49.1 trimmed.

for trivy 0.49.1
```
trivy fs --scanners vuln,misconfig .    
2024-03-26T09:47:04.895+0100	INFO	Need to update DB
2024-03-26T09:47:04.895+0100	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2024-03-26T09:47:04.895+0100	INFO	Downloading DB...
44.64 MiB / 44.64 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 15.69 MiB p/s 3.0s
2024-03-26T09:47:08.874+0100	INFO	Vulnerability scanning is enabled
2024-03-26T09:47:08.874+0100	INFO	Misconfiguration scanning is enabled
2024-03-26T09:49:27.265+0100	INFO	Number of language-specific files: 28
2024-03-26T09:49:27.265+0100	INFO	Detecting pom vulnerabilities...
2024-03-26T09:49:27.380+0100	INFO	Detected config files: 7
```

for trivy 0.50.0

```
trivy fs --scanners vuln,misconfig .
2024-03-26T09:52:01.415+0100	INFO	Vulnerability scanning is enabled
2024-03-26T09:52:01.415+0100	INFO	Misconfiguration scanning is enabled
2024-03-26T09:57:01.403+0100	WARN	Increase --timeout value
2024-03-26T09:57:01.403+0100	FATAL	filesystem scan error: scan error: scan failed: failed analysis: walk filesystem: walk error: unknown error with ./ums: failed to analyze file: analyze file (ums/pom.xml): semaphore acquire: context deadline exceeded
```

**Comment by awakenine** [comment]
I can confirm the issue.

Below is scan output for the same repo. Scan output for 0.49.1 trimmed.

for trivy 0.49.1
```
trivy fs --scanners vuln,misconfig .    
2024-03-26T09:47:04.895+0100	INFO	Need to update DB
2024-03-26T09:47:04.895+0100	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2024-03-26T09:47:04.895+0100	INFO	Downloading DB...
44.64 MiB / 44.64 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 15.69 MiB p/s 3.0s
2024-03-26T09:47:08.874+0100	INFO	Vulnerability scanning is enabled
2024-03-26T09:47:08.874+0100	INFO	Misconfiguration scanning is enabled
2024-03-26T09:49:27.265+0100	INFO	Number of language-specific files: 28
2024-03-26T09:49:27.265+0100	INFO	Detecting pom vulnerabilities...
2024-03-26T09:49:27.380+0100	INFO	Detected config files: 7
```

for trivy 0.50.0
```
trivy fs --scanners vuln,misconfig .
2024-03-26T09:52:01.415+0100	INFO	Vulnerability scanning is enabled
2024-03-26T09:52:01.415+0100	INFO	Misconfiguration scanning is enabled
2024-03-26T09:57:01.403+0100	WARN	Increase --timeout value
2024-03-26T09:57:01.403+0100	FATAL	filesystem scan error: scan error: scan failed: failed analysis: walk filesystem: walk error: unknown error with ./ums: failed to analyze file: analyze file (ums/pom.xml): semaphore acquire: context deadline exceeded
```

**Comment by knqyf263** [comment]
It was fixed in [v0.50.2](https://github.com/aquasecurity/trivy/releases/tag/v0.50.2). Please let us know if it still persists.

**Comment by knqyf263** [comment]
>2024-04-23T06:40:26.542Z	DEBUG	Failed to fetch from maven.java.net/content/repositories/releases/org/jetbrains/annotations/13.0/annotations-13.0.pom


@DmitriyLewen Do you think the fetching failure will be resolved by https://github.com/aquasecurity/trivy/issues/6508? It seems something different since it's not a snapshot.

**Comment by DmitriyLewen** [comment]
It looks like some pom files contain enabled repositories.
So Trivy (like `mvn`) checks these repositories first. If there are no dependencies in the repositories -> Trivy checks maven Central.

Similar example in #6412 description (see `release version + release repository enable` spoiler).

**Comment by knqyf263** [comment]
OK, so is it the same behavior as `mvn` and intentional?

**Comment by DmitriyLewen** [comment]
I'm pretty sure yes.
If @azdanov shares test `pom.xml` file, I can compare `mvn` and `Trivy` logic.

**Comment by azdanov** [comment]
@DmitriyLewen 
<details><summary>pom.xml</summary><pre><?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.4</version>
        <relativePath/>
    </parent>
    <groupId>org.example</groupId>
    <artifactId>example</artifactId>
    <version>0.1.0</version>
    <name>Example</name>
    <description>Work on Example</description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.vault</groupId>
            <artifactId>spring-vault-core</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web-services</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>nz.net.ultraq.thymeleaf</groupId>
            <artifactId>thymeleaf-layout-dialect</artifactId>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity6</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>9.37.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
            <version>2.9.1</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.13.0</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.30</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>dev.fitko.fitconnect.sdk</groupId>
            <artifactId>client</artifactId>
            <version>2.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.passay</groupId>
            <artifactId>passay</artifactId>
            <version>1.6.4</version>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-admin-client</artifactId>
            <version>23.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>1.78</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>6.1.6</version>
        </dependency>
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <version>5.15.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.0.0-jre</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-client-java</artifactId>
            <version>5.15.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <version>1.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>example</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <profiles>
                        <profile>local</profile>
                    </profiles>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/*IT.java</include>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>unit</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <includes>
                                <include>**/*Test.java</include>
                            </includes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>integration</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <includes>
                                <include>**/*IT.java</include>
                            </includes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>netty-resolver-dns-native-macos-aarch64</id>
            <activation>
                <os>
                    <family>mac</family>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-resolver-dns-native-macos</artifactId>
                    <classifier>osx-aarch_64</classifier>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
</pre></details>

**Comment by DmitriyLewen** [comment]
Looks like most fetching errors when Trivy parses parents. But `mvn` doesn't logs about parents.

But i found 1 case when `mvn` tries to download from another repository:
```
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/io/projectreactor/reactor-bom/2020.0.8/reactor-bom-2020.0.8.pom
Downloading from central: https://repo.maven.apache.org/maven2/io/projectreactor/reactor-bom/2020.0.8/reactor-bom-2020.0.8.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/projectreactor/reactor-bom/2020.0.8/reactor-bom-2020.0.8.pom (4.5 kB at 51 kB/s)
```

So I think Trivy works like `mvn`.

**Comment by mateuszkozakiewicz** [comment]
I've noticed a significant increase of scan times for pom.xml files after updating from 0.46.0 to 0.53.0
Trivy 0.46.0
```
pom.xml (pom)

Total: 13 (UNKNOWN: 0, LOW: 1, MEDIUM: 5, HIGH: 7, CRITICAL: 0)

real    3m 8.25s
user    0m 1.37s
sys     0m 0.24s
```
Trivy 0.53.0
```
pom.xml (pom)

Total: 15 (UNKNOWN: 0, LOW: 1, MEDIUM: 6, HIGH: 7, CRITICAL: 1)

real    9m 2.10s
user    0m 1.88s
sys     0m 0.76s
```
Is there something that can be done?

**Comment by DmitriyLewen** [comment]
now we check repositories like maven does.
you can use `mvn dependency:resolve` to download dependencies - this will speed up the scan

**Comment by mateuszkozakiewicz** [comment]
If Trivy is downloading those files shouldn't subsequent runs be faster, isn't there some sort of cache?
It doesn't appear to be the case currently, at least I can't spot a difference in execution times.
It would be far easier to cache that directory between pipeline runs than run extra stage just to download maven dependencies for Trivy.

**Comment by DmitriyLewen** [comment]
Unfortunately, Trivy doesn't currently save cache for `fs` mode.
