### ISSUE TITLE
Excluding Paths in Rego

### ISSUE THREAD

**Issue by pryorda** [aquasecurity/trivy#652]
Is there a way to exclude paths within the example rego files?

**Comment by knqyf263** [comment]
What is the path? Do you mean a path to a lock file like `/app/Gemfile.lock`?

**Comment by pryorda** [comment]
@knqyf263 Correct

**Comment by knqyf263** [comment]
Rego receives detected vulnerabilities only. If you want to exclude paths, you can use `--skip-files` or `--skip-dirs`.

**Comment by pryorda** [comment]
Can you combine the rego with those and .trivyignore?

**Comment by knqyf263** [comment]
They can be used together.
