### ISSUE TITLE
Hacktoberfest at Aqua Security

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#653]
Dear community, we appreciate you and your contribution to the success of our open source projects! In celebration of [Hacktoberfest](https://hacktoberfest.digitalocean.com/), we would like to extend our appreciation and reward your hard work. This repository is participating in Aqua Security 2020 Hacktoberfest campaign. For full details and guidelines please visit the official repo: [Hacktoberfest at Aqua Security](https://github.com/aquasecurity/Hacktoberfest).

**Comment by simar7** [comment]
Thanks for everyone's contributions! 🎊
