### ISSUE TITLE
The InstalledFile of dpkg package should exclude directories

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#6548]
## Description
The logic to exclude directories doesn't work in cases where a list of files/dirs is not sorted.
https://github.com/aquasecurity/trivy/blob/164b025413c5fb9c6759491e9a306b46b869be93/pkg/fanal/analyzer/pkg/dpkg/dpkg.go#L126-L135

**Comment by y4ney** [comment]
Hi,@knqyf263 ! I have submitted a [PR](#6551 ) to address this issue and would appreciate your review.
