### ISSUE TITLE
perf(misconf): High memory usage (9.5 GB) and long scan time (45 min) on some repos

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#6557]
### Discussed in https://github.com/aquasecurity/trivy/discussions/6549 and https://github.com/aquasecurity/trivy/discussions/6517

<div type='discussions-op-text'>

<sup>Originally posted by **ptupitsyn** April 24, 2024</sup>
### Description

Some repos, like https://github.com/kubernetes/minikube, take a very long time to scan (45 minutes on `t3.xlarge`) and consume up to 9.5 GB of RAM.

### Desired Behavior

Memory consumption below 1 GB, scan time under 5 minutes.

### Actual Behavior

Memory consumption of 9.5 GB, scan time 45 minutes.

### Reproduction Steps

```bash
1. git clone https://github.com/kubernetes/minikube.git
2. cd minikube
3. docker run -v $PWD:/myapp --entrypoint "trivy" aquasec/trivy --timeout 60m --quiet filesystem --scanners vuln,config --format json  /myapp
```

### Target

Filesystem

### Scanner

Vulnerability

### Output Format

JSON

### Mode

Standalone

### Debug Output

```bash
No output.
```

### Operating System

Ubuntu 22.04

### Version

```bash
0.50.2
```

### Checklist

- [X] Run `trivy image --reset`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

**Comment by simar7** [comment]
Looks like the issue lies [here](https://github.com/aquasecurity/trivy/blob/94d6e8ced63232728e5b743353871404e5486e9a/pkg/misconf/scanner.go#L506-L521)

We seem to spend an awful lot of time getting the underlying metadata for the code snippets to show in the results. This involves reading each file that has a misconfiguration, which is expensive to do with large repos as there are many files.

<img width="426" alt="image" src="https://github.com/aquasecurity/trivy/assets/1254783/20e1d84c-934b-4fbf-8a59-6ce1754fe2cc">


### Results

Input: https://github.com/kubernetes/minikube.git  

#### Before
```Doesn't finish in a reasonable time```

#### After
```
./trivy --debug config ~/repos/trivy-issues/6557/minikube/

  194.62s user 5.54s system 152% cpu 2:11.61 total
```


### Conclusion
Maybe we should disable code snippets with such large repos (many files) as it is very expensive to read each file individually to know the source of misconfiguration. 

To be clear, misconfigurations are still shown, just not the code snippets. They will look as follows:

<img width="1311" alt="image" src="https://github.com/aquasecurity/trivy/assets/1254783/007e2353-4258-4035-900a-7cbab1047d69">

**Comment by DmitriyLewen** [comment]
I also have some thoughts:
- I don't have much experience with `trivy/iac`, so I could be wrong.
    Why do we need to read files again to get wrong code? Can we store cause code (like we do for secrets - we store previous and next line for secret as soon as we find it). My idea: scan file -> detect misconfiguration -> save wrong line in `Result`. @simar7 correct me if this is not possible.
  This should save time, but we still need to double-check memory usage.
- Do we need to read files if the check passes?

**Comment by ptupitsyn** [comment]
It would be great to be able to toggle code snippets with a CLI flag. Disable them when not needed to improve performance.

**Comment by DmitriyLewen** [comment]
@simar7 i agree with @ptupitsyn .
I would also choose a new flag to add more variety to the trivi experience.

**Comment by knqyf263** [comment]
I'm still wondering why it consumes 9.5 GB. If it reads each file individually, it doesn't use so much memory. Or does it keep all the file content in memory?

**Comment by kaypee90** [comment]
> It would be great to be able to toggle code snippets with a CLI flag. Disable them when not needed to improve performance.

I agree with @ptupitsyn's approach
