### ISSUE TITLE
Trivy behind corporate proxy?

### ISSUE THREAD

**Issue by SK360** [aquasecurity/trivy#66]
We are behind a corporate proxy, we currently set proxy via http_proxy & https_proxy environment variables.  It seems Trivy is not picking this up.   When trying to run trivy against an image we are getting back:

`2019-06-03T17:49:49.296Z        FATAL   error in vulnerability DB update: error in vulnsrc clone or pull: failed to clone repository: error in git clone: failed to exec: exit status 128`

**Comment by mai346** [comment]
git clone fails:
To avoid this, set proxy to "~/.gitconfig".

Failure to acquire vulnerability information:
This can be avoided by defining proxy environment variables.

Could not get image from dockerhub:
In docker environment, if "/var/run/docker.sock" is bound, it can process host side image.
(I don't know how to get the image directly.)

**Comment by webmutation** [comment]
same issue... behind corporate proxy it is not able to fetch the vulnerability db

**Comment by vjtm** [comment]
Hi,
If it helps, in my case the disk was full.

**Comment by ngauje** [comment]
Behind a proxy I can fetch the vuln DB but it fails after : 
error in image scan: failed to analyze image: failed to extract files: failed to create the registry client: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.0.254: no such host

This is strange because I want to scan an image on a private registry without auth.
**Can someone explain what is this GET on registry-1.docker.io ?**
The nslookup fails because I don't have a DNS, every http should pass through proxy connect.

**Comment by ngauje** [comment]
Solved this by :
1. Downloading my image using `skopeo copy` (should work with `docker copy` but skopeo is great for CI)
2. Using `trivy --input`

DB download is correctly using https_proxy/http_proxy setting. Try with `trivy --download-db-only`

Great product btw !

**Comment by krol3** [comment]
@SK360 do you still with problems using Trivy behind proxy?

**Comment by SK360** [comment]
@krol3 we are now using the aquasec/trivy docker image and setting HTTP_PROXY and HTTPS_PROXY variables and all seems to be fine now.

**Comment by krol3** [comment]
Thanks for your reply. I will close this issue.

**Comment by alainlompo** [comment]
I am still having the issue to download the DB behing an enterprise proxy as of today.I am using the trivy CLI and  I have set the http/https_proxy environment variables but without success.

$ trivy sbom --format json ./target/bom.json
2023-03-09T10:51:29.507+0100    INFO    Need to update DB
2023-03-09T10:51:29.507+0100    INFO    DB Repository: ghcr.io/aquasecurity/trivy-db
2023-03-09T10:51:29.507+0100    INFO    Downloading DB...
2023-03-09T10:51:58.687+0100    WARN    Increase --timeout value
2023-03-09T10:51:58.687+0100    FATAL   init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: Get "https://ghcr.io/v2/": dial tcp 140.82.121.33:443: i/o timeout
