### ISSUE TITLE
Readme doc Update

### ISSUE THREAD

**Issue by Surajv311** [aquasecurity/trivy#664]
I believe that the README.md file can be updated. 
I can add the **Credits** section in the **Table of Contents** in the README.md file.
(As it has been followed in other participating repos.)
@knqyf263

**Comment by knqyf263** [comment]
Thank you for the suggestion! Could you tell me other repos you mentioned?

**Comment by Surajv311** [comment]
@knqyf263 Sir, I mean that the table of contents in the repos has been referenced to every part of Readme.md file. Hence I thought adding & referencing the credits section may enhance the readme file of current repo.

**Comment by knqyf263** [comment]
I see. I thought you meant other repositories. I'm sorry, but I don't think `Credits` is necessary in the TOC for now. I have intentionally omitted some parts of README to avoid making the TOC longer.

**Comment by Surajv311** [comment]
@knqyf263 Okay. Thanks for the info 👍
