### ISSUE TITLE
make --skip-dirs / --skip-files available when using trivy client

### ISSUE THREAD

**Issue by Alexc0007** [aquasecurity/trivy#665]
Hi, 
i think it would be useful to make the option --skip-dirs / --skip-files available when using trivy client.
to tell the server which directories of files to skip when traversing.

for now the option is only available when using trivy image...

**Comment by Alexc0007** [comment]
Hi,
is there a plan to make this happen?
it could be super useful

**Comment by knqyf263** [comment]
I've added this task to the backlog. It is good the first issue.
