### ISSUE TITLE
PDF output format

### ISSUE THREAD

**Issue by alterEgo123** [aquasecurity/trivy#680]
I think it might useful to generate trivy reports as pdf. I, for example need to report image scans to my manager and it would be better for him to read a pdf rather than screenshots.

**Comment by pippo** [comment]
I'd like to give this a try.

**Comment by simar7** [comment]
hi @alterEgo123 there has been some previous work w.r.t. adding support for HTML template [here](https://github.com/aquasecurity/trivy/pull/567), which could be rendered as a PDF as well. Was that what you had in mind or something else?

**Comment by alterEgo123** [comment]
@simar7 in the simplest of ways, I thought about generating a PDF with Trivy's output as it is, but I think that an HTML template would be much nicer

**Comment by knqyf263** [comment]
If you still need PDF, please feel free to reopen the issue. Thanks.
