### ISSUE TITLE
Skip downloading DB if a remote DB is not updated

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#684]
When the cron job building trivy-db on GitHub Actions fails, trivy downloads an old DB and tries to download the latest db again at every start time.
https://github.com/aquasecurity/trivy/issues/675

Trivy should skip downloading DB if a remote DB is not updated.

**Comment by neha-viswanathan** [comment]
Hi @knqyf263 do you think this would help - https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action

**Comment by knqyf263** [comment]
No, I don't think so. It is a cache for GitHub Actions, right? I meant Trivy's runtime cache.

**Comment by mozillazg** [comment]
@knqyf263 What do you think about add a new field `DownloadedAt` to `metadata.json` after download db, and check value of this new field to see whether it should to download new version of db (only download when `DownloadedAt < now - 1hour`).

**Comment by knqyf263** [comment]
@mozillazg Nice! That is exactly the same as my idea.
