### ISSUE TITLE
package trivy for nix/nixOS in nixpkgs

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/trivy#685]
package trivy for nix/nixOS in nixpkgs

issue created as per [aquasecurity/Hacktoberfest](https://github.com/aquasecurity/Hacktoberfest) requirements

> Is this integration generally valuable to the project and should be discussed in the project's repository? If so, please open the issue in the project's repository instead.

Resolved by https://github.com/NixOS/nixpkgs/pull/99407

---

Trivy is now in `nixpkgs` on `master`, I'm happy to close the issue now or if you'd prefer we can close this once it hits `unstable` (a more commonly used release channel) or a stable release

**Comment by knqyf263** [comment]
Thanks a lot!
