### ISSUE TITLE
Debian Stretch - Installation fails with: No package matching 'trivy' is available

### ISSUE THREAD

**Issue by darkwizard242** [aquasecurity/trivy#689]
**Description**

Unable to locate trivy package on Debian Stretch (9) when using repository source:

```shell
https://aquasecurity.github.io/trivy-repo/deb stretch main
```

This has started to occur from a day or two.

**What did you expect to happen?**

Able to find the package and install it.

**What happened instead?**

After adding the repository source and updating the repository cache, getting the following:

```shell
No package matching 'trivy' is available
```

**Additional details (base image name, container registry info...):**
Example of a TravisCI build for Ansible role of Trivy: https://travis-ci.com/github/darkwizard242/ansible-role-trivy/jobs/399931251#L699

**Comment by knqyf263** [comment]
Thanks for your report! This is because `stretch` recently reached End-of-Life.
https://wiki.debian.org/DebianReleases

The following command no longer return `stretch`.
```
$ debian-distro-info --supported
```

I updated the deb repository manually and this issue should have been fixed. Could you check it?

**Comment by darkwizard242** [comment]
@knqyf263 - Ah, that makes sense. Btw, was able to install trivy package after your manual update to the repository. Thanks very much !

**Comment by knqyf263** [comment]
We merged the PR to keep EOL versions, so I hope that it will never happen. Thank you for reporting!

**Comment by darkwizard242** [comment]
Much appreciated @knqyf263 👍🏻
