### ISSUE TITLE
Do you have a Plan to develop an API for Trivy?

### ISSUE THREAD

**Issue by prabha1331** [aquasecurity/trivy#690]
If yes, When we can expect API to be available for Trivy?

**Comment by simar7** [comment]
hi @zidhumenon - could you explain a bit more by what you mean by API? Are you wanting to use Trivy as a library or something else?

**Comment by masahiro331** [comment]
@zidhumenon 
This is minimum trivy client library.
https://github.com/masahiro331/trivy-client-py

**Comment by zidhumenon** [comment]
@simar7 @masahiro331 okay Let me explain what was my question, my question is whether trivy has REST API support? So basically users can hit a rest endpoint with image details and get results as a JSON response.!

**Comment by masahiro331** [comment]
@steveprabha 
Trivy does not support REST API. 
Now trivy support rpc request.
