### ISSUE TITLE
feat(sbom): migrate to `CycloneDX v1.6`

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#6902]
##Description
`CycloneDX v1.6` released - https://cyclonedx.org/news/cyclonedx-v1.6-released/
`github.com/CycloneDX/cyclonedx-go v0.9.0` already supports `v1.6`.

`v1.6` doesn't contain broken changes for fields used in Trivy.
So we can upgrade to `v1.6` without any problems.

**Comment by eruvanos** [comment]
@knqyf263 could we reopen this until a downstream fix this issue?

**Comment by knqyf263** [comment]
@DmitriyLewen Can you please take a look?

**Comment by DmitriyLewen** [comment]
Hello @eruvanos
I think that downgrading the CycloneDX version is not very good idea (especially since trivi does not use this field)
I created https://github.com/CycloneDX/cyclonedx-go/pull/204 in `cyclonedx-go`.
I hope they will consider it quickly

**Comment by DmitriyLewen** [comment]
Hello @eruvanos 
CycloneDX finally merged my PR.

I create #8105
