### ISSUE TITLE
feat(misconf): support for Impact for Rego

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#6934]
Currently, Impact is only supported in Go checks.

An example of using a field in Rego:
```rego
# METADATA
# title: Athena databases and workgroup configurations are created unencrypted at rest by default, they should be encrypted
...
# custom:
#   id: AVD-AWS-0006
#   avd_id: AVD-AWS-0006
#   provider: aws
#   service: athena
#   severity: HIGH
#   short_code: enable-at-rest-encryption
#   recommended_action: Enable encryption at rest for Athena databases and workgroup configurations
#   impact: Data can be read if the Athena Database is compromised
#   input:
#     selector:
#       - type: cloud
#         subtypes:
#           - service: athena
#             provider: aws
```

**Comment by itaysk** [comment]
IMO we should merge this into description

**Comment by nikpivkin** [comment]
@itaysk Before or after? 

The [avd](https://avd.aquasec.com/misconfig/aws/accessanalyzer/avd-aws-0175/) website uses the Impact field.

**Comment by itaysk** [comment]
I see, but it doesn't exists in all rules anyway. after looking at some checks and their impact, I'm in favor of simplifying it and putting it under schema. this will also be better for consistency with existing rego checks.
This is how I suggest to map the metadata fields, wdyt?
- Summary -> title
- Explanation -> description
- Impact -> description
- Resolution -> recommended_action
- Links -> related_resources

**Comment by nikpivkin** [comment]
@itaysk I got it. I chose the same field mapping scheme, except for the Impact field.
