### ISSUE TITLE
bug(secret): set limit for line length

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#6999]
## Description
We show line with secret (also line before and after it) in report.
But there are cases when this line is very long (see #6980).
In this case we will show very large output.

So we need to set maximum line length for secrets or set limit on output shown.

### Discussed in https://github.com/aquasecurity/trivy/discussions/6980

**Comment by knqyf263** [comment]
I assigned this task to @afdesk. It would be appreciated if @DmitriyLewen assists him.
