### ISSUE TITLE
Warning output in client, for unsupported images (like scratch)

### ISSUE THREAD

**Issue by BobVanB** [aquasecurity/trivy#703]
**Our setup:**
* trivy server
* trivy client

**When we try an image that is not supported:**
trivy client wil report the following:
```
trivy client --debug -f json --remote "${TRIVY_URL}" "busybox"
DEBUG   Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
DEBUG   cache dir:  /home/scanner/.cache/trivy
DEBUG   Vulnerability type:  [os library]
DEBUG   Artifact ID: sha256:id
DEBUG   Blob IDs: []
null
```
And the server gives a warning:
```
WARN	OS is not detected and vulnerabilities in OS packages are not detected.
```
**My request is:**
1. show the warning in the client
2. or make this an unsupported error
3. return valid json when running with `-f json`
4. return json with the error in output
    `{ "status": "failed", "reason", "unsupported" }
5. matching errorcode

with kind regards,

**Comment by jeff-cook** [comment]
This would be a good answer to #647.

**Comment by BobVanB** [comment]
I dont mind the solution, if i can parse it from the client side.

**Comment by JanMkl** [comment]
I assume there is no solution yet for this? I would also like to have a way to identify that the OS was not supported and be able to parse it on a client side script.

**Comment by BobVanB** [comment]
@simar7 any progress with this?

**Comment by simar7** [comment]
I'm not actively working on this issue at the moment. It's up for grabs.
