### ISSUE TITLE
There are no results when I scan my git repo (no lock files)

### ISSUE THREAD

**Issue by pascalandy** [aquasecurity/trivy#710]
**Description**

I use Trivy in my CI. The Dockerfile scan works as expected. 

I saw I can **scan a git repo** in your README. So I added the steps:

```
  export VERSION_TRIVY=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION_TRIVY}/trivy_${VERSION_TRIVY}_Linux-64bit.tar.gz
  tar zxvf trivy_${VERSION_TRIVY}_Linux-64bit.tar.gz
  ./trivy repo https://github.com/firepress-org/ghostfire/
```

The CI run normally, there are no results when I scan my git repo.

**What did you expect to happen?**

Results about my git repo.

**What happened instead?**

https://github.com/firepress-org/ghostfire/runs/1290151071?check_suite_focus=true#step:7:1

**Output of run with `-debug`:**

Not necessary at this point

**Output of `trivy -v`:**

Not necessary at this point

Thanks!

**Comment by knqyf263** [comment]
The `repo` scan looks for lock files and detects vulnerabilities of a library for programming language. The repository doesn't include any lock files.
https://github.com/firepress-org/ghostfire/

**Comment by pascalandy** [comment]
OK, so you are saying everything runs normally right? I think we should see a message confirming this statement :)

**Comment by knqyf263** [comment]
Yes, it seems that everything is fine in your case. Do you mean "no lock files are detected" or something like that?

**Comment by pascalandy** [comment]
Yes.

> Do you mean "no lock files are detected" or something like that?

Or better:

```
Trivy could not scan your Git repo because no lock files were detected.
```

At the moment, the "none feedback" make me unsecure.

**Comment by knqyf263** [comment]
OK. Could you raise a new issue?

**Comment by pascalandy** [comment]
Sure, but why this one is not enough?

**Comment by knqyf263** [comment]
Hmm. So, let's change the PR title.

**Comment by pascalandy** [comment]
Sorry I'm still confuse. This is an issue and there is no PR yet :-p

**Comment by knqyf263** [comment]
sorry, not PR title, but this issue title.

**Comment by pascalandy** [comment]
What ever you want :) Just rename it
