### ISSUE TITLE
PR: ISSUE_TEMPLATE formatting

### ISSUE THREAD

**Issue by pascalandy** [aquasecurity/trivy#711]
On https://github.com/aquasecurity/trivy/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md
In this template, for the sections, I suggest to use **H2** instead of **bold**
Let me know if you would like a PR :)

# TEMPLATE SUGGESTION
```
## Description
This text is used as a placeholder. Words that will follow won't make any sense and this is fine. At the moment, the goal is to build a structure for our site.

## What did you expect to happen?
This text is used as a placeholder. Words that will follow won't make any sense and this is fine. At the moment, the goal is to build a structure for our site.
```
 
## Description
This text is used as a placeholder. Words that will follow won't make any sense and this is fine. At the moment, the goal is to build a structure for our site.

## What did you expect to happen?
This text is used as a placeholder. Words that will follow won't make any sense and this is fine. At the moment, the goal is to build a structure for our site.

# ACTUAL TEMPLATE
```
**Description**
This text is used as a placeholder. Words that will follow won't make any sense and this is fine. At the moment, the goal is to build a structure for our site.

**What did you expect to happen?**
This text is used as a placeholder. Words that will follow won't make any sense and this is fine. At the moment, the goal is to build a structure for our site.
```

**Description**
This text is used as a placeholder. Words that will follow won't make any sense and this is fine. At the moment, the goal is to build a structure for our site.

**What did you expect to happen?**
This text is used as a placeholder. Words that will follow won't make any sense and this is fine. At the moment, the goal is to build a structure for our site.

**Comment by simar7** [comment]
Sounds good @pascalandy - go ahead and open a PR!

**Comment by pascalandy** [comment]
PR: https://github.com/aquasecurity/trivy/pull/714/

**Comment by simar7** [comment]
Thanks!
