### ISSUE TITLE
Add version endpoint to trivy server

### ISSUE THREAD

**Issue by bgoareguer** [aquasecurity/trivy#715]
As an end user, I want to always make sure that I use the Trivy client version that corresponds to the Trivy version deployed on the server.

Trivy has client/server mode and the server provides some endpoints. It would be useful if it could provide /version that returns status code 200 and the same information as when calling `trivy --version --format json` from the command line:
```json
{
  "Version": "0.11.0",
  "VulnerabilityDB": {
    "Version": 1,
    "Type": 1,
    "NextUpdate": "2020-10-22T00:21:42.374714307Z",
    "UpdatedAt": "2020-10-21T12:21:42.374715307Z"
  }
}
```

With the /version endpoint, I would be able to run trivy like this:
```bash
docker run --rm aquasec/trivy:$(curl trivy-server/version | jq --raw-output ".Version") alpine:3.11.5
```

**Comment by gmolkvk** [comment]
This would be really helpfull
