### ISSUE TITLE
feat(python): support PKG-INFO and METADATA

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#716]
Currently, Trivy traverses all paths and looks for all Pipfile.lock or poetry.lock in a container image. However, the image sometimes has only Pipfile.lock and doesn't install python packages listed in the Pipfile.lock. A python package should have PKG-INFO and METADATA depending on `egg` or `wheel`.

https://packaging.python.org/discussions/wheel-vs-egg/

To avoid false positives from Pipfile.lock, we are probably able to take advantage of `*.dist-info/METADATA`  and `*.egg-info/PKG-INFO`file.

How it works:

1. Look for all `*.dist-info` and `*.egg-info` directory
    - Note that `*.egg-info` is sometimes a file.
1. Parse `PKG-INFO` or `METADATA` under those directories
1. Extract a python package name and version
1. Use them for vulnerability detection

How to implement it:
1. Add a new parser [here](https://github.com/aquasecurity/go-dep-parser/tree/master/pkg) like `pkg/egg/parse.go` or `pkg/python/egg/parse.go`
1. Add a new analyzer [here](https://github.com/aquasecurity/fanal/tree/master/analyzer/library) like `analyzer/library/egg/egg.go`
1. Add a new detector [here](https://github.com/aquasecurity/trivy/tree/827cea3245081923df9b0e06e5e4f33fbe7302f3/pkg/detector/library)

I'm sure the first two tasks are not difficult and good for the first contributor as well. There are a few things to consider when implementing it in Trivy.

**Comment by dai-dao** [comment]
Hello , i would like to take on this feature

**Comment by dai-dao** [comment]
hello, so i've spent some time on this, and figured out the following:

1. Pipfile.lock doesn't include all sub-dependencies packages, only some of it. So if you want to parse METADA and PKG_INFO and get a list of all the sub-dependencies, the final list will be much bigger than the list in Pipfile.lock
2. A simpler solution would probably be to parse Pipfile.lock and get the list of dependencies , then verify it by parsing site-packages folder for those packages only

Let me know what you think. Cheers

**Comment by knqyf263** [comment]
This issue aims to scan python packages without Pipfile.lock. Some packages are not listed in Pipfile.lock and it might be false negative. It would be great if you get a bigger list than Pipfile.lock.

**Comment by westonsteimel** [comment]
Clair appears to take a similar approach here if that is useful to anyone who may take on implementing this: https://github.com/quay/claircore/blob/master/python/packagescanner.go
