### ISSUE TITLE
chore(docs): Update docs regarding trivy client/server for misconfiguration scanning 

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#7177]
TODO:
- Removing AWS from the table
- Changing `Config` to unsupported in the table
- Adding a new table for supported scanners

Misconfiguration scanning is performed on the client side. Otherwise, a client needs to send all the IaC files, which may include sensitive information, to the server.
Another benefit of the client/server mode is caching. In image scanning, the server stores the analysis result in the cache per layer, and the client can skip analyzing layers in subsequent scans. This is very useful for vulnerability scanning but not for misconfiguration scanning. In misconfiguration scanning, we need to cache the IaC file contents. In addition, filesystem scanning doesn't fit for cache.

For the above reasons, misconfiguration scanning (and secret scanning for the same reasons) doesn't support the client/server mode.

@simar7 @nikpivkin I think we should update [the document](https://aquasecurity.github.io/trivy/v0.53/docs/references/modes/client-server/).
- Removing AWS from the table
- Changing `Config` to unsupported in the table
- Adding a new table for supported scanners

_Originally posted by @knqyf263 in https://github.com/aquasecurity/trivy/discussions/7172#discussioncomment-10069547_

**Comment by nikpivkin** [comment]
@knqyf263 I'm confused by the 3rd point. Are there restrictions for certain scanners in client/server mode?

**Comment by knqyf263** [comment]
The misconfiguration and secret scanners do not support client/server mode. More strictly, detection still occurs in client/server mode, but the scanning is done on the client side and therefore works in the same way as in standalone mode. 

It may be clearer to mention which side the scan is performed on, as ‘not supported’ may sound like it doesn't work. The misconfiguration scans are performed on the client side, so the checks bundle also needs to be downloaded by the client. And this is not what many users want from client-server mode.

**Comment by nikpivkin** [comment]
Thank you! Is it also worth adding a log that secrets and misconfiguration scanning will be done on the client side in client/server mode?

**Comment by knqyf263** [comment]
Yes, it helps.
