### ISSUE TITLE
docs: auto-generate document for trivy.yaml

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#7229]
Currently, [this page](https://aquasecurity.github.io/trivy/v0.53/docs/references/configuration/config-file/) is maintained manually, but it's very hard for us to keep it up-to-date. It should be automatically done through `mage docs:generate`.

**Comment by knqyf263** [comment]
@DmitriyLewen, I remember talking with you about this idea. Please assist @afdesk.

**Comment by DmitriyLewen** [comment]
We discussed this here - https://github.com/aquasecurity/trivy/pull/6547#discussion_r1577397667

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/pull/7261
