### ISSUE TITLE
Trivy client server data exchange

### ISSUE THREAD

**Issue by mfuxi** [aquasecurity/trivy#730]
I Would like to know when I run trivy on my source code or on one of my docker images what exactly is being sent to the server?

**Comment by simar7** [comment]
Do you mean when Trivy runs in client mode, what information gets sent to the server?

**Comment by mfuxi** [comment]
Yes, when I run the trivy CLI

**Comment by simar7** [comment]
These are the arguments that a scan request has that get sent over https://github.com/aquasecurity/trivy/blob/master/rpc/scanner/service.proto#L12-L17

Hope that helps.

**Comment by mfuxi** [comment]
I just would like to know which portion of my source code is being sent to your server is it only the package.json.lock and package.json files?

**Comment by knqyf263** [comment]
@mfuxi It sends only package names and versions. Trivy doesn't send any files as is.

**Comment by mordf** [comment]
thanks, this answers my question.
i'll close the ticket now

**Comment by mfuxi** [comment]
Great, I'm closing the issue
