### ISSUE TITLE
Windows container

### ISSUE THREAD

**Issue by jcamu** [aquasecurity/trivy#738]
Hello,

I can't find if we can use trivy to scan windows container.
Is it possible?

Regards

**Comment by simar7** [comment]
If you're looking for scanning windows based images then today Trivy cannot do that.

**Comment by jcamu** [comment]
OK. is it planned?

**Comment by simar7** [comment]
At the moment we don't have any plans @jcamu - but we'll keep this issue in order to prioritize it accordingly. 

As always, if it's something you'd like to help us with by contributing, we'd be happy to assist!

**Comment by ishowta** [comment]
@jcamu  Why did you close it? I checked the documentation and could not find any mention of scan windows containers.

**Comment by jcamu** [comment]
Don't remind. As the issue was going to be closed without activity. Maybe i close it in advance but yes no news on my side for windows container scan

**Comment by ishowta** [comment]
Sorry, I did not know that the `actions/stale` BOT automatically closes Issues.
