### ISSUE TITLE
Trivy fails to parse JUnit template

### ISSUE THREAD

**Issue by phr0zenx** [aquasecurity/trivy#744]
## Description

Updated junit.tpl , fails to parse file when running trivy scanner.

## What did you expect to happen?

Successfully run trivy scanner and generate junit report.

## What happened instead?

Encountered error: 
unable to write results: failed to initialize template writer: error parsing template: template: output template:464: function "className" not defined

## Output of run with `-debug`:

n/a

## Output of `trivy -v`:

```
Version: 0.12.0
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2020-10-30 00:26:25.414667324 +0000 UTC
  NextUpdate: 2020-10-30 12:26:25.414667024 +0000 UTC
```

## Additional details (base image name, container registry info...):

Continuing from https://github.com/aquasecurity/trivy/issues/732

Unable to reopen case.

**Comment by knqyf263** [comment]
It works in my environment. Which image did you scan? Could you tell me the command you ran? And please share the `junit.tpl` you are using.

**Comment by phr0zenx** [comment]
https://github.com/aquasecurity/trivy/blob/master/contrib/junit.tpl

As per advice, i pulled and used the link to fetch the latest version.

**Comment by phr0zenx** [comment]
`trivy image --severity HIGH,CRITICAL --format template --template "@/usr/local/bin/junit.tpl" -o junit-trivy-report.xml ''' + DOCKER_REG_LOCAL_URL + '''/''' + DOCKER_NAME + ''':''' + DOCKER_TAG + '''`

**Comment by phr0zenx** [comment]
Docker images are private and varies based on CI/CD pipeline.

**Comment by phr0zenx** [comment]
@knqyf263

**Comment by knqyf263** [comment]
Could you remove the sensitive information and share your Dockerfile?

**Comment by phr0zenx** [comment]
```
# pull official base image
FROM node:13.12.0-alpine as build
# set working directory (This will be created automatically when you specifiy your WORKDIR)
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install serve -g
# copy the files and folder for the build
COPY . ./
RUN npm run build-js
# add app
COPY . ./
# start app
CMD ["serve", "-s", "build", "-l", "80"]

```

**Comment by knqyf263** [comment]
I built the Dockerfile without package.json/package-lock.json, but it worked well. Could you share the package.json/package-lock.json as well?

**Comment by phr0zenx** [comment]
{
  "name": "x",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "-": "0.0.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "antd": "^3.26.6",
    "bootstrap": "^4.3.1",
    "compressorjs": "^1.0.6",
    "event-source-polyfill": "^1.0.12",
    "g": "^2.0.1",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.27",
    "nodemon": "^2.0.3",
    "npm-run-all": "^4.1.5",
    "react": "^16.13.1",
    "react-app-polyfill": "^1.0.6",
    "react-beautiful-dnd": "^13.0.0",
    "react-bootstrap": "^1.0.0-beta.14",
    "react-dom": "^16.13.1",
    "react-here-map": "^3.1.0-0",
    "react-lineto": "^3.1.4",
    "react-localization": "^1.0.15",
    "react-neditor": "^1.0.2",
    "react-resize-detector": "^4.2.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.1",
    "react-semantic-ui-datepickers": "^2.2.0",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.88.1",
    "stylus": "^0.54.7"
  },
  "scripts": {
    "build-css": "stylus -w src/styles/theme/theme.styl -o src/styles/theme/theme.css",
    "start-js": "react-scripts start",
    "build-js": "react-scripts build",
    "start": "npm-run-all -p build-css start-js",
    "build": "npm-run-all -p build-css build-js",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by ivanceki** [comment]
Hi @phr0zenx do you mind sharing the content of the junit.tpl file? I had a same issue few days ago, and it turned out to be a bad formatting/encoding of junit.tpl in my case.

**Comment by phr0zenx** [comment]
As per what @ivanceki suggested, some formatting got screwed up in the transition between windows and linux os.
