### ISSUE TITLE
No tokens came to the e-mail address

### ISSUE THREAD

**Issue by aycavuralandac** [aquasecurity/trivy#754]
I registered for tokens yesterday and today with different emails both on the command line and on the site, but no mail received. Can you help about that?

**Comment by simar7** [comment]
Could you elaborate what you're trying to do @aycavuralandac? Trivy doesn't require any tokens to use.

**Comment by aycavuralandac** [comment]
Sorry, wrong subject. I am going to open the issue in microscanner. Thank you
