### ISSUE TITLE
Is there anyway to skip one scan failure when CI/CD has multiple trivy scan for different docker

### ISSUE THREAD

**Issue by yehching0109** [aquasecurity/trivy#758]
![image](https://user-images.githubusercontent.com/30792655/100563569-a7e54c80-32f9-11eb-9474-58799b13d84a.png)
there's one docker package break down, cause the jobs failed.
But there are other trivy scan didn't start yet,
![image](https://user-images.githubusercontent.com/30792655/100563740-1e824a00-32fa-11eb-95af-7634f7078db7.png)
so the question is "Is there anyway to skip one trivy scan failure to continue the whole scanning jobs?"

**Comment by knqyf263** [comment]
If you remove `--exit-code 1`, the job will not fail.

**Comment by yehching0109** [comment]
@knqyf263 thanks for the reply.
I knew the` --exit-code 1 or 0`, sorry for not clearly explain my question.
Is there another way to skip this failure with `--exit-code 1` in the command in gitlab CI/CD yaml?

**Comment by fad3t** [comment]
Hi, you might be looking for the `allow_failure` keyword.
https://docs.gitlab.com/ee/ci/yaml/#allow_failure

**Comment by yehching0109** [comment]
@fad3t thanks for the reply.
sorry for not explain my question clearly.
I want to see the "ERROR Job failed .... exit code 1",but continue the scan, not break down the script immediately.
Is there any suggestion?

**Comment by knqyf263** [comment]
I don't know of any other way. As @fad3t suggested, `allow_failure` sounds good for your case.

**Comment by yehching0109** [comment]
Thanks for the reply @knqyf263 @fad3t .
I can dynamically choose the exit code 1 or 0 in order to bypass the error or not.
