### ISSUE TITLE
feat(misconf): Improve terraform plan JSON error logging

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#7630]
This would be especially useful when scanning Terraform Plan JSON, since we are converting it to HCL and have no way to track the location of the error. 

We can add, for example, a cause field on logging that contains the source code of the location where the error occurred:
```bash
2024-09-28T09:47:17+06:00	DEBUG	[terraform parser] Parsing	module="root" file_path="main.tf"
2024-09-28T09:47:17+06:00	ERROR	[terraform parser] Error parsing file	module="root" file_path="main.tf" 
cause="\tbucket = <" err="main.tf:2,11-12: Invalid expression; Expected the start of an expression, but found an invalid expression token."
```

_Originally posted by @nikpivkin in https://github.com/aquasecurity/trivy/discussions/7608#discussioncomment-10781373_

**Comment by nitrocode** [comment]
I got the same error when running `trivy config ./plan.json` and it's my first time running trivy after using tfsec for years. Looking forward to this fix. Thank you for creating the issue.

**Comment by aziotix** [comment]
I've faced with a similar error when converting Terraform (Azure infra) output to JSON format:
`ERROR	[terraform parser] Error parsing file	module="root" file_path="main.tf" cause="\thidden-link: /app-insights-resource-id =\"/subscriptions/..."" err="main.tf:404,15-16: Invalid expression; Expected the start of an expression, but found an invalid expression token.`

In my case the file included the lines Trivy could not parse correctly:
```JSON
                        "tags": {
                            "environment": "...",
                            "hidden-link: /app-insights-resource-id": "/subscriptions/...",
                            "managed_by": "...",
                            "owner": "...",
                            "project": "..."
                        }
```

I used this workaround to clean JSON file (just remove the line `"hidden-link: /app-insights-resource-id": "/subscriptions/...",`):
```bash
      jq 'walk(
        if type == "object" then
          with_entries(select(.key | test("[/:]") | not))
        else
          .
        end
      )' tfplan.json > tfplan-cleaned.json
```

Then I was able to run the command with no issues: `trivy config tfplan-cleaned.json`.
