### ISSUE TITLE
Is there any suggestion to get the results using shell script?

### ISSUE THREAD

**Issue by yehching0109** [aquasecurity/trivy#764]
Hi guys,
I am confused if there's any way to get the specific "LIBRARY" or types after the scan finished ?
![image](https://user-images.githubusercontent.com/30792655/100970511-087dbf00-3570-11eb-884b-c25de9207842.png)
for example, i want to bypass "libssl1.1" but use the exit code will also bypass the other 2 LIBRARY. I want to use a shell script to add rules like "if the LIBRARY == libssl1.1 , exit code =0; else exit code = 1"

And how am i supposed to get the result from the table(figure) ?
any suggestion?

Thanks
YEH

**Comment by yehching0109** [comment]
Don't wanna change the trivyignore btw.

**Comment by simar7** [comment]
> Don't wanna change the trivyignore btw.

Why not? You could specify the CVE you are not interested in. Or were you looking to ignore libraries rather than CVE IDs? 

You could also try to script around the JSON output if its slightly easier to consume for your shell script (`--format=json`)

**Comment by knqyf263** [comment]
If you want to ignore specific packages, you can also try OPA policy.
https://github.com/aquasecurity/trivy#filter-the-vulnerabilities-by-open-policy-agent-policy

In this example, some packages are ignored.
https://github.com/aquasecurity/trivy/blob/master/contrib/example_policy/basic.rego#L7
