### ISSUE TITLE
False positive on CentOS up-to-date

### ISSUE THREAD

**Issue by ghost** [aquasecurity/trivy#77]
Hi, I obtain a false positive result  … packages are up-to-date and are fixed versions

<img width="1034" alt="Screen Shot 2019-06-27 at 16 35 46" src="https://user-images.githubusercontent.com/5010785/60304920-77c59d00-9900-11e9-948a-82fd1fa9d11c.png">

**Command used to launch trivy on my image:**

```
trivy --ignore-unfixed colundrum/centos-builder-custom_nginx_rpms:latest
```

**Output of `trivy -v`:**

```
trivy version 0.1.3
```

**Additional details (base image name, container registry info...):**

- GitHub with the Dockerfile : https://github.com/colundrum/centos-builder-custom_nginx_rpms
- My docker image : https://hub.docker.com/r/colundrum/centos-builder-custom_nginx_rpms

Regards

**Comment by knqyf263** [comment]
@colundrum Thank you for the report! It seems to be a bug that an epoch number (before colon, 4 in this case) of `perl-ExtUtils-Embed` can't be extracted.

However, an epoch number of `perl-Pod-Escapes` (this case is 1) can be extracted. I need to examine why there is a difference.

**Comment by krol3** [comment]
The user ghost and the files were deleted. This issue could be closed.

**Comment by knqyf263** [comment]
@krol3 Thanks.
