### ISSUE TITLE
fix(golang): do not trim `v` prefix from versions

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#7711]
## Description
[the go mod analyzer](https://github.com/aquasecurity/trivy/blob/2d80769c34b118851640411fff9dac0b3e353e82/pkg/dependency/parser/golang/mod/parse.go#L103) should not remove the `v` prefix from versions to get aligned with [the go binary analyzer](https://github.com/aquasecurity/trivy/blob/9b31697274c8743d6e5a8f7a1a05daf60cd15910/pkg/dependency/parser/golang/binary/parse.go).

### Discussed in https://github.com/aquasecurity/trivy/discussions/7709

**Comment by Rutam21** [comment]
@knqyf263 I would like to work on this. Please assign this issue to me. Thanks.
