### ISSUE TITLE
webui panel for trivy

### ISSUE THREAD

**Issue by lucmichalski** [aquasecurity/trivy#773]
Hi guys,

Hope you are all well !

Pretty much simple question, is there a way to have webui for trivy ?

Thanks for any inputs or insights on that.

Cheers,
Luc Michalski

**Comment by simar7** [comment]
Hi @lucmichalski - we don't have one today. We do support various output types including HTML. 

Feel free to make a proposal with your thoughts and we can take it from there.

**Comment by 06kellyjac** [comment]
How are you using trivy? There might already be an option

If you're using k8s you can use https://github.com/aquasecurity/starboard and https://github.com/vmware-tanzu/octant with https://github.com/aquasecurity/starboard-octant-plugin for a dashboard like so:

![image](https://user-images.githubusercontent.com/9866621/102765971-4dc62d00-4375-11eb-8849-7e6db02950a9.png)

If you're using harbor as your registry and trivy for the scans it's already integrated:

https://goharbor.io/docs/2.0.0/administration/vulnerability-scanning/
https://www.infoq.com/news/2020/04/trivy-docker-harbor/

![image](https://blog.aquasec.com/hs-fs/hubfs/Blog/12-18%20Harbor%20integrations/Image1_Harbor_trivy_scan.jpg?width=1169&name=Image1_Harbor_trivy_scan.jpg)

![image](https://cdn2.hubspot.net/hubfs/1665891/Blog/12-18%20Harbor%20integrations/trivy_scan_Report.jpg)



If you just want the web UI for local scanning results I guess there could be a flag that could automatically output to HTML then host those files on localhost:xyz to be easier to view? :shrug:

**Comment by ltmleo** [comment]
You can use [dependencytrack](https://dependencytrack.org/) sending cyclone-dx format through the api. 
```
$ trivy image --format cyclonedx -o $FILE_NAME $IMAGE_NAME:$IMAGE_TAG
$ curl -X "POST" "http://$DEPENDENCY_TRACK_URL/api/v1/bom" \
     -H 'Content-Type: multipart/form-data' \
     -H "X-Api-Key: $API_KEY" \
     -F "autoCreate=true" \
     -F "projectName=${IMAGE_NAME}" \
     -F "projectVersion=${IMAGE_TAG}" \
     -F "bom=@$FILE_NAME"

```

Example:
![image](https://user-images.githubusercontent.com/43857006/226451408-7a59f3b3-c561-4737-a480-244cb2dbc618.png)

**Comment by locustbaby** [comment]
I created a project [trivy-ui](https://github.com/locustbaby/trivy-ui) to showcase vulnerability reports from Trivy Operator.

![Image](https://github.com/user-attachments/assets/ef5d98fb-bc18-4e37-a396-48f69331add8)

![Image](https://github.com/user-attachments/assets/2abec8dc-7496-4c84-bdae-46c1b061ac49)
