### ISSUE TITLE
scan from docker-compose stack all images / local html reports

### ISSUE THREAD

**Issue by lucmichalski** [aquasecurity/trivy#774]
Hi @simar7 ,

Hope you are all well !

Is it possible to scan periodically/or after triggering a github action, all images in from a docker-compose file ? and save the reports in a local folder for each of them ?

Thanks for any insights or inputs for that.

Cheers,
X

**Comment by simar7** [comment]
Could you share your docker-compose file here? I'm not sure if I understand what you're looking for. Are you looking to use the trivy GitHub action to run a scan during the CI run? Or something else?

**Comment by lucmichalski** [comment]
@simar7 I found a solution with trivy-actions :-)

Closing this issue
