### ISSUE TITLE
fix(checks): Improve AVD-DS-0005 logic

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#7806]
We can improve the logic of this check a little:

- If <src> is a local tar archive, it is decompressed and extracted to the specified destination
- If <src> is a URL, the contents of the URL are downloaded and placed at the specified destination
- If <src> is a Git repository, the repository is cloned to the specified destination

Discussion: https://github.com/aquasecurity/trivy/discussions/7791

**Comment by nicwortel** [comment]
@simar7 I believe this issue can be closed now, as https://github.com/aquasecurity/trivy-checks/pull/281 has been merged :+1:
