### ISSUE TITLE
Add redis support in the Helm chart

### ISSUE THREAD

**Issue by bgoareguer** [aquasecurity/trivy#781]
Trivy supports using Redis as a cache storage option.

It would be nice if we could benefit from this feature when installing Trivy with the Helm chart.

The chart should let the possibility to use an already existing Redis server or install a new Redis server as a sub-chart.

**Comment by Hokwang** [comment]
@czunker you maybe have an idea.

**Comment by czunker** [comment]
You could add the option with the env variable `TRIVY_CACHE_BACKEND`.
But you would then have to exclude `TRIVY_CACHE_DIR`, the mount and the PVC.
When you don't have a PVC, the StatefulSet isn't needed either. You could then just create a Deployment as [discussed](https://github.com/aquasecurity/trivy/pull/751#discussion_r531807384) the @danielpacak in the initial FR.


Taking a look at the [bitnami redis helm chart](https://bitnami.com/stack/redis/helm), I wouldn't suggest integrating anything of it. This gets to complex. In case someone needs redis as caching backend, it can be deployed however needed and trivy configured to use this instance by specifying the backend.

**Comment by bgoareguer** [comment]
I understood that Redis is only used for the cache, not for the vulnerability database (see NOTE in https://github.com/aquasecurity/trivy/issues/765#issue-756010345). 
So there is still a need to store the vulnerability database, even when using Redis as a cache backend.

**Option1:**
If the vulnerability database is stored in an emptyDir volume, the StatefulSet can be replaced with a Deployment. But the vulnerability database will be re-downloaded from scratch each time a pod restarts. And depending on the cache backend (PVC or Redis) the chart will have to deploy completely different resources.

**Option2:**
If the vulnerability database is stored in a PVC, the pods should start quickly. And in this case the same resources (StatefulSet, PVC, etc.) will be deployed for both cache backends (PVC and Redis).

Does this make sense? What do you think?

**Comment by danielpacak** [comment]
I agree with @czunker that we should not have dependency on Redis Helm chart. IMHO we should just allow specifying Redis backend / connection URL.

**Comment by czunker** [comment]
Thanks @bgoareguer for the clarification. I missed this point.
That makes the change much easier.

We could keep the emptyDir mount as default for caching. In case a redis backend is specified, we could skip the emptyDir caching mount.

**Comment by knqyf263** [comment]
How about the `redis.enabled` option? Redis is deployed only when `redis.enabled` is true.
https://github.com/helm/charts/blob/2f030a8e9db3e451e8030b12d2658371f5708f7d/stable/sentry/requirements.yaml#L6-L9
https://github.com/helm/charts/blob/2f030a8e9db3e451e8030b12d2658371f5708f7d/stable/sentry/values.yaml#L244

**Comment by Hokwang** [comment]
I think most of users can deploy redis easily in kubernetes cluster using helm chart or other way.

We need to add doc or comment in values.yaml how to use `--cache-backend` option when user has redis.

**Comment by czunker** [comment]
I created a PR for further discussion.

I used the bitnami helm chart to set up a simple redis server:
```
helm upgrade --create-namespace --install -n trivy-redis --set podSecurityPolicy.create=true --set serviceAccount.create=true --set rbac.create=true --set slave.persistence.enabled=false --set master.persistence.enabled=false --set usePassword=false trivy-redis bitnami/redis
```

What confused me a bit, is that the cache directory is still used for the database. So, you actually have two caches.
The filesystem for the database and redis for the image layers.

With the above redis I could verify, the image layers are really stored in redis.

I couldn't get Trivy to use redis with just a password:
```
2020-12-24T09:52:59.468+0100	FATAL	error in image scan: failed analysis: analyze error: failed to store layer: sha256:50644c29ef5a27c9a40c393a73ece2479de78325cae7d762ef3cdc19bf42dd0a in cache: unable to store cache on the server: twirp error internal: unable to store layer info in cache: unable to store blob information in Redis cache (sha256:50644c29ef5a27c9a40c393a73ece2479de78325cae7d762ef3cdc19bf42dd0a): dial tcp: address :ooV2GvXbUy@trivy-redis-master.trivy-redis.svc:6379: too many colons in address
```
So, I opted for tests without password. Perhaps it would work, when I added a username to the bitnami helm values.
