### ISSUE TITLE
refactor(misconf): Remove unused options

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#7849]
We have a few options within the misconfiguration scanner that aren't used they are as below:

1. `combined` https://github.com/aquasecurity/trivy/blob/39c80248bcafd296e0bb6712113da3abe70e4ce2/pkg/iac/rego/metadata.go#L225
2. `rego warnings` https://github.com/aquasecurity/trivy/blob/main/pkg/iac/scan/result.go#L198

**Comment by nikpivkin** [comment]
Warnings are used in [trivy-operator](https://github.com/aquasecurity/trivy-operator) tests:
```bash
grep -rn "warn"
./go.mod:360:	gopkg.in/warnings.v0 v0.1.2 // indirect
./go.sum:1799:gopkg.in/warnings.v0 v0.1.2 h1:wFXVbFY8DY5/xOe1ECiWdKCzZlxgshcYVNkBHstARME=
./go.sum:1800:gopkg.in/warnings.v0 v0.1.2/go.mod h1:jksf8JmL6Qr/oQM2OXTHunEvvTAsrWBLb6OOjuVWRNI=
./docs/docs/design/design_compliance_report.md:483:                "status": "warn"
./docs/docs/compliance/compliance.md:3:!!! warning "EXPERIMENTAL"
./docs/getting-started/installation/upgrade.md:8:!!! warning
./docs/tutorials/writing-custom-configuration-audit-policies.md:36:Once we've got our metadata defined, we need to create the logic of the policy, which is done in the `deny` or `warn`
./pkg/policy/policy_test.go:305:			name: "Should eval warn rule with invalid resource as failed check",
./pkg/policy/policy_test.go:342:		warn[res] {
./pkg/policy/policy_test.go:373:			name: "Should eval warn rule with valid resource as successful check",
./pkg/policy/policy_test.go:413:		warn[res] {
./pkg/policy/policy_test.go:555:			name:          "Should eval warn rule with any resource and multiple messages",
./pkg/policy/policy_test.go:623:			name: "Should eval warn role rule with built in policies",
./pkg/policy/policy_test.go:933:	// varMessage is the name of Rego variable used to bind deny or warn
./pkg/policy/policy_test.go:939:// `warn` rules.
./pkg/policy/policy_test.go:947:	// Messages deny or warning messages
```

**Comment by nikpivkin** [comment]
I have [found](https://sourcegraph.com/search?q=context:global+path:.*%5C.rego+combine%22:&patternType=regexp&sm=0) use of `Combined` outside of Trivy, but only in one repo:

- https://github.com/ryanmrestivo/red-team/blob/1e53b7aa77717a22c9bd54facc64155a9a4c49fc/Forensic-Reverse-Engineering-Password-Attacks-%26-Analysis/trivy-container-git-scanner/docs/misconfiguration/custom/combine.md?plain=1#L7
- https://github.com/ryanmrestivo/red-team/blob/1e53b7aa77717a22c9bd54facc64155a9a4c49fc/Forensic-Reverse-Engineering-Password-Attacks-%26-Analysis/trivy-container-git-scanner/examples/misconf/combine/policy/custom.rego#L12

**Comment by simar7** [comment]
> Warnings are used in [trivy-operator](https://github.com/aquasecurity/trivy-operator) tests:
> 
> ```shell
> grep -rn "warn"
> ./go.mod:360:	gopkg.in/warnings.v0 v0.1.2 // indirect
> ./go.sum:1799:gopkg.in/warnings.v0 v0.1.2 h1:wFXVbFY8DY5/xOe1ECiWdKCzZlxgshcYVNkBHstARME=
> ./go.sum:1800:gopkg.in/warnings.v0 v0.1.2/go.mod h1:jksf8JmL6Qr/oQM2OXTHunEvvTAsrWBLb6OOjuVWRNI=
> ./docs/docs/design/design_compliance_report.md:483:                "status": "warn"
> ./docs/docs/compliance/compliance.md:3:!!! warning "EXPERIMENTAL"
> ./docs/getting-started/installation/upgrade.md:8:!!! warning
> ./docs/tutorials/writing-custom-configuration-audit-policies.md:36:Once we've got our metadata defined, we need to create the logic of the policy, which is done in the `deny` or `warn`
> ./pkg/policy/policy_test.go:305:			name: "Should eval warn rule with invalid resource as failed check",
> ./pkg/policy/policy_test.go:342:		warn[res] {
> ./pkg/policy/policy_test.go:373:			name: "Should eval warn rule with valid resource as successful check",
> ./pkg/policy/policy_test.go:413:		warn[res] {
> ./pkg/policy/policy_test.go:555:			name:          "Should eval warn rule with any resource and multiple messages",
> ./pkg/policy/policy_test.go:623:			name: "Should eval warn role rule with built in policies",
> ./pkg/policy/policy_test.go:933:	// varMessage is the name of Rego variable used to bind deny or warn
> ./pkg/policy/policy_test.go:939:// `warn` rules.
> ./pkg/policy/policy_test.go:947:	// Messages deny or warning messages
> ```

Thanks for the heads up. I think we should remove these tests.
