### ISSUE TITLE
bug(sbom): Trivy overwrites `Applications` when multiple sbom files contain aggregated language type

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#7851]
## Description
We already had similar case - when single sbom file contains multiple `Applications` for same aggregated language type (see #5812).
This problem has been fixed.

But we have similar behavior when image contains multiple sbom files for same [aggregated type](https://github.com/aquasecurity/trivy/blob/efdb68d3b9ddf9dfaf45ea5855b31c43a4366bab/pkg/fanal/types/const.go#L90) (e.g. Java, Python, etc)

FilePath for these Applications is empty:
https://github.com/aquasecurity/trivy/blob/88ba46047c93e6046292523ae701de774dfdc4dc/pkg/sbom/io/decode.go#L179-L183

So when we fill `nestedMap` in `ApplyLayers` function - we overwrite Applications:
https://github.com/aquasecurity/trivy/blob/69bf7e00ea5ab483692db830fdded26a31f03183/pkg/fanal/applier/docker.go#L121-L125

### Example:
```
➜ tree
.
├── Dockerfile
├── api
│   └── log4j-api-2.24.1.jar
└── core
    └── log4j-core-2.24.1.jar

3 directories, 3 files
➜ trivy -q rootfs ./api -f spdx-json -o report-api.spdx.json    
➜ trivy -q rootfs ./core -f spdx-json -o report-core.spdx.json

➜ cat Dockerfile 
FROM alpine

COPY ./report-api.spdx.json /api/report-api.spdx.json

COPY ./report-core.spdx.json /core/report-core.spdx.json
                       
➜ docker build -t test:7846 .
[+] Building 0.1s (8/8) FINISHED                           docker:desktop-linux
...

➜  example trivy -q image test:7846 -f json --list-all-pkgs --pkg-types library
{
...
  "Results": [
    {
      "Target": "Java",
      "Class": "lang-pkgs",
      "Type": "jar",
      "Packages": [
        {
          "ID": "org.apache.logging.log4j:log4j-core:2.24.1",
          "Name": "org.apache.logging.log4j:log4j-core",
          "Identifier": {
            "PURL": "pkg:maven/org.apache.logging.log4j/log4j-core@2.24.1",
            "UID": "ea631ef0af9d09d6"
          },
          "Version": "2.24.1",
          "Licenses": [
            "NOASSERTION"
          ],
          "Layer": {
            "DiffID": "sha256:efe02b781f0ce0882531fe6ae24f5e369dcd59a33cefac6d9c184e1937298507"
          },
          "FilePath": "log4j-core-2.24.1.jar"
        }
      ]
    }
  ]
}

```

### Discussed in https://github.com/aquasecurity/trivy/discussions/7846

**Comment by javierfreire** [comment]
Hi, is there any update on this issue? It's currently blocking us from updating Trivy. Thanks for your help!

**Comment by DmitriyLewen** [comment]
Hello @javierfreire 
#8052 should fix this issue.

**Comment by javierfreire** [comment]
Thank you!!
