### ISSUE TITLE
Does trivy need a database to store image scan results?

### ISSUE THREAD

**Issue by duyanghao** [aquasecurity/trivy#786]
There are three questions about trivy I want to ask:

Q1: Does trivy need a database to store image scan results?
As we know, clair stores the image scan results and CVE metadatas on postgres database. I am curious about how trivy handles the scan results and CVE metadatas, does it also needs a database like postgres?

Q2: How to achieve the high-availability of trivy in kubernetes environments?
It seems that trivy is deployed by Kubernetes statefulset, so how to achieve its high-availability?

Q3: How to run trivy in an offline environment?
In our production offline environment, trivy has no access to outside network, so how to run trivy normally in this situation?

**Comment by simar7** [comment]
Hi @duyanghao - I'll take a stab at it.

> There are three questions about trivy I want to ask:
> 
> Q1: Does trivy need a database to store image scan results?
> As we know, clair stores the image scan results and CVE metadatas on postgres database. I am curious about how trivy handles the scan results and CVE metadatas, does it also needs a database like postgres?
> 

Trivy doesn't store its scan results. It has a vulnerability DB it downloads to have vulnerability definitions. It's available here https://github.com/aquasecurity/trivy-db/releases

> Q3: How to run trivy in an offline environment?
> In our production offline environment, trivy has no access to outside network, so how to run trivy normally in this situation?

You could run Trivy with a pre downloaded DB. We call it the offline DB and it's available here: https://github.com/aquasecurity/trivy-db/releases/download/v1-2021010412/trivy-offline.db.tgz
