### ISSUE TITLE
imagePullSecrets needed in helm chart

### ISSUE THREAD

**Issue by Hokwang** [aquasecurity/trivy#787]
Hi,

I forgot one thing in helm chart.

If you use docker hub, as you know, docker hub has rate limit,
so we need to set `imagePullSecrets`.

and here's one more question.
can I use sub path in ingress like,
`my.company.com/trivy` instead of `trivy.my.company.com`?

Thanks,

**Comment by czunker** [comment]
@Hokwang The current Ingress template does not allow what you asked for because the path is hardcoded. You could use your own Ingress object. Otherwise, this might be a separate feature request.

**Comment by Hokwang** [comment]
@czunker yeah, in this issue, I referred two separate issue.
If you want to split, I will.

I manually edited helm chart for ingress path, but it does not work.

**Comment by czunker** [comment]
@Hokwang Yes, please split the issue and add your Ingress definition to the new issue.
