### ISSUE TITLE
change ENTRYPOINT to CMD in your Dockerfile

### ISSUE THREAD

**Issue by Hokwang** [aquasecurity/trivy#788]
Hi,

user sometimes need to `docker run -it trivy sh` for `ls`, `df`, whatever not `trivy`.

`ENTRYPOINT` make difficult to do this.

**Comment by czunker** [comment]
You can just run `docker run --entrypoint=sh -ti aquasec/trivy` to get a shell.

Does this solve your problem?

**Comment by knqyf263** [comment]
Thanks for your help, @czunker. As @czunker said, `ENTRYPOINT` can be overwritten.
