### ISSUE TITLE
Possible to scan local images without docker.sock?

### ISSUE THREAD

**Issue by diggnsaegg** [aquasecurity/trivy#791]
Hey,
I am running Fedora 33 with Podman and I tried to scan an updated centos image.

As I do not want to push it to docker hub I would like to know if it is possible to scan images on my machine?

FAQ says:

> 
If you would like to scan the image on your host machine, you need to mount docker.sock.

$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
    -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy python:3.4-alpine

Because I am not running docker, there is no docker.sock.

Error says following:

`podman run --rm -v $HOME/.local/share/containers/storage/overlay-images:/root/.cache/:Z aquasec/trivy localhost/centos7patched
2021-01-04T20:51:04.137Z	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2021-01-04T20:51:06.481Z	FATAL	unable to initialize a scanner: unable to initialize a docker scanner: 2 errors occurred:
	* unable to inspect the image (index.docker.io/localhost/centos7patched:latest): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* GET https://index.docker.io/v2/localhost/centos7patched/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:localhost/centos7patched Type:repository]]
`

Any workaround?

best

**Comment by simar7** [comment]
Good question. You could use tar mode for this purpose. Here's an example:

```
$ trivy image --input vuln-image.tar
```

Where the `--input` is a path to the vulnerable image saved as a tarball. You can save an image as a tarball by running `docker save` command.

Hope it helps.

**Comment by diggnsaegg** [comment]
Thanks for the input, this works as expected, even with podman.

`podman save localhost/centos7patched -o centos7patched.tar`

most docker commands works the same in podman.


`podman run --rm -v $HOME/centos7patched.tar:/root/centos7patched.tar:Z aquasec/trivy --input /root/centos7patched.tar`


Good workaround, hope one day trivy supports podman :)

**Comment by tisc0** [comment]
+1 trivy supporting podman

**Comment by knqyf263** [comment]
Thank you all. I raised a new issue for Podman. Let me close this issue.
