### ISSUE TITLE
bug(cli): Don't error out on empty trivy config yaml file

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#7934]
We should handle empty trivy config yaml files more gracefully. 
```
$ touch invalid-file.yaml
$ ./trivy config --ignorefile ./invalid-file.yaml  /tmp
2024-11-01T16:15:15-06:00       INFO    [misconfig] Misconfiguration scanning is enabled
2024-11-01T16:15:15-06:00       INFO    Detected config files   num=0
2024-11-01T16:15:15-06:00       FATAL   Fatal error     filter error: filtering error: ./invalid-file.yaml error: ./invalid-file.yaml parse error: yaml decode error: EOF
```

_Originally posted by @EdKingscote in https://github.com/aquasecurity/trivy/discussions/7856#discussioncomment-11275794_

**Comment by itaysk** [comment]
small nit but this should be either a bug or a feature

**Comment by simar7** [comment]
> small nit but this should be either a bug or a feature

You're right. Since empty YAML files are technically valid YAML, this is a bug fix. I've updated the title.

**Comment by knqyf263** [comment]
If an empty file is a valid YAML, IMO, the YAML library should not return an error. Then, I found this issue.
https://github.com/go-yaml/yaml/issues/805

I still feel like `Decode` should work in the same way as `Unmarshal`, but we may want to change it to `Unmarshal` here to work it around.
https://github.com/aquasecurity/trivy/blob/46f11399c2b8305e98b5a68989ed03e6492fc469/pkg/result/ignore.go#L231

**Comment by simar7** [comment]
> If an empty file is a valid YAML, IMO, the YAML library should not return an error. Then, I found this issue. [go-yaml/yaml#805](https://github.com/go-yaml/yaml/issues/805)
> 
> I still feel like `Decode` should work in the same way as `Unmarshal`, but if that is the decision in the library, we may want to change it to `Unmarshal` here to work it around.
> 
> https://github.com/aquasecurity/trivy/blob/46f11399c2b8305e98b5a68989ed03e6492fc469/pkg/result/ignore.go#L231

Yes, I also observed that but I thought I was doing something wrong as I didn't find the issue you linked.

But I agree, in theory the two methods should behave the same. I've updated the PR for now to use `Unmarshal`.
