### ISSUE TITLE
Mitigate rate limit issues by utilizing `mirror.gcr.io` as default DB repository

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#7938]
## Description
The Trivy team has been exploring solutions to address the rate limit issues encountered during database updates and has provided [some workarounds](https://github.com/aquasecurity/trivy/discussions/7699). It has come to our attention that [mirror.gcr.io](https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images) functions as a mirror for Docker Hub without imposing rate limits. By configuring `mirror.gcr.io` as the default repository for the Trivy databases, we can potentially resolve the current rate limit challenges. Additionally, incorporating GHCR as a secondary repository could provide further redundancy and reliability.

For reference, please see [the related discussion](https://github.com/aquasecurity/trivy/discussions/7538#discussioncomment-11258881)

**Comment by DmitriyLewen** [comment]
Added in #7679
