### ISSUE TITLE
helm chart's github token problem

### ISSUE THREAD

**Issue by Hokwang** [aquasecurity/trivy#795]
Hi,

I think `TRIVY_GITHUB_TOKEN` is wrong.
`GITHUB_TOKEN` is right, isn't it?

https://github.com/aquasecurity/trivy/blob/e2c483f856c6512e8dcb713394842cbfd42c20f5/helm/trivy/templates/statefulset.yaml#L66

**Comment by czunker** [comment]
Yes: https://github.com/aquasecurity/trivy#github-rate-limiting
