### ISSUE TITLE
Releases missing asset for windows

### ISSUE THREAD

**Issue by JorritSalverda** [aquasecurity/trivy#797]
I'm trying to build a Windows container with Trivy embedded, for which it would be very useful to be able to download a zip file straight from the release assets. Can it be added?

**Comment by simar7** [comment]
hi @JorritSalverda - are you trying to run trivy on Windows (inside an image that's based on top of Windows)? Currently Trivy doesn't support Windows unfortunately. The support was removed as part of this PR https://github.com/aquasecurity/trivy/pull/278

**Comment by JorritSalverda** [comment]
Ah, I wasn't aware it didn't support Windows containers or running on Windows yet since I did fine some existing issues related to scanning image on Windows. I do see now that issue #738 mentions this. If they would ever be supported in the future creating a release asset for Windows is also desirable of course. Will close this for now.
