### ISSUE TITLE
Why does Trivy scan intermediate layers of an ociv1 image?

### ISSUE THREAD

**Issue by liubogithub** [aquasecurity/trivy#799]
Hi Devs,

From the end user's perspective, only the final view makes sense, but Trivy scans all layers of an image.
Can anyone elaborate on why intermediate layers need to be scanned?

Thanks a lot.

**Comment by knqyf263** [comment]
Could you elaborate on it? Trivy extracts files from each layer, merge them, and scan only the merged one.

**Comment by liubogithub** [comment]
Hi @knqyf263 
Please correct me if I was wrong, Trivy uses fanal to do the analysis job, and fanal seems to inspect each layer in order to get a layerInfo which includes `OS`, `PackageInfos`, `Applications`.
https://github.com/aquasecurity/fanal/blob/3f85e04a8048aa6fbeabecee38af81ed7a9fd449/artifact/image/image.go#L70

I see the layerInfo will be merged later, at least [here](https://github.com/aquasecurity/fanal/blob/3f85e04a8048aa6fbeabecee38af81ed7a9fd449/analyzer/analyzer_test.go#L216)

So why Trivy scans each layer instead of scan the final merged layer (i.e. mount with overlayfs)?

**Comment by knqyf263** [comment]
I see. That's because it saves the layer cache and skips downloading the layer next time. Let's say Trivy scans `alpine:3.12` and `python:3.9-alpine3.12` with some layers on `alpine:3.12`. If Trivy (technically fanal) stores the layer cache of `alpine:3.12`, Trivy doesn't need to download those layers when scanning `python:3.9.1-alpine3.12`.

**Comment by liubogithub** [comment]
@knqyf263 I see, thanks for the inputs.

So I'm thinking about making [nydus](https://github.com/dragonflyoss/image-service) work with Trivy given only the BOM files are scanned, and with nydus, metadata (bootstrap) is stored separately [doc](https://github.com/dragonflyoss/image-service/blob/master/docs/nydus-design.md#1-rafs), so we can do scan the image with metadata only.

But there is one thing missing in nydus, that is, right now it only provides the metadata for the merged view of an image, thus it is not possible to provide a layer info for those intermediate layers.

So I was wondering which way might be more?
"merging layer info cache of each layer" vs "scan the merged layer for layer info".

My guess is that scanning takes much less efforts than downloading layers, if so, then avoid downloading layers will make sense.

**Comment by knqyf263** [comment]
If `nydus` has the merged layer, you can pass it to trivy with a digest like a virtual layer. Let's say an image consists of layer A,B,C and nydus has the merged layer D (=A+B+C), trivy can take only layer D.

**Comment by liubogithub** [comment]
That is great, nydus's metadata layer is a layer packed as tar.gz format with a digest, and it represents the merged layer's view, so with nydus daemon's help (providing on-demand fetch), trivy can take that for scanning.

**Comment by knqyf263** [comment]
Please feel free to reopen this issue if you have any other questions.
