### ISSUE TITLE
"Use your github token" output is confusing to the user

### ISSUE THREAD

**Issue by paulmossman** [aquasecurity/trivy#813]
## Description

When I run with a GITHUB_TOKEN environment variable defined Trivy includes a line in the output: "Use your github token".  This is confusing, because it sounds like an instruction to use a Github Token, implying that one has not been detected.

## What did you expect to happen?

Trivy should output "Using your github token" when a GITHUB_TOKEN environment variable is detected and being used.
## What happened instead?

Trivy output "Use your github token".

## Output of run with `-debug`:

$ GITHUB_TOKEN=<<<hidden>>> ~/go/bin/trivy --debug alpine:3.112021-01-20T19:50:13.077-0500	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL2021-01-20T19:50:13.126-0500	DEBUG	cache dir:  /Users/paulmossman/Library/Caches/trivy2021-01-20T19:50:13.126-0500	INFO	Use your github token2021-01-20T19:50:13.127-0500	DEBUG	DB update was skipped because DB was downloaded during the last hour2021-01-20T19:50:13.127-0500	DEBUG	DB Schema: 1, Type: 1, UpdatedAt: 2021-01-20 12:41:55.820704048 +0000 UTC, NextUpdate: 2021-01-21 00:41:55.820703648 +0000 UTC, DownloadedAt: 2021-01-21 00:48:13.297301 +0000 UTC2021-01-20T19:50:16.428-0500	DEBUG	Vulnerability type:  [os library]2021-01-20T19:50:16.809-0500	DEBUG	Artifact ID: sha256:5c534be56eca62e756ef2ef51523feda0f19cd7c15bb0c015e3d6e3ae090bf6e2021-01-20T19:50:16.809-0500	DEBUG	Blob IDs: [sha256:0fcbbeeeb0d7fc5c06362d7a6717b999e605574c7210eff4f7418f6e9be9fbfe]2021-01-20T19:50:16.809-0500	INFO	Detecting Alpine vulnerabilities...2021-01-20T19:50:16.809-0500	DEBUG	alpine: os version: 3.112021-01-20T19:50:16.809-0500	DEBUG	alpine: the number of packages: 142021-01-20T19:50:16.810-0500	INFO	Trivy skips scanning programming language libraries because no supported file was detected
alpine:3.11 (alpine 3.11.7)===========================Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

## Output of `trivy -v`:

$ ~/go/bin/trivy -vVersion: devVulnerability DB:  Type: Light  Version: 1  UpdatedAt: 2021-01-20 12:41:55.820704048 +0000 UTC  NextUpdate: 2021-01-21 00:41:55.820703648 +0000 UTC  DownloadedAt: 2021-01-21 00:48:13.297301 +0000 UTC

## Additional details (base image name, container registry info...):

None.

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/pull/814 fixed it.
