### ISSUE TITLE
support scanning on container image in customer private repository

### ISSUE THREAD

**Issue by shaolinyang2009** [aquasecurity/trivy#821]
support scanning on container image in popular public repository is good feature! Would you please extend this to support private repository as most users like us are using private repository? 

E.g we are using Nexus server as our private repository, server link llke: 

https://otaaplvlp05.,mycomparny.com:grpc_server.latest

thanks! 
shaolin

**Comment by danielefranceschi** [comment]
We had the same requirement, solved using OCI layout scanning:
```bash
skopeo copy --src-creds $NEXUS_USER:$NEXUS_PASSWORD docker://$IMGWITHREPO oci://tmp/xxx
trivy image --input /tmp/xxx
```

**Comment by nemethloci** [comment]
The below seems to work as well. Of course it assumes docker being installed and the user having the rights to pull into the local registry:
```
docker image pull <private_registry>/<repo>:<image_tag>
trivy image <private_registry>/<repo>:<image_tag>
docker rmi <private_registry>/<repo>:<image_tag>
```

**Comment by jleonard-r7** [comment]
Any plans to support this directly from trivy?

**Comment by knqyf263** [comment]
Trivy should work with private registries. You need `docker login <private_registry>` or `TRIVY_USERNAME` and `TRIVY_PASSWORD`.
https://aquasecurity.github.io/trivy/v0.36/docs/advanced/private-registries/
https://aquasecurity.github.io/trivy/v0.36/docs/advanced/private-registries/self/

**Comment by knqyf263** [comment]
The latest doc
https://aquasecurity.github.io/trivy/v0.41/docs/advanced/private-registries/
