### ISSUE TITLE
Installation with install.sh fails on armv7 platform

### ISSUE THREAD

**Issue by joerijansen** [aquasecurity/trivy#822]
## Description

Installation using the https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh script does not work correctly on arm7 platforms (Raspberry PI). The installation stops after two lines of info.

## What did you expect to happen?
Correct installation

## What happened instead?
curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
aquasecurity/trivy info checking GitHub for latest tag
aquasecurity/trivy info found version: 0.15.0 for v0.15.0/Linux/armv7

## Additional details (base image name, container registry info...):
This can be fixed by extending the adjust_arch() method in the script, by adding:
armv7) ARCH=ARM ;;

**Comment by krol3** [comment]
@joerijansen  are you still with problems on arm7 platforms?

**Comment by joerijansen** [comment]
Hi @krol3 I recently switched to an ARM64 OS version, so I worked around it.
