### ISSUE TITLE
Add CSV template with support for replacing characters in output

### ISSUE THREAD

**Issue by sishbi** [aquasecurity/trivy#826]
I am using Trivy in my company and I have written a csv.tpl as my manager would like the output format.
While the basic template is fine the output contains additional columns due to the description including commas.
I have therefore added a new 'replaceAll' template function that wraps the 'strings.ReplaceAll' function to make it accessible to the Go template.

I have committed this to my fork and will make a PR so that it can be included in the next release.

**Comment by knqyf263** [comment]
`replaceAll` is provided by sprig.
http://masterminds.github.io/sprig/

**Comment by sishbi** [comment]
Please reopen, as I have added the 'csv.tpl' template which uses the sprig 'replace' function in #919

**Comment by sharmautkarsh31** [comment]
You can use the following template for getting a csv:
`Image,PackageName,VulnerabilityID,Severity,Score,InstalledVersion,FixedVersion,Title
{{ range . }}
{{- $target := .Target -}}
{{- if (eq (len .Vulnerabilities) 0) }}
    {{- $target }},,,,,,,
{{- else }}
{{- range .Vulnerabilities }}
    {{- $description := .Title }}
    {{- if not $description }}
        {{- $description = .Description -}}
        {{- if gt (len $description ) 150 -}}
            {{- $description = (slice $description 0 150) | printf "%v..." -}}
        {{- end}}
    {{- end }}
    "{{- $target }}","{{- .PkgName }}","{{- .VulnerabilityID }}","{{- .Vulnerability.Severity }}",{{- $score := (index .CVSS "nvd").V3Score -}}{{- if not $score -}}{{- $score = (index .CVSS "redhat").V3Score -}}{{- end -}}"{{- $score }}","{{- .InstalledVersion }}","{{- .FixedVersion }}","{{- $description }}"{{ end }}{{ end -}}
{{- end }}
   `

**Comment by macedogm** [comment]
@sishbi and @knqyf263 I would like to contribute a CSV template. I saw that PR https://github.com/aquasecurity/trivy/pull/919 got stalled. Should we re-open this issue or is it better to open a new one instead?

**Comment by sishbi** [comment]
I suggest opening a new issue as I am no longer working on this

**Comment by a-devops-guy** [comment]
`"Target","Vulnerability Class","Target Type","Vulnerability ID","Severity","PackageName","Installed Version","Fixed Version","Title","Description","Reference","Vulnerability Score"
{{- range . }}
{{- $target := .Target | quote }}
{{- $class := .Class | quote }}
{{- $vulnerabilityType := .Type }}
{{- range .Vulnerabilities }}
{{- $vulnerabilityID := .VulnerabilityID | quote }}
{{- $pkgName := .PkgName | quote }}
{{- $title := .Title | quote }}
{{- $description := .Description | quote }}
{{- $installedVersion := .InstalledVersion | quote }}
{{- $fixedVersion := .FixedVersion | quote }}
{{- $severity := .Severity | quote }}
{{- $reference := .PrimaryURL | quote }}
{{- if $fixedVersion }}
{{ printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s" $target $class $vulnerabilityType $vulnerabilityID $severity $pkgName $installedVersion $fixedVersion $title $description $reference  }}
{{- else }}
{{- $nullFixedVersion := "" | quote }}
{{ printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s" $target $class $vulnerabilityType $vulnerabilityID $severity $pkgName $installedVersion $nullFixedVersion $title $description $reference  }}
{{- end }}
{{- end }}
{{- end }}
`

This is convert json to csv but im unable to extract V3Score alone and add to the column for each CVE

**Comment by AbhigyanKumarTrellix** [comment]
Hi, was a CSV template ever actually added ?
I needed a basic one just , name , issue id , severity  and maybe the source link etc. 
I am not good with Go

**Comment by rams3sh** [comment]
I made the below template for my tsv format. I prefer tsv since handling quotes and `,` is a headache in csv. This however can be opened by any of the spreadsheet software and has same view as csv. Template is below :- 

```
"Image" "Title" "Description"   "Severity"  "Vulnerability ID"  "Vendor ID" "Package Class" "Package Type"  "Package Name"  "Installed Version" "Fixed Version" "Severity Source"   "Primary Url"   "Reference"
{{- range $ri, $r := . }}
{{- $imageName := $r.Target }}
{{- $pkgClass := $r.Class }}
{{- $pkgType := $r.Type }}
{{- range $vi, $v := .Vulnerabilities }}
{{$imageName}}  {{ $v.Title }}  {{ $v.Description }}    {{$v.Severity}} {{ $v.VulnerabilityID }}    {{$v.VendorIDs | join ", "}}    {{ $pkgClass }} {{$pkgType}}    {{ $v.PkgName }}    {{$v.InstalledVersion }}    {{ $v.FixedVersion }}   {{$v.SeveritySource}}   {{$v.PrimaryURL}}   "{{$v.References | join "\r"}}"
{{- end}}
{{- end }}
```
Sixth line in the above code block is `tab` separated. In case , while copying, formatting gets lost, re-edit the template and manually put the `tab` between each of the fields. 

Save the above template as say `tsv.tpl`. 

Use trivy cli as below :- 

```
trivy image --format template --template '@tsv.tpl'  centos > output.tsv
```


The template and the provided cli works well with the following trivy version :- 
```
Version: 0.36.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-04-03 12:08:20.93338503 +0000 UTC
  NextUpdate: 2023-04-03 18:08:20.933384329 +0000 UTC
  DownloadedAt: 2023-04-03 13:28:04.607696009 +0000 UTC

```

Thought of putting this up here in case any one finds it helpful.
