### ISSUE TITLE
Way to get info CVE info from the trivy database without performing scan.

### ISSUE THREAD

**Issue by CRogers** [aquasecurity/trivy#836]
We have built an image scanning solution based on Trivy, and one of the features I want to add is when a user views an old saved Trivy report, I want to show if a package with a CVE has a fixed version now available according the the current trivy db, without rescanning the image. This means when a user views a scan from days/weeks/months ago they can see if there is now an upgrade available to remediate, even if there was no fix version available at scan time. To do this I need to query Trivy with something like "what is the info you have about this CVE from your db". Does this currently exist?

A bonus feature would be to get the time the CVE was reported, in order to be able to do workflows like "HIGH vulns have a window of 1 month after being reported to fix".

PS: Thanks for making Trivy, it's been super useful

**Comment by knqyf263** [comment]
Trivy doesn't have such a feature at the moment, but we might be going to support [CycloneDX](https://cyclonedx.org/). Trivy generates CycloneDX format as a result and also takes it as input. It might match your requirement.

As for the second feature, `PublishedDate` and `LastModifiedDate` are reported in the result JSON like the following.

```
        "PublishedDate": "2017-10-24T20:29:00Z",
        "LastModifiedDate": "2019-04-03T15:29:00Z"
```

**Comment by DreadPirateShawn** [comment]
We have a different use-case that leads to essentially the same feature request. We're trying to gain insight into how to reduce our CVE frequency, which leads to such questions as "what's the historical CVE velocity for package X?" or "are there any packages that we can avoid based on more frequent CVE velocity?"

The Trivy db should have all the raw data necessary to answer such questions, if only we could access it arbitrarily.

**Comment by seebi** [comment]
Hi @CRogers - how did you solved you problem? Any chance to get this information out of trivy in 2024? :-)

**Comment by seebi** [comment]
ok, here is what I found:

- get the trivy db as documented [here](https://github.com/aquasecurity/trivy-db?tab=readme-ov-file#version-2)
- install [bbolt](https://github.com/etcd-io/bbolt)
- `bbolt get trivy.db vulnerability CVE-YEAR-NO >CVE-YEAR-NO.json`

**Comment by itaysk** [comment]
> Any chance to get this information out of trivy in 2024

In 2024 you can generate an SBOM, which include the package information necessary to make a vulnerability report, and rescan it with `trivy sbom ./mysbom`

querying the DB directly through Trivy is out of scope and will not be implemented

**Comment by seebi** [comment]
@itaysk thanks for the reply. Do you think working with bbolt directly is a good idea or is the internal key structure rather unstable?

**Comment by itaysk** [comment]
it's fine if that works for you. we make any guarantees about internal structure, but it's unlikely that we will break it
