### ISSUE TITLE
Trivy Helm Chart-  is it hosted somewhere?

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [aquasecurity/trivy#839]
Trivy Helm Chart-  is it hosted somewhere?

**Comment by knqyf263** [comment]
We're working on it now. CC: @krol3 @danielpacak

**Comment by krol3** [comment]
Yeah we will create soon. You can assign me the issue

**Comment by Hokwang** [comment]
@krol3 any updates?

**Comment by krol3** [comment]
the trivy chart will be hosted here: https://github.com/aquasecurity/helm-charts/
I will work in this weekend for create the chart @Hokwang

**Comment by krol3** [comment]
@Hokwang @abhinavkhanna-sf  could you review the helm chart?
 
helm repo add aquasecurity https://aquasecurity.github.io/helm-charts/
helm repo update
helm search repo trivy
helm install my-trivy aquasecurity/trivy

**Comment by Hokwang** [comment]
@krol3 I tested it. I can install trivy successfully.

**Comment by Hokwang** [comment]
@krol3 @knqyf263 I want to tell one more thing. when you release new version, you need to take care this helm chart. actually now, helm chart's app version is v0.15.0.

**Comment by krol3** [comment]
@Hokwang the app version could be updated using set values, -set imageTag=<imagetag>. We would publish a new chart version when the helm chart structure change. We could improve this app version in the next release.

**Comment by kfox1111** [comment]
add to artifacthub.io too please?

**Comment by krol3** [comment]
@knqyf263 @kfox1111  I created this issue related improvements about helm chart release: https://github.com/aquasecurity/trivy/issues/900

**Comment by knqyf263** [comment]
As for Artifact Hub, please track #900. Let me close this issue.
