### ISSUE TITLE
SARIF output is invalid if PrimaryURL is empty

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#841]
## Description

If Trivy is set to run a scan on an image that contains a vulnerability for which there's no PrimaryURL set, the corresponding SARIF output will have an empty `helpUri` field. This is invalid as per the SARIF format.

## What did you expect to happen?

The generated SARIF output should be valid even if PrimaryURL is missing/unavailable.

## What happened instead?

Invalid SARIF output was generated and any GitHub Actions (user of this output) was impacted. Sample run https://github.com/aquasecurity/trivy-sarif-demo/runs/1883809480
<img width="893" alt="image" src="https://user-images.githubusercontent.com/1254783/107718029-d84a4f00-6c89-11eb-8978-d6600256564f.png">

## Output of run with `-debug`:

N/A

## Output of `trivy -v`:

```
trivy -v
Version: 0.15.0
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2021-02-11 12:19:14.765739498 +0000 UTC
  NextUpdate: 2021-02-12 00:19:14.765739098 +0000 UTC
  DownloadedAt: 2021-02-12 00:21:31.515093 +0000 UTC
```

## Additional details (base image name, container registry info...):
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/1254783/107718011-cd8fba00-6c89-11eb-8eb6-f3dafd8308c9.png">

**Comment by simar7** [comment]
`helpUri` was introduced here https://github.com/aquasecurity/trivy/pull/801/files FYI

**Comment by ronaudinho** [comment]
removing the `helpUri` field if `PrimaryURL` is missing solves this, but according to the spec, `helpURI` needs to conform to [RFC 3986](https://tools.ietf.org/html/rfc3986). would it be okay to assume that if `PrimaryURL` is not missing, it will be a valid one?

**Comment by simar7** [comment]
> removing the `helpUri` field if `PrimaryURL` is missing solves this, but according to the spec, `helpURI` needs to conform to [RFC 3986](https://tools.ietf.org/html/rfc3986). would it be okay to assume that if `PrimaryURL` is not missing, it will be a valid one?

Thanks for looking into this @ronaudinho – you raise a good point. It is possible today that PrimaryURL might be an empty string as well. See here below https://github.com/aquasecurity/trivy/blob/6ed25c19e69a62d0c9ea45e1a6ed8a0511a14f07/pkg/vulnerability/vulnerability.go#L124-L145

Although I can't think of a case that would get us here returning this. Can you think of any case @knqyf263? Tests are here for your reference https://github.com/aquasecurity/trivy/blob/6ed25c19e69a62d0c9ea45e1a6ed8a0511a14f07/pkg/vulnerability/vulnerability_test.go#L375-L455

So in short with your change we could most likely fix this.

**Comment by ronaudinho** [comment]
thanks for the feedback. looks to me like `PrimaryURL` will either be a valid value or empty, so I guess this change should fix it. I'll PR this shortly then.
