### ISSUE TITLE
Scan jar files in a docker image

### ISSUE THREAD

**Issue by hari819** [aquasecurity/trivy#847]
Hello ,

I am trying to detect vulnerabilities in java jar files after the announcement in https://github.com/aquasecurity/trivy/pull/837
and trivy started supporting java jar,war files.

I am still getting this error about "skipping programming languages" ,
```
**```
~$ trivy image --vuln-type library wurstmeister/kafka
2021-02-18T03:24:15.421-0500    WARN    You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2021-02-18T03:24:16.754-0500    INFO    Trivy skips scanning programming language libraries because no supported file was detected
```**
```

could you please guide me how to scan a docker image with jar files?,

thanks,
Hari

**Comment by knqyf263** [comment]
I'm sorry that the feature is not released yet. Please wait for the next version. If you want to try it, you can build it from the source.

**Comment by hari819** [comment]
> I'm sorry that the feature is not released yet. Please wait for the next version. If you want to try it, you can build it from the source.

thankyou , I will wait for the next version

**Comment by knqyf263** [comment]
Thanks.

**Comment by lepapareil** [comment]
Hi @knqyf263,

Do you know how long before the jar/war scan version will be available plz ?

**Comment by knqyf263** [comment]
It depends on GitLab. I want to support GitLab DB before releasing jar scanning for accuracy.
https://gitlab.com/gitlab-org/gitlab/-/issues/321589

**Comment by lepapareil** [comment]
> It depends on GitLab. We want to support GitLab DB before releasing jar scanning for accuracy.
> https://gitlab.com/gitlab-org/gitlab/-/issues/321589

Ok, thks

**Comment by hari819** [comment]
we can see that the dependent issues in gitlab are kind of closed now , when can we expect the next release of Trivy which contains functionality to scan jar files and support full java stuff?

thanks

**Comment by malanvaneck** [comment]
Believe a lot of people are waiting for this one.

**Comment by prabhushan** [comment]
This is really a must have feature. Which Trivy version can we get this?

**Comment by masahiro331** [comment]
Released jar scan feature!!!
https://github.com/aquasecurity/trivy/discussions/966

This release v0.17.0 has many other glad features.

**Comment by hari819** [comment]
> @hari819
> Released jar scan feature!!!
> #966
> 
> This release v0.17.0 has many other glad features.

Many thanks @masahiro331 , surely going to tryout the new features,

Thanks,
