### ISSUE TITLE
Trivy in kubernetes

### ISSUE THREAD

**Issue by DrissiReda** [aquasecurity/trivy#848]
Is there any simple way to create a cronjob in a kubernetes cluster that would scan all container images currently in use in the kubernetes cluster?

**Comment by knqyf263** [comment]
You can use [Starboard](https://github.com/aquasecurity/starboard) for that purpose. CC: @danielpacak

**Comment by danielpacak** [comment]
Indeed, Starboard v0.9 is designed to discover Kubernetes workloads and scan them for vulnerabilities. It's configurable to use Starboard with Trivy in ClientServer mode https://aquasecurity.github.io/starboard/latest/integrations/vulnerability-scanners/trivy/ which scale better with the number of workloads.

NB Rescanning on regular intervals is not implemented yet, but it's on our roadmap and we'll add that very soon.

**Comment by DrissiReda** [comment]
Thanks for the answer @danielpacak 
My use case: I have an offline kubernetes cluster that can have deployments added/modified from time to time. I want to be able to make a cronjob that runs trivy on the local images present inside my kubernetes cluster. I use containerd so I'm not sure if trivy works with that as easily as with docker. 
Will starboard be what I should use? Does it scan only local images?

**Comment by danielpacak** [comment]
### TL;DR

Starboard doesn't support air gapped environments (yet).

### Why?

Starboard is leveraging Trivy as a vulnerability scanner in addition to discovering Kubernetes workloads. This means that whenever Starboard runs a Trivy scan job it pulls a container image from a remote image registry to a temporary directory and then inspects the image for vulnerabilities. (Notice that Trivy also pulls the vulnerabilities DB / index with GitHub API and caches it in the local file system.)

Obviously this approach has pros and cons, but the main rationale behind it was to "sacrifice" performance for being container runtime (CR) agnostic and stay Kubernetes-native (= don't break abstractions introduced by Kubernetes unless absolutely necessary). This is not something that you're probably looking for @DrissiReda 

On the contrary, we have integrated Starboard with Aqua commercial scanner that does local scan by mounting a hostPath volume to the Docker socket https://github.com/aquasecurity/starboard/blob/main/pkg/aqua/plugin.go#L180 Sadly, this is no longer OSS and requires Docker runtime.

This makes me thinking whether we should consider a hybrid approach, where we run Trivy in a "local mode". This would be a RFE anyway in the Starboard project. It requires design to make sure that Starboard/Trivy is aware of the underlying CR implementation and has privileges to mount CR sockets. /cc @knqyf263 @jerbia

**Comment by DrissiReda** [comment]
Thank you very much for your explanation !
I figured out what it does with docker, but doing the same with containerd isn't enough, I can use crictl from inside a container to access the images on the nodes if I bind /var/run/containerd, but trivy is unable to reach these images cached by containerd...

**Comment by knqyf263** [comment]
Close this issue in favor of https://github.com/aquasecurity/trivy/issues/851
