### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by shorty-at-next** [aquasecurity/trivy#849]
Hi all,

I suggest the following improvement for https://github.com/aquasecurity/trivy#embed-in-dockerfile 
```
[...]
# Run vulnerability scan on build image
FROM build AS vulnscan
COPY --from=aquasec/trivy:latest /usr/local/bin/trivy /usr/local/bin/trivy
RUN trivy filesystem --exit-code 1 --no-progress /
[...]
```
In my opinion it is a much cleaner to use a multi-stage build and also the `curl | sh` part is no longer necessary.

**Comment by knqyf263** [comment]
It sounds nice! We welcome the PR.

**Comment by shorty-at-next** [comment]
Done. See in #853
