### ISSUE TITLE
Please clarify misleading warning

### ISSUE THREAD

**Issue by cburgmer** [aquasecurity/trivy#863]
## Description

When using the latest tag, trivy will spit out a warning:

```
2021-02-24T10:55:22.289Z	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
```

When adding the suggested option, trivy stops working, as `--clear-cache` does not scan the image.

## What did you expect to happen?

For the scan to continue working.

## What happened instead?

We didn't have any container scan for weeks.

## Additional details (base image name, container registry info...):

Two suggestions
1. Either change the behaviour of the --clear-cache option to not drop scanning (preferred)
2. or fix the warning to be clear about this.

**Comment by knqyf263** [comment]
Thank you for filing an issue. I just realized this warning is stale and the latest tag doesn't cause any cache issue now. I'll fix it soon.

**Comment by knqyf263** [comment]
It will not be shown in the next version. Thanks again.

**Comment by sawpresto** [comment]
Hi @knqyf263, thanks for fixing! Do you know when the next version including this fix will be released?
