### ISSUE TITLE
"trivy fs <file path>" shows a warning messages 

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/trivy#867]
## Description

I am running "trivy fs <file path>" to scan a github repository that I've forked to my laptop.

## What did you expect to happen?

I expected the scan to show me all the vulnerabilities I have.
It should show me how many files were scanned, which files matched Trivy sources (e.g. Java, Python, etc.)
and the list of vulnerabilities.

## What happened instead?

I got two messages that I did not expect (see below).

The output did not have any other indication beside these two messages.
I did not know if scan was successful or failed.

## Output of `trivy -v`:

```
trivy fs .
2021-02-25T18:24:20.684+0200	INFO	Need to update DB
2021-02-25T18:24:20.684+0200	INFO	Downloading DB...
20.28 MiB / 20.28 MiB [-----------------------------------------------------------------------------------------------------------------------------------] 100.00% 3.72 MiB p/s 5s
2021-02-25T18:24:29.023+0200	WARN	OS is not detected and vulnerabilities in OS packages are not detected.
2021-02-25T18:24:29.023+0200	INFO	Trivy skips scanning programming language libraries because no supported file was detected

```

## Additional details (base image name, container registry info...):

The "fs" scan needs output that is suitable for filesystem scan:

- If scanning the root filesystem (meaning the "/" path) then I expect a message if OS was not found. Otherwise (not scanning the root filesystem) I do not expect a warning message about missing OS.
- Output should show the path that was scanned (like when you scan an image, you get the image name in the output)
- There should be an indication on number of vulnerabilities found: Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
- No need to show "Trivy skip scanning programming languages". Instead show say how many files where checked and out of them how many were scanned.

**Comment by knqyf263** [comment]
Was fixed a long time ago
