### ISSUE TITLE
Feedback when scanning NuGet packages

### ISSUE THREAD

**Issue by cj930736** [aquasecurity/trivy#875]
Hi,

We are currently using the Nuget scanning functionality which was recently implemented in Trivy. However,
when scanning an image using --vuln-type 'library', there is no feedback from the tool. I would like to see something like
X NuGet packages scanned and Y vulnerabilities found. Is this something which can be added?

It would be good if this worked for trivy fs as well as trivy image

Best
Chris Jackson

**Comment by knqyf263** [comment]
Does your image have a lock file? Now, Trivy supports only `packages.lock.json` for NuGet.
https://github.com/aquasecurity/trivy#application-dependencies

For more details, see the Microsoft blog.
https://devblogs.microsoft.com/nuget/enable-repeatable-package-restores-using-a-lock-file/

**Comment by themar7777** [comment]
G

**Comment by cj930736** [comment]
Yes, it has the packages.lock.json file

**Comment by knqyf263** [comment]
Could you give me the Dockerfile without sensitive information? It doesn't reproduce in my environment.

**Comment by cj930736** [comment]
This is me logging into the container, listing packages.lock.json, then running trivy 
![image](https://user-images.githubusercontent.com/4950749/110456079-112ae780-80c1-11eb-8dc1-e1d9adbaf95f.png)

[Dockerfile.txt](https://github.com/aquasecurity/trivy/files/6107765/Dockerfile.txt)

**Comment by cj930736** [comment]
Update:
I didn't have the latest version installed. I have just updated Trivy, however I am now getting:

![image](https://user-images.githubusercontent.com/4950749/110467224-aaacc600-80ce-11eb-998f-8a4b6fc2f8b0.png)

Does the .json file need to be in a specific place in the container?

**Comment by knqyf263** [comment]
You logged in `bigchage.teltonika-receive:test`, but you scanned `bigchange.teltonika-processing:test`. Is it intended? Are they same image?

**Comment by cj930736** [comment]
Good spot. I lined the two up and am now getting a good response:
app/packages.lock.json
======================
Total: 0 (LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

Apologies. I'll close the issue
