### ISSUE TITLE
Trivy fails on Tekton AppSody and OpenShift S2I build images.

### ISSUE THREAD

**Issue by kitty-catt** [aquasecurity/trivy#883]
**## Description**

Trivy scans work on images that I have build via buildah in Tekton on Openshift. The format that I make Buildah use is OCI.

When I use Openshift S2I or AppSody in a TektonPipeline on Openshift then Trivy cannot analyze the image. 

**## What did you expect to happen?**

Trivy scanned the images that were build using S2I or AppSody and gave a verdict. 

**## What happened instead?**

The scan did not execute to completion,

**## Output of run with `-debug`:**

```
FATAL	error in image scan: failed analysis: analyze error: failed to analyze layer: sha256:58abc5089e711c65bb2c19c94de7e84971711b33a1728dc09c98bb3c0619ba9c : unable to get uncompressed layer sha256:58abc5089e711c65bb2c19c94de7e84971711b33a1728dc09c98bb3c0619ba9c: failed to get the layer (sha256:58abc5089e711c65bb2c19c94de7e84971711b33a1728dc09c98bb3c0619ba9c): unexpected media type: application/vnd.oci.image.layer.v1.tar for layer: sha256:e2da858243a3bd60047d6c5a610d300a933e5b046e091a7c346fa2eca40b335c
```

**## Output of `trivy -v`:**

trivy -v
Version: 0.14.0

**## Additional details (base image name, container registry info...):**

The trivy scan is done via the following container image:

quay.io/ibmgaragecloud/aquasec-trivy:latest

I run the Tekton pipeline in Openshift 4.6.15 in Code Ready Containers.

**Comment by kitty-catt** [comment]
Levelling up to image: aquasec/trivy in the Tekton Task shows the following:

[trivy-va-scan : scan-image] Trivy Security Scan image in registry with severity filter UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
[trivy-va-scan : scan-image] + trivy -v
[trivy-va-scan : scan-image] Version: 0.16.0
[trivy-va-scan : scan-image] + trivy image --exit-code 0 --input /var/oci/image
[trivy-va-scan : scan-image] 2021-03-10T12:50:45.682Z   INFO    Need to update DB
[trivy-va-scan : scan-image] 2021-03-10T12:50:45.682Z   INFO    Downloading DB...
[trivy-va-scan : scan-image]  FATAL   error in image scan: failed analysis: analyze error: failed to analyze layer: sha256:f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8 : unable to get uncompressed layer sha256:f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8: failed to get the layer (sha256:f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8): unexpected media type: application/vnd.oci.image.layer.v1.tar for layer: sha256:86621325a59525c63d656ba11d4c1c396b5163571355849f9e4fcbfffb2b31fd

**Comment by knqyf263** [comment]
Trivy depends on [google/go-containerregistry](https://github.com/google/go-containerregistry). It looks like it supports only compress blobs for now.
https://github.com/google/go-containerregistry/blob/51f01e739161bf35d663240a8ca404777d7d9378/pkg/v1/layout/image.go#L102-L103

But your image seems to have uncompressed layers according to `unexpected media type: application/vnd.oci.image.layer.v1.tar for layer`.

Could you raise an issue in google/go-containerregistry? Also, if you provide how to create your image, I might be able to help.

**Comment by kitty-catt** [comment]
Hi Teppei, 

Thank you for your help. I discovered something more. I believe it is related to the redhat-openjdk-18/openjdk18-openshift. Can you confirm it?
![customer-image](https://user-images.githubusercontent.com/66872501/111073071-93f6dc80-84dd-11eb-9ae0-69dc7e86dac2.png)

I can raise a ticket with Redhat. I cannot say what exactly it is that needs to change.

The image was build via the following tekton [task](https://github.com/ibm-garage-ref-storefront/storefront-tekton/blob/master/tekton-tasks/appsody-build-push-v2.yaml). 

I ran various experiments with the --disable-compression flag today which did not succeed in the trivy scan running to completion. 

In the build logs I see:
`
[Buildah] STEP 1: FROM kabanero/ubi8-maven:0.10.2 AS compile
[Buildah] STEP 16: FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.8
[Buildah] STEP 27: COPY --chown=java_user:java_group --from=compile ${DEPENDENCY}/BOOT-INF/classes /app
[Buildah] STEP 31: COMMIT image-registry.openshift-image-registry.svc:5000/pipelines/customer
[Buildah] Getting image source signatures
[Buildah] Copying blob sha256:f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8
[Buildah] Copying blob sha256:58abc5089e711c65bb2c19c94de7e84971711b33a1728dc09c98bb3c0619ba9c
[Buildah] Copying blob sha256:370d3b28cd2a2a324b534b479047126d0794eae32f771e615c0b047cc604c6d9
[Buildah] Copying blob sha256:c20aa93ecd64568237afca515bf77faa549e86f71ef2e629d224e33194d7d112
[Buildah] Copying config sha256:c614ded41e5b926c802b3ec51f5340c6cfa36f6b26945b6acc04089ba63dd289

`
And in the trivy logs:
`
[FATAL [0m	error in image scan: failed analysis: analyze error: failed to analyze layer: sha256:370d3b28cd2a2a324b534b479047126d0794eae32f771e615c0b047cc604c6d9 : 
unable to get uncompressed layer sha256:370d3b28cd2a2a324b534b479047126d0794eae32f771e615c0b047cc604c6d9: 
failed to get the layer (sha256:370d3b28cd2a2a324b534b479047126d0794eae32f771e615c0b047cc604c6d9): unexpected media type: application/vnd.oci.image.layer.v1.tar for layer: sha256:6e3d88c9590ac9fa1c510a4ae36fed074d44c0b14442034d4ced9432e9cda277
`
Then I fetched the image using skopeo as a docker-archive:

$ tar -tvf customer.tar 
-r--r--r-- 0/0       215633920 1970-01-01 01:00 f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8.tar
-r--r--r-- 0/0           10240 1970-01-01 01:00 58abc5089e711c65bb2c19c94de7e84971711b33a1728dc09c98bb3c0619ba9c.tar
-r--r--r-- 0/0       281866240 1970-01-01 01:00 370d3b28cd2a2a324b534b479047126d0794eae32f771e615c0b047cc604c6d9.tar
-r--r--r-- 0/0        79306752 1970-01-01 01:00 bffd51919a5767b2da3c59424d69d51263e240f7e5d55a8af0406c1b9fb5c894.tar
-r--r--r-- 0/0            7917 1970-01-01 01:00 c614ded41e5b926c802b3ec51f5340c6cfa36f6b26945b6acc04089ba63dd289.json
l--------- 0/0               0 1970-01-01 01:00 f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8/layer.tar -> ../f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8.tar
-r--r--r-- 0/0               3 1970-01-01 01:00 f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8/VERSION
-r--r--r-- 0/0              73 1970-01-01 01:00 f91d01e7b88f8f9e151243e35e2b2af90dda72fc326330bfd5cb67e2c8491cf8/json
l--------- 0/0               0 1970-01-01 01:00 0a2c8934b40d6c07f375cfcfc29b98e5ac8174251216737bb409515797376de6/layer.tar -> ../58abc5089e711c65bb2c19c94de7e84971711b33a1728dc09c98bb3c0619ba9c.tar
-r--r--r-- 0/0               3 1970-01-01 01:00 0a2c8934b40d6c07f375cfcfc29b98e5ac8174251216737bb409515797376de6/VERSION
-r--r--r-- 0/0             149 1970-01-01 01:00 0a2c8934b40d6c07f375cfcfc29b98e5ac8174251216737bb409515797376de6/json
l--------- 0/0               0 1970-01-01 01:00 8fc46ef9d8eeab01bef5bab24a260ac16e97e8b44e90350b780bf52a8a00ca73/layer.tar -> ../370d3b28cd2a2a324b534b479047126d0794eae32f771e615c0b047cc604c6d9.tar
-r--r--r-- 0/0               3 1970-01-01 01:00 8fc46ef9d8eeab01bef5bab24a260ac16e97e8b44e90350b780bf52a8a00ca73/VERSION
-r--r--r-- 0/0             149 1970-01-01 01:00 8fc46ef9d8eeab01bef5bab24a260ac16e97e8b44e90350b780bf52a8a00ca73/json
l--------- 0/0               0 1970-01-01 01:00 fda33d53a491d6e31dd5c0581701e32fbff5ac59652ff1ac2bed97123980e149/layer.tar -> ../bffd51919a5767b2da3c59424d69d51263e240f7e5d55a8af0406c1b9fb5c894.tar
-r--r--r-- 0/0               3 1970-01-01 01:00 fda33d53a491d6e31dd5c0581701e32fbff5ac59652ff1ac2bed97123980e149/VERSION
-r--r--r-- 0/0            5594 1970-01-01 01:00 fda33d53a491d6e31dd5c0581701e32fbff5ac59652ff1ac2bed97123980e149/json
-r--r--r-- 0/0               2 1970-01-01 01:00 repositories
-r--r--r-- 0/0             393 1970-01-01 01:00 manifest.json`
`
When I open the 370d3b28cd2a2a324b534b479047126d0794eae32f771e615c0b047cc604c6d9.tar then I find a help text that starts with:

% redhat-openjdk-18/openjdk18-openshift (1) Container Image Pages

**Comment by kitty-catt** [comment]
Today I have scanned the openjdk18-openshift:1.8 image using trivy using the aforementioned Tekton task. 
It can scan it ... 
That narrows down the problem area.
