### ISSUE TITLE
How can I scan one or more specified directories through trivy?

### ISSUE THREAD

**Issue by imopro** [aquasecurity/trivy#890]
Hello：
How to scan one or more specified directories through trivy instead of all directories (/) in the system?
When I scan a 4tb system, it takes hours. Can you specify to scan certain directories, such as /usr/ bin and /usr/lib.

**Comment by knqyf263** [comment]
Are you talking about `trivy fs`? What kind of issues do you want to detect?

**Comment by imopro** [comment]
> Are you talking about `trivy fs`? What kind of issues do you want to detect?

yes.
When I execute trivy FS /bin, I have encountered such an error:
Trivy skips scanning programming language libraries because no supported file was detected
<img width="936" alt="1111" src="https://user-images.githubusercontent.com/56928503/111177432-2c2bb900-85e5-11eb-8fe0-3e5b9b38e0aa.png">

trivy fs /  is OK!
Only the whole system can be scanned.

**Comment by knqyf263** [comment]
You want to detect vulnerabilities of OS packages, right?

**Comment by imopro** [comment]
> You want to detect vulnerabilities of OS packages, right?

yes. But it takes a long time to scan the whole system (/) each time. So, I wonder if I can customize some specific directories to scan. How can I do that? Can I customize directory scanning?

thank you very much！

**Comment by knqyf263** [comment]
I see. This issue is relevant to https://github.com/aquasecurity/trivy/issues/766. Even if the `--skip-dirs` option is specified, Trivy will traverse all directories and filter those results for now. We probably should skip traversal itself.

**Comment by imopro** [comment]
> I see. This issue is relevant to #766. Even if the `--skip-dirs` option is specified, Trivy will traverse all directories and filter those results for now. We probably should skip traversal itself.

Yes. I hope this can be resolved soon. In the next version, you can actually skip the specified directory, or scan only the specified directory.

Thank you very much for your attention to this issue.

**Comment by vitalii-vm** [comment]
@imopro you wrote

> In the next version, you can actually skip the specified directory, or scan only the specified directory.

Did this request by chance get it to any release?

I am looking at 0.49 doc, and still don't see anything that helps to pick directories to scan (include rather than exclude with `--skip-dirs` )

**Comment by itaysk** [comment]
https://aquasecurity.github.io/trivy/v0.50/docs/configuration/skipping/

**Comment by vitalii-vm** [comment]
Hi @itaysk

Thanks, I can see the "skipping" part, but how do I **scan one or more specified directories**, is this part possible now ?

**Comment by itaysk** [comment]
no. you can specify just one directory to scan at a time
