### ISSUE TITLE
Does trivy FS / support JSON？

### ISSUE THREAD

**Issue by imopro** [aquasecurity/trivy#891]
# ./trivy fs / -f json -o 0315.json
2021-03-15T23:34:15.053+0800	ERROR	multiple targets cannot be specified
2021/03/15 23:34:15 failed to initialize options: arguments error

Does trivy FS / support JSON？

./trivy fs -f json -o 0315.json /  (is ok)

**Comment by knqyf263** [comment]
Yes, `./trivy fs -f json -o 0315.json /` should work.
