### ISSUE TITLE
Add gitlab codequality template

### ISSUE THREAD

**Issue by bmagistro** [aquasecurity/trivy#894]
We are using gitlab-ci but do not have the license to support the `container scanning` report.  Initially we explored the `junit` report format but did this shows as a series of failed tests.  For other projects (linting) we are using the codequality report which shows the found items with a severity and can perform a diff showing new and fixed items.

https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#code-quality-widget
See the speed run around T+3:10 for an example view in a merge request.
Screen shot: https://gitlab.com/gitlab-org/gitlab/-/issues/9014#note_525289446

**Comment by lmcojoshua** [comment]
I am very much looking forward to this. I was having to do some nasty stuff in later stages of my pipelines and this would clean things up nicely.
