### ISSUE TITLE
Helm chart release

### ISSUE THREAD

**Issue by krol3** [aquasecurity/trivy#900]
- Improve app chart release
- add to artifacthub.io

Related to comments on improvements in https://github.com/aquasecurity/trivy/issues/839

**Comment by Hokwang** [comment]
@krol3 how it going? trivy released new version 0.17.2 but chart did not affect.

**Comment by Hokwang** [comment]
@knqyf263 we need to upgrade helm chart version with trivy new release automatically. Please think of helm chart as artifact.

**Comment by knqyf263** [comment]
@krol3 ping

**Comment by krol3** [comment]
@Hokwang Sorry for the delay, difficult times these days. I created a PR to update the version of the image, as the next step, I will automate the chart release.
