### ISSUE TITLE
cache-dir option

### ISSUE THREAD

**Issue by faust64** [aquasecurity/trivy#907]
## Description

Trying to start trivy server with `--cache-dir /some/dir` option, as shown here: https://aquasecurity.github.io/trivy/latest/examples/cache/

Using Kubernetes, Pod args:

```
      containers:
      - args:
        - server
        - --cache-dir
        - /data
        - --listen
        - 0.0.0.0:8080
```

## What did you expect to happen?

trivy should start.

## What happened instead?

option is not recognized (error output below).
I could however set the `TRIVY_CACHE_DIR` environment variable, as it seems to be a valid alternative ( https://github.com/aquasecurity/trivy/blob/main/pkg/commands/app.go#L146 ). Startup output confirms it worked:

```
2021-03-20T22:25:59.708Z	DEBUG	cache dir:  /data
...
```

## Output of run with `-debug`:

```
Incorrect Usage: flag provided but not defined: -debug
```

Same goes with `--debug`.
Without `-debug`:

```
Incorrect Usage: flag provided but not defined: -cache-dir

NAME:
   trivy server - server mode

USAGE:
   trivy server [command options] [arguments...]

OPTIONS:
   --skip-update          skip db update (default: false) [$TRIVY_SKIP_UPDATE]
   --download-db-only     download/update vulnerability database but don't run a scan (default: false) [$TRIVY_DOWNLOAD_DB_ONLY]
   --reset                remove all caches and database (default: false) [$TRIVY_RESET]
   --cache-backend value  cache backend (e.g. redis://localhost:6379) (default: "fs") [$TRIVY_CACHE_BACKEND]
   --token value          for authentication [$TRIVY_TOKEN]
   --token-header value   specify a header name for token (default: "Trivy-Token") [$TRIVY_TOKEN_HEADER]
   --listen value         listen address (default: "localhost:4954") [$TRIVY_LISTEN]
   --help, -h             show help (default: false)
   
2021/03/20 22:19:48 flag provided but not defined: -cache-dir
```

Same goes with `-cache-dir /path/to/cache`.

## Output of `trivy -v`:

```
Version: 0.16.0
```

## Additional details (base image name, container registry info...):

```
image: docker.io/aquasec/trivy:0.16.0
```

**Comment by knqyf263** [comment]
`--debug` and `--cache-dir` are global flags. They need to be before subcommands.

```
        - --cache-dir
        - /data
        - server
        - --listen
        - 0.0.0.0:8080
```

**Comment by faust64** [comment]
Indeed, thanks for clarifying.
