### ISSUE TITLE
Trivy Fatal Error: ECR Image Scanning

### ISSUE THREAD

**Issue by ngowraj** [aquasecurity/trivy#923]
## Description
I am trying to run Trivy scan for a docker image that is stored in a private AWS ECR Registry. I have two successful scenarios and a failure scenario and would like to get some help to remediate this issue. 

### Successful
When I run Trivy scan locally for an ECR image with AWS credentials stored in ~/.aws/credentials it works.
```
trivy --debug --cache-dir /tmp/trivy/ image --vuln-type os --ignore-unfixed --severity MEDIUM,HIGH,CRITICAL -f json <image-url>
```
### Failure
I have dockerized my script and deployed as container image. When I run the same Trivy command from inside the container, it fails. 
```
2021-03-31T01:24:07.870Z	DEBUG	Severities: MEDIUM,HIGH,CRITICAL
2021-03-31T01:24:07.871Z	DEBUG	cache dir:  /tmp/trivy/
2021-03-31T01:24:07.871Z	INFO	Using your github token
2021-03-31T01:24:07.871Z	DEBUG	DB update was skipped because DB is the latest
2021-03-31T01:24:07.871Z	DEBUG	DB Schema: 1, Type: 1, UpdatedAt: 2021-03-31 00:13:23.858131211 +0000 UTC, NextUpdate: 2021-03-31 12:13:23.858130711 +0000 UTC, DownloadedAt: 2021-03-31 01:04:59.0504981 +0000 UTC
2021-03-31T01:24:08.298Z	FATAL	unable to initialize a scanner:
    github.com/aquasecurity/trivy/internal/artifact.run
        /home/circleci/project/internal/artifact/run.go:73
  - unable to initialize a docker scanner:
    github.com/aquasecurity/trivy/internal/artifact.dockerScanner
        /home/circleci/project/internal/artifact/image.go:28
  - 3 errors occurred:
	* unable to inspect the image (<image-url>): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* GET <image-url>/manifests/c28da7f: unsupported status code 401; body: Not Authorized
```
NOTE: There is no ~/.aws/credentials file inside the container. AWS creds inside the docker container are provisioned using kube2iam (https://github.com/jtblin/kube2iam).
I believe Trivy uses AWS SDK (https://aquasecurity.github.io/trivy/latest/private-registries/ecr/) and hence I believe this should work since "when using the aws-sdk, a call is made to the EC2 metadata API which provides temporary credentials that are then used to make calls to the AWS service"

### Another Successful Scenario
When mounting local ~/.aws/credentials file to the docker and running Trivy scan it works. 
```
docker run -v /Users/ng/.aws/:/home/../.aws -it --rm <image-url> bash
```

## What did you expect to happen?
I expect Trivy to successfully run insider the docker container and return output. It works locally and also when mounting the ~/.aws/credentials file but not when run inside the container (using the metadata API to return creds)

The permissions for the AWS role has been checked and it has admin credentials (more than what is needed).

## What happened instead?
Scan Failed.

## Output of run with `-debug`:
```
2021-03-31T01:24:08.298Z	FATAL	unable to initialize a scanner:
    github.com/aquasecurity/trivy/internal/artifact.run
        /home/circleci/project/internal/artifact/run.go:73
  - unable to initialize a docker scanner:
    github.com/aquasecurity/trivy/internal/artifact.dockerScanner
        /home/circleci/project/internal/artifact/image.go:28
  - 3 errors occurred:
	* unable to inspect the image (<image-url>): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* GET <image-url>/manifests/c28da7f: unsupported status code 401; body: Not Authorized
```

## Output of `trivy -v`:
```
Version: 0.16.0
```

## Additional details (base image name, container registry info...):
From inside the container, I am able to scan public images like,
```
trivy --debug --cache-dir /tmp/trivy/ image --vuln-type os --ignore-unfixed --severity MEDIUM,HIGH,CRITICAL -f json ubuntu:18.04
```

```
trivy --debug --cache-dir /tmp/trivy/ image --vuln-type os --ignore-unfixed --severity MEDIUM,HIGH,CRITICAL -f json python:3
```

Its only the ECR Images that are fails. Format: {aws-account-id}.dkr.ecr.us-west-2.amazonaws.com/{repo-name}:{repo-tag}

Similar to https://github.com/aquasecurity/trivy/issues/478

**Comment by knqyf263** [comment]
Looks IMDS doesn't work. Does the following command work in the container?

```
curl http://169.254.169.254/latest/meta-data/iam/security-credentials/role_name
```

Or

```
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" –v http://169.254.169.254/latest/meta-data/iam/security-credentials/role_name
```
