### ISSUE TITLE
How to return docker run image trivy as output file json

### ISSUE THREAD

**Issue by nurulakbartanjung** [aquasecurity/trivy#924]
docker run -i -t aquasec/trivy 
How to run docker trivy with return file json output result scanning vulnabirity?

**Comment by knqyf263** [comment]
See the document.
https://aquasecurity.github.io/trivy/latest/examples/report/#json

Just output to the mounted directory.

```
docker run -it -v $PWD:/result aquasec/trivy -f json -o /result/results.json alpine:3.12
```

Let me close this issue since it is a duplicate of https://github.com/aquasecurity/trivy/issues/889.
