### ISSUE TITLE
Use trivyignore from within Docker-Image

### ISSUE THREAD

**Issue by strowi** [aquasecurity/trivy#925]
Hi,

we recently stumbled upon the problem that teams were building Images, and scanning taking place somewhere else Or think of 1 Ops-Team providing base-images, other teams using those in Dockerfile's `FROM`.

Wouldn't it be useful if trivy could use a `.trivyignore` that is contained within the Docker-Image? And people using that image could extend the file?

Maybe make this an option so users can choose if they want to use the contained .trivyignore.

regards,
strowi

**Comment by knqyf263** [comment]
You want to exclude vulnerabilities from base images, right?

**Comment by strowi** [comment]
@knqyf263 Not exactly.. More like the actual image. My specific use-case is checking ALL images in production with a cronjob. Therefore i don't have a `.trivyignore` present for every image (those are in the specific repositories).

So i thought if the Team added their `.trivyignore` to the Docker-Image this would really be helpful.
