### ISSUE TITLE
Failed Scanning 

### ISSUE THREAD

**Issue by nurulakbartanjung** [aquasecurity/trivy#929]
![image](https://user-images.githubusercontent.com/33213081/113267368-7a88c980-9300-11eb-8efb-2a10e436747a.png)

>docker run -v cd:/result aquasec/trivy -d -f json -o /result/results.json nurulakbartanjung/hoover

i just run this command on windows 10 error result

**Comment by krol3** [comment]
@nurulakbartanjung  trivy doesnt support windows actually. See the [releases](https://github.com/aquasecurity/trivy/releases)

**Comment by simar7** [comment]
Maybe we can add a runtime check to show a little helpful message to the user about the lack of Windows support if they try to run it on Windows. Thoughts @knqyf263?

**Comment by knqyf263** [comment]
It runs the docker image. The platform on which it runs appears to be irrelevant.

@nurulakbartanjung Could you try `--timeout 10m`?
