### ISSUE TITLE
feature request: junit output

### ISSUE THREAD

**Issue by scbunn** [aquasecurity/trivy#93]
As I'm looking into integrating this into my CI pipelines, I'm looking for a way to present the findings to the user without having to troll the build logs.  One mechanism that I was thinking about was to present this to a job as tests.  Since most ecosystems support junit that seems like it would makes sense.

**Comment by knqyf263** [comment]
@scbunn Thank you for the suggestion. I didn't know that most ecosystems support junit xml.
I would like to support junit xml. 

However, I have a lot of tasks currently. If someone is interested in this feature, please implement it.

**Comment by jeff-cook** [comment]
This would be great to have.

**Comment by strowi** [comment]
I would very much like the feature, since all our other ci-tests already support junit.

**Comment by jeff-cook** [comment]
I'm working on a template for junit.xml format. First time working with Go and Go templates. The gitlab.tpl is very helpful. 

Any recommendation how to print an item and remove all double quotes?

**Comment by knqyf263** [comment]
@jeff-cook It's really helpful! I'm not sure exactly what you need, but the function might be useful.
https://golang.org/pkg/text/template/#example_Template_func

**Comment by rahul2393** [comment]
I am working on this issue, will create PR shortly

**Comment by knqyf263** [comment]
Trivy has supported JUnit output. It can be used in the next release. Thank you, @rahul2393.
https://github.com/aquasecurity/trivy#save-the-results-using-a-template

![image](https://user-images.githubusercontent.com/2253692/85738817-fcf8b300-b708-11ea-8197-e448b64c5f56.png)

**Comment by knqyf263** [comment]
I released v0.9.2 including this feature.
https://github.com/aquasecurity/trivy/releases/tag/v0.9.2
