### ISSUE TITLE
multiple targets cannot be specified in --skip-dirs options

### ISSUE THREAD

**Issue by carlosjpr-collab** [aquasecurity/trivy#934]
## Description
I tried  to do:
 `trivy -debug i --skip-dirs [/usr/share/rvm/rubies, /lib]`

## What did you expect to happen?
trivy skip scan the indicated dirs

## What happened instead?
trivy shows me an error

## Output of run with `-debug`:

```
2021-04-09T10:19:44.472+0200	ERROR	multiple targets cannot be specified
2021/04/09 10:19:44 failed to initialize options: arguments error
```

## Output of `trivy -v`:

```
Version: 0.16.0
```

**Comment by knqyf263** [comment]
It is comma-separated now.

```
trivy -debug i --skip-dirs /usr/share/rvm/rubies,/lib
```

Note that it will change in the next version as follows.

```
trivy -debug i --skip-dirs /usr/share/rvm/rubies --skip-dirs /lib
```
