### ISSUE TITLE
Trivy reports Alpine 3.13.4 as "no longer supported by the distribution"

### ISSUE THREAD

**Issue by thiago-gitlab** [aquasecurity/trivy#936]
## Description

When scanning `registry.gitlab.com/gitlab-org/release-cli:edge`, the following is printed to the job output:

```
[INFO] [Trivy] [2021-04-09 02:01:24 +0000] []  ▶  Running trivy with: trivy i --skip-update --vuln-type os --no-progress --format template -t @/usr/local/bundle/gems/gcs-0.1.0/lib/gitlab.tpl -o tmp.json registry.gitlab.com/gitlab-org/release-cli:edge
[INFO] [Trivy] [2021-04-09 02:01:24 +0000] []  ▶  trivy i --skip-update --vuln-type os --no-progress --format template -t @/usr/local/bundle/gems/gcs-0.1.0/lib/gitlab.tpl -o tmp.json registry.gitlab.com/gitlab-org/release-cli:edge
[INFO] [Trivy] [2021-04-09 02:01:25 +0000] []  ▶  2021-04-09T02:01:25.801Z	WARN	This OS version is not on the EOL list: alpine 3.13
2021-04-09T02:01:25.801Z	INFO	Detecting Alpine vulnerabilities...
2021-04-09T02:01:25.802Z	WARN	This OS version is no longer supported by the distribution: alpine 3.13.4
2021-04-09T02:01:25.802Z	WARN	The vulnerability detection may be insufficient because security updates are not provided
```

The message "This OS version is no longer supported by the distribution: alpine 3.13.4" seems incorrect, given that 3.13.4 is the latest version of alpine.

## What did you expect to happen?

The WARN messages about alpine version to not be displayed.

## What happened instead?

Warnings were displayed.

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
(paste your output here)
```

## Additional details (base image name, container registry info...):

GitLab job: https://gitlab.com/gitlab-org/release-cli/-/jobs/1164906227#L22

**Comment by knqyf263** [comment]
@thiago-gitlab Thanks for filing an issue. It will be fixed in the next release.
https://github.com/aquasecurity/trivy/pull/819

**Comment by thiago-gitlab** [comment]
Than you and apologies for the duplicate issue. It looks like the message means Trivy doesn't support Alpine 3.13 when I thought it meant version 3.13 was no longer supported by Alpine. Or maybe they're two separate warnings and I got them confused.

**Comment by knqyf263** [comment]
Oh, I'm sorry I was also confused. v0.16.0 already fixed it. Which version are you using? If v0.16.0 still shows the warning, there is something wrong.
https://github.com/aquasecurity/trivy/releases/tag/v0.16.0

**Comment by knqyf263** [comment]
As you said, the message is a bit confusing. We'll fix it.

**Comment by thiago-gitlab** [comment]
Ah, we're on 0.15.0: https://gitlab.com/gitlab-org/security-products/analyzers/container-scanning/-/blob/master/Dockerfile#L2

I'll create an issue to upgrade. Thanks again!

**Comment by knqyf263** [comment]
It makes sense. Thanks for your confirmation!
