### ISSUE TITLE
FEAT: As a user, I expect the docker image to be rebuild everday

### ISSUE THREAD

**Issue by pascalandy** [aquasecurity/trivy#94]
The latest image on docker hub is from 11 days ago.

1. **Best practice** — I don't think it's acceptable for a scanner docker image.
2. **Updates** — This will have the positive effect that we can use `--skip-update` more confidently. 

![Screen Shot 2019-07-22 at 8 26 34 AM](https://user-images.githubusercontent.com/6694151/61632455-e32e3080-ac5a-11e9-951d-8ec17b337091.jpg)

I could help if you would like to set up a CI on Travis CI.

Cheers!

**Comment by knqyf263** [comment]
@pascalandy Thank you for the report. The container image of Trivy on Docker Hub does not include vulnerability information. Even if we build this image every day, you need to update the vulnerability information. This means you cannot skip update by using `--skip-update` when using the latest image of Trivy. 

Please use `--skip-update`, for example, after you have already updated the vulnerability information right before.

**Comment by pascalandy** [comment]
Ok, I assume the vulnerability information were in the image. 

I still expect this kind of project to rebuild every day. As you use circle CI, this is one click away :)

**Comment by lizrice** [comment]
I disagree with the premise that a project should be shipping a new master release on a daily basis. It’s not necessarily just a click away - you can end up chasing down dependency issues even if the project source hasn’t changed. I’m not saying that  a bad thing, but I am saying it is a choice for the maintainers of a project, and there are plenty of projects that don’t operate that way.

**Comment by pascalandy** [comment]
I agree about:

> you can end up chasing down dependency issues even if the project source hasn’t changed.

That's why the builds must be well tagged. My suggestion:

```
aquasecurity/trivy:0.15_2019-08-28_23H00s21_319a5f3 
```

This is how I do it on https://github.com/firepress-org/rclone-in-docker
Thanks to Github action this is now easy to do. 

I'll be glad to PR if @knqyf263 agrees that this is best practice.

**Comment by christian-weiss** [comment]
Re-building of releases (re-using of existing "version strings") is bad practice in a docker ecosystem.
Disagree with your example.

Only for `latest` there is a common exception to this rule. It is commonly accepted that `latest` will change over time. Disagree with your naming convention.

Re-building `latest` e.g. every day is a good thing to catch problems in downstream dependencies. But only if you have tests that can spot problems. In the end there is no need to release the build artifact as a new `latest` release. On success everything for next release is "cool". On failure the developer knows that he need to update some dependencies before doing the next release. So it is more a "pre-flight"  job.

**Comment by pascalandy** [comment]
regarding release best practices (from https://goreleaser.com/docker/)

![Screen Shot 2020-01-28 at 9 24 57 AM](https://user-images.githubusercontent.com/6694151/73272265-17f1e600-41b0-11ea-8e9f-4f9311feff65.jpg)

**Comment by daniela-waranie** [comment]
This is a practice, but for sure not a "best practice" - not for docker and not for general purposes.

Please read for example Jess Humbles Continuous Delivery for Build Patterns, Release Patterns and proper Dependency Management: https://www.amazon.de/Continuous-Delivery-Deployment-Automation-Addison-Wesley/dp/0321601912

- re-using a release tag for "changed content" is a bad practice
- re-building the same release 1000x is ok (as it should be reproducable), but a re-build artifact should  nearly never released under an already existing release tag (to avoid replacing a previous build artifact by the new re-build one). There are really raw amount of situations where you want to re-release: be aware of changed file timestamps, as it could produce problems downstream, even if the content is still the same)

A release is an release - independent from the targeted audience (developers, alpha-testers, stable-users). A "official" release and a "technical" release (just for testing, etc.) - both are releases from the point of view of a dependency manager (human or software). Unstable release could be tagged with e.g. v1.6.4-RC1, v1.6.4-RC2, etc.

If your project has a dependency to an upstream docker image (lets say: v1.6.4) you should point your project file (e.g. Dockerfile FROM to v1.6.4). If weeks later 1.6.5 will be release then you had to change that version number in your Dockerfile, to ensure your commit / project-builds are reproducable at any point in time in the future. 

Subsequent builds should always produce the same content for that commit, as if it was build the very first time for that commit. "latest" or a "changing v1" or a "changing v1.6" would break this rule. Try to avoid using such "content-changing release tags".

If you want to catch a new release without changing a file in your project manually, then your build process or a local script should emulate a dependency constraint/patter evaluation, and commit/push the updated Dockerfile (with evaluated concrete version number). At this point in time Docker ecosystem has no "Dependency Manager" that evaluates "dependency constraints" (like "1.6.*" or ">=1.6; <1.7") and which updates the Dockerfile directly with a concrete version number or has a *.lock file like in many other Dependency Managers. So at this moment you have to do it manually or have a script which does it for you. 

Re-building and re-releaseing docker images (same release tag, but changed content) is NOT the solution for that! You should not ask a vendor to do that bad practice or do it in your project.

**Comment by angelbarrera92** [comment]
We are doing it here: https://github.com/sighupio/trivy-offline

**Comment by pascalandy** [comment]
Exactly what I was looking for @angelbarrera92
