### ISSUE TITLE
Old version of Trivy is reporting vulnerabilities that latest trivy is not reporting.

### ISSUE THREAD

**Issue by adammfrank** [aquasecurity/trivy#941]
On our CI server we are running trivy version 0.5.0. Currently, when I run it against a freshly built image during CI, it shows 3 high level vulnerabilities. When I run trivy locally with version 0.16.0 against the image that was just created in CI it reports 0 high vulnerabilities. 

We can certainly upgrade trivy on the CI server, but I'm wary of hiding the vulnerabilities in this way. Why would the old version find vulnerabilities that the new one doesn't? Shouldn't they be checking the same CVE database?

**Comment by adammfrank** [comment]
Turns out the vulnerabilities that 0.5.0 was detecting are very real. I don't know why 0.16.0 is not detecting them.

**Comment by knqyf263** [comment]
Trivy used to use severities from NVD, but switched to use severities from vendors such as Red Hat in the later version. The NVD severity is a general one, while the vendor severity is for the distribution. It improves accuracy. I'm guessing that's why the vulnerabilities are not reported with high severitiy.

**Comment by tspearconquest** [comment]
This sounds right. If you are basing your image on a well known public image like ubuntu, the image vendor may have a lower severity due to custom patches which might partially mitigate the issue in their code, thus making it a lower severity for that OS release.

**Comment by adammfrank** [comment]
Thanks for explaining. I'll close.
