### ISSUE TITLE
traviy and AWS ECR: failed to initialize options: invalid image: could not parse reference

### ISSUE THREAD

**Issue by carlosjpr-collab** [aquasecurity/trivy#945]
I am trying to do a security scan using trivy 

I am using this bash code to scan all ECR images
  
    for e in $(aws ecr describe-repositories | jq '.[] | .[] | .repositoryUri') ; do (trivy i $e) ; done

The PB is that i have this error 

     failed to initialize options: invalid image: could not parse reference

but when i do the commande alone:

    trivy i (the repositoryUri of the image )

This works without probleme.

**Comment by knqyf263** [comment]
You have to eliminate quotes. Try

```
for e in $(aws ecr describe-repositories | jq -r '.[] | .[] | .repositoryUri') ; do (trivy i $e) ; done
```
