### ISSUE TITLE
 trivy say that i have an old vuln in rails gem 

### ISSUE THREAD

**Issue by carlosjpr-collab** [aquasecurity/trivy#952]
I have this bug where trivy say that i have an old vuln. I searched in google and normaly, this vuln not exist in version 4.0.2 of this gem.

![image](https://user-images.githubusercontent.com/38086105/116048913-fbc04b80-a675-11eb-8a8e-c4a0ae033158.png)

## Output of `trivy -v`:

```
0.16
```

**Comment by jmortlock** [comment]
We also have the same issue listed in a Rails 6.1 project

**Comment by knqyf263** [comment]
Could you give me your Gemfile.lock?

**Comment by jmortlock** [comment]
[Gemfile.lock.txt](https://github.com/aquasecurity/trivy/files/6412364/Gemfile.lock.txt)

Here is a Gemfile.lock that has the problem (Rails 6.1 API only project)
