### ISSUE TITLE
Build fail not working in azure devops

### ISSUE THREAD

**Issue by basavarajb** [aquasecurity/trivy#953]
Build is not failing even image containing vulnerability and it is not outputting the .xml 

- script: |
      echo $(Build.ArtifactStagingDirectory)
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/root/.cache/ aquasec/trivy:0.16.0 --exit-code 0  --cache-dir .trivycache/ --severity="MEDIUM,HIGH" --format template --template "@contrib/junit.tpl" -o $(Build.ArtifactStagingDirectory)/junit-report-low-med.xml --ignore-unfixed image kumarbiradar7/shopingcart:20210424.24 
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/root/.cache/ aquasec/trivy:0.16.0 --exit-code 1 --cache-dir .trivycache/ --severity="CRITICAL" --format template --template "@contrib/junit.tpl" -o $(Build.ArtifactStagingDirectory)/junit-report-crit.xml --ignore-unfixed image XXXXX/shopingcart:20210424.24 
    displayName: Trivy Security Scan  
  - task: PublishTestResults@2
    inputs:
      searchFolder: '$(Build.SourcesDirectory)'
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit-report-low-med.xml'
      mergeTestResults: true
      failTaskOnFailedTests: false
      testRunTitle: 'Trivy - Low and Medium Vulnerabilities'
    condition: 'always()'   

  - task: PublishTestResults@2
    inputs:
      searchFolder: '$(Build.SourcesDirectory)'
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit-report-high-crit.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'Trivy - High and Critical Vulnerabilities'
    condition: 'always()'

**Comment by rahul2393** [comment]
Please follow this
https://aquasecurity.github.io/trivy/latest/examples/others/
