### ISSUE TITLE
Cannot scan distroless images

### ISSUE THREAD

**Issue by atbentley** [aquasecurity/trivy#96]
**Description**

Trivy cannot scan distroless docker images.

**What did you expect to happen?**

Trivy would be able to scan the distroless image for vulnerabilities

**What happened instead?**

Trivy failed with an unexpected error

**Output of run with `-debug`:**

```
trivy --debug gcr.io/distroless/java:11
2019-07-24T13:30:13.936+0200	DEBUG	cache dir:  /Users/andrew/Library/Caches/trivy
2019-07-24T13:30:13.936+0200	DEBUG	db path: /Users/andrew/Library/Caches/trivy/db/trivy.db
2019-07-24T13:30:13.939+0200	INFO	Updating vulnerability database...
2019-07-24T13:30:13.939+0200	DEBUG	git pull
2019-07-24T13:30:15.077+0200	DEBUG	total updated files: 1
2019-07-24T13:30:15.107+0200	DEBUG	Vulnerability type:  [os library]
2019-07-24T13:30:15.196+0200	DEBUG	OS family: debian, OS version: 9.9
2019-07-24T13:30:15.196+0200	FATAL	error in image scan:
    github.com/knqyf263/trivy/pkg.Run
        /root/project/pkg/run.go:166
  - failed to scan image:
    github.com/knqyf263/trivy/pkg/scanner.ScanImage
        /root/project/pkg/scanner/scan.go:54
  - failed to analyze OS packages:
    github.com/knqyf263/trivy/pkg/scanner/ospkg.Scan
        /root/project/pkg/scanner/ospkg/scan.go:51
  - Failed to analyze packages:
    github.com/knqyf263/fanal/analyzer.init.ializers
        /go/pkg/mod/github.com/knqyf263/fanal@v0.0.0-20190706175150-0e953d070757/analyzer/analyzer.go:27
```

**Output of `trivy -v`:**

```
trivy version 0.1.4
```

**Additional details (base image name, container registry info...):**

Google publishes "distroless" docker images that are very slim and only contain packages critical to your runtime. See https://github.com/GoogleContainerTools/distroless

These images don't contain much, but they do still contain glibc, openssl, libssl, etc.

I briefy tried the nodejs image and the java11 image, both failed for the same reason

**Comment by knqyf263** [comment]
Now, Trivy can scan distroless🎉  Thank you, @atbentley @tomoyamachi

**Comment by atbentley** [comment]
Thanks for the work @knqyf263 and @tomoyamachi! I can confirm it is working perfectly 🙂

**Comment by avthart** [comment]
Thanks! I was also expecting the same issue with using distroless.

**Comment by thabach** [comment]
I don't see it working on `trivy version 0.1.6`. On trying to scan Google's distroless base image `gcr.io/distroless/base:latest`I get 
<img width="1024" alt="Screenshot 2019-10-04 at 22 19 10" src="https://user-images.githubusercontent.com/3873324/66237303-0f533c80-e6f5-11e9-8147-9256483c1dca.png">
I must be doing something wrong, please advise.

**Comment by knqyf263** [comment]
v0.1.6 doesn't support distroless. You need to wait for v0.1.7.

**Comment by thabach** [comment]
... or can I build from source myself and see it work today 💯 ?

**Comment by knqyf263** [comment]
Exactly. I'm going to release a new version shortly.

**Comment by thabach** [comment]
Just built it locally on my Mac 
<img width="851" alt="Screenshot 2019-10-04 at 22 51 39" src="https://user-images.githubusercontent.com/3873324/66239247-a7ebbb80-e6f9-11e9-8bd2-fde66b39c3b1.png">
and works like a charm - awesome work - very nice !

**Comment by abdennour** [comment]
scanning distroless-based images is working. However, I noticed that it has critical issues thou it's distroless.
I noticed also that detected vulnerabilities are similar to screenshot posted by @thabach above.
I wonder is it really have all these critical issues

![image](https://user-images.githubusercontent.com/1788384/105065784-4aff4a80-5a8f-11eb-8c84-e0f4d998632d.png)
