### ISSUE TITLE
Docs: Link to trivy vulnerability explorer

### ISSUE THREAD

**Issue by Morl99** [aquasecurity/trivy#967]
Hello,

I wanted to bring a small project to your attention, that might be useful for your users. As a heavy trivy user, I felt the need to explore arbitrary trivy reports. We use trivy in our CI pipelines, and they produce a JSON report. So here it is, the Trivy Vulnerability Explorer (yeah, not the most creative name ;)): https://dbsystel.github.io/trivy-vulnerability-explorer/

I would even add a link to this in your docs myself, but I could not find a suitable place. Maybe it would be time to start a third-party page, or something along the lines. 

Let me know if you have any questions. And thanks for the hard work that is put into this project, we at DB really appreciate it.

**Comment by Morl99** [comment]
@knqyf263 are you interested in adding a link to the vulnerability explorer? If not, we could close this issue.

**Comment by Morl99** [comment]
I am sure you are busy, but maybe you could give me a quick sign if this is something you are interested in. If not we can close this issue. If yes, feel free to point me to the right spot and I will add something to the docs.

Appreciate all your work on trivy @knqyf263!

**Comment by knqyf263** [comment]
I'm sorry I missed it. We don't have a place to link the URL of external tools because it is difficult to maintain it by us. But thank you for your suggestion.

**Comment by Morl99** [comment]
No worries, and thanks for the feedback. In that case, I am closing this issue.

**Comment by knqyf263** [comment]
Hi @Morl99, we eventually decided to manage the community tools in our doc. Please feel free to give us any feedback.

**Comment by Morl99** [comment]
That is great. To be clear: Did you already include it in the docs, or are you planning to so? Let me know if I can be of help.

**Comment by knqyf263** [comment]
You can see the above PR. It is not yet merged, but will be soon.

**Comment by Morl99** [comment]
Ah thanks, the GitHub mobile app collapsed it, so I overlooked it!
