### ISSUE TITLE
Trivy scan fails in Client server mode with error error in image scan: failed analysis: analyze error: failed to store layer:

### ISSUE THREAD

**Issue by akshay654** [aquasecurity/trivy#979]
Description

I am using trivy in client server mode and i have integrated it with gitlab CI to run a security scan stage which runs after Build.
I tried to run the same commands from different server rather than on gitlab server but it gives the same error mentioned below.
The client scan command works fine when i run a scan using trivy client mode on same server where trivy server is running.

What did you expect to happen?

Reports to be returned.

What happened instead?

FATAL    error in image scan: failed analysis: analyze error: failed to store layer: sha256:64e81128280439694f575ee0aba02c5ad9b9098ede8218706f35551127e50f88 in cache: unable to store cache on the server: twirp error internal: unable to store layer info in cache: invalid diffID (sha256:64e81128280439694f575ee0aba02c5ad9b9098ede8218706f35551127e50f88/11111111111111111111111): found non-hex character in hash: /

Output of `trivy -v`:

0.16.0

**Comment by ko-harada** [comment]
@akshay654 I got same error. I updated the server version to the same as the client, and resolve the error. Might the server/client versions be different?

**Comment by akshay654** [comment]
@ko-harada - yes i matched the client server version and issue is fixed now, Thanks

Closing this issue.
