### ISSUE TITLE
Avoid network request during JAR scans

### ISSUE THREAD

**Issue by fawind** [aquasecurity/trivy#982]
Hey Trivy Team!

Great work on the 0.17 release! I am quite excited for some of the shipped features, especially the[ jar scanning](https://github.com/aquasecurity/trivy/pull/837)!

However I wanted to share some feedback about the network requests happening during jar scans as this has been blocking us from adopting this feature. Concretely, we have been running into the following issues:

1. ~~Scan durations for our java images have drastically increased from \~25sec to \~10mins. While iterating and parsing the jars adds extra overhead, I believe that a decent amount of time can be attributed to the additional network requests, especially for images containing a large number of jars.~~
    * Edit: The scan durations actually only increased from ~30sec to ~1min which seems okay. The very long scan times came actually from network requests timing out due to being in an air-gapped environment.
2. This does not work in air-gapped environments and also leaks internal jar names. This is unfortunate as most air-gapped environments also have some sort of vuln scanning requirements and could benefit from Trivy.

As I understood it, the requests are currently required to identify and check existence of derived maven identifiers to match entries in the advisory DB ([source](https://github.com/aquasecurity/go-dep-parser/blob/3c97ccc53976562d6011dd6b4517b9ef507ce83e/pkg/jar/parse.go#L150-L175)).

I am wondering if you are tracking any work to avoid these requests? For example, I could imagine using file hashes instead of maven IDs for matching jars with the vuln DB. I.e. we could "preprocess" the entries in the vuln DB to include hashes of the jars within the affected version range (maven-central already serves sha256 files so no need to download the actual jars for this). That way when scanning, we can lookup the hashes of the jars found in the image with the vuln DB and potentially don't have to do any network requests. 
I understand that this would make creating and updating the vuln DB quite expensive. However updates can be made incrementally only for newly released vulns and this would be a one-off cost vs continuous overhead at scan time.

**Comment by Xaseron** [comment]
We are facing the same problem. It breaks our air gapped CI/CD pipelines.

**Comment by zubcevic** [comment]
I am also facing the same problem. Even if you specify --vuln-type os , it will still try to connect to http://search.maven.org/solrsearch.... if it detected any jar in the container image. The option --vuln-type seems to effect the reporting part only.
Both the outgoing requests and information as well as the http protocol are undesired in financial/governmental enterprise environments. 
The OWASP dependency check is able to run in air-gapped mode. So maybe Trivy can get an improved air-gapped function, where you can e.g. use some Nexus, Artifactory intermediate/proxy to facilitate a controlled internet usage and prevent leaking information.
I have used Trivy 0.18.3

**Comment by mbreevoort** [comment]
Most annoying is of this issue that if there is nog connection to maven.org and `--vuln-type os` it gets very slow and a scan will timeout :-(
Please add a setting so it wouldn't go to the internet.

**Comment by CRogers** [comment]
This is really wrecking us as we do scans in air-gapped environments. We stopped upgrading the trivy binary to 0.17+ because of it, but now we're in a situation where we need to support alpine 3.14 so need at least 0.19.0, which puts us in a quandry.

Even an option to turn off jar scanning, or making it not do jar scans with `--vuln-type os`, would get out us of this sticky situation.

**Comment by dimon222** [comment]
Is there a way to still scan JARs but skip checking for existence on Maven?

**Comment by fawind** [comment]
Late follow-up: Just found out about the new [trivy-java-db](https://github.com/aquasecurity/trivy-java-db) ([docs](https://aquasecurity.github.io/trivy/v0.37/docs/advanced/air-gap/#download-the-java-index-database1)). Based on some initial testing, it does a pretty good job at finding JARs and associated CVEs while working offline. Thanks a bunch for adding, this is awesome! 🎉
