### ISSUE TITLE
does trivy use the NVD database? https://nvd.nist.gov/vuln

### ISSUE THREAD

**Issue by hari819** [aquasecurity/trivy#995]
hello ,

does trivy use the NVD database? https://nvd.nist.gov/vuln 
this database gets updates very fast , nearly 20 to 30 updates for a day ,
It is used as primary db in many of the scanning tools ,

does trivy use this database for scanning , is there a way we can point trivy  to use this database ?

Thanks,
Hari

**Comment by sateffen** [comment]
As far as I can see trivy downloads the data from [this repository](https://github.com/aquasecurity/trivy-db) releases, which use the sources mentioned in [this repository](https://github.com/aquasecurity/vuln-list). So yes, nvd.nist.gov should be included, but trivy-db is only rebuild every 12 hours, so it might lack behind a little.

**Comment by knqyf263** [comment]
Yes, Trivy uses NVD to display vulnerability details.

**Comment by tuxerrante** [comment]
> Yes, Trivy uses NVD to display vulnerability details.

Hi, is this referenced somewhere in the docs?
Searching for[ the data sources](https://aquasecurity.github.io/trivy/v0.49/docs/scanner/vulnerability/#data-sources) it seems Trivy look into the specific OSs registries, also in the [pkg/vulnsrc](https://github.com/aquasecurity/trivy-db/blob/db9bf07792afba73dceb20b99723c8af007da1f8/pkg/vulnsrc/nvd/nvd.go#L25) I see the NVD as the one of many sources. 
What if NVD stops publishing for a while? 
https://www.infosecurity-magazine.com/news/nist-vulnerability-database/

**Comment by knqyf263** [comment]
https://aquasecurity.github.io/trivy/v0.49/docs/scanner/vulnerability/#severity-selection
